### ISSUE TITLE
Adjacent # fmt: on+off treated as # fmt: on

### ISSUE THREAD

**Issue by llchan** [psf/black#1005]
Operating system: Linux
Python version: 3.7.4
*Black* version: ae5588cf073be10b51dc48ad2fc513e11c4f3e03 (current master)
Does also happen on master: yes

When blackening this code:
```
def foo():
    # fmt: off
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    # fmt: on

    # fmt: off
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0
    # fmt: on
```
it seems that the second `# fmt: off` is ignored and the second block is formatted.  If a statement (e.g. `pass`) is inserted in between the adjacent fmt directives, the formatting is left alone, so I think this only happens when `# fmt: on` is immediately followed by a `# fmt: off`.

**Comment by tigarmo** [comment]
I've also reproduced this on Windows 10/Black 19.3b0: [playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFNAHhdAD2IimZxl1N_Wg0-Ef3tYndKG4aPypy3FGjEBLxlRL9_75RXsRyiaeS2IVbA_2o4vO4n7lmMWgVj8hJ5SSt1BVifJKj4Vpz5C2A-xYPG6SsihaPvbT_yni2kYSgYAd99AJtnbtGiUm1vMYCU-jzhQpHpGM2_pHioUAD81HWiu4GiiwABlAHOAgAAY-TU7bHEZ_sCAAAAAARZWg==)

Input:
```python
# fmt: off
custom_formatting = [
    0,  1,  2,
    3,  4,  5,
    6,  7,  8,
]
# fmt: on

# fmt: off
custom_formatting = [
    0,  1,  2,
    3,  4,  5,
    6,  7,  8,
]
# fmt: on
regular_formatting = [
    0,  1,  2,
    3,  4,  5,
    6,  7,  8,
]
```

Output:
```python
# fmt: off
custom_formatting = [
    0,  1,  2,
    3,  4,  5,
    6,  7,  8,
]
# fmt: on

# fmt: off
custom_formatting = [0, 1, 2, 3, 4, 5, 6, 7, 8]
# fmt: on
regular_formatting = [0, 1, 2, 3, 4, 5, 6, 7, 8]
```

For us, the use case for consecutive `fmt` statements like that is auto-generated code (with cogapp).
