### ISSUE TITLE
Black sometimes adds two newlines at the end of file and doesn't remove it by itself on reformatting

### ISSUE THREAD

**Issue by Kushagra-0801** [psf/black#1006]
Operating System: `Ubuntu 19.04`
Python version: `3.7.4`
Black version: `19.3b0`
Editor: `VS Code (snap)`
Happens on the branch installed by pip
Black sometimes adds an extra newline at the end of the file (mostly when there already is a newline there, I think). The newline is not removed on reformatting. Once I remove it, it doesn't happen again.
It doesn't happen a lot so I haven't seen any clear pattern to it.

**Comment by JelleZijlstra** [comment]
Could you give an example that reproduces this bug?

I wonder if this could be a bug in your editor integration or IDE.

**Comment by ichard26** [comment]
This is most likely a bug with Visual Studio Code Python extension's diff handling. The duplicate issue of this issue has linked this: https://github.com/microsoft/vscode-python/issues/11001.

**Comment by JelleZijlstra** [comment]
Seems unlikely that this is a bug in Black. Closing in favor of the VSCode issue.
