### ISSUE TITLE
blackd has no API to get server version

### ISSUE THREAD

**Issue by jacobbogdanov** [psf/black#1013]
I am working on a client to `blackd` and would like to be able to get the version of the `blackd` server from the http endpoint.

This is for the same use-case that `black` itself has; disk caching of already formatted files. It would be advantageous to be able to check the cache and avoid the network IO.
Whether there is a new API endpoint, `/version`, or the response to each POST contains a header containing the server version should be equivalent for this particular use-case

Operating system: macOS
Python version: `python3.6`
*Black* version: `blackd, version 19.3b0`
Does also happen on master: as far as I can tell from the source code

**Comment by linusg** [comment]
> I'd be happy to review a PR :)

@zsol please see https://github.com/psf/black/pull/1046 :)
