### ISSUE TITLE
Enhancement request: option to specify whether # is followed by space

### ISSUE THREAD

**Issue by edreamleo** [psf/black#1014]
I am the author of [Leo](http://leoeditor.com/). At present, black inserts a blank between "#" and "@".  Alas, this seriously interferes with Leo's 20-year-old format for sentinel comments.

[This post](https://groups.google.com/d/msg/leo-editor/DiM0fQyztr0/NifPH7oDFQAJ) discusses all the gory details.  The take-away is that Leo has is *no* good solution to the problem.

Happily, there is a dead easy patch:  In make_comment, change:
```python
if content and content[0] not in " !:#'%":
    content = " " + content
```
to:
```python
if content and content[0] not in " @!:#'%": # EKR: This string would better be an option.
    content = " " + content
```
Better, the option could be a regex, specifying the exact exceptions.

I hope you will consider adding such an option. Even a non-regex option would make a big difference.

Edward

P.S. For Leo, the regex would be the union of the following :-)
``` python
ref = g.angleBrackets(r'(.*)') # Yields << \1 >>, which is special Leo syntax.
delim1, delim2 = '#', ''
patterns = (
    # These patterns must be mutually exclusive.
    fr'^\s*{delim1}@afterref{delim2}$',             # @afterref
    fr'^(\s*){delim1}@(\+|-)all\b(.*){delim2}$',    # @all
    fr'^\s*{delim1}@@c(ode)?{delim2}$',             # @c and @code
    fr'^\s*{delim1}@comment(.*){delim2}',           # @comment
    fr'^\s*{delim1}@delims(.*){delim2}',            # @delims
    fr'^\s*{delim1}@\+(at|doc)?(\s.*?)?{delim2}\n', # @doc or @
    fr'^\s*{delim1}@end_raw\s*{delim2}',            # @end_raw
    fr'^\s*{delim1}@@first{delim2}$',               # @first
    fr'^\s*{delim1}@@last{delim2}$',                # @last
    fr'^(\s*){delim1}@\+node:([^:]+): \*(\d+)?(\*?) (.*){delim2}$', # @node
    fr'^(\s*){delim1}@(\+|-)others\b(.*){delim2}$', # @others
    fr'^\s*{delim1}@raw(.*){delim2}',               # @raw
    fr'^(\s*){delim1}@(\+|-){ref}\s*{delim2}$'      # section ref
)
```
EKR

**Comment by JelleZijlstra** [comment]
Related: #960

**Comment by JelleZijlstra** [comment]
Let's take a decision in #3668.

**Comment by edreamleo** [comment]
@JelleZijlstra I agree that none of the options discussed in #3668 are perfect. Most projects should be able to find a way of living with Black's formatting of comments. For example:
- Leo has long been able to *read* blackened sentinel comments.
- Leo's newish `--black-sentinels` command-line option causes Leo to *write* black-compatible sentinel comments
