### ISSUE TITLE
Black's behavior with comments is not described in the style guide

### ISSUE THREAD

**Issue by kylrth** [psf/black#1017]
I had to go to #208 to finally find out that Black does not reformat comments. I shouldn't have to find a GitHub conversation from 2018 to find out how Black handles comments.

An explanation should be added to the readme.

**Comment by ichard26** [comment]
Given how warmly received this has been by the community, I would definitely accept a patch for this!

Thanks for the suggestion!

p.s. info about how some comments get special treatment, may be moved where linters then get mad, etc. (i.e. the edge cases) should definitely be included
