### ISSUE TITLE
Major indentation failure when `# fmt: off` falls out of scope

### ISSUE THREAD

**Issue by rwarren** [psf/black#1019]
**Black v19.3b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB0AFRdAD2IimZxl1N_WlbvK5V8VC25920rAZ8u-PGWNSmMwU50CYbpOC67RE5dT69p2ZcqGOU9LP8vHsBiEq_0g7YXaEM4EphTh_vyzcPh2TgOZ5-e8WfQ_wAyQ6bKlancygABcHVuSdYvH7bzfQEAAAAABFla)

## Options

`--line-length=89`

## Input

```python
def bar():
    # fmt: off
    x=1

y=2

```

## Output

```python
def bar():
    # fmt: off
    x=1

    y = 2

```

## Expected
```
def bar():
    # fmt: off
    x=1

y = 2

```

This seems somewhat related to #884, but this is a concise case.

This is a major bug since it actually changes the resulting code _significantly_.

**Comment by rwarren** [comment]
In case it wasn't obvious, the problem is that the `y = 2` line got moved into the function (!!).

**Comment by zsol** [comment]
This seems like the same case as #569, let's keep the discussion there
