### ISSUE TITLE
How to not place arguments on their own line?

### ISSUE THREAD

**Issue by mattdonders** [psf/black#1022]
Is there some way to tell Black to fit as many variables passed into a function on a single line as opposed to putting each argument on their own line (besides using `# fmt: off` & `# fmt: on` keywords)?

Sample Code - 
```
# Desired Output
center_text(
    draw=draw, left=0, top=540, width=bg_w,
    text=game.venue.upper(), color=Colors.WHITE, font=FONT_DETAIL_LARGE,
)

# Black Formatted Output
center_text(
    draw=draw,
    left=0,
    top=600,
    width=bg_w,
    text=text_hashtags,
    color=Colors.WHITE,
    font=FONT_DETAIL_SMALL,
)
```

----

Operating system:
Python version: 3.6.5
*Black* version: 19.3b0
Does also happen on master: Yes

**Comment by zsol** [comment]
No, Black doesn't support that code style.

**Comment by mattdonders** [comment]
Is there a way to propose this as an enhancement and if so what is the process to do that?

Thanks for the quick response.

**Comment by JelleZijlstra** [comment]
We're very unlikely to change such a fundamental aspect of Black's code style.
