### ISSUE TITLE
Black breaks comment formatting for slurm/pbs cluster directives.

### ISSUE THREAD

**Issue by asford** [psf/black#1024]
Slurm and PBS use block comments of the form [`#SBATCH`](https://slurm.schedmd.com/sbatch.html) or [`#PBS`](http://docs.adaptivecomputing.com/torque/4-0-2/Content/topics/commands/qsub.htm)  immediately following the `#!` header to provide default configuration parameters for a batch scheduler.  Unfortunately, these tools don't support a pep8 compatible `# SBATCH` or `# PBS` syntax.

Applying black to a script with `#SBATCH` and `#PBS` directives silently breaks these tools, in that:

```python
#!/usr/bin/env python
#SBATCH --exclusive
[...]
```

is reformatted as:

```python
#!/usr/bin/env python
# SBATCH --exclusive
[...]
```

causing the `--exclusive` directive to be ignored by SLURM.

As the directive *must* follow the shebang and *must not* have a space between `#` and `SBATCH`. As such a `# fmt: off` escape hatche isn't a viable solution and (interestingly) don't prevent block comment reformatting in black's current implementation.

**Comment by asford** [comment]
#960 attempted to address this issue with a special-case for these directives, but it seems clear in #1014 that a purely special-case solution isn't practical in the long term.

@JelleZijlstra @edreamleo would an escape hatch option `--skip-comment-normalization` akin to `--skip-string-normalization` be a viable solution? Taking an opinion here seems hard given the potential complexity of multiple semantically overloaded comment pragma. It seems like providing a bail-out option is the most blackish solution?

**Comment by zsol** [comment]
I think that's the best solution I've seen so far, even though it would make Black produce code that's technically not PEP-8 compliant. But maybe it's the pragmatic choice.

**Comment by asford** [comment]
Yes, for clarity for incoming readers, the explicit ask in the referenced PRs is for a form on non-pep8 compliant output for semantically overloaded comments.

**Comment by thomas-albrecht** [comment]
I came across the very same problem and would very much appreciate a pragmatic solution.
Is there any progress on this issue?

**Comment by edreamleo** [comment]
Similarly, [Leo's sentinel comments](http://leoeditor.com/appendices.html#format-of-external-files) are not pep-8.

Leo now does allow whitespace between the '#" and '@', but that creates other problems, including massive diffs after blackening files.

In short, a pragmatic solution would be very much appreciated. It would be good if black could be told not to munge some (or all) comments. Thanks.

**Comment by SomeoneSerge** [comment]
I think the pragmatic solution would be to make `fmt: off` work for comments, cf. https://github.com/psf/black/issues/1245

**Comment by SomeoneSerge** [comment]
> `sbatch` submits a batch script to Slurm. The batch script may be given to sbatch through a file name on the command line, or if no file name is specified, sbatch will read in a script from standard input. The batch script may contain options preceded with "#SBATCH" before any executable commands in the script. sbatch will stop processing further #SBATCH directives **once the first non-comment non-whitespace line has been reached in the script.**
> ...
> https://slurm.schedmd.com/sbatch.html

Emphasis added

**Comment by tautomer** [comment]
> > However, according to the OP that's not an option for these #SBATCH comments, because they must be right after the shebang line.
> 
> I've just tried running a job with `fmt: off` between shebang and the SLURM directives and it worked. Idk yet if it's documented

I can confirm this is the behavior I observe as well.

**Comment by JelleZijlstra** [comment]
Let's make a decision in #3668.
