### ISSUE TITLE
Exclude option doesn't exclude specified file

### ISSUE THREAD

**Issue by steka** [psf/black#1025]
Operating system: Windows 7
Python version: 3.7.4
*Black* version: 19.3b0

It would be nice if the command:
"black --exclude file.py file.py"
Would not do anything, since specified file is listed to be excluded.
Specially useful when used in an editor integration, where the arguments can just be specified as:
Arguments: "--exclude file.py $FilePath$"

**Comment by JelleZijlstra** [comment]
We argued about this in #949; let's keep the discussion there.
