### ISSUE TITLE
Black fails with produced code not equivalent to source

### ISSUE THREAD

**Issue by johannesjmeyer** [psf/black#1026]
Operating system: Windows 10, Version 10.0.18362 Build 18362
Python version: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
*Black* version: 19.3b0
Does also happen on master: No

___

Black fails with "error: cannot format tests\test_simulator_device.py: INTERNAL ERROR: Black produced code that is not equivalent to the source"

As it does not happen on master, I think it will be fixed with the next release, nevertheless here are the minimal example and the diff log:

[black_fmt_error.zip](https://github.com/psf/black/files/3621000/black_fmt_error.zip)

**Comment by JelleZijlstra** [comment]
Didn't check the zip file, but assuming this has been fixed in one of our more recent releases.

**Comment by ichard26** [comment]
Can confirm this has been fixed.
