### ISSUE TITLE
Black not producing flake8 compatible output

### ISSUE THREAD

**Issue by uweschmitt** [psf/black#1029]
Operating system: Mac OS 10.14.6
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

The following output of `Black` is not accepted by `flake8`:

```python
a = [1, 2, 3]
i = 0
a[i + 1 : -1]
```

`flake8` reports an error regarding the last line:
```
test.py:6:8: E203 whitespace before ':'
```

**Comment by hugovk** [comment]
This is mentioned in the README at https://github.com/psf/black#slices.

It's suggested you instruct flake8 to ignore it, something like:

```ini
[flake8]
max-line-length = 80
...
select = C,E,F,W,B,B950
ignore = E501,W503,E203
```

https://github.com/psf/black#line-length
