### ISSUE TITLE
No-emoji switch for better output

### ISSUE THREAD

**Issue by im-n1** [psf/black#1031]
It would be really nice to have a switch which can disable emojis at all but not any other piece of Black output. The reason is emojis are graphical stuff which a lot of terminal emulators are not capable of not speking of pure console (framebuffer). I'm not hating emojis but I think they should be optional.

 An example output from my urxvt:

![image](https://user-images.githubusercontent.com/198654/65497606-cdd3bd80-deba-11e9-85be-2150d7193461.png)

`--quiet` doesn't work here quite good (based on this https://github.com/psf/black/issues/223)

**Comment by zsol** [comment]
Those emojis are unicode characters, which all modern terminals are capable of displaying, provided they're using a decent font.

Try using a font that can display these. There are plenty of free & paid options or you can [patch your own](https://github.com/ryanoasis/nerd-fonts)

**Comment by im-n1** [comment]
Do you think app output should be readable only in certain terminals with certain fonts?

**Comment by fiendish** [comment]
I think you should modernize your terminal. Unicode has been the standard for text in Python for 11 years now.

**Comment by im-n1** [comment]
Try to seek how graphics work in terminals. Maybe you will consider your opinion.

Anyway thank you all for your opinions. I'm out.
