### ISSUE TITLE
Proposed Format for Call Chains

### ISSUE THREAD

**Issue by sithankanna** [psf/black#1037]
By default, *Black* sets the first call in a call chain to be on the same line as the method that it calls from. Ideally, every call is placed on a new line. 

Example from the README: 
### Call chain Now:
```def example(session):
    result = (
        session.query(models.Customer.id) 
        .filter(
            models.Customer.account_id == account_id,
            models.Customer.email == email_address,
        )
        .order_by(models.Customer.id.asc())
        .all()
    )
```
### Proposed Call Chain

```def example(session):
    result = (
        session
        .query(models.Customer.id)
        .filter(
            models.Customer.account_id == account_id,
            models.Customer.email == email_address,
        )
        .order_by(models.Customer.id.asc())
        .all()
    )
```
Benefits:
* More readable 
* Consistent with other languages (e.g. JavaScript) https://en.wikipedia.org/wiki/Method_chaining 

#
Operating system:
Python version: 3.6
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by ClaytonJY** [comment]
I'd like that too, but as pointed out when the original implementation happened, that would cause inconsistencies with other code, e.g. https://github.com/psf/black/issues/67#issuecomment-389681164.

**Comment by wbolster** [comment]
i think this issue should be closed since this was discussed before, and this specific example was also discussed, and eventually rejected for the current behaviour.

see https://github.com/psf/black/issues/67#issuecomment-389681164

**Comment by JelleZijlstra** [comment]
Closing per @wbolster's comment. We're unlikely to change this formatting now.

**Comment by joshdunnlime** [comment]
Can we have an option for this please? 🙏🏽

**Comment by wbolster** [comment]
@joshdunnlime that is unlikely.

black in general doesn't do options to influence formatting, which is a feature.

and if you actually read through this ticket and the linked issues, you'll see this is a complex and subtle topic, making it extra unlikely that black will ever support two different approaches at the same time.
