### ISSUE TITLE
Adding fmt: off for multiline shell strings

### ISSUE THREAD

**Issue by xNinjaKittyx** [psf/black#1049]
I have a question in how we can disable black formatting when using multiline bash/sh shebang sections.

I'm doing something similar to this user on stackoverflow: https://unix.stackexchange.com/questions/66210/how-can-i-have-more-than-one-possibility-in-a-scripts-shebang-line

Code looks something like this:
```
#!/bin/sh
"true" '''\'
if [ -f /usr/bin/python3.6 ]; then
    echo "Using /usr/bin/python3.6"
    /usr/bin/python3.6 $0
else
    echo "Using /usr/bin/python3"
    /usr/bin/python3 $0
fi
exit $?
'''
```

I don't want black to format these triple single quotes, but I can't seem to figure out a way I could add # fmt: off.

Edit: There are obvious workarounds that are totally reasonable, but I would like to know a solution to this particular scenario.

Operating system: Ubuntu 18.04, Fedora 30, OpenSUSE Leap & Tumbleweed latest.
Python version: Python 3.6 
*Black* version: 19.3b0
Does also happen on master: yes?

**Comment by JelleZijlstra** [comment]
Black is meant for formatting Python code, not shell scripts. Why are you trying to format this file with Black?

**Comment by xNinjaKittyx** [comment]
This is a python file, but with a different shebang at the top.
There's a lot of python code after those lines.

I know it sounds slightly ridiculous, since it could be split into 2 files, but I was wondering if there was a way I could keep it as one file.

**Comment by zsol** [comment]
No, Black will never try and figure out which parts of its input are python. It assumes the entire input is valid python.
