### ISSUE TITLE
Ugly formatted code

### ISSUE THREAD

**Issue by 520Chris** [psf/black#1055]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Windows
Python version: 3.7.3
*Black* version: Latest
Does also happen on master: Yes

This is how black formatted my code.
From
```
entro_sum = p * self.entropy(index(X, part1), index(y, part1)) \
    + (1 - p) * self.entropy(index(X, part2), index(y, part2))
```
To
```
entro_sum = p * self.entropy(index(X, part1), index(y, part1)) + (
    1 - p
 ) * self.entropy(index(X, part2), index(y, part2))
```

Black makes the code more unreadable.

**Comment by GriceTurrble** [comment]
This is more indicative of the code needing some adjustment than Black having a problem formatting it.

Consider:

```python
entropy_1 = self.entropy(index(X, part1), index(y, part1))
entropy_2 = self.entropy(index(X, part2), index(y, part2))
entro_sum = p * entropy_1 + (1 - p) * entropy_2
```

**Comment by 520Chris** [comment]
@GriceTurrble Thanks for your response.
I think original code is beautiful enough. It seems that black hates backslash very much.
Is it possible that make black respect backslash?
