### ISSUE TITLE
Stubs: Different behavior inside "if version_check" blocks

### ISSUE THREAD

**Issue by srittau** [psf/black#1060]
Operating system: Debian buster
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: yes

We are currently looking into reformatting typeshed with black. One snag I ran into is in the following example:

```python
import sys

class Foo:
    def bar(self): ...

def abc(): ...

if sys.version_info >= (3,):
    class Foo:
        def bar(self): ...

    def abc(): ...
```

Reformatting this with black removes the empty line between the class and the function inside the "if" block, but not outside it:

```python
import sys

class Foo:
    def bar(self): ...

def abc(): ...

if sys.version_info >= (3,):
    class Foo:
        def bar(self): ...
    def abc(): ...
```

This causes some sub-module that are basically one big "if" block (since they were added in later Python versions) to be very "dense". One example is: https://github.com/python/typeshed/blob/c90b41bb230121a20e18da3adf772da1d03f7ab4/stdlib/3/importlib/metadata.pyi

**Comment by hauntsaninja** [comment]
I think I fixed this in https://github.com/psf/black/issues/2784 / https://github.com/psf/black/pull/2820
