### ISSUE TITLE
single value in __slots__ 

### ISSUE THREAD

**Issue by lordofinsomnia** [psf/black#1066]
Thanks for great tool, and keep up the good work. :)

Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Manjaro
Python version: 3.7
*Black* version: 19.3b0
Does also happen on master:

When i create a class with single slot varible: like this

```python
class Foo:
    __slots__ = "bar"
```
I got an error from pylint via tidypy:
```Class __slots__ should be a non-string iterable (pylint:single-string-used-for-slots)```
[Ok I have tried to make it a tuple](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABpAFVdAD2IimZxl1N_WlXnON2nzNhBxHQVvIQYWY51BsxQ8VT6gnQteiXMaVTLhBfiV2ekRhWDJvH-hrUuOsf9o85ZB9GfAUntbUkp8etBC_4b_7sHNTsmgEkAAAAApSuVWVejEPAAAXFq2nXFux-2830BAAAAAARZWg==)

```python
class Foo:
    __slots__ = ("bar")
```

after starting black is formatted without parentheses 
like in my first example.
```python
class Foo:
    __slots__ = "bar"
```

workaround for this issue is to put in this case surround item in this case "bar" with parentheses and put a comma between "bar" and close right parentheses.

```python
class Foo:
    __slots__ = ("bar",)
```
[With this workaround code is unchanged.](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABqAFVdAD2IimZxl1N_WlXnON2nzNhBxHQVvIQYWY51BsxQ8VT6gnQteiXMaVTLhBfiV2ekRhWa9H6jei5twWzUb-haijxANTH9b3hsxtS_gh76vC0a93nQ6ScAAAAAZi6mAsuKvYEAAXFrTEXCzB-2830BAAAAAARZWg==)

**Comment by JelleZijlstra** [comment]
`__slots__ = ("bar")` doesn't make it into a tuple; you need a comma for that. Black is doing you a service here by hinting that your mental model about how to create a tuple is wrong.
