### ISSUE TITLE
Vim Plugin cannot be used with Anaconda

### ISSUE THREAD

**Issue by MaxG87** [psf/black#1072]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 18.04
Python version:  3.7.4
*Black* version: black=19.3b0=py_0 (the one of conda)
Does also happen on master: Probably; I downloaded the vim plugin from there.

I always have an active Miniconda environment and do all my work in that. However, with that some virtual environment stuff does not work as expected by the black vim plugin. The error message I get is:

```
Please wait, one time setup for Black.
Creating a virtualenv in /home/mgoerner/.vim/black...
(this path can be customized in .vimrc by setting g:black_virtualenv)
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
    apt-get install python3-venv
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
Failing command: ['/home/mgoerner/.vim/black/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
Fehler beim Ausführen von "/home/mgoerner/.vim/pack/various/start/black/plugin/black.vim":
Zeile  135:
E880: Can't handle SystemExit of python exception in vim
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```

Thus, I cannot use Black's Vim integration. It would be great to see that resolved.

**Comment by lodagro** [comment]
Had the same message, installed ```python3-venv``` as suggested, worked fine from then on.
With conda you probably need https://anaconda.org/anaconda/virtualenv.

**Comment by MaxG87** [comment]
Unfortunately, doing `conda install virtualenv` did not help.

**Comment by lodagro** [comment]
Do you still get the same message?

**Comment by MaxG87** [comment]
Somehow I do not manage to reproduce the above verbose error message :-(. I do not recall what I have done to obtain the above message. I'll try to be a bit more specific about what I do now.

I created the following Conda environment:

    name: debug
    channels:
      - defaults
    dependencies:
      - python=3.7.5
      - virtualenv

Inside the environment I open up Vim and execute ':PlugInstall'. This clones the repository to `~/.vim/plugged/black` and then fails with:

    Fehler beim Ausführen von "function provider#python3#Call":
    Zeile   18:
    Traceback (most recent call last):
      File "<string>", line 63, in <module>

If I subsequently start Vim, I get the following error message:

    Fehler beim Ausführen von "function provider#python3#Call":
    Zeile   18:
    ModuleNotFoundError: No module named 'black'

For the record:

  1. This does not change when I remove the dependency on `virtualenv` from the environment. 
  2. Using NeoVim shows the same behaviour.

**Comment by qshzh** [comment]
same issue, it would be great if black can use conda as virtualenv

**Comment by hauntsaninja** [comment]
Closing, since this is stale and doesn't have a clear repro
