### ISSUE TITLE
[Request] No new line in classes with docstrings that don't define functions (e.g. Exceptions)

### ISSUE THREAD

**Issue by jmholla** [psf/black#1075]
Operating system: Mac OS 10.15
Python version: 3.7.4
*Black* version: 19.3b0
Does also happen on master: Yes

black formatted file:
```python
class FooException(Exception):
    """ Bar """

    pass
```

I wouldn't expect the new line. This is most common when defining exceptions.

**Comment by maxfischer2781** [comment]
You do not need the ``pass`` in this case. Black won't add an additional newline if the ``pass`` is not there

```
class FooException(Exception):
    """ Bar """
```

**Comment by jmholla** [comment]
I'm gonna go ahead and close this out. Thanks maxfischer2781!
