### ISSUE TITLE
Black unable to parse asignment expresions

### ISSUE THREAD

**Issue by ignaloidas** [psf/black#1077]
Operating system: Linux
Python version: 3.8.0
*Black* version: 19.3b0
Does also happen on master: No

Black is unable to parse this Python 3.8 code:
```
if (s:= 1+2) > 1:
    print(s)
```

**Comment by hugovk** [comment]
Support was added in https://github.com/psf/black/pull/935, to be released.

**Comment by JelleZijlstra** [comment]
Yes, this is fixed on master.
