### ISSUE TITLE
find_project_root fails to find repository root inside a git worktree

### ISSUE THREAD

**Issue by dominic-grindle** [psf/black#1083]
Bug seen when using black within a git worktree, the code at line 3540 in black.py only returns a directory when ".git" is a directory. 

For a normal git repository this is a directory, but when you use a git worktree ".git" is just a file, meaning this check fails and "find_project_root" usually ends up returning the file system root.

This caused trouble for a codebase I work on, as the full file path to my git worktree included "/build", which is excluded by black's default "--exclude" argument. This meant that no files in the worktree could be formatted by black as they were all excluded.

I'd suggest changing the check for ".git" to check for either a directory or a file, so that the correct project root is found in a git worktree as well.

**Comment by ichard26** [comment]
Didn't notice until now, but this has been fixed in PR https://github.com/psf/black/pull/1217.
