### ISSUE TITLE
Black fails to parse positional-only arguments, even when running on python 3.8 and targeting python 3.8

### ISSUE THREAD

**Issue by Starwort** [psf/black#1084]
As in title.
```
starwort@starwortlaptop:~/Documents$ py -m black binomial_playground.py -t py38
error: cannot format binomial_playground.py: Cannot parse: 3:22: def factorial(x: int, /) -> int:
All done! 💥 💔 💥
1 file failed to reformat.
```

**To Reproduce** Steps to reproduce the behaviour:

1. Take this file
```py
def factorial(x: int, /) -> int:
    if x in [0, 1]:
        return 1
    return factorial(x-1) * x
```
2. Run _Black_ on it with these arguments `-t py38`
3. See error

**Expected behaviour** black formats the file in the same way as non-positional-only arguments, but leaving the slash

**Environment (please complete the following information):**

- Version: 19.3b0 running on Python 3.8.0
- OS and Python version: Ubuntu/Python 3.8.0

**Does this bug also happen on master?** no

**Additional context** Add any other context about the problem here.

**Comment by MonliH** [comment]
Black also complains when you give it assignment expressions e.g.:
```python
if (x := 10) == 10:
    print(x)
```

**Comment by JelleZijlstra** [comment]
These are both fixed on master. We'll have a release soon with 3.8 support.
