### ISSUE TITLE
Formatting struct-like code

### ISSUE THREAD

**Issue by ptsl** [psf/black#1087]
Would it be possible to make black recognize struct-like code? I mean, I have a nicely formatted namedtuple:

```
MyObject = collections.namedtuple(
    "MyObject",
    [
        "name",
        "location",
        "direction",
        "speed",
    ],
)
```

and black reformats it to a (much less comprehensible) three-liner:

```
MyObject = collections.namedtuple(
    "MyObject", ["name", "location", "direction", "speed"]
)
```

The same is the case with dictionaries and key-value style constructors:

```
obj = MyObject(
    name=other.name,
    location=other.location,
    direction=other.direction,
    speed=other.speed,
)
```
gets formatted to (if the line length is set to 120 chars which is PyCharm's default):

```
obj = MyObject(name=other.name, location=other.location, direction=other.direction, speed=other.speed)
```

Yes, one can use `# fmt: off/on` in such cases, but isn't black's motto "to cede control over minutiae of hand-formatting"?

Or - to make a bolder statement - wouldn't it make sense to always prefer a "single column" style?

**Comment by timthelion** [comment]
This is the reason I don't use black. This makes code review much more difficult as you have to read word diffs.

**Comment by ichard26** [comment]
Now with _Black_ version `20.08b1` both of those examples are left untouched (probably due to the ["magic trailing comma"](https://github.com/psf/black/blob/master/docs/the_black_code_style.md#the-magic-trailing-comma) feature which has been fixed to work properly recently):

```console
R:\Programming\black>type temp.py
MyObject = collections.namedtuple(
    "MyObject",
    [
        "name",
        "location",
        "direction",
        "speed",
    ],
)
obj = MyObject(
    name=other.name,
    location=other.location,
    direction=other.direction,
    speed=other.speed,
)

R:\Programming\black>black temp.py --diff --color -l 120
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

**Environment:**
* _Black_ version: `20.08b1`
* Python version: `CPython 3.8.1`
* OS version: `Windows 10 Home Edition Build 18363`

**Comment by JelleZijlstra** [comment]
Indeed, let's close this.
