### ISSUE TITLE
Any way to disable black for specific files?

### ISSUE THREAD

**Issue by george-ge** [psf/black#1088]
I’m a bit new to this package, and I’ve been using it a lot recently as a part of the CI/CD pipeline that has been put into place by my team.

My team enforces a strict character count for each line, and even though it works for majority of cases, it is just a hindrance in other cases. 

A good example is when one of our files contains functions with multiple decorators. After running black through the file, it looks like a jumbled mess due to all the variable multiline decorators.

I was wondering if there was an option to turn off black for specific files using a comment, like with pylint?

**Comment by hugovk** [comment]
Can you use `#fmt: off` and `#fmt: on` around those sections of files you don't want to format?

```python
this_is_formatted = "123"

# fmt: off
this_will_be_left_as_it_is =    '123'
# fmt: on

this_is_formatted = "123"
```


https://github.com/psf/black#the-black-code-style

**Comment by JelleZijlstra** [comment]
You can turn off individual sections in a file with comments, as @hugovk says. In addition, you can use the `--exclude` option to exclude specific files from reformatting, as mentioned in the repo's README.
