### ISSUE TITLE
Black is running forever on a small directory

### ISSUE THREAD

**Issue by crinny** [psf/black#1096]
**Describe the bug** 
I have installed Black in my PyCharm project's venv and tried to run it. At first it gave me these errors:
```
PermissionError: [WinError 5] Access denied
error: cannot format C:\Users\crinny\PycharmProjects\autobot\config.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\crinny\PycharmProjects\autobot\main.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\crinny\PycharmProjects\autobot\middlewares.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\crinny\PycharmProjects\autobot\responses.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\crinny\PycharmProjects\autobot\test.py: A process in the process pool was terminated abruptly while the future was running or pending.
All done! 💥 💔 💥
5 files failed to reformat.
```
After I disabled read-only on the directory and all files in it, black is just running forever in it. I have waited for about 10 minutes but got no result at all.

**To Reproduce**

1. Install _Black_ in PyCharm project
1. Run _Black_ on it with path as an argument
3. Wait forever looking at clean console

**Expected behavior** A clear and concise description of what you expected to happen.
Black is formatting my code or making any output to console

**Environment**

- Version: latest from pip
- OS and Python version: `Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32`/Windows 10

**Does this bug also happen on master?**

Yes

**Additional context**

**Comment by JelleZijlstra** [comment]
Have you tried the `-v` option?

**Comment by crinny** [comment]
@JelleZijlstra I just outputs this and runs forever
```
.git ignored: matches the --exclude regular expression
```

**Comment by ambv** [comment]
@crinny, can you try the updated version from pip and tell us if this is still happening? There were Windows-related fixes that should help you.
