### ISSUE TITLE
Please do another release

### ISSUE THREAD

**Issue by gvanrossum** [psf/black#1099]
I've noticed that master can format Python 3.8 code with walrus operators, but the latest release (19.3b0) cannot. Now that 3.8.0 is released can you do another release?

(Also is there an explanation of the version numbers somewhere in the docs?)

**Comment by hugovk** [comment]
A beta release is due out on monday:

* https://twitter.com/llanga/status/1187675966694449152 
* https://github.com/psf/black/issues/517#issuecomment-546396161

Black uses [calver](https://calver.org/), the version is yy.m and b0 for first beta of that month. 

* https://github.com/psf/black/blob/master/README.md#183a0

**Comment by gvanrossum** [comment]
Great to hear!

Am I misinterpreting the output of `git tag`, or are all releases betas or alphas?

**Comment by hugovk** [comment]
That's right, only alphas and betas so far, but a stable release is planned for 2019 :) 

* https://twitter.com/llanga/status/1187675968007278592

**Comment by ambv** [comment]
Done. Sorry for the wait.
