### ISSUE TITLE
getitem syntax gets multilined

### ISSUE THREAD

**Issue by jleclanche** [psf/black#1101]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

Use this file:
```py
class Foo:
    def bar():
        foo = Foo.objects.filter(
            a, bunch, of, arguments, **and_then_some
        ).prefetch_related(
            "aaaaaaaa", "bbbbbbbbbbbbbbb", "cccccccccccccccc", "dddddddddd"
        )[:50]
```

It will become reformatted to the following:

```py
class Foo:
    def bar():
        foo = Foo.objects.filter(
            a, bunch, of, arguments, **and_then_some
        ).prefetch_related(
            "aaaaaaaa", "bbbbbbbbbbbbbbb", "cccccccccccccccc", "dddddddddd"
        )[
            :50
        ]
```

The multiline `[:50]` is pretty nasty. This happens on master.

**Comment by graingert** [comment]
to help with the GitHub issue search: this is known as subscript notation

**Comment by graingert** [comment]
there seems to be a few duplicates of this:

https://github.com/psf/black/issues/814
https://github.com/psf/black/issues/1101
https://github.com/psf/black/issues/1406

**Comment by ichard26** [comment]
This would classify as a design issue, while I agree subscript handling can be and should be improved, Black isn't violating any documented expectations. Also, yeah this is a duplicate of #814 so I'll be closing this. Thanks for the suggestion!
