### ISSUE TITLE
it keeps output really ugly style for dict

### ISSUE THREAD

**Issue by hackrole** [psf/black#1107]
```
#  before black
    cluster = {
        "uuid": "4e3bb9d2d37611e9bb652a2ae2dbcce4",
        "publish_threshold": 0.99,
        "count": 333,
        "id": 11888,
        "model_tag": "package_餐饮具",
# after black
    cluster = {
        "uuid":
        "4e3bb9d2d37611e9bb652a2ae2dbcce4",
        "publish_threshold":
        0.99,
        "count":
        333,
        "id":
        11888,
        "model_tag":
        "package_餐饮具",
```

is this the designed behaive?

**Comment by ambv** [comment]
No, this is not Black doing this. In fact Black never puts a single-token value on a separate line from the key. Make sure you are not using a different formatter.

**Comment by hackrole** [comment]
OK, I use spacemacs to edit python file. And set python-formatter to black, and also set isort import while save buffer. 
if this is not black problem, I will try to figure out it.
Thanks
