### ISSUE TITLE
INTERNAL ERROR: Black produced invalid code: invalid syntax

### ISSUE THREAD

**Issue by bhearsum** [psf/black#1111]
Tried this with both 19.10b0 and master (6bedb5c58a7d8c25aa9509f8217bc24e9797e90d).

```
  File "/home/bhearsum/.local/lib/python3.7/site-packages/black.py", line 3388, in assert_equivalent
    dst_ast = ast.parse(dst)
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
```

https://gist.github.com/mozbhearsum/3754deeab4785419e5efafd683420b0e

**Comment by jeffwidman** [comment]
@bhearsum I can't access the gist?

**Comment by JelleZijlstra** [comment]
Looks like it's https://gist.github.com/bhearsum/3754deeab4785419e5efafd683420b0e now

**Comment by JelleZijlstra** [comment]
The gist has a syntax error in it. Closing as I don't know how to reproduce it.

**Comment by ichard26** [comment]
My hunch is that the gist is the invalid output produced by Black, in which case is probably another case of #569, but I don't feel like checking.
