### ISSUE TITLE
Remove trailing whitespace

### ISSUE THREAD

**Issue by pylang** [psf/black#1114]
**Is your feature request related to a problem?**

 Running black (in VSCode) does not remove trailing whitespaces.  

`s = 'Hello world!"_ _`

**Describe the solution you'd like** 

Rather, I'd like black to remove trailing whitespace on all lines.

`s = 'Hello world!"`

**Describe alternatives you've considered**

I  have to do a followup "Trim Whitespace" command in VSCode.  I'd like this to be part of black by default.

There are some prior issues (#567) regarding trailing whitespace inside strings.  Removing trailing whitespace by default can clean up code and even save some wasted space.

**Comment by msgongora** [comment]
this can be fixed using vscode feature instead:

**settings.json**
```json
"[python]": {
        "files.trimTrailingWhitespace": true,
    },
...
```

**Comment by ichard26** [comment]
Black already does this. 
```diff
richard-26@ubuntu-laptop:~/programming/tools/ghprcl$ black test.py
reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.
richard-26@ubuntu-laptop:~/programming/tools/ghprcl$ diff -u --color orig.py test.py
--- orig.py	2020-07-28 17:45:02.959401063 -0400
+++ test.py	2020-07-28 17:44:46.307273954 -0400
@@ -1 +1 @@
-s = "Hello world!"  
+s = "Hello world!"
```
### BEFORE
![Screenshot from 2020-07-28 17-57-26](https://user-images.githubusercontent.com/63936253/88726555-f55b6e00-d0fb-11ea-8be7-f5a51745c222.png)
### and AFTER
![Screenshot from 2020-07-28 17-58-15](https://user-images.githubusercontent.com/63936253/88726558-f7bdc800-d0fb-11ea-9fb1-7452d1c38eb5.png)



This seems like a problem with how Visual Studio Code handling of diffs. [Maybe related to this?](https://github.com/microsoft/vscode-python/issues/11001) 

--- 

**Environment:**
* OS version: `Ubuntu 18.04.04 LTS`
* Python version: `CPython 3.8.1`
* Black version: `19.10b0`

**Comment by JelleZijlstra** [comment]
Closing as this is most likely an issue with VSCode, not Black.

**Comment by rjurney** [comment]
Try these in `<project_root>/.vscode/settings.json`:

```json
{
    "python.formatting.provider": "black",
    "[python]": {
        "files.trimTrailingWhitespace": true,
        "editor.formatOnSave": true
    }
}
```
