### ISSUE TITLE
README is out of date regarding trailing commas

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#1118]
https://github.com/psf/black/blob/master/README.md#trailing-commas does not seem correct after #826?

**Comment by graingert** [comment]
black 19.3b0:
```patch
-ham("spam",)
+ham("spam")
```
```patch
ham("spam",)
```

**Comment by pabelanger** [comment]
I can confirm this, also 

```
ham("spam",)
```

no longer makes flake8 happy (I know we still run it in some cases with black) and there is no trailing space after the comma.

**Comment by graingert** [comment]
@pabelanger that's a collection so is behaving differently

**Comment by ichard26** [comment]
Fixed by 6b935a34d08c0b18d858e7da5093dc69a29c55f2, closing.
