### ISSUE TITLE
black 19.10b0 moves comments

### ISSUE THREAD

**Issue by graingert** [psf/black#1119]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

```diff
--- before.py	2019-10-30 09:58:55.912054280 +0000
+++ after.py	2019-10-30 09:59:04.940064509 +0000
@@ -1,10 +1,10 @@
 def ham():
     ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = (
-        "foo"
-    )  # tipe: str
+        "foo"  # tipe: str
+    )
 
 
 def ham():
     ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = (
         "foo"
     )  # type: str

```

**Expected behavior** A clear and concise description of what you expected to happen.

Should behave the same regardless of "type:" or "tipe:"

**Environment (please complete the following information):**

N/A repros on playground

**Does this bug also happen on master?** To answer this, you have two options:

yes https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFUAGZdAD2IimZxl1N_WlbvK5V9jFWWIeAUKtl9yAIWu0xBZRYufu53E20KvwjrvjpCNcD_sEfkfz8H1QKqCpEG4ABfAgYKTpykKZPWkBxEuvOvpIJY9YHAweNveGybKuGuXnDULzCm_9I1QQAAABnNawxy_QTjAAGCAdUCAAB71UO_scRn-wIAAAAABFla

**Additional context** Add any other context about the problem here.

**Comment by graingert** [comment]
this is bad because it changes the semantics of other comment annotations

**Comment by graingert** [comment]
@ambv is this expected behaviour?

**Comment by ambv** [comment]
Well. It's a known issue. In its essence it's related to #379 with the added insight that maybe it would be better to treat *all* comments as type comments.
