### ISSUE TITLE
Broken hyperlinks in home page

### ISSUE THREAD

**Issue by claird** [psf/black#1122]
Intra-page hyperlinks of the home page don't resolve, because target anchors are missing.

Example:  [https://pypi.org/project/black/#change-log](https://pypi.org/project/black/#change-log) does _not_ display the **Change Log** section, because the **Change Log** heading lacks its intended anchor:

        ...
    <p>More details can be found in <a href=CONTRIBUTING.md rel=nofollow>CONTRIBUTING</a>.</p>
    <h2>Change Log</h2>
    <h3>19.10b0</h3>
    <ul>
        ...

**Comment by hugovk** [comment]
They work at https://github.com/psf/black because of the way GitHub processes the Markdown.

**Comment by claird-ot** [comment]
Ha!  I see.  Thank you, Hugo.

**Comment by ichard26** [comment]
No longer relevant as the TOC doesn't exist after my documentation reorganization effort: #2174.

Thanks for noticing though!

(p.s. I probably would've used `<h1 id="change-log">Change Log</h1>` to fix this)
(p.s.s I just noticed the changelog is referenced twice in the distribution's long description, we should probably fix that, that's a new issue tho)
