### ISSUE TITLE
Black 19.10b0 breaks subscript with 1D tuple

### ISSUE THREAD

**Issue by flying-sheep** [psf/black#1139]
**Black v19.10b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABKADpdAD2IimZxl1N_WlOfrjrv6KoHiX2PJdp0pHbojcutZl2As4EWHdkA4o_gekz_mZJcPVWgdbLmnuJVpkAAAAAKwn4TXP5SrQABVkvh12ktH7bzfQEAAAAABFla)

This should be left alone:

```python
a = a[:2,]
```

But it becomes:

```python
a = a[
    :2,
]
```

**Comment by jdufresne** [comment]
Probably related to  #1136 and #1129. Original work done in #826.

**Comment by gforcada** [comment]
:+1: on fixing this one, I just stumbled upon it :sweat_smile:

**Comment by alimcmaster1** [comment]
Another example of this - we are noticing when running black on pandas:
```
import pandas as pd

df = pd.DataFrame({"A": [1], "B": [2]})
res = df.loc[lambda x: x.A > 2,] 
```
Becomes:
```
import pandas as pd


df = pd.DataFrame({"A": [1], "B": [2]})
res = df.loc[
    lambda x: x.A > 2,
]
```
[playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACnAIddAD2IimZxl1N_WlwxRhR7MSgFCBRtpZAMNEh4Czj-43CTn4IDkJ1u_LB7eF_PaoLFS3Pt47KzRFhaBQ2fUnQn8KYYe7ygm5GwRB2I5wDwQDvWfqVXejEJUAbfy1RwAvbdHLPZAdBOdwiE5s1-TauMVqnXNZ2GkDX-lI8L1hOUAaliCPBoPdTJMAAASLJlqyR6t1IAAaMBqAEAAPDFoOixxGf7AgAAAAAEWVo=)

**Comment by jorisvandenbossche** [comment]
Note that several explanations in the black docs / README are also no longer correct (if it is the intention to keep this specific change).

Eg in the section on "Trailing commas":

> One exception to removing trailing commas is tuple expressions with just one element. In this case Black won't touch the single trailing comma as this would unexpectedly change the underlying data type. Note that this is also the case when commas are used while indexing. This is a tuple in disguise: `numpy_array[3, ]`.

or in "How Black wraps lines":

> As for vertical whitespace, Black tries to render one full expression or simple statement per line. If this fits the allotted line length, great.
>
> ```
> # in:
>
>j = [1,
>     2,
>     3,
>]
>
># out:
>
>j = [1, 2, 3]
>```

**Comment by JelleZijlstra** [comment]
Right, but this case is clearly a bug, and we should fix it rather than the README. We'd appreciate if anyone is able to contribute a way to fix this bug.

**Comment by vemel** [comment]
Basically, we should check if it is a list or a subscript. In case of a subscript - trailing comma should not split lines aggressively.

**Comment by vemel** [comment]
Well, whole `Line.is_collection_with_optional_trailing_comma` works only for one collection per line. This logic should be moved to `right_hand_split` function

**Comment by vemel** [comment]
Fixed in [PR](https://github.com/psf/black/pull/1164)

**Comment by taraskuzyk** [comment]
@vemel 
from 
```
 assert expected_dict["clutch_name"] == "lol" and expected_dict["clutch_industries"][0] == {"name": "lol", "humanized_name": "lol"}

```

getting 
```
assert expected_dict["clutch_name"] == "lol" and expected_dict["clutch_industries"][
        0
    ] == {"name": "lol", "humanized_name": "lol"}
```

which just looks really odd

**Comment by marcglobality** [comment]
> @vemel from
> 
> ```
>  assert expected_dict["clutch_name"] == "lol" and expected_dict["clutch_industries"][0] == {"name": "lol", "humanized_name": "lol"}
> ```
> 
> getting
> 
> ```
> assert expected_dict["clutch_name"] == "lol" and expected_dict["clutch_industries"][
>         0
>     ] == {"name": "lol", "humanized_name": "lol"}
> ```
> 
> which just looks really odd

you could add a magic comma after `"humanized_name": "lol"`. That would split it into something like:
```
assert element["a"] == "lolaaaaaaaaaaaaaa" and element["b"][0] == {
        "name": "lol",
        "humanized_name": "lol",
    }
```

I say something like because I don't really use black but our wrapper `globality-black` which fixes some of its weaknesses. If interested, see https://github.com/globality-corp/globality-black/

**Comment by JelleZijlstra** [comment]
Fixed on main:
```
% black -c 'a = a[:2,]'                     
a = a[:2,]
% black --version      
black, 22.12.1.dev17+g5ea8938.d20221219 (compiled: no)
Python (CPython) 3.11.0
```
