### ISSUE TITLE
assertion not consistent with type annotations

### ISSUE THREAD

**Issue by wimglenn** [psf/black#1144]
https://github.com/psf/black/blob/9b484d1bcc2e15dcd5544cddab729c76b4d1d2e9/black.py#L216-L224

^ something looks fishy here, the annotation hints that value is:

    value: Union[str, int, bool, None]

but the assertion says otherwise

    assert not isinstance(value, (int, bool)), "Invalid parameter type passed"

To say nothing about using assertions for input validation, it looks like these can't _both_ be right.

**Comment by vemel** [comment]
I just pushed a [PR](https://github.com/psf/black/pull/1166). Good catch!

**Comment by ichard26** [comment]
This should be closed as PR #1166 has been merged.

**Comment by cooperlees** [comment]
@ichard26 says we're good. We're good.
