### ISSUE TITLE
Error on invalid function signature faults wrong line

### ISSUE THREAD

**Issue by thatch** [psf/black#1158]
**Describe the bug** 

Some files with invalid syntax, where there is a type hint earlier in the file, fault the type hint line rather than the line it should.

**Expected**

On most files it faults the same line as running with python itself:

```
class T:
        stmt = 2

def parse(text, a=1, b):
    pass
```
and

```
$ black t.py
error: cannot format t.py: cannot use --safe with this file; failed to parse source file.  AST error message: non-default argument follows default argument (<unknown>, line 4)
$ python t.py
  File "t.py", line 4
    def parse(text, a=1, b):
             ^
SyntaxError: non-default argument follows default argument
```

**Errant condition**
On this input with line 2 containing a type hint, the error faults the wrong line, while python's error is unchanged.

```
class T:
        stmt: int = 2

def parse(text, a=1, b):
    pass
```

```
$ black t.py
error: cannot format t.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 2)
$ python t.py
  File "t.py", line 4
    def parse(text, a=1, b):
             ^
SyntaxError: non-default argument follows default argument
```

**Environment (please complete the following information):**

- Version: 19.10b0 and black-19.10b1.dev5+gde6f4b1 (master)
- OS and Python version: Arch Linux, black installed via pip in venv, 3.7.4

**Comment by JelleZijlstra** [comment]
This is because Black tries to parse files with both a Python 3 and a Python 2 grammar if you don't specify the target version. If you set the `target_version` option to Python 3 versions only, we'll try only the Python 3 grammar.

I don't think this is actionable for us.
