### ISSUE TITLE
Automatically read configuration file, similar to prettier

### ISSUE THREAD

**Issue by hallazzang** [psf/black#1163]
**Is your feature request related to a problem? Please describe.**
Not really a problem, it's just a feature request.
I think it'd be nice to have something like `.blackrc` file, similar to JS formatter _**prettier**_.

**Describe the solution you'd like**
_**black**_ automatically reads configuration from `.blackrc` if presents, or fallback to default when formatting.

**Describe alternatives you've considered**

**Additional context**
I see there already is a `--config` command line argument but there is no documentation about it. Automatic configuration recognition would be good to support editors too, because users do not have to specify additional command line argument pointing their configuration file.

**Comment by hugovk** [comment]
Black supports the `pyproject.toml` config file, and automatically reads it:

*&* https://github.com/psf/black#pyprojecttoml

**Comment by hallazzang** [comment]
@hugovk Oh sorry. I didn't read README carefully. Closing this issue.
