### ISSUE TITLE
Incorrect Space Added after Assignment Expression in If Statement

### ISSUE THREAD

**Issue by t-mart** [psf/black#1174]
**Description**
Black on the [current master@c53853f](https://github.com/psf/black/tree/c53853f5716f2b5100b17b8f8509e026dd7fa4e2) and ([19.10b0](https://github.com/psf/black/tree/19.10b0)) adds a space after [Assignment Expressions](https://www.python.org/dev/peps/pep-0572/) and before the final colon in `if` statements.

For what it's worth, I'm not sure if this is actually intended behavior or not, but it doesn't seem like it. No other parenthesized expressions in `if` statements get this treatment.

**To Reproduce**:

1. Put this example in a file:
    ```python
    if (foo := True):
        print(foo)
    ```
2. Run `black <file> --diff`

**Expected behavior**
Black should not need to act upon this file. There should be no diff output and black should claim `1 file would be left unchanged.`

**Actual behavior**
Black currently inserts a space between the end of the assignment expression and the colon.

Actual `black <file> --diff` output:
```diff
--- blacktest.py        2019-11-23 00:56:09.070688 +0000
+++ blacktest.py        2019-11-23 00:56:15.282759 +0000
@@ -1,3 +1,3 @@
-if (foo := True):
+if (foo := True) :
     print(foo)
 ```

**Environment:**

- Version:  [current master@c53853f
](https://github.com/psf/black/tree/c53853f5716f2b5100b17b8f8509e026dd7fa4e2)
- OS and Python version: Windows 10 and Linux tested with Python 3.8.0

**Does this bug also happen on master?**
Yes

**Other Information**
This also affects `if` statements that are broken up into several lines.

_The following example comes come a current project, excuse the specificity. The `# pylint: disable=superfluous-parens` should be treated simply as a comment for the scope of this issue. (In reality, pylint is also currently having [a problem with assignment expressions](https://github.com/PyCQA/pylint/issues/3249#issuecomment-557462095))_
```python
class Foo:
    def method(self):
        if (
            invalid_reasons := self.invalid_reasons()
        ):  # pylint: disable=superfluous-parens
            LOGGER.error(
                f"Not saving raid for the following reasons: {', '.join(invalid_reasons)}"
            )
            return

```

```diff
--- blacktest.py        2019-11-23 01:07:27.116369 +0000
+++ blacktest.py        2019-11-23 01:07:30.956945 +0000
@@ -1,10 +1,10 @@
 class Foo:
     def method(self):
         if (
             invalid_reasons := self.invalid_reasons()
-        ):  # pylint: disable=superfluous-parens
+        ) :  # pylint: disable=superfluous-parens
             LOGGER.error(
                 f"Not saving raid for the following reasons: {', '.join(invalid_reasons)}"
             )
             return
```

**Comment by JelleZijlstra** [comment]
Agree that this is a bug.
