### ISSUE TITLE
Cannot format when unaligned `# fmt: on` follows function body

### ISSUE THREAD

**Issue by aperiodic** [psf/black#1175]
**Describe the bug**
Black cannot reformat a file when:
- the last line of a function or method body is the `# fmt: on` directive
- the `# fmt: on` directive has no indentation (it starts on first character of the line)
- there is another global statement or expression following the function/method definition.

When these three conditions apply, Black errors out with the message that "Black produced code that is not equivalent to the source."

**To Reproduce**
1. Paste the following into a python source file, at the global level:
```py
def foo(bar):
    # fmt: off
    baz = "qux"
# fmt: on

def biz(baz):
    pass
```
2. Run _Black_ on it with no arguments.
3. See error

**Expected behavior**
Black should reformat the source listed above to:
```py
def foo(bar):
    # fmt: off
    baz = "qux"
    # fmt: on

def biz(baz):
    pass
```

**Environment (please complete the following information):**
- Version: 19.10b0, master at fb1ac69
- OS and Python version: MacOS Mojave (10.14.5) with Python 3.6.8 or Python 3.8.0.

**Does this bug also happen on master?**
Yes, I have reproduced this bug on my local machine, at the current head of master (fb1ac69) (and I've verified that all tests pass, though I had to follow what the TravisCI job does rather than following the instructions in the bug report issue template or in CONTRIBUTING.md).

**Additional context**
[This is the AST diff log file that black writes](https://github.com/psf/black/files/3887870/blk_mfzvh0bs.log) when trying to format a file containing only the problematic source listed above.

**Comment by zsol** [comment]
This is most likely the same case as #569, let's keep the discussion there.
