### ISSUE TITLE
Erroneous rewriting of long lines creates tuples

### ISSUE THREAD

**Issue by futuraprime** [psf/black#1177]
**Describe the bug** Black is rewriting a long line in a way that changes the type of variable being written by the line of code.

**To Reproduce**

Add this line to a file:

```
for c in results:
    paId = session.query(Constituency).filter(Constituency.onsCode == c["code"]).one().paId

```
which returns an integer.

When you run Black on the file, it converts this to:

```
for c in results:
    paId = (
        session.query(Constituency).filter(Constituency.onsCode == c["code"]).one().paId
    )

```

This code returns a tuple.

**Expected behavior** 

paId should return an integer from my database. The reformatted code produces a tuple containing the integer, which breaks subsequent code.

**Environment (please complete the following information):**

- Version: black, version 19.10b0
- OS and Python version: MacOS 10.14.6/Python 3.6.8

**Does this bug also happen on master?** To answer this, you have two options:

[Yep.](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACwAIddAD2IimZxl1N_WlkNxQPVtT5M0PGZc0nUwKfm4HoNxmjBTKSdmD-gHjhYOFbc-3iV2rCmRzuji6Byo3pWHbyOD9yWrZEVaBynbLjJ4g_1xhM3LWvNPJHJPD0E0oW38dXbyNm8UZ01yXCD297pBvCVJ7inhDQkpUyB5YwTESYNlOfuBTUhR__2AAAAZD2JOSW8YloAAaMBsQEAAOXdscWxxGf7AgAAAAAEWVo=)

**Comment by asottile** [comment]
that's not a tuple, just continuation parentheses

a single-element tuple needs a comma:

```pycon
>>> (
...     1
... )
1
>>> 
>>> (
...     1,
... )
(1,)
```

**Comment by JelleZijlstra** [comment]
@asottile is right. We can argue about whether this formatting is the best one, but Black doesn't change the meaning of the code.

**Comment by futuraprime** [comment]
I mean, you’re free to argue with the Python interpreter. But I get back a tuple from this line, and when I try to write it to a database on the next line I get a type error because I cannot write a list to a numeric field, and I do not get that error from the un-reformatted line.

**Comment by asottile** [comment]
The post you've written is not a tuple, your bug is somewhere else
