### ISSUE TITLE
"not equivalent to the source" error

### ISSUE THREAD

**Issue by ivirshup** [psf/black#1181]
**Describe the bug** A clear and concise description of what the bug is.

Black errors while checking a file.

**To Reproduce** Steps to reproduce the behavior:

1. Take [this file](https://github.com/theislab/scanpy/blob/6340abca1cb332175d322ad2350ee5286c02c3dd/scanpy/metrics/_gearys_c.py)
2. Run _Black_ on it with these arguments `--check --diff`
3. See error

```python
error: cannot format scanpy/metrics/_gearys_c.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/blk_ag2u14jv.log
Oh no! 💥 💔 💥
1 file would fail to reformat.
```

- Version: master and release
- OS and Python version: macOS for master and release, version `black-19.10b0` on travis ([failed build](https://travis-ci.org/theislab/scanpy/jobs/618445618#L251)). Python 3.7 all around.

**Does this bug also happen on master?**

Yup. Not using the online formatter, but I installed it locally (macOS) and it failed

**Additional context**

[Log contents (gist)](https://gist.github.com/ivirshup/3cfda906e75fe521971bd5f1b7fedb01)

**Comment by JelleZijlstra** [comment]
This looks like the same tabs/spaces issue that caused #1170.

**Comment by ivirshup** [comment]
Update: If I remove the `# fmt: off` comment on line 102 the error stops occurring.

**Comment by ivirshup** [comment]
Just came back to say I was getting this issue with `black==20.8b1`. However, I closed the `# fmt: off` with a `# fmt: on` and now it works.

**Comment by ichard26** [comment]
@ivirshup good to know! In that case, I'll close this issue as another case of GH-569.
