### ISSUE TITLE
Format SQL strings

### ISSUE THREAD

**Issue by dms-cat** [psf/black#1185]
With Black and Prettier in place SQL strings are pretty much the only major holdouts in the project I'm working on. Manually enforcing a SQL style is time consuming and boring, [`format-sql`](https://pypi.org/project/format-sql/) is broken and unmaintained, and there doesn't seem to be any other options at the moment.

Of course, detecting plain SQL strings is not going to work on its own; there would be too many false positives. What we could do is detect string literals being used in certain specific method calls, such as `psycopg2.SQL("""SELECT …""")`, and format only *those.* More advanced versions could support `psycopg2.SQL(query)` or even `psycopg2.SQL(query + optional_where_clause)`.

Ideally the solution would apply similar rules as in Python to common structures. So `SELECT foo, bar` would be unchanged, while `SELECT foo, [lots of columns], bar` would be formatted as *something like*

```sql
SELECT foo,
       first_intermediate_column,
       …,
       bar
```

or

```sql
SELECT
    foo,
    first_intermediate_column,
    …,
    bar
```

I suspect this is not appropriate as a Black core module because of the dependency on third party packages to determine which strings are actually SQL, but maybe as a plugin?

**Comment by energizah** [comment]
https://pglast.readthedocs.io/en/latest/ is a maintained sql formatter.

**Comment by dms-cat** [comment]
@energizah Looks promising, but AFAICT it needs work to reformat files.

**Comment by zsol** [comment]
This is not something that's likely going to make it into Black itself. Having said that, at my company we use Black's APIs to parse out all strings and then determine if they're SQL or not. If they are well-formed SQL statements, we format those using an external binary, shove them back into the AST and then let Black run on the result. So it's basically the approach you describe. It's a bit slow because of the need to identify if a string is SQL or not, but in practice it works well enough.

**Comment by bfelbo** [comment]
@zsol That sounds great. Any plans to open-source your approach?

**Comment by zsol** [comment]
Not as far as I know :(

**Comment by zeha** [comment]
@zsol is the library you're using to format SQL open source?

**Comment by zsol** [comment]
It's not, but it wraps https://github.com/zeroturnaround/sql-formatter

**Comment by louisabraham** [comment]
why was this issue closed? I'm interested in contributing!

**Comment by zsol** [comment]
It was closed because this feature is out of scope for a simple tool like Black. Sorry.

**Comment by JelleZijlstra** [comment]
I started working on a SQL parser/formatter which includes a tool to format SQL embedded in Python: https://github.com/JelleZijlstra/sqltree.

**Comment by louisabraham** [comment]
@JelleZijlstra Great, how can I launch it on .py files?

**Comment by JelleZijlstra** [comment]
Added https://github.com/JelleZijlstra/sqltree/pull/20 to document it. If that doesn't work for you, let me know on the sqltree repo.

**Comment by louisabraham** [comment]
That's awesome!!! Thanks!
