### ISSUE TITLE
Black crashes on annotated tuple assignment

### ISSUE THREAD

**Issue by antonagestam** [psf/black#1189]
Black crashes on tuple assignment without parentheses, when using type annotations.

**To Reproduce**

With no config or flags, this crashes:

```python
from typing import Tuple

p: Tuple[int, int] = 0, 0
```

```
error: cannot format black-fail2.py: Cannot parse: 3:22: p: Tuple[int, int] = 0, 0
Oh no! 💥 💔 💥
1 file failed to reformat.
```

This doesn't crash:

```python
from typing import Tuple

p: Tuple[int, int]  = (0, 0)
```

And neither does this:

```python
p = 0, 0
```

**Environment:**

- Version: 19.10b0
- OS and Python version: Macos 10.15/Python 3.8.0

**Does this bug also happen on master?**: Yes, tested on black.now.sh

**Comment by JelleZijlstra** [comment]
This is because this code was a syntax error in Python < 3.8, and apparently our parser hasn't been updated to support the new syntax. It should hopefully be an easy fix.

**Comment by antonagestam** [comment]
Oh cool, TIL! :)
