### ISSUE TITLE
Black fails to find python files

### ISSUE THREAD

**Issue by AnOctopus** [psf/black#1193]
**Describe the bug**
Black, when run on a directory, fails to find python files contained in it.

**To Reproduce** Steps to reproduce the behavior:
Directory structure:
```
tree src/cloudbuild 

src/cloudbuild
├── build
│   ├── build_args.py
│   ├── build_result.py
│   ├── build_tool.py
│   ├── config
│   │   ├── mypy_tool.ini
│   │   ├── pycodestyle_tool.ini
│   │   ├── pylint_tool.rc
│   │   ├── python_toolchain.yaml
│   │   └── test_coverage_tool.rc
│   ├── __init__.py
│   └── tool
│       ├── compile_tool.py
│       ├── docstr_coverage_tool.py
│       ├── __init__.py
│       ├── mypy_tool.py
│       ├── pycodestyle_tool.py
│       ├── pylint_tool.py
│       ├── python.py
│       ├── python_report_tool.py
│       └── unittest_tool.py
└── __init__.py
```
```
black src/cloudbuild/

All done! ✨ 🍰 ✨
1 file left unchanged.
```
```
black src/cloudbuild/build/tool/ 

No Python files are present to be formatted. Nothing to do 😴
```
```
black src/cloudbuild/build/tool/*

reformatted src/cloudbuild/build/tool/python.py
reformatted src/cloudbuild/build/tool/pycodestyle_tool.py
reformatted src/cloudbuild/build/tool/unittest_tool.py
reformatted src/cloudbuild/build/tool/mypy_tool.py
reformatted src/cloudbuild/build/tool/python_report_tool.py
reformatted src/cloudbuild/build/tool/pylint_tool.py
All done! ✨ 🍰 ✨
```
**Expected behavior**
Running Black on a directory runs it on all python files within that directory and subdirectories.

**Environment (please complete the following information):**

- Version: both `black-19.10b0` and master
- OS and Python version: Arch Linux, Python 3.7.2

**Does this bug also happen on master?** To answer this, you have two options:
Yes

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment]
This is because by default we exclude the `build` directory, as mentioned under https://github.com/psf/black#command-line-options.

**Comment by AnOctopus** [comment]
Ah, that explains it. Thanks.

**Comment by knatten** [comment]
Would you be willing to re-consider your default exclude patterns? We have several subfolders called `build` in our source code, and it caught me by surprise that these were excluded when I tried to format my source tree.

**Comment by lordmauve** [comment]
I think this is still a bug: the exclude pattern should not match path components that were given on the command line.

The example given above was

```
black src/cloudbuild/build/tool/ 

No Python files are present to be formatted. Nothing to do 😴
```

So the user has told it to act on a specifically specified directory. It has then evaluated *that* directory against the default `--exclude` patterns and concluded it has nothing to do.

IMHO when given a directory as a CLI argument, black should consider the paths of items in the directory relative to the directory given when applying the `--exclude` pattern.

**Comment by lordmauve** [comment]
I should add: this has just bitten us. We have a build farm where projects are checked out under `/build`. We were trying to run

```
black --check /build/someproject
```

for each project, which was silently failing.

**Comment by zsol** [comment]
@lordmauve that is a different bug that's tracked under #438

**Comment by dhimmel** [comment]
In my project, we have a `manubot/build` directory containing a python submodule. We'd like `black` to lint the python files in this directory. What do we add in our `pyproject.toml` under `[tool.black]` to make black not exclude build?

Is it bad practice to name a Python submodule `build`?

**Comment by alongalky** [comment]
For posterity, I ran into this issue because the files were in `.gitignore`, which black apparently excludes by default.

**Comment by Drakan1** [comment]
This seems to still be an issue.

In my case:
`black data_structure/* --diff` 
For a subfolder data_structure, correctly formats the python files. 

But specifying a specific file, e.g.
`black data_structure/player.py --diff`
Gives the same response of `No python files ...` and does not format anything.

It is not in a build folder, the file is not in a .gitignore
And feels like buggy behaviour, even if intended
