### ISSUE TITLE
MANIFEST.in does not match setuptools_scm instructions

### ISSUE THREAD

**Issue by dyve** [psf/black#1199]
Black uses https://github.com/pypa/setuptools_scm/ in `setup.py`.

According to https://github.com/pypa/setuptools_scm/blob/master/README.rst, `MANIFEST.in` should only be used to override the default hooks `setuptools_scm` provides.

The content of `MANIFEST.in` does not seem to exclude files that are included by `setuptools_scm`, nor does it seem to include files that are excluded by `setuptools_scm`.

If you agree, the file `MANIFEST.in` could be deleted, since it has no function and thus causes confusion for people trying to determine the build process.

**Comment by hugovk** [comment]
Makes sense, and one less file to maintain :+1:

Please see PR #1200.
