### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by bersbersbers** [psf/black#1212]
**Describe the bug** See title

**To Reproduce**

1. Take attached file.
2. Run _Black_ on it without any argments
3. See error

**Expected behavior** Works

**Environment (please complete the following information):**
```
C:\Work\Desktop>black bug.py
error: cannot format bug.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\bersbersbers\AppData\Local\Temp\blk_sow6kszn.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

Log:
```
--- src
+++ dst
@@ -13,17 +13,17 @@
             None,  # NoneType
         )  # /arguments
       body=
         Pass(
         )  # /Pass
+        Pass(
+        )  # /Pass
       decorator_list=
       name=
         'bug',  # str
       returns=
         None,  # NoneType
       type_comment=
         None,  # NoneType
     )  # /FunctionDef
-    Pass(
-    )  # /Pass
   type_ignores=
 )  # /Module
```

- Version: `19.10b0`
- OS and Python version: Windows/Linux, 3.7.5

**Does this bug also happen on master?** Yes (note indentation of last `pass`)

[bug.py.txt](https://github.com/psf/black/files/3988975/bug.py.txt)

**Comment by zsol** [comment]
This will be the same root cause as #569, let's keep the discussion there
