### ISSUE TITLE
Allow .git to be an ordinary file, as well as a directory.

### ISSUE THREAD

**Issue by jfine2358** [psf/black#1213]
With git, the .git object need not be a directory. It can also be a suitable ordinary file. For me, git works fine with the following:

```sh
$ cat .git
gitdir: /home/jfine/.gitrepos/scratch.git/
```
However, black uses the code
```python
        if (directory / ".git").is_dir():
            return directory
```
(See https://github.com/psf/black/blob/master/black.py#L3600)

This problem is particularly important when git worktrees are used. (Because git allows .git to be a suitable ordinary file, I regard it as a bug rather than feature, that black doesn't recognise this.)

By they way, there's a great deal I like about black. I've been reading the source, because I want find a configuration file in a similar way. Hence my discovery of the above.

**Comment by JelleZijlstra** [comment]
Good find! Would you mind submitting a PR to fix it?

**Comment by jfine2358** [comment]
Thank you @hauntsaninja and @JelleZijlstra for doing this. You've done the right thing. And I've missed my chance to be a contributor to black!

**Comment by hugovk** [comment]
@jfine2358 Contributing issues is just as important as code, thank you!
