### ISSUE TITLE
Style issue with triple quotes

### ISSUE THREAD

**Issue by justinmoon** [psf/black#1216]
I was following along with the [Ariadne GraphQL server tutorial](https://ariadnegraphql.org/docs/intro) where we defined this beautiful little snippet representing a "Hello, world!" GraphQL query:

```python
type_defs = gql("""
    type Query {
        hello String!
    }
""")
```

Black formatted it into this:

```python
type_defs = gql(
    """
    type Query {
        hello String!
    }
"""
)
```

I'm not sure what the "right thing" is here, but the black formatted version looks much worse to me. It's 2 lines longer and the quotes have mismatched indentation. It's the first time I've had an "ewwww" reaction to black's formatting, so I figured I'd leave you folks some feedback :+1: 

I'm using `black, version 18.9b0`

**Comment by hugovk** [comment]
How's it look with 19.10b0?

**Comment by zsol** [comment]
Let's track this in #256
