### ISSUE TITLE
Define Line Length via config

### ISSUE THREAD

**Issue by joelhess** [psf/black#1218]
It appears as though the only way to change the max line length used to reformat is via the --line-length cmd line option. 

It would be helpful to be able to use a config to drive this so that it can be a shared/committed style.

**Comment by hugovk** [comment]
It's already possible to add it to a `pyproject.toml` config file, for example:

```toml
[tool.black]
line-length = 88
```

https://github.com/psf/black#pyprojecttoml

**Comment by joelhess** [comment]
RTFM! Thank you!
