### ISSUE TITLE
Long import statement violates flake8: H301: one import per line

### ISSUE THREAD

**Issue by kamo-naoyuki** [psf/black#1220]
Black's production is incompatible with H301.

```python
from aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa import (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
)
```

This comma should be removed if it is one import line.
Or, shoud this be dealt as a bug of flake8?

**Comment by JelleZijlstra** [comment]
I think Black is right here. Putting a comma there even for a single element makes the syntax consistent with other list-like syntax elements, like, um, actual lists, and makes the diff smaller if an additional import is added.

**Comment by kamo-naoyuki** [comment]
O.K. I'll ask this in flake8 threads. I don't mind if you close this issue.

**Comment by yukihiko-shinoda** [comment]
I asked in Openstack hacking issue tracker: 
[Bug #2123810 “H301 with long line” : Bugs : hacking](https://bugs.launchpad.net/hacking/+bug/2123810)
