### ISSUE TITLE
Trailing space in comment type hints produces non-equivalent code

### ISSUE THREAD

**Issue by emmacasey** [psf/black#1221]
If a type hint ends in a trailing space then `INTERNAL ERROR: Black produced code that is not equivalent to the source. ` is thrown.

Minimal example:

```
class Part:
    def __init__(self, text: str) -> None:
        self.text = text # type: str 
```
(Note trailing space after the final str.)
Output:
```
error: cannot format tmp.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_kbv5kwij.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
```
cat /tmp/blk_kbv5kwij.log
--- src
+++ dst
@@ -54,11 +54,11 @@
                       id=
                         'self',  # str
                     )  # /Name
                 )  # /Attribute
               type_comment=
-                'str ',  # str
+                'str',  # str
               value=
                 Name(
                   ctx=
                     Load(
                     )  # /Load
```
Obviously this is trivial to fix in any given case by nixing the trailing space and running black again. But in an automated context it might not be so easy.

**Comment by JelleZijlstra** [comment]
We should make the equivalence check actually consider this equivalent, since I'm guessing type checkers don't care about trailing whitespace in type comments.

**Comment by JelleZijlstra** [comment]
This no longer crashes.
