### ISSUE TITLE
Unnatural split on a line with a line-comment

### ISSUE THREAD

**Issue by exhuma** [psf/black#1222]
**Describe the style change** 

A line containing a `type: ignore` comment caused a really weird output. It has split an equality operation *on* the operator which looks very unnatural. Even though the line would fir well into the maximal line length making the split unnecessary.

It is probably easiest to see in the example below.

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

```
     def __eq__(self, other: Any) -> bool:
         if not isinstance(self, other.__class__):
             return False
 
-        return (self.device_ == other.device_ and  # type: ignore
-                self.scope == other.scope and
-                self.id == other.id)
+        return (
+            self.device_ == other.device_
+            and self.scope  # type: ignore
+            == other.scope
+            and self.id == other.id
+        )
```

**Desired style** How do you think _Black_ should format the above snippets:

```
     def __eq__(self, other: Any) -> bool:
         if not isinstance(self, other.__class__):
             return False
 
-        return (self.device_ == other.device_ and  # type: ignore
-                self.scope == other.scope and
-                self.id == other.id)
+        return (
+            self.device_ == other.device_
+            and self.scope == other.scope  # type: ignore
+            and self.id == other.id
+        )
```

**Comment by JelleZijlstra** [comment]
I am going to say this is another case of #379, which is generally about "Black reformatted the code and moved a comment to the wrong place".
