### ISSUE TITLE
Use conditional case in Report rendering when diff is True

### ISSUE THREAD

**Issue by khgitting** [psf/black#1225]
When black is called with either the --check or --diff option, files are not actually reformatted.

In the former, --check, case, black checks *whether* any files would change, and if so, correctly uses the conditional case in the terminal output (eg, "3 files WOULD BE reformatted", my capitalization).

In the latter, --diff, case, the output says "3 files reformatted", when instead the conditional case should also be used, since files are not actually reformatted.

PR forthcoming.

**Comment by khgitting** [comment]
PR: https://github.com/psf/black/pull/1226

**Comment by ichard26** [comment]
Since the fixing PR has been merged, this issue can be safely closed. @khgitting thanks for the PR!

**Comment by ichard26** [comment]
So now I have triage rights... this issue seems like a safe one to start my triaging journey :)
