### ISSUE TITLE
Black no longer removes the trailing comma from function arguments

### ISSUE THREAD

**Issue by alexwlchan** [psf/black#1228]
If a function has a trailing comma in the argument list, black does not remove it.

Start from:

```python
def one(
    a,
):
    pass

def two(
    a,
    b,
):
    pass
```

Run black over that file, and you get:

```python
def one(a,):
    pass


def two(
    a, b,
):
    pass
```

I would expect something more like:

```python
def one(a):
    pass


def two(a, b):
    pass
```

**Environment:**

- Version: I can reproduce this in release and master builds; 19.10b0 and 19.10b1.dev16+g1ab87a3
- OS and Python version: macOS, Python 3.7.5

**Does this bug also happen on master?** Yes.

**Additional context** 

Possibly related issues:

- #880 Trailing comma for function with one arg, which is where I took the minimal example from. Unlike that issue, this seems to affect functions with more than one argument.
- #1136 tracks the bug where it's not collapsing the argument list of `two(a, b)` into a single line.

I had a look for duplicates in the trailing-comma label, couldn't find any.

**Comment by duichwer** [comment]
I think, what is even worse that black also adds a trailing comma to my parameter list.

**Comment by zsol** [comment]
This is the same as #1202.
