### ISSUE TITLE
Exclude-Section

### ISSUE THREAD

**Issue by qohelet** [psf/black#1231]
**Description** I want to be able a certain section of my code to be excluded from the reformatting of black.

**To Reproduce** 
In some of my tests I have to avoid the error:` django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`
 with this imports:
```
import django
django.setup()
from .forms import *
```
In this specific order. But this order is always reversed to:
```
from .forms import *
import django
django.setup()
```
And my code fails.
**Expected behavior** Just give me the freedom to avoid some of my code from being formatted. 

**Environment:**

- Version:  19.10b
- emacs: 26.3
- Python: 3.6.8

**Comment by zsol** [comment]
Black doesn't do import reordering at all, as you can see here: https://tinyurl.com/vm2gj9b

I suspect you want to adjust `isort`'s behavior with `# isort:skip`

**Comment by zsol** [comment]
Having said that, if you do want Black to avoid touching a section of the code, you can use `# fmt: off` and `# fmt: on` comments. Check out the readme for details
