### ISSUE TITLE
Black causes indentation errors on if conditions

### ISSUE THREAD

**Issue by staticdev** [psf/black#1233]
**Describe the bug** A clear and concise description of what the bug is.
After running black version 19.3b0 on a file, it breaks some logic inside if statement

**To Reproduce** Steps to reproduce the behavior:

1. Take this file:
test.py
```
""" Black test """

import datetime
import pytz


def _know_birthday(arg1, arg2):
    """ Ignore this function """
    return True


def my_func():
    """ The if in this function breaks with black -l 80 """
    birth_day = 1
    birth_month = 1
    current_tz = "TZ=America/Sao_Paulo"
    current_time = datetime.datetime.now(pytz.timezone(current_tz))
    if (_know_birthday(birth_day, birth_month)
            and current_time.day == birth_day
            and current_time.month == birth_month):
        return True
    return False


def my_func2():
    """ The if in this function breaks with black -l 80 """
    birth_day = 1
    birth_month = 1
    current_tz = "TZ=America/Sao_Paulo"
    current_time = datetime.datetime.now(pytz.timezone(current_tz))
    if (_know_birthday(birth_day, birth_month) and current_time.day == birth_day and current_time.month == birth_month):
        return True
    return False

```

2. Run _Black_ on it with these arguments `black -l 80 test.py`
3. The if statements in both functions (my_func and my_func2) are converted to the error form:
```
    if (
        _know_birthday(birth_day, birth_month)
        and current_time.day == birth_day
        and current_time.month == birth_month
    ):
        return True
    return False

```
4. See errors (when you run `pylint test.py` to check syntax):

> ************* Module test.test
> test.py:19:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         _know_birthday(birth_day, birth_month)
>         ^   | (bad-continuation)
> test.py:20:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         and current_time.day == birth_day
>         ^   | (bad-continuation)
> test.py:21:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         and current_time.month == birth_month
>         ^   | (bad-continuation)
> test.py:34:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         _know_birthday(birth_day, birth_month)
>         ^   | (bad-continuation)
> test.py:35:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         and current_time.day == birth_day
>         ^   | (bad-continuation)
> test.py:36:0: C0330: Wrong hanging indentation before block (add 4 spaces).
>         and current_time.month == birth_month
>         ^   | (bad-continuation)

**Expected behavior** A clear and concise description of what you expected to happen.
Convert to a form that doesn't break the code.

**Environment (please complete the following information):**

- Version: 19.3b0
- OS and Python version: Linux/Python 3.7.5

**Does this bug also happen on master?** Yes.

**Additional context** No need.

**Comment by zsol** [comment]
Code is not broken, it should run perfectly fine. It's just that `pylint` doesn't like that particular indentation style. I suggest ignoring linters related to formatting if you're using Black.
