### ISSUE TITLE
Preserve r-string prefix capitalization

### ISSUE THREAD

**Issue by janosh** [psf/black#1244]
The [MagicPython](https://github.com/MagicStack/MagicPython) syntax highlighter (and VS Code, Sublime Text and Atom which all use it) interprets upper (`R"foo"`) and lower case r-strings (`r"bar"`) differently. The reason for this is explained in their readme:

> Raw strings are often interpreted as regular expressions. This is a bit of a problem, because depending on the application this may actually not be the most common case. Raw strings can simply be the input to some other processor, in which case regexp-specific highlighting is really hindering the overall readability. MagicPython follows a convention that a lower-case r prefix means a regexp string, but an upper-case R prefix means just a raw string with no special regexp semantics. This convention holds true for all of the legal combinations of prefixes. As always the syntax is biased towards Python 3, thus it will mark Python-2-only prefixes (i.e. variations of ur) as deprecated.

This is a neat feature, especially in cases with more involved string interpolation which are hard to read and easy to mess up without proper highlighting. As a simplified example:

```py
import matplotlib.pyplot as plt

plt.title(R"$y_\mathrm{true}$ vs $y_\mathrm{pred}$")
plt.title(r"$y_\mathrm{true}$ vs $y_\mathrm{pred}$")
```

Note that even GitHub syntax highlighting has this feature. This is what it looks like in VS Code:

![upper](https://user-images.githubusercontent.com/30958850/72980560-ba861f80-3dd2-11ea-85a7-24899d4a3a69.png)
![lower](https://user-images.githubusercontent.com/30958850/72980561-bb1eb600-3dd2-11ea-9397-23092e184fa2.png)

Unfortunately, this feature becomes unusable in conjunction with `black` since `black` automatically lower cases all r-strings.

**Describe the solution you'd like**

Either add an option to `pyproject.toml` to disable automatic lower casing and/or change `black`'s default behavior to preserve string prefix casing. I prefer the latter.

**Additional context**

This behavior was introduced in #198, apparently without being aware that some syntax highlighters treat the cases differently.

**Comment by JelleZijlstra** [comment]
I'm fine with removing the casefolding. Should we do this only for `R`, or is there a reason to do it for all string prefixes?

**Comment by janosh** [comment]
I'm not aware of any other string prefixes where case matters. But then I only did a quick search just now.

**Comment by zsol** [comment]
I would remove it for all string prefixes for consistency.

**Comment by wenzeslaus** [comment]
Was this issue reintroduced?

```
R"""About test"""


def test1():
    R"""Create test data"""
    pass
```

Creates:

```
R"""About test"""


def test1():
    r"""Create test data"""
    pass
```

**Comment by JelleZijlstra** [comment]
Can confirm that we lowercase docstring R prefixes now.
