### ISSUE TITLE
Function definitions inside if blocks introduce whitespace

### ISSUE THREAD

**Issue by nyanpasu64** [psf/black#1249]
**Describe the style change**

Right now, if you `def` a function inside an if block, a new line is introduced between the `if` and the `def`. I think this looks too spaced out and unpleasant to read.

**Examples in the current _Black_ style**

```
if condition:

    def func():
        ...

    func()
```

**Desired style**

```
if condition:
    def func():
        ...

    func()
```

**Additional context** Add any other context about the problem here.

This is related to #196, but that issue seems to be for functions defined directly in other functions, not in blocks.

**Comment by ichard26** [comment]
This falls under issue #450 (via #377). Just recently closed https://github.com/psf/black/issues/1691 for the same reason.
