### ISSUE TITLE
No emojis

### ISSUE THREAD

**Issue by Makogan** [psf/black#1255]
Emojis, among other things, are not universally supported, are not consistent across systems, and require additional formatting on the part of the terminal. Having support for UTF is great, but forcing non ascii characters onto users for something as frivolous as emojis is perhaps better avoided.

**Comment by hugovk** [comment]
See https://github.com/psf/black/issues/223 and https://github.com/psf/black/issues/1031.

**Comment by zsol** [comment]
You can use `--quiet` to disable non-essential output.

**Comment by Makogan** [comment]
If people are repeatedly requesting to remove a feature, it is, perhaps, symptomatic that that feature should not be your default.

**Comment by zsol** [comment]
Look, nobody is forcing anything onto users. My read on this situation is that the vast majority of people using Black are okay with the emojis being part of the output by default. My opinion is that terminals incapable of displaying these characters are broken, not the tools that output them. Your opinion might be different, and that's completely fine.
