### ISSUE TITLE
Invalid value: Path doesn't exist

### ISSUE THREAD

**Issue by EvilManiac26** [psf/black#1258]
C:\Users\name>black problem1.py
Usage: black [OPTIONS] [SRC]...
Try "black -h" for help.

Error: Invalid value for "[SRC]...": Path "problem1.py" does not exist.

I'm confused as to why this is happening? Any solutions?

**Comment by zsol** [comment]
Does the file `problem1.py` exist in `C:\Users\name\problem1.py`?

**Comment by EvilManiac26** [comment]
It exists in C:\Users\name\Documents\Projects

**Comment by zsol** [comment]
Then try `black C:\Users\name\Documents\Projects\problem1.py`

**Comment by zsol** [comment]
I assume this is solved.
