### ISSUE TITLE
f-string usage should be reported when used inside logging

### ISSUE THREAD

**Issue by nicholasamorim** [psf/black#1261]
Using f-strings inside logging can be particularly problematic when using structured logging and tools like Sentry. Not to mention it can be pretty expensive to interpolate thousands/millions of `logging.debug` with no need depending on the log level.

Their immediate rendering means there's no "message and context" but rather only "different messages".

In my opinion, it would be great if this anti-pattern could be reported to the developers.

PyLint implements this as W1201 and W1202.

**Comment by JelleZijlstra** [comment]
Thanks for your suggestion, but Black is a formatter, not a linter. This kind of check is out of scope for Black.
