### ISSUE TITLE
Black fails to parse valid code

### ISSUE THREAD

**Issue by tulustul** [psf/black#1264]
**Describe the bug** Black seems to fail with `Cannot parse` on valid code.

**To Reproduce** Steps to reproduce the behavior:
```py 
def foo1():
    ...


def foo2():
    ...


callables: tuple = foo1, foo2
```
call `black test.py`

result:
`error: cannot format test.py: Cannot parse: 9:23: callables: tuple = foo1, foo2`

**Expected behavior** The file should pass the linting.

**Environment**

- Version: 19.10b0
- OS and Python version: Linux/Python 3.8.1

**Does this bug also happen on master?** yes

**Additional context** The file passes if we change the problematic line to:
`callables: tuple = (foo1, foo2)`
or
`callables = foo1, foo2`

**Comment by JelleZijlstra** [comment]
As background, this syntax was invalid before Python 3.8. We'll need to update the parser to allow it.

**Comment by ichard26** [comment]
See also (a duplicate): #1368

**Comment by SergiyShebotnov** [comment]
Still having this issue in 2024 with black 23.12:
![image](https://github.com/psf/black/assets/133217140/99d866d3-18e6-455f-930f-cd301d80911c)

**Comment by hauntsaninja** [comment]
That's not syntactically valid Python. Whitespace is significant in Python.

(Also in the future, please provide complete examples and avoid posting screenshots)
