### ISSUE TITLE
How to support Snakemake files

### ISSUE THREAD

**Issue by mbhall88** [psf/black#1265]
**Is your feature request related to a problem? Please describe.** A clear and concise
description of what the problem is. Ex. I'm always frustrated when [...]

This issue is more of an exploration of how the best way to approach this issue would be.  

[Snakemake](https://snakemake.readthedocs.io/en/stable/) is a workflow management system, and its workflows are defined in a syntax that is an extension of the Python language (see [here](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/tree/master/rules) for examples).  
There has been a discussion on the snakemake repository (https://github.com/snakemake/snakemake/issues/36) about how best to set up a formatter for Snakefiles that effectively does the same thing as Black.

**Describe the solution you'd like** A clear and concise description of what you want to
happen.

There seem to be three possible solutions to solve this problem (feel free to add/remove any I have missed):

1. Add Snakefile support directly to Black. There is a very active community of Snakemake users who I am sure would be happy to help with this.
2. Create a separate python project that uses the Black API to format the pure Python components of the Snakefiles and writes additional code for formatting the Snakemake sections not supported by Black already.
3. If Black's API is not very useful for external users (or doesn't exist), then write something completely from scratch that has no integration with Black except to potentially use system calls to it for various things.

Any advice/help you can offer in this would be very valued. I have searched around for others who may have tried to do something similar but could not seem to find anything. But if I have missed something, please point me in that direction.

**Comment by zsol** [comment]
I suppose option 2 would be the best way to do this (I've seen other projects do this successfully). Check out [format_str](https://black.readthedocs.io/en/stable/reference/reference_functions.html#black.format_str) to get started

**Comment by mbhall88** [comment]
Thanks for the tip @zsol . I don't suppose you could also point me at a project you've seen do this successfully?

**Comment by goi42** [comment]
I would like to second this request. Option 1 would be, by far, the most useful--it would enable quick Snakefile formatting and ease of access.

**Comment by mbhall88** [comment]
@goi42 I have implemented this as a CLI tool: https://github.com/snakemake/snakefmt

**Comment by goi42** [comment]
@mbhall88 Thanks!

**Comment by iamh2o** [comment]
Awesome! Thank you.
