### ISSUE TITLE
Option not to install black venv and use the system one

### ISSUE THREAD

**Issue by mcepl** [psf/black#1269]
I'm always frustrated when I install this vim plugin to my system, and I have already installed black as a Python library from my system packages (on openSUSE), and the plugin without my consent and against my will dumps yet another directory to my already too crowded ``~/.vim`` directory. And no, I don't want to put venv somewhere else, just don't bother install from PyPI yourself and trust that I am not an idiot and I can install required Python packages myself.

There should be an option for users who don't want to have vim plugin installing anything. In case, after all, I am an idiot, and I forget to install it, then plugin just fails and crash horribly.

**Comment by naught101** [comment]
Duplicate: https://github.com/psf/black/issues/3308

**Comment by ichard26** [comment]
Indeed. Thanks @naught101 for bringing it to our attention!
