### ISSUE TITLE
black should remove trailing spaces in comments

### ISSUE THREAD

**Issue by Dr-Irv** [psf/black#1274]
I'm using Visual Studio Code to write python with black used inside.  Very handy.  But if I am writing comments, especially multiline ones, then pycodestyle gives W293 ("blank line contains whitespace") or W291 of "trailing whitespace"

Here's a simple example:
```python
def silly():
    """
    Next line has spaces at beginning
        
    This line has trailing spaces     
    """
    return None
```
(Note - the spaces are there in the markdown)

**Describe the solution you'd like** 

I think that black should remove trailing spaces in comments.

**Describe alternatives you've considered** 
Hand editing?  Running flake8??

**Additional context** 
```
flake8 foo.py
foo.py:4:1: W293 blank line contains whitespace
foo.py:5:34: W291 trailing whitespace
```
The snip shows how VS Code is showing the lines with extra spaces.

![image](https://user-images.githubusercontent.com/15113894/74550288-21ed4600-4f1f-11ea-867c-d66d55d8fea2.png)

**Comment by ambv** [comment]
This is not a comment. This is a string and Black doesn't interfere with string contents. There's a related issue on doing some formatting of docstrings: #144.
