### ISSUE TITLE
flake8 error E231 after a successful black run

### ISSUE THREAD

**Issue by vytas7** [psf/black#1289]
**To Reproduce** Steps to reproduce the behavior:

1. Take this file: `example.py`
```python
# A set literal with a trailing comma.
{
    "Something": {"hi": {"My", "set", "items",}},
    "Something else": {},
}
```
2. Run _Black_ on it:
```
black example.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
```
3. Run `flake8` on it:
```
flake8 example.py 
example.py:3:46: E231 missing whitespace after ','
```

**Expected behavior** A clear and concise description of what you expected to happen.
Expecting not to get any `flake8` errors barring the different line length setting, and edge cases where black is unable to condense output under 88 chars.

**Environment (please complete the following information):**
```
Python 3.8.1
black, version 19.10b1.dev26+g8fef74c
flake8 3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Linux
```

Also getting the same behaviour with `black-19.10b0`.

**Comment by ambv** [comment]
This is a bug related to #1288 and will be fixed as part of that issue. Thank you for the time to report this!

In the mean time, if you remove the trailing comma by hand, Black won't re-add it.

**Comment by mezhaka** [comment]
This is still reproducible despite the #1288 has been closed.   Would it be possible to re-open this issue?

**Comment by felix-hilden** [comment]
Hi! I tried it on the [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACtAGpdAD2IimZxl1N_Wm_vzTQ-P7e8lcz08_VZa-sDkLSE3ZUMq1MJ3f80cDie3Nxpa9UOjCG6Z1x7y5KiJAmPmsXkLR7rQbogSFFUy_lb2O5B0RMpYy1vKfuTo0gYKixVVH7WtK1sFO2NgqGA-zUAAAAR0EXZyZLfNQABhgGuAQAAqQ6qmrHEZ_sCAAAAAARZWg==), but it's formatted correctly. Do you have a failing example? (meaning unmodified but would expect modifications)

**Comment by mezhaka** [comment]
@felix-hilden My bad.  I used black 19.10b0 and indeed in the most recent 22.1.0 this problem is resolved.
