### ISSUE TITLE
[Bug bounty] Black formatting gallery for chosen PyPI packages

### ISSUE THREAD

**Issue by ambv** [psf/black#1290]
## Bounty amount
$500 paid on merge to an agreed PayPal account.

## Motivation
We need a way to easily see what formatting would Black apply to given PyPI projects. This is especially important to compare formatting changes between two versions of Black.

### Docker image
Create a Docker image running with Python 3.8 which accepts the following arguments:
- `-p`: name of the PyPI source package to download;
- optionally `-v`: version of the PyPI source package to download; 
- version of Black to apply formatting with;
- optionally: `pyproject.toml` for Black to apply formatting with.

There can be multiple pairs of Black version and configs. If there is more than one, the second formatting should be applied over the first one.

### Result
Running the Docker image will produce a sub-directory in the output directory named $PROJECT-$VERSION. It will be a Git repository with the following branches:
- `master`: a commit with the original contents of the downloaded PyPI source package;
- `black-$N`: a commit with `master` reformatted with Black version $N;
- `black-$N+1`: a commit with `black-$N` reformatted with Black version $N+1;
- `black-$N+2`: a commit with `black-$N+1` reformatted with Black version $N+2;
- and so on.

### Example invocations of the tool
* Django 3.0.3, three versions of Black, no pyproject.toml
```sh
$ docker run -it -v /host/directory/for/output:/output black_gallery:latest -p Django -v 3.0.3 19.3b0 19.10b0 master
```
* latest Twisted, two versions, with pyproject.toml
```sh
$ docker run -it -v /host/directory/for/output:/output black_gallery:latest -p Twisted 19.10b0:pyproject-19.10b0.toml master:pyproject-master.toml
```
Note: no `-v` specified, would download "19.10.0" at the time of writing this issue (3.3.2020).

### Support for CPython standard library tests and PyPy
On top of PyPI packages, the tool needs to accept the following special values of `-p` and `-v`:
* when `-p` is "cpython", the project to download is "https://github.com/python/cpython/archive/VERSION.zip" where VERSION is specified with `-v` (for example `-v v3.9.0a4` or `-v master`);
* when `-p` is "pypy", the project to download is "https://foss.heptapod.net/pypy/pypy/repository/VERSION/archive.tar.bz2" where VERSION is specified with `-v` (for example: `-v release-pypy2.7-v7.3.0rc4` or `-v branch/default`).

### Logs
The tool should log output verbosely to stdout.

### Source code location
All source code for this project should be located in a `gallery` directory in the `psf/black` Git repository.

### Can I call dibs on this one?
No, anybody is invited to present us with a pull request as long as this issue is open. If you'd like to announce that you're working on it, submitting a work-in-progress pull request is a great way to do it.

### What if multiple people present pull requests?
In this situation the maintainers of Black will choose the one they like best.

### What if there are multiple authors on the pull request?
The principal author of the pull request receives the full amount. If they decide to split it later, they are free to do whatever they wish.

### Can you use a different platform than PayPal?
No.

### This issue is under-specified.
We're happy to clarify.

### I have a different question.
Ask below.

**Comment by isidentical** [comment]
There is mention of a linked directory called `/output` to put git repository as a result, but I couldn't see anywhere we can put pyproject.toml's and then link as a volume to read them inside the container. Do we free to choose something (like `/input`), or are you going to specify it?

**Comment by ambv** [comment]
Either putting the configs in `/output` on the host side or defining `/input` separately is fine.
