### ISSUE TITLE
Add @cooperlees to maintainers

### ISSUE THREAD

**Issue by ambv** [psf/black#1295]
Hi Ernest,
another favor to ask. I'd like to add @cooperlees to maintainers of Black but since he is not a member of @psf I cannot do it myself. Could you add him to the org?

**Comment by ewdurbin** [comment]
Invitation sent.

**Comment by ambv** [comment]
What took you so long?

**Comment by cooperlees** [comment]
Clicked  on 🖱.

**Comment by ambv** [comment]
Thanks, @ewdurbin 🖤
