### ISSUE TITLE
If Project Name contains Spaces PyCharm Black does not work

### ISSUE THREAD

**Issue by DanielOberlechner** [psf/black#1299]
**Describe the bug** A clear and concise description of what the bug is.
Hi, if the project name contains spaces, black does not work
**To Reproduce** Steps to reproduce the behavior:
Just open a project which contains in the path spaces ...

1. Take this file '/Users/username/project name/project'
2. Run _Black_ on it with these arguments => like the documentation
3. See error => Error: Invalid value for "[SRC]...": Path "/Users/username/PaperRock" does not exist. => name would be "/Users/username/PaperRock Scissors"

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- OS and Python version: [macOs Python 3.8]

**Additional context** Add any other context about the problem here.

I'm not sure, is this a Black problem or is this from PyCharm?
If it is from PyCharm I'm sorry, I'm going to post it there then. But at the moment I'm not sure about that. Sorry if I post it wrongfully. 

Greets,
Daniel :)

**Comment by zsol** [comment]
I suspect this is a bug in the pycharm integration, Black handles spaces in paths just fine

**Comment by Wlodarski** [comment]
When setting up Black as an PyCharm external tool, if you use parameters like ``$FilePath$``, don't forget to put them in quotes, ``"$FilePath$"``

**Comment by kkravch** [comment]
> When setting up Black as a PyCharm external tool, if you use parameters like `$FilePath$`, don't forget to put them inside quotes, `"$FilePath$"`

This works like a charm 😉

**Comment by ichard26** [comment]
Given this has a solution, this should be closed.

**Comment by divineajaegbu** [comment]
Error: Invalid value for 'SRC ...': Path '[file' does not exist. Python Black
