### ISSUE TITLE
Accidental tag?

### ISSUE THREAD

**Issue by hugovk** [psf/black#1303]
`https://github.com/psf/black/releases/tag/''`

https://github.com/psf/black/releases

It's an unusual tag name :)

Also, looks like this brought to light a possible problem in the Travis deploy scripts, there's a "Bad credentials" in the logs:

https://travis-ci.com/psf/black/jobs/296088421

**Comment by zsol** [comment]
I've deleted that release now. Don't really know what created it though. As for the deploy script issue, I likely won't ahve time to investigate until the weekend.

**Comment by danygielow** [comment]
The release doesn't seem to be gone in Github. Please also remove the tag. Or alternatively create a new release with a correct tag.

pre-commit autoupdate still picks up the incorrect tag/release. 
Thank you.

**Comment by zsol** [comment]
Tag is also deleted now, thanks for flagging.
