### ISSUE TITLE
vim plugin way of installing black is broken

### ISSUE THREAD

**Issue by odormond** [psf/black#1304]
**Describe the bug**

The way the vim plugin install black is broken because:
- it does not guarantee the installed `black` will actually be used as it is added at the end of `sys.path` so any other version on the system will be used instead
- it install the latest version of black registered on pypi which can be incompatible with the vim plugin itself, in particular when following the installation instructions as `Plug` will install from master

**To Reproduce** Steps to reproduce the behavior:

1. Add `Plug 'psf/black'` to your vimrc
2. Run `vim -c PlugInstall`
3. Run `vim foo.py -c Black`
4. See error:
```
"foo.py" [New File]
Error detected while processing command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 97, in Black
  File "<string>", line 133, in get_configs
AttributeError: module 'black' has no attribute 'find_pyproject_toml'
```

**Expected behavior**

No error and vim ready to edit the file.

**Environment (please complete the following information):**

- Version: master
- OS and Python version: Linux/Python 3.7.5

**Additional context**

Somewhat related issue about the forced installation of black by the vim plugin: #1269

**Comment by PanagiotisS** [comment]
For anyone interested, until this bug is fixed using commit ce14fa8b497bae2b50ec48b3bd7022573a59cdb1 works fine,
as the commit 8fef74cf527d7fa5f2da78fafc61152c8766d0ad is the one which introduces 'find_pyproject_toml' function.

For example using dein 
```vim
call dein#add('psf/black', { 'rev': 'ce14fa8b497bae2b50ec48b3bd7022573a59cdb1' })
```

**Comment by Qu4tro** [comment]
Using Plug:

```
Plug 'psf/black', { 'commit': 'ce14fa8b497bae2b50ec48b3bd7022573a59cdb1' }
```

**Comment by leblancfg** [comment]
Probably related? I got the following error when installing. Maybe important fact: installed from an activated venv. (:grey_question: )

~~~
subprocess.CalledProcessError: Command '['/home/leblancfg/.vim/black/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
~~~

Using @PanagiotisS' fix made it work.

**Comment by rpdelaney** [comment]
Thanks to @bkjohnson for showing how to pin vim-black to the installed release from pypi using vim-plug:

```
Plug 'psf/black', { 'tag': '19.10b0' }
```

**Comment by dlukes** [comment]
I think this can now be closed (cf. #1318).

**Comment by tommyjcarpenter** [comment]
I hit this issue this morning (June 3 2020), what closes this?

**Comment by dlukes** [comment]
It's the [change in the docs](https://github.com/psf/black/pull/1318/files) that I referenced above. To avoid this issue, you must take particular precautions when installing `psf/black`.

**Comment by dlukes** [comment]
Yep :) 🎉

**Comment by tommyjcarpenter** [comment]
Got it thanks. I hit this issue as well as https://github.com/psf/black/issues/1379 this morning

**Comment by tommyjcarpenter** [comment]
Oh, is #1318 ALSO the fix for 1379?

**Comment by dlukes** [comment]
#1380 is the fix for #1379, strictly speaking (as shown in the issue thread, search for "closed this in") :) But the error in #1379 is a very general symptom, so it's possible you encountered it for a different reason and #1318 helped you resolve it.

**Comment by stigok** [comment]
I have to provide a `branch` to make it work.
```
Plug 'psf/black', { 'branch': 'stable' }
```

**Comment by richtong** [comment]
I'm suddenly getting this black error again even with the branch stable fix. Any ideas? I have externally `brew install black` so the command line I have version 20.8.b1_1

So is table no longer the correct pinning needed? I tried the `{'tag': '19.10b0'}` and this fails with 

```
File <string>, line 63, in <module>
ModuleNotFoundError: No module named 'black'
```

**Comment by EgZvor** [comment]
@richtong check out my fork https://github.com/EgZvor/vim-black it uses the executable available in the system and supports ranges.

**Comment by dlukes** [comment]
@richtong The plugin unfortunately doesn't have a good health check story while at the same time being fairly brittle (the virtualenv can break, the versions can get out of sync). I've found it easiest to just delete the virtualenv and start afresh when I run into trouble. I even added a command for that so that I don't have to remember the particulars:

```vim
function! s:black_reinstall()
  " if using vim-plug: make sure the black plugin is loaded
  call plug#load('black')
  echom "BlackReinstall: Removing Black's virtualenv in ".g:black_virtualenv.'.'
  echom repeat('=', 72)
  python3 import os, shutil, vim; shutil.rmtree(os.path.expanduser(vim.eval("g:black_virtualenv")))
  BlackUpgrade
  echom repeat('=', 72)
  " again, the :PlugUpdate recommendation applies if using vim-plug
  echom 'BlackReinstall: If the issue persists, run :PlugUpdate black and retry reinstalling.'
endfunction

command! BlackReinstall :call s:black_reinstall()
```

@EgZvor may be onto something with his fork -- separating out the plugin and relying on the user to install black manually will probably make it easier to troubleshoot, not to mention more lightweight.

**Comment by fbunt** [comment]
> @richtong check out my fork https://github.com/EgZvor/vim-black it uses the executable available in the system and supports ranges.

@EgZvor Thank you! I've been really frustrated by this bug and the addition of ranges is great.

**Comment by richtong** [comment]
Wow. This is a great idea. The reinstall.

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by richtong** [comment]
And having black installed outside makes sense. It’s the way syntactic works.

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by Chocrates** [comment]
@PanagiotisS does the dein install actually work for you?
When I used that and run `:call dein@install()`  vim can't find the `:Black` command

**Comment by PanagiotisS** [comment]
> @PanagiotisS does the dein install actually work for you?
> When I used that and run `:call dein@install()` vim can't find the `:Black` command

As it was frequently broken, I had actually given up on using it as a plugin and instead I was using `:!black %`. 

So, I just made a minimal vimrc with just dein and black `call dein#add('psf/black', { 'rev': 'stable' })` and dein reports

> [dein] /home/ps/.local/share/nvim/dein/repos/github.com/psf/black_stable 
>[dein] fatal: invalid reference: stable 

And it just installs the master branch 



Suprisingly at the moment of writting it works.

It initialised and subsequently I can run it with `:Black`

```vim
:BlackVersion
Black, version 20.8b1 on Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38)
[GCC 7.3.0].
```

or outside conda env where I do not have black installed

```vim
:BlackVersion

Black, version 20.8b1 on Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)].
````

If I instead use the revision from my previous post,

```vim
 call dein#add('psf/black', { 'rev': 'ce14fa8b497bae2b50ec48b3bd7022573a59cdb1' })
```

it installs the requested revision 

```
± pwd                                                                                                                                                                      
/home/ps/.local/share/nvim/dein/repos/github.com/psf/black_ce14fa8b497bae2b50ec48b3bd7022573a59cdb1
± git status
# HEAD detached at ce14fa8
```

and works without problems again

**Comment by PanagiotisS** [comment]
> @PanagiotisS does the dein install actually work for you?
> When I used that and run `:call dein@install()` vim can't find the `:Black` command

Hi @Chocrates,

As it was frequently broken, I had actually given up on using it as a plugin and instead I was using `:!black %`. 

So, I just made a minimal vimrc with just dein and black `call dein#add('psf/black', { 'rev': 'stable' })` and dein reports

> [dein] /home/ps/.local/share/nvim/dein/repos/github.com/psf/black_stable 
>[dein] fatal: invalid reference: stable 

And it just installs the master branch (dein bug?)

```bash
± pwd
/home/ps/.local/share/nvim/dein/repos/github.com/psf/black_stable
± git status
# On branch master
```

Suprisingly at the moment of writting it works.

It initialised and subsequently I can run it with `:Black`

```vim
:BlackVersion
Black, version 20.8b1 on Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38)
[GCC 7.3.0].
```

or outside conda env where I do not have black installed

```vim
:BlackVersion

Black, version 20.8b1 on Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)].
````

If I instead use the revision from my previous post,

```vim
 call dein#add('psf/black', { 'rev': 'ce14fa8b497bae2b50ec48b3bd7022573a59cdb1' })
```

it installs the requested revision 

```bash
± pwd                                                                                                                                                                      
/home/ps/.local/share/nvim/dein/repos/github.com/psf/black_ce14fa8b497bae2b50ec48b3bd7022573a59cdb1
± git status
# HEAD detached at ce14fa8
```

and works without problems again

```vim
:BlackVersion
Black, version 20.8b1 on Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38)
[GCC 7.3.0].
```

I am using self-built neovim https://github.com/neovim/neovim/commit/71d4f5851f068eeb432af34850dddda8cc1c71e3

As vim cannot find black, most likely is not installed correctly? (Check if the directories are there, the runtimepath has no issues).
Also, I think deleting the black directory `~/.local/share/nvim/black` can help with some problems.
The commands `dein#recache_runtimepath() ` and `dein#clear_state()` are useful (or manually deleted the respective directory and file).

I rarely use Windows so I cannot help you if there are any Windows specific issues.

**Comment by hauntsaninja** [comment]
Closing as per #1293
