### ISSUE TITLE
black is too lenient on Python syntax

### ISSUE THREAD

**Issue by dimaqq** [psf/black#1308]
I accidentally managed to whip up something that `black` accepts but `Python-3.9.0a4` does not:

```py
> cat black-walrus.py
if expiration < now := time.time():
    raise Exception("too late")

> black black-walrus.py
All done! ✨ 🍰 ✨
1 file left unchanged.

> python black-walrus.py
  File "/Users/dima.tisnek/shobosso/black-walrus.py", line 1
    if expiration < now := time.time():
       ^
SyntaxError: cannot use assignment expressions with comparison
```

tested with `black` 19.10 and 729f2d8 from this repo

**Comment by JelleZijlstra** [comment]
Black provides no guarantee that it will detect all invalid Python code, just that it supports all valid Python code.

**Comment by dimaqq** [comment]
I'll note current black 🖤  behaviour here for posterity (`21.5b2`):

`black` All done! ✨ 🍰 ✨ 1 file left unchanged.

`black -l 30` (to force reformat) error: cannot format black-walrus.py: cannot use --safe with this file; failed to parse source file.  AST error message: The requested source code has invalid Python 3 syntax.

`black --fast -l 30`: All done! ✨ 🍰 ✨ 1 file reformatted. the result is:
```
if (
    expiration
    < now := time.time()
):
    raise Exception(
        "too late"
    )
```
