### ISSUE TITLE
Black produced code that is not equivalent to the source (related to comments)

### ISSUE THREAD

**Issue by AlexandreYang** [psf/black#1310]
**Describe the bug**

Seems black is not able to format this code:

```
import ssl

ssl.SSLContext(
    # Some comments
    ssl.PROTOCOL_TLS  # type: ignore
)
```

**To Reproduce**

1. Add this code to a file:

```
import ssl

ssl.SSLContext(
    # Some comments
    ssl.PROTOCOL_TLS  # type: ignore
)
```

2. Run _Black_ on it without any argument
3. See error

Black will output this error:

```
INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/tm/r8m0vyxs1_q0gqttgn969pc80000gn/T/blk_yjsu9m9i.log
```

The log file contains:

```
--- src
+++ dst
@@ -11,25 +11,10 @@
     )  # /Import
     Expr(
       value=
         Call(
           args=
-            Attribute(
-              attr=
-                'PROTOCOL_TLS',  # str
-              ctx=
-                Load(
-                )  # /Load
-              value=
-                Name(
-                  ctx=
-                    Load(
-                    )  # /Load
-                  id=
-                    'ssl',  # str
-                )  # /Name
-            )  # /Attribute
           func=
             Attribute(
               attr=
                 'SSLContext',  # str
               ctx=

```

**Expected behavior**

No error, formatted code.

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: MacOS Catalina / Python 3.8.1

**Does this bug also happen on master?**

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.

It produces incorrect output:
 https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACbAHtdAD2IimZxl1N_WlwxRhR7MSgFSDCyd42ZEyZcQp6kAy4x_I0E1OHVTCg8xMjGR2xGmI7gKBLEvAUIIwMzn8Zd74t3smY2yC-SDUM5vhxhS_rJKmOAQg0EIniK6BGK94Bu-j1C6T2oqIBRWbsJQBHH78hc1jKeH3-NJxk4uQAA_CxTcUjjgVoAAZcBnAEAAL3vAgixxGf7AgAAAAAEWVo=

2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python setup.py test`; and
   - run `black` like you did last time.

Yes, using `master` produces the same error as described above.

**Additional context**

No

**Comment by oefd** [comment]
Pretty sure this is the same issue I had here: https://github.com/psf/black/issues/1287
