### ISSUE TITLE
Black doesn't delete trailing commas in dictionary when shrinking to one line

### ISSUE THREAD

**Issue by rmorshea** [psf/black#1312]
Version: 19.10b

Given the following code:

```python
[
    {
        "items": {
            "properties": {"type": {"const": "array"}},
            "required": ["type"],
        },
    }
]
```

Is shrunk to:

```python
[{"items": {"properties": {"type": {"const": "array"}}, "required": ["type"],},}]
```

Which leaves a trailing commas in place that, according to `flake8` (E231), ought to be removed.

**Comment by dandavison** [comment]
I think this is a dup of https://github.com/psf/black/issues/1288

> Worse yet, in those cases it leaves trailing commas behind when a collection ends up compressed into one line.

**Comment by whatisaphone** [comment]
Prettier has a nice rule:

- multiline sequences always have trailing commas
- single-line sequences never have trailing commas

Easy, simple, consistent. I hope black considers adopting this.

In the meantime, you can "fix" this by downgrading:

```
pip install black==19.3b0
```

**Comment by rmorshea** [comment]
Interesting. What feature-add introduced this bug?

**Comment by JelleZijlstra** [comment]
Yes, this is basically #1288. The behavior is an unfortunate consequence of #826.
