### ISSUE TITLE
Black inserts a space before the ":" in a slice notation under some circumstances

### ISSUE THREAD

**Issue by jonatanj** [psf/black#1323]
**Describe the bug**

Black 19.10b0 seems to insert a space before the ":" in a slice notation under some circumstances.

**To Reproduce**
```
$ cat fisk.py
x = y[2:]
x = y[len("//"):]

$ black fisk.py
reformatted fisk.py
All done! ✨ 🍰 ✨
1 file reformatted.

$ cat fisk.py
x = y[2:]
x = y[len("//") :]

$ pycodestyle fisk.py 
fisk.py:2:16: E203 whitespace before ':'
```

**Expected behavior**

I would have expected no space to have been inserted before the ":" in the second slice. That is, consistent with how black treats the first slice and how pycodestyle thinks it should be.

**Environment**

- Version: Black 19.10b0
- OS and Python version: Linux/Python 3.6.8

**Does this bug also happen on master?**

Yes.

**Comment by jonatanj** [comment]
The Fine Manual says the behavior is by design (https://github.com/psf/black#slices).

**Comment by idgserpro** [comment]
The last comment link is not available, use https://github.com/psf/black/tree/7e4c6bf71fffc36ead970afde46a726144515e87#slices instead:

> PEP 8 recommends to treat : in slices as a binary operator with the lowest priority, and to leave an equal amount of space on either side, except if a parameter is omitted (e.g. ham[1 + 1 :]). It also states that for extended slices, both : operators have to have the same amount of spacing, except if a parameter is omitted (ham[1 + 1 ::]). Black enforces these rules consistently. This behaviour may raise E203 whitespace before ':' warnings in style guide enforcement tools like Flake8. Since E203 is not PEP 8 compliant, you should tell Flake8 to ignore these warnings.

The readme file has been refactored with more information into https://github.com/psf/black/blob/master/docs/the_black_code_style.md#slices. Always check if for updated information:

> PEP 8 recommends to treat : in slices as a binary operator with the lowest priority, and to leave an equal amount of space on either side, except if a parameter is omitted (e.g. ham[1 + 1 :]). It recommends no spaces around : operators for "simple expressions" (ham[lower:upper]), and extra space for "complex expressions" (ham[lower : upper + offset]). Black treats anything more than variable names as "complex" (ham[lower : upper + 1]). It also states that for extended slices, both : operators have to have the same amount of spacing, except if a parameter is omitted (ham[1 + 1 ::]). Black enforces these rules consistently. This behaviour may raise E203 whitespace before ':' warnings in style guide enforcement tools like Flake8. Since E203 is not PEP 8 compliant, you should tell Flake8 to ignore these warnings.
