### ISSUE TITLE
"misplaced type annotation" error with typing on return bracket.

### ISSUE THREAD

**Issue by inkhey** [psf/black#1329]
**Describe the bug** 

Get ast error by typing bracketed content of return statement.

**To Reproduce** Steps to reproduce the behavior:

1. Put this in a file (test.py for example):

```
def a():
    return (
        "str"
    )  # type: str

print(type(a()))
```
2. Run _Black_ with no argument.
3. See error:
```
error: cannot format test.py: cannot use --safe with this file; failed to parse source file.  AST error message: misplaced type annotation (<unknown>, line 5)
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**  
We expect that formatting does work correctly and that black doesn't break.

**Environment (please complete the following information):**

- Version : latest stable available : 19.10b0
- Ubuntu 18.04, pythonOS and python 3.6.9

**Does this bug also happen on master?** To answer this, you have two options:

Bug does not append with the online formatter using master or stable (python version issue) ?

**Other**

A workaround can be : 
 
```
def a():
    return (
        "str"  # type: str
    )

print(type(a()))
```

But in some case, it's less clear (this example is stupid, but i found this issue with a more complex example where it's clearer to have multiple line with bracket return value).

**Comment by JelleZijlstra** [comment]
This is because typed-ast raises an error here, which means that this code will also be rejected by mypy (and likely by Python 3.9, which adds native support for typed-ast, but I haven't checked).

**Comment by ichard26** [comment]
Closing since there's nothing we can reasonably do due to this being an issue with the `typed_ast` library.  A workaround is running Black on Python 3.8+

Thanks for the bug report tho, a bit unfortunate we can't do anything about :(
