### ISSUE TITLE
Excluded files also changed on pre-commit

### ISSUE THREAD

**Issue by SuyashSalampuria** [psf/black#1334]
**Describe the bug** Excluded files also changed on pre-commit. I had excluded migrations  folder from black

My pyproject.toml looks like this
[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | ^myapp/migrations/
)
'''
But still running
```pre-commit run --all-files```
changes the files inside the migrations folder

- OS and Python version: Ubuntu18.04/3.7

**Comment by asottile** [comment]
this is a duplicate of #438
