### ISSUE TITLE
Possible alternatives to the pickle module

### ISSUE THREAD

**Issue by dosisod** [psf/black#1342]
From the [pickle documentation](https://docs.python.org/3/library/pickle.html):

>Warning
>The pickle module is not secure. Only unpickle data you trust.
>It is possible to construct malicious pickle data which will execute arbitrary code during unpickling.
>Never unpickle data that could have come from an untrusted source, or that could have been tampered with.

>Consider signing data with hmac if you need to ensure that it has not been tampered with.

>Safer serialization formats such as json may be more appropriate if you are processing untrusted
>data. See Comparison with json.

Black stores cache data in pickle format. Is it reasonable to assume that the cached pickle files are safe against tampering (whether it be by the user or someone else)? If not, would it be possible to use a file format (perhaps json) to store cache data instead?

**Comment by tiran** [comment]
pickle is only problematic when pickled data comes from an untrusted source and the content of a pickle cannot be verified by other means.

black stores its cache in the home directory of the current user. The home directory of a user is a trustworthy location. If an attacker is able to manipulate or arbitrary files in the home directory of a user, then black's cache files are the least of your problems.
