### ISSUE TITLE
Black breaks flake8's E203 by adding space in slicing expression

### ISSUE THREAD

**Issue by tgy** [psf/black#1343]
**Describe the bug** A clear and concise description of what the bug is.

The following code
```python
processed = ""
splits = [1, 2]
lines = ["test", "test", "test"]
processed += "".join(lines[splits[-1]:])
```
is reformated by `black` as
```python
processed = ""
splits = [1, 2]
lines = ["test", "test", "test"]
processed += "".join(lines[splits[-1] :])
```
where a space is added in `lines[splits[-1] :]`.

This breaks `flake8`

**To Reproduce** Steps to reproduce the behavior:

Just apply black to a Python file containing what I showed above

**Expected behavior** A clear and concise description of what you expected to happen.

I expect black to respect `E203`

**Environment (please complete the following information):**

- Version: `master (959848c)`
- OS and Python version: `macOS 10.15.4`, `Python 3.7.6`

**Does this bug also happen on master?** To answer this, you have two options:

Yes, tested on `master (959848c)`

**Comment by hugovk** [comment]
This is intentional:

* https://github.com/psf/black/blob/master/README.md#slices

**Comment by tgy** [comment]
I see, thanks!
