### ISSUE TITLE
Parsing error for generator expression with implicit tuple

### ISSUE THREAD

**Issue by Horstage** [psf/black#1344]
**Describe the bug** A clear and concise description of what the bug is.
When writing a generator expression `(i**2 for i in range(10))` which returns implicitly a tuple `(i, i**2 for i in range(10))` there is an parsing error.

**To Reproduce** Steps to reproduce the behavior:
The following code (blown up example to get to >88 chars)
```python
def foo():
    return (variable_a, variable_b for variable_a, variable_b in zip(range(10), range(10)))
```
results in
> error: cannot format black_check.py: Cannot parse: 2:35:     return (variable_a, variable_b for variable_a, variable_b in zip(range(10), range(10)))

However,
```python
def foo():
    return ((variable_a, variable_b) for variable_a, variable_b in zip(range(10), range(10)))
```
works just fine and results in 
```python
def foo():
    return (
        (variable_a, variable_b) for variable_a, variable_b in zip(range(10), range(10))
    )
```

**Expected behavior** A clear and concise description of what you expected to happen.
I would expect the same output for both examples

**Environment:**

- Version: 19.10b0
- OS and Python version: Windows 10 with Python 3.7.7

**Does this bug also happen on master?**:
Yes it does
[black.now.sh/?version=master](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACrAHFdAD2IimZxl1N_WlbvK5V9KEd0suDTtUY1JbKiBl4H6EXxj_d755vSxsmT3AHR2faQMpGXiTLdcJGyriKvpHEm89QYGWh2X1L8q_HxLAGdioWymZv6Vy8iBXglNU_P37Rxd4CNYQDOMKm2AXX5BmPBlroAAAAAALbPPainsxxOAAGNAawBAADhNmRascRn-wIAAAAABFla)

**Comment by Horstage** [comment]
Might be linked to #1264

**Comment by JelleZijlstra** [comment]
This is also a syntax error at runtime.

**Comment by Horstage** [comment]
You are absolutely correct 🙈. Than it's an unexpected behavior from PyCharm, that it doesn't show me the syntax error right away.
