### ISSUE TITLE
Wrong Formatting with Type Hint

### ISSUE THREAD

**Issue by AdamMartinCote** [psf/black#1354]
**Describe the bug**: The formatting doesn't seem right for the following code snippet:
```
    def setUp(self) -> None:
        self.phase_advancement: AssessmentPhaseAdvancement = AssessmentPhaseAdvancement.objects.get_or_create(
            phase=self.phase
        )[
            0
        ]
```
Note the the total line length here is 107, which is not coherent with Black's default settings.

**To Reproduce**:

1. put the following code in a file:
```
def setUp(self) -> None:
    self.phase_advancement: AssessmentPhaseAdvancement = AssessmentPhaseAdvancement.objects.get_or_create(phase=self.phase)[0]
```
2. Run _Black_ on it with these arguments: None or `-t py38` or `--p36`
3. See the result above

**Expected behavior**: A formatting under 89 characters, which does not split `[0]` on 3 lines

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: Windows/Python3.8.2

**Does this bug also happen on master?**:  Yes

**Comment by ichard26** [comment]
Closing since Black version 21.5b1 produces way more reasonable and also non line length limit violating code:

```diff
~/programming/oss/black on HEAD (2f52e4b) [$?] via v3.8.5 (black) 
❯ black test.py --check --diff --color -t py38
--- test.py	2021-05-29 04:06:40.530352 +0000
+++ test.py	2021-05-29 04:08:11.162416 +0000
@@ -1,3 +1,4 @@
 def setUp(self) -> None:
-    self.phase_advancement: AssessmentPhaseAdvancement = AssessmentPhaseAdvancement.objects.get_or_create(phase=self.phase)[0]
-
+    self.phase_advancement: AssessmentPhaseAdvancement = (
+        AssessmentPhaseAdvancement.objects.get_or_create(phase=self.phase)[0]
+    )
would reformat test.py
Oh no! 💥 💔 💥
1 file would be reformatted.
```

Thank you for reporting!
