### ISSUE TITLE
Black --check returns 1 when invalid config file is specified

### ISSUE THREAD

**Issue by tobywf** [psf/black#1360]
**Describe the bug**

`--check` returns `1` when invalid `--config` is specified, not some higher error code as implied. This can make debugging issues tricky for CI integrations relying on return codes. I wouldn't go so far as to call it a bug, but it was a bit unexpected to me.

(It also happens without `--check`.)

**To Reproduce**

```console
$ printf "def a():\n    pass\n" | black - --check; echo "return: $?"
def a():
    pass
All done! ✨ 🍰 ✨
1 file left unchanged.
return: 0
$ printf "def a():\n    pass\n" | black - --check --config "foo"; echo "return: $?"
Error: Could not open file foo: Error reading configuration file: [Errno 2] No such file or directory: 'foo'
return: 1
```

**Expected behavior**

`--check` says:

> Don't write the files back, just return the status.  Return code 0 means nothing would change.  Return code 1 means some files would be reformatted.  Return code 123 means there was an internal error.

So I would expect this case to return an error code other than `1`.

**Environment (please complete the following information):**

- Version: `19.10b0`, `master` (both tested)
- OS and Python version: macOS 10.15.3 with Python 3.7.7; and Ubuntu 18.04.4 with Python 3.6.9

**Does this bug also happen on master?**

Yes (tested via cloning and `pipenv shell`)

**Additional context**

This can be very awkward to debug in a CI environment if you rely on return codes only.

**Comment by tobywf** [comment]
I think this could be quite an easy fix. I'm not sure why, but `--config` doesn't require the file to exist:

https://github.com/psf/black/blob/8654e8d7aef5253faa7f8ff31d4be3b0b8b9c392/black.py#L394-L402

`src` does:

https://github.com/psf/black/blob/8654e8d7aef5253faa7f8ff31d4be3b0b8b9c392/black.py#L386-L393

If `exists=True`, then this becomes a [`BadParameter`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L66) click exceptions, which inherits from [`UsageError`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L34), which has [`exit_code = 2`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L43), as does any other invalid parameter.

Instead, it progresses until it tries to read the config file:

https://github.com/psf/black/blob/8654e8d7aef5253faa7f8ff31d4be3b0b8b9c392/black.py#L251-L256

This raises a [`FileError`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L204), which inherits from [`ClickException`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L12), which has [`exit_code = 1`](https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/exceptions.py#L16)

With `exists=True`, this happens instead:

```console
$ printf "def a():\n    pass\n" | black --check --config "foo" -; echo "return: $?"
Usage: black [OPTIONS] [SRC]...
Try 'black -h' for help.

Error: Invalid value for '--config': File 'foo' does not exist.
return: 2
```

Happy to create a pull request if this sounds like a good solution to you?

**Comment by JelleZijlstra** [comment]
Switching to `exists=True` sounds like the right call. Please send a PR!
