### ISSUE TITLE
Please change the project's name.

### ISSUE THREAD

**Issue by CydiaGod666** [psf/black#1363]
Many view the project's name (Black) as incredibly racist and insensitive. I think it should be changed at the developer(s) earliest convince.

Naming a project designed to do all the work for you is incredibly insensitive to the African Americans forced to do slave labor.

Thank you for taking the time to read my issue and I hope you consider making this change.

\- Cydia God

**Comment by iago-lito** [comment]
Can you elaborate on this "Many" you are referring to? I am personally aware of no one viewing this project's name this way, and I can't find any discussion about it online.

**Comment by georgek** [comment]
Just someone trying to manufacture some outrage.

**Comment by oneslash** [comment]
The black is just a color as any other like green or purple. I am not sure how this can offend people.

**Comment by edeediong** [comment]
Could this issue be closed, please?

**Comment by ambv** [comment]
For future reference: the name was coined as a humorous reference to Henry Ford's quote on the Model T: "Any customer can have a car painted any color that he wants so long as it is black." The readme begins with a shortened version of this quote. The logo is a play on the Ford logo.

In no way or form was I referring to any race or ethnicity when choosing the name.

**Comment by mikemonteith** [comment]
Please note this is definitely a troll (see the user's github profile and repos). Nobody thinks the name is racist. Don't feed the trolls 😊

**Comment by Tatsh** [comment]
> Could this issue be closed, please?

And locked.
