### ISSUE TITLE
Use black as a library

### ISSUE THREAD

**Issue by saroad2** [psf/black#1367]
Hey! First of all, thanks for this amazing tool! This really elevates my code significantly.

I would like to write a python main that runs black with a few more checks. As for now, black only can be called as a command in the command line, therefore the only way I could call black is via `subprocess.run`. I would like to use black as a library that I can import. Here is some code example:

```python
import black
from pathlib import Path

source = Path("/this/is/a/path/to/code.py")
black.format_file(source)

code_string = '''
def a_function():
   """This is a function to format."""
   a= b  # This line will be formatted
'''

black.format_string(code_string)

```

The alternative is to use `subprocess.run`, but it seems like something that can be avoided.
What do you think?

**Comment by JelleZijlstra** [comment]
You can already do this! It's not necessarily well-documented and we may provide a more stable API in the future, but you can import black and call it.

**Comment by saroad2** [comment]
Thanks! will do :)
