### ISSUE TITLE
Chokes on annotated unparenthesised tuples

### ISSUE THREAD

**Issue by retnikt** [psf/black#1368]
See upstream python/typed_ast#136. I thought it would be worth reporting here just for information.
Example:
```python
foo: tuple = 5,
```
```
error: cannot format test.py: Cannot parse: 1:14: foo: tuple = 5,
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Comment by zsol** [comment]
That's a syntax error I believe.

**Comment by zsol** [comment]
Correction: it's not a syntax error anymore after Python 3.8

**Comment by ichard26** [comment]
This in itself is a duplicate of #1264, please redirect all future discussion to there. Thanks!
