### ISSUE TITLE
internal error on tuple with trailing comma and redundant parentheses

### ISSUE THREAD

**Issue by aaxelb** [psf/black#1387]
**Describe the bug**
internal error on tuple with trailing comma and redundant parentheses

**To Reproduce**

```sh
$ echo 'foo = ((1, 2,))' > foo.py
$ black foo.py
error: cannot format foo.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/pc/3h2v8dx52xqbzbzw_0dkfs5c0000gn/T/blk_s9044_lt.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

log file:
```diff
--- source
+++ first pass
@@ -1,2 +1,2 @@
-foo = ((1, 2,))
+foo = (1, 2,)
 
--- first pass
+++ second pass
@@ -1,2 +1,5 @@
-foo = (1, 2,)
+foo = (
+    1,
+    2,
+)
 
```

**Expected behavior**
no error, remove the redundant parentheses, format like normal

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: macos 10.13, python 3.6.4

**Does this bug also happen on master?**
yes: [first pass removes the redundant parens](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABOADxdAD2IimZxl1N_WlkOEznFeHor0lCdmsv4bjeJgHXgwTYi0QLVBNTJ7eq0-H_H9YZZQklNHslbXxGnHI3RnwAVGyPeH2rU8QABWE92Poe0H7bzfQEAAAAABFla), then [second pass makes it a multiline tuple](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABMADtdAD2IimZxl1N_WlkOEznFeHjvWr7rXcf1qr2ARoQlnEKgleyFjIJWaTZ_19XlqC1Ne-RavP0oARWWSucAAABHJlBnuljvewABV02VQxHdH7bzfQEAAAAABFla), as in the log above.

**Comment by JelleZijlstra** [comment]
Doesn't reproduce on main.
