### ISSUE TITLE
Add a GitHub Action that runs `gallery` against a list of notable projects

### ISSUE THREAD

**Issue by ambv** [psf/black#1390]
We should be running `gallery` against a list of notable projects in a GitHub Action on any commit and any pull request.

### A commit to master
It should run `black` twice: using the *latest released version* and *the current master*; and diff the codebases. This will allow us to identify which commit introduces some weird and unwanted formatting behavior.

### A pull request
The GitHub action should also run on all PRs too but it needs to compare *current master* versus *current PR* instead of *latest released version* versus *current master*.

### Note
We cannot make the GitHub action "fail" because whether a formatting change is desired or not is in the eye of the beholder.

**Comment by cooperlees** [comment]
So I've started on this - I've wrote a tool `black-primer` that will run whatever black is in PATH in parallel at a level the runner can configure. 

This will enable us to run with Current Master then compare with stable / latest release on CI by uninstalling the editable / TOT version and `pip install black` ...

Once a few more people have played with the tool I'll look to get a PR up to add this into our CI runs unless someone beats me. Docs and code itself are up and linked here.

**Comment by ichard26** [comment]
@cooperlees do you think that `black-primer` is good enough and feature-complete to consider this issue done. You know how much I want to bring down the number of issues we have open and this seems like a good one to close :D

Just look at this (photo)graph!
![riseofblackissues](https://user-images.githubusercontent.com/63936253/102001341-1691b500-3cbf-11eb-8fe5-c699054d8862.png)
