### ISSUE TITLE
Priority of breaking subscripts vs breaking previous elements

### ISSUE THREAD

**Issue by dhalbert** [psf/black#1406]
**Describe the style change** A subscript at the end of a long line of parenthesized elements gets broken in an odd way. The length must be just slightly over the line length.

**Examples in the current _Black_ style**

The length is crucial. The last element must be, e.g., `12345` or `123456` to make this happen
```
a = (123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 12345)[
    0
]
```

**Desired style**
(A last element of `1234567` would generate something like this, so it's an edge case.)
```
a = (
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    123,
    12345,
)[0]
```

This is not terrible, but I was just startled by it when I saw it.

**Comment by graingert** [comment]
there seems to be a few duplicates of this:

https://github.com/psf/black/issues/814
https://github.com/psf/black/issues/1101
https://github.com/psf/black/issues/1406

**Comment by ichard26** [comment]
Indeed this is a duplicate of #814. Thanks for the formatting suggestion!
