### ISSUE TITLE
dict formatted in a non-pep8-compliant format

### ISSUE THREAD

**Issue by WhyNotHugo** [psf/black#1409]
I've found a specific pattern, in which `black` generates code that's not pep8-complaint, and also makes flake8 unhappy:

```
from blah import JsonResponse, Wharever


def something():
    context = Wharever()
    return JsonResponse(
        {
            "results": [
                {"text": obj.name, "id": obj.pk,} for obj in context["object_list"]
            ],
            "more": context["page_obj"].has_next(),
        }
    )
```

By running code through `black`, this is what I got as a result.

The trailing comma in `{"text": obj.name, "id": obj.pk,}` Makes flake unhappy due to there being [no space after the comma](https://www.flake8rules.com/rules/E231.html).

Black should either drop this comma, or leave a space before the closing bracket (I prefer the first, but either option is valid).

This happens both on latest stable and on `master`.

**Comment by JelleZijlstra** [comment]
This is part of #1288.
