### ISSUE TITLE
Use Poetry for dependencies management

### ISSUE THREAD

**Issue by jsparmani** [psf/black#1411]
The repository already has a `pyproject.toml` file. Using **poetry** for dependency management would reduce the number of additional files like `.flake8`, `setup.cfg`, `Pipfile` and keep everything centralised and structured in `pyproject.toml`. Also, operations for adding and removing any packages would be simplified this way.

**Comment by zsol** [comment]
I'm actually working on this in the `poetry` branch

**Comment by Spectre5** [comment]
Looks like poetry was used in the past, but was removed 16 months ago partially in [this commit](https://github.com/psf/black/commit/6bedb5c58a7d8c25aa9509f8217bc24e9797e90d#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).  So you may want to make sure it'll be welcomed back, though I have no knowledge on why it was removed.

**Comment by felix-hilden** [comment]
We recently moved away from Pipenv, and I think we're quite ok with the dev workflow for now.
