### ISSUE TITLE
Parenthesise long expressions in function arguments even if splitting without parentheses is allowed

### ISSUE THREAD

**Issue by chrisjbillington** [psf/black#1420]
Black currently does this:

```python
foo(
    use_scm_version={"local_scheme": "no-local-version"}
    if (os.getenv("GITHUB_ACTIONS") or os.getenv("SOME_OTHER_VAR"))
    else True,
    another_kwarg=False,
)
```

That's two arguments, but at first glance it looks like it might be four since there isn't any extra indentation to show the first is split over multiple lines.

Putting the arg in parentheses adds the extra indentation that makes it clearer:

```python
foo(
    use_scm_version=(
        {"local_scheme": "no-local-version"}
        if (os.getenv("GITHUB_ACTIONS") or os.getenv("SOME_OTHER_VAR"))
        else True
    ),
    another_kwarg=False,
)


```

**Comment by felix-hilden** [comment]
This is a similar request to #2248, which is a bit more detailed and has more thumbs up, so I'll close this issue in favor of it!
