### ISSUE TITLE
Split up README.md + Update Docs Config

### ISSUE THREAD

**Issue by cooperlees** [psf/black#1430]
README.md is getting very large. Let’s split up the components documentation to start with:
- blackd
- black-primer
- editor plugins

Please link from README.md to the specific documentation in the repo or the readthedocs equivalent.

Totally open to other ideas here too.

**Comment by zsol** [comment]
Maybe have a separate doc for the style itself as well?

**Comment by SanketDG** [comment]
How about we move the docs as a whole here and just link from Readme to the Readthedocs link?

**Comment by ichard26** [comment]
It should be noted when linking to the specific documentation in the repo, absolute links should be used so they still function on the PyPI project home page. (I also might not be totally responsible for the larger README...)

**Comment by ichard26** [comment]
@zsol, does that includes `Pragmatism`? I'm assuming yes.

**Comment by zsol** [comment]
I think that section belongs together with the style description, it's a nice context setting
