### ISSUE TITLE
Black should enforce capitals and proper puncuation in docstrings

### ISSUE THREAD

**Issue by Luke-zhang-04** [psf/black#1431]
## Describe the style change ##
Black isn't in compliance with [PEP 257 docstring conventions](https://www.python.org/dev/peps/pep-0257/)

## Examples in the current _Black_ style ##
```
def f():
    """make sure this code is blackened"""
    pass
```

## Desired style ##
```
def f():
	"""Make sure this code is blackened."""
    pass
```

## Additional ##
Is not a duplicate of #144, which only cares about the positioning of the docstrings.

**Comment by JelleZijlstra** [comment]
This feels out of scope to me. It's very possible for docstrings to start with a string that shouldn't be uppercased (like "iPhone"). Black can't understand English (or whatever other language you write your docstrings in) well enough to always get this right.
