### ISSUE TITLE
Wrong line number in error message

### ISSUE THREAD

**Issue by mbarkhau** [psf/black#1434]
I have a file with some invalid syntax on line 4.

```
x = 1+1
print(f"asdfasd {x} asdf")

y = 1+1
print(f"asdfasd {} asdf")
```

When I try to format it, black raises an error, but for the incorrect line number

```shell
$ black --check fmt_error_msg.py
error: cannot format fmt_error_msg.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 2)
$ black --version
black, version 19.10b0
```

I would have expected this to point to line 4.

**Comment by ichard26** [comment]
Seems rather similar to #1263.

**Comment by JelleZijlstra** [comment]
Yes, this is a duplicate

**Comment by mbarkhau** [comment]
Sorry about that, tried the search function but unfortunately there are many many issues.
