### ISSUE TITLE
Black and Flake8 don't agree on one particular formatting

### ISSUE THREAD

**Issue by MennoNij** [psf/black#1437]
There seems to be one instance in our code that triggers a reformat in Black which is not approved by flake8. Given the line
```
yield lst[i:i + n]
```
Black will reformat this to
```
yield lst[i : i + n]
```
This will trigger an error in flake8 however:
```
E203 whitespace before ':'
```
This is with black version 19.10b0 and flake 3.8.1 on Python 3.6.10

**Comment by hugovk** [comment]
This is intentional:

* https://github.com/psf/black#slices

(And a duplicate: https://github.com/psf/black/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+E203 :)

**Comment by danieldugas** [comment]
note that the above link is no longer valid, I believe this is the new url: https://black.readthedocs.io/en/stable/the_black_code_style.html#slices

**Comment by marxin** [comment]
> note that the above link is no longer valid, I believe this is the new url: https://black.readthedocs.io/en/stable/the_black_code_style.html#slices
> 
> >

Moved now to:
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
