### ISSUE TITLE
Two blank lines between class methods

### ISSUE THREAD

**Issue by xxiang4** [psf/black#1443]
The following script is formatted using black. Is there a way to insert TWO blank lines between class methods. I would very much prefer the style for clarity, especially when the methods are long.

```
class Arithmetic:
    def add_one(self, num):
        num += 1
        return num

    def add_two(self, num):
        num += 2
        return num
```

**Comment by jaymody** [comment]
From the first couple lines in the README.md:

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

The point of black is that it's not configurable (with the exception of max line length).

**Comment by JelleZijlstra** [comment]
We are not going to change this aspect of Black's style.

**Comment by Tim-K-DFW** [comment]
I respect that. Is it possible to add a configuration option though? In any case, thank you very much for doing this. 🙏🏼
