### ISSUE TITLE
PEP-440: No final releases

### ISSUE THREAD

**Issue by DustinMoriarty** [psf/black#1445]
All of the black releases are pre-releases such as 19.10b0. There are no final releases such as 19.10 as specified by PEP-440. This makes understanding versions of black confusing because it looks like I am requiring unreleased software in my dependencies.

**Comment by ichard26** [comment]
Yeah, that's something we working on. We once planned our first stable release almost two years ago, but things came up. Don't worry, this is definitely our goal. When? I can't say. We do have a stable label and project that includes the main things that need to be finished until a stable release has a chance of being released.
