### ISSUE TITLE
PEP 8: E203 whitespace before ":"

### ISSUE THREAD

**Issue by badochov** [psf/black#1448]
**Describe the bug** 
Black on slice with arithmetic operation in it results in violation of PEP 8.

**To Reproduce**
Make file with following code.
`[0, 1][0+0:1]`
Run Black with default arguments.
It results in: `[0, 1][0 + 0 : 1]` expected `[0, 1][0 + 0:1]`
`[0, 1][(0+0):1]` results in `[0, 1][(0 + 0) : 1]` which is also not expected.
`[0, 1][(0+0):1:1]` results in `[0, 1][(0 + 0) : 1 : 1]` so it has two incorrect whitespaces before ":"

**Environment (please complete the following information):**

black, version 19.10b0
Linux/Python 3.8.3

**Does this bug also happen on master?** To answer this, you have two options:
Yes it does.

**Comment by zsol** [comment]
This is working as intended. See the readme here for an explanation: https://github.com/psf/black#slices

**Comment by badochov** [comment]
> This is working as intended. See the readme here for an explanation: https://github.com/psf/black#slices

Thank you  haven't seen it.

**Comment by a3n** [comment]
FTR, since the readme file has been refactored, see https://github.com/psf/black/blob/master/docs/the_black_code_style.md .
