### ISSUE TITLE
Trailing comma after **kwargs not removed when targeting py35

### ISSUE THREAD

**Issue by alexomics** [psf/black#1463]
**Describe the bug** 
When running black with `-t py35` code that raises syntax errors is left unchanged.

**To Reproduce:**

_example.py_
```python
def func(
    a_long_variable_name: int = 1000000,
    another_long_variable_name: int = 1000000,
    **kwargs,
):
    pass
```
This example is valid in python 3.7 but not in python 3.5.

1. Run _Black_ on it like so:
    ```bash
    black --target-version=py35 example.py
    ```
1. File remains unchanged

**Expected behavior**
I would expect black to tell me that the trailing comma is a syntax error in the target python version, or remove the trailing comma.

**Environment:**
 - black: 19.10b0
 - OS: Docker using python:3.7-buster (Python 3.7.7 (default, May 16 2020, 07:16:36))

**Does this bug also happen on master?** 
Yes

**Additional context** 
Maybe related #419 ?

**Comment by ichard26** [comment]
This is similar to #1356 but with `**kwargs` and `Python3.5` instead of `*args` and `Python2.7`.
