### ISSUE TITLE
Black produces a long one-liner which previously fitted line length limit

### ISSUE THREAD

**Issue by jack1142** [psf/black#1470]
**Describe the style change**:
I don't know what exactly should Black do in such cases, but it seems weird that _Black_ makes the code that respected line length into a code that doesn't.

I'm also a little surprised with how _Black_ treats parentheses that are near `==` operator but the line length is the bigger problem here than that IMO.

**Examples in the current _Black_ style**
```py
assert (
    stdout
    == "A\x00added_file.txt\x00\tM\x00mycog/__init__.py\x00\tD\x00sample_file1.txt\x00\tD\x00sample_file2.txt\x00\tA\x00sample_file3.txt"
)

assert (
    p.stderr.decode().strip()
    == "error: short SHA1 95da0b57 is ambiguous\nhint: The candidates are:\nhint:   95da0b576 commit 2019-10-22 - Ambiguous commit 16955\nhint:   95da0b57a commit 2019-10-22 - Ambiguous commit 44414\nfatal: Needed a single revision"
)
```

**Desired style**:
(I don't know if it's *desired* style, it's just what the code looked like originally)
```py
assert stdout == (
    "A\x00added_file.txt\x00\t"
    "M\x00mycog/__init__.py\x00\t"
    "D\x00sample_file1.txt\x00\t"
    "D\x00sample_file2.txt\x00\t"
    "A\x00sample_file3.txt"
)

assert p.stderr.decode().strip() == (
    "error: short SHA1 95da0b57 is ambiguous\n"
    "hint: The candidates are:\n"
    "hint:   95da0b576 commit 2019-10-22 - Ambiguous commit 16955\n"
    "hint:   95da0b57a commit 2019-10-22 - Ambiguous commit 44414\n"
    "fatal: Needed a single revision"
)
```

**Additional context**
Might be partially related to #1467 but the second assert does have spaces in the string so _Black_ would normally have something to split on no matter if #1467 was a thing.

This bug appears when black is ran with `--experimental-string-processing` flag. Last time I tried reproducing this, I tested on commit cd3a93a14689f046468ece2a5b1f78863c3c4cd2.

I'm sorry for the amount of issues but I tried to run Black's master on Cog-Creators/Red-DiscordBot's code base which resulted in quite a few of errors and also some undesired (by me) changes which I wanted to at least report even if they're not gonna be changed.

**Comment by jack1142** [comment]
The original code (the one in "Desired style" section) now gets transformed into the code below so I suppose it's fixed. I'll leave closing to the collaborators just in case I've missed something though.
```py
assert (
    stdout
    == "A\x00added_file.txt\x00\t"
    "M\x00mycog/__init__.py\x00\t"
    "D\x00sample_file1.txt\x00\t"
    "D\x00sample_file2.txt\x00\t"
    "A\x00sample_file3.txt"
)

assert (
    p.stderr.decode().strip()
    == "error: short SHA1 95da0b57 is ambiguous\n"
    "hint: The candidates are:\n"
    "hint:   95da0b576 commit 2019-10-22 - Ambiguous commit 16955\n"
    "hint:   95da0b57a commit 2019-10-22 - Ambiguous commit 44414\n"
    "fatal: Needed a single revision"
)
```

**Comment by JelleZijlstra** [comment]
Thanks, closing this issue.
