### ISSUE TITLE
Black is compromising on trailing comma in one line

### ISSUE THREAD

**Issue by uriva** [psf/black#1472]
Black allows this:

```
foo(bar,)
```
and also this

```
foo(bar)
```

Leaving freedom for arguing and inconsistency. I think best decide to go with either one and make the formatter fix it.

**Comment by uriva** [comment]
Duplicated with #725

**Comment by traviswaelbro** [comment]
If this is a duplicate of #725, then can this issue be closed?

**Comment by traviswaelbro** [comment]
Actually, it looks like this and #725 are both duplicates which are being addressed in #1288.

**Comment by uriva** [comment]
sgtm
