### ISSUE TITLE
Wrong insertion of parenthesis transforms expression into tuple

### ISSUE THREAD

**Issue by jbsilva** [psf/black#1474]
**Describe the bug**
Parenthesis insertion transforms a date into a tuple containing that date.

**To Reproduce** 

With -l 79, this code
```
    data_inicio = date.fromisoformat(
        conf.get("data_inicio")) if "data_inicio" in conf else DATA_INICIO_DFT
```
is converted into the following:
```
    data_inicio = (
        date.fromisoformat(conf.get("data_inicio"))
        if "data_inicio" in conf
        else DATA_INICIO_DFT
    )
```

They are not equivalent, as the second is a tuple.

**Expected behavior**
The code should be left untouched, as it was already correct and under 80 columns.

**Environment:**

- Version: 19.10b0
- OS and Python version: GNU/Linux 5.6.14-arch1-1, Python 3.8.2 from conda-forge

**Does this bug also happen on master?**
Yes.

**Comment by JelleZijlstra** [comment]
It is not a tuple. Commas make a tuple, not parentheses. Black has safety checks that ensure that it does not make changes that affect semantics.

We can argue about which style is better, but Black's output is consistent with Black's general style.

**Comment by jbsilva** [comment]
Yes, you're correct. Sorry about that.
A comma was introduced in my original code and made it a tuple, but I can't say that it was because of Black (probably not) and I can't reproduce it anymore.
Thanks for the quick reply.
