### ISSUE TITLE
Add pre-commit-hook github topic to the repository

### ISSUE THREAD

**Issue by ssbarnea** [psf/black#1475]
In order to advertise the black as being also usable as a pre-commit hook, please add the magic `pre-commit-hook` topic to this repository, along side the few others.

This will make Black visible under https://github.com/topics/pre-commit-hook -- and also be the most popular one.

FYI, editing topics can be done only by a repository owner.

**Comment by ssbarnea** [comment]
@JelleZijlstra Can you help with this one?

**Comment by JelleZijlstra** [comment]
Sorry for not responding here. I don't think I have the necessary permissions to do this, so this will require @ambv to use his superior administrative powers.

**Comment by ambv** [comment]
Fixed.
