### ISSUE TITLE
Black fails to find files to reformat

### ISSUE THREAD

**Issue by urbnbob** [psf/black#1479]
**Describe the bug**
Black 19.10 does not seem to be picking up files to check/ reformat.

**To Reproduce** 

Using: Python 3.8.0
Run: `pip install black`
Run: `black --version`
Note: black, version 19.10b0
cd into directory with python files, run: `black .`
Note:
No Python files are present to be formatted. Nothing to do 😴

**Expected behavior**
Black checks files to be reformatted and either indicates that no reformatting was necessary or reformats the files.

**Environment (please complete the following information):**

- OS and Python version: Mac High Sierra 10.13.6

**Comment by JelleZijlstra** [comment]
Do you have these Python files gitignored or excluded in a `pyproject.toml`?

**Comment by urbnbob** [comment]
No. They are checked into their git repo.

**Comment by hugovk** [comment]
Can you try with `black . --verbose`? It may give some helpful info.

**Comment by urbnbob** [comment]
Running from the root of my repo I get (among other things):

`src ignored: matches the .gitignore file content`

Here is the entirety of my .gitignore file:

# Created by pytest automatically.
*

.python-version
.idea/workspace.xml
src/__pycache__/
src/nep/__pycache__/
src/nep/config/__pycache__/
src/nep/processing/__pycache__/
src/nep/processing/clients/__pycache__/
src/nep/processing/clients/aws/__pycache__/
src/nep/processing/schemas/__pycache__/
src/nep/processing/tasks/__pycache__/
src/nep/processing/util/__pycache__/
src/tests/__pycache__/
src/tests/unit/__pycache__/
src/tests/unit/clients/__pycache__/
src/tests/unit/fixtures/__pycache__/
src/tests/unit/handlers/__pycache__/
src/tests/unit/tasks/__pycache__/
src/tests/unit/util/__pycache__/

All of the python files are in src/nep/* or subdirectories. It seems like they should be picked up when running `black .` from the root (or from any relevant subdirectory.

When I run it from the first directory in which there is code I would expect to be checked (a file called processor.py), I get :

processor.py ignored: matches the .gitignore file content

As you can see above, it doesn't seem to match anything in .gitignore.

**Comment by urbnbob** [comment]
Somehow a * was entered into my .gitignore file, not sure how because I never edited it manually, but that was causing everything to be ignored.

**Comment by nk9** [comment]
In my case, the problem was that I was passing a list to `extend-exclude`:

```
# Wrong, wrong, wrong
extend-exclude = ["^/migrations/"]
```

But the setting takes a string, not a list. When I removed the brackets, everything worked as expected.
