### ISSUE TITLE
Black Deletes the Escape Sequence's Leading Backslash

### ISSUE THREAD

**Issue by SoCalDude** [psf/black#1482]
**Describe the bug**

In the _replace(old, new[, count])_ string method, when replacing a double-quote in a string with an escape sequence to preserve the double-quote (using a leading backslash ( \\ ) character), _Black_ deletes the backslash in the _new_ argument. 

Using the optional _count_ argument makes no difference to the aforementioned reformatting behavior.

For an example, refer to the next section below (the "To Reproduce" section).

**To Reproduce**

1. Take this line of python code: 
`"myString".replace('"', '\"')`
2. Run _Black_ on it using default setting (arguments)
3. The line of code incorrectly gets modified to: 
`"myString".replace('"', '"')`

**Expected behavior**

The particular line of code should not be modified by _Black_.

**Environment**

- Local Version: 19.10b0
- Windows 10 Version 1909 (OS Build 18363.836)
- Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] 

**Does this bug also happen on master?**

Yes (on the _Black Playground_ online formatter).

**Additional context** 

(n/a)

**Comment by JelleZijlstra** [comment]
Those strings are the same:
```
In [41]: print(repr('\"'))
'"'

In [42]: print(repr('"'))
'"'
```

**Comment by jeremyarde** [comment]
Another example of the issue is when dealing with json strings:

valid json strings,
```
In [1]: json.loads("{\"json_key\":\"value\"}")

{'json_key': 'value'}
```

turns into the following not valid string after Black formatting
```
In [2]: json.loads("{"json_key":"value"}")

File "<ipython-input-74-22187b96f295>", line 1
    json.loads("{"json_key":"value"}")
                         ^
SyntaxError: invalid syntax
```

**Comment by ichard26** [comment]
@jeremyarde I can't reproduce the behaviour you're see with Black version 21.5b0:

```diff
❯ black a --diff --color
--- a	2021-05-07 14:47:58.410916 +0000
+++ a	2021-05-07 14:50:50.250636 +0000
@@ -1 +1 @@
-json.loads("{\"json_key\":\"value\"}")
+json.loads('{"json_key":"value"}')
would reformat a
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Comment by jeremyarde** [comment]
You solved it @ichard26, adding `--skip-string-normalization` was all I had to do. Thanks for the help!

**Comment by jeremyarde** [comment]
I can reproduce with black 21.5b0

```
> black --version
black, version 21.5b0
> black .\code.py --diff --color
--- code.py     2021-05-07 15:29:36.164961 +0000
+++ code.py     2021-05-07 15:29:51.311743 +0000
@@ -1,4 +1,4 @@
 import json

 print(json.loads('{"json_key":"value"}'))
-print(json.loads("{\"json_key\":\"value\"}"))
+print(json.loads('{"json_key":"value"}'))
would reformat code.py
All done! ✨ �🍰✨✨
1 file would be reformatted.
```

**Comment by jeremyarde** [comment]
^ My mistake, black will not create invalid strings like I originally said. My bad

**Comment by JelleZijlstra** [comment]
I don't think there's any bug here.

**Comment by sean-workman** [comment]
I realize this issue is closed but I ran into the same problem with black version 22.6.0. I'm sure I'm doing a poor job of putting together my regex, but regardless, black stripped the leading backslashes I was using and broke the pattern. 

```
 TAGS = [
     "(?s)",
-    '(White \"(?P<white>\S+)\")',
-    '(Black \"(?P<black>\S+)\")',
-    '(UTCDate \"(?P<date>\d+.\d+.\d+)\")',
-    '(UTCTime \"(?P<time>\d+:\d+:\d+)\")',
-    '(WhiteElo \"(?P<white_elo>\d+)\")',
-    '(BlackElo \"(?P<black_elo>\d+)\")',
-    '(TimeControl \"(?P<time_control>\d+[/\+\d+]{0,})\")',
-    '(Termination \"(?P<termination>(\S+\s){,10}\w+)\")',
-    "(Link .+/(?P<game_id>\d+))",
+    '(White "(?P<white>\S+)")',
+    '(Black "(?P<black>\S+)")',
+    '(UTCDate "(?P<date>\d+.\d+.\d+)")',
+    '(UTCTime "(?P<time>\d+:\d+:\d+)")',
+    '(WhiteElo "(?P<white_elo>\d+)")',
+    '(BlackElo "(?P<black_elo>\d+)")',
+    '(TimeControl "(?P<time_control>\d+[\+\d+]{0,3})")',
+    '(Termination "(?P<termination>(\S+\s){,10}\w+)")',
+    "(Link .+/live/(?P<game_id>\d+))",
 ]
 
 TAG_PATTERN = re.compile(".+".join(TAGS))
```

I suppose I can use the  `--skip-string-normalization` flag, but as mentioned above it seems like default behaviour shouldn't break valid code.

**Comment by JelleZijlstra** [comment]
@sean-workman the before and after strings are the same at runtime.

```
In [19]: print('(White \"(?P<white>\S+)\")')
(White "(?P<white>\S+)")

In [20]: print('(White "(?P<white>\S+)")')
(White "(?P<white>\S+)")
```

**Comment by sean-workman** [comment]
Weird, I must have fixed something else that was the real culprit without realizing. Yikes, sorry for wasting your time!
