### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by sondrelg** [psf/black#1489]
Not sure this is a bug or not, but the following code generates a black error (i run black as a pre-commit hook)

```python
    def example_function(items: list) -> str:
        for item in items:
            for item in items:
                # fmt: off
                var = ''
        # fmt: on
        other_var = ''
        return other_var
```

In the original example, the inner loop is much longer and so the `# fmt: on` line was accidentally de-indented.

If the fmt-statements *need* to have the same alignment, perhaps the handling of this error could be improved upon.

-----------

Error: error: cannot format <path>: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be he
lpful: <path>\blk_mmykp4j7.log

**Comment by williamfzc** [comment]
actually error still happened even after removing `fmt: on` :

```python
def example_function(items: list) -> str:
    for item in items:
        for item in items:
            # fmt: off
            var = ""
    other_var = ""
    return other_var
```

**Comment by sondrelg** [comment]
I understand :) And I'm guessing that also makes it hard to improve upon the error message? 

Once I found what caused my error I realized it was probably not a bug, but a user-error, though in a perfect world it would have been nice if the black error explained that from the start.

Feel free to close the issue :)
