### ISSUE TITLE
Comments in list comprehensions cause breakages

### ISSUE THREAD

**Issue by Ianleeclark** [psf/black#1499]
**Describe the bug**

Having comments within a list comprehension can cause black to blow up.

**To Reproduce** Steps to reproduce the behavior:

Running black (19.10b0) against the following will cause the error:

```python
xs_by_y = {'a': {'nested': [1,2]}, 'b': {'nested': [1,2,3]}}


output = []
for foo in ['a', 'b']:
    output.extend(
        [
            individual for
            # Foobar
            container
            in xs_by_y[foo]
            # Foobar
            for individual in container['nested']
        ]
    )
```

causing the following error log:

```
  File "/home/ian/.virtualenvs/warehouse/lib/python3.7/site-packages/black.py", line 3762, in assert_equivalent
    dst_ast = parse_ast(dst)
  File "/home/ian/.virtualenvs/warehouse/lib/python3.7/site-packages/black.py", line 3686, in parse_ast
    return ast27.parse(src)
  File "/home/ian/.virtualenvs/warehouse/lib/python3.7/site-packages/typed_ast/ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)
xs_by_y = {'a': {'nested': [1, 2]}, 'b': {'nested': [1, 2, 3]}}


output = []
for foo in ['a', 'b']:
    output.extend(
        [
            individual
            for# Foobar container in xs_by_y[
                foo
            ]
            # Foobar
            for individual in container['nested']
        ]
    )
```

**Expected behavior** 

Comments shouldn't ever affect the AST.

**Environment (please complete the following information):**

- Version: black==19.10b0
- OS and Python version: Ubuntu 18.04.4 & Python 3.7.5

**Does this bug also happen on master?** 

Kind-of? Except it doesn't seem to cause an explosion like it does locally. 

See: https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGFAMZdAD2IimZxl1N_WmzAbErO6W20whB8UqORY6avBsePx6WA06SdTM72VoQesVmVn3b8T1Up_2FGsNuFHimXxp-qJrJd6Mush3h7MEK3piUixbZh2M9IYpioOTsOXC4DsFdT_NJ87yJalHXj0w_1dcbQ7028XwJCr7dW3mRmNCmnUBUPFhYvJl5l1JIbIMPXEqda5GATyCS5s50NUQLG7k-pOaHI3aw8fHA6398xUq7SBToxxO64Uv5v7YtLAm2PDptMZ3fO_aHOPgAAACarixe0ayfLAAHiAYYDAABaEM1vscRn-wIAAAAABFla

**Comment by ichard26** [comment]
Duplicate of #563?

**Comment by Ianleeclark** [comment]
@ichard26 Seems I didn't search quite hard enough. Closing and thanks!
