### ISSUE TITLE
Rename name of the repo to diverse term that don't show any racism.

### ISSUE THREAD

**Issue by justice-for-black** [psf/black#1500]
For diversity reasons, it would be nice to rename project's name from "black"(which can be associated to racism) to something else like "rainbow" or "pystyler".

**Comment by stefanoborini** [comment]
Is this real?

**Comment by zserg8** [comment]
Yes, idiots and trolls are absolutely real, unfortunately.

**Comment by cooperlees** [comment]
I understand the good intent of this issue and 100% agree Black Lives Matter. That said, I don't think this issue will spawn healthy discussion, so I will be locking it.

As stated many times before, the name of the project was used in a context having no relation to racial connotations of the word. Renaming this project would cause so much churn for developers all over the world I really think it's unfair to them and the overhead it would place on the volunteer maintainers of the project.
