### ISSUE TITLE
Fail to read .editorconfig with '*' group

### ISSUE THREAD

**Issue by henrik242** [psf/black#1511]
black fails to read an `.editorconfig` with a `*` group:

```
$ black --config .editorconfig .
Error: Could not open file ./.editorconfig: Error reading configuration file: Invalid group name '*'. Try quoting it. (line 1 column 1 char 0)

$ cat .editorconfig
[*.py]
line_length = 140
``` 

black, version 19.10b0, install with Homebrew on macOS 10.15.5

**Comment by ichard26** [comment]
Hi @henrik242.

Unfortunately Black only read and parse a TOML file, not a `.editorconfig` file, which is a modified INI file format. I am not sure whether the TOML specification allows the use of star as a table name. Regardless, Black will not understand the file. Currently, we do not have plans to start accepting other file formats for configuration. 

Is there a piece of documentation that we can improve? Maybe `docs/compatible_configs.md`? I do see how you could misunderstand that piece of docs. Its purpose is to provided Black-compatible configurations of **other tools**, not for Black itself. Black isn't that configurable.

Thanks for the bug report though!

**Comment by henrik242** [comment]
Hi @ichard26, thanks for your comprehensive answer! I totally misread `compatible_configs.md` as you deduced ;)
