### ISSUE TITLE
Change default line length from 88 -> 90

### ISSUE THREAD

**Issue by tevansuk** [psf/black#1512]
I know, I know, this is going to be contentious. Black should change its default line length to 90.

Black's default line length is 88. From the docs

> You probably noticed the peculiar default line length. Black defaults to 88 characters per line,
> which happens to be 10% over 80. This number was found to produce significantly shorter files 
> than sticking with 80 (the most popular), or even 79 (used by the standard library). 
> In general, 90-ish seems like the wise choice.

The problem with 88 is that it is a [well known dog whistle for white supremacists](https://www.adl.org/education/references/hate-symbols/88). I'm not suggesting that anyone involved in choosing 88 as the default initially was aware of this, or chose it for that reason. 

If "90-ish" is the wise choice, lets make it 90 whilst this project is still beta.

**Comment by ichard26** [comment]
Hello @tevansuk! 

This has already been discussed here https://github.com/psf/black/issues/1191. I share your opinion that it is very unfortunate that the value that was chosen happens to be a Nazi symbol. The problem with changing the defaults is that Black is already in use in production environments and changing the most important default would:
1) Possibly break the trust Black currently has among developers;
2) Break CI and pre-commit hooks;
3) Cause well-formatted code across different projects to become not well-formatted, and

would just cause a large amount of developer frustration. Not every user of Black does lock in their configuration in a config file and we can't blame them. In Black's documentation, it clearly says:
> **Pro-tip:** If you're asking yourself "Do I need to configure anything?" the answer is "No". Black is all about sensible defaults. 

As @ [zsol has already said](https://github.com/psf/black/issues/1191#issuecomment-562975586):
> If it's any consolation, none of the core contributors meant the default line length to signify anything other than a practical upper limit on the number of characters in a line that makes python code readable for the majority of people using Black.

Sorry, but I don't think Black will change the default line length.

**Comment by Enerccio** [comment]
seriously we should ban number 88 from everything? Really? SMH at idiots who think that
