### ISSUE TITLE
Different exit codes based on what's been done to the source files

### ISSUE THREAD

**Issue by archpollux** [psf/black#1515]
**Is your feature request related to a problem? Please describe.**
I currently cannot use black in automated tasks, like a pre-commit git hook.

**Describe the solution you'd like**
Have different exit codes based on what has been done to the source files, just like blackd has different status codes.

**Describe alternatives you've considered**
I've considered parsing the output, but exit codes are a lot cleaner.

**Comment by hugovk** [comment]
The `--check` option has different exit codes:

```
--check                         Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted.  Return code 123 means
                                  there was an internal error.
```
https://black.readthedocs.io/en/stable/installation_and_usage.html

**Comment by ichard26** [comment]
Black does return different exit codes codes depending on what happened (and if `--check` was passed). See https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html for more. 

Closing since there's nothing actionable for us.
