### ISSUE TITLE
Specifying target-version in pyproject.toml fails

### ISSUE THREAD

**Issue by stub42** [psf/black#1519]
**Describe the bug**

Specifying target-version in pyproject.toml causes black to fail with an error, indicating black chose to only use the first character of the string.

**To Reproduce**

Create a `pyproject.toml` file in an empty directory containing just the following:

```toml
[tool.black]
target-version = "py34"
```

Run black in that directory to see it fail:

```
$ black .
Usage: black [OPTIONS] [SRC]...
Try 'black -h' for help.

Error: Invalid value for '-t' / '--target-version': invalid choice: p. (choose from py27, py33, py34, py35, py36, py37, py38)
```

**Environment**

- Version: 19.10b0
- OS and Python version: Linux/Python 3.8.2

**Does this bug also happen on master?**

~~Yes~~ No

**Additional context**

Other config items I've tried work fine in pyproject.toml (max-line-length, force-exclude, skip-string-normalization)

**Comment by stub42** [comment]
Fixed on master

**Comment by ssbarnea** [comment]
The irony is that the correct accepted syntax for `pyproject.toml` looks like:
```toml
[tool.black]
target-version = ["py38"]
```
