### ISSUE TITLE
Keep single-module import statements on a single line

### ISSUE THREAD

**Issue by wchargin** [psf/black#1521]
**Describe the style change** A clear and concise description of how the style can be
improved.

Permit `import` statements of a single module to have unbounded line
length.

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

```python
from some.long.package.path import (
    some_long_module_name,
)
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
from some.long.package.path import some_long_module_name
```

**Additional context** Add any other context about the problem here.

The big reason is that `git grep 'import module_name'` is a really
useful tool both for interactive exploration and mass refactorings, and
splitting imports across multiple lines like this makes that much
harder. I guess you can kind of do it with

```sh
git grep -e 'import module_name' -e '^    module_name,'`
```

but that has more false positives and requires much more thought.

For instance, see <https://github.com/tensorflow/tensorboard/pull/3757>,
where we grep for `import.*application`; this only works because the
desired module name happens to be shorter than our line length limit.

IMHO, this falls under the “enables better integration with some
workflow” category of valid reasons for suggestions, as described in the
README.

**Comment by JelleZijlstra** [comment]
If we made this change, we'd instead get complaints that we aren't obeying the line length limit. This would be especially bad if there are multiple imported names (like `from typing import Any, cast, Dict, List, Iterable, NewType, Generic, TypeVar`).

I understand the use case, but I don't think it's something we can reasonably support.

**Comment by ichard26** [comment]
Also `# fmt: skip` workarounds the issue in this case.

**Comment by gschaffner** [comment]
@wchargin Semgrep might be of use to you. E.g. `semgrep -l py -e 'import module_name'`.
