### ISSUE TITLE
Odd Formatting Bug

### ISSUE THREAD

**Issue by e-xe** [psf/black#1523]
**To Reproduce** Steps to reproduce the behavior:
Write this:
```py
posts = [
    {
        "author": "CoreyMS",
        "title": "Blog Post 1",
        "content": "First post content",
        "date_posted": datetime.datetime.utcnow().strftime("%A, %x")
    },
    {
        "author": "CoreyMS",
        "title": "Blog Post 1",
        "content": "First post content",
        "date_posted": datetime.datetime.utcnow() + datetime.timedelta(3).strftime("%A, %x"),
    }
]
```

Press `ctrl + s` to save on vscode with black as the formatter (It does not matter if you do this or run black normally with `black .`
This happens:
```py
posts = [
    {"author": "CoreyMS", "title": "Blog Post 1", "content": "First post content", "date_posted": datetime.datetime.utcnow().strftime("%A, %x")},
    {
        "author": "CoreyMS",
        "title": "Blog Post 1",
        "content": "First post content",
        "date_posted": datetime.datetime.utcnow() + datetime.timedelta(3).strftime("%A, %x"),
    },
]
```

**Expected behavior:**
It keeps that style instead of the (no-offence) ugly formatting

**Environment:**
- Version: Master
- OS and Python version: Kubuntu 20.04 LTS focal fossa (kde 5) with python 3.8.2

**Does this bug also happen on master?**
It does

**Additional context:**
Also with this, black is colliding with flake8. Black makes a code that looks like this:
```py
example = {'one': 'first', 'two': 'second'}
```
To this:
```py
example = {'one': 'first', 'two': 'second',}
```
(It adds the extra `,` at the end without a space)
This raises `missing whitespace after ','flake8(E231)`
Is there a configuration option to either add a space or just not have a trailing comma at the end? I tried to look up in the docs for such configuration option but failed to find it :disappointed: 
Additionally, I cannot see any configuration options in the docs that I can add in the configuration file

**Comment by mx-psi** [comment]
If you add a trailing comma at the end of the  `date_posted` field it should keep it as it is. The behavior is being worked on (see #1288) but that should work for now.

**Comment by e-xe** [comment]
I tried to play with the styling on this dictionary and this is what I wanted:
![image](https://user-images.githubusercontent.com/65941041/85966907-d6749980-b9e0-11ea-8a2c-0bd2bca38c0c.png)
But when I format it I get this:
![image](https://user-images.githubusercontent.com/65941041/85966940-e8eed300-b9e0-11ea-942e-a534d22446c3.png)
Adding a trailing comma also does not fix this :disappointed:

**Comment by mx-psi** [comment]
Maybe I explained myself incorrectly. In your screenshots you are _removing_ the trailing comma, while what I suggested was doing:

```python
posts = [
    {
        "author": "CoreyMS",
        "title": "Blog Post 1",
        "content": "First post content",
        "date_posted": datetime.datetime.utcnow().strftime("%A, %x"),
    },
    {
        "author": "CoreyMS",
        "title": "Blog Post 1",
        "content": "First post content",
        "date_posted": datetime.datetime.utcnow() + datetime.timedelta(3).strftime("%A, %x"),
    }
]
```

which should keep the format.

**Comment by e-xe** [comment]
Nothing changes, even if I copy the same exact code that you sent 😞

**Comment by ichard26** [comment]
For clarity, the "magic trailing comma" feature doesn't work in nested collection literals.

This falls under the scope of #1288 and there is already an issue filed for this bug: #1377.
