### ISSUE TITLE
Support for formatting jinja templates

### ISSUE THREAD

**Issue by ryanwalder** [psf/black#1524]
Given Jinja is a templating language for Python it would be nice if Black could format Jinja templates as well.

Main use case: Formatting the jinja/yaml `sls` format used by [Salt](https://github.com/saltstack/salt) which can get very [jinja heavy](https://github.com/saltstack-formulas/users-formula/blob/master/users/init.sls).

**Comment by H3Atom** [comment]
I also have a use case

**Comment by ScriptAutomate** [comment]
This also impacts [`cookiecutter`](https://cookiecutter.readthedocs.io) templates for Python projects

**Comment by alyssweissglass** [comment]
I am writing a cookiecutter template and would very much like to use `black` to format our code. Is any update on this issue?

**Comment by ichard26** [comment]
No update. This is rather low priority for us maintainers. We would love external contributions though!

**Comment by hauntsaninja** [comment]
I think this is out of scope for this project. Jinja is different enough from Python that this is best explored in another tool.
