### ISSUE TITLE
Line too long: Attribute chain on right-hand side

### ISSUE THREAD

**Issue by joaoe** [psf/black#1525]
Issue code (assume max line length <= 80):
```
    self.some_long_variable_name.some_property_name = self.some_other_property_name.some_long_value
    self.some_long_variable_name.some_property_name = self.some_other_property_name.some_long_method(some_parameter)
```

Black indents this as
```
    self.some_long_variable_name.some_property_name = self.some_other_property_name.some_long_value
    self.some_long_variable_name.some_property_name = self.some_other_property_name.some_long_method(
        some_parameter
    )
```
However, that first line still violates the line length limit.

Suggestion: use parenthesis:
```
    self.some_long_variable_name.some_property_name = (
        self.some_other_property_name.some_long_value
    )
    self.some_long_variable_name.some_property_name = (
        self.some_other_property_name.some_long_method(some_parameter)
    )
```

**Comment by Paul-Aime** [comment]
To add on this, I have a similar case, where this:

```python
da_outliers_loc = (
    (ds.precipitation > ds_qt.precipitation.sel(quantile=qt_values[0])) &
    (ds.temperature > ds_qt.temperature.sel(quantile=qt_values[1]))
)
```

is formatted like this: (tested in the black playground)

```python
da_outliers_loc = (
    ds.precipitation > ds_qt.precipitation.sel(quantile=qt_values[0])
) & (ds.temperature > ds_qt.temperature.sel(quantile=qt_values[1]))
```

which is arguably uglier.

**Comment by yilei** [comment]
Triaging comments:

1. Example from OP https://github.com/psf/black/issues/1525#issue-648293373 is already fixed: [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFHAJNdAD2IimZxl1N_WlbvK5V8G17R4xukEnqRFWVRr90XpIX-hmnTVOToWeZRf_GrZx8A2AaEfckhaRH25L5PW_ALtd3bpkl8RzxoTjWsXBg7yUO9WMT3_MOxHuA5kt8HH3M1mKfN0oK_jOGYB8E91oTCQInUCVr1j_36VS4jnL49T34-HQ-BqJ_DD0nRCXJD6OgOrgQtAAAAQ8cBLZa73ZkAAa8ByAIAANFMAqaxxGf7AgAAAAAEWVo=).
2. [Second example](https://github.com/psf/black/issues/1525#issuecomment-653156210) is a dup of #2156.
3. I'm not sure [third example](https://github.com/psf/black/issues/1525#issuecomment-938866320) is better, at least it's not related to OP.

**Comment by Dr-Irv** [comment]
> 3\. I'm not sure [third example](https://github.com/psf/black/issues/1525#issuecomment-938866320) is better, at least it's not related to OP.

Should I create a new issue for that?

**Comment by JelleZijlstra** [comment]
I think #510 is enough and this one doesn't need to be kept open.
