### ISSUE TITLE
# fmt: on does not reactivate in pytest test

### ISSUE THREAD

**Issue by johnthagen** [psf/black#1530]
**Describe the bug**

`# fmt: on` doesn't turn back on for `pytest` test.

**To Reproduce**
1. Take this file

```py
import pytest

# fmt: off
@pytest.mark.parametrize('n,expected', [
    (1, 1),
    (2, 2),
    (3, 6),
    (10, 3628800),
])
# fmt: on
def test_factorial(n: int, expected: int) -> None:
    # Too many spaces after assert. Expecting black to format.
    assert   n == expected
```

2. Run _Black_ on it with these arguments

```
[tool.black]
line-length = 99
target-version = ["py36", "py37", "py38"]
```

```bash
(venv) $ black .
```

3. See error

**Expected behavior**

```py
import pytest

# fmt: off
@pytest.mark.parametrize('n,expected', [
    (1, 1),
    (2, 2),
    (3, 6),
    (10, 3628800),
])
# fmt: on
def test_factorial(n: int, expected: int) -> None:
    assert n == expected
```

**Environment (please complete the following information):**

- Version:  19.10b0
- OS and Python version: Windows 10/3.8.3

**Does this bug also happen on master?**

No. This may already be fixed in master. The online formatter ran correctly. Please feel free to close if this is a duplicate.

**Comment by florczakraf** [comment]
@johnthagen this has already been fixed in https://github.com/psf/black/pull/1325 on master indeed. [Previous issue](https://github.com/psf/black/issues/560) related to this problem has been closed after that merge. A new black version that incorporates that patch has not been released yet.

**Comment by johnthagen** [comment]
@florczakraf Thank you. I will close this issue.
