### ISSUE TITLE
please address these concerns

### ISSUE THREAD

**Issue by gabroo** [psf/black#1536]
I would like @ambv to address the accessibility concerns asked for in this screenshot. I am not making any claims about the specific single quotes issue at hand but my claim is that you were very disrespectful for not even acknowledging @ofek 's statement.

This behavior does not align with principles outlined in the Python [code of conduct](https://www.python.org/psf/conduct), to which your own [code of conduct](https://github.com/psf/black/blob/master/.github/CODE_OF_CONDUCT.md) links.

@ofek I am sorry that your voice was not heard.

<img width="802" alt="Screen Shot 2020-07-06 at 7 33 54 PM" src="https://user-images.githubusercontent.com/6046841/86693835-e3385500-bfbf-11ea-84e6-357d8677e5b5.png">

**Comment by ofek** [comment]
@gabroo Hello there! While I appreciate your concern, I believe as long as `-S, --skip-string-normalization` exists then all is fair. The CoC was most definitely not broken as the situation is just a differing of opinions.

Also, I'm not sure if you're aware but the use of the word "voice" nowadays is often the prelude to a certain series of events, of which I want no part of 😉 

Could you please close this?

**Comment by gabroo** [comment]
Sure, sorry I just wanted to make sure you weren’t left without a solution. 

I would still personally encourage @ambv to rethink how he handled that situation.
