### ISSUE TITLE
Add a BLACKED badge to repos that use black formatter

### ISSUE THREAD

**Issue by trallnag** [psf/black#1538]
It would be nice to show very prominently that a repository is using the uncompromising **black** formatter, so I thought of a more confident badge design. It would also help more people to get to know **black**.

Maybe something like this? (Done with the tool Green Is My Pepper)

![Annotation 2020-07-07 150350](https://user-images.githubusercontent.com/24834206/86785736-59da5e80-c063-11ea-8d27-883be1d70a2e.png)

Feedback is encouraged

**Comment by hugovk** [comment]
Like this one? :)

[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)

https://github.com/psf/black#show-your-style
