### ISSUE TITLE
Slice operator with dot adds space after colon

### ISSUE THREAD

**Issue by adaamz** [psf/black#1541]
**Describe the style change**
When dot `.` is used in slice operator, Black adds space after that eg. `[: xxx.xxx]`.

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

```python
class C:
    def asdfg():
        a = a[: self.a]
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
class C:
    def asdfg():
        a = a[:self.a]
```

**Additional context**
https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AByAFddAD2IimZxl1N_WlXnON2nzNJyA7rxEz3ITq0VF6LAEbb8KjoOA0E32jq8-3vOetMZNY-7SWYYSAFFbljWM19Vl4J5db4Ol-NrQHqNbH2nFIppRa8bOf3-TQAAd-N_ha7ANnoAAXNzmL-Y7R-2830BAAAAAARZWg==

**Comment by JelleZijlstra** [comment]
This is intended behavior, see https://github.com/psf/black/blob/master/docs/the_black_code_style.md#slices.
