### ISSUE TITLE
Black reindents Py:Percent/Spyder IDE comments destroying them.

### ISSUE THREAD

**Issue by Skylion007** [psf/black#1542]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

Full instructions for reproduce are provided here: https://github.com/mwouts/jupytext/issues/562

**Expected behavior** A clear and concise description of what you expected to happen.
Black shouldn't reindent `# %%` blocks, but it will try to and that causes issues since it not longer represents break points for Spyder, VSCode, JuPyText or other IDEs. Splitting an if statement or function so that Spyder will no longer recognize it as such. Replacing the comments with the equivalent `#%%` leads to the same behavior.

I've even tried to guard these comments with `#fmt: off` and `#fmt: on` but that hasn't worked. My only current workaround is to use sed find and replacements directly after black which unfortunately breaks a lot of the functionality.

The tests [located here](https://github.com/psf/black/blob/c6c8ef76a4d991cd8a7a3b00a816b6db72ecdf04/tests/data/comments3.py) do not cover this edge case unfortunately and should be updated.

**Environment (please complete the following information):**

- Version: [e.g. master] black, version 19.10b0
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] Linux/Python 3.6.7

**Does this bug also happen on master?** To answer this, you have two options:
[Yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACCAF5dAD2IimZxl1N_Wg092zIW6Wg2uUw4-dxJZB6xEs3k4s1rO_NRLjUcOE2Y57ymtsVy_pf3_Yy7Y7WDiTuYGkmAvivJ2PNwYfctZpSGBaiuDze9tbw6qROo-fKVrkUa11sAAACDQ655ZJJW2wABeoMBAAAAXVcWJ7HEZ_sCAAAAAARZWg==)
1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** These features are important for JuPyText jupyter notebook scripts and currently make maintaining them more difficult.

**Comment by JelleZijlstra** [comment]
Let's discuss this in #3668.
