### ISSUE TITLE
import black, black.check(string)

### ISSUE THREAD

**Issue by nschloe** [psf/black#1544]
For checking code snippets in my READMEs, I use [exdown](https://github.com/nschloe/exdown). I would now like to black-check the snippets, too, so I'd love to see something like
```python
import black

black.check(string)
```
working.

**Comment by hugovk** [comment]
See also https://github.com/psf/black/issues/779 and https://github.com/asottile/blacken-docs.

**Comment by felix-hilden** [comment]
Let's discuss the API details on the linked issue (#779). I'll add this case as well.
