### ISSUE TITLE
Issue with blank lines and E301 / E302

### ISSUE THREAD

**Issue by Holt59** [psf/black#1548]
**Describe the bug** When I run `black` on my stubs, it does not add empty blank lines after classes/functions, making `flake8` throwing tons of E301/E302.

**To Reproduce** Steps to reproduce the behavior:

This can be reproduced by running black on this file https://github.com/ModOrganizer2/pystubs-generation/blob/master/stubs/2.3.0a12/mobase.pyi

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):** I would expect two blank lines after classes and one blank line after methods. Even if I add these manually, `black` always remove them.

- Version: 19.10b0
- OS and Python version: Windows 10, Python 3.8.2

**Does this bug also happen on master?** It does not happen with the online master at https://black.now.sh but it happens with the command line black `19.10b1.dev128+g8d036ce`.

**Comment by ichard26** [comment]
Hello @Holt59!

So having looked at the Black source code, typing stubs do in fact have special formatting. The issue requesting `.pyi` support is https://github.com/psf/black/issues/207. In which, the following details can be found:
> * Black automatically formats *.pyi files in a package in addition to *.py files
> * Stub files mostly follow the same convention with a few changes, as follows:
>   
>   * If the body of a function or class is just `...`, don't put it on a separate line, but just put it after the `:`
>   * Don't put blank lines between methods or functions, or between classes with an empty body
>   * Only put one blank line between other classes.
>   * Potentially allow longer lines. Typeshed's coding conventions currently allow infinite-length lines, but I'm not sure we should keep doing that.

These details were [based off this style guide](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions).

Unfortunately, Black will automatically determine whether a to-be-formatted file is a typing stub if it's suffix is `.pyi`:
https://github.com/psf/black/blob/2c5041cfa0e5645275504c070ef7d0ca5609752f/src/black/__init__.py#L782-L783

A solution would be to use Black as a library and call the right functions with the right parameters, although the current non-stable API is not the friendliest to work with. Or do what www.github.com/python/typeshed does and [configure `flake8` to ignore warnings](https://github.com/python/typeshed/blob/a913af9523675dc526acab3cc379d1334bb0602c/.flake8#L15-L17) that don't really make sense for typing stubs. 

Sorry for the possibly underwhelming response. Thanks for the bug report nevertheless, and have a good one!

**Comment by Holt59** [comment]
Thanks for the very detailed answer. 

I indeed found-out that this was caused by the `.pyi` extension, but if these are the "official" rules for stubs, it is kind of normal that black follow them. I will look at the `flake8` configuration to exclude warnings from `.pyi` files.
