### ISSUE TITLE
Configfile not found when reading from stdin on Windows (due to bug in pathlib)

### ISSUE THREAD

**Issue by dhaug-op** [psf/black#1549]
When reading https://github.com/psf/black#where-black-looks-for-the-file, the following commands should find the same ``pyproject.toml`` file:
* ``black --check -v test.py``
* ``type test.py | black --check -v -``

On Linux this seems the case (with ``type`` replaced by ``cat``), but on Windows only the first command finds the ``pyproject.toml`` file if it's in a parent folder. When I discovered this, my journey began. Please find any details about the underlying issue below.

**Steps to reproduce the behavior:**

1. Work on Windows
1. Create a folder with a ``pyproject.toml`` file
1. Create a subfolder and a file ``test.py`` in this subfolder
1. ``cd`` into the subfolder
2. Run _Black_ on it by using the both commands given in the introduction
3. See the different output:
    * ``black --check -v test.py`` says ``Using configuration from <TESTFOLDER>\pyproject.toml.``
    * ``type test.py | black --check -v -`` does not print any information about a config file being loaded

**Expected behavior**: Both commands should find and use the same configuration file, as the [docs](https://github.com/psf/black#where-black-looks-for-the-file) clearly describe, the current working directory is used as base for searching in case of reading from ``stdin``.

**Environment (please complete the following information):**

- Version: 19.10b0 (and master)
- OS and Python version: Windows 10, Python 3.8.2

**Does this bug also happen on master?**: yes

**Additional context**

I researched the issue and found it being caused by a bug in Pythons ``pathlib`` library. As https://bugs.python.org/issue38671 is know for over 6 months and not resolved yet, *black* might want wo circumvent the issue by slightly changing the code.

The bug described here is caused as follows:
* https://github.com/psf/black/blob/8d036ceb3f0a0e0b52276e8d4afe840d1fcad11b/src/black/__init__.py#L5837 calls ``resolve()`` on all source paths
* as described in https://bugs.python.org/issue38671, ``resolve()`` actually does not make the path absolute (as stated in https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve) on Windows, if it does not exist. So ``Path('-').resolve()`` (the ``-`` coming from the input as symbol for reading from ``stdin``) gets ``WindowsPath('-')`` (as opposed to Linux, where it gets ``PosixPath('<CWD>/-')``).
* ``WindowsPath('-').parents`` just yields ``WindowsPath('.')``, so the ``common_base`` calculated in the following lines is just ``WindowsPath('.')`` with empty ``common_base.parents``.

Possible fixes:
* wait for Python to fix the bug in ``pathlib``
* replace `Path(src).resolve()` in https://github.com/psf/black/blob/8d036ceb3f0a0e0b52276e8d4afe840d1fcad11b/src/black/__init__.py#L5837 by ``Path(Path.cwd() / src).resolve()``. This should make sure, the path is really absolute under all circumstances

**Comment by dhaug-op** [comment]
Just if anybody is wondering: the bug described is neither introduced nor fixed by https://github.com/psf/black/pull/1518. It exists before (I discovered it in version 19.10b0) and after (`master` is still buggy).

**Comment by cooperlees** [comment]
If your workaround does not break PosixPath (Non Windows), I'd accept the PR.

**Comment by dhaug-op** [comment]
As discussed for example here: https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/11 this should not break on Windows or Linux, since if the ``src`` given is already absolute, it will be used as anchor. The commenter (which is actually the same guy how is working on a fix for the basic problem) clearly states, something like `Path(src).resolve() if Path(src).resolve().is_absolute() else Path(Path.cwd(), src).resolve()` is not necessary.

**Comment by cooperlees** [comment]
Fixed by #1550
