### ISSUE TITLE
Add test for `A᧚ = 0`

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#1557]
Black v19.10b0 fails to parse certain assignments involving unicode identifiers - [playground link here](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABLADtdAD2IimZxl1N_WjMy7A7oUimP5kl9tNitfjGTgMhZej2xgomiikPHniF7YMrqeF7JYab2JGKtxYQLJtMAAACEQNE3-XEpLQABV0wDcxaqH7bzfQEAAAAABFla).

```python
A᧚
A፩
```

This code is in fact valid Python, as you can confirm by pasting it into a repl or with `compile("A\u19da = 0")`.

Found, as with most of my bugs, via [Hypothesmith](https://github.com/Zac-HD/hypothesmith).  Given that this applies to multiple unicode digit characters, it might be due to unicode digits in identifiers?

**Comment by ichard26** [comment]
Yapf has the same problem, https://github.com/google/yapf/issues/403, `lib2to3` (of which `blib2to3` is built on) doesn't really have full unicode support.

**Comment by ichard26** [comment]
Resolved by https://github.com/psf/black/commit/5e2bb528e09df368ed7dea6b7fb9c53e799a569f first available in 21.12b0 which broadened the acceptable character set for NAMES significantly. Thanks for reporting!

**Comment by JelleZijlstra** [comment]
We should add a regression test to make sure this doesn't regress if we change our tokenizer.
