### ISSUE TITLE
Inconsistent slicing formatting

### ISSUE THREAD

**Issue by elanmart** [psf/black#1563]
**Describe the style change** 
Always add whitespace around the slicing operator.

**Examples in the current _Black_ style** 
```python
a = x[i:]
b = x[i:j]
c = x[i&j]
d = x[i+0:j+1]
```

translates to

```python
a = x[i:]
b = x[i:j]
c = x[i & j]
d = x[i + 0 : j + 1]
```

**Desired style** 

for both `a` and `b` I would expect the whitespace to be added as well, following the logic from the black docs: `PEP 8 recommends to treat : in slices as a binary operator with the lowest priority, and to leave an equal amount of space on either side`. 

```python
a = x[i :]
b = x[i : j]
c = x[i & j]
d = x[i + 0 : j + 1]
```

**Additional context** 
```
$ black --version 
black, version 19.10b0 
```

**Comment by JelleZijlstra** [comment]
We more often get people who complain when we *do* add the spacing. :)

PEP 8 explicitly says not to put spaces around simple slice expressions like these (https://www.python.org/dev/peps/pep-0008/#pet-peeves), and we're unlikely to change that behavior.

**Comment by elanmart** [comment]
@JelleZijlstra I see, thanks, in that case I'm sorry for creating noise.
