### ISSUE TITLE
Black removes empty lines within multiline parenthetical expressions

### ISSUE THREAD

**Issue by pokey** [psf/black#1565]
**Describe the bug**
Black loses empty lines within multiline parenthetical expressions or argument lists.  I use these newlines to delineate structure within long pandas chains, or when I am defining some kind of fixture.

**To Reproduce**

1. Take this file:
```py
foo(
    "bar",
    "baz",

    # Some comment
    "bongo",
)

bar = (
    pd.read_csv("foo")

    .pipe(lambda x: baz(x))

    # Some steps
    .drop_duplicates()
    .rename(bongo="bazman")
)
```
2. Run _Black_ on it with no arguments
3. It outputs the following:

```py
foo(
    "bar",
    "baz",
    # Some comment
    "bongo",
)

bar = (
    pd.read_csv("foo")
    .pipe(lambda x: baz(x))
    # Some steps
    .drop_duplicates()
    .rename(bongo="bazman")
)
```

**Expected behavior**
I'd expect the input to be unchanged, but instead it loses the newlines inside the parenthetical expressions and argument lists.  Also, if there are no comments, it collapses the whole thing, which is also not ideal when I've tried to break the chain / arg list into multiple sections

**Environment (please complete the following information):**

- Version: [e.g. master] `black, version 19.10b0`
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] MacOS, Python 3.8.0

**Does this bug also happen on master?** Yes

**Additional context**
Maybe this is not a bug?  Seemed like a bug, but I guess it's possible this behaviour is as intended

**Comment by JelleZijlstra** [comment]
I'm inclined to say this is expected behavior. Perhaps in rare cases it's intentional formatting to have newlines within an expression (similar to newlines between statements, which we do preserve), but it's probably more common for the newlines just to be an accidental feature that we should standardize away.

**Comment by pokey** [comment]
Not sure how common accidental newlines are, but I use them plenty when writing [pandas method chains](https://tomaugspurger.github.io/method-chaining.html) to group operations.  Definitely makes the chains tougher to read when everything gets squashed together

**Comment by JelleZijlstra** [comment]
We try to minimize changes in the stable style now (https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy). This is not a common request and it has the potential to make Black's style less consistent, so I am closing it.

**Comment by mhsmith** [comment]
Further discussion: 
* #2805.
