### ISSUE TITLE
Black output junitxml for CI pretty integration

### ISSUE THREAD

**Issue by falcorocks** [psf/black#1568]
* Feature: I use black in CI (gitlab) in my organisation to enforce standardised code. I know this sounds ridiculous, but black output (together with the gitlab job output log) can look a bit intimidating to people unfamiliar with these tools.
Gitlab allows for pretty printing of reports from test tools (like pytest or mutmut) within a merge request, other CI tools do as well. The "standard" format for these tests output is junitxml. See for example gitlab section about it https://docs.gitlab.com/ee/ci/junit_test_reports.html.

* Solution: it would be cool if black supported a junitxml output!

**Comment by MReinisch** [comment]
My organization started using black in gitlab ci pipelines, too.

I started working on implementig this feature on a Fork.

**Comment by JelleZijlstra** [comment]
As mentioned on the linked PR, I'm making the call that this is out of scope for Black right now.

**Comment by dosas** [comment]
https://github.com/quantum-0/black-junit
