### ISSUE TITLE
Search for pyproject.toml to user root regardless of .git presence

### ISSUE THREAD

**Issue by danrneal** [psf/black#1577]
When I have a project that does not have a pyproject.toml file, such as a project without a style guide.  I would still like my code to use a system-wide default for black config.  Ie I would like to place a config file in my user root directory for a system wide default.  I am able to that with a .flake8, .pylintrc, and .isort.cfg file in this directory for system wide default.  Isort also allows to parse a pyproject.toml in the user root as well.  If black did the same, it would make things very tidy.  If this is undesirable for the maintainers, I understand, but wanted to suggest it in case it is something willing to be considered.

**Comment by dquitmann-op** [comment]
I would also like a fallback to a global default ``pyproject.toml``. If this is something, the maintainers are interested, I would be happy to write a PR for this. Can we get some hint, if this work would be worth it?

**Comment by stinos** [comment]
Would be good if this gets fixed, but on the other hand: I'd rather have black search upwards like other tools do, so without stopping at .git and other directories.
