### ISSUE TITLE
fmt: on/off ignores comments unless code also present

### ISSUE THREAD

**Issue by djlondon** [psf/black#1578]
`fmt: off/on` doesn't disable black formatting for comments unless code is also present.

The following:
```
# fmt: off
#setup: device 3423
# fmt: on
```
Yields:
```
# setup: device 3423
```

But, add some code:
```
# fmt: off
#setup: device 3423
black = 'test'
# fmt: on
```
and the comment is also ignored (as desired).

- Version: Lastest (19.10b0)
- OS and Python version: macOS 10.15.5/Python 3.8.2

Also happens on master.

**Comment by hugovk** [comment]
Duplicate of https://github.com/psf/black/issues/1245?

**Comment by ichard26** [comment]
Thanks @hugovk, yes, this is a duplicate of #1245. Thanks @djlondon for filing the bug report,  good to know that this issue still exists on current master!
