### ISSUE TITLE
Release new version onto PyPI

### ISSUE THREAD

**Issue by johnthagen** [psf/black#1583]
The last version of `black` released to PyPI is [almost 10 months old, released Oct 2019](https://pypi.org/project/black/19.10b0/). Meanwhile, [there have been many important fixes committed to the `master` branch since then](https://github.com/psf/black/pulls?q=is%3Apr+is%3Amerged).

Could a new release be uploaded to PyPI?

**Comment by JelleZijlstra** [comment]
We're hoping to do this soon! However, there are some important issues (#1575, #1581) that should be fixed before a release; any help dealing with those would be appreciated.

**Comment by davidszotten** [comment]
i think #1575 is now fixed (possibly pending #1600). was #1592 enough for #1581 or is more work needed?

**Comment by JelleZijlstra** [comment]
I think #1575 and #1581 are OK now, but I found several other crashes (essentially, the most recent entries in https://github.com/psf/black/issues/created_by/JelleZijlstra), and I'm hoping we'll be able to resolve those before the release too.

**Comment by johnthagen** [comment]
[`black 20.8b0` has been released!](https://pypi.org/project/black/20.8b0/)
