### ISSUE TITLE
Internal Error ") :"

### ISSUE THREAD

**Issue by mmcewen-g** [psf/black#1588]
The formatter notices this bug itself, and politely asked me to file an issue:

```
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  
Please report a bug on https://github.com/psf/black/issues.
```

Here's a repo:
1. take this file
```
very_long_variable_name = 0
very_very_long_variable_name = 1
extraordinarily_long_variable_name = 2

if assignment_expression := very_long_variable_name + very_very_long_variable_name > extraordinarily_long_variable_name:
    print("fubar")
```

2. format it, and get the error with the following log
```
--- source
+++ first pass
@@ -1,8 +1,10 @@
-
 very_long_variable_name = 0
 very_very_long_variable_name = 1
 extraordinarily_long_variable_name = 2
 
-if assignment_expression := very_long_variable_name + very_very_long_variable_name > extraordinarily_long_variable_name:
+if (
+    assignment_expression := very_long_variable_name + very_very_long_variable_name
+    > extraordinarily_long_variable_name
+):
     print("fubar")
 
--- first pass
+++ second pass
@@ -3,8 +3,8 @@
 extraordinarily_long_variable_name = 2
 
 if (
     assignment_expression := very_long_variable_name + very_very_long_variable_name
     > extraordinarily_long_variable_name
-):
+) :
     print("fubar")

```

- Version: black == 19.10b0
- OS and Python version: Linux/Python 3.8.5

**Comment by mmcewen-g** [comment]
Seems to be resolved on master?

https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE9AJxdAD2IimZxl1N_Wmp_J_tu2Yxt5S2uR7Vve9f5yNEzzTShAhCtvgdvqv04MD4kSBFn826X8RroICrEU1oEv00MLBkH4ky98TWUCpfdURQX8swoBa8CVft-6XTFZtoEgEOCb9RelK9R2Ox5OMPOpkB94cBaVCJlSltgSyyBCBxkBTZ268Aa_ksxMEsOcSUsyBGNRnHcx46jb1uJ_mgzrwD12i1h9jcpdQABuAG-AgAAsoGF9rHEZ_sCAAAAAARZWg==

**Comment by ichard26** [comment]
> Seems to be resolved on master?

No :(
```console
(black-rHKUX7ap) R:\Programming\black>type test.py
very_long_variable_name = 0
very_very_long_variable_name = 1
extraordinarily_long_variable_name = 2

if assignment_expression := very_long_variable_name + very_very_long_variable_name > extraordinarily_long_variable_name:
    print("fubar")

(black-rHKUX7ap) R:\Programming\black>black test.py
error: cannot format test.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\User\AppData\Local\Temp\blk_hpuu4wvb.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

That's an UI issue with that site. It runs with `--fast` which is rarely used as `--safe` is the default. Ironically, running with `--fast` in this case was better than running with `--safe` but usually not.

**Comment by hugovk** [comment]
Hmm, I was going to make a PR to Black Playground to remove `--fast`, but couldn't find it. Here's the config it uses:

https://github.com/jpadilla/black-playground/blob/439d825ae07fc478e0bce671973d295f46691884/api/app.py#L85-L90
