### ISSUE TITLE
Provide more helpful error message with python3 -m py_compile ...

### ISSUE THREAD

**Issue by osamuaoki** [psf/black#1604]
Error message produced by **black** is sometimes cryptic.  Here is one example with one wrong character accidentally inserted to the code at line 403.  It complains at seemingly unrelated line 169 as:
```
$ black error_1_char 
error: cannot format error_1_char: Cannot parse: 169:33:                     print(l, file=file)
Oh no! 💥 💔 💥
1 file failed to reformat.
```
If you know python well, it's not so difficult to find the root cause of  this failure by doing:
```
$ python3 -m py_compile error_1_char 
  File "error_1_char", line 403
    if item.number_ref != translation.items[j].number_ref(:
                                                          ^
SyntaxError: invalid syntax
```
In light of this, I would like to request to add one of the following feature options.

Feature option 1:
In case of failed reformat, please add an line to urge user to run `python3 -m py_compile ` _programname_`.py` to find the syntax error

Feature option 2:
In case of failed reformat, please run `python3 -m py_compile ` _programname_`.py` for user on all failed files so user see the syntax error. 

I attach an example code with error.
[error_1_char.gz](https://github.com/psf/black/files/5075705/error_1_char.gz)

**Comment by ichard26** [comment]
The problem with Black misidentifying which line has invalid syntax when doing AST sanity checks has already been reported as #1263. Black tries all Python versions when parsing the input. So when there is a parse error Black tries a lower version until Python 2.7. So when parsing with all versions fail, the parse error from Python 2.7 is the one shown to the user.

**Comment by JelleZijlstra** [comment]
#2178 provides an alternative suggestion for fixing this. Using `-m py_compile` isn't an option because Black may not know where to find a Python binary that can parse the affected file. I'm closing this in favor of #2178.
