### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by Yukti-09** [psf/black#1606]
Code:
```
def func:
return('hello')
```
Black cannot fix the indentation and it returns  
```
1 file failed to reformat.
```
We could add an enhancement to fix the indentation.

@JelleZijlstra

**Comment by JelleZijlstra** [comment]
It's not Black's job to fix syntax errors. Simple cases may seem clear but in general it's going to be hard to figure out what the user intended, which goes against Black's safety guarantees.

**Comment by Yukti-09** [comment]
Simple issues such as Tab Error can be added. 

It would enhance black.
