### ISSUE TITLE
Update editor integration docs at readthedocs

### ISSUE THREAD

**Issue by dsabsay** [psf/black#1624]
I had trouble integrating vim with vim-plug as shown [here](https://black.readthedocs.io/en/stable/editor_integration.html):
```
Plug 'psf/black'
```

I noticed [this page](https://github.com/psf/black/blob/master/docs/editor_integration.md#vim) recommends using the `stable` branch:
```
Plug 'psf/black', { 'branch': 'stable' }
```
and my problem was fixed. I later ran into a different problem, but this comment still stands. There's some inconsistency in the docs that should be fixed.

It wasn't obvious to me how the readthedocs content gets built, or I would try to fix myself.

**Comment by ichard26** [comment]
Hi @dsabsay.

Those pages are pretty much the same files. The first one you linked is the version from when the `stable` branch was last updated, which happens to be 10 months ago! While the other one is the newest version available (i.e. the `master` branch). Look at the URLs, you can tell what branch the docs are from. 

Fortunately on ReadTheDocs, you can change what version of the documentation you'd like to read by pressing/clicking the black box in the bottom right corner. 

I don't see anything that is actionable and so I will close this issue. Thanks!

**Comment by dsabsay** [comment]
@ichard26 Ah yes, silly me :) Thanks for your reply.
