### ISSUE TITLE
Black splits ternary to multiline without indent

### ISSUE THREAD

**Issue by CrazyIvan359** [psf/black#1625]
**Describe the bug**
Black splits a ternary expression that exceeds the line length limit on `if` and `else` keywords when said expression is within another set of parentheses eg. a function call with named arguments. The resulting code does not read nicely as the lines appear at the same indent and read as if they are 3 separate lines and not a single expression. 

**To Reproduce**
Example expression (assume it would exceed the line limit):

```python
func(v="a" if True else "b")
```

Results in an output of:

```python
func(
    v="a"
    if True
    else "b"
)
```

**Expected behavior**

Output along the lines of:

```python
func(
    v="a"
        if True
        else "b",
)
```

Or:

```python
func(
    v=(
        "a"
        if True
        else "b"
    ),
)
```

**Environment:**

- Version: 19.10b0
- OS and Python version: Ubuntu 20 / Python 3.8.2

**Does this bug also happen on master?**

Yes. Tested using the online tool (adjust line length limit to something like 15).

**Comment by JelleZijlstra** [comment]
That's not a syntax error, but I agree that it's suboptimal formatting. This is then a similar issue to #1563.

**Comment by CrazyIvan359** [comment]
Oh yes, I was rushing and fired it into repl.it as a variable assignment not an argument to test. Still doesn't read nicely though, all at the same indent, as you say.

**Comment by ambv** [comment]
I don't agree this is suboptimal. It looks weird only until you get used to it. This behavior is consistent with all other operators (see `and`, `or`, `+`, `-`, and so on) as well as list comprehensions. Spending an additional indentation level gives you no additional information.

**Comment by CrazyIvan359** [comment]
@ambv it sure does take getting used to... Thank you for the insight.

**Comment by wchinfeman-cedar** [comment]
IMO the additional indentation will tell you "the prior lines are incomplete"

Like, if I see 
```
many_arg_function(
  foo=None
  if condition()
  else 100
  bar=200
```

Then it's easy for me to accidentally just conclude `foo=None`.  Just because it's actually subtle for me to recognize that the following two lines are part of the "foo" assignment.

But if you injected an extra layer of indentation it would tell me, "the assignment for `foo` takes place across more than 1 line"
