### ISSUE TITLE
use `from __future__ import annotations` to imply `--target-version=py37`

### ISSUE THREAD

**Issue by graingert** [psf/black#1630]
**Is your feature request related to a problem? Please describe.**
I'd like trailing commas after `**kwargs` to be supported in files starting, `from __future__ import annotations`

**Describe the solution you'd like** use `__future__ imports annotations` to imply `--target-version=py37`

**Describe alternatives you've considered** I've not

**Additional context** N/A

**Comment by ambv** [comment]
Awesome idea actually.

**Comment by graingert** [comment]
@ambv it also makes me wonder how `from __future__ import print_function` should be interpreted because it's ambiguous:

Is it an explicit declaration of py2 support being required, or is it a legacy that should be removed?

**Comment by ambv** [comment]
Due to Python 2/Python 3 polyglot code, `print_function` is still accepted as a (nullop) future in Python 3.10. So, what it *could* tell us at best is that "we are 2.7 or 3.0+" which isn't useful :-)

**Comment by ambv** [comment]
@graingert, care to prepare a PR for this?

**Comment by graingert** [comment]
@ambv yeah I'll have a look, I'll also add support for generator_stop

**Comment by graingert** [comment]
@ambv I've added a second PR for the py2 `__future__` implication because it's technically a different problem, but it has the same solution
