### ISSUE TITLE
use `from __future__ import division, print_function, absolute_imports` to imply `--target-version=py27`

### ISSUE THREAD

**Issue by graingert** [psf/black#1644]
This issue is the dual of https://github.com/psf/black/issues/1630

**Is your feature request related to a problem? Please describe.**

I have a large number of Python 2 files like this, that I'm working full time to port to py3.8

there are also files mixed in with python 3.8 support annotated per  https://github.com/psf/black/issues/1630

```python
# -*- coding: utf-8 -*-
from __future__ import print_function, division, absolute_import

...
def _example():
    3rd_party.call(data=b"foo", mode=u"ham-mode")

# many more lines of carefully tuned b/u strings

def foo():
    _spam(
        a,
        bacon=eggs,
        **kwargs,
    )
```

When running black on save, it strips all the carefully chosen `u` prefixes from my literals, because black correctly determines that is is indeed only valid in py3+

**Describe the solution you'd like** A clear and concise description of what you want to
happen. `from __future__ import print_function, division, absolute_import` consider any of these as stronger signal for py2 compat requirement than `**kwargs,`

**Describe alternatives you've considered** #
* There are already documented workarounds for this, but they aren't as convenient: eg I could configure which format my files are by running two different CLIs of black with a allowlist/denylist of what is py2/py3. But this requires running two processes of black and configuring it for every editor/os configuration, also it requires defining the version of a file in two places and acts as an impediment for upgrading a file directly to py3.8+ only.
* For the specific problem I mentioned regarding `u` prefixes I could use `from __future__ import unicode_literals` but this future is no-longer best practice for universal py2/py3 support, due to needing str(u"...") to create "native" strings

**Additional context** Add any other context or screenshots about the feature request
here.

**Comment by JelleZijlstra** [comment]
I agree with doing this, feel free to submit a PR.

**Comment by Shivansh-007** [comment]
Since we have dropped python 2.7 support from black, we could close this issue?
