### ISSUE TITLE
No module named 'dataclasses' in Python 3.6.9

### ISSUE THREAD

**Issue by l0b0** [psf/black#1645]
Python 3.6 doesn't have dataclasses, so the following fails:

```text
Traceback (most recent call last):
  File "…/.venv/bin/black", line 7, in <module>
    from black import patched_main
  File "…/.venv/lib/python3.6/site-packages/black/__init__.py", line 49, in <module>
    from dataclasses import dataclass, field, replace
```

**Comment by ichard26** [comment]
Not sure how that could happen as the requirement of `dataclasses` is listed in `setup.py`... 😕 

https://github.com/psf/black/blob/2b75f8870eac943c93e93c740c9d2ef74efeeb41/setup.py#L70-L80

**Comment by l0b0** [comment]
I tried changing pyproject.toml from `black = {version = "^19.10b0", allow-prereleases = true}` to `black = {version = "*", allow-prereleases = true}`. This results in an upgrade to 20.8b1 (`poetry update` prints "Updating black (19.10b0 -> 20.8b1)") and an entry in poetry.lock for the "dataclasses" package:

```toml
[[package]]
category = "main"
description = "A backport of the dataclasses module for Python 3.6"
marker = "python_version < \"3.7\""
name = "dataclasses"
optional = false
python-versions = ">=3.6, <3.7"
version = "0.7"

[package.source]
reference = "package proxy"
type = "legacy"
url = "http://…/root/pypi/+simple"
```

But for whatever reason it looks like it's not being installed - `poetry update` doesn't print anything about the "dataclasses" package, and the Virtualenv doesn't have it:

```text
$ find .venv -name '*dataclasses*'
.venv/lib/python3.6/site-packages/isort/_future/__pycache__/_dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/isort/_future/_dataclasses.py
.venv/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/astroid/brain/brain_dataclasses.py
.venv/lib/python3.6/site-packages/mypy/plugins/dataclasses.py
.venv/lib/python3.6/site-packages/mypy/plugins/dataclasses.cpython-36m-x86_64-linux-gnu.so
.venv/lib/python3.6/site-packages/mypy/plugins/__pycache__/dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/mypy/typeshed/stdlib/3.7/dataclasses.pyi
.venv/lib/python3.6/site-packages/mypy/typeshed/third_party/3/dataclasses.pyi
```

**Comment by l0b0** [comment]
Looks like it's [this Poetry issue](https://github.com/python-poetry/poetry/issues/2480).

**Comment by JelleZijlstra** [comment]
Yes, looks like a Poetry issue.

**Comment by l0b0** [comment]
FYI: Upgrading Poetry to 1.0.10 seems to have fixed this issue.

**Comment by Cheukting** [comment]
I did not use Poetry but came across the same issue. It's tox on a Travis build.

**Comment by Cheukting** [comment]
I think this maybe the issue: https://github.com/pypa/pip/issues/8686

**Comment by erdnaxeli** [comment]
> I think this maybe the issue: [pypa/pip#8686](https://github.com/pypa/pip/issues/8686)

I am not sure this is it, this issue is about using `extra != a`. Here the check is about the python version.

I use pipenv and I can reproduce the bug.
