### ISSUE TITLE
Existing variable using format string causes AST error

### ISSUE THREAD

**Issue by MartinThoma** [psf/black#1659]
**Describe the bug** Two almost identical invalid Python scripts give different results (originally, I thought the code was valid)

**To Reproduce** Steps to reproduce the behavior:

This is "All done! ✨ 🍰 ✨ 1 file left unchanged." (but only if there is no newline at the end)

```
import re

path = f'{re.sub("[^\\w ]", "_", "bar")}'
```

This gives an AST error:

```
import re

path = ''
path = f'{re.sub("[^\\w ]", "_", "bar")}'
```

**Expected behavior** I would expect both to show an error message (or both to succeed). The inconsistency is weird.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu (WSL2) /Python 3.7.8 (pyenv)

**Does this bug also happen on master?** It does not happen at [black.now.sh](https://black.now.sh/?version=master)

**Comment by ichard26** [comment]
For me they both fail to parse (yes I did modify Black to print out all parse failures, not just the last one):

```console
(black-rHKUX7ap) R:\Programming\black>type temp.py
import re

path = f'{re.sub("[^\\w ]", "_", "bar")}'
(black-rHKUX7ap) R:\Programming\black>black temp.py --diff --color
Parse failure with Python 3.8 grammar: f-string expression part cannot include a backslash (<unknown>, line 3)
Parse failure with Python 3.7 grammar: f-string expression part cannot include a backslash (<unknown>, line 3)
Parse failure with Python 3.6 grammar: f-string expression part cannot include a backslash (<unknown>, line 3)
Parse failure with Python 3.5 grammar: Format strings are only supported in Python 3.6 and greater (<unknown>, line 3)
Parse failure with Python 2.7 grammar: invalid syntax (<unknown>, line 3)
error: cannot format temp.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 3)
Oh no! 💥 💔 💥
1 file would fail to reformat.

(black-rHKUX7ap) R:\Programming\black>type temp.py
import re

path = ''
path = f'{re.sub("[^\\w ]", "_", "bar")}'
(black-rHKUX7ap) R:\Programming\black>black temp.py --diff --color
Parse failure with Python 3.8 grammar: f-string expression part cannot include a backslash (<unknown>, line 4)
Parse failure with Python 3.7 grammar: f-string expression part cannot include a backslash (<unknown>, line 4)
Parse failure with Python 3.6 grammar: f-string expression part cannot include a backslash (<unknown>, line 4)
Parse failure with Python 3.5 grammar: Format strings are only supported in Python 3.6 and greater (<unknown>, line 4)
Parse failure with Python 2.7 grammar: invalid syntax (<unknown>, line 4)
error: cannot format temp.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 4)
Oh no! 💥 💔 💥
1 file would fail to reformat.
```

<details>
<summary> <b>Environment:</b></summary>

* _Black_ version: `master` (0c6d4ca0c33aa97202e0e94a4a2389cc432597bc)
* Python version: `CPython 3.8.1`
* OS version: `Windows 10 Home Edition Build 18363`

</details>

Unfortunately I do not have a Ubuntu installation with CPython 3.7 to test this properly. Regardless, (I think) this might be a problem with `typed-ast` which Black uses for its AST equivalence check on CPython 3.7 and below. What version of `typed_ast` do you happen to have?

**Comment by MartinThoma** [comment]
I have `typed-ast==1.4.1`.

Please note that black only shows the happy message if the first example has NO empty line in the end.

**Comment by ichard26** [comment]
Okay so I can repro on Linux and with CPython 3.7.8:

```console
(env) ichard26@acer-ubuntu:~/programming/testing$ cat test.py
import re

path = f'{re.sub("[^\\w ]", "_", "bar")}'
(env) ichard26@acer-ubuntu:~/programming/testing$ cat test2.py
import re

path = ''
path = f'{re.sub("[^\\w ]", "_", "bar")}'
(env) ichard26@acer-ubuntu:~/programming/testing$ black --version
black, version 20.8b1
(env) ichard26@acer-ubuntu:~/programming/testing$ python --version
Python 3.7.8
(env) ichard26@acer-ubuntu:~/programming/testing$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
(env) ichard26@acer-ubuntu:~/programming/testing$ black test.py --diff --color
All done! ✨ 🍰 ✨
1 file would be left unchanged.
(env) ichard26@acer-ubuntu:~/programming/testing$ black test2.py --diff --color
error: cannot format test2.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 4)
Oh no! 💥 💔 💥
1 file would fail to reformat.
```

Weird that I couldn't repro on Windows... I'll have to look into it more it appears

**Comment by DanInSpace104** [comment]
I have same issue
In file1.py i have f-strings like this:
```
def func1(param1):
    somefunc(f'test:{param1}:test')
```
And it works just fine
And in file2.py i have absolutely the same code, i just copy-paste it, but black fails with 
```
error: cannot format file2.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line XX)
Oh no! 💥 💔 💥
1 file failed to reformat.
```
In file2.py black swears even on just simple f-string like this `foo = f'test{bar}test'`
pip freeze:
```
black==20.8b1
typed-ast==1.4.2
```

**Comment by DanInSpace104** [comment]
Problem with https://github.com/psf/black/issues/1659#issuecomment-814670537 was in absolutely other line and with other reason. It was `SyntaxError: keyword argument repeated` in line 100. But black showed error with f-string in line 50. So It is other issue with wrong error message.

**Comment by ichard26** [comment]
@DanInSpace104 this issue is already tracked by GH-1263.

**Comment by hauntsaninja** [comment]
Black currently errors on both. In general, Black doesn't guarantee erroring out on invalid Python code.
