### ISSUE TITLE
Update docs to remove flake8 ignore of W503, which is ignored by default

### ISSUE THREAD

**Issue by johnthagen** [psf/black#1660]
The flake8 compatible configuration docs here: https://black.readthedocs.io/en/stable/compatible_configs.html#id1

Says:

```
max-line-length = 88
extend-ignore = E203, W503
```

But as explained by the `flake8` developer, `W503` is already ignored by default: https://gitlab.com/pycqa/flake8/-/issues/542#note_172953512

The flake8 compatible configuration docs could thus be simplified to:

```
max-line-length = 88
extend-ignore = E203
```

**Comment by scottfurry** [comment]
Suspect regression. Using v 4.0.1 (Gentoo X86_64). Having just installed black (v22.1.0), reformatting produced multiple W503 messages. Attempted to utilize extended-ignore and reloaded/rescanned project. Warnings persisted. I ensured no W503/W504 ignores were present in code or configuration. Only after adding explicitly W503 to extended-ignore would flake8 be satisfied.
