### ISSUE TITLE
Conda Release of 20.8b1

### ISSUE THREAD

**Issue by vivekmig** [psf/black#1665]
We are currently having inconsistencies when linting with black installed with Anaconda and PyPI, since version 20.8b1 has been released on [PyPI](https://pypi.org/project/black/#description) but [Anaconda](https://anaconda.org/conda-forge/black) still has version 19.10b0 . We wanted to find out the expected release of the 20.8b1 on Anaconda to determine whether we should make the changes for consistency with 20.8b1.

Thanks for the great work with black!

cc: @NarineK

**Comment by cooperlees** [comment]
How do we find out who maintains the anaconda package? I don't think any of the core maintainers have access to that (e.g. I've never used anaconda in my life).

**Comment by vivekmig** [comment]
> How do we find out who maintains the anaconda package? I don't think any of the core maintainers have access to that (e.g. I've never used anaconda in my life).

Just looked into it, seems like it's maintained through a corresponding [repo](https://github.com/conda-forge/black-feedstock) in conda-forge. There's already a [PR](https://github.com/conda-forge/black-feedstock/pull/16) to update to 20.8b1, but seems like it hasn't merged yet, I'll follow up there, thanks!

**Comment by cooperlees** [comment]
Cool - very handy to know and on next release one of us might submit a PR or see if we can automate etc.
- Thanks for reminding us conda exists.

**Comment by xhochy** [comment]
The PR should be generated automatically, just not automatically merged at the moment. Feel free to add yourself as a maintainer on the conda recipe to be able to merge these PRs.
