### ISSUE TITLE
Docstring for class attributes

### ISSUE THREAD

**Issue by earonesty** [psf/black#1675]
PEP-257: String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called "attribute docstrings".

```python
class Foo:
    attr = 1
    """PEP for doscstrings on attrs is that it comes after.  So this is for 'attr'"""
    some_other_attr = 'is this the one we're documenting?'
```

Semicolon is a natural delimiter for single-line attribute docstrings.

```python
class Foo:
    # pylint: disable=multiple-statements
    attr = 1;  """PEP for doscstrings on attrs is that it comes after. So this is for 'attr'"""
    some_other_attr = 'is this the one we're documenting?'
```

The black  style is obviously unclear.   Docstrings, in general, are hard to format well... the simplest rule is that they must be visually linked to the thing they are documenting.   Fortunately, the semicolon allows us to visually connect a single-line docstring to its attribute -as long as the line-length is short.

As an alternative a comment or something could provide visual cues

```python
class Foo:
    attr = 1;
    """PEP for doscstrings on attrs is that it comes after. So this is for 'attr'"""
    # -----
    some_other_attr = 'is this the one we're documenting?'
```

**Comment by JelleZijlstra** [comment]
I'm inclined to close this request:
- This would be the only place Black formatting uses semicolons
- What if the docstring is too long to fit in one attribute? Do we go back to the current style?
- Even the examples in https://www.python.org/dev/peps/pep-0258/#attribute-docstrings (rejected but closely linked to PEP 257, the docstring style guide) put the docstring on its own line.
