### ISSUE TITLE
Document that black automatically excludes files in .gitignore

### ISSUE THREAD

**Issue by johnthagen** [psf/black#1682]
I had a difficult time understanding why `black` was not formatting certain files. I changed the ``exclude`` configuration parameter to override the default to try to help, but it wasn't until I dug through the source code I realized that `black` is ignoring things that match `.gitignore`. 

https://github.com/psf/black/blob/6284953d07060804dcdeacf4626b76aed7a20683/src/black/__init__.py#L5909-L5914

Could the fact that the `.gitignore` file is used be added to the docs? Perhaps here?
-  https://black.readthedocs.io/en/stable/pyproject_toml.html#where-black-looks-for-the-file

Perhaps also in the `--help` for `--exclude`?

**Comment by J-Exodus** [comment]
I'd like to be assigned this one please.  This is my first time ever contributing to open source.

**Comment by johnthagen** [comment]
PR: #1734

**Comment by johnthagen** [comment]
Fixed in https://github.com/psf/black/commit/ea4e714b9a3b636afd8e81c5c5c916fcf8e6ed42
