### ISSUE TITLE
Documentation for "Trailing Commas" no longer matches behavior

### ISSUE THREAD

**Issue by thejcannon** [psf/black#1685]
[The documentation for "Trailing Commas"](https://black.readthedocs.io/en/stable/the_black_code_style.html#trailing-commas) is no longer correct with regards to magic trailing commas. 

The following paragtraph is no longer correct:

> Unnecessary trailing commas are removed if an expression fits in one line. This makes it 1% more likely that your line won’t exceed the allotted line length limit. Moreover, in this scenario, if you added another argument to your call, you’d probably fit it in the same line anyway. That doesn’t make diffs any larger.

In addition to removing that paragraph, a link to the [Magic Trailing Comma](https://black.readthedocs.io/en/stable/the_black_code_style.html#the-magic-trailing-comma) section would be nice at the end of the "Trailing Commas" section (or merging the two sections/putting them adjecent, which would probably be less confusing)

**Comment by ichard26** [comment]
Hi @thejcannon, those incorrect paragraphs [were already replaced](https://github.com/psf/black/commit/6b935a34d08c0b18d858e7da5093dc69a29c55f2) with a new paragraph linking to the "magic trailing comma" section. This error was unfortunately noticed and fixed after the stable version of the documentation was released so this change is only viewable on the current version of the docs. 

Sorry for the confusion!
