### ISSUE TITLE
integration with Conda

### ISSUE THREAD

**Issue by goi42** [psf/black#1686]
It would be nice to have the option to use black as part of a Conda environment. This would allow me to more easily incorporate it into repositories that use Conda.

**Comment by cooperlees** [comment]
What does this mean? Can you elaborate for us maintainers that do not use Conda at all (e.g. me 🤓)

Seems to exist here:
https://anaconda.org/conda-forge/black

**Comment by goi42** [comment]
@cooperlees I'll be darned, so it does. I guess this is just a request to add the `conda-forge` label to the docs next to the `license` and `pypi` labels, a la the `Bioconda` label [here](https://github.com/snakemake/snakemake).
