### ISSUE TITLE
Blackd Packaging

### ISSUE THREAD

**Issue by mlucool** [psf/black#1688]
**Describe the bug**

The [blackd documenation states](https://black.readthedocs.io/en/stable/blackd.html):
> blackd is not packaged alongside Black by default because it has additional dependencies. You will need to execute pip install black[d] to install it.

But `blackd` is included in [packages](https://github.com/psf/black/blob/master/setup.py#L65) for black.

**To Reproduce** Steps to reproduce the behavior:

```bash
$ python3 -m venv venv; source venv/bin/activate
$ pip install black
$ which blackd
/path/to/venv/bin/blackd
```

**Expected behavior**

No binary named `blackd` is installed because its webserver dependencies are not installed.

**Environment (please complete the following information):**

- Version: master
- OS and Python version: Linux

**Does this bug also happen on master?**
Yes, see above

**Comment by cooperlees** [comment]
Does anyone have suggestions here? I’m trying to read docs on how to do this and not finding many answers. I’ll keep dogging. We do have ‘[d]’ in the console_scripts entry ...

**Comment by zsol** [comment]
I'm fairly sure this used to work as described in the docs. Has something changed in or around `pip`?

**Comment by zsol** [comment]
From [the python packaging guide](https://python-packaging-user-guide.readthedocs.io/specifications/entry-points/?highlight=extras#file-format):

> Using extras for an entry point is no longer recommended. Consumers should support parsing them from existing distributions, but may then ignore them. New publishing tools need not support specifying extras. The functionality of handling extras was tied to setuptools’ model of managing ‘egg’ packages, but newer tools such as pip and virtualenv use a different model.

It's unclear to me what this different model is, but we should probably use that.

**Comment by cooperlees** [comment]
I did see this too, but I can't work out what it is. I'll call in favors from friends to try work this out.

**Comment by hugovk** [comment]
That was added to the guide in https://github.com/pypa/packaging.python.org/pull/390.

I've not read through it, but it also adds an "entry points specification", perhaps there's something useful in there? Could also ask someone from that PR?
