### ISSUE TITLE
Remove not-needed parenthesis

### ISSUE THREAD

**Issue by klahnakoski** [psf/black#1689]
**Problem**
When formatting code with Black, some not-needed parenthesis are kept.

**Current behaviour**
The following lines remain unchanged after Black formatting
> x = (a).b
> x = ((a)).b
> x = (((a))).b

**Expected Behaviour**
I would expect parenthesis to be removed
> x = a.b

**Comment by felix-hilden** [comment]
This is related to #1123. I agree that they should be removed with method calls as well.

**Comment by JelleZijlstra** [comment]
This is essentially the same as #2039.
