### ISSUE TITLE
Documentation search not working as expected (is slow and sometimes produces 502)

### ISSUE THREAD

**Issue by hnykda** [psf/black#1694]
**Describe the bug** 
Trying to use search in the documentation: https://black.readthedocs.io/en/stable/search.html?q=comma takes a long time and _sometimes_ results in timeouts:
![image](https://user-images.githubusercontent.com/2741256/92704166-0c27ee00-f353-11ea-84f5-9f0a7e91a93c.png)

**To Reproduce** Steps to reproduce the behavior:
Go to https://black.readthedocs.io/en/stable/search.html?q=comma and try to use the search for several times.

**Expected behavior**: it wouldn't timeout and wouldn't take more than <5 sec

I really like the docs though! (but I was searching for the magic trailing comma and can't find it anywhere - I swear I saw it in the readme in [the past](https://github.com/psf/black/tree/0196437f8e062817d3277bb1484de3fbdcb3e19d#trailing-commas), but it's not there anymore or in the docs (well, maybe is, but I can't find it)!)

**Comment by hugovk** [comment]
Here's the part you're looking for: https://black.readthedocs.io/en/stable/the_black_code_style.html?#the-magic-trailing-comma (it was the third result for me).

**Comment by hnykda** [comment]
Thanks, not sure what was wrong. If it was just a temporary deployment issue, feel free to close this one.

**Comment by cooperlees** [comment]
Thanks for the report. Worked for me too. Must have been a temporary issue with read the docs.
