### ISSUE TITLE
Formatting does not respect line length if comma at the end

### ISSUE THREAD

**Issue by orso82** [psf/black#1714]
**Describe the bug**
black does not respect the specified line length if there is a comma at the end of a list of arguments, of lists, tuples, sets, dictionaries. This issue is not present in version 19.3b0 of black

**To Reproduce**

Run black (not version 19.3b0) on this:

```python
def func1(a, b, c, d, e, f):
    pass


l1 = ['1', '2', '3']

t1 = ('1', '2', '3')

s1 = {'1', '2', '3'}

d1 = {'1': 1, '2': 2, '3': 3}


########


def func2(a, b, c, d, e, f, ):
    pass


l2 = ['1', '2', '3', ]

t2 = ('1', '2', '3',)

s2 = {'1', '2', '3', }

d2 = {'1': 1, '2': 2, '3': 3, }
```

which will be formatted as:

```python
def func1(a, b, c, d, e, f):
    pass


l1 = ["1", "2", "3"]

t1 = ("1", "2", "3")

s1 = {"1", "2", "3"}

d1 = {"1": 1, "2": 2, "3": 3}


########


def func2(
    a,
    b,
    c,
    d,
    e,
    f,
):
    pass


l2 = [
    "1",
    "2",
    "3",
]

t2 = (
    "1",
    "2",
    "3",
)

s2 = {
    "1",
    "2",
    "3",
}

d2 = {
    "1": 1,
    "2": 2,
    "3": 3,
}
```

**Expected behavior**

I expect the following behavior (which is how version 19.3b0 of black used to work)

```python
def func1(a, b, c, d, e, f):
    pass


l1 = ['1', '2', '3']

t1 = ('1', '2', '3')

s1 = {'1', '2', '3'}

d1 = {'1': 1, '2': 2, '3': 3}


########


def func2(a, b, c, d, e, f):
    pass


l2 = ['1', '2', '3']

t2 = ('1', '2', '3')

s2 = {'1', '2', '3'}

d2 = {'1': 1, '2': 2, '3': 3}
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: OSX/Python 3.7.6

**Does this bug also happen on master?**

YES

**Additional context**

My workaround at this point is to format all of my source with
version 19.3b0 of black, and then give it a second pass with
the latest version 20.8b1 (at the time of writing)

**Comment by hugovk** [comment]
This is by design and called the "magic trailing comma":

https://black.readthedocs.io/en/stable/the_black_code_style.html#the-magic-trailing-comma

**Comment by orso82** [comment]
Thanks for the info. Can such magic behavior be disabled?

**Comment by hugovk** [comment]
No, it's not one of the (few) options.

**Comment by orso82** [comment]
Ok, thanks. I ended up monkey patching black for my purposes.
For the record, I disabled the "magic trailing comma" magic with:

```python
import black


def maybe_should_explode(self, closing):
    return False


black.Line.maybe_should_explode = maybe_should_explode
```
