### ISSUE TITLE
it is showing wrong formatted code with respect to  PEP8 formatter.

### ISSUE THREAD

**Issue by Mohitkumar6122** [psf/black#1718]
**Describe the bug** A clear and concise description of what the bug is.

I was formatting my code with this formatter and when i got output it  showed no error but when i formatted the same code with PEP8 formatter online it showed me error which was correct. 
**To Reproduce** Steps to reproduce the behavior:

1. Take this file '...'
2. Run _Black_ on it with these arguments '....'
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: [e.g. master]
- OS and Python version: [ Linux/Python 3.8.2]

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.

**Additional context** Add any other context about the problem here.

**1. Black Formatter output which  is showing  no error.**
![table](https://i.ibb.co/BykR3jQ/Screenshot-from-202**0-09-22-15-42-31.png)

**2. PEP8 Formatter with actual error.**

![table](https://i.ibb.co/cbsSwHc/Screenshot-from-2020-09-22-15-47-58.png)

Could you tell me how this error occured ?

**Comment by zsol** [comment]
Please use the template to report bugs. Try and provide a minimal example we can work with, and make sure you include what you think the correct formatting should be. No screenshots, please.

**Comment by Mohitkumar6122** [comment]
it is ok now (showing correct result).
