### ISSUE TITLE
gitignore only respects the root gitignore

### ISSUE THREAD

**Issue by max-sixty** [psf/black#1730]
**Is your feature request related to a problem? Please describe.**

This is fairly narrow, and would be understandable if it weren't worth fixing, but posting regardless.

Currently black only respects the root `.gitignore` to ignore files (https://github.com/psf/black/issues/475). So a path like:

```
project
|-.gitignore <- doesn't contain .terraform
|-python-project
|-infra
  |-.gitignore # <- contains .terraform
  |-.terraform
    |-module.py
```

...will still format `module.py`

**Describe the solution you'd like** 

Apply `.gitignore` rules like git does

---

Thanks as ever for the superb library!

**Comment by hadialqattan** [comment]
Hi, I'm working on that, can anyone assign this issue to me?

**Comment by JulianVolodia** [comment]
"have you got home"?
