### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by spapanik** [psf/black#1741]
**Is your feature request related to a problem? Please describe.**

It is frustrating to see a git diff the all it does is changing the line endings from LF to CRLF. In a language with significant whitespace, I don't want to do diffs with the hide whitespace option. 

**Describe the solution you'd like**

I would like either black to enforce LF, or have LF as default and be able to choose in `pyproject.toml`, in something along the lines:
```toml
[tool.black]
line-ending = "LF" or "CR" or "CRLF"
```

**Describe alternatives you've considered**
Viewing diffs with "hide whitespace changed" on.

**Additional context**
N/A

**Comment by hugovk** [comment]
As another alternative, there are a number of pre-commit hooks to do this: https://pre-commit.com/hooks.html

* `mixed-line-ending` - Replaces or checks mixed line ending
* `forbid-crlf` - Forbid files containing CRLF end-lines to be committed
* `remove-crlf` - Replace CRLF end-lines by LF ones before committing

**Comment by zsol** [comment]
IIRC we have considered this, but ultimately decided to be extra careful and preserve the original CRLF line endings, as we felt that's more in the domain of the version control software being used. The only opinion Black has on this matter is that line endings should be consistent (which is a fairly basic requirement :) )

The alternatives @hugovk offers above are also excellent.

**Comment by hugovk** [comment]
Oh, and Git itself can be configured to handle line endings:

* https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings

**Comment by felix-hilden** [comment]
Since reasonable alternatives have been proposed, there has been no discussion for a while and no additional points have been raised, should this issue be closed? I agree that line endings should not be handled by Black.

**Comment by ichard26** [comment]
I also agree line ending shouldn't be handled by Black (it would probably be one of the more risky things Black would do if accepted) so closing!

Thanks for the suggestion though.
