### ISSUE TITLE
Leading whitespace in docstring produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by vterron** [psf/black#1754]
Black produced code that is not equivalent to the source.

The problem seems to be leading whitespace in functions' docstrings:

```
       body=
         Expr(
           value=
             Constant(
               value=
-                b" The immutable celestial coordinates of an astronomical object.\n\n    The first two positional arguments, 'ra' and 'dec', are the right ascension\n    and declination of the astronomical object, in decimal degrees. 'pm_ra' and\n    'pm_dec' are the proper motion, in seconds of arc per year (arcsec/yr).\n\n    ",  # bytes
+                b"The immutable celestial coordinates of an astronomical object.\n\n    The first two positional arguments, 'ra' and 'dec', are the right ascension\n    and declination of the astronomical object, in decimal degrees. 'pm_ra' and\n    'pm_dec' are the proper motion, in seconds of arc per year (arcsec/yr).\n\n    ",  # bytes
             )  # /Constant
         )  # /Expr
         FunctionDef(
           args=
[...]
```

**To Reproduce** Steps to reproduce the behavior:

1. Take this file: https://github.com/vterron/lemon/blob/980bd1bd62a0b4da6eb19e60cf2bc4ea64ea5cd0/astromatic.py
2. Run _Black_ on it with these arguments: `black astromatic.py`
3. See error _"Black produced code that is not equivalent to the source."_

**Expected behavior** Expected Black to format the file.

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] ArchLinux, Python 3.8.5.

**Does this bug also happen on master?** Yes (used https://black.now.sh/?version=master)

**Additional context** None.

**Comment by JelleZijlstra** [comment]
This no longer crashes with current main.
