### ISSUE TITLE
Inconsistent formatting in lists with trailing commas in sub lists

### ISSUE THREAD

**Issue by oteph** [psf/black#1760]
The list a, b and c in the following example should be the same after formating:  

```python
a = [[1,2],[3,4]]
b = [[1,2,],[3,4,]]
c = [[1,2],[3,4,]]
```
Expected:
```python
a = [[1, 2], [3, 4]]
b = [[1, 2], [3, 4]]
c = [[1, 2], [3, 4]]
```
Result:
```python
a = [[1, 2], [3, 4]]
b = [
    [
        1,
        2,
    ],
    [
        3,
        4,
    ],
]
c = [
    [1, 2],
    [
        3,
        4,
    ],
]

```

The same behavior also happens with tuples.

**To Reproduce** 

https://black.now.sh/?version=master,&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACHAFJdAD2IimZxl1N_WlOfrjrukHwUt1mT_WU6La1zQ_eB2gNrcWL3YZ9VBc9YWiBPYIrKs3HPs7CIFyTQFBr497GRVaT7efgZC5JXA2RobIA1Ig6TxgAAAADkaLLa478C-AABbogBAAAAwSaByLHEZ_sCAAAAAARZWg==

**Environment**
black, version 20.8b1

Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux

**Does this bug also happen on master?** yes

**Comment by ikseek** [comment]
It's actually a feature named "The magic trailing comma" in the docs

**Comment by hugovk** [comment]
https://black.readthedocs.io/en/stable/the_black_code_style.html?#the-magic-trailing-comma

**Comment by oteph** [comment]
Thanks and great feature - i somehow managed to miss the introduction to this
