### ISSUE TITLE
black breaks the type annotation into multiple lines when it's possible to keep it on one line

### ISSUE THREAD

**Issue by passichenko** [psf/black#1765]
**Describe the bug**

black breaks the type annotation into multiple lines, while existing formatting keep it on one line by using parentheses around expression

**To Reproduce**:

old formatting:
```
class Foo:
    def foo(self):
        if True:
            content_ids: Mapping[str, Optional[ContentId]] = (
                self.publisher_content_store.store_config_contents(files)
            )
```

after black:
```
class Foo:
    def foo(self):
        if True:
            content_ids: Mapping[
                str, Optional[ContentId]
            ] = self.publisher_content_store.store_config_contents(files)
```

playground link: https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEZAK5dAD2IimZxl1N_WlXnON2nzNX9HFvHx6cBSdVHWyzJO6O50DK3ha9hxTlR0JwlWYXCXbF4CjYJWeEpyQIXtrrOkKmzjEkT25z6cJ4YzWm7pHh_LmznKdvIU8f2vDLKjoyxv-ZPlxXoOnqhPz8sGlioAQx7_azDc47CPs6gbJw5n5j0LZ-lBGbWsnS8ldMWJXrmleKBm2qB_EmzBNy6IQNsCElvvBmM-J3BIWV55zK6IAAAAAMi_lQVqdYNAAHKAZoCAAARFT-fscRn-wIAAAAABFla

**Expected behavior**
black keeps existing formatting

**Environment:**

- Version: both stable and master
- OS and Python version: Linux/Python 3.7.5+

**Does this bug also happen on master?**
Yes.

**Comment by lnking81** [comment]
Will it be fixed? Very annoying, actually

**Comment by ichard26** [comment]
Eventually yes, but we can't really make guarantees for when as no one is being paid to work on this project.

**Comment by lnking81** [comment]
Sure, I understand. Just wonder if you pay any attention to the issues opened years ago.

**Comment by felix-hilden** [comment]
Just for housekeeping and eventual implementation, this is likely closely related to #749.

**Comment by MeGaGiGaGon** [comment]
This was fix at some point, the above [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFOAL1dAD2IimZxl1N_WlXnON2nzNX9HFvHx6cBSdVHWyzJO6O50DK3ha9hxTlR0JwlWYXCXbF4CjYJWeEpyQIXtrrOkKmzjEkT25z6cJ4YzWm7pHh_LmznKdvIU8f2vDLKjoyxv-ZPlxXoOnqhPz8sGlioAQx7_azDc47CPs6gbJw5n5j0LZ-lBGbWsnS8ldMWJXrmleKBm2qBdq2TMYeljEfPPJFO00WMCbYtyZCaShq64ByXgU0ESjUXGsfaf8PUAAAAAACbQq1ei8G9gAAB2QHPAgAAtJqu5rHEZ_sCAAAAAARZWg==) now doesn't change the formatting, and the [incorrect formatting is now corrected](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFUALxdAD2IimZxl1N_WlXnON2nzNX9HFvHzs2eWBUV0Kbwxj2L7BNaTuRLQ2dkozL7VD-FNfn9gBJ8vXFI3216_8wdWtLiuSepgMC1F-IUlyzMSWrnb4EdYbUnL7Hp0Yxc0_TAouANprnoZoB9oTZdP6BkLxtb0RRQESIbqT8uTgi52FclJbpYe-fjwYd2gdFTIv1A9-FntB7xc4VZVE1mT6ko7piDoC7Ckz6087b_61ufzo5vTM0Ej1B7YmGIYBIAACDAZ_vm5FNbAAHYAdUCAADq_lYSscRn-wIAAAAABFla)
