### ISSUE TITLE
black --diff alsways passes pre-commit

### ISSUE THREAD

**Issue by Bibo-Joshi** [psf/black#1773]
**Describe the bug**

When running `black` as pre-commit hook with the `--diff` option, the hook always succeeds, even if running `black` manually would reformat files.

**To Reproduce** Steps to reproduce the behavior:

1. clone this MWE-Repo: https://github.com/Bibo-Joshi/black-mwe
2. `cd black-mwe`
3. `pre-commit install`
4. `pre-commit run --all-files` → doesn't fail
5. Remove `diff = true` from `pyproject.toml`
6. `pre-commit run --all-files` → reformats `main.py` and fails

**Expected behavior:** pre-commit hook gives the same result as runnig `black` manually

**Environment:**

- Version: 20.8b1
- OS and Python version: Tried on both Windows and Linux on Py3.8

**Does this bug also happen on master?** To answer this, you have two options:

Using the online formatter at https://black.now.sh/?version=master, it reformats the file `main.py` as expected

**Additional context:** I only recently switched to `black` and really do hope that it's not just some stupid configuration error 😬 But I tried to find solutions online and tested on different machines with the same result. I'd be happy for a response :)

**Comment by hugobuddel** [comment]
I'm also new to black, and pre-commit, and `pyproject.toml`, so the perfect person to answer this :wink:.

It seems that you need to add `check = true` to the black configuration in `pyproject.toml`:
```
$ cat pyproject.toml
[tool.black]
diff = true
check = true
verbose = true

$ pre-commit run --all-files
black....................................................................Failed
- hook id: black
- exit code: 1

Using configuration from [..]/black-mwe/pyproject.toml.
--- main.py     2020-10-22 09:38:34.174300 +0000
+++ main.py     2020-10-22 09:41:17.363695 +0000
@@ -1,11 +1,6 @@
-def print_hi(
-
-
-
-        name):
+def print_hi(name):
     print(f"Hello there! - {name}")
 
 
-if __name__ == '__main__':
-    print_hi(
-        "General Kenobi.")
+if __name__ == "__main__":
+    print_hi("General Kenobi.")
would reformat main.py
Oh no! 💥 💔 💥
1 file would be reformatted.
```

See https://github.com/psf/black/blob/407052724fa1c97ee8bcd4e96de650def00be03e/src/black/__init__.py#L6104

**Comment by Bibo-Joshi** [comment]
Thanks for the solution, @hugobuddel :)
Still, somewhat unexpected, at least in the pre-commit setting … I'll check later how that affects the non-pre-commit setting and maybe try and PR.

**Comment by MarcoGorelli** [comment]
@Bibo-Joshi from the [black](https://black.readthedocs.io/en/stable/installation_and_usage.html) docs:

> exits with code 0 unless an internal error occurred (or --check was used).

So if no code was modified (because you used `--diff`) and the output code is `0` (because you didn't use `--check`), then this seems like expected behaviour

**Comment by Bibo-Joshi** [comment]
Fair enough @MarcoGorelli . Still, that's a bit unintuitive with pre-commit, so maybe I'll at least PR to add a note to the "VC integration" paragraph of the readme :)

**Comment by hugobuddel** [comment]
It is actually weird that pre-commit fails without `check = true` in the normal (non-diff) case, because `black` itself will not raise an error without `--check`. Maybe pre-commit secretly uses `--check`, but not when `--diff` is given.
