### ISSUE TITLE
Provide a --stdin-display-name option like flake8

### ISSUE THREAD

**Issue by bellini666** [psf/black#1776]
I'm trying to use `black` as a fixer on ale on vim. It works fine and my config file is respected, except for the `exclude` and `force-exclude` files/folders.

The problem is that the tool calls black passing the code through stdin, and thus, black doesn't know the filename that is being parsed.

flake8 workas around that issue by providing a `--stdin-display-name` which can be used to identify which is the name of the file being passed through stdin, allowing those exclude rules to be followed.

What do you think?

**Comment by arcanemachine** [comment]
@bellini666 Forgive me for replying to this old issue, but I have been running in circles trying to get `--force-exclude` to work with Black and ALE.

How did this help you fix this problem?

**Comment by bellini666** [comment]
Hey @arcanemachine ,

I'm not using ale anymore because I changed from vim to neovim, and in there I'm using null-ls. But I think ale needs to be upgraded to use the `--stdin-filename` to the command line for this to work

**Comment by arcanemachine** [comment]
OK, thanks for the info.
