### ISSUE TITLE
black igoners ex/include in pre-commit run --all-files

### ISSUE THREAD

**Issue by Bibo-Joshi** [psf/black#1778]
**Describe the bug** When specifying directories to include via `pyproject.toml`, black will still run on excluded/not included files when running `pre-commit run --all-files`.

**To Reproduce** Steps to reproduce the behavior:

1. clone this MWE-Repo: https://github.com/Bibo-Joshi/black-mwe
2. `cd black-mwe`
3. `pre-commit install`
4. `pre-commit run --all-files` → fails
6. `black . --check` → succeeds as expected

**Expected behavior:** `black` should respect `include` and `ignore` in pre-commit even when running with `--all-files`, because that flag just means "run also on non-changed files" not "ignore all hook settings"

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Windows, Py3.8

**Does this bug also happen on master?**

Yes. Installed via `pip install git+https://github.com/psf/black.git` and above steps still fail.

**Additional context** I only recently switched to `black` and really do hope that it's not just some stupid configuration error again like in #1773 😬 I'd be happy for a response :)

**Comment by MarcoGorelli** [comment]
As far as I understand, pre-commit passes each file one-by-one, and so what you end up running is:
```
black file1.py file2.py file3.py ... filen.py
```

If you look at the docs https://black.readthedocs.io/en/stable/installation_and_usage.html?highlight=exclude#command-line-options it says

>   --exclude TEXT                  A regular expression that matches files and
                                  directories that should be excluded on
                                  recursive searches. 

As pre-commit doesn't run `black` recursively, it'll have no effect.

Instead, you should use pre-commit's own `files` and `exclude`.

In your example:
```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --check
        files: ^(foo|bar)/.*\.py$
        exclude = ^bar/vendor
```

**Comment by Bibo-Joshi** [comment]
Thanks again for the explanation @MarcoGorelli !
Based on your answer another solution would be to `force-exclude` everything *not* in `include`, in this case 

```
force-exclude = '^(?!(foo|bar)/).*\.py$'
```

That allows it to have `pre-commit` and `black` behave the same …
Closing, but this confirms me in PRing to improve the documentation of VC integration
