### ISSUE TITLE
Tuple and comma in __init__ method

### ISSUE THREAD

**Issue by matkosoric** [psf/black#1784]
**Describe the bug** 

formating __init__ method wraps some arguments in single-element tuple and ads a trailing comma.
there seems to be other similar issues, but not this one.

**To Reproduce**

format this: 

```
class Car:

    def __init__(self,
                 year,
                 type,
                 color):
        self.year = year,
        self.type = type
        self.color = color
```

**Expected behavior** A clear and concise description of what you expected to happen.

```
class Car:
    def __init__(self, year, type, color):
        self.year = **year**
        self.type = type
        self.color = color
```
instead, result is this:
```
class Car:
    def __init__(self, year, type, color):
        self.year = **(year,)**
        self.type = type
        self.color = color
```
**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Windows 10, Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by hugovk** [comment]
In your intial code `year,` (with a comma) is already a tuple. Black is adding brackets to make it clearer.

To demonstrate:

```pycon
>>> year = 2020,
>>> year
(2020,)
>>> type(year)
<class 'tuple'>
>>> year == 2020
False
>>> year = (2020,)
>>> year
(2020,)
>>> type(year)
<class 'tuple'>
>>> year == 2020
False
>>>
```

I think you want to fix your original code to remove the comma:

```diff
                  year,
                  type,
                  color):
-        self.year = year,
+        self.year = year
         self.type = type
         self.color = color
```
