### ISSUE TITLE
pip install error with nix and venv environment.

### ISSUE THREAD

**Issue by alunduil** [psf/black#1786]
**Describe the bug** A clear and concise description of what the bug is.

When using nix to create a Python environment and installing black via pip the installation ends in an error.

**To Reproduce** Steps to reproduce the behavior:

1. Add the following to shell.nix:

```
let
  pkgs = import <nixpkgs> {};
in
  pkgs.mkShell {
    buildInputs = [
      pkgs.python3
      pkgs.python37Packages.virtualenv
    ];
  }
```

2. Add the following to .envrc:

```
use nix
layout python3
```

3. Run `direnv allow`

4. Run `pip install .`
5. See error at https://gist.github.com/c8a4d664f8ca413ccef172b27f3c821f

**Expected behavior** A clear and concise description of what you expected to happen.

I expected the installation to proceed without error.

**Environment (please complete the following information):**

- Version: 19.10b0, 20.8b1, and master
- OS and Python version: Python version: 3.7.6

OS /etc/os-release:

```
NAME=NixOS
ID=nixos
VERSION="20.03.3175.afcf35320d8 (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03.3175.afcf35320d8"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Does this bug also happen on master?** To answer this, you have two options:

Yes, I also attempted to use this environment on master with the same results.

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.

I'm sure this is something about the environment I'm using but it's not clear to me what about the black packaging system is causing this particular issue or how its interacting strangely with my environment.  Other Python software works fine with this kind of environment.

**Comment by kalekseev** [comment]
That's not a black problem, and it described in nix python doc https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#python-setuppy-bdist_wheel-cannot-create-whl
Also `pip install --no-binary :all: .` should work too.

**Comment by alunduil** [comment]
Thanks for checking in on this.  That solution works perfectly and I found it shortly before you posted it here.  Sorry about the noise here.
