### ISSUE TITLE
Long string remains unchanged

### ISSUE THREAD

**Issue by lyz-code** [psf/black#1787]
Long strings remain unchanged.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file:

```python
value = "aldkfdskdksfjdskfj dslkfj sdkl dklsfj dsklfj sdklfjdsklfjdskl fjdskl jdsklf jdsklfj dsklfj dsklfj dsklfj dsklfj dsklfj dsklfj dkl"

fstring = f"f-strings definitely make things more {difficult} than they need to be for {{black}}. But boy they sure are handy. The problem is that some lines will need to have the 'f' whereas others do not. This {line}, for example, needs one."

good_split_func(
    xxx, yyy, zzz,
    long_string_kwarg="But what should happen when code has already "
                      "been formatted but in the wrong way? Like "
                      "with a space at the end instead of the "
                      "beginning. Or what about when it is split too "
                      "soon?",
)
```

2. Run _Black_ on it with no arguments.
3. Actual output

```python
value = "aldkfdskdksfjdskfj dslkfj sdkl dklsfj dsklfj sdklfjdsklfjdskl fjdskl jdsklf jdsklfj dsklfj dsklfj dsklfj dsklfj dsklfj dsklfj dkl"

fstring = f"f-strings definitely make things more {difficult} than they need to be for {{black}}. But boy they sure are handy. The problem is that some lines will need to have the 'f' whereas others do not. This {line}, for example, needs one."

good_split_func(
    xxx,
    yyy,
    zzz,
    long_string_kwarg="But what should happen when code has already "
    "been formatted but in the wrong way? Like "
    "with a space at the end instead of the "
    "beginning. Or what about when it is split too "
    "soon?",
)
```

**Expected behavior**: Formatting should meet the behaviour of #1132 .

**Environment (please complete the following information):**

- Version: master (`pip install git+git://github.com/psf/black`)
- OS and Python version: Linux/Python 3.7.3

**Does this bug also happen on master?** Yes, [tested with black.now.sh](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AM9AcpdAD2IimZxl1N_Wmp8V60GiUhqmIgs8fla4363lVEvD2S76yAZR1O5DEZ37Rjb_AVSbMlKwqt4kY9eif1JBa9lyDR6e1sOyFONPRkEbQMwcKPaQBxogxTb3tMRrKYHko38f90v6aFtUPgbWYePaYhETyd3t6tz9nWFpMnOuIsJhcVwYN7jzDUgsTjhupPoIib01K3c5nDQb7u2SjTtuGgFRZm9V4YciIuVLr6MTUdHMvyekfVw_dF_NWg54IJW7EGb5mR8PAEbNAn6eGiTfiH0j90aYH-m8dU3GNgi6_zwCj3sV-jPYex11AniwRa2joH6NA7_vAiLiHNSO16sTBDzuv_6Eq5AeYuiGA8v2zc0VjvyYY7e5CFbHMu5ZeCkrHsf7tnVSQGWP0rwKPpBj-6qFrqoACRwIH7K80ZRv_o3OrZdGKQ77VTbnf2KGfGLzfZa4YNZNq_fBCYccJ-_iLensqEQSoiXwqHhz9_oo-pYZjTObk2IXtsmwg5QsxcXnyvYQz2RqtVkrcuVLfwW3xXw9mJ6DlWYMazsW_G8d7PO9K_NnTBuPaUo6fuX7w10Bf7sN2pvgvbu28JFnlAtmdGrNTehN9qDe-LjAgY8AAAAoyAEZ61LlBIAAeYDvgYAAIkTyL2xxGf7AgAAAAAEWVo=)

**Additional context**: After reviewing the git log, I've seen that the #1132 PR was merged into the branch `origin/poetry` but not into the current master. Although the code [seems to be present](https://github.com/psf/black/blob/master/tests/data/long_strings__edge_case.py)

**Comment by hugovk** [comment]
https://github.com/psf/black/pull/1132 was disabled in https://github.com/psf/black/pull/1609.

You can re-enable it with the undocumented  `--experimental-string-processing` flag.

**Comment by lyz-code** [comment]
Thanks @hugovk, it worked. Should I create a PR on the documentation to add this option?

**Comment by hugovk** [comment]
Good to hear!

Nope, it's intentionally undocumented until the related crashes are fixed, and then it'll become the default when it's more stable. But thanks for the offer!

**Comment by ichard26** [comment]
> Nope, it's intentionally undocumented until the related crashes are fixed, and then it'll become the default when it's more stable. But thanks for the offer!

Just to be clear, if we can't get the extra string processing stable enough it won't ever be released. On the flip side, that's unlikely as there already has been [efforts by bbugyi200](https://github.com/psf/black/pulls?q=is%3Apr+author%3Abbugyi200)!

Closing as there isn't anything actionable in this issue.

**Comment by asgmeonerandom** [comment]
It doesn't work on the string
`XCLIENT_ID = "123ij12o3i1j2o3icj12o3icj123ij12o3i1j2o3icj12o3icj123ij12o3i1j2o3icj12o3icj123ij12o3i1j2o3icj12o3icj123ij12o3i1j2o3icj12o3icj"` using the `--experimental-string-processing`

**Comment by ichard26** [comment]
@asgmeonerandom the string is left unchanged because there isn't anything for Black to split on (i.e. no spaces).

>It should be noted that #1132 will not change the output of the example that you gave above since the example string has no spaces in it. This would be undesirable, for example, in the case of long URLs.

https://github.com/psf/black/issues/1331#issuecomment-623653386

**Comment by asgmeonerandom** [comment]
> @asgmeonerandom the string is left unchanged because there isn't anything for Black to split on (i.e. no spaces).
> 
> > It should be noted that #1132 will not change the output of the example that you gave above since the example string has no spaces in it. This would be undesirable, for example, in the case of long URLs.
> 
> [#1331 (comment)](https://github.com/psf/black/issues/1331#issuecomment-623653386)

mine has  spaces between variables

**Comment by lyz-code** [comment]
Is there any way of setting this setting in the `pyproject.toml` section? I've tried 

```toml
[tool.black]
experimental_string_processing = true
experimental-string-processing = true
experimental_string_processing = "true"
experimental-string-processing = "true"
```

but none worked. 

Thanks

**Comment by ichard26** [comment]
@lyz-code, the `experimental_string_processing = true` form should work, chances are that Black can't find your pyproject.toml file. When you run Black with verbose mode turned on (pass `-v` to it), Black will print a blue message that indicates it found and is using a configuration file (e.g. `Using configuration from /home/ichard26/programming/oss/black/pyproject.toml.`). Do you get that line, what is your directory structure, and how are you running Black?
