### ISSUE TITLE
Magic comma not working in sum

### ISSUE THREAD

**Issue by bersbersbers** [psf/black#1795]
**Describe the bug** 
In a sum of several expressions with magic comma, several mistakes arise (which can all be explained by the magic comma being applied to another term):

**To Reproduce**

1. `echo "f(v=0,) + f(v=1,) + f(v=2,)" | black -`

Only the last trailing comma is considered:
```
f(v=0,) + f(v=1,) + f(
    v=2,
)
```

2. `echo "f(v=0,) + f(v=1) + f(v=2)" | black -`

Trailing comma seems to be applied in the wrong term:
```
f(v=0,) + f(
    v=1
) + f(v=2)
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Linux, Python 3.8.6

**Does this bug also happen on master?**

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.

Yes.

**Comment by JelleZijlstra** [comment]
This is fixed:
```
 % echo "f(v=0,) + f(v=1,) + f(v=2,)" | black -

(
    f(
        v=0,
    )
    + f(
        v=1,
    )
    + f(
        v=2,
    )
)
```
