### ISSUE TITLE
PEP 8: E203  whitespace before ':'

### ISSUE THREAD

**Issue by Dipet** [psf/black#1803]
Black adds whitespace before `:` in statements like this: `val[pos + 1 :]`

**Examples in the current _Black_ style**

```python
def f(arr, position):
    return arr[position + 1 :]
```

**Desired style**

```python
def f(arr, position):
    return arr[position + 1:]
```

Black version: version 20.8b1

**Comment by av1m** [comment]
For information, https://github.com/psf/black/issues/1841#issuecomment-734701947
