### ISSUE TITLE
Black does not accuse unnecessary spaces in the docstring

### ISSUE THREAD

**Issue by LeonardoFurtado** [psf/black#1812]
**Describe the bug** Black does not accuse unnecessary spaces in some docstrings

**To Reproduce** Steps to reproduce the behavior:

1. Try to use black on a file with this code:
```
def get_accepted_answers(accepted_answer_ids: List[str]) -> List[str]:
    """      Take an accepted answer id and return the body of it """

    answers_bodies = []
```
2. no changes will be made.

**Expected behavior** docstring should be formatted

- Version: Stable
- OS and Python version: [Windows/Python 3.8]

I've try to use https://black.now.sh/?version=master but the result was the same.

In code snippets like this:

```
def get_answers(query, traceback, off):
    """         This coordinate the answer aquisition process. It goes like this:
    1- Example;
    2.1- Example;
    2.1- Example;
    3- Example;
    """
    ids,accepted = get_questions(query)
```
The output is:

```
def get_answers(query, traceback, off):
    """This coordinate the answer aquisition process. It goes like this:
    1- Example;
    2.1- Example;
    2.1- Example;
    3- Example;
    """
    ids, accepted = get_questions(query)
```

As you can see, the formatting was done and and the spaces have been removed.

**Comment by YashVadhadiya** [comment]
Hello @LeonardoFurtado  
I get your problem and I'll try to resolve give me some time to know this thing.
I'll get back to you.
[Check it once.](https://github.com/psf/black/pull/1053)

**Comment by stinos** [comment]
To summarize: I have the impression the problem is that single-line docstrings are treated differently than multi-line ones. Or parhaps that single-line docstrings aren't recognized as docstrings because it seems whatever you do with it, they remain untouched.
