### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by sai38** [psf/black#1813]
This diff might be helpful: /var/folders/_r/y8nnm1j16538p6n3xkb4cxpw0000gp/T/blk_y0rwo0xf.log
Oh no! 💥 💔 💥

**Comment by ichard26** [comment]
Thanks for reporting but it is impossible for us to know what happened as there isn't enough information. At a minimum please copy and paste the contents of the log file. The full suite of source, environment, steps, etc would be ideal, but usually we can construct a reproducer with just a log file.

I'll be closing this issue soon if no further info is provided.
