### ISSUE TITLE
PySpark long instructions style

### ISSUE THREAD

**Issue by vmgustavo** [psf/black#1816]
**Describe the style change**
It is frequent to use long instructions for PySpark chained with the dot operator. The official Apache Spark [tutorials](https://spark.apache.org/docs/latest/sql-getting-started.html#starting-point-sparksession) on how to use PySpark suggest using `\` to break the statement. The current style splits the statement simply to avoid crossing the char columns limit and doesn't consider readability. By splitting the statement at the dot operators this could be better.

**Examples in the current _Black_ style**

```python
spark = (
    SparkSession.builder.appName("Python Spark SQL basic example")
    .config("spark.some.config.option", "some-value")
    .getOrCreate()
)
```
```python
data.repartition("column").write.partitionBy("column").mode("ignore").option(
    "compress", "snappy"
).parquet(output_path)
```

**Desired style**
Should follow the Apache Spark code style
```python
spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()
```
Or maybe if not using `\` to split the lines
```python
spark = (
    SparkSession
    .builder
    .appName("Python Spark SQL basic example")
    .config("spark.some.config.option", "some-value")
    .getOrCreate()
)
```

**Additional context**
* This could be applied to code using Pandas as well
* This is similar to #1781

**Comment by JelleZijlstra** [comment]
We will not use the style with backslashes; that's against Black general style principles.

I'm most interested in changing the output for your second example, with `data.repartition`. That does look ugly right now, and I'd welcome suggestions for how to make it better.

**Comment by vmgustavo** [comment]
By simpling wrapping the instructions with parenthesis the style is already great:

```python
(data.repartition("column").write.partitionBy("column").mode("ignore").option(
    "compress", "snappy"
).parquet(output_path))
```

```python
(
    data.repartition("column")
    .write.partitionBy("column")
    .mode("ignore")
    .option("compress", "snappy")
    .parquet(output_path)
)
```

The bad formmating only happens when there is no parenthesis. Would it be possible to "force add" parenthesis?

**Comment by felix-hilden** [comment]
@vmgustavo We have an open issue about improvements to fluent interfaces: #571
