### ISSUE TITLE
"Format All" appears to not respect disabled string normalization

### ISSUE THREAD

**Issue by gsamaras** [psf/black#1822]
**Describe the bug**

In Sublime Text 3, I have overwritten default settings with my user settings that disable string normalization. When I right-click anywhere inside a Python script, I am able to "Format file" and have my user settings respected.

However, another option is available when I right-click, "Format all", which if clicked goes through the whole project folder that I have opened in Sublime, formats it, but ignores the string normalization!

Note: Maybe the rest of the settings too, but I didn't check and I have now deleted the project.

**To Reproduce** 

1. Disable string normalization in Sublime Text 3, in Black User Settings.
2. Open project in Sublime.
3. Open a (Python) file.
4. Right-click anywhere in the file -> Black: Format all.
5. Observe that all the single quotes have been string normalized (despite this functionality being disabled by the user), i.e. (all) `'` have become `"`.

**Expected behavior**

Black doesn't convert the single quotes to double ones, i.e. it respects User Settings about string normalization.

**Environment (please complete the following information):**

- Version: master
- OS and Python version: Mac, 3.6.

**Additional context**

If possible, I would like to contribute and fix this.

**Comment by JelleZijlstra** [comment]
This sounds like a bug in the Sublime plugin for Black, not in Black itself. I don't know what plugin you're using, but if it's Sublack, the issue tracker is at https://github.com/jgirardet/sublack.
