### ISSUE TITLE
Can't format a yield expression with a type annotation and without parentheses

### ISSUE THREAD

**Issue by grahamalama** [psf/black#1828]
**Describe the bug** 
Can't format a [yield expression](https://www.python.org/dev/peps/pep-0342/#new-syntax-yield-expressions) with a type annotation and without parentheses.

**To Reproduce** 
Paste the following snippet in the [black playground](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACvAHVdAD2IimZxl1N_WlbvK5V_5E5NEzEakNf_hFekK8lLVE09BitvHbpZS6OelPZPMcpkchxrJHL7oA6RntadGfB4FSrVHt9pQ6VdwYXLGeUICNj46Ar-Sy7RERu36z958Pu01O2nxAl4SUukN7ZjjEHLtbpf-ISflwAAAACh7HWJ50i_bAABkQGwAQAAJhy_NLHEZ_sCAAAAAARZWg==):
```python
def talkin_bout_my_generator():
    next_yield: str = yield "first_yield"
    yield next_yield
```

**Expected behavior**
Black is able to validate that the snippet is formatted.

**Actual behavior**
`Cannot parse: 2:22:     next_yield: str = yield "first_yield"`

**Environment (please complete the following information):**
- Version: master
- OS and Python version: [e.g. MacOS/Python 3.8.0]

**Additional context**
This seems to be a very specific corner case. Black is able to process both:
```python
next_yield = yield "first_yield"
```
and 
```python
next_yield: str = (yield "first_yield")
```
It's the combination of the type annotation and lack of parentheses that seems to be the issue. Probably a low priority thing, but since it seems like `next_yield: str = yield "first_yield"` is valid python, black should be able to process it.

**Comment by hauntsaninja** [comment]
For what it's worth, this is invalid syntax in Python 3.7 and lower (https://bugs.python.org/issue35814)

**Comment by JelleZijlstra** [comment]
What @hauntsaninja says is probably why Black doesn't accept it. We should update the grammar to accept this syntax, being careful not to emit `x: str = yield y` in <= 3.7.
