### ISSUE TITLE
Please change repo name

### ISSUE THREAD

**Issue by blm397** [psf/black#1830]
In light of recent patch to Git removing master as a default branch (https://lore.kernel.org/git/pull.762.git.1605221038.gitgitgadget@gmail.com/) and general efforts to remove/replace non-inclusive language such as "whitelist" and "blacklist", it seems appropriate to also rename this repository, which can harm inclusivity. Thanks for understanding.

**Comment by iago-lito** [comment]
duplicates #1363 #1554

**Comment by nth10sd** [comment]
I get a 404 "not found" when trying to access #1363, presumably it is hidden and all discussions are locked out of public view.

(#1554 is marked as a duplicate of #1363 so there's not much discussion there either)

Any way to get more official information/reasoning other than an immediate closure and duping to a locked non-public issue?

**Comment by ichard26** [comment]
The name was coined as a humorous reference to Henry Ford's quote on the Model T: "Any customer can have a car painted any color that he wants so long as it is black." The readme begins with a shortened version of this quote. The logo is a play on the Ford logo.
