### ISSUE TITLE
Option to preserve manual line breaks

### ISSUE THREAD

**Issue by jamesmyatt** [psf/black#1833]
**Is your feature request related to a problem? Please describe.**

It frustrates me that sometimes my carefully chosen line breaks are replaced by black.
For example, it may be beneficial to have something other than one argument per line, e.g.

```
things = [
    "one_a", "one_b",
    "two_a", "two_b", "two_c",
]
function(
    a, b, c,
    kw_1=1, kw_2=2,
)
```

I can disable formatting for this block using `#fmt: off/on`,
but it frustrates me that this also disables all of the other great replacements that black makes.

**Describe the solution you'd like**

I'd like to be able to write something like:

```
# in

things=[
    'one_a',"one_b",
    'two_a','two_b','two_c',
    ]  #nofmt: line_breaks

# out

things = [
    "one_a", "one_b",
    "two_a", "two_b", "two_c",
]  #nofmt: line_breaks
```

I think it would be OK if this caused it to exceed the line limit.

There's probably a better name for the option than "line_breaks" too.

**Describe alternatives you've considered**

Another solution would be to use block syntax, like `#fmt: off-newline/on-newline`,
but looking at the black code, I'm pretty sure that this would be hard.

**Additional context**

`styler` for R has options for different scopes of change, one of which is "line_breaks", although this isn't an exact match to the functionality above: https://styler.r-lib.org/reference/tidyverse_style.html

**Comment by JelleZijlstra** [comment]
It's already possible to use `# fmt: off`. Adding more fine-grained control of what formatting to change in a particular block would complicate our code and go against Black's no-configuration philosophy.
