### ISSUE TITLE
Black causes W1404 Implicit string concatenation found in assignment (implicit-str-concat)

### ISSUE THREAD

**Issue by vertti** [psf/black#1837]
**Describe the bug**

When Black decides a multiline string can be put to single line, it leaves the concatenation in place rather than merging them to a single string. This is considered a bug pattern by Pylint and does seem to be a bug rather than a feature from Black.

**To Reproduce** Steps to reproduce the behavior:

Having code something like this:

```
foo = (
  "not really super long line "
  "but enough that I split it"
)
```

will, when line length allows, be pulled by Black to:

```
foo = "not really super long line " "but enough that I split it"
```

rather than a single string.

**Expected behavior**

In the above situation I would have expected the result to be:

```
foo = "not really super long line but enough that I split it"
```

instead of single-line implicit concatenation that is by default flagged by Pylint (W1404)

**Environment **

- Version: master
- OS and Python version: Ubuntu 20.10, Python 3.8.5

**Does this bug also happen on master?**

Yes

**Comment by JelleZijlstra** [comment]
I believe the `--experimental-string-processing` flag fixes this (we'll turn this on by default once it's stable enough).

**Comment by vertti** [comment]
Excellent. Thanks!

**Comment by jontwo** [comment]
We're still seeing this in v23.3.0. The `--experimental-string-processing` should have been removed by now, yes?

**Comment by JelleZijlstra** [comment]
It is not yet enabled by default; it's still part of `--preview`. Hopefully it will be the default in Black 24.

**Comment by tylerlaprade** [comment]
I have an f-string that looks like `f"blah blah blah ... blah blah blah {my_variable}"`. This is getting auto-fixed when using `--preview` to 
```
"blah blah blah ... blah blah blah"
f" {my_variable}"
```
which reports the violations `reportImplicitStringConcatenation` in Pyright and `ISC002` in Ruff/Flake8.

**Comment by ichard26** [comment]
That's intentional. If you like this changed, please upvote/comment here: https://github.com/psf/black/issues/2553.
