### ISSUE TITLE
PEP 8: E203 (whitespace before :) violation

### ISSUE THREAD

**Issue by shifqu** [psf/black#1841]
Black violates [PEP 8: E203 whitespace before ':'](https://www.flake8rules.com/rules/E203.html) when using a method call as first slicing index

**Steps to reproduce the behavior:**

[Playground Link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGHAK9dAD2IimZxl1N_Wg09_6u33o7WYe7JkHYh42Xtd5WmVnTxWn4eHstVPPh7TdY8phtS2kn-iGDSfFquT79bP1vOAv95n_f1kj0BEkOSDOR5aK3JCFWtvdRQ2QyCAi6UqqL-768L85NASkM9NHXzRaLpdWei0E8A3Sya5mz0bcWjiFgTtDR6XQPU2sAds7KDjb5XsmJPJzEYJzccY4EWwJAEjjRXSKYHdgpPmvQwQ3cTfBoAAAksxfSBT1TKAAHLAYgDAACXM7GvscRn-wIAAAAABFla)
```python
# Method call used in subsetting --> Unexpected behaviour
foo = "bar"
foo[foo.find("a") :]  # PEP 8 E203 whitespace before :

# Variable used in subsetting --> Expected behaviour
foo = "bar"
a_index = foo.find("a")
foo[a_index:]

# Value used in subsetting --> Expected behaviour
foo = "bar"
a_index = foo.find("a")
foo[1:]
```

**Expected behavior** 
```python
foo = "bar"
foo[foo.find("a"):]  # No whitespace after first slicing index
```

**Environment (please complete the following information):**

- Version: stable [version 20.8b1]
- OS and Python version: MacOs Catalina v10.15.7/Python 3.8.6

**Does this bug also happen on master?**

[Yes, Playground Link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGHAK9dAD2IimZxl1N_Wg09_6u33o7WYe7JkHYh42Xtd5WmVnTxWn4eHstVPPh7TdY8phtS2kn-iGDSfFquT79bP1vOAv95n_f1kj0BEkOSDOR5aK3JCFWtvdRQ2QyCAi6UqqL-768L85NASkM9NHXzRaLpdWei0E8A3Sya5mz0bcWjiFgTtDR6XQPU2sAds7KDjb5XsmJPJzEYJzccY4EWwJAEjjRXSKYHdgpPmvQwQ3cTfBoAAAksxfSBT1TKAAHLAYgDAACXM7GvscRn-wIAAAAABFla)

**Comment by iago-lito** [comment]
This is expected behaviour (although I think an issue heavily duplicated in this repo): https://black.readthedocs.io/en/stable/the_black_code_style.html#slices

**Comment by shifqu** [comment]
Oh, did not find this is in the docs. Thanks for the information!
