### ISSUE TITLE
experimental-string-processing causing INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by Starwort** [psf/black#1846]
**Describe the bug**
Feeding Black a file containing a string split over several lines can cause an internal error when using experimental-string-processing

**To Reproduce**

1. Take this file<details>
   <summary>File</summary>

   ```py
   (
       "my very long string"
       " that should get formatted"
       " if I'm careful to make sure"
       " it goes over 88 characters which"
       " it has now"
   )
   ```
   </details>
2. Run _Black_ on it with these arguments `--experimental-string-processing`
3. See error

<details>
<summary>Log</summary>

```diff
--- src
+++ dst
@@ -4,10 +4,46 @@
       value=
         Constant(
           kind=
             None,  # NoneType
           value=
-            "my very long string that should get formatted if I'm careful to make sure it goes over 88 characters which it has now",  # str
+            'my very long string',  # str
+        )  # /Constant
+    )  # /Expr
+    Expr(
+      value=
+        Constant(
+          kind=
+            None,  # NoneType
+          value=
+            'that should get formatted',  # str
+        )  # /Constant
+    )  # /Expr
+    Expr(
+      value=
+        Constant(
+          kind=
+            None,  # NoneType
+          value=
+            "if I'm careful to make sure",  # str
+        )  # /Constant
+    )  # /Expr
+    Expr(
+      value=
+        Constant(
+          kind=
+            None,  # NoneType
+          value=
+            'it goes over 88 characters which',  # str
+        )  # /Constant
+    )  # /Expr
+    Expr(
+      value=
+        Constant(
+          kind=
+            None,  # NoneType
+          value=
+            'it has now',  # str
         )  # /Constant
     )  # /Expr
   type_ignores=
 )  # /Module
```
</details>

**Expected behaviour** Black formats the string into two lines as follows:
```py
(
    "my very long string that should get formatted if I'm careful to make sure it "
    "goes over 88 characters which it has now"
)
```

**Environment (please complete the following information):**

- Version: 20.8b2.dev50+g7f75fe3
- OS and Python version: Linux/Python 3.9.0

**Does this bug also happen on master?** Yes

**Comment by bbugyi200** [comment]
@ichard26 Thanks for tagging me on this.

The problem was that was trying to remove the surrounding parens which changes the AST in this case. This issue should be fixed by #1888.

**Comment by bbugyi200** [comment]
@Starwort Note that the expected output should actually be that the string is left unchanged in this example, since black respects manual/user string splits when it is possible to do so without violating the line length limit.

**Comment by Starwort** [comment]
@bbugyi200 out of interest, what is a 'pointless string' in this context? When I first read your commit name I kinda thought you were mocking my example string but then after reading more into it it's clear that that's a proper term - could you explain it to me?

**Comment by bbugyi200** [comment]
@Starwort No problem. I'm stealing that nomenclature from [pylint](https://github.com/PyCQA/pylint)'s "basic" checker's `pointless-string-statement` check. You can find a description of this check in [pylint's documentation](https://docs.pylint.org/en/1.6.0/features.html#id3). Taken directly from that documentation:

> **pointless-string-statement (W0105):**
>  Used when a string is used as a statement (which of course has no effect). This is a particular case of W0104 with its own message so you can easily disable it if you’re using those strings as documentation, instead of comments.

To be clear, regardless of whether the string is "pointless" or not, it should _not_ cause black to crash, so this was a valid issue. Thank you for reporting it.

**Comment by Starwort** [comment]
That makes sense; thank you for explaining :)
