### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source.

### ISSUE THREAD

**Issue by semajson** [psf/black#1851]
**Describe the bug** When running black over the following code:
```
from pestincl import SCRIPT_FAILURE

class Suite:
    def fail(self, msg=None):
        """
        Fail immediately, with the given message.
        """
        raise SCRIPT_FAILURE, msg

    def add_failure(self):
        """ A call has failed. Record this. """
        self.num_failures += 1

    def hangup_all(self, who = None, num_at_once = 10, sleep_hangups = 1.0):
        """ Hang up all phones that are off hook.
        """
        pass
```
The error `INTERNAL ERROR: Black produced code that is not equivalent to the source.` is reported

**To Reproduce** Run black over code snippet posted above

**Expected behavior** Black formats the file without error

**Environment :**

- Version: 20.8b1
- OS and Python version: Centos 7 / Python 2.7.5 (although code was from a python 2 script, I don't think it's a python 2 specific issue)

**Does this bug also happen on master?** Yes, it repos on https://black.now.sh/?version=master

**Additional context** Output of the of the diff file:
```
--- src
+++ dst
@@ -197,11 +197,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    b' Hang up all phones that are off hook.\n        ',  # bytes
+                    b'Hang up all phones that are off hook.',  # bytes
                 )  # /Constant
             )  # /Expr
             Pass(
             )  # /Pass
           decorator_list=
```

**Comment by CiderMan** [comment]
This looks like the same issue reported in [this issue](https://github.com/psf/black/issues/1844)
