### ISSUE TITLE
Add pre-commit hook configuration option to always re-stage modified files so pre-commit doesn't fail

### ISSUE THREAD

**Issue by plammens** [psf/black#1857]
Currently, when the pre-commit hook runs, if some files need reformatting (but other than that there is no error), black reformats them *but stops the commit* because either it returns exit code 1 or pre-commit detects that files have been changed. This is frustrating because after that you have to do the whole commit process again, while I would like it to just silently commit the reformatted files. The whole point of black is you shouldn't need to check its output, because you fully concede to it any and all authority regarding code formatting. So there's no point in failing the commit so that the developer can check the modified files and re-start the commit process.

I would like to see a way to configure the commit hook so that it only fails the commit if there was a fatal error (e.g. parsing error); if some files were reformatted it should just add the changes to the commit and continue. (As discussed below, this is not directly supported/endorsed by pre-commit, but I think black should work around this by silently re-adding the modified files to the staging area so pre-commit doesn't notice.)

An alternative I've considered is making my own pre-commit hook that wraps around black and always re-adds files if the reformatting completed without errors, but I would rather just have this as an official feature in black.

See also: https://stackoverflow.com/q/58398995/6117426

**Comment by ichard26** [comment]
> I'm not sure if this is possible in pre-commit

Yeah it appears that when a file is modified, pre-commit will notice that and automatically fail the commit regardless of the exit code. For local development of Black, we run Black without `--check` yet pre-commit will detect files that were modified:

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ git commit -m "test"
black....................................................................Failed
- hook id: black
- files were modified by this hook <---- notice how it doesn't say "- exit code: 1" 

reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.

flake8...................................................................Passed
mypy.....................................................................Passed
prettier.............................................(no files to check)Skipped
```

This behaviour seems to be intentional: https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080

**Comment by plammens** [comment]
Couldn't something like the `git add -u` mentioned in that comment (but perhaps a little bit more refined) be added to black's pre-commit hook (optionally)? I'd say most users would be fine with letting black modify their files to be committed—after all, that's the whole purpose of black, blind trust in its ability to format files correctly in exchange for never having to waste time on that.

**Comment by MarcoGorelli** [comment]
Hey @plammens - you could always overwrite the `entry` key from the if you want pre-commit to silently change what's being committed, see https://stackoverflow.com/a/64309843 , it doesn't need to be changed upstream

**Comment by plammens** [comment]
> Hey @plammens - you could always overwrite the `entry` key from the if you want pre-commit to silently change what's being committed, see https://stackoverflow.com/a/64309843 , it doesn't need to be changed upstream

Hey, yes that can work as a temporary solution. But as mentioned there using `bash` is not portable, and the crude "`git add -u`" is too coarse and unsafe ("firing from the hip" as the author says). That's why I think adding a more well-rounded solution that is safer and works in more cases is better. E.g. black could re-add specifically only the files it modified, and from python with `subprocess` instead of bash.

**Comment by plammens** [comment]
Just realised that if the commit only includes certain hunks of the diff, it will be very complicated to only try to re-add those when black reformats. So there's no universal solution for this; a custom script by the user (if they so wish) is the only way.

**Comment by MatthewScholefield** [comment]
What about a best-effort solution? Ie. Only re-add changes in the common case where a file is staged with no unstaged changes (ie. the whole file is added). Then, as long as all parsed files are 100% staged, black can format, re-stage, and return exit code 0.
