### ISSUE TITLE
Parse error on annotated yield from

### ISSUE THREAD

**Issue by plammens** [psf/black#1858]
**Describe the bug** 
`black` returns exit code 123 if it encounters an annotated variable which is the assignment target of a `yield from` expression.

**To Reproduce**

1. Write a Python file containing the following:
    ```python
    x: int = yield from y
    ```
2. Run _Black_ on it
3. See error

**Expected behavior**
No error; black reformats the file correctly.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Windows 10 / Python 3.9.0

**Does this bug also happen on master?** No (tested using black.now.sh)

**Comment by ichard26** [comment]
> **Does this bug also happen on master?** No (tested using black.now.sh)

Yeah, this was fixed in commit 4d03716eaea58ee38d77cf2bba0a72b7a27ec9fa, so once a new release comes, this will no longer be an issue. Thanks for the report nevertheless!

**Comment by plammens** [comment]
> > **Does this bug also happen on master?** No (tested using black.now.sh)
> 
> Yeah, this was fixed in commit [4d03716](https://github.com/psf/black/commit/4d03716eaea58ee38d77cf2bba0a72b7a27ec9fa), so once a new release comes, this will no longer be an issue. Thanks for the report nevertheless!

Yeah when I saw it worked on master I thought whether it was worth reporting; I did just in case and for the record. Cheers!
