### ISSUE TITLE
FIles with district in name being ignored

### ISSUE THREAD

**Issue by sanders41** [psf/black#1860]
Black is skipping all file that have the word district in their name. For example if I have a file named district.py or test_district.py they would both be ignored by black.

**To Reproduce** Steps to reproduce the behavior:

1. Create a directory called test containing a file named district.py that should be reformatted.
2. Run `black test`
3. The file will not be formatted even when there are changes that should be made.

**Expected behavior** Files that contain the word district should be formatted along with all other files.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS Big Sur, python 3.8.6

**Does this bug also happen on master?** To answer this, you have two options:
The master branch re-formats the file correctly

**Comment by sanders41** [comment]
The problem seems to be related to any file or folder that contains "dist". Maybe there is a regex somewhere excluding dist with wild cards on either end to exclude distribution files/directories?

**Comment by ichard26** [comment]
Hey thanks for the bug report! Unfortunately, I cannot reproduce the behaviour you're describing locally on a Ubuntu 20.04.01 LTS machine with CPython 3.8.5 and Black 20.8b1.

```console
(env) ichard26@acer-ubuntu:~/programming/testing/exclusion$ tree test
test
├── district.py
└── test_district.py

0 directories, 2 files
(env) ichard26@acer-ubuntu:~/programming/testing/exclusion$ black test -v
/home/ichard26/programming/testing/exclusion/test/district.py already well formatted, good job.
/home/ichard26/programming/testing/exclusion/test/test_district.py already well formatted, good job.
All done! ✨ 🍰 ✨
2 files left unchanged.
```

May I ask for the contents of your `pyproject.toml` file if you have one?

**Comment by sanders41** [comment]
This is my pyproject.toml

```
[tool.black]
line-length = 100
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
(
    \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)
'''
```

When I run black it does see the files but leaves them unchanged. For example if test_district.py has a line with a length of 110 it will still leave it unchanged and report it as unchanged. If I then rename the file to test.py, and make no other changes it gets reformatted.

If I remove the dist line from the pyproject.toml the file does get formatted. When I tested with the master branch this dist line was in the pyproject.toml and the files with district were still formatted.

**Comment by ichard26** [comment]
Thanks for providing the contents of your `pyproject.toml` file!

So the problem is that the directories you want to exclude in your regex are not wrapped with directory separators:  slashes. Black calls `exclude.search(file_or_dir_normalized_path)` and since the `dist` regex does match somewhere in `test_district.py` and `district.py`  the files are excluded. If you want Black to only exclude directories you can add forward slashes around the (sub-)regex. Don't worry about Windows using backslashes, the path is normalized to always use POSIX forward slashes before checking for a match.

For your exclude regex, I think something like this should work:
```regex
exclude = '''
(
  \(
      \.egg
    | \.git
    | \.hg
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | \venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | setup.py
)
'''
```

**Comment by sanders41** [comment]
Adding the slashes fixed it. I did have them in my test on master and didn't notice I missed them in my original file which explains why one worked and the other didn't. Thanks for the help.
