### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source.

### ISSUE THREAD

**Issue by adamhammes** [psf/black#1866]
**Describe the bug** A clear and concise description of what the bug is.

Black won't format my file, and the error message said to report it.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file: [Black playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIDAQBdAD2IimZxl1N_WlXnON2nzOBEIKS0s9m-vGEhxipoD617A0ttgF8ypzLjiyCpR0Oc_Q9xwjvsgD7dcatPhASF7okBqYoKGIuNLZh2Io4VndIFZAo610JzNskT1LjAv0xn_agDczMwAswkpghVLYcEF_kvpGS_29jQokTLXa8BGyZmMo9bYTfIYva3RDKhB72MYBLxaWVyoXCqT41M-uZmoQ6WY6JvgbiAQWr06l58NoRDjXk78EX9ua1TPHTMnu677zm1Gp8adb7cbvuSXamIZA5cL2hr1As9Ox5enapvtMVxhubw5OE0If1wsVOiE091sOGBIG6T2FwNZsEuG3iTmQAACT7DTkw2p2YAAZwChAQAADXYA7axxGf7AgAAAAAEWVo=)

```python
class Orientation(enum.IntEnum):
    North = 0
    East = 1
    South = 2
    West = 3

    def as_coords(self) -> Point:
        # fmt: off
        return Point(*{
            Orientation.North: ( 0,  1),
            Orientation.East:  ( 1,  0),
            Orientation.South: ( 0, -1),
            Orientation.West:  (-1,  0),
        }[self])

    @staticmethod
    def from_char(c: str) -> 'Orientation':
        pass
```

2. See error: INTERNAL ERROR: Black produced code that is not equivalent to the source.

- Version: [e.g. master]: v20.8b1
- Black Playground, as well as macOS Mojave w/ Python 3.8

**Does this bug also happen on master?** To answer this, you have two options:

Yes, [playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIDAQBdAD2IimZxl1N_WlXnON2nzOBEIKS0s9m-vGEhxipoD617A0ttgF8ypzLjiyCpR0Oc_Q9xwjvsgD7dcatPhASF7okBqYoKGIuNLZh2Io4VndIFZAo610JzNskT1LjAv0xn_agDczMwAswkpghVLYcEF_kvpGS_29jQokTLXa8BGyZmMo9bYTfIYva3RDKhB72MYBLxaWVyoXCqT41M-uZmoQ6WY6JvgbiAQWr06l58NoRDjXk78EX9ua1TPHTMnu677zm1Gp8adb7cbvuSXamIZA5cL2hr1As9Ox5enapvtMVxhubw5OE0If1wsVOiE091sOGBIG6T2FwNZsEuG3iTmQAACT7DTkw2p2YAAZwChAQAADXYA7axxGf7AgAAAAAEWVo=)

**Additional context** Add any other context about the problem here.

Nothing to add, just wanted to say that I love this tool!

**Comment by ichard26** [comment]
Another case of #569.

I recommend you add `fmt: on` after the `}[self])` line so you don't get bit by a pretty bad indentation bug when `fmt: off` applies after the end of scope.

> Nothing to add, just wanted to say that I love this tool!

Thank you! Also thanks for submitting this bug report!
