### ISSUE TITLE
Vim plugin doesn't find pyproject.toml if it's in a subdirectory

### ISSUE THREAD

**Issue by austinglaser** [psf/black#1870]
Given the directory organization:

```
<repository_root>
└── subproject
   ├── pyproject.toml
   └── subproject
      └── foo.py
```

if I run `vim subproject/subproject/foo.py` and then `:Black`, black will not find `subproject/pyproject.toml`, since it searches relative to the current working directory instead of the path to the current buffer.

I think there are a number of other cases like this (for instance, editing two files from different projects in two different buffers).

**Comment by ichard26** [comment]
Fixed by GH-1871 and thank you for the bug report!
