### ISSUE TITLE
Enforce blank line after module docstring

### ISSUE THREAD

**Issue by lsorber** [psf/black#1872]
Black does not have an opinion on whether there should be a blank line immediately after a module's docstring. This causes inconsistencies across blackened files because whatever the author chooses, stays.

Both examples below satisfy black:
```python
"""Module docstring."""

import typing
```

```python
"""Module docstring."""
import typing
```

My preference would be to enforce a blank line.

Related issue: https://github.com/psf/black/issues/450

**Comment by JelleZijlstra** [comment]
Agree that we should add a blank line here.

**Comment by felix-hilden** [comment]
A moderate +1 for the proposal. To get a feel for multiline docstrings and some more imports:

```python
"""
Multiline docstring.

That explains details about the module.
"""
import stuff
import antigravity

from __future__ import braces

# VS

"""
Multiline docstring.

That explains details about the module.
"""

import stuff
import antigravity

from __future__ import braces
```

I don't have a strong preference either way. Personally I don't add the empty line because the `"""` is enough of a separator, but that's not a hill I'm willing to die on 😄 I'd be happy with either 👍
