### ISSUE TITLE
Automatically add newline at the end of file

### ISSUE THREAD

**Issue by jaladh-singhal** [psf/black#1874]
**Is your feature request related to a problem? Please describe.** 
Black doesn't enter newline at EOF on its own if there is not any

**Describe the solution you'd like**
It should auto insert new line or at least provide a configuration option that does so

**Additional context**
I think it's recommended somewhere in PEP8, besides several other code formatters does it

**Comment by JelleZijlstra** [comment]
I believe we already do this. Could you give an example where we don't?

**Comment by ichard26** [comment]
Maybe VS Code integration -> https://github.com/psf/black/issues/1662?

**Comment by rcalfredson** [comment]
I stumbled across a corner case where the newline doesn't appear: seemingly, when the length of the last line equals the limit (i.e., the default of 88). Here is a tiny script where I found it:

```python
import numpy as np

PATCH_UBOUND = 160
patch = np.zeros((PATCH_UBOUND, PATCH_UBOUND, 1))
for _ in range(4):
    patch[np.random.randint(0, PATCH_UBOUND), np.random.randint(0, PATCH_UBOUND), :] = 1
```
In all other cases, the newline got added in my experience with Black.

**Comment by ichard26** [comment]
We haven't been able to find a consistent working reproduction so closing (even the one above doesn't work for me).
