### ISSUE TITLE
`--verbose` mode should print location of project root

### ISSUE THREAD

**Issue by pachewise** [psf/black#1880]
**Describe the bug** A clear and concise description of what the bug is.

Black 20.8b1 does not respect skip-string-normalization = true in the pyproject.toml

**To Reproduce** Steps to reproduce the behavior:

1. pyproject.toml
```
[tool.black]
target-version = ['py36']
line-length = 120
skip-string-normalization = true
exclude = '(.*/migrations/.*\.py)'
include = '.*/server/.*\.py$'
```

2. create a python file with single strings

```
example = 'This is an example'
```

3. run `black <filename> --check --diff` from same directory as pyproject.toml (which is root repo dir)

**Expected behavior** A clear and concise description of what you expected to happen.

No changes would be applied by black given our pyproject.toml. Note that if you pass `--config` to that same command it works. 

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS 10.15.7, Python 3.7.2 (but target version is 3.6)

**Does this bug also happen on master?** To answer this, you have two options:

Yes with:

> 2. Or run _Black_ on your machine:
>    - create a new virtualenv (make sure it's the same Python version);
>    - clone this repository;
>    - run `pip install -e .`;
>    - make sure it's sane by running `python -m unittest`; and
>    - run `black` like you did last time.
> 

**Additional context** Add any other context about the problem here.

We haven't normalized our strings yet because it's a ~30k line change (we plan to in the coming months). Noting that it seems to be a general "not respecting pyproject.toml" issue but string normalization was the most obvious thing.

**Comment by ichard26** [comment]
Thanks for reporting, but hmm I cannot reproduce:

```console
ichard26@acer-ubuntu:~/programming/testing$ mkdir black1880
ichard26@acer-ubuntu:~/programming/testing$ cd black1880/
ichard26@acer-ubuntu:~/programming/testing/black1880$ python -m virtualenv env/
ichard26@acer-ubuntu:~/programming/testing/black1880$ actenv
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ pip install black==20.8b1
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ vim pyproject.toml
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ vim test.py
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ black test.py --check --diff -v
Using configuration from /home/ichard26/programming/testing/black1880/pyproject.toml.
test.py already well formatted, good job.
All done! ✨ 🍰 ✨
1 file would be left unchanged.
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ cat pyproject.toml 
[tool.black]
target-version = ['py36']
line-length = 120
skip-string-normalization = true
exclude = '(.*/migrations/.*\.py)'
include = '.*/server/.*\.py$'
(env) ichard26@acer-ubuntu:~/programming/testing/black1880$ cat test.py
example = 'This is an example'
```

**Comment by pachewise** [comment]
Hmm. I realize there's an implementation detail that mattered: the subdirectory we had the file in (server/) had a .git directory due to a docker quirk. Looking at find_pyproject_toml() and testing by removing the .git directory, it looks like black looks at the lowest directory with a .git and then uses that as the "root"?

**Comment by ichard26** [comment]
Yeah, it's intended behaviour to first look in the common parent directory of the discovered or/and passed-in files for a "project root" indicator. Although, I'll admit it isn't exactly clear at first glance, even with `--verbose`. Perhaps it would be helpful to have Black print what folder it determined as the project root when verbose output is enabled? (I know that the root of the filesystem fallback doesn't really count as the root of any project but we can bikeshed over that later)

**Comment by pachewise** [comment]
+1 more debug info. We can close this as "user shouldn't code after 6pm"

**Comment by tomage** [comment]
Got a file:
```
$ cat blacktest.py
example = 'This is an example'


def func():
    '''this is a docstring'''
    pass


def func2():
    '''
    this is a docstring
    '''
    pass
```

When run with black==19.10b and `skip-string-normalization = true` in pyproject.toml, nothing happens.

When I do the same with latest black (20.8b1) I get:
```
$ black blacktest.py --check --diff
would reformat blacktest.py
Oh no! 💥 💔 💥
1 file would be reformatted.
--- blacktest.py	2021-02-20 01:44:06.141640 +0000
+++ blacktest.py	2021-02-20 01:47:05.430516 +0000
@@ -5,9 +5,9 @@
     '''this is a docstring'''
     pass


 def func2():
-    '''
+    """
     this is a docstring
-    '''
+    """
     pass
```

I.e. it does seem like black 20.8b1 _is_ indeed converting single-quote docstrings into double-quote docstrings, at least when the docstring starts with a newline.

Should that still be considered a bug, or what do you think @ichard26 ?

**Comment by ichard26** [comment]
@tomage yeah that would be considered a bug. Fortunately that's been reported and fixed already (see [commit](https://github.com/psf/black/commit/7fe19fac5bccc08dbcf21c293ab50f1fcda7716f), [PR](https://github.com/psf/black/pull/1637), and [issue](https://github.com/psf/black/pull/1637)). Unfortunately the fix hasn't been shipped in a release yet.

**Comment by tomage** [comment]
Ah - dang - should have noticed that one! Thanks for the update!

**Comment by JelleZijlstra** [comment]
Going to rename this issue to reflect @ichard26's suggestion that `--verbose` should print more information.

**Comment by felix-hilden** [comment]
Had my eyes on implementing this. The core issue seems to be getting `verbose` and `find_project_root` to communicate, because parsing the configuration is done in the option declaration rather than in the main CLI function. Just to steer the implementation: would you prefer moving parsing the configuration inside main from the option declaration, *or* set some global state that is then read in main for verbose printing?
