### ISSUE TITLE
Comma after last item in formatted list

### ISSUE THREAD

**Issue by mrgou** [psf/black#1881]
When a long list is formatted with one item per line, the last item is followed by a comma. Since commas separate items in a list, I don't see how this is correct, although it's accepted by Python:

```python
mylist = ['item 1', 'item 2', 'item 3', 'item 4', 'item 5', 'item 6', 'item 7', 'item 8']
```

is formatted to:

```python
mylist = [
    "item 1",
    "item 2",
    "item 3",
    "item 4",
    "item 5",
    "item 6",
    "item 7",
    "item 8",
]
```
There shouldn't be a comma behind `"item 8"`.

**Comment by asottile** [comment]
this is definitely intentional, [trailing commas](https://github.com/asottile/add-trailing-comma#multi-line-method-invocation-style----why) are there to preserve blame on changes and reduce merge conflicts

**Comment by ichard26** [comment]
Yeah, Black's second goal is to reduce diff noise and those trailing commas help. Just imagine you have this list:
```py3
couleurs = [
    "rouge",
    "orange",
    "jaune",
    "vert",
    "bleu"
]
```
If you want to add another colour to the list you have to modify two lines, adding a comma on the previous line **and** the actual item on a new line, but if there's a trailing comma already there, only one line needs to be modified (i.e. added): the line containing the new item.

**Comment by mrgou** [comment]
I disagree as clean code shouldn't contain meaningless characters, but if this intentional rather than a bug, I'll close this topic.
