### ISSUE TITLE
Bug in docs: doctest of black/__init__.py is broken

### ISSUE THREAD

**Issue by ftnext** [psf/black#1883]
**Describe the bug** doctest of `black/__init__.py` is broken

**To Reproduce** Steps to reproduce the behavior:

1. clone this repository and setup venv (`pip install -e .`)
2. `python -m doctest src/black/__init__.py`
3. See "Test Failed"

```
$ python -m doctest src/black/__init__.py
**********************************************************************
File "src/black/__init__.py", line 989, in __init__.format_str
Failed example:
    print(black.format_str("def f(arg:str='')->None:...", mode=Mode()))
Expected:
    def f(arg: str = "") -> None:
        ...
Got:
    def f(arg: str = "") -> None:
        ...
    <BLANKLINE>
**********************************************************************
File "src/black/__init__.py", line 995, in __init__.format_str
Failed example:
    print(
      black.format_str(
        "def f(arg:str='')->None: hey",
        mode=black.Mode(
          target_versions={black.TargetVersion.PY36},
          line_length=10,
          string_normalization=False,
          is_pyi=False,
        ),
      ),
    )
Expected:
    def f(
        arg: str = '',
    ) -> None:
        hey
Got:
    def f(
        arg: str = '',
    ) -> None:
        hey
    <BLANKLINE>
**********************************************************************
1 items had failures:
   2 of   3 in __init__.format_str
***Test Failed*** 2 failures.
```

**Expected behavior** All test passed

**Environment (please complete the following information):**

- Version: master (a522aa4)
- OS and Python version: macOS/Python 3.8.6

**Does this bug also happen on master?** Yes, but this is bug of documentation

**Additional context** 
According to doctest document, 
https://docs.python.org/3/library/doctest.html#how-are-docstring-examples-recognized
> If expected output does contain a blank line, put <BLANKLINE> in your doctest example each place a blank line is expected.

The following code with additional `<BLANKLINE>`s passes doctest.

```python
def format_str(src_contents: str, *, mode: Mode) -> FileContent:
    """Reformat a string and return new contents.

    `mode` determines formatting options, such as how many characters per line are
    allowed.  Example:

    >>> import black
    >>> print(black.format_str("def f(arg:str='')->None:...", mode=Mode()))
    def f(arg: str = "") -> None:
        ...
    <BLANKLINE>

    A more complex example:

    >>> print(
    ...   black.format_str(
    ...     "def f(arg:str='')->None: hey",
    ...     mode=black.Mode(
    ...       target_versions={black.TargetVersion.PY36},
    ...       line_length=10,
    ...       string_normalization=False,
    ...       is_pyi=False,
    ...     ),
    ...   ),
    ... )
    def f(
        arg: str = '',
    ) -> None:
        hey
    <BLANKLINE>

    """
```

**Comment by ichard26** [comment]
I honestly have no idea whether our docstrings were ever intended for use as tests. I'm assuming not since we have a standalone test suite in `tests/` but `¯\_(ツ)_/`?

**Comment by JelleZijlstra** [comment]
As far as I know they're just intended as documentation. I guess it would be nice to use doctest to check that they're correct, but adding "<BLANKLINE>" strings just seems distracting.

**Comment by JelleZijlstra** [comment]
Going to close this as doctests aren't part of our test suite. The docstrings are just for documentation.
