### ISSUE TITLE
Tweak docstring of format_str() method

### ISSUE THREAD

**Issue by ftnext** [psf/black#1884]
**Describe the bug** I found docstring of `format_str()` is confusing

**As is**

```
    `mode` determines formatting options, such as how many characters per line are
    allowed.  Example:

    >>> import black
    >>> print(black.format_str("def f(arg:str='')->None:...", mode=Mode()))
    def f(arg: str = "") -> None:
        ...
```

**Issue** the above code causes `NameError`

```python
>>> import black
>>> print(black.format_str("def f(arg:str='')->None:...", mode=Mode()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Mode' is not defined
```

**To be** replace `Mode` to `black.Mode`

```
    `mode` determines formatting options, such as how many characters per line are
    allowed.  Example:

    >>> import black
    >>> print(black.format_str("def f(arg:str='')->None:...", mode=black.Mode()))
    def f(arg: str = "") -> None:
        ...
```

**Environment (please complete the following information):**

- Version: master (a522aa4)
- OS and Python version: macOS/Python 3.8.6

**Does this bug also happen on master?** No, this is about docstring (or about documentation)

**Comment by ichard26** [comment]
Sure, I'm open to a PR as this is probably the most used function when Black is used as a library (and is effectively the public API).

**Comment by ftnext** [comment]
Exactly. I referred the `format_str` docstring and I was a little confused the `NameError`.

I opened the PR to tweak the docstring. Thanks!
