### ISSUE TITLE
pyserial 115200 converts into 115_200

### ISSUE THREAD

**Issue by andreas-amlabs** [psf/black#1890]
**Describe the bug** A clear and concise description of what the bug is.
When running black --fast nad_transport.py baudrate=115200 converts into baudrate=115_200 which
seems incorrect as 115_200 is not defined by pyserial

**To Reproduce** Steps to reproduce the behavior:

1. Take this file '...' https://github.com/joopert/nad_receiver/blob/master/nad_receiver/nad_transport.py
2. Run _Black_ on it with these arguments '....' --fast nad_transport.py
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.

115_200 seems to not be defined by pyserial, so 115200 should not be altered

**Environment (please complete the following information):**

- Version: [e.g. master]
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]
Debian, black, version 18.9b0

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.

**Comment by ichard26** [comment]
Technically `115200` is the same as `115_200`: 

```pycon 
ichard26@acer-ubuntu:~$ python
Python 3.8.5 (default, Sep  9 2020, 23:45:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 115_200 == 115200
True
```

But regardless of language semantics, there are two solutions you have:

1. Pass `--skip-numeric-underscore-normalization` to Black to tell it to not add underscores to numeric literals
2. Upgrade to a newer version of Black where that behaviour was removed (for reasons you can read in #549) like `19.3b0`, `19.10b0`, and `20.8b1`.

Hope that helps!

**Comment by andreas-amlabs** [comment]
Thanks for pointing that out, I use Debian buster and I did apt-get installed black (so old version). Closing the issue
