### ISSUE TITLE
Error on some assignment expressions

### ISSUE THREAD

**Issue by dmyersturnbull** [psf/black#1898]
Black seems to break on some assignment expressions.

*This works fine:*
```python
if (version := get_version()) is not None:
```

*This breaks:*
```python
if (version := get_version() is not None):
```

It should either do nothing or remove parentheses as per #1656.

- Version: master head as of 2020-01-01 (f07832e)
- OS and Python version: Windows, Python 3.9.1 (virtualenv inside Miniconda env)

**Comment by ichard26** [comment]
Thanks for the bug report! Unforutunately I can't reproduce the bug you're describing using the [Black Playground](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACBAF1dAD2IimZxl1N_Wlws4SR7IeEMLN42a4Er5qefCWHa22M-cK6QA1IQZouOHVcrOojPp8rPAAkrtruhTMTfYBMlIHQHBzsYoGe0XMiwC1X0A6NIt87KNql-iPWIBTBn2QAAAABBlzU-dZRF9wABeYIBAAAAQwzinLHEZ_sCAAAAAARZWg==) and locally with CPython 3.8.5 and Ubuntu 20.04.01 LTS installed:

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ git log -n1
commit f07832eac44eb38f8b048aae3e1de3512a06057c (HEAD -> main, upstream/master)
Author: Paul "TBBle" Hampson <Paul.Hampson@Pobox.com>
Date:   Sat Jan 2 05:54:35 2021 +1100

    Use Prettier pre-commit mirror (#1896)
    
    This fixes Prettier install failures similar to those seen in
    https://github.com/prettier/prettier/issues/9459, and is the solution
    recommended there.
    
    Signed-off-by: Paul "TBBle" Hampson <Paul.Hampson@Pobox.com>
(black) ichard26@acer-ubuntu:~/programming/oss/black$ echo "if (version := get_version() is not None):
    pass" > test.py
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black test.py --diff --check --color
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

I also tested in a CPython 3.9.1 virtualenv and still no error. 

By any chance were you getting `black produced different code on the second pass of the formatter` errors? If yes, then I'm guessing you were hitting #1588 which is fixed on master although the fix hasn't been shipped in any release. If not, what error? The other two options are 1. `black produced invalid code`  errors, OR 2. uncaught exceptions.

**Comment by dmyersturnbull** [comment]
@ichard26 Yes, I am seeing that. (I should have pasted the error message!)

Assuming #1588 is the underlying issue, I'll go ahead and close this.
