### ISSUE TITLE
Tabs in docstrings are replaced with spaces

### ISSUE THREAD

**Issue by Cireo** [psf/black#1901]
**Describe the bug** A clear and concise description of what the bug is.
When tabs are present in multiline function docstrings, black fails with
```
INTERNAL ERROR: Black produced code that is not equivalent to the source.
```

**To Reproduce** Steps to reproduce the behavior:
Run `black, version 20.8b1` on the following:
```
"""is	ok
"""

def fails():
    """a	b
    """

def is_ok():
    """a	b"""
```
(file embedded as .txt below)

1. Take this file

[tabcomment.txt](https://github.com/psf/black/files/5760976/tabcomment.txt)

2. Run _Black_ on it with these arguments (no arguments)
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.
I would expect tabs to be replaced or preserved as black wishes, without errors.

**Environment (please complete the following information):**

- Version: `20.8b1`
- OS and Python version:  19.6.0 Darwin x86 / Python 3.9.0

**Does this bug also happen on master?**
No.  On master the multiline comment with tabs is converted to a single line comment with tabs.

```
"""is	ok
"""


def fails():
    """a	b"""


def is_ok():
    """a	b"""
```

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment]
Thanks for the report; closing since this is fixed on master and the bug has already been reported.
