### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by jamesgeddes** [psf/black#1914]
**Is your feature request related to a problem? Please describe.** 
We would like to use Black to help resolve [GeekZoneHQ/web#175](https://github.com/GeekZoneHQ/web/issues/175)

**Describe the solution you'd like** 
An official docker hub image of black would be tremendously helpful

**Describe alternatives you've considered** 
There are images of black that appear to be unofficial, however an official one would be fantastic.

**Additional context**
NA

**Comment by cooperlees** [comment]
Have manually built arm64 + amd64 images @ https://hub.docker.com/repository/docker/cooperlees/black from #1916.

Have put up #2086 to see how we want to go about automating docker image builds.

**Comment by cooperlees** [comment]
Moved to https://hub.docker.com/r/pyfound/black as I now have access to push there. Will work on getting automation there too.
