### ISSUE TITLE
Concatenation of bytes literal and f-string does not always raise an error

### ISSUE THREAD

**Issue by ProgVal** [psf/black#1921]
**Describe the bug** 

Missing comma between b"" and f"" sometimes raises an error and sometimes doesn't, depending on unrelated lines

**To Reproduce**

1. On this file:
```
(b"a" f"{b}")
 
(
    "foo",
    "bar"
)
```

Black fails with: `error: cannot format foo.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 1)`, as it should.

2. On this file (the same, with an extra comma on the first line):

```

(b"a", f"{b}")
 
(
    "foo",
    "bar"
)
```

Black succeeds, as it should

3. On this file (same as the first one, with a comma on the second-to-last line):

```
(b"a" f"{b}")
 
(
    "foo",
    "bar",
)
```

Black succeeds, but it (probably) shouldn't.

**Expected behavior** It should either fail on case 3, or succeed in case 1.

**Environment (please complete the following information):**

- Version: I tried with both 19.10b0 and 20.8b1
- OS and Python version: Linux/python3.7.3

**Does this bug also happen on master?** [yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACCAFpdAD2IimZxl1N_WhQ1WavmwYi1DssXVrCjQC1auWO7BVony-KE4KmvwLPnjoxVFvRpm38rc_sFh3cUeBYEn7jByNkck23DiRbEs5Skw2SPnm80IlcCAqIIgNSPCAAAAHjfIqCARyXrAAF2gwEAAAAml9RQscRn-wIAAAAABFla)

**Comment by mvolfik** [comment]
Could you please check the third example again? I wasn't able to reproduce it with `20.8b1` or `master` with Python `3.7.10` or `3.8.5` - it always fails for me.

However, that is the correct behavior – running python on that file reports that you can't mix byte (`b`) and string literals. If black worked on that, it would likely be a bug in the AST parsing module anyways.

**Comment by ProgVal** [comment]
Indeed, I can't reproduce it. Sorry for the noise
