### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source.

### ISSUE THREAD

**Issue by mefuller** [psf/black#1923]
[blk_kevvs06_.log](https://github.com/psf/black/files/5803772/blk_kevvs06_.log)
**Describe the bug** A clear and concise description of what the bug is.
Black produced code that is not equivalent to the source and reported this on the command line as an internal error.
See attached output file.

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version: Fedora Rawhide / Python 3.9.1
[blk_kevvs06_.log](https://github.com/psf/black/files/5803785/blk_kevvs06_.log)

**Comment by MickMiller** [comment]
[bug_black.txt](https://github.com/psf/black/files/5843860/bug_black.txt)

**Comment by CiderMan** [comment]
I think that this might be another manifestation of [this issue](https://github.com/psf/black/issues/1844).

**Comment by ichard26** [comment]
For the OP case, the log file isn't enough to definitively know it's another manifestation of GH-1844, but for Mick's case, it not even erroring on master (6d0bdc2f38d57ddf07e7d127215d51f8553997f9). So I'll be closing this as there isn't anything actionable here.
