### ISSUE TITLE
module 'blib2to3.pygram' has no attribute error while running black 

### ISSUE THREAD

**Issue by jalajcodes** [psf/black#1929]
**Describe the problem**.
Unable to format test files with black.

Repo  Link: https://github.com/jalajcodes/mentorship-backend

Here's the error output for a single file: 
```sh
error: cannot format tests/mentorship_relation/test_dao_listing.py: module 'blib2to3.pygram' has no attribute 'python_grammar_no_print_statement_no_exec_statement_async_keywords'
```

**Expected behavior** A clear and concise description of what you expected to happen.
There sould be no errors

**Environment (please complete the following information):**

- Version: develop branch of above repo
- OS and Python version: Windows (WSL2 with Ubuntu 20.04)  /  Python 3.9.1

**Comment by ichard26** [comment]
Why did you close this? Was it a mistake or did you fix it yourself? If this is a reproducible bug, we've got a not so fun problem on our hands, so we'll want to know about it.

**Comment by jalajcodes** [comment]
@ichard26 I tried reinstalling it tomorrow but it didn't work, turns out there was a folder named `black-20.8b1.dist.info` that was not getting removed during uninstall. So I deleted it manually and reinstalled black and it works now.
