### ISSUE TITLE
tab inside of docstring

### ISSUE THREAD

**Issue by JakubWysokinski** [psf/black#1944]
Hi, 

**Describe the bug** 
 I got error that black cannot proceed with tab inside of docstring, here is following error log:
 
 ```
--- src
+++ dst
@@ -16951,11 +16951,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'Based on 38.211 - Table 6.3.2.1-1\nFormat 3 - \tLong PUCCH.\nwith large UCI payloads and with no multiplexing capacity in the same PRB',  # str
+                'Based on 38.211 - Table 6.3.2.1-1\nFormat 3 -  Long PUCCH.\nwith large UCI payloads and with no multiplexing capacity in the same PRB',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(

```

**To Reproduce** 

Unfortunetely I cannot give you full file. Here is docstring, however tab got changed to 4 spaces in here.
I launched black with .toml file, which you can find at the bottom. I didn't write there all of the excludes but it should not matter in this case.
```

 """

Based on 38.211 - Table 6.3.2.1-1
Format 3 -     Long PUCCH.
with large UCI payloads and with no multiplexing capacity in the same PRB
"""
```

**Expected behavior** 
not returning error, fixing the docstring or skipping it.

**Environment:**

 python: 3.7.9
 black: 20.8b1 (latest)
 OS: Ubuntu 20.04.1 LTS

```
[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs
    | \.git 
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
  )/
)
'''

**Comment by JelleZijlstra** [comment]
This is fixed on master (#1810).
