### ISSUE TITLE
On lines chaining bitwise operators, Black doesn't try to reduce the line length

### ISSUE THREAD

**Issue by tpilewicz** [psf/black#1947]
**Describe the bug**

I use Airflow for scheduling jobs. The syntax for defining dependencies between tasks is the following:

```
task_1 >> task_2 >> task_3
```

If the names of my tasks are very long, and it crosses the line length limit, black will not try to fix it. Worse: actually if I span my dependencies on several lines with backslashes, black will all put them on one line, causing the line length limit to be crossed. The workaround is to span the dependencies on several lines with parenthesis instead of backslashes, and black will not undo it. But I would expect black to even do it for me.

**To Reproduce** Steps to reproduce the behavior:

1. Take these files:

File 1:

```
loooooooooooooooooooooooooooooooooooooong_task_name = 0
looooooooooooooooooooooooooooong_task_name = 1
loooooooooooong_task_name = 2
loooooooooooooooooooooooooooooooooooooong_task_name >> looooooooooooooooooooooooooooong_task_name >> loooooooooooong_task_name
```

and File 2:

```
loooooooooooooooooooooooooooooooooooooong_task_name = 0
looooooooooooooooooooooooooooong_task_name = 1
loooooooooooong_task_name = 2
loooooooooooooooooooooooooooooooooooooong_task_name \
    >> looooooooooooooooooooooooooooong_task_name \
    >> loooooooooooong_task_name
```

2. Run _Black_ on them with no arguments
3. Result:

File 1 is unchanged. File 2 is formatted into exactly File 1.

**Expected behavior**

File 1 should be formatted so as not to cross the line length limit. For example like this:

```
loooooooooooooooooooooooooooooooooooooong_task_name = 0
looooooooooooooooooooooooooooong_task_name = 1
loooooooooooong_task_name = 2
(
    loooooooooooooooooooooooooooooooooooooong_task_name
    >> looooooooooooooooooooooooooooong_task_name
    >> loooooooooooong_task_name
)
```

File 2 should either be left untouched, or if trailing backslashes are bad, it should be formatted into the example given right above.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Mac / python 3.6.8

**Does this bug also happen on master?** To answer this, you have two options:

yes (checked with the online playground)

**Comment by tpilewicz** [comment]
Hello, I would like to add that is this is recognized as an issue, I'd be pleased to try and fix it.

**Comment by JelleZijlstra** [comment]
@tpilewicz thanks for reporting this issue! I agree that Black should format the code like in your example and I'd welcome a PR.

**Comment by tpilewicz** [comment]
Alright I will give it a try as soon as I have some time!

**Comment by ichard26** [comment]
Closing this has been resolved by GH-2001. @tpilewicz thank you for reporting this issue and submitting a fix!
