### ISSUE TITLE
Projects using black

### ISSUE THREAD

**Issue by RHammond2** [psf/black#1956]
I couldn't really find anywhere else to put this, with there being no contact information, so hopefully this isn't in the way. If this is totally the wrong place, feel free to close it down.

For projects using Black, there are two (and soon a third) projects within the public facing National Renewable Energy Laboratory (NREL) GitHub repository that will be using black in a pre-commit framework for automatic code formatting. The first project and the third (not yet integrated, but working on it) are both fairly major projects within the wind energy modeling space. I figured I'd let you all know given you have a comment in your readme about that.

1) [FLORIS](https://github.com/NREL/floris) - wind farm wake modelling
2) [ORBIT](https://github.com/WISDEM/ORBIT/) - wind farm installation simulation tool for cost assessments
3) [OpenOA](https://github.com/NREL/OpenOA) - SCADA data processing and analysis tool (not yet integrated, but am working on it)

**Comment by cooperlees** [comment]
Awesome. Feel free to do the PR to add it to the README.md if that's your goal here.

**Comment by ichard26** [comment]
Oh how lovely! We actually have a section perfect for this: https://github.com/psf/black#used-by

If you don't mind, you can send in a PR. Don't worry, I can always pick up on the tab if you don't want to or can't.

**Comment by ichard26** [comment]
of course me and cooper *have* to walk on top of each other's toes :D

**Comment by RHammond2** [comment]
Thank you both! I'll put together a PR for this, but might hold off until I get the third project integrated (sometime over the next few weeks) to avoid multiple PRs now that I know that's the best way to do this.

Thanks for all your work on this project, I very much so appreciate it!

**Comment by ichard26** [comment]
Hi @RHammond2, what's the status on this? It's been a quite while :)

**Comment by RHammond2** [comment]
This is my fault, I've quite swamped and let this slide. I'm going to submit a PR now so I don't forget again!
