### ISSUE TITLE
--exclude not working on pycharm

### ISSUE THREAD

**Issue by vasukandimalla** [psf/black#1967]
--exclude is not working when I use it is pycharm file watchers

Below is the screenshot of how I tried configuring

![Screenshot 2021-02-05 at 1 13 25 PM](https://user-images.githubusercontent.com/46773737/107004422-42f41a00-67b4-11eb-9a10-1e871e849f7f.png)

**Expected behavior** 

Black should ignore files under alembic/

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: [MacOS/Big Sur 11.2/ python3 3.8.2 python2 2.7]

**Additional context**
--exclude is ignoring files as expected when i run via terminal 
e.x. `black --exclude=alembic/ alembic/  `

**Comment by ichard26** [comment]
My guess that pycharm is handing in the files directly through the CLI which `--include/--exclude` doesn't touch since they only apply to recursive automatic discovery. `--force-exclude` is like `--exclude` but will exclude matching files and directories even if they're passed via the command line.

**Comment by vasukandimalla** [comment]
@ichard26 that works. Thanks.
