### ISSUE TITLE
Migrate off Travis CI (.org)

### ISSUE THREAD

**Issue by ichard26** [psf/black#1971]
> Looks like Travis is just never finishing, do we still need it?

Travis CI for Open Source is shutting down in a few weeks so the queue for jobs is insane due to lower resources. I'm 99.99% sure we don't need it as our Test, Lint, Docs, Upload / Package, Primer, and Fuzz workflows are all on GitHub Actions. So even though we *can* migrate to the .com version with its 1000 free Linux minutes(?), I don't think we need to.

([more info here](https://blog.travis-ci.com/oss-announcement), [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), and [also here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration))

_Originally posted by @ichard26 in https://github.com/psf/black/issues/1953#issuecomment-771213516_

---

Assuming that we are not migrating to the .com version, there's a few things we should do before travis-ci.org shuts down:

- [Remove Travis CI build badge in docs ](https://github.com/psf/black/blob/master/docs/conf.py#L317) and the [readme](https://github.com/psf/black/blob/master/README.md#the-uncompromising-code-formatter)
- [Remove Travis CI config ](https://github.com/psf/black/blob/master/.travis.yml)
- Migrate Coveralls to use GitHub Actions as the coverage collection source instead of Travis CI
  - [We'll probably use this](https://github.com/marketplace/actions/coveralls-github-action) (I have no idea how to configure this correctly)

edit: removed a stupid colon my brain automatically puts after parentheses lol

**Comment by ichard26** [comment]
>   -  - We'll probably use this (I have no idea how to configure this correctly)

Nope! It doesn't support Python unfortunately

**Comment by LoopThrough-i-j** [comment]
Just out of curiosity: Why use coveralls and not codecov?

**Comment by ichard26** [comment]
> Why use coveralls and not codecov?

Can't tell ya, I joined this project somewhat recently (March 2020 I think?) so core decisions like this one were made far before I was ever involved. It's probably @ ambv who knows why (purposefully not @ ing them since they don't need more notifications).

**Comment by LoopThrough-i-j** [comment]
ahh ok, I understand.
