### ISSUE TITLE
Trailing comma prevents multiline -> single line

### ISSUE THREAD

**Issue by jbnjohnathan** [psf/black#1982]
**Describe the bug** A clear and concise description of what the bug is.
When a python file contains a line split over several lines, which should be one line black does not compress it into one line if there is a trailing comma.

**To Reproduce** Steps to reproduce the behavior:

This code:
```
responseObject = jsonify(
    {
        "status": "success"
    }
)
```
Will be formatted to:
```
responseObject = jsonify({"status": "success"})
```
This is expected behaviour.

But if there is a trailing comma like this:
```
responseObject = jsonify(
    {
        "status": "success",
    }
)
```
The code will not be changed.

**Expected behavior** A clear and concise description of what you expected to happen.
I expect black to move the multiline statement to one line if the line will not be too long, regardless of the trailing comma.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: [e.g. Ubuntu/Python 3.6.9]

**Does this bug also happen on master?** To answer this, you have two options:
Yes it happens on master, tested with https://black.now.sh/?version=master

**Additional context** Add any other context about the problem here.

**Comment by MarcoGorelli** [comment]
Is this the same as #1742 ?

**Comment by jbnjohnathan** [comment]
> Is this the same as #1742 ?

Ah yes indeed! Then this one can be closed as a duplicate
