### ISSUE TITLE
[Feature request] Disable continuous integration for pull requests that are in 'draft' mode

### ISSUE THREAD

**Issue by jayaddison** [psf/black#1992]
**Is your feature request related to a problem?**
Sorta - it'd be nice to have a way to temporarily indicate that an open pull request does not require continuous integration on each commit push.

**Describe the solution you'd like**
GitHub's notion of ['draft' pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) could be useful here.  A draft commit can't be merged; first it has to be marked as 'open' again.

It'd be important to make sure that continuous integration _does_ run on the commit when the state change back to 'open' takes place.

**Describe alternatives you've considered** A clear and concise description of any
- Not pushing until ready - fine, but it's often good to get work out there early and visible and available online
- Developing in a branch - also fine, especially given good developer discipline and attention

**Additional context**
- https://github.community/t/dont-run-actions-on-draft-pull-requests/16817

**Comment by ichard26** [comment]
While I find that having CI run even for draft PRs quite helpful, running CI through my repo clone is good enough. And any benefit by allowing reviewers to review and give feedback early is negated because none of the core team members of Black have enough time to review like that (including me!)

So sure, not a high priority IMO, but it seems reasonable enough.

**Comment by jayaddison** [comment]
Also the risk of continuous integration cost should be mitigated by the presence of developer `pre-commit` checks, I suppose.

**Comment by ichard26** [comment]
> Also the risk of continuous integration cost should be mitigated by the presence of developer pre-commit checks, I suppose.

Yeah, I personally use CI to offload primer and fuzz workflows cause they take forever, but they _can_ be run locally.

**Comment by jayaddison** [comment]
This can be closed for now, I think.  The pull request volume on the project isn't huge, and drafts aren't used frequently within those.  Thanks for the feedback!
