### ISSUE TITLE
Long list of arguments for subprocess

### ISSUE THREAD

**Issue by archiif** [psf/black#2006]
**Describe the style change** 
When constructing a particularly long and complex list of arguments to be passed to `subprocess`, the way Black formats the list makes it rather unreadable. So allowing more flexibility such as being able to group items together would greatly improve the readability of this kind of lists.

**Examples in the current _Black_ style**

```python
args = [
    "ffmpeg",
    "-rtbufsize",
    "150M",
    "-f",
    "dshow",
    "-i",
    'audio="virtual-audio-capturer"',
    "-b:v",
    "1M",
    "-deadline",
    "realtime",
    "-c:a",
    "libopus",
    "-b:a",
    "128k",
    "-y",
    path,
]
```

**Desired style**

```python
args = [
    "ffmpeg",
    "-rtbufsize", "150M",
    "-f", "dshow",
    "-i", 'audio="virtual-audio-capturer"',
    "-b:v", "1M",
    "-deadline", "realtime",
    "-c:a", "libopus",
    "-b:a", "128k",
    "-y",
    path,
]
```

**Comment by cooperlees** [comment]
This was a concious decision and is a part of the chose style. Many reasons but the main one being if an argument is changed it's a simple 1 line change that easy to read. I get your style choice, but how can a formatter sanely make that decision? Very hard to inspect and we'll always get that wrong.

https://black.readthedocs.io/en/stable/the_black_code_style.html#the-magic-trailing-comma

I don't think there is general interest in changing this. But I'll leave open to get other thoughts.

**Comment by archiif** [comment]
What about allowing items within a long list to be grouped together if they fit the current line?

**Comment by Akuli** [comment]
Afaik allowing two different things is not what `black` is about, but you can already use `# fmt: off` and `# fmt: on`.

**Comment by Akuli** [comment]
Here's a somewhat weird workaround:

```
args = (
    ["ffmpeg"]
    + ["-rtbufsize", "150M"]
    + ["-f", "dshow"]
    + ["-i", 'audio="virtual-audio-capturer"']
    + ["-b:v", "1M"]
    + ["-deadline", "realtime"]
    + ["-c:a", "libopus"]
    + ["-b:a", "128k"]
    + ["-y"]
    + [path]
)
```

Black keeps this code unchanged. I found myself doing this not because of black formatting, but because some arguments were not hard-coded:

```
    return subprocess.run(
        [compile_info["cc"]]
        + shlex.split(compile_info["cflags"])
        + [str(path) for path in project_root.glob("obj/*.o")]
        + [str(path) for path in c_paths]
        + ["-o", str(exepath)]
        + shlex.split(compile_info["ldflags"])
        + ["-I", str(project_root)]
    ).returncode
```

**Comment by newbery** [comment]
Regarding the desired style from the OP, is the following good enough?
```python
_args = [
    "ffmpeg",
    "-rtbufsize 150M",
    "-f dshow",
    '-i audio="virtual-audio-capturer"',
    "-b:v 1M",
    "-deadline realtime",
    "-c:a libopus",
    "-b:a 128k",
    "-y",
    path,
]
args = shlex.split(' '.join(_args))
```

**Comment by Akuli** [comment]
That does not work correctly if the path contains spaces or quotes. You can fix it with `shlex.quote(path)` if you really want to use `shlex.split` for this.

**Comment by newbery** [comment]
Indeed. Or alternatively,
```python
args = shlex.split(' '.join(_args[:-1]) + [_args[-1]]
```
:)

**Comment by ichard26** [comment]
Closing in favour of https://github.com/psf/black/issues/2006 (trying to focus discussion and clean up the issue tracker along with Jelle).

Thanks for the feedback tho!
