### ISSUE TITLE
Code is line-broken differently between list and list comprehension when comments are present

### ISSUE THREAD

**Issue by bersbersbers** [psf/black#2012]
**Describe the bug** The following valid pieces of code are line-broken *differently* between list and list comprehension

**To Reproduce** Steps to reproduce the behavior. This is `black`'s output for two pieces of code

```python
import pandas as pd

[
    df
    # comment 1
    .sum().sum()
    # comment 2
    .sum().sum()
    for df in [pd.DataFrame()]
]
```

The following equally valid code has two additional line breaks:
```python
import pandas as pd

df = pd.DataFrame()
[
    df
    # comment 1
    .sum()
    .sum()
    # comment 2
    .sum()
    .sum()
]
```

**Expected behavior** I would expect the two to be formatted similarly. (Maybe it's intended, then I would welcome an explanation.)

**Environment (please complete the following information):**

- Version: today's master
- OS and Python version: also Linux, Python 3.8.8, 20.8b1

**Does this bug also happen on master?** Yes.

**Comment by bersbersbers** [comment]
Here is a related (I think) example not using lists or list comprehension:

```python
df = (
    df
    # Filter 1
    .groupby(["property1"]).filter(lambda x: true)
)
```
vs.
```python
df = (
    df
    # Filter 1
    .groupby(["property1"])
    .filter(lambda x: true)
    # Filter 2
    .groupby("property2")
    .filter(lambda x: true)
)
```

It may have something to do with "would the whole thing fit into one line without the comment" - only if so, don't break behind the comment. But in the interest of minimal diffs, adding a second filter block to the first example should not line-break the first filter block - there is no reason to do that. Each comment block should be regarded separately in my opinion - or at least, if no individual block needs to be broken, no block should be. (I can see why one would want to break all block even if only one block needs to.)

**Comment by JelleZijlstra** [comment]
I think this is #458.
