### ISSUE TITLE
Hang when parsing `# fmt: on` in the middle of an expression

### ISSUE THREAD

**Issue by remyjette** [psf/black#2015]
**Describe the bug**
`black` hangs when parsing `# fmt: on` in the middle of an expression

**To Reproduce**
1. Take this file
```py
from subprocess import run

path = ["."]
run(
    # fmt: off
    [
        "ls",
        "-la",
    ]
    # fmt: on
    + path,
    check=True,
)
```
2. Run _Black_ on it with these arguments `--target-version py38`
3. Observe that black never exits.

**Expected behavior**
Either black should format the file fine (19.10b0 does not have trouble here) or it should error out and tell me it failed to format.

**Environment (please complete the following information):**

- Version: [e.g. master] 20.8b1
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] Linux/Python 3.8.5

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

Yes, it is happening on the online formatter as well.

**Additional context**
If I remove `check=True,` from my example, it works fine. If I move `# fmt: on` after `+ path,` it works fine.

We've modified our code to put `# fmt: on` in a more reasonable location, but still wanted to report it as I wouldn't expect a hang.

**Comment by ichard26** [comment]
Yeah, this is definitely hanging and wow does this (partial) call graph look wrong. Created using 858225d34dc49ca353f9e573dd82dd5845766115 and the code in the bug report.
![Screenshot from 2021-03-02 20-22-21](https://user-images.githubusercontent.com/63936253/109738198-63d24400-7b95-11eb-8de8-b0c99f8e904d.png)
