### ISSUE TITLE
parenthesized 'a if b else c' in dict

### ISSUE THREAD

**Issue by Akuli** [psf/black#2018]
**Examples in the current _Black_ style** This code looks terrible, but is unchanged by black:

```python
if blah:
    if blah:
        if blah:
            blah = blah_blah_blah_blah_blah_blah_blah_blah_blah_blah_blah % {
                "blah_blah_blah": "a"
                if blah_blah_blah_blah_blah_blah_blah_blah_blah
                else "b"
            }
```

**Desired style** If I add parentheses before `"a"` and after `"b"`, black converts it to this good-looking code:

```python
if blah:
    if blah:
        if blah:
            blah = blah_blah_blah_blah_blah_blah_blah_blah_blah_blah_blah % {
                "blah_blah_blah": (
                    "a" if blah_blah_blah_blah_blah_blah_blah_blah_blah else "b"
                )
            }
```

It would be nice if black would always do this, regardless of whether the original code contains parentheses or not.

**Additional context** None

**Comment by JelleZijlstra** [comment]
I agree, a PR would be welcome.

**Comment by felix-hilden** [comment]
I believe this is the same proposal as #620, which has more discussion. So I'll close this issue in favor of it!
