### ISSUE TITLE
Passing args to the github action

### ISSUE THREAD

**Issue by rhiaro** [psf/black#2019]
Arguments passed to the github action don't do anything.

The [docs here](https://black.readthedocs.io/en/stable/github_actions.html) don't demonstrate arg passing at all. The [docs here](https://github.com/psf/black/blob/master/docs/github_actions.md) say to pass `black_args` but that results in an error saying only `args` is valid input. Using:

```
uses: psf/black@stable
with:
  args: "standards_lab/ --check --diff"
```

appears to pass the args:

![Screenshot at 2021-03-04 12-00-38](https://user-images.githubusercontent.com/466229/109960930-43170500-7ce1-11eb-96da-da017fdff7c1.png)

but they aren't actually effective. I tried this with ``--line-length`` as well. Am I using this wrong?

**Expected behavior**

Black operates with the arguments applied, ie. only checks the directory passed, or applies a line length amendment.

**Environment:**

- Version: `psf/black@stable`
- OS and Python version: Linux (ubuntu-latest)/Python 3.9.1

**Comment by cooperlees** [comment]
Pretty sure that support was added after the last release / stable tag. Try with @master or / @main and it should work.

**Comment by rhiaro** [comment]
Yep, works with `@master`, thanks!
