### ISSUE TITLE
Two blank lines after an import should be reduced to one

### ISSUE THREAD

**Issue by WhyNotHugo** [psf/black#2020]
**Describe the style change**

This applies to the first line of code after the block of imports at the top of the file.

These lines are not changed by black:

```python
from middleman.authentication import validate_oauth_token

logger = logging.getLogger(__name__)
```

This is changed to the above (makes sense to me):

```python
from middleman.authentication import validate_oauth_token
logger = logging.getLogger(__name__)
```

However, black does not reformat this:

```python
from middleman.authentication import validate_oauth_token


logger = logging.getLogger(__name__)
```

This is very annoying since it allows for inconsistency.

**Desired style**

I think `black` should reformat that final example to look like the first. As an alternative, it could also always leave two lines. Either one or two lines is fine by me, but only **one** option should be valid.

**Additional context**

I think it's that simple.

**Comment by ichard26** [comment]
_I'm sure I've seen a design issue talking about this, but I can't seem to find it..._

**Comment by ichard26** [comment]
Also, can't reproduce on the [Black Playground](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACsAIJdAD2IimZxl1N_WlkPinBFoL0tm5t9q_PtbHR0oyjvbRFsA487w7rIMkOvflq1Y-1KqdGGzb0ogBkSYLenu-KK7qAZXK6QBNNfZZ-X70QyUuQ-r43928PK_VJok5PJZiMFCWyg-tnwg3-9eVTqS381oquJf6AtaPxJ21DejwuQORztymAAAABBG--aeLR9IgABngGtAQAAsSGaZ7HEZ_sCAAAAAARZWg==).

**Comment by JelleZijlstra** [comment]
Can't find any duplicates in https://github.com/psf/black/labels/F%3A%20empty%20lines. The bug is really that the last example (with two lines after the import) doesn't get reduced to one line, and I can reproduce that on main.

**Comment by felix-hilden** [comment]
The two-line issue still persists: [playground](https://github.com/psf/black/issues/799)

**Comment by kastkeepitjumpinlikekangaroos** [comment]
hey! I opened a PR here trying to address this issue https://github.com/psf/black/pull/4489 - I made some test cases from the examples in the issue description which are working as described
