### ISSUE TITLE
Better multiline formatting for binary operators with function calls in operands

### ISSUE THREAD

**Issue by rmorshea** [psf/black#2023]
One things that's bugged me about `black` for a while is the way it handles the multiline formatting for binary operators when their operands are function calls. The case that most frequently occurs for me is in `if` statements. Consider the unformatted code below:

```python
if some_function(an_argument) or some_other_function(another_argument, yet_another_argument):
    ...
```

Presently `black` will reformat this in the following way:

```python
if some_function(an_argument) or some_other_function(
    another_argument, even_more_arguments
):
    ...
```

When I skim over the code above, I tend to read it a little like this:

```python
if some_functi_________________________ther_function(
    another_argument, even_more_arguments
):
    ...
```

I end up passing over the content in the middle because:

1. The arguments of the second function stands out and draw my attention
2. This is a common reformatting pattern for other function calls that do not have operators on the same line

Further, even if you're someone who is able to read this correctly, this reformatting isn't "symetric" (for lack of a better word). Putting each operand of `or` into its own line would improve the aesthetics a great deal:

```python
if (
    some_function(an_argument)
    or some_other_function(another_argument, yet_another_argument)
):
    ...
```

Yes, it takes up an extra line or two, but using more lines doesn't cost you anything, and I think the easier readability/aesthetic benefit is substantial. It's also worth noting that this form is what black adopts as soon as you add one more operator into the equation. For example, given the following unformatted code:

```python
if some_function(an_argument) or some_other_function(another_argument, yet_another_argument) or the_last_thing:
    ...
```

`black` will reformat it into the more pleasing form:

```python
if (
    some_function(an_argument)
    or some_other_function(another_argument, yet_another_argument)
    or the_last_thing
):
    ...
```

So beyond trying to reduce the number of lines in a file, it's not clear to me what the benefit of this form is:

```python
if some_function(an_argument) or some_other_function(
    another_argument, yet_another_argument
):
    ...
```

**Comment by rmorshea** [comment]
I've realized the current behavior for this is rather inconsistent too. The following:

```python
if my_really_long_function_name(the_first_argument, the_second_argument) or my_other_function(and_its_argument):
    ...
```

Get's formatted as:

```python
if my_really_long_function_name(
    the_first_argument, the_second_argument
) or my_other_function(and_its_argument):
    ...
```

When this form happens to pass 88 characters:

```python
if my_really_long_function_name(the_first_argument, the_second_argument) or my_other_function(
    and_its_argument
):
    ...
```

So adopting the proposed strategy for reformatting conditions described above would also help with the consistency too since there would only be one way to reformat in either scenario.

**Comment by felix-hilden** [comment]
I think this is essentially the same as #2156, so I'll close this in favor of it, thanks for reporting!
