### ISSUE TITLE
fmt: skip is not working

### ISSUE THREAD

**Issue by AstroMatt** [psf/black#2024]
`# fmt: skip` is not working:

```
data = {'a': 1, 'b': 2}
rev = {v:k for k,v in data.items()}  # fmt: skip
```

But turning off and on works well:

```
# fmt: off
data = {'a': 1, 'b': 2}
rev = {v:k for k,v in data.items()}
# fmt: on
```

**Environment (please complete the following information):**

* black, version 20.8b1 (fresh install from pip)
* Python 3.9.1
* macOS 11.3

**Comment by ichard26** [comment]
Support for `fmt: skip` was just recently merged into the main branch, so the latest release doesn't contain this feature. Using Black [from the main branch works as expected](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACWAHRdAD2IimZxl1N_Wlbsjje2biO6uuR9bCrS1OHApgsNW0TaWfma0Px-nah1xnhPcDl7P4lcRWDpctuviv4C410xNXR-8E19bsFXicGUvevaC_jrzFs_C318nNca7IYxPhlCcphhaBbc82yEo8K_nKwtD8_b7RcAAEGqD7uCKtjgAAGQAZcBAAAEWAbCscRn-wIAAAAABFla). 

Although I just realized that it doesn't have a changelog entry! Will fix that. 

Hope that clarifies things! Thanks.
