### ISSUE TITLE
Style: Problem with list

### ISSUE THREAD

**Issue by AstroMatt** [psf/black#2026]
**Describe the style change** A clear and concise description of how the style can be
improved.

I have the following code

```
DATA = [1, 4, 6, 7, 4, 4, 4, 5, 1, 7, 0,
        0, 6, 5, 0, 0, 9, 7, 0, 4, 4, 8,
        2, 4, 0, 0, 1, 9, 1, 7, 8, 8, 9,
        1, 3, 5, 6, 8, 2, 8, 1, 3, 9, 5,
        4, 8, 1, 9, 6, 3]
```

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

```python
DATA = [
    1,
    4,
    6,
    7,
    4,
    4,
    4,
    5,
    1,
    7,
    0,
    0,
    6,
    5,
    0,
    0,
    9,
    7,
    0,
    4,
    4,
    8,
    2,
    4,
    0,
    0,
    1,
    9,
    1,
    7,
    8,
    8,
    9,
    1,
    3,
    5,
    6,
    8,
    2,
    8,
    1,
    3,
    9,
    5,
    4,
    8,
    1,
    9,
    6,
    3,
]
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
DATA = [1, 4, 6, 7, 4, 4, 4, 5, 1, 7, 0,
        0, 6, 5, 0, 0, 9, 7, 0, 4, 4, 8,
        2, 4, 0, 0, 1, 9, 1, 7, 8, 8, 9,
        1, 3, 5, 6, 8, 2, 8, 1, 3, 9, 5,
        4, 8, 1, 9, 6, 3]
```

Or at least:

```python
DATA = [1, 4, 6, 7, 4, 4, 4, 5, 1, 7, 0,  0, 6, 5, 0, 0, 9, 7, 0, 4, 4, 8, 2, 4,
        0, 0,  1, 9, 1, 7, 8, 8, 9, 1, 3, 5, 6, 8, 2, 8, 1, 3, 9, 5, 4, 8, 1, 9, 6, 3]
```

**Additional context** Add any other context about the problem here.

* black, version 20.8b1 (fresh install from pip)
* Python 3.9.1
* macOS 11.3

**Comment by ichard26** [comment]
Closing in favour of https://github.com/psf/black/issues/1281.

Thank you for your feedback though!
