### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by stijntratsaertit** [psf/black#2032]
When chaining multiple .get()'s on a dictionary within an if Black is not formatting the specified file anymore and throws an error in the terminal.

When I manually started a new line after each '.get("..")' black suddenly started formatting correctly again.

**Environment (please complete the following information):**
- Version: 20.8b1
- OS and Python version: Debian/Python3.9.1

**Additional context**
Part of logfile where things go wrong:
```
-    def _extract_group_permission(self, permission: dict) -> Iterator[IntegrationPermission]:
-        if group_displayname := permission.get("grantedTo").get("user").get("displayName"):
+    def _extract_group_permission(
+        self, permission: dict
+    ) -> Iterator[IntegrationPermission]:
+        if (
+            group_displayname := permission.get("grantedTo")
+            .get("user")
+            .get("displayName")
+        ):
```

**Comment by ichard26** [comment]
I'm pretty sure this is a duplicate of https://github.com/psf/black/issues/1588.

**Comment by ichard26** [comment]
Closing since it's impossible to figure what is the problem here. If someone comes with a functional repro case, I'm open to reopening.
