### ISSUE TITLE
Sort imports alphabetically

### ISSUE THREAD

**Issue by arazi47** [psf/black#2033]
**Is your feature request related to a problem? Please describe.** A clear and concise
description of what the problem is. Ex. I'm always frustrated when [...]

I use black and flake8 together, and black always solves my problems and always makes flake8 happy, except for not sorting the imports alphabetically.

**Describe the solution you'd like** A clear and concise description of what you want to
happen.

I want black to sort my imports alphabetically.

**Describe alternatives you've considered** A clear and concise description of any
alternative solutions or features you've considered.

I just sort my imports by hand.

**Additional context** Add any other context or screenshots about the feature request
here.

e.g.:
```
import os
import math
```

would turn to

```
import math
import os
```

**Comment by JelleZijlstra** [comment]
Already being discussed in #333
