### ISSUE TITLE
Redundant parentheses around return annotation

### ISSUE THREAD

**Issue by NeilGirdhar** [psf/black#2041]
```python
def infer_encoding_trajectory(encoding: EncodingElement,
                              observation: PoolingMessage,
                              prediction: PredictionMessage,
                              weights: hk.Params,
                              rng: Generator,
                              iterations: int) -> (
                                  tuple[EncodingState, EncodingTrajectory]):
```
became
```python
def infer_encoding_trajectory(
    encoding: EncodingElement,
    observation: PoolingMessage,
    prediction: PredictionMessage,
    weights: hk.Params,
    rng: Generator,
    iterations: int,
) -> (tuple[EncodingState, EncodingTrajectory]):
```
The parentheses were only there to allow wrapping and should have been removed.  In general, black doesn't need to preserve parentheses around an entire expression, including a type annotation.

**Comment by JelleZijlstra** [comment]
I agree, a PR would be welcome. In general, there's a number of places where Black should remove parentheses that it currently keeps. From past experience it's tricky sometimes to remove parentheses without causing stability bugs, but maybe in this context it won't be too bad.
