### ISSUE TITLE
Proposal: use mode 1 when all lines fit

### ISSUE THREAD

**Issue by NeilGirdhar** [psf/black#2042]
I realize that this is going to be a very unpopular feature request, but it's the only thing stopping me from using Black, and I love the idea of Black, so I feel compelled to propose it.  Feel free to close this as "will not implement".

Fundamentally, Black has [chosen](https://black.readthedocs.io/en/stable/the_black_code_style.html) to wrap lines in one of three ways: single line, separate indented line, multi-line.  The multi-line output is like [mode 3](https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes/) of isort.

While mode 3 is very versatile, it is harder to read than mode 1.  My proposal is to try mode 1 to see if all lines fit without wrapping, and if so use that before using mode 3.  For example, in mode 3, we have
```python
        return PredictionMessage(
            self.observation + other.observation,
            self.prediction + other.prediction,
            self.desire + other.desire,
        )
```
but in mode 1, we have
```python
        return PredictionMessage(self.observation + other.observation,
                                 self.prediction + other.prediction,
                                 self.desire + other.desire)
```
Of course legibility is in the eye of the beholder, but the two points in favour of mode 1 are that:

-  The arguments sit to the right of the function call, which makes the function call more visually obvious.
-  The output takes fewer lines of vertical space.  Minimizing vertical space means that more code is visible on the screen, which makes reasoning about large functions a lot easier since you don't need to scroll and memorize code.

For the same reason, in the case of exactly two or three arguments, mode 1 is in my opinion preferable over the single indented line: 
```python
        return PoolingMessage(
            self.presence + other.presence, self.pooled_value + other.pooled_value
        )
```
but in mode 1, we have 
```python
        return PoolingMessage(self.presence + other.presence,
                              self.pooled_value + other.pooled_value)
```
Again, we have the benefit of distinct function calls, and less vertical space.  We also have each argument on its own line, which makes them easier to distinguish without looking for commas.

I concede that when there is a line that doesn't fit within the line length, mode 3 is superior.  Similarly, when there are many arguments that all fit in the single-indented-line format, then that format is superior.  I'm not proposing eliminating those modes.  I'm proposing adding mode 1 in particular cases.  In short, my proposal is to format as follows:

- single line if possible (as before)
- **mode 1 if there are 2 or 3 arguments and all lines fit** (proposed)
- single indented line if possible (as before)
- **mode 1 if all lines fit** (proposed)
- mode 3 otherwise (as before)

I realize that Black's rules are simple, but if the goal is to write code the way humans read and write code, I think a little bit of extra complexity in the rules would go a long way to making code easier for people to read.  The downside of this proposal is longer diffs, but diffs are read a lot less often than code is read as it's being worked on.

**Comment by Gyllsdorff** [comment]
> While mode 3 is very versatile, it is harder to read than mode 1.

Objection! Opinion. 😉

At least for me mode 3 is way easier to read, instead of having to mentally figure out if the wrapped lines are going to appear hanging with a lot of whitespace to left or if it will be indented one level I know exactly where to look. It also makes it easier to spot deeply nested code at a glance since the indentation follows a easily predictable pattern.

**Comment by JelleZijlstra** [comment]
We're very unlikely at this point to make such a fundamental change to Black's code style.
