### ISSUE TITLE
Support "py39" option for "--target-versions" parameter

### ISSUE THREAD

**Issue by vyahello** [psf/black#2043]
**Is your feature request related to a problem? Please describe.**
Since python3.9 is officially released it would be great to add support for "py39" for "--target-version" option. Currently, black supports the following versions - [py27|py33|py34|py35|py36|py37|py38].

**Describe the solution you'd like** 
Add "py39" option as a new supported target version.

**Comment by ichard26** [comment]
Black on master does support `--target-version py39` but Python 3.9 support is not fully completed IIRC. Currently relaxation of decorator syntax support is the only feature hidden by the flag value IIRC.

**Comment by eli-b** [comment]
My project requires Python 3.9. As a result, I have to install Black from the Github repository, since my project package manager (Pipenv) doesn't allow me to install Black from PyPI because no PyPI version of Black supports Python 3.9.

**Comment by JelleZijlstra** [comment]
Pull requests are welcome. This should be an easy fix to make.

**Comment by abid-mujtaba** [comment]
As @ichard26 mentioned the required changes are already in `master`, they just aren't on `stable` yet. I am assuming a Pull Request is unnecessary in this case.

**Comment by JelleZijlstra** [comment]
Sorry for missing that! We should really get around to making a release.

**Comment by tommilligan** [comment]
This is now released, tested in `black==21.5b1`. @vyahello are you happy to close this issue?

**Comment by cooperlees** [comment]
Yeah, this is definitely out and about i the wild. Please reopen if we've missed anything.

**Comment by vyahello** [comment]
@tommilligan thanks for releasing the changes, appreciate this!
