### ISSUE TITLE
Make Python 2 support an "extra" (removed the dependency on typed-ast)

### ISSUE THREAD

**Issue by KotlinIsland** [psf/black#2044]
https://github.com/python/mypy/issues/10124
https://github.com/python/mypy/pull/10183/files

typed-ast is a pain and not required for py >= 3.8

Can something similar to mypy be implemented where python 2 support is extra?

**Comment by ichard26** [comment]
I'm personally +1 for this but it would have to quite well managed and well signalled to reduce breakage and breakage duration. Right now we informally tell users that Python 2 support won't be removed for the foreseeable future and this change would break that.

@cooperlees @JelleZijlstra initial thoughts?

**Comment by JelleZijlstra** [comment]
Maybe we can eventually remove Python 2 support? I personally don't use it, but clearly some people still do.

I wonder if making typed-ast an extra could also break some Python 3 use cases, like formatting Python 3.9-only code with Black running under 3.6.

**Comment by cooperlees** [comment]
I feel we just copy mypy here and add the version gate + extra install to `typed-ast`.

E.g.: Adding `; python_version<'3.8'` should fix most things.
https://github.com/psf/black/blob/master/setup.py#L74
- We can also copy the extra install:
```python
extras_require={'python2': 'typed-ast>=1.4.2'},
```

I have no idea with poetry tho. I am sure we'd need changes there too. but I'd totally accept this PR.

**Comment by ichard26** [comment]
Closing as this was implemented by GH-2053. If there's any issues, either comment them here or create a new issue. Thanks @KotlinIsland for the request!
