### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by rggjan** [psf/black#2045]
On:
https://black.readthedocs.io/en/latest/editor_integration.html

The enumeration is not rendered properly, and it shows:
```
PyCharm/IntelliJ IDEA¶
1. ...
1. ... 
1. ...
1. See it `install_location_from_step_2`
```

**Comment by bene64** [comment]
It seems that this is some error within [sphinx](https://github.com/sphinx-doc/sphinx). The enumeration itself is a valid markdown file, so it should render to 1.,2.,...

The markdown file itself renders nicely on github: https://github.com/psf/black/blob/master/docs/editor_integration.md
