### ISSUE TITLE
Issue with --extend-exclude parameter

### ISSUE THREAD

**Issue by arefrazavi** [psf/black#2060]
**Describe the bug** 
It seems that `--extend-exclude` doesn't work on the 20.8b1 version.

**To Reproduce** 

1. Run _Black_ on it with these arguments '--extend-exclude ':
```
 black --extend-exclude venv/ .
```
2. See error:
```
Error: no such option: --extend-exclude
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Linux/Python 3.8.5

**Does this bug also happen on master?** 
No

**Comment by JelleZijlstra** [comment]
It will exist in the next release
