### ISSUE TITLE
Long strings not broken?

### ISSUE THREAD

**Issue by kierdavis** [psf/black#2062]
**Describe the bug**

With #1132 merged, I would expect strings that are longer than the line length limit and are located as the value of a keyword argument to be broken into multiple lines, but I don't see this behaviour in practice.

**To Reproduce**

```
[user@host ~] pip install 'git+https://github.com/psf/black.git#egg=proj'
...
[user@host ~] black --version
black, version 20.8b1
[user@host ~] cat test.py
foo(
    bar="a really really really really really really really really really really really really really really really really really long string",
)
[user@host ~] black test.py
All done! ✨ 🍰 ✨
1 file left unchanged.
[user@host ~] cat test.py
foo(
    bar="a really really really really really really really really really really really really really really really really really long string",
)
```

**Expected behavior**

`test.py` to be reformatted to look like the examples in #1132, something like:

```python
foo(
    bar=(
        "a really really really really really really really really really"
        " really really really really really really really really long string"
    ),
)
```

**Environment (please complete the following information):**

- Version: master
- OS and Python version: RHEL 7 + Python 3.6.8

**Does this bug also happen on master?**

Yes (both when installed locally and on black.now.sh).

**Comment by JelleZijlstra** [comment]
This is currently behind the `--experimental-string-processing` flag. We'll enable that by default once the feature is stable.
