### ISSUE TITLE
Numeric literal formatting is inconsistent with Black code style document

### ISSUE THREAD

**Issue by jack1142** [psf/black#2066]
According to [Numeric literals section of Black code style](https://github.com/psf/black/blob/master/docs/the_black_code_style.md#numeric-literals), the numeric literals should use lowercase letters for the syntactic parts and uppercase letters for the digits themselves but this seems to no longer be the case on `master` (has been changed in #1775). I don't really agree with that change but nonetheless, the implementation should be consistent with the documentation so it looks like one of these needs changing.

I used a blank issue as this very well may just be a documentation issue.

**Comment by JelleZijlstra** [comment]
The current documentation in https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#numeric-literals is consistent with Black's actual behavior. (We changed back to uppercase for hex digits.)
