### ISSUE TITLE
Internal error due to second pass mismatch  

### ISSUE THREAD

**Issue by javierhonduco** [psf/black#2068]
**Describe the bug** 

Black fails to format a file due to inconsistent subsequent reformatting (`INTERNAL ERROR: Black produced different code on the second pass of the formatter.`)

**To Reproduce** Steps to reproduce the behavior:

```shell
➜  ~ cat black_repro.py
```

```python3
return calculate_timedelta(
    # comment
    param1, param2
) / datetime.timedelta(days=self._step)
```
```shell
➜  ~ black black_repro.py
error: cannot format black_repro.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/20/wmj13sqn4llcdlg29q8dn2xh0000gn/T/blk__vpfxszf.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Environment (please complete the following information):**

Repros on Linux:
```shell
➜  ~ black --version
black.linux, version 20.8b1
➜  ~ python3 --version
Python 3.8.6
```
and MacOS:
```shell
➜  ~ black --version
black.macos, version 20.8b1
➜  ~ python3 --version
Python 3.7.5
```

**Does this bug also happen on master?** To answer this, you have two options:

[repros](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC0AH5dAD2IimZxl1N_WmXWfJWiTYL4H5VX3XzzWFR_s1X-_T81UKjRbBADWbqR6MFUO1Z9aWKB7aQGMMJ6l0pxjEvgEvG4jhLxQxK0p8nzlHjIsor9XAGlqpRFStZqsB2uDIlf51RdKPXKpRfH2WUwUeeovDWf2r2z41v-NzTWawbOkwAAAOT3kkeu18BAAAGaAbUBAADXHKZpscRn-wIAAAAABFla) (black.now.sh is amazing stuff btw, thanks!):

<details>

```
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_swphvz7x.log

Mode(target_versions=set(), line_length=88, string_normalization=True, magic_trailing_comma=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,4 +1,5 @@
 return calculate_timedelta(
     # comment
-    param1, param2
-) / datetime.timedelta(days=self._step)
\ No newline at end of file
+    param1,
+    param2,
+) / datetime.timedelta(days=self._step)
--- first pass
+++ second pass
@@ -1,5 +1,8 @@
-return calculate_timedelta(
-    # comment
-    param1,
-    param2,
-) / datetime.timedelta(days=self._step)
+return (
+    calculate_timedelta(
+        # comment
+        param1,
+        param2,
+    )
+    / datetime.timedelta(days=self._step)
+)

```
</details>

**Additional context**
This bug wasn't found as a result of fuzzing or any other testing technique, it was found in our codebase (if you are a FB employee: https://fburl.com/diffusion/9t7h8e06). I just minimised it a bit.

Thanks!!

**Comment by javierhonduco** [comment]
Seems like it might be https://github.com/psf/black/issues/1629

**Comment by ichard26** [comment]
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!
