### ISSUE TITLE
Remove non-breaking space at the beggining of comments

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [psf/black#2091]
Black apply a space after a ``#`` in comment like so:
```diff
- #Comment content 
+ # Comment content 
```
The thing is, often we developers fat fingers an insecable space after creating the ``#`` by not releasing the <kbd>Alt Gr</kbd> key fast enough.

Then black had a space before it resulting in visually two spaces:
```diff
- # Comment content 
+ #  Comment content 
```

I'd like black to remove insecable spaces at the beginning of comment and then replaces them with a real space:
```diff
- # Comment content 
+ # Comment content 
```

**Comment by JelleZijlstra** [comment]
By "insecable space" do you mean the non-breaking space (nbsp) character https://www.compart.com/en/unicode/U+00A0 ? If so it seems reasonable to me for Black to replace leading nbsps in comments.

**Comment by Pierre-Sassoulas** [comment]
Yes, sorry if it was not clear I translated the name from french.

**Comment by JelleZijlstra** [comment]
I'd merge it (unless someone else comes up with a problem with this suggestion).

**Comment by Pierre-Sassoulas** [comment]
@ichard26 answered my question : https://github.com/psf/black/pull/2092#issuecomment-817178166
