### ISSUE TITLE
There is no normal release in PyPI, only pre-releases.

### ISSUE THREAD

**Issue by yanqd0** [psf/black#2115]
**Is your feature request related to a problem? Please describe.** 

There is no normal release in PyPI, only pre-releases.

https://pypi.org/project/black/#history

Normal releases is better. In some cases, pre-release versions are not preferred by default, like `pipenv lock`.

```shell
$ pipenv lock
...
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.                    
ERROR: Could not find a version that matches black (from betterproto[compiler]==1.2.5->-r /tmp/pipenv4ukrxon_requirements/pipenv-wgm4qc5a-constraints.txt (line 11))
Skipped pre-versions: 18.3a0, 18.3a0, 18.3a1, 18.3a1, 18.3a2, 18.3a2, 18.3a3, 18.3a3, 18.3a4, 18.3a4, 18.4a0, 18.4a0, 18.4a1, 18.4a1, 18.4a2, 18.4a2, 18.4a3, 18.4a3, 18.4a4,
 18.4a4, 18.5b0, 18.5b0, 18.5b1, 18.5b1, 18.6b0, 18.6b0, 18.6b1, 18.6b1, 18.6b2, 18.6b2, 18.6b3, 18.6b3, 18.6b4, 18.6b4, 18.9b0, 18.9b0, 19.3b0, 19.3b0, 19.10b0, 19.10b0, 20
.8b0, 20.8b1                                                                          
There are incompatible versions in the resolved dependencies:
```

In this case, `pipenv lock --pre` is not a good solution. I can trust `black`, but I can't trust any pre-release version of other projects.

It is `black`'s fault to release a normal version like a pre-release version.

**Describe the solution you'd like**

Yes, `black` may still be beta status. But the version can be set to `20.8.1`, instead of `20.8b1`. `20.8b1` means the beta version of `20.8`, not the project.

References:
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

**Comment by JelleZijlstra** [comment]
See the pinned issue #517
