### ISSUE TITLE
Contra docs, Black does not add backslashes for multiple context manages

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#2118]
https://black.readthedocs.io/en/latest/the_black_code_style.html says:

> Black always gets rid of backslashes, [with] one exception: with statements using multiple context managers. Python’s grammar does not allow organizing parentheses around the series of context managers.
> 
> We don’t want formatting like:
> 
> ```python
> with make_context_manager1() as cm1, make_context_manager2() as cm2, make_context_manager3() as cm3, make_context_manager4() as cm4:
>     ...  # nothing to split on - line too long
> ```
> 
> So Black will now format it like this:
> 
> ```python
> with \
>      make_context_manager(1) as cm1, \
>      make_context_manager(2) as cm2, \
>      make_context_manager(3) as cm3, \
>      make_context_manager(4) as cm4 \
> :
>     ...  # backslashes and an ugly stranded colon
> ```

but Black 20.8b1 doesn't make any changes to the input line.

**Comment by ichard26** [comment]
Sigh, this issue has been noted before:

> [...] I dislike that we advertise that Black handles with statements in a sane manner in the documentation, yet none of the work needed for any of it has seen the light of day. Doing documentation-driven development is good, but I think we're sending the wrong signal if the actual development ends up never finished. But, just my opinion, shrugs.

by @ichard26 (i.e. me!) https://github.com/psf/black/issues/1948#issuecomment-770285226

This will be fixed once I finish up the documentation reorganization effort I'm doing, but I've been slow.

**Comment by felix-hilden** [comment]
The documentation reorganisation has been done, and the information is now in [The future of the Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html). Can this issue be closed?
