### ISSUE TITLE
Black runs into internal error when docstring ends with EM QUAD

### ISSUE THREAD

**Issue by jack1142** [psf/black#2120]
**Describe the bug**

**To Reproduce**

1. Copy this code (it needs to be copied as it contains `\u2001` character at the end of first docstring line):
```py
def foo():
    """A special character: ` 
`
    """
```
2. Run _Black_ on it with the default configuration.
3. See error:
```diff
INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_o610r37n.log

--- src
+++ dst
@@ -16,11 +16,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'A special character: `\u2001\n`',  # str
+                'A special character: `\n`',  # str
             )  # /Constant
         )  # /Expr
       decorator_list=
       name=
         'foo',  # str

```

**Expected behavior**
No error

**Environment:**

- Version: both stable and master
- OS and Python version: Windows/Python 3.8 (as well as whatever is running on Black Playground)

**Does this bug also happen on master?** Yes

**Additional context**
None

**Comment by JelleZijlstra** [comment]
This is https://www.compart.com/en/unicode/U+2001, a whitespace character, so presumably we're stripping it as trailing whitespace in the docstring processing code, but not accepting the change in the safety check. Shouldn't be hard to fix.
