### ISSUE TITLE
Give us tab support

### ISSUE THREAD

**Issue by caniko** [psf/black#2122]
I want my Python code to have tabs instead of spaces, and want to use black. Please give us the option to use tabs instead of spaces.

Just calling something evil, and shutting down the conversation is unfair to those who need/want this functionality, #47. There is a live implementation in https://github.com/jleclanche/tan, I think it has some bugs, but at least a step in the right direction.

Give the developer more power.

**Comment by JelleZijlstra** [comment]
Black's philosophy is to minimize formatting options. Our choice is to use spaces; you are free to make a different choice.

**Comment by caniko** [comment]
Ironically this sort of thinking goes against what is written in you contribution section:
![image](https://user-images.githubusercontent.com/29519599/115677154-be8b4f00-a33f-11eb-9ba2-5543d4f09864.png)

**Comment by simaki** [comment]
Let me kindly add one thing.

Black is PEP8 compliant in its philosophy,
> Black is a PEP 8 compliant opinionated formatter. 
(https://github.com/psf/black#the-black-code-style)

and PEP8 recommends spaces.
> Spaces are the preferred indentation method.
(https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)

I personally don't think tab is a devil and everyone can of course opt tab.
It's just that Black doesn't fit such a case the best.

Black is strict, while its community is I think open to conversation.
 I look forward to more suggestions for improvement. Happy coding!

**Comment by caniko** [comment]
I like your don't step on any egg shells attitude :dagger: 

I don't think any high-profile person in PSF is open to any sort of discussion on this topic. Wanted to see if things are changing, but no, most high-profile developers are still following old text written by the retired founder. Resemblance?

OK, trolling aside. I really do think PEP8 is wrong on line-lengths, which Black does deviate from PEP8 (80 * 1.1). It is even allowed to be configured (one of the few parts that is configurable, the discussion is hilarious #290).

Rant: I still don't understand why tabs are not the defacto indentation character, with basis on history yes, but not pragmatically.

**Comment by JelleZijlstra** [comment]
@caniko to be clear, "as configurable as gofmt" means "*not* configurable" (https://golang.org/cmd/gofmt/).

Whether I like spaces or tabs doesn't matter. The reason I'm closing all issues asking for big changes in formatting style is that Black is already widely used as a formatter, and any big changes would be disruptive.

**Comment by kamahen** [comment]
If you want tabs, there's a tool for doing that: https://linux.die.net/man/1/expand

Simply pipe your black output to expand and you're done.

If you want more choices in how the source is formatted, I suggest yapf (https://github.com/google/yapf). But there are probably things in yapf that you won't like, such as its philosophy is to not make any source-level changes (e.g., adding/removing parentheses). But a combination of black and yapf might get what you want. ;)

FWIW, I've worked at a few places that had a period of "discussion" about formatting standards. In the end, we all agreed to compromise on a standard that didn't make anyone perfectly happy; but it was better to have a non-negotiable standard than no standard. Non-negotiable formatting rules have a pretty long history -- the oldest one I know of is https://en.wikipedia.org/wiki/Plus_(programming_language)

**Comment by sciyoshi** [comment]
@simaki @caniko you can use this patch which is against the latest main branch and adds support for tabs: https://github.com/sciyoshi/black/commit/faddb504b395c71a92e6a9ffadaafcc9413ecd88

**Comment by caniko** [comment]
I appreciate it @simaki. Hopefully a feature like this makes it into the main branch one day
