### ISSUE TITLE
INTERNAL ERROR when formatting a function with a comment over max line length

### ISSUE THREAD

**Issue by inftydev** [psf/black#2124]
**Describe the bug** 
Black produced different code when formatting a function with a comment over max line length.

**To Reproduce**

1. Take this code 
```python
def foo():
    context.this_is_here_so_we_get_a_line_that_is_too_long = Bar(  # and now it is too long
        some=argument
    )
```

2. Run _Black_ on it
3. See error 
```
$ black make_black_sick.py
error: cannot format make_black_sick.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_frk8cnu0.log
Oh no! 💥 💔 💥

1 file failed to reformat.
```
[blk_frk8cnu0.log](https://github.com/psf/black/files/6357906/blk_frk8cnu0.log)

**Expected behavior** 
The file is reformatted

**Environment (please complete the following information):**
- Version: black, version 20.8b1
- OS and Python version:  Linux/Python 3.8.6

**Does this bug also happen on master?** 
Yes, [show code on black.vercell.app](https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADUAJtdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyZPtcsSAj0SAyBfvORzYaBbZewuJ_pKeSVIFgZAjLu4Ab1nr32UxLvmfDm3TXOeDmRxq9xEPut9vE3SrsmmuvFrXPxqKcQPDJxgaLR-qOLHzX-81Pfu2NW0y4fDNHXZoHyhSvwxHgQUae_gD7A8SiJS6qvUKkK32S9BtGQoQtjgOTerYAADmj6Cnk1AELQABtwHVAQAAPP2y6bHEZ_sCAAAAAARZWg==)

**Additional context** 
May be related/dupe to #2065

**Comment by ichard26** [comment]
Hello!

That code issue now formats without error on master.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!
