### ISSUE TITLE
Inconsistent behavior between similar strings

### ISSUE THREAD

**Issue by Hoxbro** [psf/black#2134]
**Describe the bug** 
I have something similar to these line in my code:
```python
title_api1 = "https://example-webapi.example-api.com/api/title_detail?title_id={title_id}"
title_api2 = "https://example-webapi.example-api.com/api/title_detail?title_id={title_id}&example=test"

```
and when running them with black, I get:
``` python
title_api1 = (
    "https://example-webapi.example-api.com/api/title_detail?title_id={title_id}"
)
title_api2 = "https://example-webapi.example-api.com/api/title_detail?title_id={title_id}&example=test"
```

**Expected behavior** 
I would expect the output to be consistent between the two strings. 

**Does this bug also happen on master?** 
yes, I used the online formatter.

**Comment by ambv** [comment]
One of them is too long so it gets moved to another line to fit. The other one is too long and moving it to its own line wouldn't make it fit anyway so no reformatting is attempted. There's no way Black can be "consistent" about lines that are next to each other. It treats each one separately using the same rules.

**Comment by JelleZijlstra** [comment]
I believe the `--experimental-string-processing` flag fixes this.
