### ISSUE TITLE
fmt: skip for long line of context managers leads to INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by mkhl** [psf/black#2138]
Adding `# fmt: skip` after a long `with ... as ...:` line leads to black raising an internal error.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file `foo.py`:
    ```python
    name = "foo.py"


    def foo():
        with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:  # fmt: skip
            print(f1, f2, f3, f4, f5)
    ```
2. Run _Black_ on it with these arguments `black foo.py`
3. See error: `error: cannot format foo.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_lejlacgg.log`
4. The helpful diff (attached)

**Expected behavior** Black formats the source file, leaving the line marked to be skipped alone.

**Environment (please complete the following information):**

- Version: black, version 21.4b0
- OS and Python version: Linux, Python 3.9.4

**Does this bug also happen on master?** [Yes it does](https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEEAJFdAD2IimZxl1N_WmFm63wsQYxa3iKd5NgD9wTuCPA8tXPZto6Z99Hjctu-G04oaNFwP0prhun9D_WwMRE2qvt9XrGWUmhvMlrPsdHF8rb6YbTjYiezBhLlkOtY8bqbawGuKbY8MsSA1n6NE-6hT0_Pz-gdHZUSmcScrbgrszUMecOfLe-OfEh6y2WRdiiwisWNhecAAAAAjHfk5WJS8PcAAa0BhQIAADpttIKxxGf7AgAAAAAEWVo=)

**Additional context** Add any other context about the problem here.

**Comment by mkhl** [comment]
I'm failing to attach the helpful diff so here it is inline:
```diff
Mode(target_versions=set(), line_length=88, string_normalization=True, magic_trailing_comma=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,6 +1,12 @@
 name = "foo.py"
 
 
 def foo():
-    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:  # fmt: skip
+    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(
+        name
+    ) as f5:
+
         print(f1, f2, f3, f4, f5)
+
+
+# fmt: skip
--- first pass
+++ second pass
@@ -5,8 +5,6 @@
     with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(
         name
     ) as f5:
 
         print(f1, f2, f3, f4, f5)
-
-
-# fmt: skip
+  # fmt: skip
```

**Comment by polaum** [comment]
We would also appreciate this fix

**Comment by JelleZijlstra** [comment]
This no longer crashes but now it puts `# fmt: skip` on its own line, which isn't great.

```
 def foo():
-    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:  # fmt: skip
+    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(
+        name
+    ) as f5:
+
         print(f1, f2, f3, f4, f5)
+
+
+# fmt: skip
```
