### ISSUE TITLE
Black does not support "Assignment Expressions" ("the walrus operator") in the `assert` statements.

### ISSUE THREAD

**Issue by AIGeneratedUsername** [psf/black#2139]
**Describe the bug** 
Black does not support "Assignment Expressions" ("the walrus operator") in the `assert` statements.

**To Reproduce** 

1. Take this code:
`assert (foo := 42 + 42)`

2. Run _Black_ with or without any arguments
3. See error

> error: cannot format _local.py: INTERNAL ERROR: Black produced invalid code on pass 1: invalid syntax (<unknown>, line 1).

**Expected behavior** 

Black must support "Assignment Expressions" ("the walrus operator") in the `assert` statements.

**Environment (please complete the following information):**

- Version: 21.4b0
- OS and Python version: Linux, Python 3.8 and Linux, Python 3.9

**Does this bug also happen on master?** 

Yes.

**Comment by JelleZijlstra** [comment]
Looks like we remove the parentheses when we shouldn't. A PR would be welcome.

**Comment by ichard26** [comment]
I forgot to link the PR, manually closing.
