### ISSUE TITLE
fmt: off/on on different indentation levels leads to INTERNAL ERROR: Black produced invalid code on pass 1

### ISSUE THREAD

**Issue by mkhl** [psf/black#2140]
Placing several `fmt: off`/`fmt: on` comments, each around long `with ... as ...:` lines, leads to black raising  an internal error

**To Reproduce** Steps to reproduce the behavior:

1. Take this file `foo.py`
    ```
    name = "foo.py"


    def foo():
        # fmt: off
        with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:
            # fmt: on
            print(f1, f2, f3, f4, f5)


    def bar():
        # fmt: off
        with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:
            # fmt: on
            print(f1, f2, f3, f4, f5)
    ```
2. Run _Black_ on it with these arguments: `black foo.py`
3. See error: `error: cannot format foo.py: INTERNAL ERROR: Black produced invalid code on pass 1: invalid syntax (<unknown>, line 12). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /tmp/blk_3i4qdouv.log`

**Expected behavior** Black formats the source file, leaving the line marked to not be formatted alone.

**Environment (please complete the following information):**

- Version: black, version 21.4b0
- OS and Python version: Linux, Python 3.9.4

**Does this bug also happen on master?** [Yes it does](https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHUAJldAD2IimZxl1N_WmFm63wsQYxa3iKd5NgD9wTuCPA8tXPZto6Z99Hjctu-G02vQ66iazqXJ-pZayASz_zt2d6hMht-Jz3nSIdAJx8Lbu-jjCl2N3lDI4xfh7bbsLR1KxCmyuhwYrFT9mXzxip7MhJ4QfBbWxURZlPZnaqHmrP9cGhxLd6aOZp7upBQiGacF0GSuolpk9M0NbREAAAAAACaKx9iKoxo3QABtQHVAwAAWYj-p7HEZ_sCAAAAAARZWg==)

**Additional context** Add any other context about the problem here.

The helpful diff:
<details>
<pre>
  File "/home/mkhl/.cache/pypoetry/virtualenvs/api-FV8o_s3F-py3.9/lib/python3.9/site-packages/black/__init__.py", line 6508, in assert_equivalent
    dst_ast = parse_ast(dst)
  File "/home/mkhl/.cache/pypoetry/virtualenvs/api-FV8o_s3F-py3.9/lib/python3.9/site-packages/black/__init__.py", line 6409, in parse_ast
    return ast27.parse(src)
  File "/home/mkhl/.cache/pypoetry/virtualenvs/api-FV8o_s3F-py3.9/lib64/python3.9/site-packages/typed_ast/ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)
name = "foo.py"

def foo():
    # fmt: off
    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:
        # fmt: on
        print(f1, f2, f3, f4, f5)

    def bar():
        # fmt: off
    with open(name) as f1, open(name) as f2, open(name) as f3, open(name) as f4, open(name) as f5:
        # fmt: on
        print(f1, f2, f3, f4, f5)

**Comment by ambv** [comment]
Black doesn't like when you turn off and turn on formatting at different levels. We should fix this, in the mean time use `# fmt: skip` or turn off the entire block from formatting.

**Comment by ichard26** [comment]
See also #569
