### ISSUE TITLE
primer.json is not installed

### ISSUE THREAD

**Issue by hroncok** [psf/black#2153]
**Describe the bug** The black-primer tool uses primer.json on runtime, but the file is not installed.

**To Reproduce** Steps to reproduce the behavior:

```
[tmp]$ python -m venv venv
[tmp]$ . venv/bin/activate
(venv) [tmp]$ pip install black
...
Installing collected packages: toml, click, appdirs, mypy-extensions, pathspec, regex, black
Successfully installed appdirs-1.4.4 black-21.4b1 click-7.1.2 mypy-extensions-0.4.3 pathspec-0.8.1 regex-2021.4.4 toml-0.10.2
(venv) [tmp]$ which black-primer
~/tmp/venv/bin/black-primer
(venv) [tmp]$ black-primer
Usage: black-primer [OPTIONS]
Try 'black-primer -h' for help.

Error: Invalid value for '-c' / '--config': Path '/home/churchyard/tmp/venv/lib64/python3.9/site-packages/black_primer/primer.json' does not exist.
```

**Expected behavior** `site-packages/black_primer/primer.json` should be installed

**Environment (please complete the following information):**

- Version: at least 20.8b1 to 21.4b1 but possible any
- OS and Python version: Fedora Linux / Python 3.9.4 (but also happens on any other version)

**Does this bug also happen on master?** Yes

```
(venv) [tmp]$ SETUPTOOLS_SCM_PRETEND_VERSION=21.5 pip install -U https://github.com/psf/black/archive/refs/heads/master.zip
...
Successfully installed black-21.5
(venv) [tmp]$ black-primer
...

Error: Invalid value for '-c' / '--config': Path '/home/churchyard/tmp/venv/lib64/python3.9/site-packages/black_primer/primer.json' does not exist.
```

**Comment by hroncok** [comment]
Working on a fix

**Comment by ichard26** [comment]
A simple package_data mod should fix it:

https://github.com/psf/black/blob/1728bb441e6cc3ba5a5ce52ec62014bbfa435a82/setup.py#L67

Thanks for noticing!

**Comment by hroncok** [comment]
Yes, I have that ready, now going trough https://github.com/psf/black/blob/master/CONTRIBUTING.md

**Comment by hroncok** [comment]
Ready in https://github.com/psf/black/pull/2154

**Comment by cooperlees** [comment]
This is interesting. I didn't package the config, as I would expect anyone running it locally to want to run their own configs on their own projects. E.g. $ORG has 10 black repos, before bringing in a new version or as a check primer could check to see if everything is `black` compliant.

I can see the benefit of including this default config tho. So will accept the PR. Thanks!
