### ISSUE TITLE
Proposed modifications to the label system + plus more!

### ISSUE THREAD

**Issue by ichard26** [psf/black#2160]
Hey fellow maintainers of Black!

So since I've been promoted to a proper maintainer (thanks Łukasz!) I can now edit the label system we got :) Over time I've wanted more from the labels we got right now. What follows below are the changes I want to make, unless explicitly noted, they are all independent (so feel free to reject one ideas while approving the rest, or whatever) (also reasonable bikeshedding of any proposed names is fine by me).

**Section A: Edits to existing labels:**
1. Delete `hacktoberfest-accepted` - we don't need it anymore and we can always readd it when we need it
2. Repurpose `question` into `awaiting response` - I honestly have no idea what the `question` label is used for on first sight and reading the description doesn't help much. My guess is that it's for when the issue is waiting for more information from OP; let's make that clear.
3. Rename `lib2to3` to `blib2to3`

**Section B: New labels:**
1. `accepted` - used to mark design (or even feature requests / documentation) issues that can be implemented in a PR
2. `maintenance` - used to mark issues related to the maintenance of this project so topics like CI, testing, policy changes, or heck even this very issue!
3. `needs repro` - bug reports that need a reproduction (either because none was provided or the bug is old)

**Section C: let's change the whole world changes:** (we could implement them or not, I don't feel strongly)
1. Add prefixes to our labels? Our labels typically come in groups and it could be beneficial to explicitly organize them. Here's the groups I can think of off my head:
   1. `T:` (`type: ` could work too) - type: what is the issue about in a super duper general sense (e.g. `T: bug`, `T: documentation`, ... and so forth)
   2. `F:` - formatting: what area of formatting is the issue concerned with (e.g. `F: trailing commas`)
   3. `C:`- non-formatting categories (e.g. `C: performance` or `C: installation`) 
   4. `R:` - response: how was the issue resolved? (e.g. `R: duplicate`, `R: not a bug`) 
   5. `S:` - status: what state is the issue in right now? (e.g. `S: needs repro`)

Although it should be noted that in general I'll be editing the label descriptions without feedback (I've already done as of writing this!). I plan to edit even more to help clarify what they are used for.

What do y'all think?

**Comment by cooperlees** [comment]
All sounds good to me. I don't disagree with any of it.

**Comment by ichard26** [comment]
Since I've received positive feedback from two maintainers, I'll be implementing Section A and probably Section B too soon (I really want to start using `maintenance` labels). I'll leave Section C unimplemented just in case some one doesn't like it but they haven't been able to respond yet.

In terms of when I'll implement Section C, maybe in a few days? I don't know, I'm in no rush to implement them and I'd rather make sure everyone is happy.

**Comment by ichard26** [comment]
Okay, so I've implemented Section A and B. One thing to note is that I actually renamed `question` to `user support` since the issues that were labelled with it were actually question type issues (go figure...). The issues seem to be mostly split between design issues worded like a question and user support issues (e.g. how do you use Black with X editor?). I still added a separate `awaiting response` label though.

**Comment by ichard26** [comment]
Cool, I've implemented section C as well. If anyone doesn't like it, please speak up and I can revert. I've also added a `C: file collection` label for stuff like caching, .gitignore, exclusion & inclusion configuration, etc.
