### ISSUE TITLE
Unable to include empty docstring

### ISSUE THREAD

**Issue by sbliven** [psf/black#2168]
Empty docstrings are used by sphinx to indicate methods that should not be included in the documentation. However, as of 21.4b0 black reformats empty docstrings to contain a space.

**To Reproduce**:
Source:
```
def foo():
    """"""
    ...
```

gets reformatted to

```
def foo():
    """ """
    ...
```

**Expected behavior** I'm generally supportive of the style changes introduced in #1740. However, in this case black is changing the code in a meaningful way. I suggest that empty docstrings be ignored as a special case. I am agnostic on whether the empty docstring should be spelled `""` or `""""""`.

**Environment:**

- Version: 21.4b2
- OS and Python version: debian 10/Python 3.7.10

**Does this bug also happen on master?** Yes

**Comment by JelleZijlstra** [comment]
See #2150 for some similar previous discussion. I'm supportive of leaving empty docstrings alone to support this use case.

**Comment by sbliven** [comment]
> See #2150 for some similar previous discussion. I'm supportive of leaving empty docstrings alone to support this use case.

If #2150 resolves in favor of reducing AST modifications that would certainly fix this bug. However a special case allowing empty docstrings would be sufficient for my use case.

**Comment by sethmlarson** [comment]
This is impacting the urllib3 documentation, we use an empty docstring to avoid having subclass methods from Python's `http.client.HTTPConnection` that aren't relevant to our users show up in our documentation generated via autodoc.
