### ISSUE TITLE
Normalize raw f-strings prefix

### ISSUE THREAD

**Issue by jamesmyatt** [psf/black#2171]
**Is your feature request related to a problem? Please describe.**

Black should normalize the prefix used for raw f-strings (https://www.python.org/dev/peps/pep-0498/#raw-f-strings). Both `rf` and `fr` work, but one should be preferred.

Currently, the following code is not changed:

```
    f = rf"hello {world}"
    f = fr"hello {world}"
```

**Describe the solution you'd like**

Pick one and normalize. I don't really care which. `rf` matches the name "raw f-string", but `fr` matches the example in PEP-498 and Jupyterlab syntax highlighting seems to prefer it.

**Describe alternatives you've considered**

Doing nothing leaves open the opportunity for inconsistency and disagreement.

**Additional context**

None

**Comment by JelleZijlstra** [comment]
Agree that we should standardize here. This also affects raw bytestrings: `rb'x'` and `br'x'` are both valid.

**Comment by ichard26** [comment]
Seconded. I weakly prefer `rb"x"` and `fr"x"` visually since they are recognizable pairs to me (rb is a Ruby file extension and fr is a code for French which I can speak some of). But going with the general standard and what tools prefer is probably better.

**Comment by cooperlees** [comment]
> @cooperlees you mean `br`? :D
> 
> ```python
> >>> bf"foo"
>   File "<stdin>", line 1
>     bf"foo"
>       ^
> SyntaxError: invalid syntax
> >>> 
> ```

Sure ...

**Comment by felix-hilden** [comment]
While having a simple rule is elegant, I think matching spoken word is important like James pointed out. Just to provide one more perspective, I'd prefer:

- `rf` - raw f-string
- `rb` - raw binary string

To be fair, "binary" could be thought of as an adjective too. But "raw binary" seems more fitting, since "binary" feels like the primary attribute to me.

**Comment by jamesmyatt** [comment]
I don't think the alphabetical order convention is a good one, otherwise you might end up with inconsistent placing e.g. `br`, `fr` and `rx` (under the hypothetical scenario where `x` and `rx` are a valid prefixes). I'd prefer either "r-first"---as in "raw f-string/byte string"---or "r-last"---as in the "f" or "b" are the most important parts of the prefix or possibly chain-rule i.e. the "raw" processing is applied before the "format" processing; I don't know how the parser actually handles it.

To me, "r-first"---as in "raw f-string/byte string"---is the clearest justification.

**Comment by Zac-HD** [comment]
Sorting will also have problems with [the capital-R prefix](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#r-strings-and-r-strings), `Rf""`, `Rb""`, `br""`, `fr""`.  I'd prefer "r-last" (`fR""`, `bR""`) but would be happy with any simple and consistent rule.

**Comment by jamesmyatt** [comment]
@Zac-HD I didn't know about the R-strings. Thanks for that :+1:. Seems odd to have the more common syntax (i.e. lower case r) be for the special case of regular expressions, especially when `br""` doesn't make sense ... I think, but I digress.

I think I agree that `fR""` looks better than `Rf""`. In fact, I'm also moving towards a justification that since the "f" or "b" is more important, it should go first.

**Comment by felix-hilden** [comment]
To find some common ground first, I think it would be reasonable to propose that no matter which "r/R", the order stays the same. Meaning no mixing `rf` with `fR` and vice versa. And I think allowing other capital letters is a no-go as well. So it seems that the suggestions have converged to:

- `r` first, as in spoken word: `rb"str", rf"str", Rb"str", Rf"str"`
- `r` last, as the common attribute applicable to both `b` and `f`: `br"str", fr"str", bR"str", fR"str"`

Personally I still feel like matching spoken word is more important, and I'm not bothered by the capital "R" being first. That being said arguments can be made both ways. Would the maintainers like to decide, or would we vote, or have a PR race? 😄

**Comment by JelleZijlstra** [comment]
We just need to make the call, one way or the other. Maybe ask for more opinions on Discord and then take a majority vote among the maintainers.

**Comment by vcokltfre** [comment]
I've voted on the poll on Discord, but to explain why I voted for things like `fr` I think it makes more sense for them to be in alphabetical order if they're going to be standardised, as other things' order also follow that pattern

**Comment by felix-hilden** [comment]
After 8 hours the poll is 8-5 for `rf`. Could the maintainers only vote here thumbs up for `r` first and down for `r` last?

**Comment by felix-hilden** [comment]
I opened the PR to fix this. It seems that in Python 2 the order is not arbitrary and two combinations: `ur` and `br` are the only valid ones. They go against `r` first.

Since `ur` is invalid in Python 3, I'm inclined to introduce a special case for Python 2 and let the rule be. Another option would be to just use `r` last and call it a day. Thoughts?

**Comment by jamesmyatt** [comment]
Given that no-one had strong feelings about which way round it should be, maybe it's better to switch to r-last for consistency with Python 2.

**Comment by felix-hilden** [comment]
Update: since we're dropping Python 2 now, I think I'll go with our original option of "r" first.
