### ISSUE TITLE
SQL String Causing Invalid Syntax Error

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [psf/black#2177]
**Describe the bug** A clear and concise description of what the bug is.

SQL string causing invalid syntax error

**To Reproduce** Steps to reproduce the behavior:

Using SQLAlchemy to construct a query I have the following line

```python
query = query.filter(field.ilike(f"%{v}%"))
```

Which leads to the following error

```
  File "<unknown>", line 311
    query = query.filter(field.ilike(f"%{v}%"))
                                            ^
SyntaxError: invalid syntax
```
I assume that Black is thinking that the % is an old style format string?

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: 21.4b2
- OS and Python version: Linux Python 3.6.9

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.

Using the online formatter I did not see any complaints.

**Comment by JelleZijlstra** [comment]
You may be running into the Black behavior where it tries to parse code as Python 2 if parsing as Python 3 fails. I couldn't reproduce this error locally; could you give a full self-contained example?

**Comment by Anti-Distinctlyminty** [comment]
I tracked it down to a docstring in some old commented out code that was several hundred lines down. I manage to whittle the whole thing down to this 

```python

class RenderOutputsResource():
    def get(self):
        s = f'%{v}%'

# class Blah():
#     def blob(self):
#         """
#         type: integer
#         """
```

The culprit is the `#         type: integer` line.

**Comment by JelleZijlstra** [comment]
I can't reproduce a crash on that example. Are you using non-standard options? Does it still crash with the latest release?

**Comment by Anti-Distinctlyminty** [comment]
No non-standard options. But I just tested again with a fresh Black install, and it didn't cause any issues. 
I'll re-open if I find out more.
