### ISSUE TITLE
Remove empty lines between a function's doc string and body

### ISSUE THREAD

**Issue by ggoodvin-fincad** [psf/black#2189]
**Black v21.4b2**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADfAHRdAD2IimZxl1N_WlbvK5V_r8p8RWVQhH4RKYRsWyDTv1j9Kefe6CYARnBIR_HGlKYy_sdd49QShmDeaPR-ut4FKtHTrfylJn0T5qbgKnjEqaEEve2nBGS-1DnQr48WuMuK84yebBhTuDIx-kgW4U0Lm17yK3sAAP9aT0HQpcW3AAGQAeABAAAhwO40scRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
def some_func():
    """Doc string."""
    
    return 1.0
    
def some_other_func():
    """Doc string."""
    return 2.0


```

## Output

```python
def some_func():
    """Doc string."""

    return 1.0


def some_other_func():
    """Doc string."""
    return 2.0

```

## Expected

```python
def some_func():
    """Doc string."""
    return 1.0


def some_other_func():
    """Doc string."""
    return 2.0

```

(Or insert a single empty line in both cases, no strong preference, just after consistency).

**Comment by felix-hilden** [comment]
If I had to choose, it would be removed. Multi-line docstrings in particular have a good visual distinction with the first line already:

```python
def foo():
    """
    Docstring.

    On multiple lines explaining the function
    that needs documentation.
    """
    return 1 + 1 == 2
```

But I don't feel strongly about one-line docs. Looking at my own code I tend to write without the empty line, but I can imagine others might want it for separation. What do the maintainers think?

**Comment by xrisk** [comment]
Perhaps look at what some of the repos that primer checks does (or other authoritative sources)? There should be some strong precedent for enforcing one style over another I think.

**Comment by felix-hilden** [comment]
Looks like this is essentially the same as #2370, and since there's been more discussion over there I'll close this one as a duplicate.
