### ISSUE TITLE
Regression: Black tries to reformat venv files while it was not doing this before

### ISSUE THREAD

**Issue by cgaunet** [psf/black#2219]
It seems that black naturally excludes venv files from its check.
However, since 21.5b1 was released, this behiavour has stopped working and now black would reformat a huge amount of libraries code.
I'm sure black would improve these libraries code formatting, but I'm not the one dealing with this :)

**To Reproduce** Steps to reproduce the behavior:

1. Install the latest version of black in a venv that contains other libraries
2. Run venv/bin/black . --check
3. Check the output, it would reformat venv libraries files

**Expected behavior**
I'd like black to default exclude venv files as it was doing in 21.4 and prior versions

**Environment (please complete the following information):**

- Version: 21.5b1
- OS and Python version: Linux/Python 3.9

**Does this bug also happen on main?** To answer this, you have two options:
I think yes but haven't tried

**Comment by JelleZijlstra** [comment]
This sounds like a consequence of #2170.

**Comment by cgaunet** [comment]
Unfortunately, I don't use --exclude option for my command.
I have this gitignore:
```bash
....
# virtualenv
venv/
ENV/
....
```

And the command launched with the output:
```bash
➜  api git:(8415-set-movies-visa-as-isbn-to-prevent-duplication) ✗ venv/bin/black . --check
would reformat venv/lib/python3.9/site-packages/PIL/BlpImagePlugin.py
would reformat venv/lib/python3.9/site-packages/PIL/IptcImagePlugin.py
would reformat venv/lib/python3.9/site-packages/PIL/ImageColor.py
would reformat venv/lib/python3.9/site-packages/PIL/BmpImagePlugin.py
would reformat venv/lib/python3.9/site-packages/PIL/Jpeg2KImagePlugin.py
would reformat venv/lib/python3.9/site-packages/PIL/ImageDraw.py
.........

Oh no! 💥 💔 💥
99 files would be reformatted, 1219 files would be left unchanged, 8 files would fail to reformat.
```

**Comment by cooperlees** [comment]
I doubt this since it use to work, but does your repo have a `pyproject.toml` with any black exclude settings? Should they possibly be `extend-exclude`?

Is your repo public that's exhibiting these problems? If so, can you please link.

**Comment by cgaunet** [comment]
@cooperlees, ok sorry for this issue, it comes from our `pyproject.toml` indeed.

Should we close this issue ? :)

**Comment by cooperlees** [comment]
Maybe so, but I wonder if we should make a FAQ / series of steps to help people debug for "something isn't getting excluded" as follow up to this ... A PR would be accepted by me for sure ...

**Comment by ichard26** [comment]
@cooperlees haha see #2176

**Comment by cooperlees** [comment]
In that case ... closing :D
