### ISSUE TITLE
black preserves python2-style prints

### ISSUE THREAD

**Issue by fpdotmonkey** [psf/black#2230]
**Describe the style change**

Given that python2 is now fully dead and its prints lead to a SyntaxError in python3, black should, out of the box, reformat `print` to use the python3 style with parenthesis.  Maybe if `--target-version` is `py27` or less, then the python2-style prints should be preserved.

**Examples in the current _Black_ style**

```python
print "I am the very model of a modern major general"
print "%s sells %s by the %s shore" % (pronoun, commodity, water_body)

# output

print "I am the very model of a modern major general"
print "%s sells %s by the %s shore" % (pronoun, commodity, water_body)
```

**Desired style**

```python
print "I am the very model of a modern major general"
print "%s sells %s by the %s shore" % (pronoun, commodity, water_body)

# output

print("I am the very model of a modern major general")
print("%s sells %s by the %s shore" % (pronoun, commodity, water_body))
```

**Comment by JelleZijlstra** [comment]
This would be changing the syntax, which Black isn't in the business of doing. You can use tools like 2to3 to convert from Python 2 to Python 3 syntax.
