### ISSUE TITLE
Support Python 3.10 pattern matching syntax

### ISSUE THREAD

**Issue by tirkarthi** [psf/black#2242]
**Is your feature request related to a problem? Please describe.**

Python 3.10 has added support for pattern matching. It will be good to support it. https://www.python.org/dev/peps/pep-0622/

**Describe the solution you'd like** .

**Describe alternatives you've considered** 

**Reproducer**

```python
from dataclasses import dataclass

@dataclass
class Person:
    name: str

person = Person("Kate")

match person:
    case Person(name):
        print(f"Found {name}")
    case _:
        print("Not found")
```

```
 black /tmp/dataclass_match.py
error: cannot format /tmp/dataclass_match.py: Cannot parse: 10:6: match person:
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Additional context** Add any other context or screenshots about the feature request
here.

**Comment by brandtbucher** [comment]
Note that the syntax has changed slightly since PEP 622 was superseded. [PEP 634](https://www.python.org/dev/peps/pep-0634/) (the accepted PEP) has the updated grammar.

I'm happy to help review or answer any questions on this once the work begins. I'm definitely looking forward to this support!

**Comment by JelleZijlstra** [comment]
This will probably require #2318.

**Comment by LordOfPolls** [comment]
May I ask if there's any news in regards to this?

**Comment by graingert** [comment]
and here https://github.com/Instagram/LibCST/issues/285#issuecomment-894699168

**Comment by LordOfPolls** [comment]
So, re the above. Does this mean black will be getting support for the new syntax shortly? Or are we to switch to using one of the forks?

**Comment by JelleZijlstra** [comment]
What I'd like to see is that we land support based on @isidentical's patch, but somebody needs to step up to actually make a PR and get it landed. I might work on that if I have time, but I can't give any guarantees.

**Comment by isidentical** [comment]
I would love to contribute @JelleZijlstra! If the lack of full support and other issues I have mentioned is considered and agreed upon I can convert my PR to a patch. And iterate over it for better support.

**Comment by JelleZijlstra** [comment]
That would be great! I'd be OK with landing partial support first and iterating on the rest later.

**Comment by isidentical** [comment]
Cool, will send a patch within this week!

**Comment by JelleZijlstra** [comment]
I am going to close this because thanks to @isidentical's awesome work we shipped 21.11b1 with basic match support. There may be some cases that don't work, but we should open new issues for those as we run into them.

**Comment by AlozoR** [comment]
Got the last version and it still fails to parse the match keyword on my end, with the exact same example as the OP, any ideas?

**Comment by JelleZijlstra** [comment]
@AlozoR make sure you pass `--target-version py310` explicitly. We don't use the match grammar by default.

**Comment by AlozoR** [comment]
Just saw that! Thanks!

**Comment by thesammy2010** [comment]
> @AlozoR make sure you pass `--target-version py310` explicitly. We don't use the match grammar by default.

this still throws 
```
Error: Invalid value for '-t' / '--target-version': invalid choice: py310. (choose from py27, py33, py34, py35, py36, py37, py38)
```

when running on `black==21.11b1` for me

**Comment by g-berthiaume** [comment]
FYI: 
If you're using vscode, you can add the following to your `settings.json`
```json
"python.formatting.blackArgs": [
    "--target-version",
    "py310"
],
```

**Comment by AdriandLiu** [comment]
FYI:
If you're using Atom, you can follow this step to point python-black to find the right `black`:
Go to .atom -> packages -> python-black -> lib -> python-black.js -> binPath -> default, change it to the path get from `which black`

**Comment by rgant** [comment]
With the online formatter match-case doesn't work unless you turn on "skip temporary sanity checks" even when targeting py3.10.

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AU_As5dAD2IimZxl1N_WlkPinBFoXIfdFTaTVkGVeHShArYj9yPlDvwBA7LhGo8BvRQqDilPtgsfdKl-ha7EFp0Ma6lY_06IceKiVsJ3BpoICJM9wU1VJLD7l3qd5xTmo78LqThf9uibGWcWCD16LBOn0JK8rhhx_Gf2ClySDJtvm7zQJ1Z-Ipmv9D7I_zhjztfi2UTVsJp7917XToHBm2EoNZqyE8homtGskFIiif5EZthHQvvOj8S2gJx8_t_UpWp1ScpIsD_Xq83LX-B956I_EBIeNoGwZZPFC5zAIoMeiaC1jU-sdOHVucLJM_x-jkzMvK8Utdfvp9MMvKyTfb_BZoe0-FAc2ZVlXEpwYgJVAGdCXv3lQT4bpTXyBwDrDVrUeJDivSSwOvT8tlnuMrXoD1Sk2NZB5SHyNmZsfyAEqLALbUnhkX8hbt5U2yNQRDf1LQhuUIOii6k6H9wnDNRnBiQHUfzKfW1CLiThnuVFjlCxQhJ60u67n3EK38XxHkQdOocJXpBNO51E4-f9z2hj0EDTu_ScuqOiC9cI8qJ4grSZIOnnQLv9WPvmCzx5zib3JacesIxMVvZNQiljq_gL7udm1yeXQjENOrBWbfBEkv1P4izWeAysoJgZUhtZFwKFdoCGt2TXe3xQ-wVZFS5KoMPhGFDZGPKzpK15caQOnWobOHLKaL8eFA-qI44qZrMQ7sSLn04bYeenNR2Vxz7hvK0lJhkgKrpVfUnZrtF-e-ubeeUCThWus4jZbKlFBe2Kroz90Elij_UaYd3YKuJu25o9LadNF0XlRH8pq_gjACDJK1uhpLOtB_wDfoOiJ0KTXLSgtUwAGWTSmhvO9zEP-9EzdJB9eHeXBR07v8NkRwgzuz-UFdvthBsX-ok_-fLFLdnIv0v-La2xLaXEJU2pO9UpwgQUalhX6pQSEs0hVUqfz9HUY8f8bnlu00yzNHohgAAAAAk9gpxkIeipgAB6gXACgAAmQiwx7HEZ_sCAAAAAARZWg==

**Comment by JelleZijlstra** [comment]
We do not control the Black Playground. Please report issues with it to https://github.com/jpadilla/black-playground. (Most likely it's running Black under a version <3.10 on the backend.)

**Comment by harmbuisman** [comment]
> FYI: If you're using vscode, you can add the following to your `settings.json`
> 
> ```json
> "python.formatting.blackArgs": [
>     "--target-version",
>     "py310"
> ],
> ```

Thanks, this also helps in getting the black commit hook to work, e.g. in the pre-commit-config.yaml:
```
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: ["--target-version", "py310"]

```
