### ISSUE TITLE
Formatting of conditional expressions in named function arguments

### ISSUE THREAD

**Issue by JEphron** [psf/black#2248]
When formatting conditional expressions in function calls with named arguments, Black's formatting varies significantly depending on whether the expression is surrounded by parenthesis. 

### Exhibit A:
Black considers this correctly formatted
```py
aaa = my_function(
    foo="test, this is a sample value",
    bar=some_long_value_name_foo_bar_baz
    if some_boolean_variable
    else some_fallback_value_foo_bar_baz,
    baz="hello, this is a another value",
)
```

### Exhibit B
When fed the following block as input:
```py
aaa = my_function(
    foo="hello, this is a sample value",
    bar=(some_long_value_name_foo_bar_baz
    if some_boolean_variable
    else some_fallback_value_foo_bar_baz),
    baz="hello, this is a sample value",
)
```

Black formats it with a much nicer indentation 
```py
aaa = my_function(
    foo="hello, this is a sample value",
    bar=(
        some_long_value_name_foo_bar_baz
        if some_boolean_variable
        else some_fallback_value_foo_bar_baz
    ),
    baz="hello, this is a sample value",
)

```

I consider the second output far more readable. In exhibit A the `if` expression lies on the same indent as the kwargs, making it hard to tell what's going on. In the second, it's quite clear that some computation is spanning those three lines. 

I think ideally Black would never produce Exhibit A, rather it would insert the parenthesis in order to indent the conditional expression.

In keeping with the opinionated style, we should pick one or the other, but probably not allow both. Even if Black decided to strip parenthesis and produce exhibit A all of the time, it'd be preferable to the current ambiguity.

**Comment by TylerYep** [comment]
+1 that Exhibit B's end result is much easier to read

**Comment by MeGaGiGaGon** [comment]
This has been fixed on stable, probably as of the 2024 release. [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFtAMxdAD2IimZxl1N_WlRp5AcAUJ2aCYYpN2q6eaj0KDqjGeIeZcqICtx2pSIQu94LPMYHHGrGvhuRt98yM2SlAbYbEL-x_i_LcNKIdTIDSgnmJ3iAQLNEfsVZ9thDpB6SZeou-huD0lr-CTPVppNl8TzR8so37Zl4WUK7A39YxbQ2kTC0qdBXxxTphQE7Ga0pxQGD_zMo29oYZyFqHVCXaR_IzPk34MB_XK0pP5SpjCwjtpy73s4YS0J4TxzvHh6DyaxucUAC74oqO3Ig4EDCJgDOiwLJIv_hWgAB6AHuAgAA54YGMbHEZ_sCAAAAAARZWg==)

**Comment by JelleZijlstra** [comment]
Thanks!
