### ISSUE TITLE
Move Binary building CI to latest python (3.9)

### ISSUE THREAD

**Issue by cooperlees** [psf/black#2252]
Today we hard set python version to 3.7 for building our static binaries we push to GitHub. Lets move this to 3.9

https://github.com/psf/black/blob/main/.github/workflows/upload_binary.yml

- Bonus Points: Just don't set the version and we automatically move as new version of Python come out.

**Comment by felix-hilden** [comment]
I think this can be closed now, my bad for not automating it in the PR itself.

**Comment by ichard26** [comment]
And I totally forget to close this issue when I originally noticed this was still opened :laughing:
