### ISSUE TITLE
fmt:skip fails with internal error

### ISSUE THREAD

**Issue by memeplex** [psf/black#2254]
**Describe the bug** A clear and concise description of what the bug is.

`# fmt:skip` fails with internal error message.

**To Reproduce** Steps to reproduce the behavior:

1. Open the link to vercel.app below
2. See the log at the right hand side

**Expected behavior** A clear and concise description of what you expected to happen.

Not sure, that it doesn't abort with an error at the bare minimum, I was just giving a try to the new `# fmt: skip` directive, my intention was to avoid a blank line before a local class definition, maybe it's not supposed to work like that, it's not clear to me, but that's one thing and another is:

```
error: cannot format /Users/carlos/Repositories/Jampp/predex-docs/dox.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/st/d_bcbs_j6033r_g_dfztgmxc0000gn/T/blk_7soxut5i.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Environment (please complete the following information):**

I'm not sure this is relevant because I'm reproducing the issue in vercel.app, but here it is:

- Version: 21.5b0
- OS and Python version: 3.8.5

**Does this bug also happen on main?** To answer this, you have two options:

I hope this resource is persistent enough, because of the large URL I wasn't allowed to post directly from vercel.app:

[https://black.vercel.app/?version=main&state=...](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4BclB-NdAD2IimZxl1N_WlwxRhR7MSgEofbjIYetoq3c39_bAan9-vGj_muCNt2IJmCUcYYdGvv9c_kpjBLXC11IPxpVmC1TU3iRQH1FHIfWj6Nv8jykZL-LhWVrGEp1zvlct6FWYbt9IXnO8b_7yCKraClJFzvWxJ5ByHCa09njhdo8DtOdEEmsuoHZ79buhAxvjhAJp5N6XRrQgveaamNijV-z8fG-oQTJ85ccbjBNNm86fk8p564RqHP2MNXpnE2lO6RV6BQhohubJeaHiL4rgbOQvebFszNr2GTca3_obrr6KVP0VDDmzKOlBqmeANytHUtXGUOR-udZkuMCqt8rEbpzs2BnbYmD1ucBRj7RwwUe8Rpdssazljhx19cnDic82Uz6eWRV-mIuT86r66NnSgsNZu7VqAN9s0HIgfeNypX1HUPQvMIgzu1KTtH42XRMmNFUMeIJU64lbQS341-d-UdaU8g0V4uRD_q_oQR1UtXJUPNSo9kI1ALhy9GCmtZGksj3SIIYjsOLkvToN5jDgG1Q905BIzA3LQOG2Pe0SuEzOkbVSoEnBJGPE5JLri7Y_6cXBra2WbZd9AY9wIDkr5R3mhKoftcqa3zDLmyculGFZ22UyCIN89Cg0-FzC2Ilsof934JcDoCxz2cgEZikoBz0oRTizqm_90uoX5CTNphAP1jqy1avz4CF9QzBUVc1FRWphPIddZN468JGVQaFQk9lTLm8LXCyK0Tj4ZrRII3VnzQkUd_phO-nquq3HuWjhVsv34uOzwKQ_tcF_x62Sc8x_OG0LLfzsUgoSgul1bnpm5ZnnEGXAe4oFLSPbBBgQXD2NGL9YJwke1j3-gyRGCsinkUCaXeBZd0QHANVtnmRlWjc9Kv7XMeZ3EsjTV2s-_FcCMRcvq3Fss8G31PgM6-O7DHMn55jO0Efx3YaGS6xoQCE-zVbidb_cZ_EniXH_p_5dUiTkRQeZo1BHYogTvMlkkVLCkPCwFdFyZ3YsAIo15__e09Wag8UX6VZ0cieHMWN8NFicux4S1zWkd0GPi0YkQLtIKz3n2-P5X_JTxnYZIqw2nsvb3d8vzozqSREOIeY6rgsFfMMLe83nLzIZNNQK1ezDf288XXit07EA5wEGr-dxiU1ARS15EfRAKAqcj9rCaW5uCSlBIW9kF07cw3Z3OjX0aH1mVTgP4JY6AoABYmVrbmdJdgSU1wmkbGcPdZtt9LSDPTRglMOqcheFdnqCYEi1OdS6ZwRPxTyKjdTYnslxHy6QmVZ_Iu-Kzpmqlai0yrv3VR4VAsVPOEBrydBUA-ie5OEk9dJx6V2iqrDBFkiR-FLBtQkSMkSG-Qbf0zHXLrw4qB2JOcEJxQZPLd15__RYfStxctShZyRwOQG01WkNwpYfNziC0W0zSDWwuIcXf3EXoAo02uwyVoV8uTvFp3C1Ow9Q9UPG0nrV-GF36tgLhRcrU0xF4O2SjDszJNUjirfuOet4EFIm_RYONYB-9QWWW9vQ5H7k8C4x-zdIFPL5e0BQIz7yVPXCm6K8-jmI5ia432q8rmmWTASTbhdrP30tFRRp9TSyCLYB5yasMBwM2s55hwgnIAXJmWwggk4gP_MAKZNw2GTvhyr2wTs3luxUefAPREFuAS_wXjeFCtktkif79upTOY2zXLqoMO4VUGjQdZNNFr0ePy8-gyBg4S7XCeRbb7RP6BumejzHyivVNfHut2eBxoxJUHVSOskrGCL8o2-k_j12IpiKzmFmD3NDSAOhcduRxJMxQVzTkUJFfkKg3px4sQtVBFRjbVzq-8BsDvX-nN4Vjl2E6u2corekvbzL_5e92_ysMyVJ39t9G1LViYmh3HXp6qx3t_Eo8qMtUB4DTF_9VoBlpXHlIJs-Z4Dw9NeEx7Dl54lyDvTufH8Qo4vxFqfQJBo2lsTyZUGooQKy5aJwGKG-jYLon4c71freJO6dT8WKNpcltC5jYHKlBqRu51CpZdcMkEdSpE-5S42xpKT69SvexH4u_gtE4WPuQRGfRnszoCnB8PVq4PPzekmzQ_6GKZHzvKUrbEZ3BmUDARX1jWSaiMftfy8UO_jBp4NUzLlqewWevFy_1KXZu664nKSr_HXePo-LuEKEVTA3UP_95X29sxUYzxB7PD-LuExaTRWSRqjR073y9kEYGlOMkLMRwwD4eiAwxC4qltoN5Vuh_9oHp8m8OgHGINrQosR195DjUghoITj_yJxAcL78rOtHX-AmzA3g3ePF4DE3yuvwJ9DAs9fSo55ftYCIjKDh9S7O-kgnotnbm8NkuBrsj1XkDqSRrPbGU_EjiIKQAwnVjPQs7CBHVzpuSt4-y2a3dwe6hgKfSUC3RsQzSaEc_Y5EgdKk8OXQ9mJZE6_R2nMlilQIRxzzOdDqT1tKFZKgqBhmi-OCVh8FIEMcHf6pyDc4bq6VLyW6fRGbJDIFPEu69l8axZp0DMCONeKhu_vslauv9jXKBdCpJgSg0UMmASWu4O8LJBioFl3wDRAA6R4JQlu76xBVcf_1N6K58XEmN6h8uLqvshZkkz2CWogvZmlH2rlf5jp-oaMAiC5n-pJd-dp4QqsbSr8deAbLyu0TteCD7aXESyuGDwQ_5SmotOkuBFSO2PGOsEHgXQ2YOThbGoFKzBt6s3VFu6LAKhmJJl0bIos5egIln5ncoRt50NShaMmwqaSbEyqYgAAggVgnGv9IpsAAf8Ppi4AAPPFEv-xxGf7AgAAAAAEWVo=)

Removing `# fmt: skip` in line 42 fixes the issue.

**Comment by enzet** [comment]
I have the same problem with Black 21.4b2, Python 3.9.1.  There is a simplified example to reproduce:

```python
class A:
    def f(self):
        for line in range(10):
            if True:
                pass  # fmt: skip
```

Removing any line fixes the problem.

**Comment by memeplex** [comment]
Thanks!
