### ISSUE TITLE
Support click 8.*

### ISSUE THREAD

**Issue by kasium** [psf/black#2255]
Recently click 8 was released. It would be nice, if black would support click 8 so that users can use it, too.
I understand, that the click dependency is needed for blackd, but for the day-to-day user, is this really needed?

Thanks a lot!

**Comment by cooperlees** [comment]
Hi,

Can you please give an example as to how it does not work? Our piplock is at 8.0.0 and my pip installs seem to be working with >= 8.0.0.

What’s your error? This will help us developers a lot.

As for needing it, yes, you do, all our CLI parsing is done by it. For example: https://github.com/psf/black/blob/main/src/black/__init__.py#L30

**Comment by kasium** [comment]
Hi,
you are right. Pip just showed a weird output because another dependency required only click 7. Thanks for the support.
