### ISSUE TITLE
Add optional extra uvloop install

### ISSUE THREAD

**Issue by cooperlees** [psf/black#2257]
Lets offer support for using [uvloop](https://github.com/MagicStack/uvloop) optionally via a extra install and `try/except` import + loop policy set.

- If we can import it, use and set it as the loop
  - Naturally this will only work on POSIX OS's (e.g. there is now windows uvloop)

**Comment by johnthagen** [comment]
Is this different than using `uvicorn[standard]` which also uses `uvloop`? Curious why a user should pick one over the other.

**Comment by McSinyx** [comment]
> there is now windows uvloop

I think this was a typo, as at the time of typing uvloop has yet to support Windows.  Should there be a `platform_system` marker so that users won't accidentally cause an installation error?
