### ISSUE TITLE
Black does not honor pylint disabling comments

### ISSUE THREAD

**Issue by apkrymov** [psf/black#2261]
After applying the Black code style to existing code I receive many Pylint errors on lines where was a Pylint disabling comment (http://pylint.pycqa.org/en/latest/user_guide/message-control.html) 
This is caused by Black does not honour the place where the comment was located

**Comment by ichard26** [comment]
Hi @apkrymov,

Thank you for submitting a bug report. While sanely handling comments when moving the code they are attached to is hard and annoying, we in general try to make it at least not behaviour influencing. The thing is that we'll need a piece of code where the comment handling isn't ideal. So could you share your code that had its pylint comments dangerously moved?

Thank you!

**Comment by ichard26** [comment]
We can't really make the comment placement preservation logic much better if we don't even have any test cases to try it on. Due to this + the lack of response in a few months.. I'll be closing this issue, I know this is disappointing but this isn't actionable as it stands. Thank you for the report tho.

**Comment by BotchJet-Pony** [comment]
Can you elaborate more on test case?

**Comment by ichard26** [comment]
I meant some code I could test black against to check its behaviour and if it meets my expectations. It's sorta like a proper test case with unittest for example, just manual and specific to black.

**Comment by BotchJet-Pony** [comment]
I can provide one today.
