### ISSUE TITLE
Multiline Context Manager 'with/as' parsing error

### ISSUE THREAD

**Issue by jacobian91** [psf/black#2264]
**Describe the bug**
Black reports a parsing error when using multiline context managers using the 'with/as' pattern.

**To Reproduce**
Run the below code for the parsing issue. Then remove `as x` `as y` `as z`, this will run without issue.

```python
with (
    open("xxxxxxxxxxxxxxxxxxxx", "w") as x,
    open("yyyyyyyyyyyyyyyyyyyyyy", "w") as y,
    open("zzzzzzzzzzzzzzzzzzz", "w") as z,
):
    x.write("x")
    y.write("y")
    z.write("z")

```

**Expected behavior**
No error, this is valid code that runs on python 3.9

**Environment**
- Version: main
- Windows Python 3.9.1

**Does this bug also happen on main?** To answer this, you have two options:
Yes, using <https://black.vercel.app/?version=main>

**Comment by JelleZijlstra** [comment]
See #1948.
