### ISSUE TITLE
What does "b" in release version mean?

### ISSUE THREAD

**Issue by Hongbo-Miao** [psf/black#2266]
What does "b" in release version mean?
The reason I ask is I am using Renovate.
Because Black is using "b" in all versions, it lets Renovate think all versions are unstable.
https://github.com/renovatebot/renovate/discussions/10199
I am wondering can we drop "b0", "b1", "b2" in release versions to make it like most other packages? Thanks

**Comment by felix-hilden** [comment]
Hi! It does indeed mean an unstable release. See and follow the pinned issue #517 about a stable release for updates!

**Comment by Hongbo-Miao** [comment]
Thanks @felix-hilden I just found that at same time. A very long thread! LOL

**Comment by felix-hilden** [comment]
Yeah 😅 it's been a long road
