### ISSUE TITLE
Black is wrapping result of an if/else oneliner in tuple (changing variable type)

### ISSUE THREAD

**Issue by tmotyl** [psf/black#2267]
**Describe the bug** A clear and concise description of what the bug is.

In some cases black is changing variable type by wrapping if/else oneliner expression in a tuple, which changes the variable type.

**To Reproduce** Steps to reproduce the behavior:
See example code:
https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACqAHxdAD2IimZxl1N_Wmlq4KNAXQ0SPvPbuEKTxVQ0VY8PC6zOM3kOy_hazUIwFPqfT_KXfZ566uiV3GFO2KICIF0rToCYmmHFekAa5Voo3cqCmEerIqUxWsd_agoWXOoD5xyciiHhcC9f073DM015yl7cEM_WBRDRH1F-576OK14ApIEdZYNxmK4AAZgBqwEAAHCdqJSxxGf7AgAAAAAEWVo=

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: stable

**Does this bug also happen on main?** 

yes

**Comment by felix-hilden** [comment]
Hi! I think this does not result in a tuple. Adding a set of parentheses is simply a way of spreading the expression on multiple lines. To form a one-tuple, you'd need a comma after the value:

```python
# tuple
val = (1,)

# not a tuple
val = (1 if False else 2)
```

Could you verify whether or not the result is indeed a tuple?

**Comment by tmotyl** [comment]
ah, yea, Thanks @felix-hilden yoy're right
