### ISSUE TITLE
`--experimental-string-processing` crash on string + % {

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#2271]
```
% cat legacy.py                                   

def _legacy_listen_examples():
    text += (
        "    \"listen for the '%(event_name)s' event\"\n"
        "\n    # ... (event logic logic logic) ...\n"
        % {
            "since": since,
        }
    )
% black --experimental-string-processing legacy.py
error: cannot format legacy.py: Apparently, old parentheses do NOT exist?!
Oh no! 💥 💔 💥
1 file failed to reformat.
```
Minified from a file in sqlalchemy that we originally found this crash on.

The crash is in the `StringParenWrapper` class in `trans.py`, which apparently doesn't know how to handle the parentheses enclosing the string + `% {`. I spent some time looking at it but I'm not sure what the best solution is.

**Comment by ichard26** [comment]
What even... apparently I opened the label selection menu at the worse time ever that I cleared the labels... AHHH

**Comment by JelleZijlstra** [comment]
@bbugyi200 would you still be interested in fixing this one? Right now it's the only `--experimental-string-processing` crash we're aware of.

**Comment by bbugyi200** [comment]
@JelleZijlstra Thanks for tagging me. The follownig PR should fix this: https://github.com/psf/black/pull/2283

**Comment by JelleZijlstra** [comment]
Thank you! I really appreciate you helping out with all of these issues.
