### ISSUE TITLE
Valid toml syntax causes black to crash

### ISSUE THREAD

**Issue by nat-n** [psf/black#2280]
**Describe the bug**

I have a pyproject.toml for configuring various other tools (not black), which includes a list with mixed type contents, as explicitly support by the v1.0.0 of the toml spec.

When I run black it crashes with a cryptic traceback from inside the toml library.

**To Reproduce**

```bash
mkdir new_project
cat <<EOT > ./new_project/pyproject.toml
# this example is from the toml spec
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
EOT
cd new_project
black .
```

**Expected behavior**

It shouldn't crash.

**Environment (please complete the following information):**

- Version: black, version 21.5b1
- OS and Python version: MacOs Python 3.8.8

---

Since the presently used "toml" library explicitly only supports up to version 0.5.0 of the spec (from about two years ago), I'd suggest switching to [tomlkit](https://github.com/sdispater/tomlkit), which supports the current toml spec (officially up to 1.0.0rc1 but nothing has materially changed since then).

I'd be happy to put together a PR if this approach is deemed acceptable in principle.

**Comment by JelleZijlstra** [comment]
Seems reasonable. It looks like pip itself still uses `toml` though, and in practice compatibility with other Python tools that use pyproject.toml is probably more important for us than compatibility with the toml standard. There's some related discussion in https://discuss.python.org/t/adopting-recommending-a-toml-parser/4068.

**Comment by cooperlees** [comment]
[tomli](https://github.com/hukkinj1/tomli) looks promising. Hope it can get into the stdlib so toml can become "real" in python as a low level config file format. Thanks for raising this interesting issue. For now tho I think you're stuck using `0.5.0` toml for pyproject.toml as I'd like us to follow what `pip` does too.

**Comment by nat-n** [comment]
I see, yes it seems pip has the same issue. I'd argue there's still value in supporting the latest toml syntax, even if pip does not yet. In principle it should be a non breaking change, though I guess the bottom line is that any divergence presents a risk of unexpected consequences?

**Comment by hukkinj1** [comment]
I made an issue in pip issue tracker about this: https://github.com/pypa/pip/issues/10034

Let's see if they have willingness to upgrade to a TOML v1.0.0 compatible parser.
