### ISSUE TITLE
String processing doesn't respect existing code formatting for f-strings

### ISSUE THREAD

**Issue by jack1142** [psf/black#2293]
**Describe the bug**

There is some issue with how Black splits the string if at least one of them is an f-string.

**To Reproduce**

For example:
1. Take this file:
```py
message = (
    f"1. Go to Google Developers Console and log in with your Google account."
    "(https://console.developers.google.com/)"
    "2. You should be prompted to create a new project (name does not matter)."
    "3. Click on Enable APIs and Services at the top."
    "4. In the list of APIs choose or search for YouTube Data API v3 and "
    "click on it. Choose Enable."
    "5. Click on Credentials on the left navigation bar."
    "6. Click on Create Credential at the top."
    '7. At the top click the link for "API key".'
    "8. No application restrictions are needed. Click Create at the bottom."
    "9. You now have a key to add to `{prefix}set api youtube api_key`"
)
```
2. Run _Black_ on it with `--experimental-string-processing` flag
3. See rather bad formatting even though the original respected line length:
```py
message = (
    f"1. Go to Google Developers Console and log in with your Google account."
    f"(https://console.developers.google.com/"
    f")2. You should be prompted to create a new project (name does not matter"
    f").3. Click on Enable APIs and Services at the t"
    f"op.4. In the list of APIs choose or search for YouTube Data API v3 "
    f"and click on it. Choose En"
    f"able.5. Click on Credentials on the left navigatio"
    f"n bar.6. Click on Create Credential at t"
    f'he top.7. At the top click the link for "A'
    f'PI key".8. No application restrictions are needed. Click Create at th'
    f"e bottom.9. You now have a key to add to `{{prefix}}set api youtube api_key`"
)
```
I'm also not sure why it splits in the middle of the word?

**Expected behavior**

No 

**Environment (please complete the following information):**

- Version: main (cf75673 at the time of testing)
- OS and Python version: Windows 10/Python 3.8.9

**Does this bug also happen on main?**

Yes

**Additional context**

N/A

**Comment by vaneseltine** [comment]
I'm only seeing this with  --experimental-string-processing

**Comment by jack1142** [comment]
Aaaaand, of course, I forgot to mention that in the description, sorry. I updated the issue description appropriately.

**Comment by bbugyi200** [comment]
I'm looking into this. Note that this only occurs when you prefix one of the substrings with a redundant `f` (i.e. one of the substrings is an f-string containing no f-expression).

**Comment by bbugyi200** [comment]
This issue should be fixed by the following PR: https://github.com/psf/black/pull/2311
