### ISSUE TITLE
String processing produces code exceeding length limit

### ISSUE THREAD

**Issue by jack1142** [psf/black#2294]
**Describe the bug**

String processing produces code exceeding the length limit when it was already formatted properly before.

**To Reproduce**

For example:
1. Take this file:
```py
class X:
    async def foo(self):
        msg = ""
        for candidate in CANDIDATES:
            msg += (
                "**{candidate.object_type} {candidate.rev}**"
                " - {candidate.description}\n"
            )
```
2. Run _Black_ on it with these arguments `--experimental-string-processing`
3. See the reformatted code that exceeds line length limit:
```py
class X:
    async def foo(self):
        msg = ""
        for candidate in CANDIDATES:
            msg += "**{candidate.object_type} {candidate.rev}** - {candidate.description}\n"
```

**Expected behavior**

I expected the code to remain unchanged.

**Environment (please complete the following information):**

- Version: main (`cf75673` at the time of testing)
- OS and Python version: Windows 10/Python 3.8.9

**Does this bug also happen on main?**

Yes.

**Additional context**

I was unable to find another issue that would seem to be the same as this though it's possible I missed something. Just to be sure it's not about the same thing #2284 is, I also tried out the changes from #2292 (since they apparently fix some edge cases that weren't fixed by #2286.
Also, the original code actually contained f-string but to rule out that it has anything to do with #2293, I changed it to use regular strings which as you can see from the issue description didn't change the end result.

**Comment by jack1142** [comment]
Probably what's also important here is that Black doesn't try to split this string despite it being too long:
```py
class X:
    async def foo(self):
        msg = ""
        for candidate in CANDIDATES:
            msg += "**{candidate.object_type} {candidate.rev}** - {candidate.description}\n"
```

After a second look, it appears that usage of `+=` is the key issue here - it works fine when replacing it with `=`

**Comment by JelleZijlstra** [comment]
Does #2292 fix this?

**Comment by JelleZijlstra** [comment]
Never mind, you already discussed it.

**Comment by bbugyi200** [comment]
This issue should be fixed by the following PR: https://github.com/psf/black/pull/2312
