### ISSUE TITLE
Black as a library import should check for running event loop before installing

### ISSUE THREAD

**Issue by skrawcz** [psf/black#2302]
https://github.com/psf/black/blob/f2a3fee15c3bc0f4068b2b2fb64f255b417cb4ef/src/black/__init__.py#L57-L63

See comments I left here https://github.com/psf/black/commit/754eecf69eed0bdc75fe224c19a702a4f0676807#r51686621

# what is the issue?

We are using the black library in a system that already had an eventloop set. Importing black the library now clears the event loop settings we had. Impact to us is that we cannot use this latest version of black. 

# Suggestion

Black the library should not assume that it can create its own event loop -- instead it should check to see if a running event loop exists before calling `uvloop.install()`.  

Actually, I'd go further to ask why the library should be thinking about controlling an eventloop in the first place? Much like configuring loggers should not be set in libraries, event loops should not be set in libraries either?

**Comment by JelleZijlstra** [comment]
This also caused problems for us, though I haven't had time to investigate exactly what happened yet.

I suggest we should do `uvloop.install` only when Black is invoked from the command line, perhaps in `patched_main()`. This prevents side effects when Black is imported as a library.

**Comment by JelleZijlstra** [comment]
Note that Black doesn't have a supported library API yet (#779). However, we recognize that many people are already importing Black as a library and we shouldn't make the experience worse.

**Comment by cooperlees** [comment]
Yup. This all makes sense. I'll get a PR up to move the loop install for black to patched_main()..

I think it still makes sense for blackd / primer where it is.
