### ISSUE TITLE
Black fails due to non-equivalent code generation 

### ISSUE THREAD

**Issue by sharpblade4** [psf/black#2322]
**Describe the bug**

Format failure due to non-equivalent code to the original, probably because of replacing tab with spaces inside a doc-string.

**To Reproduce**

1. create a file `something.py`
1. paste the content:
    ```python
    def foo() -> None:
        """ Some documentatios:
                    'serialization.format' = '	',
        """
        pass
    
    ```
1. run `black something.py` 
1. observe error like:
    ```bash
    error: cannot format something.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please     report a bug on https://github.com/psf/black/issues.  This diff might be helpful:     /var/folders/lf/bprxq7t92ksgtvk8l0f41yxmdsfv3p/T/blk_adei6c6h.log
    ```

**Expected behavior**

Black should format the file, or at least leave it untouched, instead of failing.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS 11.4 (Big Sur) build 20F71, Python 3.9.4

**Does this bug also happen on main?**
Black seems to be *not crashing* when used on https://black.vercel.app/?version=main

**Additional context**
Code originally written in intellij 2020 with python plugin.

**Comment by JelleZijlstra** [comment]
Can you update to the latest release? 20.8b1 is quite out of date now.

**Comment by sharpblade4** [comment]
Upgrading to the latest version solved the issue.
