### ISSUE TITLE
No new line at file end

### ISSUE THREAD

**Issue by mironnn** [psf/black#2328]
**Add a new line at the end of python file or not to remove it**

Currently black removes extra blank line after python code at the end of file.
Tested inside the docker build from the repository.

```shell
root@8c79a371a51b:/# black test.py --check --diff --verbose
--- test.py	2021-06-11 09:53:10.665099 +0000
+++ test.py	2021-06-11 09:53:15.809714 +0000
@@ -1,6 +1,5 @@
 def main():
     print(11)


 main()
-
would reformat test.py
Oh no! 💥 💔 💥
1 file would be reformatted.
root@8c79a371a51b:/#
```

**Desired style**

Add a new line at the end of the file.

Flake8 example
https://www.flake8rules.com/rules/W292.html

**Comment by felix-hilden** [comment]
Hi, thanks for reporting! However, I can't reproduce this on the [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB1AFFdAD2IimZxl1N_WlbvK5V-fnZfBCsrtgusrgnbEsiETABMBYguIkpGMdZcwD5unV4-dfYkF1lw0GzdVPAnTCfnqBsd4NIvNke3HtN7Snx4MpBwywAAAADt1aHF7Ni0DgABbXbIdLNJH7bzfQEAAAAABFla). I'm not familiar with the docker build though. Do you have the latest version?

**Comment by mironnn** [comment]
Steps for reproduce:
1. git clone https://github.com/psf/black.git
2. cd black
3. docker build -t test_black .
4. docker run -it black_test bash
5. apt update
6. apt install vim
7. make any python file and check with black

Could you please check with such steps?

**Comment by mironnn** [comment]
Or use old true python venv module

Steps:
1. python3 -m venv .venv
2. source .venv/bin/activate
3. pip install black
4. make a python code example with a blank line at the end
5. run black to this file. File will be modified and blank line at the file end will be removed.

**Comment by felix-hilden** [comment]
Given that you are able to reproduce it with an ordinary virtual environment, I think we have something weird going on here. I have the current main (which is equivalent to the latest release) pulled and I created a file like you described:

```python
def main():
    print(11)


main()

```

Note the existing line ending. Both `black test.py` and `black test.py --check --diff --verbose` produce no modifications on the file.

**Comment by ichard26** [comment]
I cannot reproduce using the docker container from main (aa31a11). After format, vim doesn't tell give me the `noeol` indicator as your bug report would suggest. There was a bug with the diff output not adding a missing terminating newline: https://github.com/psf/black/issues/1662, but that was fixed a long time ago.

**Comment by mironnn** [comment]
Please advise, what I'm doing wrong?


https://user-images.githubusercontent.com/9884126/125957950-1c2008c5-858f-4b16-89db-dc5a8ad44173.mp4

**Comment by TomFryers** [comment]
It looks to me like your file ends with *two* blank lines, and Black is removing the extra one.

**Comment by felix-hilden** [comment]
Indeed, could you verify @mironnn by perhaps reading the file in Python or using some other editor?

**Comment by ichard26** [comment]
Given no one else has reported this bug and we haven't heard anything from the OP in nearly a year, I'm closing this. I'd be happy if someone (else) could provide reproduction steps that work.

**Comment by mironnn** [comment]
@ichard26 you're kidding

<img width="341" alt="image" src="https://user-images.githubusercontent.com/9884126/216174001-71255af0-c085-4320-a4b9-8c4ea5f931b3.png">

**Comment by TomFryers** [comment]
@mironnn I'm not quite sure what you're getting at. It seems to me like Black is functioning as intended.
![annotated](https://user-images.githubusercontent.com/61272761/216176011-b6101a18-e457-46af-8afa-c89ef0216851.png)

**Comment by itsdani** [comment]
I have came across the same thing and I also thought black was removing the new line, but it isn't.
The explanation is that vim/neovim doesn't show the empty line at EOF, and always appends it by default. For more details check out [this question](https://vi.stackexchange.com/questions/22783/visual-indicator-for-a-file-that-doesnt-end-in-newline) and `:h eol` in vim
