### ISSUE TITLE
Zero length stdin input causes black to fail (regression)

### ISSUE THREAD

**Issue by andyphelps** [psf/black#2337]
**Describe the bug**

Using latest version 21.6b0 piping an empty file into black as below causes "string index out of range".  This is a regression from 21.5b2.  

NOTE: referencing an empty file works as expected this is only when piping into - as example below.
i.e. this works:
```
touch __init__.py
python -m black __init__.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**To Reproduce**

```
touch __init__.py
cat __init__.py | python -m black -
error: cannot format -: string index out of range
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**

Using stdin with empty file works as previous version without error.

**Environment (please complete the following information):**

- Version: 
- OS and Python version: 

**Does this bug also happen on main?**

Yes

**Additional context**

A bit of a tails case but we're using this approach within a CI script.

**Comment by cooperlees** [comment]
I feel the opposite here and that we were broken before and this is now fixed. We should error when nothing is piped in. It will allow people to optimize their calls sending open strings and save those resources if starting black for no reason.

I feel your CI should check if the file is empty before trying to pipe it into black.

**Comment by felix-hilden** [comment]
That's a fair point, but not immediately obvious at least to me. The error happens when manually inputting an empty stream as well.

At the very least, I think "string index out of range" is not the error we want to be throwing. If we want to restrict to nonempty inputs, maybe it should read "cannot format empty stream" or something like that. Thoughts?

**Comment by JelleZijlstra** [comment]
I think we should allow this, since Unix tools generally accept empty input (e.g. cat, grep, awk).

**Comment by shadchin** [comment]
Bug here - https://github.com/psf/black/blob/main/src/black/__init__.py#L806

**Comment by simaki** [comment]
May I work on this?

**Comment by JelleZijlstra** [comment]
Please do!
