### ISSUE TITLE
fmt: skip removes a comment-only line before it

### ISSUE THREAD

**Issue by felix-hilden** [psf/black#2339]
**Describe the bug**
Comments behave oddly before `# fmt: skip` lines.

**To Reproduce**

```python
1  # fmt: skip
```
This works as expected: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABdAEJdAD2IimZxl1N_Wh88hfShH0DHZZA5Q5v65Sarb329o8bdh1eNCBi1PEY4-H-oxvKzc044Q1qsOBXDx_giyUOM6spXAAAAAJulPCuBSr5kAAFeXgK5bYgftvN9AQAAAAAEWVo=)

```python
# comment
1 # fmt: skip
```
Here the comment is removed: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABnAExdAD2IimZxl1N_Wg0-D7--OqqW_cT3fv_7jVgyWfNs4p8A-_XMXk499OalVYdcPx-Mg7NZoOGrqNVCaNgsHCqJlMRpZBzRHyOdABomAwAAEjGgXYIipwsAAWho7r3Lzh-2830BAAAAAARZWg==)

```python
# comment
# comment
1 # fmt: skip
```
Multiple comment lines are also removed: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AByAE1dAD2IimZxl1N_Wg0-D7--OqqW_cT3qoxJ_e1a0dd6jGXs5HQs_YMMvlaeXVSpNpgAHY4BN3yrM0AipY8KHnFLePUdLULD7ikB_W1DngvAAAAAAC-f7eCT9J8qAAFpc0NFtV0ftvN9AQAAAAAEWVo=)

<details><summary>Outdated info:</summary>
```python
# comment with
1 # fmt: skip
```
This results in internal error (not equivalent to source) because only a "h" character is left on the comment line that acts as a constant statement: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABsAFBdAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWuEia8Gy8w5OqOeOY_J4QCyqJ2voNYAg5xLwXfn8bNP31cgiRTEgBYJWgMcLgkk02-wXQOGBfve-zAMchIZQPOMaoAAFsbWWMzdoftvN9AQAAAAAEWVo=)

```python
# comment with spaces
1 # fmt: skip
```
This has invalid Python 3 syntax because it produces two constants separated by one space `h spaces`: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABzAFZdAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWq46zIfxxG5eWFn_PhkGjL6RpuWZQx-qLmQcxytzPVX-F3cI3xFlal74yTM5xAnklLBk1vQoKeSIYxHWoInAgAAAAFLr7qgx4SpAAAXJ0ehvnah-2830BAAAAAARZWg==)

</details>

**Expected behavior**
The comments should not affect the second line.

**Comment by felix-hilden** [comment]
I managed to simplify a lot.

It seems that a particular number of characters is simply removed from the start of the comment line. This does not happen to [other lines](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB2AFldAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWq46zIfxxG5eWFouCnJU5aSXCFD9SZxs1QzMsm_yLpRpDJFPH0Ce1BoaMxk_meYS68FqTEXSTIEFqwkV79abetWsAAAAAAOrO2uihdN5nAAF1dwfcr7wftvN9AQAAAAAEWVo=), but it does happen even if there are [empty lines in between](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB1AFhdAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWq46zIfxxG5eWJ1rLsyzQRxp_OxYs3Uq4ADyvs6Efq5DauS4qIcvMr5iXqk6Kcxzwp1PaIWakiJkWajgXcwt-qgAACtb_YWhSA0IAAXR20N2z0h-2830BAAAAAARZWg==) and the number of characters removed is the same.

What's more: the number of spaces before the format comment affects how many chars are removed: [less](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AByAFVdAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWq46zIfxxG5eWFotFXHbSpS3_CJz2WevcZpFKnYBuw5xLKL46_cS5itT6ezkdqfEFO37TI650r_hq9wCRkhsAAAAA4m1V9Jo1rWEAAXFzGt2u3x-2830BAAAAAARZWg==) and [more](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB2AFhdAD2IimZxl1N_Wg0-D7--OqqW_aJd1CNWq46zIfxxG5eWFn_khThdbNbf4OZzLBqzSchQV9qOUnuS_b_MW1dOpISButMdPlmeQcn8ABrxS6pFI9nBGlL_EnAAVgytfOggCHsAAXR3Ru20pR-2830BAAAAAARZWg==).

**Comment by tbabej** [comment]
Another reproducer:

```python
"""
Simple reproducer.
"""

# This should not be erased
a = [
    i
    for i in range(5)
]  # fmt: skip
```

does get formatted by black `21.7b0` as

```
 """
 Simple reproducer.
 """
-
-# This should not be erased
 a = [
     i
     for i in range(5)
 ]  # fmt: skip
```

**Comment by odimko** [comment]
any updates here?

**Comment by ichard26** [comment]
Nope, we don't have any updates to share. None of the maintainers (or any contributors) have looked into fixing this bug. I \*can\* look into this bug but I wouldn't hold my breath since this involves a part of the codebase that I've found hard to modify before / don't understand well.

**Comment by odimko** [comment]
@ichard26 got it, any effort would be much appreciated :)

**Comment by felix-hilden** [comment]
@odimko If this problem is particularly annoying to you, I would encourage you to consider contributing! We can't really guarantee that our volunteer contributors (which is all of us) prioritise anything specific. Even more debugging could be worth doing! Anything to get us closer to finding out why this happens.

**Comment by sodul** [comment]
We're hitting this bug.

I would recommend to update the documentation to make it explicit that this bug exists since it can have unwanted adverse effect on removing meta information from the code. I do realize that `# fmt: skip` is very complex and difficult to update and appreciate the work from the contributors on Black.

**Comment by felix-hilden** [comment]
In #2539 @myw provided additional information on the case where the skipped line is a decorator (quoting):

Based on my testing so far:

- bug behavior occurs regardless of what's before the comment: it could be nothing, a function, or another expression
- bug behavior occurs regardless of the level of nesting inside a `class` or `function`
- bug behavior occurs with multiple comment lines as well as single comment lines; all the comment lines are deleted
- bug behavior occurs regardless of whether the decorator is followed by parentheses or not, or whether or not those parentheses are broken up into multiple lines
- bug behavior occurs regardless of what follows the decorator (`def` or `class`)
- bug behavior occurs regardless of number of whitespace lines around the comment or decorator
- bug behavior occurs regardless of whether or not there are any number of comment lines, surrounded by any number of lines of whitespace, between the decorator and the thing it is decorating
- bug behavior occurs regardless of the presence, absence, or value of the following flags: `-S`, `--safe`, `--fast`, `--verbose`, `-C`, `--line-length`
- bug behavior occurs regardless of the length of the line(s) in the comment
- bug behavior occurs if the comments are indented but there is no preceding code at that indentation:
```python
    # foo

@sum  # fmt: skip
def x():
    pass
```
   will still remove the comment
- bug behavior does **not** occur if a comment is indented to the level of indentation of code inside a function or class that comes before it:
```python
def a():
    pass
    # foo

@sum  # fmt: skip
def x():
    pass
```
   will **not** remove the comment
- bug behavior does **not** occur if the decorator is wrapped in `#fmt: on`/`#fmt: off`; it only occurs when `# fmt: skip` is used by itself; this is the workaround mentioned above
- but behavior does **not** occur with docstring-style (`"""`) comments

- By my testing, 19.10b0 was the last version that behaved correctly. I see release notes for 20.8b*, but was not able to install those to check. But by 21.4b0, the bug already exists.

**Comment by felix-hilden** [comment]
It seems that the behavior has changed a bit since creating this issue. The comment is no longer chopped, but instead always removed completely.
