### ISSUE TITLE
Failing to parse single-quote f-string with backslash inside it

### ISSUE THREAD

**Issue by whitespace-negative** [psf/black#2348]
**Describe the bug**

The formatter is failing to parse single quote f-string as it cannot include a backslash inside it.

**To Reproduce**

1. Take this test.py containing:
```python
b = "example1"
sts = "example2"
f"\"{b}\"{' ' * (long-len(b)+1)}: \"{sts}\",\n"
```
2. Run black without arguments.
3. See error -->
```
  File "/var/task/black/__init__.py", line 986, in assert_equivalent
    dst_ast = parse_ast(dst)
  File "/var/task/black/parsing.py", line 125, in parse_ast
    raise SyntaxError(
f'"{b}"{\' \' * (long-len(b)+1)}: "{sts}",\n'
```

**Expected behavior**
The formatter is expected to throw the said error and fail to format the said file.

**Environment (please complete the following information):**

- Version: [main]
- OS and Python version: [Linux/Python 3.9.5]

**Does this bug also happen on main?**
Yes

**Comment by ichard26** [comment]
heh, this was actually a bug with our string quote normalization logic. There's a check that asserts no backslashes was introduced in f-string expressions. Problem is that ehe regex used to detect f-string expressions wasn't quite right so the not all expressions were checked. 

This was a cool bug to debug and fix so thank you @whitespace-negative for reporting it!
