### ISSUE TITLE
Style question

### ISSUE THREAD

**Issue by ImmoWetzel** [psf/black#2350]
Hi,

we use black in the company to format the python code for some small internal tools. But nobody could explain why black converts a readable code into non readable.. There is for sure an idea behind this.
Which ?

example:
```

    parser.add_argument("-o", "--output_dir",   default=None, help="fixed folder of the BaseConfig log output and modified XML file; or automatic /tmp/ ")
    parser.add_argument("-a", "--arg_file",     default=None, help="Robot Project argument file (when given this replaces all other arguments) ")
    parser.add_argument("-e", "--debug",        default=None, help="debug level < *INFO* | DEBUG > ")

```
the extra spaces makes it more readable and faster readable and verify but black removes the extra spaces.

example:
an dictionary is filled with defaults very self explaining
```

            ....
            'propagate': True
            },
            'plain': {
                'handlers': ['plain'],
                'level': "DEBUG",
                'propagate': True
            }
        }
    })

```
but black compresses many of these helpful structures. Why ?

**Comment by cooperlees** [comment]
Why it does not directly answer you question, have you read https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html? It explains why Black does some of the behaviors you're asking about.

Black's main goal is to avoid this discussion. If you find the Black style does not work for you, maybe it's not the tool for you and your organization.

**Comment by ichard26** [comment]
Given this issue has received zero activity in over 5ish months (and the unlikeliness of us changing this formatting as it flys in the face of "don't take into account user formatting") I'll be closing this. Thank you for asking, happy to explain further!
