### ISSUE TITLE
"IndexError: list index out of range" on all filesm in folder

### ISSUE THREAD

**Issue by adamklaff** [psf/black#2351]
I'm running black via pipx, and I am getting this on every file I run black on in my project folder. If I move the file outside my project folder, it will process. Any ideas?

> Traceback (most recent call last):
>   File "/Users/user1/.local/bin/black", line 8, in <module>
>     sys.exit(patched_main())
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/black/__init__.py", line 1128, in patched_main
>     main()
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/click/core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/click/core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/black/__init__.py", line 410, in main
>     sources = get_sources(
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/black/__init__.py", line 476, in get_sources
>     gitignore = get_gitignore(root)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/black/files.py", line 123, in get_gitignore
>     return PathSpec.from_lines("gitwildmatch", lines)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/pathspec/pathspec.py", line 95, in from_lines
>     lines = [pattern_factory(line) for line in lines if line]
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/pathspec/pathspec.py", line 95, in <listcomp>
>     lines = [pattern_factory(line) for line in lines if line]
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/pathspec/pattern.py", line 83, in __init__
>     regex, include = self.pattern_to_regex(pattern)
>   File "/Users/user1/.local/pipx/venvs/black/lib/python3.9/site-packages/pathspec/patterns/gitwildmatch.py", line 112, in pattern_to_regex
>     if not pattern_segs[-1] and len(pattern_segs) > 1:
> IndexError: list index out of range

**Comment by adamklaff** [comment]
This was due to a misconfigured .gitignore file. Fixed.

**Comment by ichard26** [comment]
It's great you were able to fix the issue on your own @adamklaff but that uncaught exception + traceback probably wasn't the most easy thing to debug I can imagine! For that I've opened a new issue asking for a more user-friendly error to be emitted when the .gitignore related code blows up :) #2359 

Thanks for the report and therefore idea!

**Comment by SebastiaanZ** [comment]
@adamklaff I was looking into your bug and I wasn't able to reproduce it. Do you happen to have the fragment of your `.gitignore` file that triggers the exception? I want to provide a nice solution for #2359.

**Comment by adamklaff** [comment]
The last line just had a “/“ by itself
