### ISSUE TITLE
Inconsistent dict formatting with optional comma

### ISSUE THREAD

**Issue by treenoder** [psf/black#2353]
Black format of dicts with a single field is dependent of optional comma at the end.
Is it intended behavior or some kind of inconsistency?

**Before black**
```python
x = {'a':42}
y = {'a':42,}
```

**After Black:**
```python
x = {"a": 42}
y = {
    "a": 42,
}
```

**Comment by felix-hilden** [comment]
Hi, this would be the result of our optional magic trailing comma that is used to explode short collections! See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas

**Comment by graingert** [comment]
I think there's something here. A comma should only be considered magical if followed by a newline
