### ISSUE TITLE
Weird fstring formatting

### ISSUE THREAD

**Issue by matteosantama** [psf/black#2393]
## Before

```python
foo = "foo"
bar = "bar"
msg = (
    f"This is a fake message containing {foo} "
    f"and {bar}"
)
```

## After
```python
foo = "foo"
bar = "bar"
msg = f"This is a fake message containing {foo} " f"and {bar}"
```

which apparently is indeed valid Python, but preferably the two pieces would be combined into a single string literal.

Python: 3.8.7
Black: 21.7b0

**Comment by JelleZijlstra** [comment]
The `--experimental-string-formatting` flag (which we plan to turn on by default at some point) should fix this.

**Comment by matteosantama** [comment]
Ah, thanks for the quick response. I searched the issues but didn't see anything. Feel free to close!
