### ISSUE TITLE
Black is not consistent wrt trailing commas in argument lists

### ISSUE THREAD

**Issue by glandium** [psf/black#2395]
**Describe the bug**

Running black before and after modifying a file doesn't produce the same formatting wrt trailing commas in argument lists.

**To Reproduce**

1. Take this file https://hg.mozilla.org/mozilla-central/file/287995cabe8ebd9a29f2f56dde65a84678a38229/testing/mach_commands.py
1. Run _Black_ on it, it makes no change (double checked after an upgrade to 21.7b0).
1. Apply the following patch:
```
@@ -683,7 +683,10 @@ class SpiderMonkeyTests(MachCommandBase):
         test_env = os.environ.copy()
         test_env["TOPSRCDIR"] = command_context.topsrcdir
 
-        return subprocess.call(jsapi_tests_cmd, env=test_env)
+        result = subprocess.call(jsapi_tests_cmd, env=test_env)
+        if result != 0:
+            print(f"jsapi-tests failed, exit code {result}")
+        return result
 
     def run_check_js_msg(self, command_context):
         import subprocess
```
1. Run _Black_ again.

**Expected behavior**

No change the second time. Maybe changes the first time.

**Actual behavior**

Applies these changes to the file
```
@@ -176,7 +176,7 @@ class AddTest(MachCommandBase):
         doc=None,
         overwrite=False,
         editor=MISSING_ARG,
-        **kwargs
+        **kwargs,
     ):
         import addtest
         import io
@@ -437,7 +437,7 @@ class Test(MachCommandBase):
                     suite["mach_command"],
                     command_context._mach_context,
                     argv=extra_args,
-                    **kwargs
+                    **kwargs,
                 )
                 if res:
                     status = res
@@ -464,7 +464,7 @@ class Test(MachCommandBase):
                 command_context._mach_context,
                 argv=extra_args,
                 test_objects=tests,
-                **kwargs
+                **kwargs,
             )
             if res:
                 status = res
```

**Bonus**

If you unapply the patch and run black again, you don't get back the original file, you get the original file with the `kwargs` changes applied.

**Environment (please complete the following information):**

- Version: 21.7b0
- OS and Python version: Linux/Python 3.7.3

**Does this bug also happen on main?**

Yes.

**Comment by JelleZijlstra** [comment]
This is because of how we autodetect whether a file is Python 3.6-only. When you add an f-string, we detect that the file is Python 3.6+ and therefore make changes that are only safe in 3.6+, such as adding the trailing space.

To avoid getting this sort of change when you add an f-string, add an explicit `target_version` in your configuration.
