### ISSUE TITLE
blackargs not recognized when using with .editorconfig

### ISSUE THREAD

**Issue by harryghgim** [psf/black#2401]
**Describe the bug**
max line length formatting not applying when I use editorconfig. It applys only when I use vscode setting with black args `--line-length=119`. Please guide me if I missed anything.

**To Reproduce**
- install editorconfig for vscode plugin
- paste the following `.editorconfig` file recommended by django github
```
# https://editorconfig.org/

root = true

[*]
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
end_of_line = lf
charset = utf-8

# Docstrings and comments use max_line_length = 79
[*.py]
max_line_length = 119

# Use 2 spaces for the HTML files
[*.html]
indent_size = 2

# The JSON files contain newlines inconsistently
[*.json]
indent_size = 2
insert_final_newline = ignore

[**/admin/js/vendor/**]
indent_style = ignore
indent_size = ignore

# Minified JavaScript files shouldn't be changed
[**.min.js]
indent_style = ignore
insert_final_newline = ignore

# Makefiles always use tabs for indentation
[Makefile]
indent_style = tab

# Batch files use tabs for indentation
[*.bat]
indent_style = tab

[docs/**.txt]
max_line_length = 79

[*.yml]
indent_size = 2
```

do `Format document` by pressing Shift + Alt + F in vscode.

If I set `.settings.json` in my vscode project as follows however, it works.

```
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
      "--line-length=119"
    ],
```

**Expected behavior**

**Environment (please complete the following information):**

- Version: 21.7b0
- OS and Python version: Mac OS Catalia 10.15.7/python 3.8.2

**Does this bug also happen on main?**
I think so, since I directly installed by running `pip install black` in shell.

**Additional context**

**Comment by JelleZijlstra** [comment]
I don't know what an editorconfig file is, and I'm pretty sure Black doesn't either. https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file explains the config files black uses.

**Comment by felix-hilden** [comment]
To add to that, if `editorconfig` is for VSCode to read and pass to Black on the command line, I think this issue is out of scope for Black. Seems like VSCode is not smart enough to recognise that the user requests a max line length in the config and that Black has such an option available. Might be better to raise this issue with them!

**Comment by ichard26** [comment]
Yeah, Black does not support `.editorconfig` as a configuration file. My guess is that you misunderstood what the "Using Black with other tools" page is all about. The key thing is that the configuration listed there are for the other tools using their supported configuration formats (with the end goal being so the tools play nicely with each other):

> Please note that Black only supports the TOML file format for its configuration (e.g. pyproject.toml). The provided examples are to only configure their corresponding tools, using their supported file formats.

**Comment by ichard26** [comment]
Given there's already a note about this in the docs I'mma close this. If someone wants to suggest Black should support .editorconfig, please open a separate issue, thank you!

**Comment by caniko** [comment]
FYI: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html?highlight=setup.cfg#formats
