### ISSUE TITLE
Nested Tuples are not well formatted

### ISSUE THREAD

**Issue by michaelmiscanuk** [psf/black#2402]
I have some nested tuples, but unfortunately one of them is not well formatted with black. 

First one is formatted well but look at the second one - BOOK_CHOICES.
Can you explain why is that happening?

```

RADIO_CHOICES = (
    ("Value One", "Value One Display"),
    ("Value Two", "Text For Value Two"),
    ("Value Three", "Value Three's Display Text"),
)

BOOK_CHOICES = (
    (
        "Non-Fiction",
        (("1", "Deep Learning with Keras"), ("2", "Web Development with Django")),
    ),
    ("Fiction", (("3", "Brave New World"), ("4", "The Great Gatsby"))),
)

```

**Comment by felix-hilden** [comment]
Hi! This is entirely expected behavior, although admittedly more awkward for longer nested tuples. The second tuple gets exploded once more, because having it on one line would exceed the max line length.

Could you provide the formatting that you would expect?

**Comment by michaelmiscanuk** [comment]
Hi, I expect it to be consistent, so nested levels should appear at least the same, like this:

```
BOOK_CHOICES = (
    (
        "Non-Fiction",
        (("1", "Deep Learning with Keras"), ("2", "Web Development with Django")),
    ),
    (
        "Fiction", 
        (("3", "Brave New World"), ("4", "The Great Gatsby"))
    ),
)
```

But this might be better:

```
BOOK_CHOICES = (
    (
        "Non-Fiction",
            (
                ("1", "Deep Learning with Keras"), 
                ("2", "Web Development with Django")
            ),
    ),
    (
        "Fiction", 
            (
                ("3", "Brave New World"), 
                ("4", "The Great Gatsby")
            )
    ),
)
```


Or this, if you thing there is no need to make all parenthesis on their own lines, is also fine:

```
BOOK_CHOICES = (
    ("Non-Fiction",
        (
            ("1", "Deep Learning with Keras"), 
            ("2", "Web Development with Django")
        ),
    ),
    ("Fiction", 
        (
            ("3", "Brave New World"), 
            ("4", "The Great Gatsby")
        )
    ),
)
```

**Comment by felix-hilden** [comment]
I appreciate the effort for making this case work, and the formatting does look nice, but I think this wouldn't really apply to generic tuples. For example, in the first improved example the second elements of tuples are indented more. Why? I get that it's more readable in *this* case, but other than that I see no justification (apart from the next item being a collection too?). And we don't determine if collection contents are symmetric, which is why the lines that do fit are not exploded. Hope this clears the choice up a bit. What do you think?

Are you perhaps suggesting that we *should* analyse the collections to find the symmetric cases? That could be a discussion worth having.

**Comment by JelleZijlstra** [comment]
Note that you can use the magic trailing comma (https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=magic#the-magic-trailing-comma) to achieve your desired style.

**Comment by michaelmiscanuk** [comment]
Yes, training works perfectly:

```
BOOK_CHOICES = (
    (
        "Non-Fiction",
        (
            ("1", "Deep Learning with Keras"),
            ("2", "Web Development with Django"),
        ),
    ),
    (
        "Fiction",
        (
            ("3", "Brave New World"),
            ("4", "The Great Gatsby"),
        ),
    ),
)
```

Thank you :)
