### ISSUE TITLE
Simple CLI 

### ISSUE THREAD

**Issue by the-wondersmith** [psf/black#2404]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cooperlees** [comment]
Hi. Did you submit in error? I'll leave it up for a few hours in case you're editing. But as it, this is pretty unactionable.

**Comment by cooperlees** [comment]
Going to close as https://github.com/psf/black/issues/2405 looks more legit.
