### ISSUE TITLE
Please honor intended *horizontal* grow with magic comma

### ISSUE THREAD

**Issue by complyue** [psf/black#2409]
**Is your feature request related to a problem? Please describe.**

https://github.com/psf/black/pull/826#issuecomment-493549892

> ... for collections that you know will grow, there was no way to anticipate it by exploding them into one-element-per-line. Why would you want that? Because it minimizes diffs and that is a thing Black advertises as a feature: minimizing diff noise.

Now with #826 effected, my short collections with trailing commas will all explode into multiple lines, introducing way too loud noise (as well as waste of vertical space) to my codebase. 

I know they'll grow, but only within single line, in near future, I don't anticipate most of them grow into multiple lines. And when one collection shall pass the threshold from single line to multi line in farther future, that change should deserves a larger diff to give the correct visual.

My situation can not be solved with `--skip-magic-trailing-comma` introduced by #1288, as it'll remove my trailing "magic" comma, then either the last element or the first one, will appear unequal to other elements when I adjust their relative positions.

**Describe the solution you'd like**

I suggest that anticipated vertical grow to be expressed by the magic trailing comma *plus* at least 2 lines of elements, effectively making anticipated horizontal grow expressible & honored, by the magic trailing comma plus a single line of elements (within line length limit of course).

**Comment by JelleZijlstra** [comment]
Could you give some examples of code that you'd like to work differently? I don't understand from your description why you can't use `--skip-magic-trailing-comma`.

**Comment by complyue** [comment]
With `--skip-magic-trailing-comma`, black will format

```python
seq = [3, 2, 5,]
```
into

```python
seq = [3, 2, 5]
```

while without it, black would give

```python
seq = [
    3,
    2,
    5,
]
```

What I want is `seq = [3, 2, 5,]` kept intact.

(Actually `seq = [ 3, 2, 5, ]` is more preferable to me, but that's not this feature request is asking for)

**Comment by JelleZijlstra** [comment]
Thanks for the explanation. That's a change in formatting behavior that I'd be very unlikely to support. The existing magic trailing comma behavior already introduces more dependencies on prior formatting than I'd like, and this proposal would make it worse, which is going to be confusing for users and make Black-formatted code less consistent.

**Comment by complyue** [comment]
To me this change is not extending the semantics of "magic trailing comma", but to polish a corner case where it made overly strong an assumption - the element list of a collection can only grow vertically.

**Comment by cooperlees** [comment]
I agree with Jelle here. I don't think the behavior you want is intuitive to what black users are now accustom too.

Just for my interest, what is the advantage of the trailing comma when a list is on one line? Or is it just the fact you have code with this trailing comma and you want to avoid changes?
- i.e. `seq = [3, 2, 5,]`

**Comment by complyue** [comment]
@cooperlees That way I can intuitively select one or more elements together with the respective comma(s), and drag&drop to move the whole within the collection; that's at par with the vertical cases where `Option ↓` and `Option ↑` can be used to shift the whole line(s) up or down.

**Comment by complyue** [comment]
@cooperlees 
>  I don't think the behavior you want is intuitive to what black users are now accustom too.

I don't think they'll keep all elements on a single line, plus the final trailing comma, if that's really "vertical grow" already on their mind, so I suggest their intuition will be maintained.

**Comment by 153957** [comment]
> That way I can intuitively select one or more elements together with the respective comma(s), and drag&drop to move the whole within the collection;

But that won't work unless you also have a trailing space after the final comma which you can select and 'drag&drop'. Otherwise there will still be overhead/additional work when you, for example, move the last item to be the first.

**Comment by complyue** [comment]
Yeah, in my own language's formatter, both leading and trailing spaces - as written by user - are honored as well, so the practice works perfectly well. But black is not willing to respond to user directions by design, so I hesitate to make a similar (but orthogonal to this request) feature request.

Anyway, with black formatting Python, at least the result will be consistent & stable, so long as I perform a format action each time such a move is done. All rest are already acceptable, just left this bit, that for the trailing comma be preserved (and no explosion from originally single-line src, of course).

**Comment by felix-hilden** [comment]
Hi! As Jelle and Cooper have outlined already, this is likely not something we're willing to change in the style, so I'll be closing this issue.
