### ISSUE TITLE
Add tox to Pipfile

### ISSUE THREAD

**Issue by xrisk** [psf/black#2410]
The contributing guide suggests using tox to run tests. Perhaps it should be added to the dev dependencies? I would make a PR but I'm unsure how to determine the lowest version to add.

**Comment by HassanAbouelela** [comment]
Tox is part of the test-dependencies file (no version), but Ive been of the opinion all of the requirements should be merged into the pip file for a little while now.

**Comment by ichard26** [comment]
Sorry, I was planning to do this but I never did. This will be an improvement regardless if it isn't perfect - there's a lot of other things in the "improving the contributing experience" issue I need to pick up and resolve, but it's a step forward. Lemme put up a PR.

**Comment by ichard26** [comment]
Status update: I'm currently battling weird bugs with pipenv (including one where having a virtual enviroment in the project would make pipenv think a dep is local when it isn't ...) but I should hopefully get this done soon!
