### ISSUE TITLE
pre-commit example shouldn't encourage deprecated practice

### ISSUE THREAD

**Issue by MarcoGorelli** [psf/black#2415]
From the [pre-commit docs](https://pre-commit.com/)

> Using a branch name (or HEAD) for the value of rev is not supported and will only represent the state of that mutable ref at the time of hook installation (and will NOT update automatically).

I'd suggest that the docs just use the latest tag in their example

**Comment by asottile** [comment]
#420 is a duplicate

**Comment by MarcoGorelli** [comment]
indeed - thanks, I'll change the PR to reference that
