### ISSUE TITLE
Better Comments

### ISSUE THREAD

**Issue by Coronon** [psf/black#2422]
**Is your feature request related to a problem? Please describe.**

I am using the VisualStudio Code extension [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments), which works by coloring comments based on a specific symbol/string right after the comment start. The frustrating part is that Black always adds a space in between, which would turn this:
```py
a = 10  #? Should we change this
```
into this:
```py
a = 10  # ? Should we change this
```
which looks disgraceful.

**Describe the solution you'd like**

Some setting for an array of characters that can extend the commen start e.g. `--comment-start '["*", "!", "TODO"]'

**Describe alternatives you've considered**

Another option would be a flag to turn of formatting a space after the comment start.

**Comment by SoftwareSheriff** [comment]
I too would like an option to control this behavior, but probably more to just disable it entirely. I find that having the space is good for prose, but requiring it for disabled code feels wrong/unnecessary, and enforcing this automatically is probably not possible.

**Comment by JelleZijlstra** [comment]
Closing in favor of #3668.
