### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by AndrewHoos** [psf/black#2427]
INTERNAL ERROR: Black produced different code on the second pass of the formatter

**To Reproduce**

Black this file
```
def black(foo):


    assert pythoncontent.content_from_environment(
        {
            "File": tmpdir / "FilePath.ptest",
            "Environment": {
                "Virtualenv": {
                    "RequiredPackages": {
                        'package': "1.0"
                    },
                    "RequirementsFile": "r.txt"
                }
            }
        }
    ) == PythonContent(requirement_files=[tmpdir / "r.txt"])
```

**Expected behavior**
No error

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version:  macOS  and python3.8.9

**Does this bug also happen on main?**

the website does not report an error

**Additional context**

Moving the dict out of the method call and assigning it to a local variable fixed the complaint from black

**Comment by ichard26** [comment]
Hello! Sorry for the trouble, but [it looks like this has been fixed](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIpAPpdAD2IimZxl1N_WlbvK5V8VdksqUlexsUHWLSqdnR3gUR0Qnxny8B5pszzV_zvaGLPwAHf6TTaF6rS5wsTjG4d_15pOBWKujRy7imn4qxyYjP2exiyGIRgDxO83F2lsWOrS_w8IgYxKkx1SzJYaBO-qRLU9bzxKhVaD3GDQfzYg7l_OGrqOXzGTh03tfVLn6T-j1oM10tU6K1CbeYYUEuAsLreccWKbt6B6xID0koJp2J5hhcGRcsgUNthTpBlWCLB68scTLd2Td1G7kTEka_e8jUJA6jg5qTOo7F6CQoTPGcdXdMzuI7Qv292Ilh0JABPavUqxa-DHLAuzQAAAABN2uNxMUtNIwABlgKqBAAAXiN1V7HEZ_sCAAAAAARZWg==) in the latest release. Could you try that and see if it fixes your issue? Testing locally, any version including and beyond 21.4b0 fixes this error case. Thanks for reporting!

**Comment by AndrewHoos** [comment]
Yep not sure why pip was not upgrading
