### ISSUE TITLE
Clean Trailing Whitespace

### ISSUE THREAD

**Issue by john-science** [psf/black#2435]
**Describe the style change**

Black does not currently clean trailing whitespace. This is strange, and does not jive well with any major Python linter I can find (say Pylint).

**Additional context**

The only reason I can think of to not do this now is backwards compatibility.

If ticket isn't immediately closed for being annoying to the dev team, I would happily implement it.

Thanks.

**Comment by JelleZijlstra** [comment]
Can you give a specific example? I'm pretty sure we do clean it. The only exception may be within string literals, where changing whitespace could change the meaning of the code.

**Comment by BotchJet-Pony** [comment]
I'm out of the project?

пт, 20 авг. 2021 г., 21:16 John Stilley ***@***.***>:

**Comment by john-science** [comment]
> Can you give a specific example? I'm pretty sure we do clean it. The only exception may be within string literals, where changing whitespace could change the meaning of the code.

Ah, so that's your reasoning.  Okay, well, I guess we can close this.

The problem we have with `black` is that our docstrings can have trailing whitespace in them that angers `pylint`, but `black` refuses to clean it up.

But you're saying that's a design goal? Well, okay then.

Thanks!

**Comment by ichard26** [comment]
> The problem we have with black is that our docstrings can have trailing whitespace in them that angers pylint, but black refuses to clean it up.

We've had people comment how all whitespace is important in their docstrings because some pattern matching library uses the docstrings as a regex value for example :upside_down_face: [1]

#2150 has some good background discussion on this (plus other stuff). 

[^1]: I know trailing whitespace is probably less risky to touch, but honestly it feels like touching anything about docstrings is a no-no.

**Comment by onerandomusername** [comment]
IMO, I would perfer for docstrings to not be touched-- the ast should be as little affected as possible, if not touched at all. 

IF docstrings are touched, it should be a configuration option, perhaps even with a `# black: ignore` comment function to not clean up specific docstrings.
