### ISSUE TITLE
When I use the action of github, there will be incomprehensible problems when installing black

### ISSUE THREAD

**Issue by Wangwuyi123** [psf/black#2438]
Run if [ "$RUNNER_OS" == "Windows" ]; then
  
  if [ "$RUNNER_OS" == "Windows" ]; then
    python.exe -m pip install black
    python.exe -m black qlib -l 120 --check --diff
  else
    sudo python -m pip install black
    python -m black qlib -l 120 --check --diff
  fi
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.14/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.14/x64/lib
The directory '/home/runner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/runner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting black
  Could not find a version that satisfies the requirement black (from versions: )
No matching distribution found for black
Error: Process completed with exit code 1.

**Comment by onerandomusername** [comment]
First off, this is not a black issue.

Looks like the cache is not owned by the current user. I would suggest not using sudo with pip, as the error is all about that.

**Comment by ichard26** [comment]
Closing since 1) this isn't the project's issue to resolve, and 2) it's been ten days since the last update. I'm sorry your CI pipelines weren't working, but the only connection to psf/black is that pip crashed due to a cache issue when install black.
