### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by tinashe-wamambo** [psf/black#2444]
**Describe the bug**

I run `pre-commit run -a` and on a random python file, the following error is returned: `INTERNAL ERROR: Black produced different code on the second pass of the formatter`

**To Reproduce**

This error occurred randomly.

**Comment by Bluenix2** [comment]
The point of "To reproduce" is that you should attach code that looks somewhat identical to yours, but still causes (and as such, reproduces) the issue.

That way someone else can run this, and see it fail, then try to fix it until the issue stops happening.

**Comment by JelleZijlstra** [comment]
What @Bluenix2 said. We can't help you with this bug unless you give us code that reproduces the problem. It's unlikely that it really "occurred randomly"; Black's formatting code is deterministic as far as I know.
