### ISSUE TITLE
@overload definitions in .py files should be formatted as in .pyi files

### ISSUE THREAD

**Issue by andersk** [psf/black#2448]
**Describe the bug**

In a `.pyi` file, Black formats [overload annotations](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading) in a compact way following [PEP 484](https://www.python.org/dev/peps/pep-0484/) (#210). However, overloads are also allowed in a regular `.py` file, where Black unfortunately explodes them with two blank lines between every variant and each `...` on a line by itself.

The compact formatting should be allowed and/or enforced for overloads in `.py` files too—perhaps for every function whose complete body is the ellipsis literal `...` (this would help for [protocol definitions](https://mypy.readthedocs.io/en/stable/protocols.html#simple-user-defined-protocols) too).

**To Reproduce**

Run black on this `.py` file:

```python
@overload
def entry_points() -> SelectableGroups: ...
@overload
def entry_points(*, name: str, **params: str) -> EntryPoints: ...
@overload
def entry_points(*, value: str, **params: str) -> EntryPoints: ...
@overload
def entry_points(*, group: str, **params: str) -> EntryPoints: ...
@overload
def entry_points(*, module: str, **params: str) -> EntryPoints: ...
@overload
def entry_points(*, attr: str, **params: str) -> EntryPoints: ...

def entry_points(**params: str) -> Union[EntryPoints, SelectableGroups]:
    norm_name = operator.attrgetter('_normalized_name')
    eps = itertools.chain.from_iterable(
        dist.entry_points for dist in unique_everseen(distributions(), key=norm_name)
    )
    return SelectableGroups.load(eps).select(**params)
```

Black explodes it to

```python
@overload
def entry_points() -> SelectableGroups:
    ...


@overload
def entry_points(*, name: str, **params: str) -> EntryPoints:
    ...


@overload
def entry_points(*, value: str, **params: str) -> EntryPoints:
    ...


@overload
def entry_points(*, group: str, **params: str) -> EntryPoints:
    ...


@overload
def entry_points(*, module: str, **params: str) -> EntryPoints:
    ...


@overload
def entry_points(*, attr: str, **params: str) -> EntryPoints:
    ...


def entry_points(**params: str) -> Union[EntryPoints, SelectableGroups]:
    norm_name = operator.attrgetter("_normalized_name")
    eps = itertools.chain.from_iterable(
        dist.entry_points for dist in unique_everseen(distributions(), key=norm_name)
    )
    return SelectableGroups.load(eps).select(**params)
```

**Expected behavior**

This file should be formatted as written.

**Environment (please complete the following information):**

- Version: 21.7b0
- OS and Python version: Linux/Python 3.9.6

**Does this bug also happen on main?**

[Yes](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ANUAUNdAD2IimZxl1N_WjI5EWgEskyOY4KEUI3ap5YK9fw80GAAoz0aZNg8w-kbnZ2P7wPk2PApHAn1fG4rk1p22VDKvaHSon4Iul3EKZqPiyXR51Cr5lMMnUxdYliPJnOpnXQO1HyvP6QITuKwt13nwlORppToE7ktOxOZ-8J4t3geRrJRUyXWJdXGf2LssmlqLf1bb3Lx2YLExmKffgGnADSw0e2D852qdKM1q4x03-iWXxJgMxHuThY4j3l0dXyqytlctwcVPp54TuloJxMiEy7ZsaozXgmC41lETY3_e2GD04w3VsPp0n7X4i4RwzLwrOhqmVPy7HlAOtXr5vya_psxheYHxceXoyWwoAZKlimAUgLwMfjOQPyKfP1CC1wOVzPylFaniIPeynGNGu_qpNrjc0_WH9TgWSz-LGm_FcCOpYOHeOuOAABflqJUF7Vi7gAB3wLVBgAAXhz6T7HEZ_sCAAAAAARZWg==).

**Comment by graingert** [comment]
Looks like a dupe/related to https://github.com/psf/black/issues/1797

**Comment by JelleZijlstra** [comment]
Agreed, this is a special case of #1797
