### ISSUE TITLE
Black doesn't enforce two empty lines before functions on module level when they have a sticky leading comment

### ISSUE THREAD

**Issue by hugovk** [psf/black#246]
Operating system: macOS High Sierra
Python version: 3.6.5
Black version: 18.5b0
pycodestyle version: 2.4.0
Does also happen on master: yes

Should Black insert a newline between these variables and the function?

### pycodestyle complains about test.py but Black doesn't change it

```console
$ cat test.py
```
```python
from __future__ import print_function, unicode_literals

all_data = []
all_versions = set()

# Comment
def thing():
    pass
```
```console
$ pycodestyle test.py
test.py:7:1: E302 expected 2 blank lines, found 1
$ black test.py
/private/tmp/test.py already well formatted, good job.
```

### Both pycodestyle and Black are fine with test2.py

```console
$ cat test2.py
```
```python
from __future__ import print_function, unicode_literals

all_data = []
all_versions = set()


# Comment
def thing():
    pass
```
```console
$ pycodestyle test2.py
$ black test2.py
/private/tmp/test2.py already well formatted, good job.
```

### Black reformats test3.py, with no comment

```console
$ cat test3.py
```
```python
from __future__ import print_function, unicode_literals

all_data = []
all_versions = set()

def thing():
    pass
```
```console
$ pycodestyle test3.py
test3.py:6:1: E302 expected 2 blank lines, found 1
$ black test3.py
reformatted /private/tmp/test3.py
$ pycodestyle test3.py
$ cat test3.py
```
```python
from __future__ import print_function, unicode_literals

all_data = []
all_versions = set()


def thing():
    pass
```

**Comment by ambv** [comment]
@Sterbic, yes. The way that would work is to modify `format_str()` to buffer one line before appending it to `dst_contents`, and only doing that after the next line (or the end of the file) comes in. This complicates things a fair bit.

@hugovk, as a workaround in the mean time, add the extra newline yourself, Black will keep it (as you found out in test2.py).

**Comment by Sterbic** [comment]
Interesting, with give it a shot if I find some free time next week.

**Comment by tommyjcarpenter** [comment]
I was just going to post the same issue! Confirmed on my end too

```
_rmr_set_stimeout = rmr_c_lib.rmr_set_rtimeout
_rmr_set_stimeout.argtypes = [c_void_p, c_int]
_rmr_set_stimeout.restype = c_int
# extern int rmr_set_stimeout(void* vctx, int time)
def rmr_set_timeout(vctx, time):
    """
    Refer to the rmr C documentation for rmr_set_timeout
    """
    return _rmr_set_stimeout(vctx, time)
```

leads to `E302`; it doesn't change this code at all given the comment

**Comment by ichard26** [comment]
Can confirm that this is still an issue on main. Also even this code is untouched which isn't great:
```python
all_data = []
all_versions = set()
# Comment
def thing():
    pass

```
