### ISSUE TITLE
list slice format doesn't fulfill PEP8

### ISSUE THREAD

**Issue by pplmx** [psf/black#2470]
**Describe the bug**

oldvalue[index + 10:] will be replaced with oldvalue[index + 10 :]

- Pycharm will throw `PEP 8: E203 whitespace before ':'`

**To Reproduce**
create a list like this, then `black .`
```python
oldvalue[index + 10:]
```
It will be replaced with this
```python
oldvalue[index + 10 :]
```

**Expected behavior**
Keep it without any change.
```python
oldvalue[index + 10:]
```

**Environment (please complete the following information):**

- Version: 21.8b0
- OS and Python version: MacOS, Python3.9.6

**Does this bug also happen on main?**

Reproduced.

**Additional context**

**Comment by JelleZijlstra** [comment]
This is compliant with PEP 8. See https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated.

**Comment by pplmx** [comment]
Thanks for your immediate reply. 😄 :)
