### ISSUE TITLE
Installing Dependencies with Pipenv Fails

### ISSUE THREAD

**Issue by HassanAbouelela** [psf/black#2474]
**Describe the bug**

Running `pipenv install`, or any variation in python versions 3.7+, results in the following failure:
> [pipenv.exceptions.InstallError]: Looking in indexes: https://pypi.python.org/simple
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for dataclasses==0.8

**To Reproduce**

1. Clone the project
2. Run `pipenv install`

**Expected behavior**

Installation passes successfully, and dataclasses is not installed.

**Environment (please complete the following information):**

- Version: main
- OS and Python version: Windows/Python 3.9.6

I also reproduced this on docker using the `python:3-slim` image (I just modified the existing dockerfile to install using pipenv)

**Does this bug also happen on main?**

Yes

**Additional context**

https://github.com/psf/black/blob/72de89f54e744a8b3bbc9d3ea71f78a67d8ba82e/Pipfile#L54

I believe this failure is actually correct. If following the standard specified in the [docs](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#specifying-basically-anything), the following line should become:

```diff
- dataclasses = {"python_version <" = "3.7","version >" = "0.1.3"}
+ dataclasses = {markers="python_version < '3.7'","version >" = "0.1.3"}
```

**Comment by ichard26** [comment]
Hi Hassan :wave:

We've had similar reports with typing-extensions. Unfortunately this was really annoying to fix (and I suspect it might be not permanent) as pipenv locking is a pain to work with. Anyway I was able to get a PR (#2511) up so it would be wonderful if you could pull it down and confirm whether it fixes the issue. Thanks!
