### ISSUE TITLE
Vim plugin not respecting `pyproject.toml`

### ISSUE THREAD

**Issue by nullromo** [psf/black#2476]
**Describe the bug**

The vim plugin does not read or does not respect the options set in `pyproject.toml`.

**To Reproduce**

1. Create a file `test.py`:

    ```python
    def test(arg):
        print(arg)


    test(4,)
    ```

    There are 2 ways that black can format this. With the `--skip-magic-trailing-comma` option set to `false`, it formats like this (the **broken-line way**):

    ```python
    def test(arg):
        print(arg)


    test(
        4,
    )
    ```

    and with the `--skip-magic-trailing-comma` option set to `true`, it formats like this (the **connected-line way**):

    ```python
    def test(arg):
        print(arg)


    test(4)
    ```

2. Create a `pyproject.toml` file:
    ```toml
    [tool.black]
    skip-magic-trailing-comma = false
    ```
    Now run `python -m black test.py --check --diff` on the command line. It will show the **broken-line way**.

    Try running `:Black` on `test.py` in vim, and it will format to the **broken-line way**.

3. Change the `pyproject.toml` file to:
    ```toml
    [tool.black]
    skip-magic-trailing-comma = true
    ```
    Now run `python -m black test.py --check --diff` on the command line again. It will show the **connected-line way**.

    Try running `:Black` on `test.py` in vim again, and it will format to the **broken-line way**. This is incorrect. It should respect the `pyproject.toml` file's settings.

**Expected behavior**

I expect to be able to set the `--skip-magic-trailing-commas` option for the vim plugin. If it won't respect the `pyproject.toml` file, then it should at least have a `.vimrc`-settable option and this should be described in the README or documentation pages somewhere.

**Environment**

- Version: [main]
- OS and Python version: WSL (Linux)/Python 3.8.10

**Comment by lcheylus** [comment]
I confirm this issue with Black 21.9b0 version (Debian testing/bookworm amd64 - Python 3.9.7).

After some code digging, Vim plugin for black does not parse all variables in `pyproject.toml` file : see `autoload/black.vim` / `get_configs` => only the variables contained in `FLAGS` list are parsed to execute `black` command.

The variable `skip-magic-trailing-comma` in `pyproject.toml` is not parsed and used via Vim plugin.

**Comment by nullromo** [comment]
Thanks for the hint. I'm in the process of creating a PR to fix this issue.
