### ISSUE TITLE
Assignment to `with` results in error report pointing to unrelated line of code

### ISSUE THREAD

**Issue by b5nn** [psf/black#2485]
**Black https://github.com/python/black/commit/06ccb8**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADYAIRdAD2IimZxl1N_WlbvK5V7wuYaJaGG8vHPYHrG3tIt_qMy8RNUGHQ6gxXz1PNDlfq86NyLlf1gXIXWQnS4sXWdWy5ehnjWoaPqm_03lwZqYXusLZQ1uSecep0kv1g7RYOzo3foMvANkD8nKocF29JDMLx4tLn_cPHa3Zl41DCs6TkgYuBV8AAwFsIq2MwOegABoAHZAQAAp3C3vbHEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
def _print(*args, **kwargs):
    print(*args, **kwargs)


if __name__ == "__main__":
    with = 0
    _print(width)

```

## Output

```python
Cannot parse: 2:17:     print(*args, **kwargs)
```

## Expected

` ` ` 
    with = 0
         ^
SyntaxError: invalid syntax
` ` ` `

**Comment by b5nn** [comment]
Similar to: https://github.com/psf/black/issues/2442

**Comment by JelleZijlstra** [comment]
#1263 has the best explanation for what's going on here.
