### ISSUE TITLE
String's qoutation and indentation improvement/configuration//adjustment

### ISSUE THREAD

**Issue by Rafeqm** [psf/black#2490]
I want to request some features regarding quotation style.

- [ ] _**Single quote for:**_

**1. Multiline comment string**

Examples in the current _Black_ style
```python
"""_Using if Statements with Lists_"""
```
Desired style
```python
'''_Using if Statements with Lists_'''
```

**2. String inside list, tuple, dict, and any collection data type:**

Examples in the current _Black_ style
```python
available_toppings = [
    "mushrooms",
    "olives",
    "green peppers",
    "pepperoni",
    "pineapple",
    "extra cheese",
]
requested_toppings = ["mushrooms", "french fries", "extra cheese"]
```
Desired style
```python
available_toppings = [
    'mushrooms',
    'olives',
    'green peppers',
    'pepperoni',
    'pineapple',
    'extra cheese',
]
requested_toppings = ['mushrooms', 'french fries', 'extra cheese']
```
NOTE: Strings inside/passed _directly_ to functions remain as current style (i.e. `print("Are you sure you want a plain pizza?")`)

- [ ] **_Closing bracket/parenthes on multiline breaks indented as much as previous indented line_**

Examples in the current _Black_ style
```python
available_toppings = [
    "mushrooms",
    "olives",
    "green peppers",
    "pepperoni",
    "pineapple",
    "extra cheese",
]
```
Desired style
```python
available_toppings = [
    "mushrooms",
    "olives",
    "green peppers",
    "pepperoni",
    "pineapple",
    "extra cheese",
    ]
```

**Comment by cooperlees** [comment]
Thanks for the request. What do you feel the advantage of this is?

This change is very unlikely as we’re trying to stabilize the changes we enforce, not change them.

**Comment by Rafeqm** [comment]
I prefer single quoted string that way so it become neater

**Comment by felix-hilden** [comment]
Thanks for the suggestion, but this is something that is likely not going to happen. We've chosen our quotation style (see reasoning [here](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings)).

Also, at least in my opinion, changing the indentation of the last bracket does not look good. For example in function declarations this would not produce a sort of divider between arguments and the function body.

```python
def func_with(
    lots_of_long,
    arguments_that_would_not,
    fit_a_single_line_ever,
    even_if_we_tried_really_hard,
    ):
    pass

# VS

def func_with(
    lots_of_long,
    arguments_that_would_not,
    fit_a_single_line_ever,
    even_if_we_tried_really_hard,
):
    pass
```

**Comment by graingert** [comment]
regarding single quotes: https://github.com/psf/black/blob/41e670064063e3e221b1c3c40db5aaae784b5231/docs/the_black_code_style/current_style.md#L232
you can disable quote processing - and then use https://github.com/pre-commit/pre-commit-hooks#double-quote-string-fixer to force single quotes.

> NOTE: Strings inside/passed directly to functions remain as current style (i.e. `print("Are you sure you want a plain pizza?"))`

It's the first time I've heard of someone wanting to use a different style for strings not in Call node vs strings in `Call > Arg > BaseString` nodes, what purpose do you have for this? What about `print(["Are you sure you want a plain pizza?"]))`

According to PEP 8 "The closing brace/bracket/parenthesis on multiline constructs may either line up under the first non-whitespace character of the last line of list ... or it may be lined up under the first character of the line that starts the multiline construct", when given this choice by PEP 8 black chooses the second option: https://github.com/psf/black/blob/41e670064063e3e221b1c3c40db5aaae784b5231/docs/the_black_code_style/current_style.md#L122-L123

**Comment by Rafeqm** [comment]
Thanks for answering my issue. Now after digging more infos it becomes clearer now and makes more sense 👍
