### ISSUE TITLE
pre-commit hook fails when using `required-version`

### ISSUE THREAD

**Issue by spookylukey** [psf/black#2493]
This is attempting to use the pre-commit hook as described under [version control docs](https://black.readthedocs.io/en/stable/integrations/source_version_control.html) along with setting [--required-version](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#versions) in a configuration file. The pre-commit hook fails with:
```
Oh no! 💥 💔 💥 The required version `21.8b0` does not match the running version `0.1.dev1+ga8b4665`!
```

**To Reproduce**

First, a temporary folder/venv to test things in:
```
mkdir black-pre-commit-test
cd black-pre-commit-test
`which python3.9` -m venv venv
source venv/bin/activate
```
Then this script:
```
git init
pip install pre-commit
pre-commit install


cat > .pre-commit-config.yaml << EOF
repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
EOF

cat > pyproject.toml << EOF
[tool.black]
required-version = '21.8b0'
EOF

git add .pre-commit-config.yaml

touch test.py
pre-commit run black --files test.py
```
**Expected output**
```
black....................................................................Passed
```

**Actual output**
```
black....................................................................Failed
- hook id: black
- exit code: 1

Oh no! 💥 💔 💥 The required version `21.8b0` does not match the running version `0.1.dev1+ga8b4665`!
```

The same happens if doing a normal "git commit" - it is just easier to run the hook via `pre-commit run` directly. To test with hook:
```
git commit .pre-commit-config.yaml -m "pre-commit"
git add test.py
git commit test.py -m "test"
```

**Environment:**

- Version: 21.8b0
- OS: Linux, 
- Python: 3.9.5 (i.e. `which python3.9` used in the beginning of the instructions above)
- However, the version installed by pre-commit in `~/.cache/pre-commit/repo8_9vcuko/py_env-python3/bin/python3` is different - it is whatever is pointed to by `which python3`, which was Python 3.8.10 first time I ran it. By changing `language_version` in `.pre-commit-config.yaml` I can get a different version, e.g. Python 3.9.5, but it made no difference.

**Does this bug also happen on main?**

Haven't tried, because this is specific to pinning to published versions.

**Notes**

I can see the incorrect Black version by doing this:
```
~/.cache/pre-commit/repo8_9vcuko/py_env-python3.9/bin/black --version
```

However, I haven't been able to further debug because I don't know how this line works: https://github.com/psf/black/blob/41e670064063e3e221b1c3c40db5aaae784b5231/src/black/__init__.py#L67 - it appears to be doing some magical import.

**Comment by MarcoGorelli** [comment]
a workaround until this is fixed, if you need `required-version`, be to make it a local hook - then it'll be installed from `PyPI` and it'll have the right version
```python
- repo: local
   name: black
   id: black
   entry: black
   language: python
   types_or: [python, pyi]
   additional_dependencies: [black==21.8b0]
```

**Comment by jack1142** [comment]
Here's a workaround:
```yaml
repos:
  - repo: https://github.com/psf/black
    # The `refs/tags/<tag>:refs/tags/<tag>` is needed for black's required-version to work:
    # https://github.com/psf/black/issues/2493
    rev: 'refs/tags/22.3.0:refs/tags/22.3.0'
    hooks:
      - id: black
```

Because `pre-commit` accepts a git refspec, this way you can tell it to request the named ref as well.
Here's what pre-commit does more or less:
```
ubuntu@JakubWin10PC:/tmp
$ git init --template= failing-example
Initialized empty Git repository in /tmp/failing-example/.git/
ubuntu@JakubWin10PC:/tmp
$ cd failing-example
ubuntu@JakubWin10PC:/tmp/failing-example
$ git remote add origin https://github.com/psf/black
ubuntu@JakubWin10PC:/tmp/failing-example
$ git -c protocol.version=2 fetch origin 22.3.0 --depth=1
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 301 (delta 12), reused 148 (delta 6), pack-reused 0
Receiving objects: 100% (301/301), 1.14 MiB | 554.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
From https://github.com/psf/black
 * tag               22.3.0     -> FETCH_HEAD
ubuntu@JakubWin10PC:/tmp/failing-example
$ ls .git/refs/tags/



ubuntu@JakubWin10PC:/tmp
$ git init --template= working-example
Initialized empty Git repository in /tmp/working-example/.git/
ubuntu@JakubWin10PC:/tmp
$ cd working-example/
ubuntu@JakubWin10PC:/tmp/working-example
$ git remote add origin https://github.com/psf/black
ubuntu@JakubWin10PC:/tmp/working-example
$ git -c protocol.version=2 fetch origin refs/tags/22.3.0:refs/tags/22.3.0 --depth=1
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 301 (delta 12), reused 148 (delta 6), pack-reused 0
Receiving objects: 100% (301/301), 1.14 MiB | 544.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
From https://github.com/psf/black
 * [new tag]         22.3.0     -> 22.3.0
ubuntu@JakubWin10PC:/tmp/working-example
$ ls .git/refs/tags/
22.3.0
```

**Comment by felix-hilden** [comment]
Let's mention that in the docs.

**Comment by hauntsaninja** [comment]
Another way to fix this is using the new official mirror at https://github.com/psf/black-pre-commit-mirror , see https://github.com/psf/black/pull/3828

**Comment by jaques-sam-tlv** [comment]
This issue is not fixed, so I should not be closed. You can't imagine how much time I lost with this one.
The workarounds are not fixes.
