### ISSUE TITLE
replace('"', '\"') gets changed to replace('"', '"')

### ISSUE THREAD

**Issue by mbaragiola** [psf/black#2507]
**Describe the bug**

`"string".replace('"', '\"')` it is transformed to `"string".replace('"', '"')`

**To Reproduce**

Self evident in the description. Needs no arguments, just run plain `black` on any file containing that line.

**Expected behavior**

Shouldn't change the replace sentence.

**Environment (please complete the following information):**

- Version:

main, Linux, Python 3.8.10, gcc 9.4.0

**Does this bug also happen on main?**

Yes

**Additional context**

None

**Comment by felix-hilden** [comment]
Hi, why is this an issue concretely? The two strings are equal:

```python
>>> '"' == '\"'
True
```

**Comment by mbaragiola** [comment]
Ok, apparently `replace('"', r"\"")` is the correct way of doing this
