### ISSUE TITLE
Somehow funny (to me!) formatting

### ISSUE THREAD

**Issue by mpasternak** [psf/black#2515]
**Just letting you know that I love black!**

So, I had a fragment like:

```
    pbn_uczelnia.pbn_integracja = pbn_uczelnia.pbn_aktualizuj_na_biezaco = pbn_uczelnia.pbn_api_nie_wysylaj_prac_bez_pk = True
```

... and it got formatted to:

```
    pbn_uczelnia.pbn_integracja = (
        pbn_uczelnia.pbn_aktualizuj_na_biezaco
    ) = pbn_uczelnia.pbn_api_nie_wysylaj_prac_bez_pk = True
```

**How could this be improved?**

Well, perhaps I could get a warning on "enterprise-y" (long) variable names (wink). 

On the other hand... to be honest, I have no idea. I'm not sure if this could be improved, and if so - how. Just letting you know. 

Thanks for a great piece of software!

**Comment by felix-hilden** [comment]
Hi and thanks 😄 how about:

```python
pbn_uczelnia.pbn_integracja, pbn_uczelnia.pbn_aktualizuj_na_biezaco, pbn_uczelnia.pbn_api_nie_wysylaj_prac_bez_pk = (True, True, True)

# formatted:
(
    pbn_uczelnia.pbn_integracja,
    pbn_uczelnia.pbn_aktualizuj_na_biezaco,
    pbn_uczelnia.pbn_api_nie_wysylaj_prac_bez_pk,
) = (True, True, True)
```

**Comment by mpasternak** [comment]
IDK. I'm not by any means a Python style specialist and I don't aspire to be, but ``(True, True, True)`` looks bad versus ``Don't repeat yourself``. 

I guess there's just no good answer except that maybe I should stop using this kind of assignment syntax (as I hardly ever use it). 

Thanks!

**Comment by felix-hilden** [comment]
That might be it, at least I don't personally much care for it. But feel free to suggest a better formatting if you have one in mind though! To me it looks like a reasonable attempt at making it fit the line length, although I'll admit it is a bit ugly.
