### ISSUE TITLE
Add Hacktoberfest label

### ISSUE THREAD

**Issue by KristobalJunta** [psf/black#2517]
I think it would be cool for this project to take part in the global Hacktoberfest event. Hacktoberfest celebrates open source and encourages participation in the open source community.

More details can be found here: https://hacktoberfest.digitalocean.com/

**Comment by ichard26** [comment]
Mhmm as it's over now. I don't think we received any contributions that wanted to be labelled with  "hacktoberfest-accepted" anyway this year.

**Comment by aaossa** [comment]
Hi, seems like this year the participation is opt-in per project by adding the "hacktoberfest" topic to the repo, in case you want to consider it @ichard26 . More info on participation for maintainers in [the event website](https://hacktoberfest.com/participation/#maintainers).

**Comment by ichard26** [comment]
I don't have the permission needed to edit the repository's topics. That's fine though since we can still accept individual PRs via the `hacktoberfest-accepted` label.

**Comment by JelleZijlstra** [comment]
I added the label to the repo.
