### ISSUE TITLE
Missing documentation on magic comma

### ISSUE THREAD

**Issue by peterjc** [psf/black#2528]
**Is this related to a problem? Please describe.**

I am aware from the issue tracker of the "magic comma" whereby a trailing comma can sometimes influence what black does, but cannot see where this is documented - e.g. https://black.readthedocs.io/en/stable/faq.html#

**Describe the solution you'd like**

Have the "magic comma" documented.

**Describe alternatives you've considered**

I have browsed the issues but haven't hit on a succinct summary.

**Additional context**

I'm hoping to tweak how black formats some multi-line lists of constant values in my code.

**Comment by felix-hilden** [comment]
Yeah, we are discussing the "redundant" indentation level in #1811 if you'd like to follow it. But I'll close this issue for now since there seems to be nothing new requested, and the documentation exists!
