### ISSUE TITLE
CLI flag to disable looking for a configuration file

### ISSUE THREAD

**Issue by felix-hilden** [psf/black#2537]
**Is your feature request related to a problem? Please describe.**
Given that Black always looks for a configuration file, up to the file system root (!), it could be convenient to be able to explicitly *not* look for any configuration files. This would be advantageous when debugging different options.

**Describe the solution you'd like**

```sh
$ black --config -
$ black --no-config
```

Or maybe I've just missed it, didn't look at the code yet. In which case it should be documented in the CLI help.

**Comment by ichard26** [comment]
I'm in favour of this flag although I'm not sure if `--no-config` is the best name for it, perhaps `--isolated` although that could imply ignoring .gitignore files which this feature request doesn't cover ...

**Comment by felix-hilden** [comment]
`--isolated` would be fine by me if we truly isolate the run like you described. I thought `--no-config` would be recognisable as a reference to [flag options](https://click.palletsprojects.com/en/8.0.x/options/#boolean-flags), for which Click provides a `--no-...` variant as well. So would you prefer to use some sentinel value like a single dash?

**Comment by ichard26** [comment]
`--no-config` is probably best then. I'm not a big fan of the positive case being an option and the negated form being a flag, but that seems minor.

**Comment by felix-hilden** [comment]
I bet if we made it `--config -`, someone would present a case where they've named their configuration file exactly that 😄

**Comment by JelleZijlstra** [comment]
Do other tools (flake8, mypy, prettier, gofmt...) have an option for this? If so, how does it work?

**Comment by felix-hilden** [comment]
[Mypy](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-config-file) has `--config-file=`. I'm not sure if `gofmt` has any configuration files 😄

**Comment by hauntsaninja** [comment]
Closing, since I don't think there's a lot of appetite for this feature. Note `black --config /dev/null` works perfectly well for me on Unix systems.
