### ISSUE TITLE
Black deletes nonempty block comments before decorators left unfromatted with # fmt: skip

### ISSUE THREAD

**Issue by myw** [psf/black#2539]
**Bug description:**

Black deletes nonempty block comments before decorators left unfromatted with `#fmt: skip`.

As a legitimate real-world example (unlike the minimal test case I present below), I found this when `black` unexpectedly removed an `# endregion` comment in between two unit tests, the second of which was decorated with `@parameterize`. That decorator was skipped with `fmt: skip` to allow me to group/align rows of arguments.

For me right now, this is mostly an annoyance, since I know about it and have found a workaround (see below), but it's relatively severe in the correctness/safety sense, since there's real data loss from truly unexpected behavior.

See _Additional context_ for the debugging tests that I have done to isolate the conditions that do and do not trigger this particular behavior.

**Steps to reproduce:**

The link to the online playground in _Behavior on main_  below shows an example in `main`, but a similar minimal test example is included here for local reproduction.

Given the file `example.py`:
```py
# bar


@sum  # fmt: skip
def foo():
    pass
```

And the invocation: `black --diff example.py`. The results are:

```diff
--- example.py	2021-10-14 20:57:42.218431 +0000
+++ example.py	2021-10-14 20:57:51.942601 +0000
@@ -1,6 +1,3 @@
-# bar
-
-
 @sum  # fmt: skip
 def foo():
     pass
would reformat black_test.py
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

If Black is run without `--diff`, those lines are in fact removed.

**Expected behavior:**

Black should make no changes to this file. And even if it made changes, it should _definitely not_ remove the `# bar` comment.

**Environment:**

- Version: latest tagged: 21.9b0
- OS and Python version: Mac OS Big Sur 11.6, `pyenv` CPython version 3.7.10

**Behavior on `main`:**

[This bug happens on main](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB6AFpdAD2IimZxl1N_Wg0-Ef8DGymfK0sPysuNQTo-7NOt5p97IGqUzy6_KcwBYBT16xC35tVpFHm_BFc9Fss6_If81dPUPrGlNwlWBNje0QpD9WvOHGCjytILVlu6AwAAALWK31HJWZB0AAF2e-_DNJ4ftvN9AQAAAAAEWVo=).

**Additional context:**

Based on my testing so far:

- bug behavior occurs regardless of what's before the comment: it could be nothing, a function, or another expression
- bug behavior occurs regardless of the level of nesting inside a `class` or `function`
- bug behavior occurs with multiple comment lines as well as single comment lines; all the comment lines are deleted
- bug behavior occurs regardless of whether the decorator is followed by parentheses or not, or whether or not those parentheses are broken up into multiple lines
- bug behavior occurs regardless of what follows the decorator (`def` or `class`)
- bug behavior occurs regardless of number of whitespace lines around the comment or decorator
- bug behavior occurs regardless of whether or not there are any number of comment lines, surrounded by any number of lines of whitespace, between the decorator and the thing it is decorating
- bug behavior occurs regardless of the presence, absence, or value of the following flags: `-S`, `--safe`, `--fast`, `--verbose`, `-C`, `--line-length`
- bug behavior occurs regardless of the length of the line(s) in the comment
- bug behavior occurs if the comments are indented but there is no preceding code at that indentation:
```python
    # foo

@sum  # fmt: skip
def x():
    pass
```
   will still remove the comment
- bug behavior does **not** occur if a comment is indented to the level of indentation of code inside a function or class that comes before it:
```python
def a():
    pass
    # foo

@sum  # fmt: skip
def x():
    pass
```
   will **not** remove the comment
- bug behavior does **not** occur if the decorator is wrapped in `#fmt: on`/`#fmt: off`; it only occurs when `# fmt: skip` is used by itself; this is the workaround mentioned above
- but behavior does **not** occur with docstring-style (`"""`) comments

- By my testing, 19.10b0 was the last version that behaved correctly. I see release notes for 20.8b*, but was not able to install those to check. But by 21.4b0, the bug already exists.

**Comment by myw** [comment]
Hello — been a month on this bug—has anyone been able to look into this?

**Comment by myw** [comment]
Can still reproduce in 21.12b0

**Comment by angelatlarge** [comment]
Blank lines preceding lines marked with # fmt: skip are likewise deleted

**Comment by propertone** [comment]
Any plans to fix this? This is a pretty high severity bug since it literally deletes your code comments.

**Comment by felix-hilden** [comment]
This seems like a duplicate (or rather a subset) of #2339. I'll add your debugging there too, so we can consolidate the info! Thanks for digging in 👌

In terms of ETA on fixing, sadly not yet. I encourage you to contribute though!
