### ISSUE TITLE
What's up with the extra newline after from/import?

### ISSUE THREAD

**Issue by bukzor** [psf/black#2543]
**Describe the style change**

See also: #90

Black currently forces blank lines after all imports, including imports outside the "import section" at module scope. I find that this yields super inappropriate results. Black does not have enough context (outside the module-scope "import block") to know whether adding a blank line will correctly denote intent or enhance readability. Black should refuse to guess; as in #90, 

**Example input**

I'm having trouble generating a good example of a *necessary* inline import, but I hope we can agree that they do exist. Say we need to write this function, with all its unholy inline-imports intact:

```python
def f():
    from gizmo import frob

    try:
      return frob()

    except FileNotFoundError:
      import foo
      return foo.bar()
```

**The current _Black_ style**

Currently Black will force newlines into this function:

```python
def f():
    from gizmo import frob

    try:
      return frob()

    except frob.FrobError:
      import foo

      return foo.bar()
```

**Desired style**

Black should leave my newlines alone.

```python
def f():
    from gizmo import frob

    try:
      return frob()

    except FileNotFoundError:
      import foo
      return foo.bar()
```

**Additional context**

"In line" imports are considered bad style by most (all?) python communities, but they are sometimes necessary or even beneficial. Black currently inserts a newline after such statements which breaks the natural flow of code, and removes agency from developers to express intent and increase readability. I believe this is exactly analogous to issue #90 -- this (lack of a) blank line is a "extra-terse comment", denoting that this import is relevant only to the next line. Comments are really tricky for a code formatter to handle, but they're crucial, because they're a way for developers to express intent and increase readability. Black shouldn't be in the business of adding or removing comments.

**Comment by felix-hilden** [comment]
Reasonable request! Also related: #647

**Comment by HassanAbouelela** [comment]
I don't know how complex you'll want to get with this, but perhaps it should make a judgement to add that extra line in certain cases. Particularly, something that jumped to mind immediately is adding first-party imports to where you currently have `import foo`, should possibly use it. Example:

```python
    except FileNotFoundError:
      import abc
      import foo
      return foo.bar()
```

Should result in:
```python
    except FileNotFoundError:
      import abc

      import foo

      return foo.bar()
```

Alternatives would include having no line breaks there at all, but that would be a bit more complex, as you'll have to modify other tools to work with that (isort for instance).

**Comment by bukzor** [comment]
@felix-hilden I'm cleared to take a stab at implementation then? Any quick tips? I haven't worked in Black before, so I'll definitely go find and read your contributor's guide.

**Comment by stinos** [comment]
> abc is a first party import, 

right, I missed that because of the rather non-3rdparty looking name probably :)

**Comment by JelleZijlstra** [comment]
I'm inclined to keep this as is:

- We also add newlines after imports in the global scope, so the current behavior is consistent regardless of context.
- Local imports inside functions are unusual and a bit of a code smell, so it's not a bad thing that we make them stand out more.

**Comment by JelleZijlstra** [comment]
Closing per my previous comment.

**Comment by CrazyPython** [comment]
> Local imports inside functions are unusual and a bit of a code smell, so it's not a bad thing that we make them stand out more.

I agree that they are a code smell. When they are used appropriately, however, Black should not make them less readable. It should be the linter's job to warn about code smells like this.

**Comment by pevogam** [comment]
I would have preferred (and collected other opinions supporting the same conclusion):
```python
try:
    from vncdotool import api
    api.shutdown()
except ImportError:
    pass
```
rather than
```python
try:
    from vncdotool import api

    api.shutdown()
except ImportError:
    pass
```
which here even hides the semantic relation between the import line and the line to follow.

And no, local imports are not necessarily a code smell IMO and something that could be treated dynamically like any other statement. Long gone are the Pascal days of "put your imports here" followed by "put any and all of your variables here".
