### ISSUE TITLE
Slicing lists: space before/after colon not flake8 compatible

### ISSUE THREAD

**Issue by madduck** [psf/black#2550]
**Describe the bug**

A line like

```Python
bla(
    sheet=[p.row + p.timestamp for p in players[args.cutoff:]]
)
```

is turned into

```Python
bla(
    sheet=[p.row + p.timestamp for p in players[args.cutoff :]]
)                                                        # ^ space introduced here
```

This upsets flake8, which complains:

> E203 whitespace before ':'

**Environment (please complete the following information):**

- Version: 21.4b2-1 (Debian)
- OS and Python version: Debian unstable/Python 3.9.2-3

**Does this bug also happen on main?**

Yes.

**Comment by MarcoGorelli** [comment]
This is by design https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
