### ISSUE TITLE
Error trying to format line with parameter assignment and generator

### ISSUE THREAD

**Issue by tabrezm** [psf/black#2551]
**Describe the bug**

Black throws an error trying to format files containing a parameter assignment with a generator. This is valid Python code.

```
error: cannot format util.py: Cannot parse: 200:43:     if any(match := pattern_error.match(s) for s in buffer):
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**To Reproduce**

Code sample:
```python
    if any(match := pattern_error.match(s) for s in buffer):
        if match.group(2) == data_not_available:
            # Error OK to ignore.
            pass
```

**Expected behavior**

Black formats the file without errors. It seems to handle parameter assignment elsewhere just fine:
```python
            if not (next_line := next(buffer_iter, None)):
                # Buffer is incomplete, so we return early and wait to be
                # reinvoked with a complete buffer.
                return status
```

**Environment (please complete the following information):**

- Version: main
- OS and Python version: Mac/Python 3.9.7

**Does this bug also happen on main?**

Yes

**Additional context**

None

**Comment by betafcc** [comment]
up for  2022-10-09 on black 22.10.0:

```python
from typing import TypeVar, AsyncIterable

A = TypeVar("A")

async def enumerate(fa: AsyncIterable[A]) -> AsyncIterable[tuple[int, A]]:
    i = -1
    async for a in fa:
        yield i := i + 1, a
```

Result:

```
> black --version
black, 22.10.0 (compiled: yes)
Python (CPython) 3.10.6

> black dirty_bits/helpers/aitertools.py
error: cannot format dirty_bits/helpers/aitertools.py: Cannot parse: 165:15:         yield i:= i + 1, a

Oh no! 💥 💔 💥
1 file failed to reformat.
```

The parens workaround in https://github.com/psf/black/issues/1898 does work:

```python
async def enumerate(fa: AsyncIterable[A]) -> AsyncIterable[tuple[int, A]]:
    i = -1
    async for a in fa:
        yield (i := i + 1), a
```

**Comment by ichard26** [comment]
@isidentical would you be interested in taking a look at this issue?

**Comment by isidentical** [comment]
> @isidentical would you be interested in taking a look at this issue?

Yep, will look into it! Thanks for CC'ing me.

**Comment by isidentical** [comment]
@betafcc, the example you have shared already fails with the standard Python parser since the named expression has to be wrapped with parens in that case. But the bug still persists for generator expressions passed as call arguments (`any(x := y for _ in _)`), so hopefully #3327 should fix it.
