### ISSUE TITLE
The question mark in comment results in extra spaces on the second pass.

### ISSUE THREAD

**Issue by nick863** [psf/black#2554]
Repro steps:
1. Create the minimal jupyter notebook, which will contain one cell with the function ands a comment, containing question mark;
```
def example_fn(param):
    """
    param: str    what to print?
    """
    print(param)
```
2. Close the file and run
```
black-nb  Repro.ipynb
```
The error will be shown:
error: cannot format /path/to/nb/Repro.ipynb: INTERNAL ERROR: Black produced code that is not equivalent to the source on pass 1.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: ${TEMP}/blk_y4fjze4u.log

The diff will show that at the second pass extra whitespaces were added:
```
--- src
+++ dst
@@ -23,11 +23,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                '###MAGIC###    param: str    what to print?',  # str
+                '###MAGIC###        param: str    what to print?',  # str
             )  # /Constant
         )  # /Expr
         Expr(
           value=
             Call(
```
If the question mark will be removed, the notebook will pass

**Comment by HassanAbouelela** [comment]
Hi, I'm not able to reproduce on main or stable, could you perhaps share the version you're running? If possible, share the notebook too.

**Comment by nick863** [comment]
I have created separate [thread](https://github.com/tomcatling/black-nb/issues/69) on black-nb. Thank you!
