### ISSUE TITLE
black didn't format the cell note

### ISSUE THREAD

**Issue by Vincent0706** [psf/black#2588]
**Describe the style change**

**Examples in the current _Black_ style**

```python
#%% this is a cell
a = 12
```

**Desired style**

```python
# %% this is a cell
a = 12

```

**Additional context**

I found black can't format the cell note.

**Comment by MarcoGorelli** [comment]
Looks like this is intentional from https://github.com/psf/black/commit/c6c8ef76a4d991cd8a7a3b00a816b6db72ecdf04 , as `#%%` has a special meaning in the Spyder IDE

**Comment by Vincent0706** [comment]
I use vscode to write my code, and in vscode, the default note of cell is "# %%", rather than "#%%". And in spyder, "# %%" also can be distinguished as the begin of the cell. 
Whether it is better  to change the role?
I am a freshman, and could you tell me more about the difference among "##" , "#!" , "#:" and "#'"?

**Comment by ichard26** [comment]
Asking around it seems like Spyder _may have_ added support for `# %%`, `# %%%` and so on since we added that special case linked above. If that's the case we might want to remove it and the comment be reformatted normally. I'd appreciate comments from people who use Spyder though!

**Comment by lstsk** [comment]
Did someone already fix this?
