### ISSUE TITLE
Read the Docs 'stable' points to 21.9 not 21.10

### ISSUE THREAD

**Issue by adamchainz** [psf/black#2589]
**Is this related to a problem? Please describe.**

Visiting https://black.readthedocs.io/ redirects one to https://black.readthedocs.io/en/stable/ . This is the documentation for version 21.9 , so users can easily misses changes made for 21.10, such as those in: https://black.readthedocs.io/en/latest/integrations/source_version_control.html .

**Describe the solution you'd like**

Update 'stable' to point to 21.10

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by ichard26** [comment]
Yea, our policy for the time being is to move the stable tag a day or so after the release, not great from a documentation perspective but we haven't taken the time to come up with a better way of managing the documentation on release day. I'm busy till 2:30 PM EST but after then I can update the stable tag.

**Comment by cooperlees** [comment]
Yeah, I was going to say the same. I don't know what we do here. We leave it for a week or two to wait for reports. if none come we move the tag. Who ever releases that version of black usually owns moving the tag. This one is me.

21.10 isn't considered stable yet, so as far as I see, this is correct for now. `stable` on GitHub also still points @ 21.9 and should be used as the source of trith.

I'm all for ideas here tho. Latest and the versioned docs are correct right?

**Comment by JelleZijlstra** [comment]
Honestly maybe we should change this policy. It's easy to forget about later and confusing for users when the stable documentation doesn't match the latest release.

**Comment by cooperlees** [comment]
I think it's a misconception that stable should be == latest released version, especially in such a small time window ... I don't like the stable tag as a whole to be fair tho.

Maybe just removing "stable" documentation all together might help and only have versioned and latest.

**Comment by ichard26** [comment]
Another alternative is to release documentation for the specific version tags, so we would have latest and then 21.10b0 and so on ... in the dropdown or whatever. I don't like this too much as we would end up with a lot of options in the menu which doesn't work well but I also don't like removing the ability to see the documentation that isn't the latest.

**Comment by dawnofmidnight** [comment]
I like the idea of removing the stable tag and simply having tags for latest and each minor version.

**Comment by adamchainz** [comment]
> I think it's a misconception that stable should be == latest released version, especially in such a small time window

Afaiu the RtD default behaviour is that stable points to the latest non-pre-release version. Black is just being exceptional in that right now, it's all pre-releases.

As a user I'm surprised that stable != latest.

**Comment by ichard26** [comment]
It is now policy to update the stable branch after the release automation upload the sdist and wheels to PyPI. This is automated so this shouldn't be an issue anymore. It might be a good decision to not wait for the mypyc wheels to build and upload though since that can take a while (up to 30 minutes).
