### ISSUE TITLE
Provide a way for editor integrations to show warnings on lines Black would change

### ISSUE THREAD

**Issue by shacker** [psf/black#259]
In the Editor Integration section of the readme, it would be helpful to clarify that black is run in the editor as a formatter, not as a linter. It can "blindly" reformat your whole document, but it does not provide live inline suggestions.

But that raises a question: If we still want live linting, we have to keep e.g. flake8 enabled in the editor. But if we're going to format with black later anyway, what is the point of linting with another tool? Could black be utilized by editor plugins as a live linter so we don't have to use one tool for linting and black for formatting (which is going to change what we did at the linter's suggestion, and lead to discrepancy between what you're writing and what you end up with). 

Some clarification here would be helpful. And would love to hear your thoughts on whether black could be both a linter _and_ a formatter.

**Comment by shacker** [comment]
As a co-worker said, "Does this mean we can now write crap code and just trust the formatter?"

**Comment by ambv** [comment]
@shacker, yes, exactly, that is a built-in feature. Just write without worry and let the formatter care about making it look decent.

**Comment by shacker** [comment]
OK thanks. I think that most people think "Editor Integration" means "linting" so it would still be helpful to clarify the difference in that section of the readme.

**Comment by holmboe** [comment]
@ambv would you care to show how this integrate with `arc lint`? I assume you have a custom `ArcanistExternalLinter` to do this?

For anyone else reading this and curious of the Arcanist integration, here are some links:

- https://secure.phabricator.com/diffusion/ARC/browse/master/src/lint/linter/
- https://secure.phabricator.com/book/phabricator/article/arcanist_lint/

**Comment by joelruns** [comment]
Both tasks would be much easier to finish (ie: solvable with regex) if the `--diff` output had line numbers. The increase in annoyance (needing to relearn basic PHP and vim script) for writing both an `ArcanistExternalLinter` (over just a `script-and-regex` lint blob in `.arclint`) and a more complicated `ale_linter` made me abandon.

Eventually someone will write a `flake8` plugin for `black` and I think the urgency of this task will drop significantly. This seems to be the common lint usage for `prettier` in `eslint` as well.

**Comment by ambv** [comment]
Sorry @joelruns, @holmboe, I meant to share our integration but never did! Here's how you do it: https://gist.github.com/ambv/af475051961126765e35d31bd054e61c

**Comment by ambv** [comment]
The interesting part is using the built-in ArcanistDiffParser.

**Comment by joelruns** [comment]
@ambv Thanks for sharing the Arcanist linter! Could you also share a `.arclint` stub for using this class? For example, I'm not sure what to put for `"type"` in `.arclint`. 

Currently I'm having trouble setting it up... or should we just use this class as a starting point to set up an `ArcanistExternalLinter`?

**Comment by ambv** [comment]
> Currently I'm having trouble setting it up... or should we just use this class as a starting point to set up an ArcanistExternalLinter?

I don't understand. "ArcanistExternalLinter" is just a different subtype of "ArcanistLinter". I chose "ArcanistFutureLinter" because that enables up to X concurrent invocations (set to 8 in the Gist I shared).

> Could you also share a .arclint stub for using this class?

Use `arc linters` to see what type you should use in your file. There's more information on https://secure.phabricator.com/book/phabricator/article/arcanist_lint/#configuring-lint.

**Comment by hauntsaninja** [comment]
There hasn't been much demand for this specific feature, so closing. In general, we do want users to trust black, run it in a low friction way and not have to deal with noisy editor warnings in the meantime.
