### ISSUE TITLE
Display source line number on syntax error

### ISSUE THREAD

**Issue by stevexyz** [psf/black#2594]
**Describe the bug**

If a line with <> (wrong operator) is used the parser fail wothout reporting the line, and if the file is pretty long is not easy to understand what has happened

**To Reproduce**

Add this line in the middle of whatever python file:

```python

a = 1 <> 2

```

The resulting error is:

> cannot use --safe with this file; failed to parse source file.

**Expected behavior**

Display the source file line number together with the error

**Environment**

- Black's version:  main
- OS and Python version:  online formatter also

**Additional context**

**Comment by felix-hilden** [comment]
I'd be in favor of this. The information is most likely contained in the parser error message. In the meantime, you can try to run the file with Python and see the syntax error.
