### ISSUE TITLE
Is there a way to force Black to rewrite [1, 2, 3] -> [ 1, 2, 3 ]?

### ISSUE THREAD

**Issue by Alex3917** [psf/black#2596]
If I want to find all instances like `[1, 2, 3]` and then rewrite them to `[ 1, 2, 3 ]`, is there a good way to get Black to do this? I find the latter to be vastly more readable:

- Easier to see what the data structure is (e.g. list, tuple, set, etc.)
- Easier to read the first and last elements
- Especially easier within the context of function calls, so that it's easier to see that `my_func([ 1, 2, 3 ])` is accepting a list as one parameter, rather than three separate parameters.

The exception would be that I agree with PEP8 that adding spaces within lists doesn't improve things when accessing members from a list, so e.g. I'm fine with `my_list[1]` or `my_list[1:3]`.

Anyway I suspect most people won't agree with this request since it violates PEP8, but regardless I'm asking if it's possible to configure it at least for myself.

**Comment by HassanAbouelela** [comment]
Allowing configuration like that goes against one of the core tenets of black. As far as I'm aware, it isn't currently possible to do something like that.

**Comment by felix-hilden** [comment]
It's not configurable, as we really try to limit the number of configuration options. So thanks for asking, but it's a no 😅

**Comment by iago-lito** [comment]
(@Alex3917 unless you fork Black yourself into something else, with more configuration options ;)

**Comment by Alex3917** [comment]
If I can get PEP8 changed, would Black then update its formatting style to match the new PEP8?

**Comment by felix-hilden** [comment]
We'll cross that bridge when we get there 😄
