### ISSUE TITLE
Provide a flag to merge lines whenever possible

### ISSUE THREAD

**Issue by stephane-2** [psf/black#2597]
**Is your feature request related to a problem? Please describe.**
The typical situation where this would be useful:
1. The code is formatted using Black
2. This splits a parenthesized expression into multiple lines because it's too long.
3. The code is refactored.
4. The parenthesized expression would now fit on a single line.
5. But Black won't do that change, out of fear the split is intentional.
6. Each line of the code has to be checked manually to find such occurrences.

**Describe the solution you'd like**
Black should have a flag to fix this inconvenience that it introduces. More generally, Black should not introduce changes that it cannot undo once they become obsolete.

If Black had a flag to aggressively inline, then the obsolete multi-line splits Black introduced could be undone much more easily. It would be much easier to check that all introduced inlines are fine, rather than to check the whole code for split-line expressions that can be inlined.

**Additional context**
Concrete example
```
long_name_1 = (long_name_2, long_name_3)
-- Black -->
long_name_1 = (
    long_name_2,
    long_name_3,
)
-- Refactoring -->
short_name_1 = (
    short_name_2,
    short_name_3,
)
-- Black with aggressive inlining -->
short_name_1 = (short_name_2, short_name_3)
```

**Comment by felix-hilden** [comment]
Does `--skip-magic-trailing-comma` work?

**Comment by JelleZijlstra** [comment]
We already have `--skip-magic-trailing-comma` which does what you want as far as I can tell. We're unlikely to add more flags that affect formatting.

**Comment by stephane-2** [comment]
@felix-hilden @JelleZijlstra `--skip-magic-trailing-comma` does indeed work. Thank you!

I would suggest improving the documentation, though. I was only able to find it in the doc because I now know the name of the flag. An easily findable exhaustive list of flags would be great.
