### ISSUE TITLE
`skip_magic_trailing_comma = true` config file support

### ISSUE THREAD

**Issue by adamjstewart** [psf/black#2606]
**Is your feature request related to a problem? Please describe.**

One of the reasons I use black is so that I can focus on code without having to focus on style. #1824 introduced a `--skip-magic-trailing-comma` flag to further control style. However, there's no way to set this flag in a config file, so the file format will change depending on whether or not a contributor uses the flag.

**Describe the solution you'd like**

I would like to be able to set this in a config file like `pyproject.toml`:
```toml
[tool.black]
skip_magic_trailing_comma = true
```

**Describe alternatives you've considered**

I could alias `black` to `black --skip-magic-trailing-comma`, but that only affects me, not other users who contribute to my library.

**Additional context**

@hauntsaninja opening an issue as you suggested. I dug around a bit in the code but couldn't figure out how config file parsing works.

**Comment by jack1142** [comment]
The above configuration works for me, are you using an up-to-date version of Black?

**Comment by adamjstewart** [comment]
Huh, I swear this wasn't working when I tried a month ago, but it's working now. Maybe I was using an older version of black. Thanks for your help!
