### ISSUE TITLE
Vim plugin fail with Python 3.10 due to importing distutils in autoload/black.vim

### ISSUE THREAD

**Issue by 515k4** [psf/black#2607]
When you have vim builded with Python 3.10 the black plugin will fail when running :BlackUpgrade or :Black

> Error detected while processing /home/michal/.vim/bundle/black/autoload/black.vim:
> line  201:
> <string>:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

I am able to fix the issue by removing `from distutils.util import strtobool` from **autoload/black.vim** and re-implementing `strtobool` as suggested in [PEP 632](https://www.python.org/dev/peps/pep-0632/).

**Comment by JelleZijlstra** [comment]
Would you like to submit a PR?

**Comment by 515k4** [comment]
> Would you like to submit a PR?

Done. My first ever PR. I hope it's ok.
