### ISSUE TITLE
Docs: auto-hyphens show as tofu in Chromium-based browsers

### ISSUE THREAD

**Issue by hugovk** [psf/black#2609]
**Is this related to a problem? Please describe.**

* macOS Monterey
* Chrome 95
* Chrome Canary 98
* Opera 71
* Firefox 93

The CSS uses `hyphens: auto` which inserts hyphens for some words, however with the Georgia font the hyphen shows as an empty box aka ["tofu"](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character):

![image](https://user-images.githubusercontent.com/1324225/141677047-1ab0d43b-442b-4a77-9da2-e7c377d02908.png)

https://black.readthedocs.io/en/latest/contributing/the_basics.html

* Safari 15.1 is fine:

![image](https://user-images.githubusercontent.com/1324225/141677104-0b9ae277-6393-488d-a370-3d5c0ea6b7ea.png)

**Describe the solution you'd like**

Is there some other CSS needed to make the hyphen work? Or remove `hyphens: auto`? Or report to Chromium? (Edit: [reported](https://bugs.chromium.org/p/chromium/issues/detail?id=1270110))

**Describe alternatives you've considered**

Change the font? Use another browser?

**Comment by hugovk** [comment]
> * Firefox 93

Either I was mistaken about it being reproducible in Firefox 93, but in any case it's fine in newest Firefox 94.

**Comment by hugovk** [comment]
Reported to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1270110

**Comment by JelleZijlstra** [comment]
Do you know where this CSS comes from? It doesn't seem to be in our repo, so maybe this is better reported to Sphinx or whoever provides our theme.

**Comment by hugovk** [comment]
It's in a file called `basic.css`, which is from the Sphinx basic theme, and included in the Alabaster theme which Black uses. I've reported it to Alabaster: https://github.com/bitprophet/alabaster/issues/187. Thanks!

**Comment by hugovk** [comment]
Update: this was a Chromium bug on macOS Monterey, now fixed and confirmed fixed in Chrome Canary 98.0.4742.0:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1267606

Due for Chrome stable release on 1st Feb 2022:

* https://www.chromestatus.com/features/schedule

**Comment by luckman212** [comment]
Not actually fixed yet. That [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1267606) is still open, and still persists as of 101.0.4951.41

**Comment by hugovk** [comment]
(See followup here: https://github.com/bitprophet/alabaster/issues/187#issuecomment-1111789821)
