### ISSUE TITLE
Support --target-version for Python 3.10

### ISSUE THREAD

**Issue by jamilraichouni** [psf/black#2612]
**Is your feature request related to a problem? Please describe.**

I plan to start using Python 3.10 and wonder what I can specify as `--target-version`!?

**Describe the solution you'd like**

`black --help` shall list how I specify a Python 3.10 target version.

**Describe alternatives you've considered**

I installed Pyrhon 3.10 and the latest `black` version to see if `black --help` lists an appropriate target version.

**Additional context**

I looked through open issues here before I wrote the current one.

**Comment by cooperlees** [comment]
We need to support all 3.10 syntax first before being able to target this version. https://github.com/psf/black/issues/2242 is tracking that.

The support lag comes from lib2to3 deprecation and no settled replacement parser for us to use moving forward. This will be a major refactor / rewrite of black when the new parser is selected. We need all the help we can get here.

**Comment by JelleZijlstra** [comment]
@cooperlees you're out of date, we support 3.10 on main now :) We should probably do a release in the next week or so.
