### ISSUE TITLE
Black violates PEP 8: E203 (Whitespace before ':')

### ISSUE THREAD

**Issue by dyntaos** [psf/black#2626]
Black violates [PEP8: E203 (Whitespace before ':')](https://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes)

Tested on PyPi release: black-21.11b1 platformdirs-2.4.0 regex-2021.11.10 typing-extensions-4.0.0
Tested on Black Playground: Stable: 21.11b0 | Main: @d0b04d
Issue is present in all branches tested.

This only occurs in some situations in which list splicing contains an operator (see example below).

To reproduce:

Example code to be formatted with Black:
```
def good():
	a = list(range(10))
	return a[2:6]

def good2():
	a = list(range(10))
	p = 2
	return a[p:6]

def good3():
	a = list(range(10))
	q = 6
	return a[2:q]

def bad():
	a = list(range(10))
	p = 2
	return a[p:p + 4]
	
def bad2():
	a = list(range(10))
	p = 2
	return a[2:p + 4]
```

Result after formatting with Black Playground:
```
def good():
    a = list(range(10))
    return a[2:6]


def good2():
    a = list(range(10))
    p = 2
    return a[p:6]


def good3():
    a = list(range(10))
    q = 6
    return a[2:q]


def bad():
    a = list(range(10))
    p = 2
    return a[p : p + 4]  # Violates PEP8: E203


def bad2():
    a = list(range(10))
    p = 2
    return a[2 : p + 4]  # Violates PEP8: E203
```

**Comment by felix-hilden** [comment]
Hi! This is intentional: https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated

**Comment by SukiCZ** [comment]
Updated link: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#labels-why-pycodestyle-warnings
