### ISSUE TITLE
`target-version = ['py310']` does not work in pyproject.toml

### ISSUE THREAD

**Issue by AlexanderHOtt** [psf/black#2629]
**Describe the bug**

Setting `target-version = ['py310']` when using a pyproject.toml file to configure black fails to parse with the python 3.10 syntax.

**To Reproduce**

`pyproject.toml`
```toml
[tools.black]
target-version = ['py310']
```

`main.py`
```py
import random

n = random.randint(1, 10)

match n%2:
    case 0:
        print("even")
    case 1:
        print("odd")
```

```bash
$ black --config pyproject.toml main.py
error: cannot format main.py: Cannot parse: 5:6: match n%2:
Oh no! 💥 💔 💥
1 file failed to reformat.
```

```bash
$ black -t py310 test.py
reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

**Expected behavior**

I expect the config file to set the `target-version` flag correctly.
**Environment**

- Versions: 
```bash
$ black --version
black, 21.11b1 (compiled: no)

$ python -V
Python 3.10.0

$ neofetch
OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64
Kernel: 5.10.60.1-microsoft-standard-WSL2
```
**Additional context**

**Comment by ichard26** [comment]
Ah, you typoed the section name! Should be `[tool.black]` and not `[tools.black]`. Try that and lemme know if you're still facing issues.

**Comment by AlexanderHOtt** [comment]
That fixed it.
