### ISSUE TITLE
ImportError: cannot import name 'echo' from 'click' (unknown location)

### ISSUE THREAD

**Issue by salmanhiro** [psf/black#2634]
I'm using Python 3.8.9 with conda environment and resulted in this problem
```
Traceback (most recent call last):
  File "/Users/mac/opt/anaconda3/bin/black", line 5, in <module>
    from black import patched_main
  File "/Users/mac/opt/anaconda3/lib/python3.8/site-packages/black/__init__.py", line 46, in <module>
    from black.concurrency import cancel, shutdown, maybe_install_uvloop
  File "/Users/mac/opt/anaconda3/lib/python3.8/site-packages/black/concurrency.py", line 6, in <module>
    from black.output import err
  File "/Users/mac/opt/anaconda3/lib/python3.8/site-packages/black/output.py", line 11, in <module>
    from click import echo, style
ImportError: cannot import name 'echo' from 'click' (unknown location)
```

I tried to installing click by `pip install click` but the problem still persists

**Comment by ichard26** [comment]
Hello!

It's almost impossible to diagnose the issue without more information as especially this is an issue with the click library. As far as I can tell the echo function has existed under the click namespace for years. What version of click are you running? You might also want to upgrade / force-reinstall click via `--upgrade` / `--force-reinstall` pip install flags.

**Comment by JelleZijlstra** [comment]
Looks like this is probably something to do with namespace packages (https://www.python.org/dev/peps/pep-0420/).

**Comment by arturomf94** [comment]
Getting something similar in a GitHub Actions workflow running 3.7.12:

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/__init__.py)
```

**Comment by JelleZijlstra** [comment]
@arturomf94 you're using an old version of Black.

**Comment by pmolodo** [comment]
"old" meaning more than 5 hours ago:

https://github.com/psf/black/releases/tag/22.3.0

**Comment by JelleZijlstra** [comment]
> "old" meaning more than 5 hours ago:
> 
No, much older than that.

**Comment by arturomf94** [comment]
Tbf, I think I **am** using and older one! I believe it's `black==20.8b1`.

**Comment by pmolodo** [comment]
Hmm - ok, how old, then?  I was just writing some workaround code which is checking the version of black a user is requesting and pinning the version of `click` if it's before `22.3.0`.  Which version should I be checking for?

**Comment by JelleZijlstra** [comment]
Any version before 22.3.0 will fail. I was just pointing out that @arturomf94 was running a much older version.

**Comment by dahluwalia-ag** [comment]
I'm also having this error using pre-commit. pre-commit is using verison "21.12b0" so I will try the latest....
```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/daahluwa/.cache/pre-commit/repo6miac9jr/py_env-python3.7/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/daahluwa/.cache/pre-commit/repo6miac9jr/py_env-python3.7/lib/pyth
on3.7/site-packages/black/__init__.py", line 1372, in patched_main
    patch_click()
  File "/Users/daahluwa/.cache/pre-commit/repo6miac9jr/py_env-python3.7/lib/python3.7/site-packages/black/__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/Users/daahluwa/.cache/pre-commit/repo6miac9jr/py_env-python3.7/lib/python3.7/site-packages/click/__init__.py)
```

**Comment by dahluwalia-ag** [comment]
Changing to version 22.3.0 has solved the problem... thanks!

**Comment by arturomf94** [comment]
Pinned on `22.3.0` - works now 👍. Thanks @JelleZijlstra.

I think that change probably broke a lot of pipelines though :/

**Comment by flipbit03** [comment]
Just ran into the same issue on black via pre-commit. Moving to `22.3.0` fixed it. Thank goodness.

**Comment by steffnay** [comment]
Just gotta say omg glad y'all are already here because I was convinced I'd just broken my env somehow an hour ago when debugging another issue. Almost spent forever looking for a mistake that I hadn't actually made.

**Comment by JKCai** [comment]
thanks for the almost live chat and solution. Save me from troubleshooting my environment.

**Comment by JuanEscorcia** [comment]
heroes!

**Comment by flipbit03** [comment]
This was exactly my impression @JKCai, I just found this issue and we live debugged it together ahaha! Thanks everyone o/

**Comment by JuanEscorcia** [comment]
thanks a lot! :D

**Comment by JelleZijlstra** [comment]
I don't know how everyone ended up on this unrelated issue but glad it helped :) For the record, #2964 was where we tracked this bug.
