### ISSUE TITLE
21.11b1 Match Formatting Fails

### ISSUE THREAD

**Issue by idahogray** [psf/black#2636]
First off, thanks for releasing Python 3.10 support and thanks to everyone who contributed to make it possible.

**Describe the bug**

Parsing a Python 3.10 module using the match statement fails to parse.

**To Reproduce**

This snippet fails to parse (including in the online formatter).

```
match gse_element.find(".//scl:MinTime", namespaces=scl_namespaces):
    case ET.Element() as min_time_element:
        min_time = min_time_element.text
    case _:
        min_time = None
```

The resulting error is:

> error: cannot format scl_doc\scl_doc.py: Cannot parse: 47:14:         match gse_element.find(".//scl:MinTime", namespaces=scl_namespaces)

**Expected behavior**

The expectation is that black will be able to parse the file with this match statement.

**Environment**

- Black's version: 21.11b1
- OS and Python version: Windows/Python 3.10.0

Thank you and please let me know if you need more information.

**Comment by isidentical** [comment]
It actually works on the snippet you provided, but I guess the black didn't get invoked via `-t py310`. Since it is an experimental feature, it only gets enabled when you specify the target version. 

```
(.venv) (3.9.5) [  5:28ÖS ]  [ isidentical@msi:~/projects/black(main✅) ]
 $ cat t.py                                                                                                                                           150ms
match gse_element.find(".//scl:MinTime", namespaces=scl_namespaces):
    case ET.Element() as min_time_element:
        min_time = min_time_element.text
    case _:
        min_time = None
(.venv) (3.9.5) [  5:28ÖS ]  [ isidentical@msi:~/projects/black(main✅) ]
 $ black -t py310 -l10 --fast t.py                                                                                                                      2ms
reformatted t.py
All done! ✨ 🍰 ✨
1 file reformatted.
(.venv) (3.9.5) [  5:28ÖS ]  [ isidentical@msi:~/projects/black(main✅) ]
 $ cat t.py                                                                                                                                           145ms
match gse_element.find(
    ".//scl:MinTime",
    namespaces=scl_namespaces,
):
    case ET.Element() as min_time_element:
        min_time = (
            min_time_element.text
        )
    case _:
        min_time = None
(.venv) (3.9.5) [  5:28ÖS ]  [ isidentical@msi:~/projects/black(main✅) ]
```

**Comment by idahogray** [comment]
Ah, thank you. Sorry for the trouble. I have confirmed it works for me and will close the issue.
