### ISSUE TITLE
Quotes types in multiline f-string literals are not formatted

### ISSUE THREAD

**Issue by Numerlor** [psf/black#2640]
**Describe the bug**

Single quotes in multiline f-string literals are left unchanged even when unnecessary

**To Reproduce**
Run black on
```python
f"""{'a'}"""
```
the literal will be left unchanged

**Expected behavior**

The literal gets formatted into
```python
f"""{"a"}"""
```
**Environment**
- Black's version: 21.10b0 and main through the playground
- OS and Python version: Windows/Python 3.9.6

**Comment by onerandomusername** [comment]
Currently black does not format the insides of an f-string *at all*
