### ISSUE TITLE
RuntimeError: dictionary changed size during iternation.

### ISSUE THREAD

**Issue by daktsogl** [psf/black#2655]
All the time I'm seeing black get stuck, and it requires a manual restart.  

Here is an example of what we see on the pipeline console:

`$ tox -e black

black create: /tmp/pachyderm/echelon-curators/.tox/black
black installdeps: black
black installed: black==21.11b1,click==8.0.3,mypy-extensions==0.4.3,pathspec==0.9.0,platformdirs==2.4.0,regex==2021.11.10,tomli==1.2.2,typing-extensions==4.0.0
black run-test-pre: PYTHONHASHSEED='1617221419'
black run-test: commands[0] | black --check --exclude echelonlib/confluence.py curate.py report.py score.py sanitize.py scorecard_confluence.py echelonlib reports tests
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 317, in run
    result_item, is_broken, cause = self.wait_result_broken_or_wakeup()
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 376, in wait_result_broken_or_wakeup
    worker_sentinels = [p.sentinel for p in self.processes.values()]
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 376, in <listcomp>
    worker_sentinels = [p.sentinel for p in self.processes.values()]
RuntimeError: dictionary changed size during iteration`

What happens is `values()` normally returns a so-called dictionary view, but when done inside a for-loop they are transparently & magically wrapped in iter(), which means the dictionary view which normally handles changes, cannot handle changes anymore. Something like that. A common solution is to do `for v in list(d.values()):` which creates a copy of the values() in a list(), and so the original dictionary is free to change underneath.

**Comment by JelleZijlstra** [comment]
Do you have a way to reproduce this reliably?

The error is in `concurrent.futures` and we don't do anything all that crazy with process pools, so I suspect the bug is in that library (and therefore in CPython), not in black.

**Comment by daktsogl** [comment]
Ohh yes. You are correct. Apparently this is more of a python-3.9 thing.

I found this in relation to this problem.

https://bugs.python.org/issue43498
