### ISSUE TITLE
Misleading line number in `match` parse error

### ISSUE THREAD

**Issue by TmLev** [psf/black#2658]
**Describe the bug**

Attempt to format `match` expression with comma results in parsing error with misleading line number in error message.

**To Reproduce**

MRE:

```python
x = 1

match x:
    case 1 | 2:
        print("1 or 2")
    case _:
        print("Not 1 or 2")

match x, x + 1:
    case 1, 2:
        print("1 and 2")
```

Format command:

```sh
black --target-version py310 example.py
```

The resulting error is:

```log
error: cannot format example.py: Cannot parse: 3:6: match x:
Oh no! 💥 💔 💥
1 file failed to reformat.
```

And no errors are appearing if the last match expression is removed:

```python
x = 1

match x:
    case 1 | 2:
        print("1 or 2")
    case _:
        print("Not 1 or 2")
```

... OR `x, x + 1` and `1, 2` are replaced with `(x, x + 1)` and `(1, 2)`:

```python
x = 1

match x:
    case 1 | 2:
        print("1 or 2")
    case _:
        print("Not 1 or 2")

match (x, x + 1):
    case (1, 2):
        print("1 and 2")
```

**Expected behavior**

No errors (?).

**Environment**

- Black's version: `black, 21.11b1 (compiled: no)`
- OS and Python version: Mac OS 11.4, Python 3.10.0

**Comment by isidentical** [comment]
Seems similar to https://github.com/psf/black/issues/2637, can you check the same example with the latest black installed from main?

**Comment by isidentical** [comment]
Yep both the syntax and the error messages (thanks to @JelleZijlstra on #2649) seem to be fixed now.

**Comment by TmLev** [comment]
Okay, thanks.
Waiting for a new release.
