### ISSUE TITLE
py310 match: one-line case breaks

### ISSUE THREAD

**Issue by Stannislav** [psf/black#2664]
**Describe the bug**
In `python3.10` the `case` black can be written in the same line as the `case` keyword. However, this breaks `black`.

**To Reproduce**
Take this example code
```python
# example.py
x = 5
match x:
    case 5: print("it works")
```
It runs under `python3.10`:
```sh
python example.py
it works
```
However, `black` crashes:
```
black --target-version py310 example.py
error: cannot format example.py: INTERNAL ERROR: Black produced invalid code on pass 1: expected an indented block after 'case' statement on line 3 (<unknown>, line 4). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /var/folders/cz/v1lxwy5579502ksd81z14_t40000gp/T/blk_inxhkvdg.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
After manually reformatting the example as follows
```python
x = 5
match x:
    case 5:
        print("it works")
```
`black` stops crashing.

**Expected behavior**
`black` should not crash.

**Environment**
* macOS Big Sur 11.6
* `python 3.10.0`
* `black --version`: `black, 21.11b1 (compiled: no)`

**Comment by JelleZijlstra** [comment]
Confirmed the crash. cc @isidentical 

This is the output black produces (from the log file):
```
x = 5
match x:
    case 5:
    print("it works")
```
