### ISSUE TITLE
Bug on regular expression with black-21.12b0

### ISSUE THREAD

**Issue by ValentinRicher** [psf/black#2677]
**Describe the bug**

**To Reproduce**

With `pyproject.toml`

```
[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.env.*
  | \env
  | \.venv
  | \.venv2
  | venv
  | venv2
  | _build
  | build
  | dist
  | examples
  | docs

)/
'''

```

And run it with these arguments:

```sh
$ black --config="pyproject.toml" .
```

The resulting error is:

> Error: Invalid value for '--exclude': Not a valid regular expression

**Environment**

- Black's version:  21.12b0
- OS and Python version: macOs BigSur Python 3.8.10

**Additional context**

No problem with previous versions.

**Comment by JelleZijlstra** [comment]
The last line should be `\)`, not `)\`.

**Comment by ichard26** [comment]
FWIW, unless I'm missing something, we use something similar [with our configuration](https://github.com/psf/black/blob/main/pyproject.toml) and it doesn't break 🤷 Is that initial boolean OR really making and breaking this regex?

**Comment by JelleZijlstra** [comment]
Sorry, I was wrong. The problem is actually the `  | \env` line. I don't know what you meant but presumably it should be `\.env` or `env`. I can submit a PR so the error message doesn't drop re's error:
```
Error: Invalid value for '--exclude': Not a valid regular expression: bad escape \e at position 71 (line 7, column 5)
```
