### ISSUE TITLE
#fmt: skip results in change in second pass error

### ISSUE THREAD

**Issue by MJohnson459** [psf/black#2680]
**Describe the bug**

When using `#fmt: skip`, if there is no space between the `#` and `f` then black fails to format due to different result in the second pass.

**To Reproduce**

For example, take this code:
```python
def test():
    x = 1 #fmt: skip
```

https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABwAFNdAD2IimZxl1N_WlbvK5V_5PM4Nceap1_OfA9LqGqzctuugz_qJKhKcm0xODvQpn1SGiQJFVPjQaZCfva5pKHycj-2VXHw1ESugA17W0JffVNXXrlGAAC1vzI706u2xQABb3Hpg-HlH7bzfQEAAAAABFla

The resulting error is:

```
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_9vf9y7f5.log

Mode(target_versions=set(), line_length=88, string_normalization=True, is_pyi=False, is_ipynb=False, magic_trailing_comma=True, experimental_string_processing=False)
--- source
+++ first pass
@@ -1,2 +1,6 @@
 def test():
     x = 1 #fmt: skip
+  # fmt: skip
+
+
+# fmt: skip
--- first pass
+++ second pass
@@ -1,6 +1,3 @@
 def test():
-    x = 1 #fmt: skip
-  # fmt: skip
-
-
-# fmt: skip
+x = 1 #fmt: skip
+  # fmt: skip  # fmt: skip
```

**Expected behavior**

It should format correctly. I assume this is due to the first pass it being an invalid `fmt` specified without the space and so one is added which makes it valid for the second pass.

**Environment**

Black's version: black, 21.12b0 (compiled: no)

**Comment by andrerod22** [comment]
Replicated the issue on my machine, looking into the problem now.

**Comment by felix-hilden** [comment]
I think we have two options here:
- Accept any spacing in the skip comment
- Format the comment but not the line

Personally I'd be inclined to accept any amount of spacing, since the comment is also part of the line 😄 Thoughts?

We should also have a look if this is an issue with `# fmt: off`.

**Comment by andrerod22** [comment]
Ran the following with black and the #fmt: off was resolved with the space added
```
def test():
    #fmt: off
    arr = [1, 2, 3, 4, 5, 6, 7, 8]
```

**Comment by felix-hilden** [comment]
What's more, comments with additional spaces are [completely ignored](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABgAERdAD2IimZxl1N_WlOzAR7MsjJWBY1KVxq5FD2p2WWeL9idpeWYUvUSJgiqGuRQ4MOF01sNOSK8KT1padBy1ItRuHWWcBIgAHikGQ6u4xBBAAFgYUKPzn8ftvN9AQAAAAAEWVo=):

```python
a=1 #   fmt: skip

# produces

a = 1  #   fmt: skip
```

Could be unrelated to the bug itself, but definitely should be discussed when making a decision on how we accept these comments.

**Comment by andrerod22** [comment]
ull request proposal made here: https://github.com/psf/black/pull/2682

**Comment by myw** [comment]
Some of this behavior might be related to #2539
