### ISSUE TITLE
Black does not like white backgroud

### ISSUE THREAD

**Issue by csotto** [psf/black#2688]
**Describe the bug**

**To Reproduce**

For example, take this code:

```python
this = "code"
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

The resulting error is:

> cannot format file.py: INTERNAL ERROR: ...

**Expected behavior**

**Environment**

- Black's version: 
- OS and Python version: 

**Additional context**

**Comment by csotto** [comment]
I prefer white background on terminals.
Running Black ( black-21.12b0 ) on W10 Git terminal (MINGW64) configured with white background (255, 255, 255) results in a unreadable result message. (white letters over white background.

**Comment by JelleZijlstra** [comment]
What exactly is the error you are getting?

**Comment by ichard26** [comment]
![image](https://user-images.githubusercontent.com/63936253/146092063-0fca7d43-f54e-4c89-a481-64e07b5ba50d.png)

Assuming your colour padlette is configured properly it should be fine given we don't set any specific colours other than blue, yellow, green, and red.. although as I write that I do see our diff header is unreadable. 
![image](https://user-images.githubusercontent.com/63936253/146092298-17de166b-7021-4949-8438-a9b0d8ac95ad.png)

**Comment by ichard26** [comment]
Hi @csotto, did we resolve your issue via GH-2691 or do you have another issue to report?

**Comment by ichard26** [comment]
It's been two weeks so I'm going to close this issue as I can't tell what else would be broken on light-themed terminals after GH-2691. If Black is still broken for ya lemme know and I'll be happy to reopen!
