### ISSUE TITLE
Black Messing Up Working Code

### ISSUE THREAD

**Issue by barmanroys** [psf/black#2697]
Using black, 21.12b0 (installed with pip3) on Ubuntu 20.04, integrated with the atom-editor package. 

The problem is black seems to be messing up working code, introducing duplicate definitions of well defined functions and putting bracket opens and close at random places that are throwing error. 

Even if pylint was showing only warning and no error before applying black, the pylint itself is showing multiple errors after formatting with black. 

I have been recommended python black recently, and given its reputation, it seems I am using it the wrong way somehow. But did anyone else have the experience? 

The main issues I am coming up with 

- Duplicating function or method definitions
- Introducing random indents 
- Altering loop flow structures when I use `break` or `continue` 

So far, I was operating under the assumption that whatever black does, it will not break a working script. 

But from the way it is working, seems it will beautify the code, but also break at some points, that I have to correct, then _black_ the code again, hopefully with fewer changes and go through the iterations to eventually have an error free and perfectly stylised code.

**Comment by JelleZijlstra** [comment]
Black has safety checks that make the behavior you're describing highly unlikely. Is it possible that the integration with your editor is causing problems?

**Comment by onerandomusername** [comment]
Could you please share what the solution was, @barmanroys, for our reference?

**Comment by barmanroys** [comment]
> Could you please share what the solution was, @barmanroys, for our reference?

I tried to black my code via my terminal,  which worked perfectly. So it seems the issue lies with the atom package,  not the underlying black formatter. I created an issue at atom.
