### ISSUE TITLE
dependency_tree broken tomli<2.0.0,>=0.2.6, it should be using latest version 2.0.0

### ISSUE THREAD

**Issue by roshanguptamca** [psf/black#2703]
**Describe the bug**
black 21.12b0 requires tomli<2.0.0,>=0.2.6, but you have tomli 2.0.0 which is incompatible.

**To Reproduce**

For example, take this code:

```python
this = "code"
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

The resulting error is:

> cannot format file.py: INTERNAL ERROR: ...

**Expected behavior**

**Environment**

- Black's version: 
- OS and Python version: 

**Additional context**

**Comment by MarcoGorelli** [comment]
You'll have to downgrade your version of tomli, due to the upper bound on tomli in `black`

**Comment by ichard26** [comment]
I'm pretty sure @hukkin, the author behind tomli, is the one who put this pin here, would probably be a good idea to ask them to weigh in.

**Comment by hukkin** [comment]
Black is fully compatible with Tomli v2 starting from this PR here https://github.com/psf/black/pull/2431/files

Also, now that I had my one (and hopefully only) chance to make breaking changes to the API, I don't really object removing the upper pinning altogether. In case I find the need to break API in the future I'll try to do at least a year long deprecation period before.

Note that PR https://github.com/psf/black/pull/2408 includes moving the upper pin if you are otherwise happy with the changes there.

**Comment by hukkin** [comment]
BTW just out of curiosity: Do I deduce correctly from this issue that Black checks its dependency versions at runtime? Is that really necessary? Wouldn't it be better to leave dependency checking to the installer (typically `pip`) and make Black use whatever versions are available? And consider issues like this an error on user/installer side.

**Comment by MarcoGorelli** [comment]
> BTW just out of curiosity: Do I deduce correctly from this issue that Black checks its dependency versions at runtime? Is that really necessary? Wouldn't it be better to leave dependency checking to the installer (typically `pip`) and make Black use whatever versions are available? And consider issues like this an error on user/environment/installer side.

pretty sure the error here comes at installation, the `$ black file.py --target-version py39` in the issue is part of the issue template

**Comment by JelleZijlstra** [comment]
> Do I deduce correctly from this issue that Black checks its dependency versions at runtime? Is that really necessary? 

It doesn't. If you are talking about the `cannot format file.py: INTERNAL ERROR` line, that's part of the issue template. If you're reporting a bug, please don't keep that part around if you don't actually get an internal error.

**Comment by roshanguptamca** [comment]
> You'll have to downgrade your version of tomli, due to the upper bound on tomli in `black`

Yes thanks for reply, We did it as of now to go further until having permanent soluton.

**Comment by intgr** [comment]
The version pin was changed in #2408, this can be closed.

**Comment by cbrnr** [comment]
Now that black is a required dependency of ipython I think it would be even more important to push a new release rather sooner than later.

**Comment by felix-hilden** [comment]
We're releasing this week!

**Comment by cbrnr** [comment]
That's great to hear, thank you ❤️!

**Comment by merisbahti** [comment]
is there any workaround?

**Comment by MarcoGorelli** [comment]
> is there any workaround?

could install directly from GitHub, `pip install git+https://github.com/psf/black@32dd9ec`
