### ISSUE TITLE
Stubs: black removes empty lines between attributes and methods

### ISSUE THREAD

**Issue by srittau** [psf/black#2706]
Please consider the following un-blacked *stub* file:

```python
class Foo:
    x: int
    y: int

    a: int
    b: int

    def bar(self) -> int: ...
    def baz(self) -> int: ...
```

In this case, the empty line between attributes and methods is intentional as is the empty line between the attribute blocks. black 21.12b0 (no special config) changes this to:

```python
class Foo:
    x: int
    y: int

    a: int
    b: int
    def bar(self) -> int: ...
    def baz(self) -> int: ...
```

**Desired style**

I believe that black should keep one blank line between attributes and methods if there is at least one blank line in the source. This can aid readability for classes with many attributes/methods.

**Comment by Petar-Iliev** [comment]
I tried to reproduce this and black kept the blank line.
```
class Foo:
    x: int
    y: int

    a: int
    b: int

    def bar(self) -> int:
        pass

    def baz(self) -> int:
        pass
```

**Comment by JelleZijlstra** [comment]
@Petar-Iliev did you try with `--pyi`? I agree that we should keep this blank line even in stubs.

**Comment by Petar-Iliev** [comment]
@JelleZijlstra with `--pyi` it's removing the blank line
