### ISSUE TITLE
coloring to improve visibility

### ISSUE THREAD

**Issue by blankRiot96** [psf/black#2711]
**Is your feature request related to a problem? Please describe.**

It takes a bit of searching to find out how many files were reformatted and changed

**Describe the solution you'd like**

I think adding some simple coloring to the "x files reformatted, y files left unchanged" would be great, and also additionally leaving one line before "All done! ✨ 🍰 ✨" would be great too imo.

**Describe alternatives you've considered**

Adding some colons and such would help too, but I think adding some color would be better

**Additional context**
Here is an example of what I mean

![image](https://user-images.githubusercontent.com/77634274/146871370-0e3ad1d0-3d4b-4e7d-9445-016c8d99efa1.png)

**Comment by ichard26** [comment]
I'd prefer if we stuck to the blue we already use for other messages and then use it for both stats as IMO it looks weird having two different colours for similar stats, but other than that I'm accepting this enhancement. I like it @blankRiot96!

**Comment by blankRiot96** [comment]
> I'd prefer if we stuck to the blue we already use for other messages and then use it for both stats as IMO it looks weird having two different colours for similar stats, but other than that I'm accepting this enhancement. I like it @blankRiot96!

Thanks! Since you labelled it as a good first issue, I would love to work on it and make a PR. I have read the contributing guidelines too. If you don't mind, could you tell me where the output is handled in the src? 😓 
I have looked at <a href="https://github.com/psf/black/blob/main/src/black/__init__.py">__init__.py</a> and have understood that `click` is being used, which is great since I am familiar with it. And I am assuming the listing of reformatted files and the `All done!` message is being handled with `echo`
Was unable to find the output, but thanks again!

**Comment by MarcoGorelli** [comment]
I presume you'd want to modify

https://github.com/psf/black/blob/c5b458ef4ba1b6a62685461c6731f1775bee132b/src/black/report.py#L79-L104
