### ISSUE TITLE
Consider half-indents for `match`

### ISSUE THREAD

**Issue by amacfie** [psf/black#2713]
**Describe the style change**

A `match` statement uses an extra level of indentation compared to an `if` statement. In the pattern matching PEP, this is acknowledged as unfortunate but the following mitigation is [mentioned](https://www.python.org/dev/peps/pep-0622/#use-a-flat-indentation-scheme): "the horizontal space issue can be alleviated by allowing "half-indent" (i.e. two spaces instead of four) for match statements". Perhaps Black could adopt this convention.

**Examples in the current _Black_ style**

```python
match: expression
    case pattern_1:
        ...
    case pattern_2:
        ...
```

**Desired style**

```python
match: expression
  case pattern_1:
    ...
  case pattern_2:
    ...
```

**Comment by isidentical** [comment]
(not a black maintainer) But my personal opinion is multiple indentation types (1-space indent, 2-space indent, 4-space indent, etc.) should never be mixed in the same code. It makes the situation a lot trickier with code editors which do not have localized support for determining the outer indentation type. So if I press <enter> <tab> and type `case`, it will look very awkward compared to the surrounding `case` statements.

**Comment by JelleZijlstra** [comment]
Agree with @isidentical; I'd prefer for Black to stick to a single indentation type.

**Comment by felix-hilden** [comment]
I'd also prefer just to stick with a single indentation. But to add another reason, I'm not sure how well editors would deal with variable indents. My guess is that I'd have to start manually adjusting my tab strokes with hitting space a few times after, so this seems a bit awkward.
