### ISSUE TITLE
Dropping of empty lines within lists used for logical grouping

### ISSUE THREAD

**Issue by fmalina** [psf/black#2723]
**Describe the bug**

I have lists of urlpatterns or INSTALLED_APPS etc and use empty lines for logical grouping of items.
Black drops these empty lines as if they weren't meant to be there.

**To Reproduce**

For example, take this code grouping installed_apps into contrib, mine and external:

```python
INSTALLED_APPS = [
        'django.contrib.this',
        'django.contrib.that',
        'django.contrib.another',
        
        'my_app',
        'my_other_app',
        'another_app_of_mine',

        'external_non_contrib_app',
        'allauth',
        'ext_app3'
]
```

And run it with these arguments:

```sh
$ black file.py
```
Logical separation was lost.
```python
INSTALLED_APPS = [
        'django.contrib.this',
        'django.contrib.that',
        'django.contrib.another',
        'my_app',
        'my_other_app',
        'another_app_of_mine',
        'external_non_contrib_app',
        'allauth',
        'ext_app3',
]
```
**Expected behavior**

Keep empty lines within iterables that were clearly used as separators.

**Comment by felix-hilden** [comment]
Hi! Personally, I'm slightly against this. While I see your use case, would you suggest we keep empty lines for all lists? I'd prefer we clean those up, and as there isn't an easy way to tell when the grouping is logical, we shouldn't guess. In short I'd fall back to our "let's not take previous formatting into account" stance, although vertical space is one exception.

If you must have logical separation, then you could use a structure that actually reflects it! A 2D list or a dict of lists for instance.

**Comment by fmalina** [comment]
I run black on some fairly large codebases and from that experience I saw dropping empty lines in lists counterproductive as they always carried meaning and were placed strategically, this was a django so lists of urlpatterns and installed apps are mostly affected. Dictionaries and tuples would be similarly affected I'd imagine, but weren't present in my sample. Deeper structures aren't an option in these places, but comment in the blank line naming the group could be an option

**Comment by felix-hilden** [comment]
Comments seem preferable to empty spaces, to me at least. To think that we shouldn't fix

```python
[
    1,
    2,

    3,
]
```

just because it *might* be intentional seems off.

**Comment by LLyaudet** [comment]
I agree that the best choice here is to add a comment when the empty line carries meaning.

**Comment by fmalina** [comment]
Will people bother? They'll look at the changes, think my list/tuple/dict is exploded, black removed my newlines used for groupings, black is sh*t, let's not adopt it, and this whole "let's have a deterministic formatting"?crusade is over

**Comment by fmalina** [comment]
Maybe I am wrong, but less IS more

**Comment by felix-hilden** [comment]
You are right, less is elegant, and that's what we're aiming for. Not less formatting, but less special cases and guessing. So are you proposing that we keep all newlines in collections and calls, or simply in some limited cases? And if only in some cases, how would we determine those cases?

**Comment by JelleZijlstra** [comment]
I'm inclined to close this and keep the current behavior. We should minimize dependence on existing formatting.

**Comment by fmalina** [comment]
I don't have an example where in existing project black would do a good job by removing a newline in existing exploded iterable

**Comment by felix-hilden** [comment]
I think we'll close this because:

- Comments are preferable to empty lines, because they actually explain why the grouping is happening. Not bothering isn't really a great reason.
- We don't like taking previous formatting into account.

If you think there's a reasonable special case, feel free to present it and let's think about how we could recognise it.

**Comment by pyzenberg** [comment]
How this:
 ```python
INSTALLED_APPS = [
    "drf_yasg",  # should be first to prevent thread lock issues
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.gis",
    "django.contrib.postgres",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.routable_page",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",
    "versatileimagefield",
    "mptt",
    "ckeditor",
    "ckeditor_uploader",
    "jalali_date",
    "qr_code",
    "logentry_admin",
    "rest_framework_tracking",
    "modelcluster",
    "taggit",
    "crispy_forms",
    "django_extensions",
    "constance.backends.database",
    "constance",
    "fcm_django",
    "import_export",
    "adminsortable",
    "market_auth",
    "market_structure",
    "market_gis",
    "market_catalog",
    "market_order",
    "market_callcenter",
    "market_dashboard",
    "market_mag",
    "market_hr",
    "market_util",
]
```

is more readable than this?

```python
INSTALLED_APPS = [
    # should be first to prevent thread lock issues
    "drf_yasg",

    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.gis",
    "django.contrib.postgres",

    # drf apps
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",

    # wagtail apps
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.routable_page",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",

    # 3rd-party apps
    "versatileimagefield",
    "mptt",
    "ckeditor",
    "ckeditor_uploader",
    "jalali_date",
    "qr_code",
    "logentry_admin",
    "rest_framework_tracking",
    "modelcluster",
    "taggit",
    "crispy_forms",
    "django_extensions",
    "constance.backends.database",
    "constance",
    "fcm_django",
    "import_export",
    "adminsortable",

    # project apps
    "market_auth",
    "market_structure",
    "market_gis",
    "market_catalog",
    "market_order",
    "market_callcenter",
    "market_dashboard",
    "market_mag",
    "market_hr",
    "market_util",
]
```

**Comment by LLyaudet** [comment]
@pyzenberg 
Maybe this is more readable :

```
INSTALLED_APPS = [
    # ----------------------------------------------------------
    # should be first to prevent thread lock issues
    "drf_yasg",
    # ----------------------------------------------------------
    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.gis",
    "django.contrib.postgres",
    # ----------------------------------------------------------
    # drf apps
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    # ----------------------------------------------------------
    # wagtail apps
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.routable_page",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",
    # ----------------------------------------------------------
    # 3rd-party apps
    "versatileimagefield",
    "mptt",
    "ckeditor",
    "ckeditor_uploader",
    "jalali_date",
    "qr_code",
    "logentry_admin",
    "rest_framework_tracking",
    "modelcluster",
    "taggit",
    "crispy_forms",
    "django_extensions",
    "constance.backends.database",
    "constance",
    "fcm_django",
    "import_export",
    "adminsortable",
    # ----------------------------------------------------------
    # project apps
    "market_auth",
    "market_structure",
    "market_gis",
    "market_catalog",
    "market_order",
    "market_callcenter",
    "market_dashboard",
    "market_mag",
    "market_hr",
    "market_util",
]
```

I just added this line
`     # ----------------------------------------------------------`
in your empty lines,
since you already had comments to tell what is about each of your blocks of code.

I agree that your example is readable but it has both comments and empty lines.
And the good point to tell others why you structure your code this way is with comments.
I do not think that my example is less readable, but you may not like it.
You can try other ways to "explicit empty lines"
Black must do some choices and I sincerely think that our suggestions are the best choice given all the problems needed to solve.

**Comment by pyzenberg** [comment]
Looks a little ugly to me. Probably It's all about sensitiveness of my eyes. I ended up using the following style:

```python
    # should be first to prevent thread lock issues
    "drf_yasg",
    #
    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.gis",
    "django.contrib.postgres",
    #
    # drf apps
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
```
