### ISSUE TITLE
Too much whitespace when last or only param to a function/method call is a payload dict func({...})

### ISSUE THREAD

**Issue by fmalina** [psf/black#2724]
**Describe the style change**

I'd like black use more terse formatting when it comes across dictionaries as params in function and method calls. Here's a django function based view example, function calls accepting payload dicts end up looking wrong

**Example in the current _Black_ style**

```python
def view(request):
    ...
    return render(
        request,
        'places/detail.html',
        {
            'place': place,
            'opening_times': times,
            'photos': photos,
            'staff': staff,
            'town': town,
            'segment': sector,
        },
    )

```

**Desired style**

```python
def view(request):
    ...
    return render(request, 'places/detail.html', {
        'place': place,
        'opening_times': times,
        'photos': photos,
        'staff': staff,
        'town': town,
        'segment': sector
    })
```

**Comment by felix-hilden** [comment]
Hi! How would you suggest we format calls with an argument after an exploded collection? I'd argue it should take the current form. But you could make a case for the suggested formatting only if the last argument is exploded.

**Comment by fmalina** [comment]
I can't imagine the former without an example, but I would agree with the latter

**Comment by felix-hilden** [comment]
This I would expect to stay as it is.

```python
def view(request):
    ...
    return render(
        request,
        'places/detail.html',
        {...},
        some_other_argument,  # after collection to be exploded
    )
```

I'm open to making an exception for the last argument, but I'm quite happy with our current formatting as well. Thoughts by others?

**Comment by fmalina** [comment]
While in theory people can write that and in that case your formatting would look okay, I don't remember ever seeing code like that, only ever saw dict to be the last or only argument, extremely rarely two of the trailing arguments would be dicts in merging functions and there still I would prefer my formatting

**Comment by fmalina** [comment]
Even theoretically I still prefer, being more succint
```python
def view(request):
    ...
    return render(request, 'places/detail.html', {
         ...
    }, some_other_argument)
```

**Comment by fmalina** [comment]
I have just had a super rare case like you show above where dictionary argument was followed by another and I went with current black style formatting too

**Comment by felix-hilden** [comment]
I think this is sufficiently similar to #1811 so that we can close this. I'll include your case in the discussion as well. Hopefully we'll get to resolving it one way or the other!
