### ISSUE TITLE
Mention WingIDE integration with Black.

### ISSUE THREAD

**Issue by SteveBarnes-BH** [psf/black#2731]
**Is this related to a problem? Please describe.**

The newer versions of the WingIDE, (8.x) have an option to use automatic formatting with black. The current documentation only mentions manually running Black from within Wing by executing a command line and linking that to a key binding.

**Describe the solution you'd like**
Mention the mechanism for enabling black auto-formatting in Wing IDE.

In docs/integrations/editors.md add that - for Wing IDE versions >8 you can enable Black formatting on a line by line or file before save basis as detailed at https://wingware.com/doc/preferences/index 

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/88222167/147554436-7b70888b-9b60-41c2-ac49-92935f1e0fa0.png)
Project Preferences in Wing IDE 8.

**Comment by ichard26** [comment]
Awesome! Should hopefully make for an easy first-time contributor friendly issue, thank you for this!
