### ISSUE TITLE
pre-commit hook fails to format code with the Structural Pattern Matching

### ISSUE THREAD

**Issue by CelestialGuru** [psf/black#2732]
**Describe the bug**

pre-commit hook fails to format code with the Structural Pattern Matching [PEP 0622](https://www.python.org/dev/peps/pep-0622/).

**To Reproduce**

## Files
`.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
```

`pyproject.toml`:
```toml
[tool.black]
target-version = ["py310"]
```

`file_with_310_features.py`
```python
match "this":
    case "that":
        print(1  +  2)
```

`file_without_310_features.py`
```python
print(1  +  2)
```

## Setup
```sh
pip install black==21.12b0 pre-commit
git init
git add .
pre-commit install
```

And run it with these arguments:

```sh
pre-commit run black --all-files
```

The resulting error is:

> black....................................................................Failed
> - hook id: black
> - exit code: 123
> - files were modified by this hook
>
> reformatted file_without_310_features.py
> error: cannot format file_with_310_features.py: cannot use --safe with this file; failed to parse source file.
> Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
> 1 file reformatted, 1 file failed to reformat.

**Expected behavior**

Pre-commit hooks should format both `file_with_310_features.py` and `file_without_310_features.py`; they are valid python 3.10.

**Environment**

- Black's version: 21.12b0
- OS and Python version: Windows 10, Python 3.10.0

**FYI**
I can format the file with Python 3.10 features just fine:
```sh
black file_with_310_features.py
```

> reformatted file_with_310_features.py
> All done! ✨ 🍰 ✨
> 1 file reformatted,

**Comment by isidentical** [comment]
The error is due to the version of the python environment, not black. You can configure `default_language_version` to `3.10` though, which should make this work.

**Comment by ichard26** [comment]
I'll also note that this situation should be less confusing with the recent merge of GH-2786 which hints at checking your runtime Python version to make sure it supports the syntax you're throwing Black at.

**Comment by JelleZijlstra** [comment]
I don't think there's anything for us to do here. Let us know if you have further questions.
