### ISSUE TITLE
Expected Line break to be put before logical operators, even when some parentheses are added

### ISSUE THREAD

**Issue by nicolas-chan-42** [psf/black#2738]
**Black v21.12b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEZAMFdAD2IimZxl1N_Wg09_vW0J5oX86BxYk52b4QcHSVojlne7ETc3w2NvD8sp0Ds3locx7TRUjlMoDusdtRzPHTyk3k_9Gy1XhJR6mjiX7ywZlcTmUFdIh_V7MTu8aTO7o8NGBJ6hdUVVoEldJDMH5JAloRPzPdYRyU9c7f3TT0CLIM1JMfO3DgioBmm4hILeiv5rr6DqEdN3COsYlMrgY2EG02CKA3hmckRawmhJzrStJkwMVDi-Vcx2stMT6PaR_U03AAAAAAAjb3Pdhw59ZkAAd0BmgIAADIn7IGxxGf7AgAAAAAEWVo=)

## Options

`--line-length=88`
`--safe`

## Input

```python
# Long if-statement with 2 parentheses.
if (currency == "JPY" and 100_000 <= x <= 500_000) or (currency == "USD" and 1_000 <= x <= 5_000):
    print("Line breaks AFTER Logical operator `or`.")
```

## Output

```python
# Long if-statement with 2 parentheses.
if (currency == "JPY" and 100_000 <= x <= 500_000) or (
    currency == "USD" and 1_000 <= x <= 5_000
):
    print("Line breaks AFTER Logical operator `or`.")

```

## Expected

The logical operator (`or` in this case) would be put in the front of the second line of conditionals after formatting.
For example,

```python
# Long if-statement with 2 parentheses.
if (
    (currency == "JPY" and 100_000 <= x <= 500_000)
    or (currency == "USD" and 1_000 <= x <= 5_000)
):
    print("Line breaks AFTER Logical operator `or`.")

```

**Comment by nicolas-chan-42** [comment]
The following are two examples to supplement my original example for a more comprehensive look of how Black currently handles long if-statements with parentheses added by the programmer to group related conditions.

**Black v21.12b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AI-AOBdAD2IimZxl1N_Wg09_vW0J5oX86BxYk52b4QcHSVojlne7ETc3w2NvD8sp0Ds3loNZT1v0OPnU8FprHximG_X22k7Y--1fCB-eXPzSJQ_V7FJLwj2konRbAclV7_e-uMDkQemu52iV-PO1oT_5OlSUWlQPgtr6Zh9VxuNOSxMGp17TUHG7pnffhk6pmUwiY7L5zFAvTJxKTx690l7-RQSAxM1LJIrrXEAA-p6S2aBZUtkoZaTJur5b-dzUu0yc5Hm1iACxpheVTOgUM1DMZAkonAitM7ky8ySrk6jf751B9wAAGLHdmvLIpivAAH8Ab8EAAAf0n3escRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
# Long if-statement with 2 parentheses, with some long names.
if (currency == "JPY" and 100_000 <= somelonglonglonglonglonglonglonglonglonglonglongname <= 500_000) or (currency == "USD" and 1_000 <= somelonglonglonglonglonglonglonglonglonglonglongname <= 5_000):
    pass

# When there are 3 groups of parentheses.
if (currency == "JPY" and 100_000 <= x <= 500_000) or (currency == "USD" and 1_000 <= x <= 5_000) or (currency == "EUR" and 1_000 <= x <= 5_000):
    pass
```

## Output

```python
# Long if-statement with 2 parentheses, with some long names.
if (
    currency == "JPY"
    and 100_000 <= somelonglonglonglonglonglonglonglonglonglonglongname <= 500_000
) or (
    currency == "USD"
    and 1_000 <= somelonglonglonglonglonglonglonglonglonglonglongname <= 5_000
):
    pass

# When there are 3 groups of parentheses.
if (
    (currency == "JPY" and 100_000 <= x <= 500_000)
    or (currency == "USD" and 1_000 <= x <= 5_000)
    or (currency == "EUR" and 1_000 <= x <= 5_000)
):
    pass

```

**Comment by felix-hilden** [comment]
Hi, this is very similar to #2156 and other issues linked to it. I'll close this and let's continue discussion there!
