### ISSUE TITLE
Allow defining custom python magics for Jupyter support

### ISSUE THREAD

**Issue by mgmarino** [psf/black#2742]
Recent updates of black have introduced out-of-the-box support for Jupyter Notebooks, which is extremely helpful.  As of #2630 only *known* python cell magics are processed (see e.g. [here](https://github.com/psf/black/blob/8a84bebcfcabddfd5b82a8cff0b830a745999b6c/src/black/handle_ipynb_magics.py#L40)), which certainly makes sense.  We have the use case that we have several custom python cell magics that we would also like to process.  

This request is to allow configuration to support additional (user-defined) magics.  

Possible solutions:

I am aware that we could certainly call black from python directly and programmatically update `PYTHON_CELL_MAGICS` to include our custom python magics.  However, I'm not keen on doing this because it would depend on implementation details within black.   If this would be the preferred solution, then I would suggest to at least add a function that could be called to register the additional magics.

Another possibility would be to add a configuration flag/option (i.e. in `pyproject.toml`/CLI) that would allow the input of a list of additional python cell magic names.  (Using an environment variable would be a similar option, but I don't see any other place that this is done, other than with e.g. `XDG_CACHE_HOME` which is a more "global" configuration variable.)  This is likely my preferred solution, but, given that black makes a concerted effort *to avoid* configuration options, I could understand why this would not be acceptable.

Thanks in advance for any input/consideration.

**Comment by MarcoGorelli** [comment]
Hi @mgmarino ,

That's a good suggestion, thanks!

In nbQA I have such a configuration option ([cell magics](https://nbqa.readthedocs.io/en/latest/configuration.html#cell-magics)), but I left it out of the PR to `black` so as to not over-compliate things straight away.

Let's hear from the `black` maintainers if such a flag / configuration option would be welcome in `black` as well

> which is extremely helpful.

Glad to see this is useful!

**Comment by felix-hilden** [comment]
Hi, thanks for submitting the issue! With every request like this I become more in favor of simplifying Black's responsibility and having a suite of plugins be implemented in other repositories as discussed in #2721.

However, given that we already have notebook support, this configuration would be really good. Perhaps named `python_cell_magics` like in our source?

**Comment by MarcoGorelli** [comment]
@mgmarino do you want to submit a PR? [Here](https://github.com/psf/black/blob/main/CONTRIBUTING.md)'s the contributing guide if so

**Comment by mgmarino** [comment]
Sure, I'm happy to.  I'll have a look in the next few days.

**Comment by ankostis** [comment]
(Apologies for necroposting)
Does this feature support double-% whole cell magics only?

What about only single ones?
Adding `# fmt: skip` at the end of a line means that unmodified text does not work.



(Had to read the code of this PR to find out this, not obvious from the help-string or the changelog)
