### ISSUE TITLE
Support for hanging indents

### ISSUE THREAD

**Issue by fmalina** [psf/black#2743]
**Describe the style change**

Support for hanging indents

**Examples in the current _Black_ style**

```python
if (
    is_interesting(attempt)
    and len(attempt.record) <= len(source.record)
):
    source = attempt
```

**Desired style**

```python
    if (is_interesting(attempt)
        and len(attempt.record) <= len(source.record)):
        source = attempt
```

This might not be the best example and in many cases I prefer blacks exploded syntax and in many I prefer a hanging indent, having run black on a large codebase, almost half the time I did prefer syntax suggested over my own hanging indents. So just wanted to open a discussion to help formalise the rules. Apologies if this was already discussed to death before because I feel it should but I've not found any trace.

**Comment by felix-hilden** [comment]
Thanks for opening the discussion, but this is *very* unlikely to change. We aim for consistency above all. So multiple hanging indents would be a huge waste of space and very hard to read:

```python
long_variable = longer_call_name(another_long_call(some,
                                                   params),
                                 outer_param)
# compared to
long_variable = longer_call_name(
    another_long_call(
        some,
        params,
    ),
    outer_param,
)
```

**Comment by fmalina** [comment]
Yes, this is exactly it. One makes it better, multiple ones make it worse. Finding the pattern is why I opened the ticket. I have a feeling there is more

**Comment by felix-hilden** [comment]
I at least would argue that the style is worse overall. Having different levels of indentation for similar content is harder to track.

```python
some_call(and,
          some,
          parameters)
another____call(and,
                different,
                parameters)
lst = [1,
       2,
       3]

# vs

some_call(
    and,
    some,
    parameters,
)
another____call(
    and,
    different,
    parameters,
)
lst = [
    1,
    2,
    3,
]
```

And if I were to add another item my git diff would be bigger, because the last item would need to be changed to end in a comma and the parenthesis moved.

```
    [1,
-    2]
+    2,
+    3]

# vs

    [
        1,
        2,
+       3,
    ]
```
