### ISSUE TITLE
Multiline f-strings aren't formatted correctly

### ISSUE THREAD

**Issue by Alphasite** [psf/black#2747]
**Describe the bug**

When you have multiple f-strings (I suspect without a `+` between them) then when it reformats them it
will just remove the new lines without merging the strings into a single compound string, e.g. `f"{1}" f" {2}"` 
rather than `f"{1} {2}"`

**To Reproduce**

```python
c.run(
    f"docker login {self.hostname} "
    f"--username {self.username} "
    f"--password {self.password}",
)
```

For example, take this code:

```python
this = "code"
```

And run it with these arguments:

```sh
$ poetry run black src
```

The resulting error is:

```python
         c.run(
-            f"docker login {self.hostname} "
-            f"--username {self.username} "
-            f"--password {self.password}",
+            f"docker login {self.hostname} " f"--username {self.username} " f"--password {self.password}",
         )
```

**Expected behavior**

```python
         c.run(
-            f"docker login {self.hostname} "
-            f"--username {self.username} "
-            f"--password {self.password}",
+            f"docker login {self.hostname} --username {self.username} --password {self.password}",
         )
```

**Environment**

- Black's version: black, 21.12b0 (compiled: no)
- OS and Python version: Mac/Python 3.9

**Additional context**

**Comment by felix-hilden** [comment]
I believe this is fixed by using `black --experimental-string-processing`, which will soon become standard functionality.

```sh
$ black -c "f\"a\" f\"b\""
f"a" f"b"

$ black -c "f\"a\" f\"b\"" --experimental-string-processing
f"ab"
```

**Comment by Alphasite** [comment]
Oh thank you!
