### ISSUE TITLE
Should `await` automatically manage parentheses like `return`?

### ISSUE THREAD

**Issue by ambv** [psf/black#275]
On a first glance, it would be better. On another though, `await` is an expression which can potentially complicate formattings that are now rather simple.

Alternatively, `await` should be ignored by an existing bracket pair for purposes of splitting on delimiters, enabling for example fluent interfaces.

**Comment by JelleZijlstra** [comment]
Concrete example:
```
% black -c 'return (a)'   
return a
% black -c 'await (a)' 
await (a)
```
