### ISSUE TITLE
GitHub no longer supports unauthenticated installation protocol

### ISSUE THREAD

**Issue by jlazar17** [psf/black#2764]
The command for installing via pip no longer works due to changes in security protocols.

Changing the URL to an HTTPS address fixed this issue for me, i.e. `pip install git+git://github.com/psf/black`->pip install git+https://github.com/psf/black

**Comment by Gobot1234** [comment]
See #2761, this has already been fixed

**Comment by felix-hilden** [comment]
#2761 Might have already solved this!

**Comment by ichard26** [comment]
This has been fixed on main very very recently by PR #2761, if you're referencing the stable documentation, well, it won't see changes until we do another release which we're targetting for the end of the month.

**Comment by ichard26** [comment]
Wait no, there's also the URL in the documentation that is still outdated, gahhhhhh https://github.com/psf/black/blob/main/docs/getting_started.md#installation

**Comment by felix-hilden** [comment]
Yup just found the same 😆 So we'll have to apply the same fix to that as well!
