### ISSUE TITLE
Cannot use `--safe` with parenthesized with statement

### ISSUE THREAD

**Issue by spagh-eddie** [psf/black#2768]
**To Reproduce**

With this as `test.py`,
```python
with (
open('a') as f,
open('b') as g,
): pass
```
Black with fail with `--safe` (the default) but pass with `--fast`
```console
% black -t py310 test.py
error: cannot format test.py: cannot use --safe with this file; failed to parse source file.
Oh no! 💥 💔 💥
1 file failed to reformat.

% black -t py310 --fast test.py
reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.

% cat test.py 
with (
    open("a") as f,
    open("b") as g,
):
    pass
```

Interestingly, after it has been formatted it does not fail
```console
% black -t py310 test.py  
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Expected behavior**

`--safe` passes if the output of `--fast` is sane 

**Environment**

```console
% black --version
black, 21.12b0 (compiled: no)
```

**Comment by ichard26** [comment]
What version of Python are you running Black under? `Cannot use --safe ...` usually shows up when the underlying Python implementation doesn't support the file's syntax (strictly speaking, black depends on the built-in ast module).

**Comment by spagh-eddie** [comment]
> What version of Python are you running Black under?

I was using python3.7. I have tried again using 3.10 and there is no issue. My bad! I guess I was thrown off by the `--target` option.

**Comment by JelleZijlstra** [comment]
Maybe we should have a warning of some sort for this case.
