### ISSUE TITLE
"INTERNAL ERROR" on minimal python file

### ISSUE THREAD

**Issue by DavidHowlett** [psf/black#2771]
**Describe the bug**

I created a file with "# fmt: off" and no matching "# fmt: on" and black suffered an internal error. 

**To Reproduce**

Run black on this file:

```python
def foo():
    # fmt: off
    pass

def bar():
    pass
```

Example run on my computer:

```
(base) ➜  ~ cat demo.py
def foo():
    # fmt: off
    pass

def bar():
    pass
(base) ➜  ~ black demo.py
error: cannot format demo.py: INTERNAL ERROR: Black produced code that is not equivalent to the source on pass 1.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/6f/1jnzmq1d0_v9qyk4pbr96cmc0000gn/T/blk_r87c8kh7.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**

I believe the correct behaviour is for black to not format the rest of the file after the marker.

**Environment**

- Black's version: black, 21.12b0 (compiled: no)
- OS and Python version: MacOS 12.1 Python 3.9.7

**Additional context**

I discovered this accidentally while applying black to the codebase I am working on. Thanks for including a link to where to report the bug.

**Comment by felix-hilden** [comment]
Thanks for reporting. We do require a `fmt: on` as well, but your rationale is fair. And at the very least we should not output an internal error, but rather "fmt: on not found" or something akin to that. We're tracking these in #569 and #1817, so I'll close this for housekeeping.

**Comment by DavidHowlett** [comment]
Thanks for the fast reply. Sorry about the duplicate.

**Comment by DavidHowlett** [comment]
Interestingly I can use "fmt: on" without a "fmt:off". Most of the time it works as expected and does not crash.
