### ISSUE TITLE
broken down long assignment is reverted back to failing E501

### ISSUE THREAD

**Issue by ryanrhee** [psf/black#2780]
**Describe the bug**

Long assignment with parens for newline is changed to be a single line, which then violate E501.

**To Reproduce**

For example, take this code:

```python
class Foo:
    def __init__(self, frobnicate_initialization_vectors):
        self.frobnicate_initialization_vectors = (
            frobnicate_initialization_vectors
        )
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting file violates E501:

```python
class Foo:
    def __init__(self, frobnicate_initialization_vectors):
        self.frobnicate_initialization_vectors = frobnicate_initialization_vectors
```

> E501 line too long (82 > 79 characters)

**Expected behavior**

Parentheses are not removed, and the line break is kept, so that E501 is not violated.

**Environment**

- Black's version: `black, 21.12b0 (compiled: no)`
- OS and Python version: macOS 12.1 / python3.9.9

**Additional context**

**Comment by felix-hilden** [comment]
Hi! Black's default line length is 88, try `black -l 80`.

**Comment by ryanrhee** [comment]
thanks!
