### ISSUE TITLE
Complex decorators break safe mode

### ISSUE THREAD

**Issue by emfdavid** [psf/black#2782]
Using decorator syntax with a chained function call breaks the AST validation in safe mode.
This is a pattern for [prometheus client](https://github.com/prometheus/client_python#three-step-demo)

Use black [playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AG-AOddAD2IimZxl1N_WlkPinBFoR3Cl8B_4kpdkic7jS1dbrWRqxezQBIp0NHTWOT5p6HLb5MYiZOZMQhBUo9v9HGxxTDZ6Jcf2XsfLszWV0uR1KuWpiBNz2CSAba_UuLYf64DaLxWUtyLz-FBC7i3ois4nMyISUR1pfMJeUpXrWj7PrIQCvZD5y3DlweYKnGOfqiitLs-A9iannW5V6DZIwd7SWKbVC-0_unHTkPxkTATwS2_n6innP-GvKr9ZoK9luBdOeEkBN1AHfQgHJL6m5ie9wXZ4DUj9gRP5l7VBHv6Qtp1TSz_mjI7VgAAaPyaf3_P58cAAYMCvwMAAF4B5maxxGf7AgAAAAAEWVo=) repro case

<img width="1435" alt="Screen Shot 2022-01-18 at 6 28 09 PM" src="https://user-images.githubusercontent.com/84335963/150035137-e9be53a7-c66c-4eb3-a647-61f059369f46.png">

If I comment out the chained labels - it works.
<img width="1431" alt="Screen Shot 2022-01-18 at 6 30 16 PM" src="https://user-images.githubusercontent.com/84335963/150035344-e1e448bb-91a4-4436-a1b3-a8807e94ebf7.png">

Currently my best work around is to ignore the files using this syntax in my config and run black manually with fast for those files.

**Comment by JelleZijlstra** [comment]
We may never have properly added support for https://www.python.org/dev/peps/pep-0614/.

**Comment by isidentical** [comment]
AFAIK the PEP 614 support is there:
https://github.com/psf/black/blob/98db4abc21477cbd247c8fbd4cf9e8d1cf61ca0f/src/blib2to3/Grammar.txt#L15

This seems like a problem with Black Playground, since they are still using Python 3.8. 

@emfdavid what is the version of the python interpreter you are running the black with?

**Comment by emfdavid** [comment]
Excellent catch @isidentical 
I set our commit hook to use py37 as the lowest level supported and didn't think twice about it when I could repro the issue in playground.
Are issues with ast validation rare enough that it would be helpful to add `try checking your python version?` to the error message?

**Comment by JelleZijlstra** [comment]
@emfdavid good idea, do you want to submit a PR?

**Comment by isidentical** [comment]
This has been now fixed on the playground as well!

**Comment by emfdavid** [comment]
@JelleZijlstra https://github.com/psf/black/pull/2786
