### ISSUE TITLE
Blank lines at top level code in stubs should be the same inside an if

### ISSUE THREAD

**Issue by hauntsaninja** [psf/black#2784]
**Describe the style change**

Blank lines should be treated the same in top-level code under an if-statement as in top-level code proper

**Examples in the current _Black_ style**

```python
class A:
    def f(self): ...

class B:
    def f(self): ...

if sys.version_info >= (3, 8):
    class C:
        def f(self): ...
    class D:
        def f(self): ...
```

**Desired style**

```python
class A:
    def f(self): ...

class B:
    def f(self): ...

if sys.version_info >= (3, 8):
    class C:
        def f(self): ...

    class D:
        def f(self): ...
```

**Additional context**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AD8AIRdAD2IimZxl1N_WlXnON2nzNApqtITJJee2SMStFF7KJQ8b5tLWLTPF97YwrFIbsO2CJkraBrsaGIFFxZyS8cW-bxi-KzgtfNZt0bUoUnR71oEBfdQhSZgYLHjXKPdI-W9GBft7c-sf-zudh3LWYfAsj7EDjUuebHXI_AiVpD5OuhIJSCPsAC6Ox7BianITQABoAH9AQAAzkjnkrHEZ_sCAAAAAARZWg==)

Similar to / discussed in https://github.com/psf/black/issues/2783

**Comment by JelleZijlstra** [comment]
Let's do it.
