### ISSUE TITLE
Stub files: style shouldn't change when inside "if" statements

### ISSUE THREAD

**Issue by Akuli** [psf/black#2785]
**Describe the style change**

In stub files (`.pyi`), do not add/remove blank lines depending on whether code is under `if` statements.

**Examples in the current _Black_ style**

```python
class A:
    def foo(self) -> None: ...

class B:
    def foo(self) -> None: ...

if sys.platform == "linux":
    class A:
        def foo(self) -> None: ...
    class B:
        def foo(self) -> None: ...
```

**Desired style**

```python
class A:
    def foo(self) -> None: ...

class B:
    def foo(self) -> None: ...

if sys.platform == "linux":
    class A:
        def foo(self) -> None: ...

    class B:
        def foo(self) -> None: ...
```

**Additional context**

The current behavior makes many typeshed PRs unreadable. When reviewing PRs like this, I usually have to recreate the changes of the PR myself and diff my results against what's in the PR.

**Comment by hauntsaninja** [comment]
:-) I went through the exact same steps as you and filed https://github.com/psf/black/issues/2784 an hour ago
