### ISSUE TITLE
Add --ignore-line-lenght or something like this

### ISSUE THREAD

**Issue by PerchunPak** [psf/black#2788]
**Describe the solution you'd like**

I think, black really missing some customisation, which will be really usefull.

Just add config or/and command line function which will disable this style formatting:
```py
print("Really long text")
```
To
```py
print(
    "Really long text"
)
```

**Describe alternatives you've considered**

The best will be split all checks to codes, and add `--disable=CODE`, but feature request doesn't requesting this.

**Comment by felix-hilden** [comment]
Thanks for the suggestion, and I hate to be dismissive 😄 but this is exactly the [antithesis](https://black.readthedocs.io/en/stable/) of Black. We won't add such an option.

**Comment by ichard26** [comment]
Also note you could use a unnecessaily high line length like `--line-length 10000` :p

**Comment by PerchunPak** [comment]
```py
func(
    param1="123", 
    param2="321",
    param3="something"
)
```
Anyway, after formatting will be
```py
func(param1="123", param2="321", param3="something")
```
