### ISSUE TITLE
Primer deprecation plan

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#2821]
I removed black-primer from CI in #2809 because it was causing annoying and useless CI failures, but kept the code around to avoid unnecessary changes around the stable release. I'd like to keep it around for at least one release that marks it as formally deprecated.

How long should we keep it? Is there any reason to keep it around for longer?

Also, removing the primer tests lost us some platform coverage, because black-primer used to run on lots of OS and Python version combinations and diff-shades doesn't. I'm not too convinced that was helpful, because we already run our unit tests on lots of configurations, but if we wanted we could add back a bigger test matrix.

**Comment by felix-hilden** [comment]
Can't think of a reason. A one-release deprecation sounds good, and git'll have the code in store.

**Comment by cooperlees** [comment]
I’ll take this and move it to cooperlees/black-primer after the release and if people want it they can install from there …
