### ISSUE TITLE
Lone comprehensions without additional indentation

### ISSUE THREAD

**Issue by francois-rozet** [psf/black#2830]
**Describe the style change**

Comprehensions that are alone within a call (or similar) would be left  without indentation.

> This change can be considered as consistency breaking, so I would not be surprised if it was rejected.

**Examples in the current _Black_ style**

```python
something(
    [
        a,
        b,
        c,
    ]
)

[
     [
        a,
        b,
        c,
    ]
]

np.stack(
    [
        np.arange(0, i)
        for i in range(0, 666)
        if isprime(i)
    ]
)
```

**Desired style**

```python
something([
    a,
    b,
    c,
])

[[
    a,
    b,
    c,
]]

np.stack([
    np.arange(0, i)
    for i in range(0, 666)
    if isprime(i)
])
```

**Additional context**

A lot of functions take a single iterable as input, like `join`, `list.extend`, `dict.update`, `numpy.stack`, ... For those, indenting the argument when it is a comprehension makes the code less readable IMO.

A good example is creating 2d NumPy arrays:

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
```

becomes, after Black auto-format,

```python
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)
```

Another argument in favor of this change is that switching from a comprehension to a generator changes dramatically the formatting but not the meaning. For instance,

```python
join([
    formating_function_with_a_very_long_name(i)
    for i in range(123456789)
    if isprime(i)
    if isperfect(i)
])
```

and

```python
join(
    formating_function_with_a_very_long_name(i)
    for i in range(123456789)
    if isprime(i)
    if isperfect(i)
)
```

are formatted differently, even though they are quite similar semantically.

**Comment by felix-hilden** [comment]
We've discussed this in #1811, so I'll close this as a duplicate! But do point out if anything you suggest here isn't covered. Most of it should be.

**Comment by francois-rozet** [comment]
Thanks! I didn't know what keywords to look for.
