### ISSUE TITLE
Ignore __pypackages__ directory contents

### ISSUE THREAD

**Issue by cachitas** [psf/black#2834]
**Describe the bug**

When using [PDM](https://pdm.fming.dev/), `black` does not ignore `__pypackages__` directory contents.

**To Reproduce**

Run `pdm run black .`

**Expected behavior**

`black` should reformat only project files.

**Environment**

- Black's version: 22.1.0
- PDM version: 1.12.6
- OS and Python version: Ubuntu 21.10 with Python 3.10.1

**Comment by felix-hilden** [comment]
Since we already ignore venvs and a bunch of other stuff by default, I think this is a reasonable ask.

**Comment by cachitas** [comment]
Just noticed this is partly my fault.
I had the directory in my `.gitignore` but was using `exclude` in my `[tool.black]` section in `pyproject.toml`. Using `extend-exclude` as documented fixed it.

**Comment by JelleZijlstra** [comment]
Then my proposed fix wouldn't have helped you either :). But it's still a reasonable idea to exclude the directory by default.
