### ISSUE TITLE
Output claims the configuration came from project root (filesystem root) when in reality it was user-level config.

### ISSUE THREAD

**Issue by ichard26** [psf/black#2850]
**Describe the bug**

The verbose would claim that the filesystem root was identified as the project root (this is correct) and the configuration file came from `/pyproject.toml` (this is false). 

**To Reproduce**

- Create a test file in a directory where is no pyproject.toml present (up the filesystem root)
- Format it with Black with `--verbose`
- Create a [user level config file](https://black.readthedocs.io/en/latest/usage_and_configuration/the_basics.html#where-black-looks-for-the-file) and configure line length to be something very small
- Reformat using the same command and observe the wrong output

```console
❯ black test.py --check -v
Identified `/` as project root containing a file system root.
Sources to be formatted: "home/ichard26/programming/oss/test.py"
test.py already well formatted, good job.

All done! ✨ 🍰 ✨
1 file would be left unchanged.

❯ echo "[tool.black]
  line-length = 10" > ~/.config/black

❯ black test.py --check -v
Identified `/` as project root containing a file system root.
Sources to be formatted: "home/ichard26/programming/oss/test.py"
Using configuration from project root.
would reformat test.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```

**Expected behavior**

That the output would report either it came from user level configuration or at least not claim it was project configuration 'cause it's not.

**Environment**

- Black's version: 22.1.0 and d038a24ca200da9dacc1dcb05090c9e5b45b7869
- OS and Python version: CPython 3.8.5 under Ubuntu 20.04.03 LTS

**Additional context**

This made it _very_ confusing to debug an unrelated test suite issue :)

cc @Shivansh-007

**Comment by Shivansh-007** [comment]
I would look into this 👍🏻
