### ISSUE TITLE
Use one line if statement if the line is short enough

### ISSUE THREAD

**Issue by thedemons** [psf/black#2856]
**Describe the style change**
Black will format any one-line if statements to multiple lines, but that's ugly if the if statement is too short.

It can look better if Black would format one-line if statements only if the statement is long enough.

**Examples in the current _Black_ style**

```python
if match:
    return match
```

**Desired style**

```python
if match: return match
```

**Additional context**
I understand that I can disable the format style for some specific lines. But using `# fmt: off` is just not worth it.
```python
# this is worse than before
# fmt: off
if match: return match
# fmt: on
```

**Comment by felix-hilden** [comment]
Hi! Are you proposing that we do this to all short combinations of ifs and returns? Personally I'm quite against this style either way.

**Comment by JelleZijlstra** [comment]
We will not be making this change.
