### ISSUE TITLE
Allow black to add a configurable header to source files

### ISSUE THREAD

**Issue by jacksonwb** [psf/black#2862]
Would be very useful to be able to lean on black to add a specified header string python source files.

I'm imagining specifying a string in black config and upon running the format operation it ensures this string is present at the beginning of all formatted source files.

There are plenty of editor based tools to do this, and its relatively easy to write a simple script for this but it would be nice to just ask the code formatter to take care of it when it runs in the pre-commit hook.

**Comment by cooperlees** [comment]
Thanks for the idea. That said, I'm a big fan of the UNIX philosophy. A tool should do one thing and do it well. Black is a formatter. This is not "formatting" per say and for that reason I'd like to -1 this idea. I won't close yet as I'd like to leave it open for discussion.

**Comment by JelleZijlstra** [comment]
I agree, this doesn't feel in scope for Black. It should be easy to write a pre-commit hook that just adds a header if you need it.

**Comment by felix-hilden** [comment]
While I agree that it's a neat idea in general, I also think that it'd be better off somewhere else than Black.

**Comment by jacksonwb** [comment]
Fair enough, a reasonable position. This issue can serve as precedent then for future inquiries.
