### ISSUE TITLE
Black should format docstring line length

### ISSUE THREAD

**Issue by danohn** [psf/black#2865]
**Describe the style change**

Black should format docstring line length.

**Examples in the current _Black_ style**

```python
def my_func():
    """
    This is a really long docstring. This is a really long docstring. Th
is is a really long docstring. This is a really long docstring. This is a really long docstring. This is a really long docstring.
    """
    pass
```

**Desired style**

```python
def my_func():
    """
    This is a really long docstring. This is a really long docstring. Th
is is a really long docstring. This is a really long docstring. Thi
s is a really long docstring. This is a really long docstring.
    """
    pass
```

**Comment by hukkin** [comment]
[docformatter](https://github.com/myint/docformatter) already exists. IMO would be great if Black didn't alter AST any more than it already does.

**Comment by ubalklen** [comment]
Not saying this should be solved by Black, but docformatter will only help so much. Their line wrapper only applies to simple docstrings, so if you're using Google style docstrings, you're out of luck.

**Comment by felix-hilden** [comment]
Yeah, this has been a pain point in #2150.

@ubalklen this could be a feature request to docformatter.

**Comment by ubalklen** [comment]
@felix-hilden they have an [open issue](https://github.com/PyCQA/docformatter/issues/60) already. I just mentioned that here in case there are other lost souls out there expecting to find some auto formatting tool for their non-standard docstrings. The current state of affairs is: Black won't (and maybe shouldn't) help you with this. And docformatter should, but won't help you at this time.

**Comment by felix-hilden** [comment]
Related to #2289

**Comment by simonprovost** [comment]
> @felix-hilden they have an https://github.com/PyCQA/docformatter/issues/60 already. I just mentioned that here in case there are other lost souls out there expecting to find some auto formatting tool for their non-standard docstrings. The current state of affairs is: Black won't (and maybe shouldn't) help you with this. And docformatter should, but won't help you at this time.

+1

**Comment by JelleZijlstra** [comment]
I am going to say that reflowing docstrings is out of scope for Black. It's likely to break some use cases (e.g., embedded code in docstrings), it may produce ugly output (just one word on the next line), and if we reflow too aggressively it can make diffs harder to read.
