### ISSUE TITLE
Trying to print documentation crashes the web page

### ISSUE THREAD

**Issue by berellevy** [psf/black#2866]
my first issue posting of an issue on github!

when I try to print documentation from the website the page freezes.
an example page is https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

I tried in chrome and edge.
thanks!

Berel

**Comment by ichard26** [comment]
I suspect this is due to https://github.com/pradyunsg/furo/issues/358 but I don't have time right now to check

**Comment by berellevy** [comment]
@ichard26 thanks!
don't know if this detail helps but the issue still exists even when I select the text that I want to print and then right click and hit print.

**Comment by ichard26** [comment]
This is finally resolved :tada:

**Comment by ichard26** [comment]
![image](https://user-images.githubusercontent.com/63936253/162592910-8912136c-980e-4b92-875a-0e8a0a141e55.png)
