### ISSUE TITLE
Add SPDX identifer to source files

### ISSUE THREAD

**Issue by swaldhoer** [psf/black#2869]
I think the way black uses ``click``, parses the ``pyproject.toml``, and extracts information from it are all done more or less perfect.
Therefore, I just wanted to copy some files verbatim to some of my projects, as ``black``s [license](https://github.com/psf/black/blob/31fe97e7ce1055debaa54bed9c63e252508a9a75/LICENSE) allows that. Of course, here and there, some things I might need to adapt, but the basics would help a lot to avoid duplicate work.

However, I somehow, dislike to copy these files, as no licensing information and information about the origin is provided in them. A license header could help here.

I would like to see some header that is common to all project files in the repository. This makes it simple to reuse them and adds some kind of traceability where it came from to others (additional this would do some advertising for the project, and that too is not bad at all ;)).

To not just nag, but work on a solution, I think of a header, something like that, would be good:

```python
# SPDX-License-Identifier: MIT
# Project URL: https://github.com/psf/black
```

This uses the [MIT](https://spdx.org/licenses/MIT.html) SPDX identifier and tells about the project origin.

What do you think?

**Comment by ichard26** [comment]
I'm fine with this assuming this won't interfere with module docstrings.

**Comment by jpy-git** [comment]
FYI Pylint uses a fork of this [pre-commit check](https://github.com/leoll2/copyright_notice_precommit) to verify that copyright headers have been added and match the expected format so might be worth adding this check as well if we decide to have these headers 😄 

https://github.com/PyCQA/pylint/blob/f935d362f5991ec06e6fea7c91ae1499caadf16f/.pre-commit-config.yaml#L23-L29

**Comment by ichard26** [comment]
Thoughts @JelleZijlstra?

**Comment by JelleZijlstra** [comment]
I dislike putting ugly boilerplate on every file. But you asked nicely and have a reasonable use case, and it's only two lines, so maybe? I also don't know anything about the legal issues involved. How did Pylint decide to add this header? Did they get legal advise?

**Comment by hauntsaninja** [comment]
Closing, since this hasn't gone anywhere in over a year and because I also don't like boilerplate or lawyers.

**Comment by swaldhoer** [comment]
> Closing, since this hasn't gone anywhere in over a year and because I also don't like boilerplate or lawyers.

@hauntsaninja I didn't do anything for this issue, as I had the impression, that the things mentioned by @JelleZijlstra are things the project maintainers need to agree first. The issue got closed, however, I still think that the issue is relevant.

SPDX is well defined in ISO/IEC 5692:2021, backed by the Linux Foundation, and the requirement for SBOMs is getting more relevant (industry, public and private funded projects) - I think this is issue is now more relevant than it was last year.

I hope we can have a discussion about pros and cons of the request (maybe only add the SPDX identifier and not the project home) without personal opinions. I would appreciate it.
