### ISSUE TITLE
Incomplete support of Python 3.10's structural pattern matching

### ISSUE THREAD

**Issue by VRGhost** [psf/black#2872]
**Describe the bug**

Black 21.12b0 crashes with the 
```
Cannot parse: 104:68:                 case {'aggregations': {'test_agg': {'composite': {} as agg_def}}} if ('after' not in agg_def):
```

message on the code provided below

**To Reproduce**

Use the following code

```python

def _mock_search_fn(es_query):
    out = None
    match es_query:
        case {'aggregations': {'test_agg': {'composite': {} as agg_def}}} if ('after' not in agg_def):
            # First agg search (withou 'after' in composite agg definition)
            out = {'aggregations': {'test_agg': {
                'after_key': 'iter_0',
                'buckets': ['b1', 'b2'],
            }}}
        case _:
            raise NotImplementedError(es_query)
    return out
```

And run it with these arguments:

```sh
$ black file.py --target-version py310
```

The resulting error is:

> Cannot parse: 104:68:                 case {'aggregations': {'test_agg': {'composite': {} as agg_def}}} if ('after' not in agg_def):

**Expected behavior**

The usual black magic - replace all string literals with double quoted versions, add spacing, etc.

**Environment**

- Black's version:  21.12b0
- OS and Python version: Ubuntu

**Comment by isidentical** [comment]
@VRGhost can you try with the latest version. The example [you have shared](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIuAStdAD2IimZxl1N_WlbvK5V7wp2sANQDDqaTvUCEoPVvQrN2nK1kW7CmrMEHh32D2I7-fpUB6teqxhgIJEbOeK79t3MWLJ1Pdv1eFzXdZrTzvm0jHrI3WqhelK1WylCnUK0G-QxWW-_KsIwqO0pmNPmtvljAYbyHyF_uttQL4IpZj_T2aSO-_PR8QSDzyJ7hLGc8SUr5NiJQAxKNGMrUds6yRI172XbzFuzed0lOdlRrEA98ZToVFudX5Ln7zT7dM42UOMNi6X9P2fHQmb4FbyrHErrjxIA3HNMtSi20ZdtLYdHJolvk9A7-RXCnsu4fjJQgTk3m9SnMxrryyp0fOKPHCcMej307x4ZWdHRkh5JtR_riy1BFcf7Jggij5UI6oeECwQPiJtovVb6hNVByAAAimBUaN_FmhAABxwKvBAAAPgh5p7HEZ_sCAAAAAARZWg==) seems to work with 22.1.0.

**Comment by VRGhost** [comment]
@isidentical Ooops, yes, you are absolutely correct, my apologies.

I thought that I've ran the pip update, but apparently I did not.
