### ISSUE TITLE
Black 22.1.0 strips some comments

### ISSUE THREAD

**Issue by henryiii** [psf/black#2873]
**Describe the bug**

Black will now occasionally strip comments (including `type: ignore` comments).

**To Reproduce**

For example, take this code:

```python
if hasattr(view, "sum_of_weights"):
    return np.divide(  # type: ignore[no-any-return]
        view.variance,  # type: ignore[union-attr]
        view.sum_of_weights,  # type: ignore[union-attr]
        out=np.full(view.sum_of_weights.shape, np.nan),  # type: ignore[union-attr]
        where=view.sum_of_weights > 1,  # type: ignore[union-attr]
        where=view.sum_of_weights**2 > view.sum_of_weights_squared,  # type: ignore[union-attr]
    )
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting Python code is:

```python
if hasattr(view, "sum_of_weights"):
    return np.divide(  # type: ignore[no-any-return]
        view.variance,  # type: ignore[union-attr]
        view.sum_of_weights,  # type: ignore[union-attr]
        out=np.full(view.sum_of_weights.shape, np.nan),  # type: ignore[union-attr]
        where=view.sum_of_weights > 1,  # type: ignore[union-attr]
        where=view.sum_of_weights**2 > view.sum_of_weights_squared,
    )
```

**Expected behavior**

Not to strip a type ignore comment!!!

(Personally, I think all trailing comments should be ignored from all line length calculations, etc, since they are often turning off linting or type checking for the line they are on. But it clearly shouldn't just vanish!)

**Environment**

- Black's version: main and 22.1.0
- OS and Python version: Any (macOS, pre-commit.ci's linux, and whatever the web app runs on)

**Additional context**

Pretty self contained. :)  I had noticed a similar error on upgrading to 22.1.0, but it went away due to other changes, and I never worked it back down, but I'm hoping it was the same one.

**Comment by ichard26** [comment]
Hmm, is there a reason why we ignore type comments in the AST @JelleZijlstra? this would be an excellent reason to stop doing this as this is problematic.

**Comment by henryiii** [comment]
Simpler example:

```python
return np.divide(
    where=view.sum_of_weights_of_weight_long**2 > view.sum_of_weights_squared,  # type: ignore
)
```

I think it has to be in a function call, and it has to have a `**` in the same line, and has to be longer than the line length.

I think `type: ignore` comments are ignored because they can never be moved to the next line. Though that's also true for `# noqa:*`, `# pylint disable=*`, etc.
