### ISSUE TITLE
Enforce formatting at the start of comments

### ISSUE THREAD

**Issue by hellocoldworld** [psf/black#2880]
When a comment starts with a '#' character and after that two or more blank spaces, other tools like flake8 report 

```bash
E262 inline comment should start with '# '
```

indicating that a comment should start with a '#' character and only one blank space.

I think it would be great if black handle this replacing two of more blank spaces after a comment start with a single blank space. Would this be a nice addition to the black formatting style?

**Comment by JelleZijlstra** [comment]
This will break commented out code, so I think it will make a lot of our users unhappy.
