### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by idek-software** [psf/black#2886]
**Describe the bug**

The website is down

**To Reproduce**

Open the [website]( https://black.vercel.app/?version=main)

The resulting error is:

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: lhr1::frs25-1645277178676-0769820ef994

**Expected behavior**

The website opens

**Environment**

- Black's version: [main]
- OS and Python version: Windows, all Python Versions

**Additional context**

This Serverless Function has crashed.

The connection is working correctly.

Vercel is working correctly.

**Comment by jack1142** [comment]
Black Playground isn't maintained by the maintainers of this repo. You should probably report this issue here:
https://github.com/jpadilla/black-playground
