### ISSUE TITLE
A blank line right after the function definition must be removed

### ISSUE THREAD

**Issue by AIGeneratedUsername** [psf/black#2887]
**Describe the style change**

I think this is obvious enough that a blank line right after the function definition is against PEP-8 and against how people write functions, so better just see the examples below.

**Examples in the current _Black_ style**
```python
def func():

    return "Hello"
```

**Desired style**
```python
def func():
    return "Hello"
```

**Additional context**

This is the only reason to use blank lines inside functions:

> Use blank lines in functions, sparingly, to indicate logical sections.

But the blank line must not be right after the function definition.

**Versions**

black-22.1.0
Python 3.10

**Comment by felix-hilden** [comment]
Hi! Thanks for submitting. However, this is essentially the same as #902, so let's continue the discussion there!
