### ISSUE TITLE
Return code 1 when reformatting files

### ISSUE THREAD

**Issue by MarcoGorelli** [psf/black#2888]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to just use `black src` in both CI and local development.

**Describe the solution you'd like**

When `black` reformats any file, its return code would be `1` rather than `0`.

**Describe alternatives you've considered**

Run `black` via `pre-commit`, which always returns `1` if a tool modifies a file. This is fine for projects which use pre-commit, but (IMO, unfortunately) not all projects do.

**Additional context**

```console
(venv) marcogorelli@OVMG025 tmp % black --version     
black, 22.1.0 (compiled: yes)
(venv) marcogorelli@OVMG025 tmp % cat t.py            
a= 2
(venv) marcogorelli@OVMG025 tmp % black t.py          
reformatted t.py

All done! ✨ 🍰 ✨
1 file reformatted.
(venv) marcogorelli@OVMG025 tmp % echo $?             
0
```
My suggestion is that the last one should be `1`

**Comment by JelleZijlstra** [comment]
As you probably know we also have the `--check` option. Why is it important to you to be able to run the exact same command in CI and local development?

It's probably too late to change our return code for such a basic scenario.

**Comment by MarcoGorelli** [comment]
> Why is it important to you to be able to run the exact same command in CI and local development?

it saves having to duplicate everything

e.g. `make lint` runs `black`, `make ci-lint` runs `black --check`. Easier to just have `make lint` run `black` and run that both locally and in CI

With `pyupgrade` (and all of Anthony Sottile's tools) tools, the exit code is `1` if the tool modifies any file

**Comment by MarcoGorelli** [comment]
> It's probably too late to change our return code for such a basic scenario.

sure, no worries, closing then
