### ISSUE TITLE
FEAT: Add `-> None` to any typed `__init__()`

### ISSUE THREAD

**Issue by NickCrews** [psf/black#2913]
**Is your feature request related to a problem? Please describe.**

In https://github.com/pandas-dev/pandas/pull/46279 someone wants to make the pandas codebase adhere to PEP484, so they add `None` return annotations to some `__init__` methods. This is a bummer that this is manual. It would be nice if this could be included in pandas's code checks in CI, so the entire code base was consistent.

**Describe the solution you'd like**

It would be nice if black added this annotation automatically. However, it should only happen for methods that already have type annotations: black should not make a previously-untyped method suddenly be typed, because that will cause some type checkers like mypy to inspect it, and perhaps it was left untyped on purpose.

**Describe alternatives you've considered**

Not sure if this belongs here, or in another project like flake8, etc, or if this is even within scope. Thank you!

**Comment by NickCrews** [comment]
Thank you @JelleZijlstra! Would you consider autotyping mature enough to be relied upon by pandas?

**Comment by JelleZijlstra** [comment]
Sure, but it doesn't fit your description above perfectly—for example, it will apply annotations everywhere, not just to already-typed methods. Feel free to open an issue on the autotyping repo if there's specific things you'd like changed.

**Comment by felix-hilden** [comment]
Agreed on the scope restriction, although the idea in itself is solid!

**Comment by NickCrews** [comment]
Thank you!
