### ISSUE TITLE
pylint checks seem to no longer exist?

### ISSUE THREAD

**Issue by alkatar21** [psf/black#2914]
Using black with other tools says for [pylint](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#pylint), that one should switch off `disable = C0330, C0326`, however I find the checks on neither [here](https://pylint.pycqa.org/en/latest/technical_reference/features.html) nor [here](https://pylint.pycqa.org/en/latest/technical_reference/extensions.html).

**Describe the solution you'd like**

If I'm not missing anything and they really don't exist anymore, that could be removed from the documentation.

**Comment by graingert** [comment]
sources for the removals are on the PR #2931 :

> `CO330` is removed by [PyCQA/pylint#3571](https://github.com/PyCQA/pylint/pull/3571), I am not sure about the other error code but AFAIK its removal was part of the same release.

> @Shivansh-007 `C0326` was removed in [PyCQA/pylint#3577 (files)](https://github.com/PyCQA/pylint/pull/3577/files) (same release as `CO330` removal)
