### ISSUE TITLE
Horizontally align quotes in multi-line f-string breaks

### ISSUE THREAD

**Issue by ajoino** [psf/black#2915]
**Describe the style change**

Align quotation marks for multi-line string breaks (using --preview) if the resulting strings are a mixture of f-strings and normal strings.

**Examples in the current _Black_ style**

Before black:
```python
def f():
    stuff, things = 1, 2
    long_string = f'When you create an f-string that contains so much {stuff} it has to be split over multiple lines, some splits might not "contain" interpolation in them. That makes the quote {things} not align.'
```

After `black -l 50 --experimental-string-processing

```python
def f():
    stuff, things = 1, 2
    long_string = (
        "When you create an f-string that"
        f" contains so much {stuff} it has to be"
        " split over multiple lines, some splits"
        ' might not "contain" interpolation in'
        " them. That makes the quote"
        f" {things} not align."
    )#   ^
#        |
#        |
# Unaligned quotes
```

**Desired style**

```python
def f():
    stuff, things = 1, 2
    long_string = (
         "When you create an f-string that"
        f" contains so much {stuff} it has to be"
         " split over multiple lines, some splits"
         ' might not "contain" interpolation in'
         " them. That makes the quote"
        f" {things} not align."
    )#   ^
#        |
#        |
# Aesthetically pleasing column of quotes
```

**Additional context**

Brought this up in #2188 found agreement that aligning quotes would be pleasing and it was suggested that I create an issue for discussion.

**Comment by JelleZijlstra** [comment]
I don't think we should do this, it creates inconsistent indentation. I have never seen this style in manually formatted code.

**Comment by ajoino** [comment]
The argument for aligning the quotes stems from how you split f-strings. I usually keep all splits as f-strings, because that keeps the indentation and start of strings consistent. @bbugyi200 gave some good arguments why black doesn't do that, so the next best thing in my opinion would be what I suggest.

While having the start of splits in different columns creates consistent indentation in terms of leading spaces, I think it actually creates inconsistent indentation visually. Since black is a formatting tool, I think visual consistency should be prioritized over having a consistent number of spaces. Although, this argument is based what _I_ consider visual consistency, and your mileage may vary.

**Comment by TylerYep** [comment]
There are currently popular open-source linters that have rules against inconsistent indentation and unnecessary f-strings (e.g. flake8, pylint). This change would make black incompatible with these tools, effectively preventing people from easily upgrading black. As far as I know, there is no tooling supporting this style either, so it doesn't seem like a very productive change.

Personally I don't mind f strings on some parts of the string but not others. This code is perfectly readable to me:

```
my_string = (
    f"The most wonderful thing about {}"
    "is that they are the only one.\n"
    " -- ..."
)
```

**Comment by andersk** [comment]
One of Black’s documented features is “Black makes code review faster by producing the smallest diffs possible.” Horizontally aligning quotes would violate that philosophy, since this diff:

```diff
    long_string = (
-       "When you create an f-string that"
-       " contains so much stuff it has to be"
-       " split over multiple lines, some splits"
-       ' might not "contain" interpolation in'
-       " them. That makes the quote"
-       " things not align."
+        "When you create an f-string that"
+       f" contains so much {stuff} it has to be"
+        " split over multiple lines, some splits"
+        ' might not "contain" interpolation in'
+        " them. That makes the quote"
+       f" {things} not align."
    )
```

is unnecessarily longer and less readable than this one:

```diff
    long_string = (
        "When you create an f-string that"
-       " contains so much stuff it has to be"
+       f" contains so much {stuff} it has to be"
        " split over multiple lines, some splits"
        ' might not "contain" interpolation in'
        " them. That makes the quote"
-       " things not align."
+       f" {things} not align."
    )
```

**Comment by JelleZijlstra** [comment]
We won't be making this change.

**Comment by bluenote10** [comment]
> We usually intentionally add the pointless f-prefix to pretty align multiline strings.

In fact, there are actually good reasons to keep the "pointless" f-prefixes: I've often seen people re-arrange sentences of multi-line strings in a way that an interpolated element moved from one line to another. If the multi-line string uses the f-prefix only where necessary, it can happen that the interpolated expression moves into a line that misses an f-prefix. This cannot really be detected by the type checker or so, because the string will just contain the interpolation expression without interpolation, and it only shows much later e.g. in an uninterpolated log message. This issue is particularly likely, if people don't use an IDE but rather make "code edit suggestions" in a review tool that doesn't support syntax highlighting where overlooking the f-prefixes is a frequent problem. 

The other obvious argument in favor of using f-prefixes for all lines of a multi-line expression is proper alignment as mentioned before.

> black will always drop the pointless f-prefix in future releases.

I wish this can be reconsidered. Since re-adjusting f-prefix is error prone and breaks alignment, it is a sensible coding guideline to do the opposite, and use all-f-prefixes lines consistently.
