### ISSUE TITLE
Drop redundant parenthesis in `with` statement

### ISSUE THREAD

**Issue by intgr** [psf/black#2921]
**Describe the bug**

Black removes redundant parenthesis in most contexts, but this does not apply to the `with` statement yet.

**To Reproduce**
[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACXAFtdAD2IimZxl1N_Wlws4SR5ySw_sBpDkhU93hOCZPT-hFkjq5Stk1KilvNEQNrc4EaZ8ufi_zEpnhZViAkrMAiyAFGllzQQ2rS3TSp7D0gVbLYWtVvdCKgKqXub2lwAAPSQHVnPZQFHAAF3mAEAAAAQ4riMscRn-wIAAAAABFla)

```python
if (open("bla.txt")):
    pass

with (open("bla.txt")):
    pass
```

Output:
```python
if open("bla.txt"):    # <-- parenthesis removed
    pass

with (open("bla.txt")):    # <-- parenthesis retained
    pass
```

Adding `--target-version=py310` or `--preview` does not change this behavior.

**Environment**

- Black's version: 22.1.0 and main branch
- OS and Python version: Python 3.10

**Comment by JelleZijlstra** [comment]
Yes, we should remove these. There are a bunch of other contexts where we leave redundant parens around.

**Comment by intgr** [comment]
Some additional test cases involving `with`:
```python
with (open("bla.txt") as f):
    pass

with (open("bla.txt")) as f:
    pass

with (open("bla.txt") as f, open("x")):
    pass

with ((open("bla.txt")) as f, open("x")):
    pass
```

**Comment by intgr** [comment]
Thanks @jpy-git! :)
