### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by RandyMcMillan** [psf/black#2923]
https://github.com/RandyMcMillan/x20bf/runs/5547164070?check_suite_focus=true

error: cannot format /home/runner/work/x20bf/x20bf/x20bf/depends/git/test/performance/test_odb.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk__z8nbt2n.log

**Comment by JelleZijlstra** [comment]
Could you extract the file and give a self-contained repro case?

**Comment by ichard26** [comment]
Here's the code of the failing file:
```python
"""Performance tests for object store"""
import sys
from time import time

from .lib import TestBigRepoR


class TestObjDBPerformance(TestBigRepoR):

    def test_random_access(self):
        results = [["Iterate Commits"], ["Iterate Blobs"], ["Retrieve Blob Data"]]
        for repo in (self.gitrorepo, self.puregitrorepo):
            # GET COMMITS
            st = time()
            root_commit = repo.commit(repo.head)
            commits = list(root_commit.traverse())
            nc = len(commits)
            elapsed = time() - st

            print("%s: Retrieved %i commits from ObjectStore in %g s ( %f commits / s )"
                  % (type(repo.odb), nc, elapsed, nc / elapsed), file=sys.stderr)
            results[0].append(elapsed)

            # GET TREES
            # walk all trees of all commits
            st = time()
            blobs_per_commit = []
            nt = 0
            for commit in commits:
                tree = commit.tree
                blobs = []
                for item in tree.traverse():
                    nt += 1
                    if item.type == 'blob':
                        blobs.append(item)
                    # direct access for speed
                # END while trees are there for walking
                blobs_per_commit.append(blobs)
            # END for each commit
            elapsed = time() - st

            print("%s: Retrieved %i objects from %i commits in %g s ( %f objects / s )"
                  % (type(repo.odb), nt, len(commits), elapsed, nt / elapsed), file=sys.stderr)
            results[1].append(elapsed)

            # GET BLOBS
            st = time()
            nb = 0
            too_many = 15000
            data_bytes = 0
            for blob_list in blobs_per_commit:
                for blob in blob_list:
                    data_bytes += len(blob.data_stream.read())
                # END for each blobsha
                nb += len(blob_list)
                if nb > too_many:
                    break
            # END for each bloblist
            elapsed = time() - st

            msg = "%s: Retrieved %i blob (%i KiB) and their data in %g s ( %f blobs / s, %f KiB / s )"\
                % (type(repo.odb), nb, data_bytes / 1000, elapsed, nb / elapsed, (data_bytes / 1000) / elapsed)
            print(msg, file=sys.stderr)
            results[2].append(elapsed)
        # END for each repo type

        # final results
        for test_name, a, b in results:
            print("%s: %f s vs %f s, pure is %f times slower" % (test_name, a, b, b / a), file=sys.stderr)
        # END for each result
```
https://github.com/RandyMcMillan/x20bf/blob/dc7474df77070ba7310b0d719607b626156c30ef/x20bf/depends/git/test/performance/test_odb.py

I can't reproduce this internal error using the [latest version of Black](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ArUA5ZdAD2IimZxl1N_Wk8FsHfSMQkUV1YvTGci7MRx87kMwJFZdi7qd0Th8rjXEoARnvSzhPoJz57ez8SsHsC2Fd_ThrYLLryCXeukLAE_D8KvoyGy0z4lj4r7ZeodLKLKanKHDEtiQZR9a7mSnGu-nYrxUeqzK4CNAbtYE39GpkABXDHsOKgL-vNmyvus7Td0VA8-WI8o_1rFbPFZcrp3tSc06KfeuuJgafA1eAz4q7DocyvNhpGtD7BNIuwDegd5wwL_vrM05W47SFTh1z9a1KgEsuGh92c4ZBU5WPirr0MHX4dnSl6GX1tNs9qQitC4dAFOuj1DD07-QNYHJbZI6jinPZVCLPfXseLjjHJWiP-53PmVvrJ4VzojVPfWeUtamzHSr-9Jk6bMHZmClWmARWEiiBRRMwMeO2AsCK-RWg7PThC1BkrGZAxEM-QG5Y77CmY7j5jtDt9zzU9NNrWoE3bHZ7z-8a_WYXq1GuFqhddj1lfLuaMAYiFhui4td0rSLQ95MRX59J-JGyuf-BBd53FuGD7M0kNI6WhdYs-2Dvd_QoKpJoObWgStEwvS4ThUOlQQY-9ojsi-Ck7sxL9eh7RrE1J3XMGDHFokRFqCmstV6gwXwrAyH0Kqkea1mqvm7zMHKK5rlqafbH_71YohPDzl6e47ptb-F7dlW8dDe_tbUrDQjy5KllQQdGKvjUFamvQkodXofiFgvsu9lFT_84DwgvrB5S24b1UJwLxsQpzYMjVmqsWnlcBG0BPnV-d7ukdL_MA-pxb8pr_a0niA_2AB5tDpi33woSV5YISQLlL1drTyHxjdIeNeLdsolnaAVOiLE1hOHPNWlI9PZzoITc2NcdBomLIOI3XzB95QQ219UxKak_jkK_qPHnba_P49iBE9FE6MqVVxyL27DriB-HtQO9Qtx5h_GINesS6YQb8qVTGi5cz2RBj2-J49UHTe4UmS6d2NZdeJ-Zc-7j1-YjVNG6WlW9tIbPlm-sac2KZEbgUyEniCUmA8hsGAp1QeXi_opD-2qJoKQWbkzrOyGVzCFbc5UW13SLJjwKPiBtnuDdAKtBSeO3p3RMqjGBU1Db8OE_aNraBDsUp9FisFv5Fo9z8eVRwrjS6ME4ufagWWbgn5e0lnyhrq9BtcL7eot0TkUId_coRVT6rhK3-6XhchG9vDw8EEzYPjZIpTbIWd8nKwMbAoK91elj8cs0CfkJCrYrjdoHMWpgAAAPVwMXQ1SdBcAAGyB9UVAACDkhAtscRn-wIAAAAABFla) (22.1.0) or even 21.4b0. It's worth noting the repo was using black==20.8b1 at the time of the linked workflow: https://github.com/RandyMcMillan/x20bf/blob/dc7474df77070ba7310b0d719607b626156c30ef/.pre-commit-config.yaml#L3-L8
