### ISSUE TITLE
legecy install failure

### ISSUE THREAD

**Issue by Drr1122** [psf/black#2927]
![Screenshot (23).png](https://user-images.githubusercontent.com/93814052/158462989-d8a99d1f-c7ef-4dac-9c74-dd7108c9c851.png) I got stuck with this error can someone please help me out

**Comment by JelleZijlstra** [comment]
Looks like you're trying to install `dlib`, not Black. You may have better luck on their tracker.

**Comment by Drr1122** [comment]
Thank you for your quick response sir may i know the possible solution for
this problem
