### ISSUE TITLE
Addition of `isort` to our dev toolchain

### ISSUE THREAD

**Issue by Shivansh-007** [psf/black#2930]
Currently, the imports exist in any random order as added by the developers (see below), which sometimes makes it difficult to look through them in search of something. Furthermore, it is not very pretty or easy to read.

https://github.com/psf/black/blob/086ae68076de570b0cb1881a3c3b9da592b46ee0/src/black/__init__.py#L52-L59
https://github.com/psf/black/blob/086ae68076de570b0cb1881a3c3b9da592b46ee0/src/black/__init__.py#L6-L11

This is where `isort` comes in, `isort`, unlike `black` is a fantastic hyper configurable tool that will magically sort your imports so you don't have to care about them. It also allows you to format them while agreeing with the `black` style guide using [Black Profile](https://pycqa.github.io/isort/docs/configuration/profiles.html)

An experimental PR containing changes brought by isort could be made, and we could then decide how to proceed after reviewing the diff.

**Comment by JelleZijlstra** [comment]
Could also consider using https://github.com/facebookexperimental/usort
