### ISSUE TITLE
Black fails of CMake macros

### ISSUE THREAD

**Issue by InnocentBug** [psf/black#2955]
**Is your feature request related to a problem? Please describe.**
I am using CMake in combination with python. And in this context, CMake configures the python files before installation.
Which means, it replaces macros like `@SOMA_PYTHON_SHEBANG@` with a string from my installation configuration.

I would like to have black style check the input files, since these are the file we change during development.
However, black doesn't like the cmake macros and crashes with 
```
error: cannot format ConfGen.py.in: Cannot parse: 1:21: @SOMA_PYTHON_SHEBANG@

Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Describe the solution you'd like**

It would be nice to have black either automatically replace these macros with stubs.
Or let me specify manually how they should be replaced before parsing.

**Describe alternatives you've considered**

It is probably possible to chain black with `sed` commands that do the replacing, but it is not really a great solution.
Having it bundled in black would be nice.

**Additional context**

I really enjoy `black` kudos to all devs.

**Comment by JelleZijlstra** [comment]
Sorry, but I feel this is out of scope for Black. We're a Python formatter, not a CMake formatter.

**Comment by InnocentBug** [comment]
Ok, I can use my work around for this.
Just wanted to see if there is already a solution for me or if this is something you would be interested in supporting.
