### ISSUE TITLE
Avoid split strings in a single line.

### ISSUE THREAD

**Issue by mvaled** [psf/black#2956]
**Describe the style change**

Black should merge split strings that fit into a single line.

**Examples in the current _Black_ style**

```python
def f():
    raise ValueError("This was previously formatted " "with a smaller line-length") 
```

**Desired style**

```python
def f():
    raise ValueError("This was previously formatted with a smaller line-length") 
```

**Additional context**

In some projects, we have started with line-length of 80 and now we're increasing that to 95 or even 120.  We performing such a move some strings which were previously split in several lines are put together in a single line, but still split.

Some complications might arise from split strings with f-strings intermixed:

```python
def f(length):
    raise ValueError("This was previously formatted " f"with a smaller line-length {length}") 
```

When merging we might consider the following rules:

- If ``first`` is an f-string or ``second`` is an f-string, produce an f-string
- Otherwise, produce a plain string.

Which renders:

```python
def f(length):
    raise ValueError(f"This was previously formatted with a smaller line-length {length}") 
```

**Comment by jpy-git** [comment]
@mvaled Both of these already work if you use the experimental string processing feature.
Just pass the `--preview` argument when calling `black` and it will fix this for you 😄

**Comment by mvaled** [comment]
Thanks @jpy-git.  I will try it.
