### ISSUE TITLE
Bug using a previous click version

### ISSUE THREAD

**Issue by nidhaloff** [psf/black#2969]
**Describe the bug**

It looks like black is depending on click>=1.8.0, However, click changed the API in the new version 1.8.4, which is causing imports problems. BTW the pre-commit hook is also not working using the latest, stable version. I'm not sure if I'm the only one getting this!

**To Reproduce**

Just try to run black

The resulting error is:
```
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/nidhal/.cache/pypoetry/virtualenvs/deep-translator-api-jSXxDSQ4-py3.8/lib/python3.8/site-packages/click/__init__.py)
```
**Expected behavior**

Black runs normally

**Environment**

- Black's version: latest, stable
- OS and Python version: Ubuntu, py3.8

I think this can be fixed if the dependency is updated. Instead of depending on click>=1.8.0, you can depend only on patches or an exact version of click. I wanted to do a PR but I'm not sure what you guys would want in this case.

**Comment by JelleZijlstra** [comment]
Fixed in Black 22.3.0, published a full two minutes ago. See #2964.
