### ISSUE TITLE
Issue with click library upgrade

### ISSUE THREAD

**Issue by cormaza** [psf/black#2972]
Upgrade on library click https://pypi.org/project/click/8.1.0/ broken, I think we can solve restricting version of library to 8.0.4

![image](https://user-images.githubusercontent.com/1674751/160643714-6dd14fba-55fd-4792-a4cf-587f59fee327.png)

**Comment by jack1142** [comment]
This has already been fixed by Black 22.3.0.

**Comment by JelleZijlstra** [comment]
Duplicate of #2964
