### ISSUE TITLE
Docker images use a user install of Black so don't work when running as another user

### ISSUE THREAD

**Issue by RoryDungan** [psf/black#2975]
**Describe the bug**

Since [bd96139](https://github.com/psf/black/commit/bd961304b63ad8178610df7242edf180d825e336), Docker images use a user install of Black. This means they can't be used when running a container as a user other than root. 

This is a problem for me because we run Black inside of Jenkins and Jenkins runs _all_ containers with the same UID as the host, meaning that Black cannot run because it isn't on the PATH and in any case `/root/.local/bin/black` is inaccessible. It also seems like it could be problematic in any situation where the Black Docker container needs to write a file, because files it creates must be owned by root.

**To Reproduce**

Previously this would work:
```
$ docker run --rm -it -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace pyfound/black:21.9b0 black --check .
All done! ✨ 🍰 ✨
4 files would be left unchanged.
```
However on versions 21.10b0 and up, including the latest 22.3.0 I get the following output:
```
$ docker run --rm -it -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace pyfound/black:21.10b0 black --check .
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "black": executable file not found in $PATH: unknown.
$ docker run --rm -it -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace pyfound/black:22.3.0 black --check .
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "black": executable file not found in $PATH: unknown.
```

**Expected behavior**

I should be able to run the Black Docker container as any user, not just root.

**Environment**

- Black's version: 21.10b0, 22.3.0
- OS and Python version: [Linux/Python 3.10.4]

**Comment by cooperlees** [comment]
Hi - Thanks for reporting. I agree, should be able to be non root.

I guess we just have to remove the `pip --user` and copy the system install to the actual image. I'll try look at it soon but happy to take any PR to fix this.
