### ISSUE TITLE
Fail gracefully when unaligned or missing 'fmt: off/on' found

### ISSUE THREAD

**Issue by mvaled** [psf/black#2985]
The following snippet makes black fail with "Black produced code that is not equivalent to the source.".

```
import typing as t

class Named(t.Protocol):
    # fmt: off
    @property
    def title(self) -> str: ...

class Factory(t.Protocol):
    def __call__(self, **kwargs) -> Named: ...
    # fmt: on
```

The following works:

```
import typing as t

class Named(t.Protocol):
    # fmt: off
    @property
    def title(self) -> str: ...
    # fmt: on

class Factory(t.Protocol):
    # fmt: off
    def __call__(self, **kwargs) -> Named: ...
    # fmt: on
```
---

Side note: mistyping causes black to indicate the wrong error:

```
import typing as t

class Named(t.Protocol):
    # fmt: off
    @property
    def title(self) -> str: ...
    # fmt: one
    #        ^- "mistyped"

class Factory(t.Protocol):
    # fmt: off
    def __call__(self, **kwargs) -> Named: ...
    # fmt: on
```

In this case, black says "`Cannot parse: 13:4:     def __call__(self, **kwargs) -> Named: ...`"; which is misleading.

**Comment by mvaled** [comment]
This might be a duplicate of #569.  Apparently  #2842 is a similar issue, but not reproducible.   

You can reproduce the [two failing](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFYAMhdAD2IimZxl1N_WlwxRhR7MSgFUcTLI8hLawxlAyW2NgE9_lTiPPyVhMGc-wvzgZl0QYztn58fCHpBlL-a2htWFNgwe8bVc01IX4EjBLkGYlaYohJ-2bRTdv7gjwOr1uudK6ZmpF9E9tU27We1Mlly8yLc50aOfTTe7LIK_mrJ2gpIqAbdMQ44xmcpFpB8F2_bnp97Ld90fvCqi7QcroGeYUxwuojLrPrc-fpXPqEM2zJ-m-Z6nFtYVLmExbYJdJExQxyqGVA_CpfTAJ0kilQWFbBPAAHkAdkCAACEhjgrscRn-wIAAAAABFla) snippets in the [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEaALZdAD2IimZxl1N_WlwxRhR7MSgFUcTLI8hLawxlAyW2NgE9_lTiPPyVhMGc-wvzgZl0QYztn58fCHpBlL-a2htWFNgwe8bVc01IX4EjBLkGYlaYohJ-2bRTdv7gjwOr1uudK6ZmpF9E9tORRjfI9AUyG1_kW1BaoS-Lo4kWvjlORgc29LGpAPqz_36DBHaL1-DpGaY5BaQDSt3rxen-cEcaY_jZYZq_djk1141RzrrfR6h24JetehcAAAAAdY5BviE6MKwAAdIBmwIAAILyBsixxGf7AgAAAAAEWVo=).

I'm leaving this open so that the team can decide if its the same problem or not.

**Comment by felix-hilden** [comment]
FWIW, we do require the comments to be in the same block, although [the documentation](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=fmt%3A%20off#code-style) could be clearer about it.

As to your other concern, I managed to simplify a bit: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC0AFxdAD2IimZxl1N_WlXnON2nzNX9HFvHx6cBGYYzxnKDXUC9bWnmZzxb2iGsQymhw57kOZ1YCFANQYZgKwu2GQTPW_J2EDHRMjoxdYk2059SL25H6MSVOWD5Q63tef_gAKllYQb7vB0hAAF4tQEAAABwu79EscRn-wIAAAAABFla).

```python
class Foo:
    # fmt: off
    1
    # fmt: one

class Bar:
    # fmt: off
    1
    # fmt: on
```

produces a "cannot parse" on Bar's line "1". Removing the Foo definition and unindenting the body works, but removing Bar similarly produces code not equivalent to the source.

**Comment by felix-hilden** [comment]
Definitely related, but I propose we edit this issue to be about the misspell bug and open a new design issue for letting (or deciding against) `# fmt: off/on` spanning across unindents.

**Comment by felix-hilden** [comment]
In the meantime, it appears to happen even if the second comment is missing: [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACkAFtdAD2IimZxl1N_WlXnON2nzNX9HFvHx6cBGYYzxnKDXUC9bWnmZzMczz8-5oZsWrpdgU6quHPZdEvQmAg39fC5tScCiaDH3kbKBHJ-quOfPTSCcODcQLbiErAffiAAAJEww3dpp7KJAAF3pQEAAAAnngnVscRn-wIAAAAABFla)

```python
class Foo:
    # fmt: off
    1

class Bar:
    # fmt: off
    1
    # fmt: on
```

But not without the class defs.

**Comment by mvaled** [comment]
@felix-hilden 

And now that I think how black might work (I haven't really read the code; but I know it deals with the AST); I can imagine it can be very difficult to support *arbitrary* locations of paired `fmt: off/on`.

The documentation is more or less clear about it:

>  It doesn’t reformat **blocks** that start with `# fmt: off` and end with `# fmt: on`, or lines that ends with `# fmt: skip`. `# fmt: on/off` have to be on the same level of indentation. 

But it can be improved.   Let me first explain how I came up with the first example.  In the actual code from which I derived the first snippet; the first protocol is bigger and has a nice docstring that I want `black` to format.  That's why I started the `# fmt: off` inside the class itself.  The second protocol didn't have a docstring because it's trivial.

I don't think real code would use `fmt: off/on` like this very often; so it might be easier to make the documentation much more explicit about this.   Alternatively, we can fix black to detect missing `fmt: on` when the indentation level is less than the level of the last `fmt: off`.  But I wouldn't know how difficult is to introduce this change in black's parser.

**Comment by felix-hilden** [comment]
I updated docs in the PR linked above. So some thoughts about this issue:

I think in this situation, assuming we won't change `# fmt: off/on` to allow arbitrary placement, we *should* fail. Currently in the examples presented here, we fail with two different messages: "not equivalent to source" and "cannot parse". We ought to try to catch them and inform the user that `fmt` was used incorrectly. Thoughts?

**Comment by JelleZijlstra** [comment]
Agree, this sort of code is incorrect and Black should fail on it, but we should fail gracefully and not with a crash.
