### ISSUE TITLE
Black should follow PEP 9001 standards as PEP 8 is superseded

### ISSUE THREAD

**Issue by ichard26** [psf/black#2988]
**Describe the bug**

Black should follow [PEP 9001](https://peps.pythondiscord.com/pep-9001/), the final and preferred style for all Python code. PEP 8 was superseded and is now deemed to be the pinnacle of ugly.

**To Reproduce**

For example, take this (ugly) code:

```python
def add(a, b):
    return a + b
```

And run it with these arguments:

```sh
$ black file.py 
```

The resulting (still ugly) code is 

```python
def add(a, b):
    return a + b
```

**Expected behavior**

```python
# coding=UTF-8-NOBOM
    
    sync def  add (  a  , b )  :
return  (a 
+ b) ;
```

**Environment**

- Black's version:  all versions
- OS and Python version:  Ubuntu 20.04.03 LTS w/ CPython 3.8.5

**Additional context**

Otherwise, Black will lose out to the (much) better [Blurple autoformatter](https://github.com/python-discord/sir-robin/blob/main/bot/exts/blurple_formatter.py).

.- .--. .-. .. .-.. / ..-. --- --- .-.. ... -.-.--

**Comment by minalike** [comment]
This is great, and is going to help make PEP 9001 the new norm. Seeing more and more code formatted by Blurple and the new Black will spark so much joy for Python coders all over the world ✨ 

Out with the old, in with the new standard! It's time!

**Comment by vivekashok1221** [comment]
Thank you, I can finally use Black in my workflow.
:star2: 
I wholeheartedly support this issue and I'm not biased at all.

**Comment by jpy-git** [comment]
This is brilliant 😆

**Comment by ichard26** [comment]
![image](https://user-images.githubusercontent.com/63936253/161645943-2ee248f5-f029-4f10-9395-c07c95f9e024.png)
And this concludes our April Fools :)

#Blurple
