### ISSUE TITLE
610faff656c4cfcbb4a3__mypyc

### ISSUE THREAD

**Issue by mrclary** [psf/black#2994]
This is not a bug, but a general question.
Sorry, I could not ask this question on Discord as it keeps telling me I'm in an unclaimed account even though I've logged in.

`black` has listed in its distribution meta-data `top_level.txt` the module `610faff656c4cfcbb4a3__mypyc`. I'm wondering how the name of this module is generated as it is not found in `src/`.

**Comment by JelleZijlstra** [comment]
It's relate to our usage of mypyc (https://mypyc.readthedocs.io/en/latest/). I am not sure exactly how the name is generated, but apparently that's how mypyc works.

**Comment by ichard26** [comment]
So yeah we use mypyc to compile Black into a fast Python C Extension. We compile everything as one single massive compilation unit so all the code of all modules are packed in a single autogenerated extension module. It's faster this way compared to compiling each module as their own separate compilation unit. There's a little more information about this in the mypyc docs: https://mypyc.readthedocs.io/en/latest/compilation_units.html

**Comment by ichard26** [comment]
If you look at the Pure Python wheel we distribute along side the optimized platform specific wheels, you'll see how it doesn't contain the autogenerated extension module. It's completely optional and you aren't losing anything by using the pure python wheel. 

Now I think about it, it's probably worth a FAQ entry about our usage of mypyc (especially as I'd imagine the "compiled: yes/no" in `black --version` could be very confusing).

**Comment by mrclary** [comment]
Okay, thanks for the insight.
The reason for my question is that [spyder-ide/spyder](https://github.com/spyder-ide/spyder) uses [py2app](https://github.com/ronaldoussoren/py2app) to build standalone applications and needs to ensure that all of `black`'s packages are included in the application bundle. Given that `610faff656c4cfcbb4a3__mypyc` may or may not exist (or its name could be different) depending on the type of installation, I suppose it is best to inspect the `egg-info/top_level.txt` for all necessary packages.

**Comment by ichard26** [comment]
If you're aiming to package standalone applications, it may be best to use the Pure Python wheel to have the best chance of compatibility, but yes looking at .dist-info's or .egg-info's top_level.txt is a good idea.

Unless you have more questions, I'll close this since there's nothing left to action here (well except for adding an entry in the FAQ 'bout our use of mypyc -- I'll do that right now). Have a great day!
