### ISSUE TITLE
Concatenated strings have unnecessary breaks

### ISSUE THREAD

**Issue by alanbchristie** [psf/black#2998]
**Describe the bug**

When strings are concatenated, originally having been split on multiple lines, the result contains breaks that are unnecessary and conflict with tools like pylint: -

```python
_LOGGER.warning('Got ApiException' ' listing namespaced pod' ' (%s)', ex)
```

**To Reproduce**

Start with a string split over multiple lines, typically in a logger call.

For example, take this code:

```python
_LOGGER.warning('Got ApiException'
                ' listing namespaced pod'
                ' (%s)', ex)
```

And run it with these arguments:

```sh
$ black file.py --skip-string-normalization
```

The resulting error is:

```python
_LOGGER.warning('Got ApiException' ' listing namespaced pod' ' (%s)', ex)
```

**Expected behavior**

Instead, it would be a lot more sensible to either a) leave the line alone or b) generate this line: -

```python
_LOGGER.warning('Got ApiException listing namespaced pod (%s)', ex)
```

**Environment**

- Black's version: `22.3.0`
- OS and Python version: `Linux/Python 3.10.4`

**Additional context**

-none-

**Comment by JelleZijlstra** [comment]
Thanks, we have a fix for this in preview mode (previously `--experimental-string-processing`). Hopefully we'll turn it on globally for the 2023 edition of Black.
