### ISSUE TITLE
Sublime Text 3 plugin no longer maintained

### ISSUE THREAD

**Issue by jsma** [psf/black#2999]
The documentation currently recommends using the `sublack` extension but the repo was archived February 28, 2022 and is no longer maintained.

I am not super conscious which version of Sublime Text I have since version 4 doesn't really advertise it, it's just "Sublime Text" and the About window has a build number rather than a version number. So "Sublime Text" caught my eye in the docs. After looking into the LSP option, I finally figured out I'm on version 4 and the LSP path was the right one.

Should Sublime Text 3 be removed entirely from this part of the guide? Or at the very least moved below the LSP recommendations so folks on a modern version of ST4 follow the right path?

Happy to submit a PR either way. Thanks!

**Comment by ichard26** [comment]
Depending on how much Sublime Text 3 is still in use, we can either get rid of sublack recommendation, OR keep it and gently discourage people to instead use LSP.

Thanks for filing an issue, sorry for taking so long to get back to you!

**Comment by Raghav-Bell** [comment]
I would like to work on this issue, please elaborate more how can i close this issue ?
