### ISSUE TITLE
Do not collapse adjanced string concatenation

### ISSUE THREAD

**Issue by KAction** [psf/black#3001]
Python allows splitting long string using following syntax (note lack of comma)

```python
def quite_short():
    return ("foo"
            "bar")

def very_long():
	return ("57bacf6898da8b257bc5b0c1d6b13e9a7551f17ea30a0a306eaa68f51243fcbc"
		    "f2b176250dbc8eae0c97650396658c28576a18e3ec8759d6fcfedabbf8577a5d")
```

Resulting value is concatenation of parts, without any separator. Here is how black(1)
reformats this snippet:

```python
def quite_short():
    return "foo" "bar"


def very_long():
    return (
        "57bacf6898da8b257bc5b0c1d6b13e9a7551f17ea30a0a306eaa68f51243fcbc"
        "f2b176250dbc8eae0c97650396658c28576a18e3ec8759d6fcfedabbf8577a5d"
    )
```

New formatting of `very_long` function looks consistent with how
black(1) does parensis in general, but new formatting of `quite_short`
looks odd. I think it would be better to either make it one string:

```
	return "foobar"
```

or, even better, keep it as multiline assuming programmer had reason to format it
this way:

```
	return (
		"foo"
		"bar"
	)
```

```
; black --version
black, 22.1.0 (compiled: no)
```

**Comment by JelleZijlstra** [comment]
This is implemented in the preview mode (and previously in `--experimental-string-processing`). We'll hopefully turn it on by default at the end of the year.
