### ISSUE TITLE
Add support for structural pattern matching (match...case) new in 3.10

### ISSUE THREAD

**Issue by jimmyx0x** [psf/black#3005]
**Is your feature request related to a problem? Please describe.**

Black does not support the new [structural pattern matching](https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching) pattern in 3.10

**Describe the solution you'd like**

Add `match...case` to the parser

**Describe alternatives you've considered**

**Additional context**

**Comment by JelleZijlstra** [comment]
We already support this; see the issue @dignissimus linked.
