### ISSUE TITLE
'exclude' in configuration toml file does not work as expected

### ISSUE THREAD

**Issue by ankitanallana-livongo** [psf/black#3013]
**'exclude' in `pyproject.toml` does not exclude the file**

In the root directory of my project I added a `pyproject.toml` file and added `exclude = 'build.py` and I execute `pre-commit  run` in my terminal. But `build.py` is still modified

**To Reproduce**

1. Create a sample project directory with folders like src, test
2. In the project directory create this configuration file `pyproject.toml`: 
``` # Configuration for black pre-commit
[tool.black]
exclude = '''
build.py
'''
```

^ I also tried with single quotes, no quotes, `extend-exclude`, `^/build.py` but doesn't look like it works :(

`build.py` set up as:
```
name="My Project"
organization="company"
version="5.1.0"
```
3. Install `pre-commit` with this yaml:
```
repos:
-   repo: https://github.com/psf/black # Black - reformats code
    rev: 22.3.0
    hooks:
      - id: black
```
4. Run this from terminal - `$ pre-commit run`
5. You will see that `black` has added spaces in `build.py` 

**Expected behavior**

`build.py` to be untouched, unmodified.

**Environment**

- Black's version: 22.3.0
- OS and Python version: MacOS Catalina/Python3.9

**Additional context**

When I run `$ black . --exclude build.py` I see that it correctly skips the `build.py`.

**Comment by JelleZijlstra** [comment]
Have you tried the `force-exclude` option? We added that option for exactly this reason.

**Comment by ankitanallana-livongo** [comment]
@JelleZijlstra oh my god that worked!! I must have missed that option, apologies!! and big thanks!! :)

**Comment by ichard26** [comment]
Perhaps we should document this issue in the FAQ? Using pre-commit with Black is pretty common. I'd suggest pre-commit's exclude configurations first, and then black's force-exclude.

**Comment by ichard26** [comment]
Could also document it here: https://black.readthedocs.io/en/stable/integrations/source_version_control.html 

I thought we already documented this quirk there while writing the previous comment, but apparently not!
