### ISSUE TITLE
Who is correct on flake8 E0203

### ISSUE THREAD

**Issue by boatcoder** [psf/black#3021]
**Describe the bug**

Flake8 E0203 doesn't like spaces before colons
Black is placing spaces before colons in the code below
Personally I agree with Flake8 on this one but I'm not sure who is "right" here

**To Reproduce**

Take this code:

```python
    @staticmethod
    def id_from_lookup_key(lookup_key: str) -> int:
        if lookup_key.startswith(Price.LOOKUP_KEY_PREFIX):
            return short_url.decode_url(
                lookup_key[len(Price.LOOKUP_KEY_PREFIX) :] # Colon has a space in front of it after black formats it
            )
        raise LookupKeyError(
            f"'{lookup_key}' is not a valid Price LookupKey"
        )
```

And run it with these arguments:

```sh
$ black file.py --target-version py39 --line-length 110
```

The resulting error is:

> No error is reported but the space is between the `)` and the `:`

**Expected behavior**

I expect the colon to be next to the paren and the ]. `):]` vs `) :]`

**Environment**

- Black's version: black, 22.1.0 (compiled: yes)
- OS and Python version: MacOS 12.2.1/Python 3.10.2]

**Additional context**

**Comment by JelleZijlstra** [comment]
https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
