### ISSUE TITLE
Add documentation for full list of config values for black

### ISSUE THREAD

**Issue by hopper-signifyd** [psf/black#3024]
[This page](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html) in the docs has the following text:

> You've probably noted that not all of the options you can pass to Black have been covered. Don't worry, the rest will be covered in a later section.

However, I looked through the rest of the docs, and couldn't find this fabled "later section". Does it exist? If so, can the docs be updated to just link to that section instead of alluding to it? If it doesn't exist, can someone who is familiar with all of the black config options please add it?

**Comment by JelleZijlstra** [comment]
#2839 should do this. Unfortunately I haven't had the chance to fix the linking issues in that PR.

**Comment by hauntsaninja** [comment]
Closing since the PR mentioned has been merged

**Comment by hopper-signifyd** [comment]
Thank you!
