### ISSUE TITLE
Add custom configuration file with precedence over pyproject.toml

### ISSUE THREAD

**Issue by pedrorrivero** [psf/black#3027]
**Is your feature request related to a problem? Please describe.**

When working with a new project is often difficult to find out where the developers have placed all the configs for the different tools they are using. Some choose to add then to `pyproject.toml`, others to `tox.ini`, others to `setup.cfg`, others write the settings for some tools in one place, and the settings for other tools in another... this is most definitely confusing for new contributors, and in many cases cannot be avoided by the developers themselves, as, in practice, there does not seem to be a standardize place to list configs.

**Describe the solution you'd like**

Since black already supports providing a custom config file through the `--config` flag, it would be very easy to add a custom black configuration file (e.g. `.black.toml`) that takes precedence automatically over `pyproject.toml` when searching for custom configs (i.e. if it does not exist, it will fallback to `pyproject.toml` so no breaking changes would occur). This would enable developers who like to keep all their configs in separate files to at least be able to do that consistently when using Black, at no formal cost for anyone.

**Describe alternatives you've considered**

More and more packages seem to be adding support for configs in `pyproject.toml`, nonetheless this process is slow, and the more tools a software project uses, the more difficult it becomes to handle that one massive file. Migrating configs is also easier if we can just copy and paste one file for each tool that we want to reuse.

**Comment by JelleZijlstra** [comment]
We more frequently get complaints from people who don't want a plethora of different configuration files.

We will not add support for an additional standdard configuration file. This helps keep our config discovery simple and straightforward.

You can use the `--config-file` option to use a different config file than `pyproject.toml` if you want. #2525 (which we'll eventually merge) should also be helpful for your use case.

**Comment by felix-hilden** [comment]
Thank you for the thoughtful request, but I'm not really in favor. The CLI argument does enable using different file names, and going against the standard that is (or will be) pyproject.toml seems odd.
