### ISSUE TITLE
black should allow sorting functions/definitions in a module/scope

### ISSUE THREAD

**Issue by uriva** [psf/black#3029]
Formatters increase consistency, which helps readability.
In other words they reduce noise, which can be defined as variability with no attached meaning.

For example - 2 lines instead of one may imply some meaning, but may also be just an arbitrary design choice.
Whenever our minds have to handle with >1 options to interpret something, we have to invest more energy to understand what's going on.

Black does a great job at reducing a lot of ambiguity by rewriting the code.
In other words it takes a degree of freedom, that has no clear signal in it.
It knowingly leaves imports as they are because we have `isort` and that works well.

However there is another recurring thing in my codebase that has extreme variability and no signal - the ordering functions in a module.

In theory functions which have some commonality should be placed in their own module, but often this is not the case. Most of the time function ordering is completely arbitrary and makes it difficult to know your way around a new file. Sometimes the ordering of names in the module global scope are just by their dependencies (a language limitation).

So what I would like is for black to have a mode (that should eventually be the default) which sorts files in a module.

There are two ways to do it:
1. by their dependencies of each other / topological sort
2. by some lexicographic ordering

I'm not sure which is best.

For simplicity, I'd do the latter, for the reason we already have IDEs that make it easy to jump to dependencies, and we don't want large diffs when we just delete a single function call.
But for a more "story-like" reading of the module, probably the first is better.

Similarly I would like it to sort lines of code within a scope, by the same kind of logic.

So some trivial examples:

```python
def a():
  return b()


def b():
  return 1
```

should become

```python
def b():
  return 1


def a():
  return b()
```

and

```python
y = 8
x = 7
x = x + 1
z = x + y
```

should become
```python
x = 7
x = x + 1

y = 8

z = x + y
```

**Comment by JelleZijlstra** [comment]
Ordering functions, let alone variable declarations, is far too risky. Code may rely on ordering in lots of ways, e.g. through decorators, references in annotations, etc. You're welcome to create a separate tool that performs sorting, but it's out of scope for Black.

**Comment by stefaneidelloth** [comment]
Related: https://stackoverflow.com/questions/76611154/how-to-automatically-sort-functions-in-classes-by-their-usage-and-visibility
