### ISSUE TITLE
Space before slice colon is not always omitted when slice parameter is omitted

### ISSUE THREAD

**Issue by RobbeSneyders** [psf/black#3039]
**Describe the bug**

[PEP8 Whitespace in Expressions and Statements](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements) says:

> However, in a slice the colon acts like a binary operator, and should have equal amounts on either side (treating it as the operator with the lowest priority). In an extended slice, both colons must have the same amount of spacing applied. Exception: when a slice parameter is omitted, the space is omitted:

This exception is not followed by black when the slice parameter that is present is parenthesized.

**To Reproduce**

For example, take this code:

```python
def test():
    api_base_path = scope.get('root_path', '')[len(original_scope.get('root_path', '')):]
```

Black formats this as:
```python
def test()
    api_base_path = scope.get("root_path", "")[
        len(original_scope.get("root_path", "")) :
    ]
```

Which leads to style checks failing with `E203`

This is not the case if the `len()` call is replaced with a variable name:

```python
def test():
    api_base_path = scope.get('root_path', '')[very_looooooooooooooooooong_variable_name:]
```

Black formats this correctly as:
```python
def test()
    api_base_path = scope.get("root_path", "")[
        very_looooooooooooooooooong_variable_name:
    ]
```

**Expected behavior**

No space before `:`

```python
def test()
    api_base_path = scope.get("root_path", "")[
        len(original_scope.get("root_path", "")):
    ]
```

**Environment**

- Black's version: 22.3.0
- OS and Python version: Linux/Python 3.8.10

**Comment by musebc** [comment]
I think that is covered here: https://black.readthedocs.io/en/latest/contributing/issue_triage.html#black-formatted-code-is-violating-flake8-s-e203
