### ISSUE TITLE
Separated strings the don't exceed width restriction are separated with no parenthesis

### ISSUE THREAD

**Issue by mafranks** [psf/black#3042]
**Description**

If you have a string that is separated on two lines with a \ and is shorter than the maximum width allowed, it does not get formatted properly by black.

**To Reproduce**

Create a string on two lines such as:
```
variable1 = "blahblahblahblah.blahblahblahblahblah." \
            "klfdfasdfasdfasblahblahblah"
```

Run black and you'll get this invalid string:
```
variable1 = "blahblahblahblah.blahblahblahblahblah." "klfdfasdfasdfasblahblahblah"
```

**Expected behavior**

The output expected would be either:
```
variable1 = "blahblahblahblah.blahblahblahblahblah.klfdfasdfasdfasblahblahblah"
```
or 
```
variable1 = (
    "blahblahblahblah.blahblahblahblahblah." 
    "klfdfasdfasdfasblahblahblah"
)
```

**Environment**

- Black's version: 22.3.0 (compiled: yes)
- OS and Python version: MacOS 12.3.1, Python 3.10.3

**Comment by JelleZijlstra** [comment]
Black's output is not invalid, only ugly.

This will be fixed by the experimental string processing feature, which is enabled by the `--preview` flag. We'll hopefully enable it by default for Black 23.1.0.
