### ISSUE TITLE
Failed for python3.10

### ISSUE THREAD

**Issue by mikesongming** [psf/black#3047]
**Describe the bug**
Failed to call black in python3.10 environment on MacOSX, which fixed after upgrading typed_ast by PIP.

**To Reproduce**

For example, take this code:

```sh
$ black file.py 
```

The resulting error is:

> Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/ci/bin/black", line 6, in <module>
    from black import main
  File "/Users/mike/opt/anaconda3/envs/ci/lib/python3.10/site-packages/black.py", line 45, in <module>
    from typed_ast import ast3, ast27
  File "/Users/mike/opt/anaconda3/envs/ci/lib/python3.10/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3

Problem solved after upgrading typed_ast by:
```sh
pip install typed-ast --upgrade
```

**Expected behavior**

**Environment**

- Black's version:   version 19.10b0
- OS and Python version:    Python 3.10.4 on MacOSX-10.16-x86_64

**Additional context**

**Comment by felix-hilden** [comment]
Thanks for reporting. I think the problem is solved however, since the version you are using is almost three years old and we only require `typed_ast` for Python < 3.8. This was changed in a commit last year it seems: https://github.com/psf/black/commit/ed9d58b7410f24446cedebd0f767b71b154f5f5b
