### ISSUE TITLE
Literal string not formatted correctly

### ISSUE THREAD

**Issue by thedemons** [psf/black#3060]
**For some reason, the shorter line is formatted but the longer one isn't**

**To Reproduce**
These lines of code:
```python
PW_PATTERN = "08 00 00 00 09 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
ID_PATTERN = "01 00 00 00 0B 00 00 00 0D 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
```
Will be formatted like this:
```python
PW_PATTERN = (
    "08 00 00 00 09 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
)
ID_PATTERN = "01 00 00 00 0B 00 00 00 0D 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
```

**Expected behavior**
The longer one (ID_PATTERN) should be formatted instead of the shorter (PW_PATTERN) one.

**Environment**

- Black's version: 22.3.0
- OS and Python version: Windows 10, Python 3.10.2

**Comment by felix-hilden** [comment]
The shorter line fits the line length after formatting. The longer cannot, but when `--preview` is enabled, our new string processing will split the string in half. Does that work?

**Comment by thedemons** [comment]
> The shorter line fits the line length after formatting. The longer cannot, but when `--preview` is enabled, our new string processing will split the string in half. Does that work?
> 
> ```python
> PW_PATTERN = (
>     "08 00 00 00 09 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
> )
> ID_PATTERN = (
>     "01 00 00 00 0B 00 00 00 0D 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??"
>     " ?? ?? ?? ?? ?? ?? 00 00 00"
> )
> ```

Yes that works perfectly, but it seems to also format the lines with `# fmt: off` (meant to be skipped)
Is there a workaround?

Thanks.

**Comment by felix-hilden** [comment]
What's your situation exactly? Doesn't do that for me:

```python
PW_PATTERN = (
    "08 00 00 00 09 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
)
ID_PATTERN = (
    "01 00 00 00 0B 00 00 00 0D 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??"
    " ?? ?? ?? ?? ?? ?? 00 00 00"
)

# fmt: off
PW_PATTERN = "08 00 00 00 09 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
ID_PATTERN = "01 00 00 00 0B 00 00 00 0D 00 00 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00"
# fmt: on
```

Although I did find another issue 😅

**Comment by felix-hilden** [comment]
A gentle ping @thedemons: do you still have issues? It's unclear if there is a problem, so I'm tempted to close this issue for housekeeping.

**Comment by thedemons** [comment]
> A gentle ping @thedemons: do you still have issues? It's unclear if there is a problem, so I'm tempted to close this issue for housekeeping.

Oh sorry I'll close this now, the issue has been solved by enabling `--preview`, thank you!
