### ISSUE TITLE
Black module coredumps numerous times when PyCharm updates its indices

### ISSUE THREAD

**Issue by ajgringo619** [psf/black#3064]
**Describe the bug**

Whenever PyCharm CE decides to download/update its indices, I get 10+ coredump messages in the systemd journal:

```
May 09 10:06:24 systemd-coredump[12581]: [🡕] Process 12577 (python3) of user 1000 dumped core.
                                         
                                         Module /home/ajgringo619/.local/lib/python3.10/site-packages/black/parsing.cpython-310-x86_64-linux-gnu.so with build-id 97a72e588bd4d797512c9adcca045a4ecd8f48e1...
░░ Subject: Process 12577 (python3) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 12577 (python3) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
```

**To Reproduce**

Start PyCharm CE and open a project

**Expected behavior**

N/A

**Environment**

- Black's version: 22.3.0
- OS and Python version: EndeavourOS, kernel 5.17.5-zen, python 3.10.4

**Additional context**

I have no history of installing this module manually, so I'm guessing that it was installed by PyCharm (not as a system package, but a user-installed module). The system package does exist, so maybe that's an option.

**Comment by hauntsaninja** [comment]
Unfortunately, this isn't enough to reproduce the issue. Is this something you're still facing? Can you repro without PyCharm?
