### ISSUE TITLE
Ugly string concat 

### ISSUE THREAD

**Issue by blankRiot96** [psf/black#3066]
**Describe the style change**

Black made this unusual ugly change to my code after I made the string longer. 

**Examples in the current _Black_ style**

```python
    webbrowser.open(
        "https://github.com/Matiiss/" f"pygame_examples/tree/main/pgex/examples/{name}"
    )
```

**Desired style**

```python
    webbrowser.open(
        "https://github.com/Matiiss/"
        f"pygame_examples/tree/main/pgex/examples/{name}"
    )
```

**Additional context**

The ugly code I posted passed `black` linting checks for 3.7-3.10 
https://github.com/Matiiss/pygame_examples/pull/61/commits/62cd38961be197969e18e82fe043d521d8704acf

**Comment by felix-hilden** [comment]
Applying `--preview` will use our new string processing to merge the two strings. Would that work?

```python
if True:
    webbrowser.open(
        f"https://github.com/Matiiss/pygame_examples/tree/main/pgex/examples/{name}"
    )

```

**Comment by blankRiot96** [comment]
@felix-hilden Hey, thanks for the reply
That's definitely better, but not my desired code style
I think that's a fine solution if that's how the original code was, in my case however the original code was the desired code, in which case IMO it should stay the same
