### ISSUE TITLE
fmt skip wipes comments out from the line above

### ISSUE THREAD

**Issue by DStauffman** [psf/black#3076]
**Describe the bug**

When a `#  fmt: skip` is on a given line, any preceeding comments directly above the given line will be deleted.

**To Reproduce**

For example, take this code:

```python
# Comment about this line below
data = [ True,  True, False]  # fmt: skip
```

```sh
$ black file.py --target-version py310
```

The resulting file is:
```python
data = [ True,  True, False]  # fmt: skip
```

**Expected behavior**

The comment line should have remained unchanged.

**Environment**

- Black's version: black, 22.3.0 (compiled: yes)
- OS and Python version: Windows 10, Python 3.10.4

**Additional information**

If you have multiple comment lines directly above the fmt skip line, they will all be deleted.

I was also able to reproduce this on the Black Playground webpage.

**Comment by DStauffman** [comment]
Sorry, this is a duplicate of #2339.  I missed that one earlier.

**Comment by ichard26** [comment]
No worries, thanks for investigating eitherway!
