### ISSUE TITLE
ImportError: GitWildMatchPatternError missing from pathspec

### ISSUE THREAD

**Issue by danibene** [psf/black#3088]
**Describe the bug**

I could not import black without changing the pathspec library, despite both black and pathspec being the newest versions.

**To Reproduce**

```python
import black
```

The resulting error is:

> ImportError: cannot import name 'GitWildMatchPatternError' from 'pathspec.patterns.gitwildmatch' (C:\Users\myusername\anaconda3\envs\myenv\lib\site-packages\pathspec\patterns\gitwildmatch.py)

I tried updating both black and pathspec:
`pip install -U black`
`pip install -U pathspec`

Neither of those worked, so I copied and pasted the following from the [pathspec GitHub](https://github.com/cpburnz/python-path-specification/commit/ed4481f2d2708d47a25e828fd5be8980fbcfe1f4)

```
class GitWildMatchPatternError(ValueError):
	"""
	The :class:`GitWildMatchPatternError` indicates an invalid git wild match
	pattern.
	"""
	pass
```
After adding that to `C:\Users\myusername\anaconda3\envs\myenv\lib\site-packages\pathspec\patterns\gitwildmatch.py`,  there was no ImportError

**Environment**

- Pathspec's version: 0.9.0
- Black's version:   22.1.0
- OS and Python version:  Windows/Python 3.9.12

**Comment by JelleZijlstra** [comment]
You almost certainly have something unusual going on in your environment (maybe anaconda and pip installed different versions of pathspec?). pathspec 0.9.0 was released in July 2021; if it didn't work with Black, we'd have noticed by now. I checked the conda-forge package for it at https://anaconda.org/conda-forge/pathspec/files and `GitWildMatchPatternError` is present.

**Comment by danibene** [comment]
Seems like there is a mismatch between pip and anaconda, `pip show pathspec` returned `Version: 0.9.0` with my environment activated but I now looked at the version in anaconda navigator & it's 0.7.0.

Thank you for checking & getting back to me so quickly!
