### ISSUE TITLE
Add magic-trailing-comma newline to function definition and call.

### ISSUE THREAD

**Issue by synchronizing** [psf/black#3093]
The latest release, [22.3.0](https://github.com/psf/black/releases/tag/22.3.0), issue #2918, PR #2942, has broken formatting for function definition and call. In previous versions of Black the following: 

```python
def intentional_comma(a: int, b: int, c: int,) -> int:
    return a + b + c

def intentional_comma(a: int, b: int, c: int,):
    return a + b + c

intentional_comma(a=10, b=20, c=30,)
```

Would be formatted to:

```python
def intentional_comma(
    a: int, 
    b: int, 
    c: int,
) -> int:
    return a + b + c

def intentional_comma(
    a: int, 
    b: int, 
    c: int,
):
    return a + b + c

intentional_comma(
    a=10, 
    b=20, 
    c=30,
)
```

But the new versioning breaks this, and the above is now formatted as:

```python
def intentional_comma(a: int, b: int, c: int,) -> int:
    return a + b + c

def intentional_comma(
    a: int, b: int, c: int,
):
    return a + b + c

intentional_comma(
    a=10, b=20, c=30,
)
```

**Comment by zsol** [comment]
I [can't repro](https://zsol.github.io/format/#IyBQeXRob24gY29kZSBnb2VzIGhlcmUKZGVmIGludGVudGlvbmFsX2NvbW1hKGE6IGludCwgYjogaW50LCBjOiBpbnQsKSAtPiBpbnQ6CiAgICByZXR1cm4gYSArIGIgKyBjCgpkZWYgaW50ZW50aW9uYWxfY29tbWEoYTogaW50LCBiOiBpbnQsIGM6IGludCwpOgogICAgcmV0dXJuIGEgKyBiICsgYwoKaW50ZW50aW9uYWxfY29tbWEoYT0xMCwgYj0yMCwgYz0zMCwpCiAgICAgICAg) this, how are you invoking Black?
