### ISSUE TITLE
where can users get latest version of blib2to3?

### ISSUE THREAD

**Issue by CudaText-addons** [psf/black#3101]
Current Black code needs the blib2to3. where can I get it? PyPI doesn't have it.

**Comment by ichard26** [comment]
The distribution packages for Black on PyPI come with blib2to3. Black actually contains three packages: 1) black, 2) blib2to3, and 3) blackd (although most people don't care about this, and not us here). Peeking into a 22.3.0 wheel for Linux CPython 3.8, the blib2to3 sources are part of the distribution:

![image](https://user-images.githubusercontent.com/63936253/172011638-775ea42f-0492-436c-9e33-5b376aa3a8ec.png)

(if you use the pure python wheel, you won't have any compiled C code in the distribution aka no `.pyd` or `.so`)

Why do you need the latest version of blib2to3 independent of Black? You can always download blib2to3 from GitHub by cloning the repo and extracting the `src/blib2to3` directory, but you really shouldn't have to.
