### ISSUE TITLE
is library 'attr' still needed?

### ISSUE THREAD

**Issue by CudaText-addons** [psf/black#3104]
I have old code from 2020 which used 'attr' lib in Black.
folder of 'attr':
```
$ ls
_cmp.py     converters.py   filters.py   __init__.pyi  setters.py      _version_info.py
_cmp.pyi    converters.pyi  filters.pyi  _make.py      setters.pyi     _version_info.pyi
_compat.py  exceptions.py   _funcs.py    _next_gen.py  validators.py
_config.py  exceptions.pyi  __init__.py  py.typed      validators.pyi
```

I dont see .pyc files created here! so its not used?

**Comment by JelleZijlstra** [comment]
Thanks for your interest in Black, but this issue tracker isn't the place for discussion of your plugin.

You can see Black's dependencies here: https://github.com/psf/black/blob/main/setup.py#L98. `attrs` is no longer a dependency.

**Comment by ichard26** [comment]
We can help you fix / update your plugin, but we are not going to rewrite the project for you. Feel free to ask questions in the #black-formatter channel on [Python Discord](https://discord.gg/RtVdv86PrH).
