### ISSUE TITLE
Bugs maybe

### ISSUE THREAD

**Issue by erney83** [psf/black#3105]
**Describe the bug**

**To Reproduce**

For example, take this code:

```python
this = "code"
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

The resulting error is:

> cannot format file.py: INTERNAL ERROR: ...

**Expected behavior**

**Environment**

- Black's version: 
- OS and Python version: 

**Additional context**

**Comment by hauntsaninja** [comment]
I can't reproduce. Could you provide more information, such as the complete output and your version of black? Alternatively, see if you can create and link a reproducer on the Black playground: https://black.vercel.app

**Comment by JelleZijlstra** [comment]
This is just the template (https://github.com/psf/black/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). If you have a real bug to report, please do so clearly.
