### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by damianquijano** [psf/black#3127]
**Black v22.3.0**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACxAItdAD2IimZxl1N_Wljc2jrrX_BKLB5HI67_HQAIiMuwMWsXAPFTz7lRSMAhDpoIDfJDurO2NJkYG_W7_S_YmFIyKNfpE5CBOVFhB8dOwfTbAzegufY_1MKXDvGDBupJwqVD24QWCrsiVKXa8UufKGK28LMbZP4AhD7ajw1c6KWNSfdn-7Tbakc7ibESLPgAAJtl8Cnt1AtuAAGnAbIBAAAdMJVMscRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
f = None
for i in range(5):
with open("app.log", "w") as f:
if i>2:
break

print(f.closed)
```

## Output

```python
Cannot parse: 3:0: with open("app.log", "w") as f:
```

## Expected

**Comment by jack1142** [comment]
This isn't valid Python code so Black correctly errors out here.
```
λ py -3.10 3127.py
  File "C:\Users\Jakub\OneDrive\Dokumenty\3127.py", line 3
    with open("app.log", "w") as f:
    ^
IndentationError: expected an indented block after 'for' statement on line 2
```

**Comment by ichard26** [comment]
And before any comment is made that Black should fix such indentation issues, that's way too complicated for little gain so no.
