### ISSUE TITLE
Add documentation for format_cell() function. 

### ISSUE THREAD

**Issue by Hangzhi** [psf/black#3131]
Function [format_cell()](https://github.com/psf/black/blob/162ecd1d2cf9471efefb5b61c17d28b73acb79a1/src/black/__init__.py#L1055) hasn't been documented yet.  
It could be helpful for users to have it documented.

**Comment by felix-hilden** [comment]
We're not committed to a public Python API yet, but let's discuss whether or not to include this in #779!
