### ISSUE TITLE
(🐞) 22.6.0 isn't compiled / doesn't have any wheels available

### ISSUE THREAD

**Issue by KotlinIsland** [psf/black#3140]
```
> black --version     
black, 22.6.0 (compiled: no)
Python (CPython) 3.10.5
```

Is this intentional? I couldn't find any information regarding dropping of mypyc compiled wheel support.

**Comment by ichard26** [comment]
No, I just build them after cutting the release. Gimme 15-30 minutes and they'll be uploaded.

**Comment by cooperlees** [comment]
Just out of curiosity - did you notice a large speed regression? What made you need the compiled versions?

**Comment by KotlinIsland** [comment]
I just saw that there were no wheels in the release and wondered why

**Comment by ichard26** [comment]
OK, so thanks to some technical difficulties, I _just_ started to upload the Linux, Windows, and MacOS (**arm only**) wheels. I hope I can get the universal2 and x86_64 wheels for MacOS up soon.

**Comment by ichard26** [comment]
mypyc wheels are now available for all supported platforms.
