### ISSUE TITLE
Playground seems to be broken

### ISSUE THREAD

**Issue by ParitoshSingh07** [psf/black#3145]
Seems like most of this report is prefilled, hopefully it has all the necessary details. I was trying to use the playground to check things, and it seems like it's just erroring out. I changed out my actual code to something very simple and the issue seems to persist.

**Black v22.6.0**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB7AFddAD2IimZxl1N_Wlws4TBexXdmg613D2W2vO1gykBlg0ElxjidjH2deuosqH32nmM8xj1PdbPxzNWkHiZyYJ80c_DpGmoskeYwGs6I3pBda0cQKIm6K1uk0gAAqicNSjMQmpIAAXN8CaInfR-2830BAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
if True:
    print(42)
```

## Output

```python
bool object expected; got None
```

## Expected
```python
if True:
    print(42)
```

**Comment by Shivansh-007** [comment]
I think this should be filed at the playground's repo rather, https://github.com/jpadilla/black-playground/issues
