### ISSUE TITLE
Release 22.8.0 (August)

### ISSUE THREAD

**Issue by ichard26** [psf/black#3163]
**Disclaimer**: I've seen [pip](https://github.com/pypa/pip/issues/11238) and [mypy](https://github.com/python/mypy/issues/13089) use release planning issues. I've got a lot of free time for the time being so I'm curious to whether they would be of any benefit for this project (especially since our development is quite casual). FWIW I don't expect this to be as active as those seen in mypy.

Also, since I'm tentatively assuming I'll be the RM, I'm using a release milestone (https://github.com/psf/black/milestone/1) since it helps me decide and keep track on what should/needs to be done. My memory is poor and always out of room >.<

---

So we dropped the ball on our target release schedule of one per month with 22.6.0 coming three months after the previous release. In fairness to us, we, the core team, were pretty busy so there wasn't much in main to justify a release until a much larger period of time had passed. Now that I should at least have more free time, I'm happy to aim for monthly releases for the time being. Anyway, it'd be nice to get bugfixes and other improvements out more quickly since formatting stability is no longer a huge concern (thanks to the stability policy).

P.S. co-maintainers, would any of you like to be the release manager this time around? I'm happy to handle this month's release, but it'd be good to build experience among the core team (so hi @felix-hilden). I'll assign myself for the time being, but if you would like to be the RM, please lemme know and reassign the issue!

**Comment by cooperlees** [comment]
Should we look at the last release issues or have they all been sorted?

- Docs building / read the docs moving on release
   -  Since we have a stable policy do we just move the stable tag right away?
- How do we release the mypyc wheels?
  - Is there automation now we can drive?
    - Looks like we trigger https://github.com/ichard26/black-mypyc-wheels/blob/main/.github/workflows/build.yaml
  - Should we add instructions to release docs https://black.readthedocs.io/en/stable/contributing/release_process.html or link to https://github.com/ichard26/black-mypyc-wheels and add docs there? 

Was there anything else we should tidy up?

**Comment by JelleZijlstra** [comment]
Thanks for picking this up @ichard26! I'm happy with your plan.

To @cooperlees's point, I'd favor moving the "stable" tag right away on releases. The current system just makes us forget to move it until someone reminds us.

**Comment by felix-hilden** [comment]
Sounds good! I'm down to learning the release stuff, but I'll be quite busy for the next couple of weeks with moving and starting a new job. So maybe the next release?

**Comment by ichard26** [comment]
FYI, I plan on converting the stable tag into a branch as part of this release. It makes more sense for the vim integration and I'd love to see if stable being a branch fixes our weird issues with RTD. **If anyone thinks I shouldn't convert it, please holler ASAP.**

I don't have a target date for 22.7.0 since I still need to work on the release automation, but July 31st would be the worst case scenario.

**Comment by ichard26** [comment]
OK, once #3197 and #3190 are landed, I'll cut 22.7.0. I might be able to get #2656 updated and landed too, but I won't hold my breath. I've already reduced the scope for this release since I have limited time. If this release ends up in flames, you'll know who to blame :sweat_smile:

**Comment by ichard26** [comment]
Another update, so I discussed with the core team and we decided to postpone the release entirely and skip 22.7.0 so we have enough time to make sure our release automation is in good shape.

**Comment by ichard26** [comment]
Release 22.8.0 has been cut! :tada: The mypyc wheels built without incident using the new automation that's in-place and almost everything else went smoothly. Unfortunately I broke the macOS native executable so there won't be one available for 22.8.0 unless people need it soon (see also https://github.com/psf/black/issues/3250).
