### ISSUE TITLE
Upcoming aiohttp 4.0 is breaking our test suite with a new deprecation warning

### ISSUE THREAD

**Issue by ichard26** [psf/black#3176]
See https://github.com/ichard26/black-deps-ci/runs/7374216061?check_suite_focus=true. We can either bump the lower bound requirement for aiohttp, or we can reuse the approach taken in https://github.com/psf/black/pull/2974/ for a similar issue. I'll note that aiohttp 4.0 is still under development so breakage will come later, but eventually :)

cc @zsol we should probably configure pytest to _not_ error out on warnings when running under mypy_primer since it'd be pointless busywork and noise for them.

**Comment by graingert** [comment]
> cc @zsol we should probably configure pytest to not error out on warnings when running under mypy_primer since it'd be pointless busywork and noise for them.

Does mypy_primer run the black test suite?

**Comment by ichard26** [comment]
@graingert There's a PR to make it do so: https://github.com/hauntsaninja/mypy_primer/pull/41

**Comment by shivamdurgbuns** [comment]
So @ichard26 what is required to fix this, I can work on it.

**Comment by graingert** [comment]
@shivamdurgbuns simplist fix is to append the relevant ignore to filterwarnings https://github.com/psf/black/blob/main/pyproject.toml#L51

**Comment by shivamdurgbuns** [comment]
@graingert Understood! Will do accordingly.
