### ISSUE TITLE
Black prints succes to stderr

### ISSUE THREAD

**Issue by trbjo** [psf/black#3178]
Version:
`python-black 22.6.0-1`

Distro: 
Arch Linux

To reproduce the error:
`/usr/bin/black - <<< "import os" 2>/dev/null`

I think this is wrong behavior. It makes it harder to use formatting tools in text editors such as https://github.com/mitranim/sublime-fmt, because the tools relies on the correct streams.

**Comment by ichard26** [comment]
Yup, just for context for anyone else who stumbles across this issue, the general advice for STDOUT/STDERR is that all user-readable status messages should go to STDERR, not just error messages. Why? to separate them from the data being operated on, this makes using Black's via STDIN or with `--diff` much nicer (no manual filtering of the output is needed, just capture the STDOUT). 

See also https://github.com/psf/black/issues/1285.

**Comment by trbjo** [comment]
I know you are probably not going to change the behavior, but I think an approach that would be more in line with the rest of the Unix command line tools would be to simply print nothing on success.

**Comment by createyourpersonalaccount** [comment]
@trbjo just use `--quiet`
