### ISSUE TITLE
multi-line declaration incorrectly concatenated

### ISSUE THREAD

**Issue by tsmorrill** [psf/black#3181]
Some multi-line function declarations are concatenated to a single oversized line.

For example,
```
def freezer() -> Callable:
    ...
    def freezer_func(
        pitch,
        vel,
        time: float,
        s: int,
        t: int
    ) -> tuple[list, float]:
        ...
    return freezer_func
```
becomes
```
def freezer() -> Callable:
    ...

    def freezer_func(pitch, vel, time: float, s: int, t: int) -> tuple[list, float]:
        ...

    return freezer_func
```

This can be reproduced on the online formatter.

**Comment by ChrisLovering** [comment]
If you'd like to retain the multi-line function signature, you can add a trailing comma to the last argument. EG ```
def freezer() -> Callable:
    ...
    def freezer_func(
        pitch,
        vel,
        time: float,
        s: int,
        t: int,
    ) -> tuple[list, float]:
        ...
    return freezer_func
```

This behaviour is described in this section of the docs https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas

**Comment by tsmorrill** [comment]
I appreciate the solution given and will incorporate it into my code.

Doesn't this report also indicate that Black is incorrectly calculating the length of lines? The documentation referenced above states that Black will collapse collections into one line if they fit. The example given does not fit on one line.

**Comment by tsmorrill** [comment]
I understand now; I was expecting 79. I will update my pyproject.toml.
