### ISSUE TITLE
format json file error

### ISSUE THREAD

**Issue by HengyueLi** [psf/black#3200]
**Describe the bug**

cmd `black *` in project raise error for a json file

**To Reproduce**

Context in json file (`test.json`): `{"1": "\"z=1"}`
Without black, Python can load this file by `json.loads(open("test.json",'r').read())`
With black formatting (I like to run `black *` in project), read the json file failed: `json.decoder.JSONDecodeError: Expecting value...`
I checked the output of black, content of `test.json` is: `{"1": '"z=1'}` (this causes error)

**Environment**

- Black's version:  `black, 22.3.0 (compiled: yes)`
- OS and Python version: Python 3.8.7, [Clang 11.0.0 (clang-1100.0.33.17)] on darwin

**Comment by ichard26** [comment]
Black does not check the file extension for files passed directly on the command line. You can pass a file with a `.js` extension and if it is valid Python, Black will happily reformat it, possibly in a way that makes it invalid JS. That's what is happening here, by running `black *` at the root of the project, you're asking your shell to take all of the files and directories in the root and pass them to Black -- that includes your JSON file. If you have `process.py`, `data.json` and `some-directory`, running `black *` really does `black process.py data.json some-directory`.

Try running `black .` instead which won't be expanded by your shell. You'll still be asking Black to format the whole project, but you'll be letting Black discover and filter out non-Python files (according to the default `--include` and `--exclude` regexes).
