### ISSUE TITLE
Incorrect handling the content of the .gitignore file

### ISSUE THREAD

**Issue by wenh06** [psf/black#3212]
**Describe the bug**

The excluded files in the `.gitignore` file (starts with `!`) are ignored by `black`, which should not be a correct behaviour.

**To Reproduce**

The `.gitignore` file contains the following lines

```
*.ipynb
!experiment.ipynb
```

which make `git` ignore all `.ipynb` files except the `experiment.ipynb` file.

And run it with these arguments:

```sh
$ black . -v
```

The resulting error is:

> experiments.ipynb ignored: matches the .gitignore file content

**Expected behavior**

`experiments.ipynb` should not be ignored.

**Environment**

- Black's version: 22.6.0
- OS and Python version: Ubuntu 18.04/Python 3.6.9

**Additional context**

**Comment by jack1142** [comment]
`experiments.ipynb` != `experiment.ipynb` so are you sure you didn't make a typo?

**Comment by wenh06** [comment]
> `experiments.ipynb` != `experiment.ipynb` so are you sure you didn't make a typo?

Oh, I see. `git` tracks my `experiments.ipynb` but ignores all the rest notebooks. Perhaps it is because I added
```
*.ipynb
!experiment.ipynb
```
in the `.gitignore` file after I added `experiments.ipynb` via `git`.
