### ISSUE TITLE
The blackd daemon doesn't work, it just returns the input source code with line endings stripped

### ISSUE THREAD

**Issue by Hubro** [psf/black#3218]
**Describe the bug**

The Black HTTP daemon (`blackd`) doesn't reformat code, it just prints it right back at me with line endings stripped.

**To Reproduce**

For example, take this code:

**test.py**:

```python
#!/bin/env python3


def main(     ):
    pass


if __name__ == '__main__':
    main()
```

And pass it to the Black daemon (run with `blackd`):

```sh
$ cat test.py | curl -v -H "Content-Type: text/x-python" -d @- "http://localhost:45484"
```

The resulting output is:

```
*   Trying 127.0.0.1:45484...
* Connected to localhost (127.0.0.1) port 45484 (#0)
> POST / HTTP/1.1
> Host: localhost:45484
> User-Agent: curl/7.84.0
> Accept: */*
> Content-Type: text/x-python
> Content-Length: 78
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Black-Version: 22.6.1.dev29+g6064a43
< Content-Type: text/x-python; charset=utf8
< Content-Length: 79
< Date: Fri, 12 Aug 2022 22:22:14 GMT
< Server: Python/3.8 aiohttp/3.8.1
< 
#!/bin/env python3def main(     ):    passif __name__ == '__main__':    main()
* Connection #0 to host localhost left intact
*
```

All the daemon did was write my code back to me, with all line endings stripped :thinking: 

The `blackd` output meanwhile doesn't suggest any issues:

```
INFO:aiohttp.access:127.0.0.1 [12/Aug/2022:22:22:14 +0000] "POST / HTTP/1.1" 200 272 "-" "curl/7.84.0"
```

**Expected behavior**

Expected Black to output the contents of the input file, but formatted properly. Running `black` on the file regularly works as expected, this is only an issue with the daemon.

**Environment**

```
➜ black --version
black, 22.6.0 (compiled: yes)
Python (CPython) 3.8.6

➜ blackd --version
blackd, version 22.6.0

➜ python --version
Python 3.8.6
```

Also downloaded the repository and tested the fresh main branch, same problem:

```
➜ black --version
black, 22.6.1.dev29+g6064a43 (compiled: no)
Python (CPython) 3.8.6

➜ blackd --version
blackd, version 22.6.1.dev29+g6064a43
```

---

Am I doing something embarrassingly wrong here, or doesn't the HTTP daemon work? :thinking:

**Comment by cibinmathew** [comment]
Below worked for me. But I am not sure why the other didn't
```
curl -sf -XPOST localhost:45484 -d "$(cat test.py)"
```

**Comment by Hubro** [comment]
> Below worked for me. 
> 
> ```
> 
> curl -sf -XPOST localhost:45484 -d "$(cat test.py)"
> 
> ```
> 
> In curl, -d skips \n and \r characters. use --data-binary
> 
> ```
> 
> cat test.py | curl -v -X POST   -H "Content-Type: text/x-python"  --data-binary @- "http://localhost:45484"
> 
> ```

Thanks, I didn't know that. Should Black give some indication that the input is bad in this case?

**Comment by ichard26** [comment]
There's nothing Black can do here because the stripping of newlines nets this:
```python
#!/bin/env python3def main(     ):    passif __name__ == '__main__':    main()
```
which is just one long comment :upside_down_face: If you remove the shebang line, blackd will return `HTTP 400 Bad Request`
```
❯ cat test3.py | curl -v -H "Content-Type: text/x-python" -d @- "http://localhost:45484"
*   Trying 127.0.0.1:45484...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 45484 (#0)
> POST / HTTP/1.1
> Host: localhost:45484
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: text/x-python
> Content-Length: 60
> 
* upload completely sent off: 60 out of 60 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< X-Black-Version: 22.6.1.dev41+gc0cc19b
< Content-Type: text/plain; charset=utf-8
< Content-Length: 80
< Date: Sat, 27 Aug 2022 22:03:05 GMT
< Server: Python/3.8 aiohttp/3.8.1
< 
* Connection #0 to host localhost left intact
Cannot parse: 1:27: def main(     ):    passif __name__ == '__main__':    main()
```

**Comment by Hubro** [comment]
@ichard26 Aah dang, good point. Seems I'm just wasting people's time here, I'll show myself out! :sweat_smile:

**Comment by ichard26** [comment]
No worries, it took me way longer than it should've to notice that the input was all just one big comment. I thought our error handling logic was broken :sweat_smile:
