### ISSUE TITLE
Incorrect handling of .gitignore negate pattern

### ISSUE THREAD

**Issue by ajasmin** [psf/black#3228]
**Describe the bug**

When adding a name to .gitignore and negating a specific directory of that name, black incorrectly ignores the files it contains.

**.gitignore**
```
build
!/foo/build
```

**To Reproduce**

By running this shell script you should see that git doesn't ignore the file but black does.

```
#!/usr/bin/env bash
set -e

# Create project directory
TMP_DIR="$(mktemp -d)"
cd "$TMP_DIR"

# Make this a git working copy
git -c init.defaultBranch=main init

# Create .gitignore
cat > .gitignore << "EOF"
build
!/foo/build
EOF

# Create a file which shouldn't be ignored
mkdir -p foo/build
cat > foo/build/bar.py << "EOF"
x =     1
EOF

# Check that git doesn't ignore the file
if git check-ignore foo/build/bar.py; then
    echo "Path ignored by git"  # You shouldn't see this
fi

# Run black. Verbose output shows that the directory is ignored
black -v .

**Comment by jack1142** [comment]
It appears to be a bug with pathspec not handling exclusions correctly for directories without a trailing slash (this also gives you a workaround for this issue - just add a trailing slash):
```py
import pathspec


gitignore = """\
build
!/foo/build
"""
spec = pathspec.PathSpec.from_lines("gitwildmatch", gitignore.splitlines())
# incorrectly returns False
print(spec.match_file("foo/build/file.py"))


gitignore = """\
build
!/foo/build/
"""
spec = pathspec.PathSpec.from_lines("gitwildmatch", gitignore.splitlines())
# correctly returns False
print(spec.match_file("foo/build/file.py"))
```

I don't think there are any open issues for this on the pathspec repo so could you report it there?
https://github.com/cpburnz/python-path-specification/issues

**Comment by ajasmin** [comment]
This example was poorly chosen as *build* is also part of black default exclude regex.

**Comment by JelleZijlstra** [comment]
Thanks, closing as the bug appears to be in our dependency, not in Black itself.

**Comment by jack1142** [comment]
Since it doesn't seem like you got around to it, I made an issue to track this: https://github.com/cpburnz/python-path-specification/issues/57

**Comment by ichard26** [comment]
Thank you @jack1142!
