### ISSUE TITLE
Trailing commas not removed when dict/function call collapsed into single line

### ISSUE THREAD

**Issue by nyuszika7h** [psf/black#3229]
**Describe the bug**

When a multiline dict/function call is collapsed into fewer lines by black, it seems to leave stray trailing commas. This does not happen when using `--skip-magic-trailing-comma`.

**To Reproduce**

For example, take this code:

```python
def refresh_token(self, device_family, refresh_token, api_key):
    return self.orchestration.refresh_token(
        data={
            "refreshToken": refresh_token,
        },
        api_key=api_key,
    )["extensions"]["sdk"]["token"]
```

And run it with these arguments:

```sh
$ black file.py -l 120
```

The resulting output is:

```python
def refresh_token(self, device_family, refresh_token, api_key):
    return self.orchestration.refresh_token(data={"refreshToken": refresh_token,}, api_key=api_key,)["extensions"][
        "sdk"
    ]["token"]
```

**Expected behavior**

The output should look something like this (without the stray trailing commas):

```python
def refresh_token(self, device_family, refresh_token, api_key):
    return self.orchestration.refresh_token(data={"refreshToken": refresh_token}, api_key=api_key)["extensions"][
        "sdk"
    ]["token"]
```

**Environment**

- Black's version: 22.6.0 / main
- OS and Python version: Debian 10, Python 3.10.4

**Additional context**

**Comment by ichard26** [comment]
Looks similar to https://github.com/psf/black/issues/2052. Thanks for reporting by the way!
