### ISSUE TITLE
Black crashes when "fmt: off/on" is used with "with" expression

### ISSUE THREAD

**Issue by jakub-m** [psf/black#3236]
**Describe the bug**

Black crashes when "fmt: off/on" is used with "with" expression.

**To Reproduce**

For example, take this code:

```python
# file.py
def do_something():
    # fmt: off
    with open('foo') as foo,\
         open('bar') as bar:
        # fmt: on
        raise SomeError()


class SomeError(Exception):
    pass

```

And run it with these arguments:

```sh
black file.py
```

or check in black console online [HERE][ref_console].

The resulting error is:

> error: cannot format black_bug.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: ...

**Expected behavior**

Should not crash. I use "fmt: off" and "fmt: on" to prevent moving multiple "with" into one a single line.

**Environment**

```
% black --version
black, 22.6.0 (compiled: yes)
Python (CPython) 3.9.13
```
MacOS

[ref_console]:https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEhAKpdAD2IimZxl1N_WlbvK5V8u_W0bYewSuBcM2kBOfZIG1VYSgIvPCENV-3WXpf0DRe4aXtdDMwPi0eIr8ZQRgjxdAaUZjOs-wB13sd-6iN18_T9pO6vcwoq-ZlFBP_J1_zRIHe2IF3mo7CJVgfpqOyXxbKBo0wFBOKh4YU7Bo_-jNcNeIxLjZiJLp_xEuPknR8J5Gfuj-oj6l23dS7qkMeWAinPhsPi34UsEW-EAAAA1WiB3aUe5isAAcYBogIAACQFYt2xxGf7AgAAAAAEWVo=

**Comment by felix-hilden** [comment]
Hi, fmt on/off need to be on the same indentation level. This is an issue in #569, and we intend to fail gracefully in this case #2985 so that the error message is clearer. I'll close this as a duplicate!

**Comment by jakub-m** [comment]
@felix-hilden I don't think this is a duplicate. The example also fails when I move the directives to the same indentation level:

```
# file.py
def do_something():
    # fmt: off
    with open('foo') as foo,\
         open('bar') as bar:
    # fmt: on
        raise SomeError()


class SomeError(Exception):
    pass

```
or
```
# file.py
def do_something():
# fmt: off
    with open('foo') as foo,\
         open('bar') as bar:
# fmt: on
        raise SomeError()


class SomeError(Exception):
    pass

```
or
```
# file.py
def do_something():
        # fmt: off
    with open('foo') as foo,\
         open('bar') as bar:
        # fmt: on
        raise SomeError()


class SomeError(Exception):
    pass

```

**Comment by felix-hilden** [comment]
None of them are truly on the same indentation level in code. Try:

```python
# fmt: off
with ...:
    pass
# fmt: on
```

**Comment by jakub-m** [comment]
Yes, that works, thanks. But that was not the intention. I want to format the body of the `with` block, I just don't want to format the multi-line `with` line. I want to skip formatting for a single line, not the whole block.

**Comment by felix-hilden** [comment]
Yes, I get that. But this is how fmt off needs to be used. We've got fmt: skip for one-line skips, perhaps that'll help!
