### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by maxmunzel** [psf/black#3240]
Hey All! Stubled upon this, hope this is still relevant
```
error: cannot format [ommited]/pyqtgraph/widgets/TreeWidget.py: 
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_c76gbp19.log
```

This version produced the error:
```
 python3 -mblack --version
__main__.py, version 20.8b1
```

This version handles it fine:
```
black, 22.3.0 (compiled: yes)
```

[TableWidget.py.txt](https://github.com/psf/black/files/9431754/TableWidget.py.txt)
[blk_c76gbp19.log](https://github.com/psf/black/files/9431735/blk_c76gbp19.log)

**Comment by JelleZijlstra** [comment]
Since it's apparently fixed in a recent version, I don't think this is actionable.
