### ISSUE TITLE
support comment # black: off

### ISSUE THREAD

**Issue by martinResearch** [psf/black#3244]
**Is your feature request related to a problem? Please describe.**

I am currently using autopep8 to format the code in a repository and would like to gradually migrate only a part of the code to black formatting. In order to do this easily, I would like to be able to ignore selectively individual files by adding a comment at the top of the file I want to ignore. I can use "# fmt: off" but then this disables autopep8 formatting as well, while I would like to be able to disable only black and continue using autopep8 on files ignored by black. 

**Describe the solution you'd like**

In order to be able to selectively deactivate black formatting in a file without disabling other formatters like autopep8 it would be great if black could support the more specific comments "# black: off" and  "# black: on"  

**Describe alternatives you've considered**

we can list explicitly the files we want to ignore using --exclude but it is cumbersome to maintain the list of individual files we want to ignore.

**Comment by JelleZijlstra** [comment]
We also support `# yapf: disable` in order to disable Black. I don't know if autopep8 recognizes that too.

I'm not inclined to add yet another magical comment with new semantics. Black's configuration story is already getting complicated, and our advise is to apply Black all at once, not piecemeal.

**Comment by martinResearch** [comment]
Thank you for the suggestion. Autopep8 does not seem to recognize "# yapf: disable", so it solves my problem for now :) . But that does not seem to be a very elegant solution and maybe autopep8 " will start supporting  #yapf" comments in the future.

It does not seem to me that supporting "# black: off" complicates much the configuration story.  Black support already specific string related to alternative tools like yapf though "# yapf: disable" and thus it seems to me a bit strange not to support "# black: off" as well. I would think the change would only consist in adding an element to the sets FMT_OFF and FMT_ON defined in comments.py and thus I am not really seeing any significant downside, or am I missing some potential complications?
