### ISSUE TITLE
Disabling E501 hurts E225

### ISSUE THREAD

**Issue by BenjaminHoegh** [psf/black#3253]
When I add `--ignore=E501` to VSCode it also stop using E225. Any idea why?

**Comment by TomFryers** [comment]
I'm not sure what that has to do with Black. It sounds like a VS Code, Flake8 or pycodestyle issue.

**Comment by felix-hilden** [comment]
Feel free to reopen if there's anything related to Black, but I'll close this for housekeeping since it seems unlikely.
