### ISSUE TITLE
Black reformats entire virtual environment when named `env` with pathspec==0.10.0 

### ISSUE THREAD

**Issue by jnhyperion** [psf/black#3256]
**Describe the bug**

When using black and virtualenv, black try to reformat entire virtual env folder, which cause heavy process execution and hang very long.

**To Reproduce**
For example, take this code:

```python
mkdir myfolder

cd myfolder

virtualenv env

source env/bin/activate

pip install black

pip list

Package           Version
----------------- -------
black             22.8.0
click             8.1.3
mypy-extensions   0.4.3
pathspec          0.10.0
pip               22.2.2
platformdirs      2.5.2
setuptools        63.4.3
tomli             2.0.1
typing_extensions 4.3.0
wheel             0.37.1

black . --check --diff

```
then black will try to check all the env folder.

this issue is caused by the library `pathspec  0.10.0`, and black does not lock the version, looks like `pathspec` already fix the bug in `0.10.1`.

but for `black`,  does it need to lock, or force skip this buggy `pathspec` version, to avoid this fatal error

**Comment by JelleZijlstra** [comment]
If you tell Black to format everything in a directory, it will; it can't magically determine that the folder contains a virtual env. We exclude a few common names for virtual envs by default, but `env` is not among them. You can use the `--exclude` or `--extend-exclude` option to exclude directories.

Can you clarify what you think the bug is in `pathspec`?

**Comment by ichard26** [comment]
Black doesn't actually include `env` in its default excludes, I think it's probably a good idea to include it even if it's a less common virtual environment name. Not sure why upgrading pathspec would change black's behaviour, it shouldn't be coming into play here as there's no `.gitignore` file anywhere. 

Are there situations where excluding `env` by default would be a problem? @JelleZijlstra

**Comment by JelleZijlstra** [comment]
`env` is a perfectly plausible name for a folder containing actual code that you want to be formatted. It would be an unpleasant experience for a user to find out that Black silently skips a directory they want to get formatted.

**Comment by jnhyperion** [comment]
in the virtual env folder `env`, it will automatically contains `.gitignore`

```
# created by virtualenv automatically
*
```

which I think will be recogonized  by black right?

in my case, if I upgrade pathspec to `0.10.1`, this issue will disappear.

**Comment by ichard26** [comment]
https://github.com/cpburnz/python-pathspec/issues/62 ahhh I see, sounds like we should ask upstream to yank this version since it might cause a lot of grief.

**Comment by ionite34** [comment]
The `env` directory not ignored issue seems to only occur with `pathspec` version `0.10.0`, and not in `0.9.0` nor the newest `0.10.1` version. Probably related to https://github.com/cpburnz/python-pathspec/issues/62

**Comment by ichard26** [comment]
[I've asked upstream to yank pathspec 0.10.0](https://github.com/cpburnz/python-pathspec/issues/62#issuecomment-1236501291), let's see if they're open to it, otherwise, I'd be open to banning the faulty version on Black's end.

**Comment by ichard26** [comment]
And pathspec 0.10.0 has been yanked: https://pypi.org/project/pathspec/0.10.0/
