### ISSUE TITLE
How do I match GitHub action with stability policy?

### ISSUE THREAD

**Issue by lofidevops** [psf/black#3264]
**Is this related to a problem? Please describe.**

The pages on [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy) and [GitHub Actions](https://black.readthedocs.io/en/stable/integrations/github_actions.html) are very clear. However, I don't think it's possible to enforce stability with GitHub actions.

**Describe the solution you'd like**

I would like to add `uses: psf/black@2022` in my GitHub action, and have this be equivalent to `black ~= 22.0` (or `black < 23`) in the developer toolchain. I believe this would require adding a `2022` tag, updating it on every release, then adding a `2023` tag for the first `23.x` release.

**Describe alternatives you've considered**

 * Pin specific version in GitHub action, leave toolchain at `~= 22.0`. When developer toolchain is updated to `~= 23.0`, re-pin in GitHub action. Downside: chance of discrepancy between 22.x (GitHub) and 22.y (toolchain).
 * Similar options (e.g. switch toolchain to `--preview` in November/December) require even more coordination.
 * Do not pin GitHub action or toolchain. Downside: defeats the point of stability policy, which I assume is to prevent scrambling in early 2023.
 * Pin specific version of GitHub Action and toolchain. Dowside: must update for every single release.

**Additional context**

This is a professional team, so the goal is to eliminate non-critical technical alerts. It could be that the final alternative is the only viable solution. Or there's a simple solution I have missed :D

**Comment by jack1142** [comment]
You can just set version argument in the action to `<23`. The stability policy only applies to the code style so what matters is Black version, not the action version.

**Comment by lofidevops** [comment]
@jack1142 Ok, so this example adapted from the docs would work. Thanks!

```
- uses: psf/black@stable
  with:
    options: "--check --verbose"
    src: "./src"
    version: "<23"
```

**Comment by ichard26** [comment]
I don't believe that will work right now since if [the version option is provided `==` is simply prefixed](https://github.com/psf/black/blob/main/action/main.py#L19), breaking version ranges. I'd be happy to change the action to be smarter (defaulting to `==` but instead adds nothing if there's a version specifier type marker).

**Comment by cooperlees** [comment]
> @jack1142 Ok, so this example adapted from the docs would work. Thanks!
> 
> ```
> - uses: psf/black@stable
>   with:
>     options: "--check --verbose"
>     src: "./src"
>     version: "<23"
> ```

Can we add anything to our docs to make the clearer? If so PR will be accepted.

**Comment by jack1142** [comment]
> I don't believe that will work right now since if [the version option is provided `==` is simply prefixed](https://github.com/psf/black/blob/main/action/main.py#L19), breaking version ranges. I'd be happy to change the action to be smarter (defaulting to `==` but instead adds nothing if there's a version specifier type marker).

I assumed that it works based on the documentation in action.yml which says it uses PEP 440 version *specifier*, my bad for not checking the code :-)

**Comment by ichard26** [comment]
Ugh that's unfortunate. Can't really break the pre-existing usages of the action though, the default has to be included.

**Comment by aaossa** [comment]
I think this issue can be closed since the PR was merged recently
