### ISSUE TITLE
PyCharm File Watcher documentation missing

### ISSUE THREAD

**Issue by ruslaniv** [psf/black#3271]
Black documentation used to contain a section on how to use Black with PyCharm via a file watcher utility.
 
Now there is no mention of this option of using Black, only though a **third party** plugin **AND** some more dependencies. 
There might be reasons why I don't want or can not install  other dependencies, for example `aiohttp` or PyCharm extensions that is required for Black[d]

**Describe the solution you'd like**
Add a documentation section on how to use Black with PyCharm file watcher utility. 

**Describe alternatives you've considered**
Using Black[d] with a third party extension for PyCharm and some more dependencies failed due to inability to install said dependencies.

**Comment by ichard26** [comment]
Seems reasonable to bring this back. We can revert the part of https://github.com/psf/black/commit/05b63c4bccbfb292a92d3ec962ce9b8fa4ebcfd5 that removes the old integration steps and include some advice on when to use which option. 

Would you be able and happy to submit a PR?

**Comment by radioactive11** [comment]
Hello @ichard26 
Can I take up this issue?

**Comment by ichard26** [comment]
Yup.

**Comment by ichard26** [comment]
D'oh this was resolved a while back by https://github.com/psf/black/pull/3365. Let's close this :)
