### ISSUE TITLE
Black is inconsistent with empty lines before an inner function after code block open, with or without leading comments

### ISSUE THREAD

**Issue by yilei** [psf/black#3300]
**To Reproduce**

Unformatted code:

```python
def main():
    if a:

        # Comment
        def b():
            pass

    if b:
        def c():
            pass
```

Running `black --preview`:

```python
def main():
    if a:
        # Comment
        def b():
            pass

    if b:

        def c():
            pass
```

**Expected behavior**

Empty line should be consistent added (or removed) between the code block open and inner function:

```python
def main():
    if a:

        # Comment
        def b():
            pass

    if b:

        def c():
            pass
```

Or,

```python
def main():
    if a:
        # Comment
        def b():
            pass

    if b:
        def c():
            pass
```

**Additional context**

I did a bisect and this was caused by https://github.com/psf/black/pull/3035.

Note that if the inner function doesn't have a leading comment, it won't remove the empty line:

```python
def main():
    if a:

        def b():
            pass

        def c():
            pass
```

Thus I believe this is an undesired behavior change in #3035?

**Comment by yilei** [comment]
#246 is possibly related since that's also caused by a comment before the function def.

**Comment by ichard26** [comment]
I agree this should be fixed.

**Comment by yilei** [comment]
Looking at `EmptyLineTracker`, it is indeed the same underlying issue as #246, that the tracker isn't capable of doing this when there are preceding standalone comments. I'll take a stab at a fix.

**Comment by felix-hilden** [comment]
Having a look at #3035, I'd expect the newline to be removed before the first function regardless of the comment. Would you prefer otherwise?

**Comment by yilei** [comment]
I would actually personally prefer the newline to be removed after a block open.

I saw this is inconsistent with or without the comment, plus the [current _Black_ style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#empty-lines) says:

> It will also insert proper spacing before and after function definitions. It’s one line before and after inner functions...

This is the "inner function" case.

So I'm slightly in favor of changing the preview style to always remove the newline before an inner function and immediately after a block open, with or without the leading comment (I'm strong on making the behavior consistent with or without comment). I can send a separate PR to do that once we make decision. Meanwhile I updated #3302 to keep the current behavior for this case.

**Comment by felix-hilden** [comment]
I'm fully in favor of doing it, but it's fine to keep the original behavior if you'd like to 👍 I think the inner function spacing rule is secondary to the "no space in a new block" rule.

**Comment by yilei** [comment]
@felix-hilden Thanks. Mind approve #3302 and get it merged to fix #246? Then I'll send a follow-up PR to for this issue.

**Comment by felix-hilden** [comment]
Done, we'll wait for another approval since Jelle's is a bit stale. Thanks!

**Comment by flying-sheep** [comment]
Oh, wow, I didn’t expect this!

```py
    if header[0] == "Package":
        def strengthen(k: str) -> str:
            return f"<strong>{k}</strong>"
    else:
        def strengthen(k: str) -> str:
            return k
```

becomes

```py
    if header[0] == "Package":

        def strengthen(k: str) -> str:
            return f"<strong>{k}</strong>"
    else:

        def strengthen(k: str) -> str:
            return k
```

that looks really bad!

What’s the intention here?
