### ISSUE TITLE
Do not remove semicolons in Jupyter notebooks

### ISSUE THREAD

**Issue by NChechulin** [psf/black#3310]
**Describe the style change**

The main use of semicolons in Jupyter Notebooks is to hide the output of some function calls.
Automatically removing them creates (unnecessary) extra output in the Jupyter Notebook. 

**Examples in the current _Black_ style**

```python
import seaborn as sns


ax = sns.scatterplot(
    x=df["tenure"],
    y=residuals,
)
ax.set_ylabel("Residual")

```
After executing a cell with the code above, 2 things are outputted:
1. `Text(0, 0.5, 'Residual')`
2. The graph itself.

![image](https://user-images.githubusercontent.com/38015818/193873450-0d3de18e-e69f-4add-8f33-2495c2970358.png)

Clearly, this text is almost never needed, since the label will be present on a graph.

**Desired style**

```python
import seaborn as sns


ax = sns.scatterplot(
    x=df["tenure"],
    y=residuals,
)
ax.set_ylabel("Residual");
```

Currently, the only workaround is to write `_ = ax.set_ylabel()`.

**Comment by MarcoGorelli** [comment]
That's right - just tried this, and if you have a cell with
```
import seaborn as sns


ax = sns.scatterplot(
    x=df["tenure"],
    y=residuals,
)
ax.set_ylabel("Residual");
```
then it'll be left unchanged

@NChechulin is this not what you're seeing?

**Comment by MarcoGorelli** [comment]
sounds like a bug in vscode, I'd suggest reporting to them

**Comment by felix-hilden** [comment]
Aight, will close now, let's follow the vscode issue! Thanks for running this by us anyways 👍
