### ISSUE TITLE
Documentation around skipping trailing comma check

### ISSUE THREAD

**Issue by crypticraven** [psf/black#3317]
I'm looking for a way to remove the trailing comma check. When creating lists and dictionaries, the trailing comma as a style choice should be optional NOT required.

I've been leveraging the TOML configuration file as part of the Super-Linter project and Black doesn't seem to honor any of the configuration I am trying to enforce.

**Describe the solution you'd like**

I'd like a descriptive document around what syntax is expected for the TOML file.

**Describe alternatives you've considered**

I've tried .isort.cfg and .python-black as configuration files with no success.

**Additional context**

As a style choice, this check should be optional. While some may find it useful in creating exploded lists, we find it annoying to block a PR because a line is missing a comma. No OTS platform enfoces this style (Snyk/Sonar[qube/cloud]). My development teams that leverage this open-source platform for linting should be able to turn this check as well as others off. There's just no real documentation around it. Leveraging the `--help` command I thought I had the idea correct, but it still doesn't honor the configuration.

This is what I have in the TOML file:
`[tool.black]`
`line-length = 88`
`skip-magic-trailing-comma = true`
`include = '\.pyi?$'`
`extend-exclude = '''`
`/(`
`  # The following are specific to Black, you probably don't want those.`
`  | blib2to3`
`  | tests/data`
`  | profiling`
`)/`
`'''`
`# We use preview style for formatting Black itself. If you`
`# want stable formatting across releases, you should keep`
`# this off.`
`preview = true`

**Comment by felix-hilden** [comment]
Hi 👋  `skip-magic-trailing-comma` is an option for collapsing collections if they become small enough to fit one line. There is no option to skip adding the final trailing comma to a collection if that's what you're asking!

**Comment by crypticraven** [comment]
Is that a feature that could be implemented?

**Comment by JelleZijlstra** [comment]
No, that would not be in line with the general design of Black.
