### ISSUE TITLE
Avoid needless linebreaks on `|` in PEP-604 type annotations

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#3319]
**Describe the style change**

Given the increasing popularity of Python 3.10 and [PEP604](https://peps.python.org/pep-0604/) type annotations (`arg: X | Y`), it's unfortunate that Black is so eager to put linebreaks in the middle.  This happens when it's not necessary to meet line-length limits; and also when splitting doesn't achieve line-length limits!

I propose that the `|` operator be treated as binding more tightly in type annotations, to make Python 3.10+ code more elegant.

**Examples in the current _Black_ style**

```python
def func(
    options: tuple[str]
    | None = (
        "one_option",
        "another_option",
    ),
    long_arg: str
    | None = (
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    ),
    another_long_arg: str 
    | None = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",  # exceeds length limit!
):
    pass
```
Lines beginning `| None =` are all too common, and I'll admit that I don't like them at all.  Instead, I think that we should keep annotations on a single line where possible (or parenthesized where not, instead of split out to a term per line).

**Desired style**

```python
def func(
    options: tuple[str] | None = (
        "one_option",
        "another_option",
    ),
    long_arg: str | None = (
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    ),
    # treat another_long_arg the same way as long_arg
):
    pass
```

Notably I think it's important to ship this before freezing the 2023 code style, preferably with enough time for a round of feedback from `--preview` users.

**Comment by ichard26** [comment]
Yup, see https://github.com/psf/black/issues/2316.

**Comment by Zac-HD** [comment]
🤦‍♂️  should've searched for "PEP 604", right.  Closing as duplicate.
