### ISSUE TITLE
unreachable code in `parsing.py`

### ISSUE THREAD

**Issue by NNRepos** [psf/black#3321]
**Describe the bug**

unreachable code in `src\black\parsing.py:170`: 
`raise AssertionError("INTERNAL ERROR: Tried parsing unsupported Python version!")`

**Expected behavior**

not having unreachable code 😝

**Comment by JelleZijlstra** [comment]
You're right, we can remove this line.

**Comment by NNRepos** [comment]
> You're right, we can remove this line.

great!
if you would like me to create a PR, please assign me to this issue 😄
