### ISSUE TITLE
[Feature Request] Optimize imports

### ISSUE THREAD

**Issue by devxpy** [psf/black#333]
Can we please have a feature, similar to [PyCharm's "optimize imports" feature](https://www.jetbrains.com/help/pycharm-edu/optimizing-imports.html), which basically sorts and removes un-used import statements?

P.S. Great work!, Black works like a charm for me.

**Comment by thalessa** [comment]
Remove duplicate import also requested.

**Comment by hugovk** [comment]
For the time being, you can use [isort](https://github.com/timothycrosley/isort) to sort imports and [autoflake](https://github.com/myint/autoflake) to remove unused imports.

```sh
isort -rc .
autoflake -r --in-place --remove-unused-variables .
```

**Comment by jensens** [comment]
IMO import sorting should be handled separate outside of Black. With ISort (and others) we already have great tools.

**Comment by asottile** [comment]
https://github.com/ambv/black/issues/363#issuecomment-398261516 also serves as a decent indicator that this won't / shouldn't happen in black.

from @ambv's comment:
> Black is not a linter, it's a formatter. It starts and ends with the same AST

adding / removing / sorting imports would change the ast

**Comment by tweakimp** [comment]
I wish there was something like black but for linting and code review. Maybe name it white? 😋

**Comment by denizdogan** [comment]
Obviously we can use isort and autoflake (or some other tools) to achieve the same thing, but a big benefit of Black is that it's opinionated and covers everything in *one tool* and *one command* and *one **optional** configuration*.

**Comment by ambv** [comment]
I'm warming up to the idea that Black should cover this use case too.

**Comment by tweakimp** [comment]
Which one?
Sorting? Removing unused? Removing doubles?

**Comment by jaroel** [comment]
@ambv I understand why you'd want to, but pretty please stick to formatting only.
Not only should one tool do one thing (tm), we'd also be wasting the years of effort and tuning that went into tools like isort, pyflakes, pylint, et all - and at the integrations with IDEs - their options, switches and nuances.

Linting is a different kind of beast from formatting. I'm really comfortable with letting black *format* my code, as it doesn't change the working of it. But you have no idea why my code was written as it is.
For example: I *need* to have setup some paths before importing code - that's a given:
```
from configtype.jsonconfig import setup_search_paths
setup_search_paths(".")
from ocyan.main.settings import *  # isort:skip
```
I would expect that black-the-linter would always put all the imports together, without an cop-out:
```
from configtype.jsonconfig import setup_search_paths
from ocyan.main.settings import *
setup_search_paths(".")
```

I love that black takes out all discussion on *formatting*, but please please do not make black do linting. 

Thank you for reading :)

**Comment by JelleZijlstra** [comment]
I would like to see Black auto-sort imports, actually. For my team the value of Black is in taking care of boring, unimportant code-related decisions in a consistent way, so that developers don't have to worry about these things. That value gets even bigger if we can have a single tool taking care of all of these decisions, instead of having one for formatting, one for sorting imports, etc. Otherwise, developers have to remember to run every one of those tools on their code, and it gets harder to get people to install editor plugins to run every tool automatically.

It's true that import sorting is a bit trickier than what Black currently does, because it will change the AST. To @jaroel's concern, we should limit import sorting to contiguous blocks of imports: if there is any non-import code, we should not move imports around it. Similarly, we should be careful not to reorder imports that define the same name, including `import *`s. We should also study how import sorting is done by existing tools like isort and learn from them.

**Comment by jaroel** [comment]
@JelleZijlstra It looks to me that you want automation, not import-sorting-by-black per se :)
The usual approach would be to wrap tools in a utility script, or use a Makefile to call everything in the correct order - or using a pre-commit hook.
ie, `make lint` calls `isort` and then `black`. This makes it even easier for your developer, as they won't even need to know about black anymore ;)

In other words: I wouldn't want my car mechanic to clean my clothes, even if it would be handy to have that if I'm already waiting at the shop ;)

**Comment by ambv** [comment]
@jaroel, you raise some valid points. The very reason I'm considering sorting imports in Black is that isort does it wrong:
* In general, its implementation is problematic. Everything interesting happens in an `__init__()` method; it's based on string matching and not a syntax tree, and so on.
* Its configuration based on magic discovery of first-party/third-party code only works on activated virtualenvs, making it brittle for CI.
* It moves comments around in a way that is incompatible with Black.
* However, the killer thing for me is the example you give around imports placed after function calls being moved above the calls. Black would never do that because there are simply too many cases where this breaks the file. This makes codemodding any larger codebase unsafe.

Even if isort's author agreed with some of the above, backwards compatibility concerns pretty much force him to keep it as is.

If I followed some of the advice here around "reinventing" things, Black wouldn't see the light of day at all. We've had autopep8 and YAPF the entire time, didn't we? Just as I didn't want to write an auto-formatter, I don't *want* to creep more scope into it. Sadly, sorting imports looks increasingly inevitable.

Don't worry though. This feature requires careful planning so it won't appear out of the blue any time soon.

**Comment by asottile** [comment]
> If I followed some of the advice here around "reinventing" things, Black wouldn't see the light of day at all. We've had autopep8 and YAPF the entire time, didn't we?

yapf/autopep8 have much more timid goals than black, not sure it's fair to compare them :) (whereas an import sorter would hopefully have identical goals).

That said, I also reinvented the isort wheel for exactly the reasons listed above ([1](https://github.com/asottile/reorder_python_imports/blob/f5c67b716c04babb6e8e80bb52e329ee7654b1b8/reorder_python_imports.py#L80) [2](https://github.com/asottile/reorder_python_imports#reorder_python_imports) [4](https://github.com/asottile/reorder_python_imports#using--noreorder)) 🙃 (whoops I'm a hypocrite)

I definitely think (1) is fixable upstream.  I've proposed fixes to (2) but this seems to be a sticking point ([worked around instead](https://github.com/asottile/seed-isort-config#seed-isort-config)), and (4) I just don't have any good excuses for `isort` -- this behaviour is unacceptable.

**Comment by bertjwregeer** [comment]
@ambv is there anything we can do to help move this part of black along? Having fallen into various pitfalls of isort due to an issue of it's configuration (it merges `.isort.cfg` with `~/.isort.cfg` for example, meaning a projects `.isort.cfg` has to define ALL keys or a users `~/.isort.cfg` may override it), I'd love to see this implemented in black.

**Comment by JelleZijlstra** [comment]
@bertjwregeer I think the main limiting factor is that somebody has to actually do the work. Here's a list of some things that have to be taken care of:
- Generally review what other current tools (isort, and I'm sure there are others) do. What kind of things to they change? What style do they choose? How to they decide what is safe to change?
- Decide what the style is going to be that Black will enforce. Some questions to answer: Will we separate imports into different "sections", like internal vs. stdlib vs. third-party? How will we decide which imports go into which section? (I wouldn't want Black to go spelunking around the file system to figure out what is a third-party package, like isort apparently does.) Will we turn `'from x import y; from x import z` into `from x import y, z`? (I would be OK with that but maybe it's a bridge too far.)
- Figure out what the safety features are that we need. @ambv and I mentioned a few above, like not moving imports around comments or function bodies, and not moving things around `import *`, but we do need more?
- We need to actually implement this in Black itself. We'll have to add a flag to skip import normalization. Import sorting will break Black's current safety check (which checks that the AST matches before and after), so we'll have to decide what to do about it (disable it or make it smarter).

**Comment by jaroel** [comment]
I've got a Zope/Grok project where we import the whole module and refer to that.
ie `import z3c.form.widgets` + `z3c.form.widgets.select` instead of `from z3c.form.widgets import select`.
It would be nice if that could be supported in some way?

**Comment by jensens** [comment]
In the @plone project we decided to [sort imports alphabetical](https://docs.plone.org/develop/styleguide/python.html#grouping-and-sorting). Major reason is, if there are many imports it is easier to read and to find an import, without guessing what it is semantically. An we often have many imports. Also, the internal vs. third-party is difficult to define in a project with many packages. Is the application server code third party or not? Developing an Addon for Plone, is Plone then thirdparty? If it is taken into Plone-Core, do we then need to resort imports? There is no semantic true way to make sections nor is there a good way to automate that. 

Alphabetical imports are simple, easy to read and also do not need code inspection for sorting. 

It still breaks the AST diff. I usually do an isort and the run black. 

The [Black compatible (and currently still on a line length of 79) Isort configuration](https://gist.github.com/jensens/ce74e85bc297f3db46dad95fd08eb0c6).

**Comment by hugovk** [comment]
@asottile's https://github.com/asottile/reorder_python_imports "has a single aim: reduce merge conflicts" and favours:
```python
from typing import Dict
from typing import List
```
over:
```python
from typing import Dict, List
```

**Comment by bertjwregeer** [comment]
I much prefer grouping things together than a single import per line, I find the explosion of import lines to be distracting... but that all comes down to preference.

**Comment by tweakimp** [comment]
I think you can call it more than preference because if there is no other difference, less lines is better.
in hugovks example the second version is shorter, easier to read and should be preferred in my opinion.

**Comment by asottile** [comment]
I have no stake in black's implementation, that said it's not _just a stylistic preference_. -- much like the rest of black there's a reason for its opinionated decisions.  Many of them are similar to the rationale for the tool I've written: avoid merge conflicts, reduce diff churn.

> The style chosen by `reorder-python-imports` has a single aim: reduce merge
> conflicts.
> 
> By having a single import per line, multiple contributors can
> add / remove imports from a single module without resulting in a conflict.
> 
> Consider the following example which causes a merge conflict:
> 
> ```diff
> # developer 1
> -from typing import Dict, List
> +from typing import Any, Dict, List
> ```
> 
> ```diff
> # developer 2
> -from typing import Dict, List
> +from typing import Dict, List, Tuple
> ```
> 
> no conflict with the style enforced by `reorder-python-imports`:
> 
> ```diff
> +from typing import Any
>  from typing import Dict
>  from typing import List
> +from typing import Tuple
> ```

**Comment by gwax** [comment]
Worth noting that `black` guarantees that AST of input matches AST of output. Reordering imports would break this guarantee.

Also, black plays along quite well with isort, so I'm not certain this is necessary.

**Comment by impala2** [comment]
Can we just get an option to disable checking imports? Otherwise my configured isort and black keep fighting with each other over which way is correct.

**Comment by tweakimp** [comment]
black means no options

**Comment by acdha** [comment]
@impala2 See @jensens’ https://gist.github.com/jensens/ce74e85bc297f3db46dad95fd08eb0c6 Black-compatible isort config. This is the example I come back to for why I'd like at least basic import sorting in Black: right now you have to coordinate two separate tools, one with non-trivial configuration, but with that one feature you could simply use Black with no other effort required.

**Comment by gforcada** [comment]
While reading this thread I came up with another idea...

Just like there is the `-S` switch that ignores string quotation marks, could there be another switch to ignore imports? This way, `isort` sorts the imports the way one likes, `black` takes care of the rest. :heart:

**Comment by tweakimp** [comment]
> black means no options

**Comment by mec07** [comment]
@ambv Please also consider not just the ordering of the imports, but also:

- removing unused imports
- adding in imports that are getting used, e.g. if I type `os.path.join(dir, filename)` somewhere in the file but I haven't imported `os`, then just add the `import os` statement at the top of the file.

These two features are part of the Go formatting tool (which I run on save) and I find that they save me a ton of time when writing Go code. I sorely miss these features whenever I return to Python (I run black on save).

Thanks! 😍

**Comment by tweakimp** [comment]
Adding imports would change too much

**Comment by jaroel** [comment]
In the meanwhile I've kicked out isort as it turns out I don't give a shit about import ordering.
Sorry for making a fuss. I'll take whatever black will do, big thank you up front!

**Comment by jgirardet** [comment]
>     * removing unused imports
> 
You never know what could  unused imports do (connect db ....)
But the standard behavior could be to autoremove it, and the user should put it in `nofmt` block.

>     * adding in imports that are getting used, e.g. if I type `os.path.join(dir, filename)` somewhere in the file but I haven't imported `os`, then just add the `import os` statement at the top of the file.
> 
import os or os.path ?

**Comment by mec07** [comment]
> > ```
> > * removing unused imports
> > ```
> 
> You never know what could unused imports do (connect db ....)
> But the standard behavior could be to autoremove it, and the user should put it in `nofmt` block.
I see what you're saying, but I think that is quite unusual, i.e. normally you would then use that db in the file.

> > ```
> > * adding in imports that are getting used, e.g. if I type `os.path.join(dir, filename)` somewhere in the file but I haven't imported `os`, then just add the `import os` statement at the top of the file.
> > ```
> 
> import os or os.path ?
Good idea, I like the suggestion, `import os.path` would work nicely in my example.

**Comment by asottile** [comment]
> > > * adding in imports that are getting used, e.g. if I type `os.path.join(dir, filename)` somewhere in the file but I haven't imported `os`, then just add the `import os` statement at the top of the file.
> > > ```
> > 
> > 
> > import os or os.path ?
> 
> Good idea, I like the suggestion, `import os.path` would work nicely in my example.

this is impossible to know without actually performing the import (you would no longer be a _static_ analysis tool):

```python
# f.py
class D:
    x = 1

class C:
    d = D()

c = C()
```

```python
# g.py
import f

print(f.c.d.x)  # don't `import f.c.d` it's very very wrong

**Comment by mec07** [comment]
That's a good point. Thanks for bringing that up. Sticking with `import f`
would be the way to go.

**Comment by asottile** [comment]
> 
> That's a good point. Thanks for bringing that up. Sticking with `import f` would be the way to go.

even that, you can't possibly know statically is correct either (taken from [ImportSideEffects wiki page](https://github.com/asottile/scratch/wiki/ImportSideEffects))

___

Importing a package does not mean that the sub-packages/sub-modules are imported (though sometimes it may look like that!)

Consider the following:
```
$ tree
.
└── pkg
    ├── __init__.py
    ├── mod2.py
    └── mod.py
 
1 directory, 3 files
```
```
$ tail -n 999 pkg/*
==> pkg/__init__.py <==
 
==> pkg/mod2.py <==
import pkg.mod
x = 2
 
==> pkg/mod.py <==
hi = 1
```

```python
>>> import pkg
# Doesn't work!
>>> pkg.mod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'mod'
# But if we import some module that has a side-effect of importing that module
>>> import pkg.mod2
# Suddenly it works!
# DON'T EVER DEPEND ON THIS BEHAVIOUR!
>>> pkg.mod
<module 'pkg.mod' from 'pkg/mod.py'>
```

**Comment by jgirardet** [comment]
SInce black is a numb formatter, it'll never know what the  code is doing or not. can't guess it. 
So what it can do at the end ?
- format `from bla import ble, bli, blo` inline or explode one per line (already doing it)
- change verticale spacing : for example same root module not vertical space, different root module 1 new line separation.
-  "maybe"  put all stdlib first, in alphabetical order (but I 'm not sure  if it will not break the ast).

I can't see much other things.
Import is part of coding like declaring a new function. It's not necessarily only formatting.
Nobody here ever disabled isort because of some import error ?

**Comment by bertjwregeer** [comment]
To date on the projects I have worked on I have not disabled `isort` due to import errors. Although I would argue that if an import has side effects it is wrong. I don't want side effects when I import code.

**Comment by asottile** [comment]
(I don't use gevent, but my work does a lot), you frequently need to tell import reorderers off when dealing with gevent since it needs to be patched before importing other things

(I don't use matplotlib, but some of my work does) you frequently need to tell import reorderes off when using matplotlib as you need to select a rendering approach before importing other things

just some very common examples where import reordering _requires_ configuration

**Comment by bertjwregeer** [comment]
Yeah, not a fan of monkey patching in general...

**Comment by asottile** [comment]
Just so we're clear, I'm not advocating for monkeypatching :laughing:  -- just pointing out that import reorderers tend to require some amount of configuration and

> > black means no options

**Comment by gwax** [comment]
As much as we may not like import side-effects, they do happen. Reordering can be dangerous. Adding / removing imports can be dangerous.

Encouraging `nofmt` for common scenarios suggests a design failure.

"black means no options" suggests not configuring.

Personally, I'd rather some effort go into making `isort` and `black` totally compatible and keep separate tools for separate tasks.

I find the no-AST changes guarantee of black quite comforting, especially when introducing it to large, existing projects.

**Comment by joaoe** [comment]
As mentioned, sorting top level imports can cause all sorts of issues and I personally would not feel comfortable with a tool like black doing that if my IDE can do that better, plus all the side effects when scripts setup paths before imports or when imports are wrapped in `try/except` blocks, etc...

However there is one thing that black could do which is to sort imported symbols in `from .... import...` statements which is completely benign and has no side-effects, e.g.
```
from bazinga import thats_my_spot, i_informed_you_thusly, rock_paper_scissors_lizard_spock
```
would become
```
from bazinga import (
    i_informed_you_thusly,
    rock_paper_scissors_lizard_spock,
    thats_my_spot,
)
```

**Comment by asottile** [comment]
@joaoe technically with `__getattr__` (especially in py37+ where it is a first class construct for imports) even from import ordering can have side effects

**Comment by joaoe** [comment]
> technically with `__getattr__` (especially in py37+ where it is a first class construct for imports) even from import ordering can have side effects

That sounds like stuff you'd go full Linus Torvald over the module developer.

**Comment by timothycrosley** [comment]
@ambv for what it's worth:

I agree with everything you said, especially in this comment here:

> * In general, its implementation is problematic. Everything interesting happens in an `__init__()` method; it's based on string matching and not a syntax tree, and so on.
> 
> * Its configuration based on magic discovery of first-party/third-party code only works on activated virtualenvs, making it brittle for CI.
> 
> * It moves comments around in a way that is incompatible with Black.
> 
> * However, the killer thing for me is the example you give around imports placed after function calls being moved above the calls. Black would never do that because there are simply too many cases where this breaks the file. This makes code modding any larger codebase unsafe.

I am, with the help of other people in the community (especially @mkurnikov, thank you!) hoping to use these items as a roadmap for the next major isort release.  I made isort many many years ago, and have been kind of blown away and surprised by the extent of its success, but I am not one to leave things to die after people start using them. I am happy to take responsibility or even just do my part to help make it better. I have learned a tremendous amount since I first released isort, and I believe it would match a lot more of what you expect if I were to build it today. But in the end, that's not what matters to me, as much as what can be done now that will have the best outcome for the Python community. If a better more robust and black compatible isort is that, which at this point I believe it is, I will do my best to ensure that happens. If instead, helping black do sorting was that, I would be happy to help with that effort as well. My intuition is that feels inconsistent with the other goals of Black, specifically at odds with not modifying AST. Re-ordering imports, even if done perfectly, does, inherently come with some danger of breaking previously functional code. That, of course, also implies more configuration being necessary than that used in gofmt - and what I believe Black is aiming for. Though certainly less than isort has now. My current goal is to soon release a black_isort that solves all of the above complaints, and ensures compatibility with black while exposing only the minimal necessary configuration options.

**Comment by ambv** [comment]
`black_isort` written by the original author of `isort` sounds like the ideal situation for us. Thanks so much for your input. Let me know if you need any help.

**Comment by asottile** [comment]
fwiw, both [asottile/reorder_python_imports](https://github.com/asottile/reorder_python_imports) and [sqlalchemyorg/zimports](https://github.com/sqlalchemyorg/zimports) import sorters are black compatbile without configuration

**Comment by mkurnikov** [comment]
My whole venture of rewriting isort is motivated by this issue https://github.com/timothycrosley/isort/issues/818. I want imports under `if TYPE_CHECKING` be ordered too. @asottile, does any of the libraries support this usecase?

**Comment by asottile** [comment]
not that I know of, though I suspect it wouldn't be too difficult

**Comment by thomasf** [comment]
I believe that import sorting is a worth while feature. I also think that by default black should not modify the AST (it's a good goal). This by necessity requires there to be an option to enable this feature or not have it at all.

**Comment by don-mums** [comment]
I would be careful with this one. Sorting imports not only modifies AST but also can break stuff. I know one project that broke after isort modified every file in the codebase. It created cyclic imports that didn't occur when imports weren't sorted.

**Comment by tweakimp** [comment]
what about removing double imports or rewriting them so all have the same format?

**Comment by joaoe** [comment]
> It created cyclic imports that didn't occur when imports weren't sorted.

That's really not the tools' fault. Junk in, junk out.

**Comment by thomasf** [comment]
> > It created cyclic imports that didn't occur when imports weren't sorted.
> 
> That's really not the tools' fault. Junk in, junk out.

It depends, if there was a proper comment explaining why the import order mattered it should be allowed even if it's a questionable design choice.  I would guess that at the very least `# fmt: on/off` will be supported by black in the imports section as well if this feature gets added.

**Comment by joaoe** [comment]
> It depends, if there was a proper comment explaining why the import order mattered it should be allowed even if it's a questionable design choice.

Cyclic imports is broken code. I'm not going to blame the devs, I also had my share of codebases that grew from tiny, to big and spaghettified and then needed much cleanup. But you can't expect tools like pyflakes, flake8, isort and whatnot to fix broken code for you.

**Comment by thomasf** [comment]
The code is not broken until the imports are reordered in way that breaks the code.

**Comment by JelleZijlstra** [comment]
Please stop arguing about whose fault it is when import sorting breaks code. Here is what Black can guarantee:

- Future releases of Black will not make AST-unsafe changes, such as sorting imports, unless the user passes in an explicit opt-in flag.
- If we do add support for import sorting, we will provide escape hatches to enable users to avoid sorting when necessary, such as only sorting imports that are not separated by comments.

**Comment by stuartmaxwell** [comment]
Hi all - hope I'm posting this in the right place. I'm using Black with VS Code and working through the Flask Mega Tutorial https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

The following code breaks after running Black on it:

```python
from flask import Flask

app = Flask(__name__)

from app import routes
```

It is re-formatted with the `from` statements at the top of the file which breaks the code:

```python
from app import routes
from flask import Flask

app = Flask(__name__)
```

Is this due to the same issues raised in this thread? The author of the tutorial believes that the `from` statement belongs at the bottom of the code: 

> Another peculiarity is that the routes module is imported at the bottom and not at the top of the script as it is always done. The bottom import is a workaround to circular imports, a common problem with Flask applications. You are going to see that the routes module needs to import the app variable defined in this script, so putting one of the reciprocal imports at the bottom avoids the error that results from the mutual references between these two files.

**Comment by mrshannon** [comment]
After some experimentation I came across the following minimal isort configuration which is completely compatible with black and avoids any conflict between the tools.
```.ini
[isort]
line_length = 88
use_parentheses = True
include_trailing_comma = True
multi_line_output = 3
```

*If you override black's default line length then change the isort line length to match.*

Unlike the configuration posted by @jensens (thanks for the starting point), this configuration only contains settings required for compatibility with black, leaving all others to isort's defaults.  

Theoretically, any further customization will remain black compatible as long as it does not modify the settings above and does not touch any of the following:

* lines_after_imports
* lines_between_types
* indent
* force_grid_wrap

In my opinion, import sorting is beyond the scope of black.  However, it may be of use to document the minimal black compatible isort configuration just as workarounds for flake8 and black are documented.

It would also be beneficial if isort's documentation contained a similar black compatibility section.

**Comment by bertjwregeer** [comment]
Isn't this already listed under "a black compatible .isort.cfg" in the README under How black wraps lines: https://github.com/psf/black#how-black-wraps-lines: (I wish I could link to it directly)

**Comment by bertjwregeer** [comment]
I will note however, that due to the way that `isort` includes configuration files (and walks up the directory tree, and includes the users default isort configuration from their home dir) you should likely explicitly set all options (even the ones that are defaults) so that the project isort overrides any other isort configuration it finds.

This was very confusing to me at one point... not really a black comment, but figured it would be helpful to mention it either way.

**Comment by Jma353** [comment]
Wanted to revisit this thread. What are the next-steps here?

Wanted touch on a couple of things:
* I am happy to help (with hopefully the help from others) add some import sorting functionality to `black` (NOT turned on by default, with settings + escape hatches that @JelleZijlstra mentioned).  This would benefit the community, and prevent folks from having to use 2 tools if they want autoformatting + import sorting, and not JUST import sorting.
* I don't want to step on @timothycrosley's toes w.r.t. the `black_isort` project mentioned above.  What is the status of this?

**Comment by timothycrosley** [comment]
@Jma353, I'm working on this at the moment and making good progress. isort 5.0.0 should come out shortly, with a built in Black compatible profile and tests to ensure they stay in-sync. A standalone black-isort that provides gaurenteed 100% compatibility into the future is planned shortly after that release.

**Comment by brot** [comment]
I would like to refer to https://github.com/psf/black/issues/517#issuecomment-626185395  
Will this issue also become one of those relevant for Milestone "stable"?

In our team there are a lot discussions about how to write imports and this feature would help.  
Or if this feature gets dropped we will look into isort, but there should be a way to use black (and maybe isort) without too much code rewriting when some of the tools gets updated or "feature-merged" into the other

**Comment by zsol** [comment]
No, this is out of scope for a stable release.

**Comment by timothycrosley** [comment]
Well this took way longer than expected, but I never stopped working on it (every single day in fact!). isort 5.0.0 is now released with a built in black compatible profile and with all the points @ambv brought up addressed.  https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/

**Comment by aericson** [comment]
> Well this took way longer than expected, but I never stopped working on it (every single day in fact!). isort 5.0.0 is now released with a built in black compatible profile and with all the points @ambv brought up addressed.  https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/

Well done @timothycrosley  can't wait to try :D

**Comment by teresaejunior** [comment]
I get a very noticeable slowdown on VS Code when using `"editor.formatOnSave"` and black+isort together with `"editor.codeActionsOnSave": {"source.organizeImports": true}`. Tested on very small files, will disable isort for now.

**Comment by tlocke** [comment]
It seems a good clear division of labour to have Black guaranteed to preserve the AST and be purely a formatter, and have other checking tools that are guaranteed to avoid formatting and concentrate only on looking at the AST. To that end I've written Flake8 Alphabetize https://github.com/tlocke/flake8-alphabetize/ any feedback gratefully received.

That said, there is a formatting task that Black would need to do, and that's to:

* First remove any line breaks between import statements.
* Then put line breaks between import statements that belong to the different import groups identified by PEP8 (Standard Library, Third Party and Application).

For Black to be able to identify Application imports it would need perhaps need a configuration option that took a list of application package names?

**Comment by WhyNotHugo** [comment]
What's wrong with [flake8-import-order](https://github.com/PyCQA/flake8-import-order) and [reorder-python-imports](https://pypi.org/project/reorder-python-imports/)?

I don't think we needed another tools for this (there's so many floating around!), the issues here is about whether we want this integrated into black.

**Comment by hadialqattan** [comment]
For the time being, we can use [`pycln`](https://pypi.org/project/pycln/) and [`isort`](https://pypi.org/project/isort/).

**Comment by abitrolly** [comment]
`isort` lacks uncompromising defaults, so projects like https://github.com/pypa/warehouse have to use a config.

```
[tool.isort]
profile = 'black'
lines_between_types = 1
combine_as_imports = true
```

**Comment by zsol** [comment]
FWIW at my company we use [usort](https://usort.readthedocs.io/en/stable/guide.html) together with Black, and in our own open source repos we encourage [ufmt](https://github.com/omnilib/ufmt) which combines the two.

Note that `usort` has a slightly different style than `isort` in Black-compatibility mode, but at least it's minimally configurable and gets the job done.

**Comment by WhyNotHugo** [comment]
@zsol Have you considered something equivalent to isort's `force_single_line=true`?

It dramatically reduces merge conflict issues, which kinda aligns to how black approaches a lot of formatting too.

**Comment by danielbraun89** [comment]
Black absolutely should _not_ sort or touch imports whatsoever. Many times import order and convention are manually crafted to allow specific behavior (monkey patching, for example) and should never get mangled by a formatter.  As noted above this is directly changing the program AST.

**Comment by autoferrit** [comment]
For me, I run autoflake, isort, and black and if I run black last, it reorders some imports. For example, if I have these imports after running isort, and before running black:
```python
# Third Party
from jsonpath_ng.ext import parse

# Library
from myapp import utils as u
from myapp.custom_exceptions import (
    ...
)
from myapp.json_factory import JsonFactory
```
but after running black I have this
```python
# Third Party

# Library
from myapp import utils as u
from myapp.custom_exceptions import (
    ...
)
from myapp.json_factory import JsonFactory
from jsonpath_ng.ext import parse
```
The `jsonpath_ng` package is a 3rd party package. So black is moving it to here when I feel like black should not touch the imports at all. This is my config for both in `pyproject.toml`
```toml
[tool.black]
line-length = 80
target-version = ['py38']
include = '''
(
      \.pyi?$
    | \.py?$
    | ^/tests/
    | ^/src/
)
'''
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | __pycache__
    | buck-out
    | build
    | dist
    | .*/migrations
    | \.github
    | ci
    | node_modules
    | static
    | staticfiles
  )/
  | \.html
  | \.js
  | \.css
  | \.scss
)
'''

[tool.isort]
import_heading_firstparty = "Library"
import_heading_future = "Futures"
import_heading_local = "Local"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
indent = 4
known_first_party = "myapp"
lines_after_imports = 2
lines_between_types = 1
profile = "black"
```

If people feel we must sort imports (I am fairly against this because it is easy to use these tools automatically), then why are we bothering to try and find out how to fix imports, just detect if `isort` is installed and call that to run the imports. if it is not, then don't do anything. 

we could always install black like `pip install black[isort]` or something too to bring in that requirement. Like others, we have places in our code where imports need to be placed in the middle of a file or after other lines, which also helps with circular imports. So even then, if it is added it should be disabled by default.

**Comment by JelleZijlstra** [comment]
Black doesn't sort imports. I don't know what tool is reordering your imports, but it's not black.

**Comment by autoferrit** [comment]
I know it shouldn't now, but it is. running it directly from the cli using that as the config, black is changing imports after running isort. I am working on filling out a possible bug request to try and find out why.

**Comment by rmax** [comment]
#I use this settings and have no problem with running `black` and `isort`

```
# black compatibility settings
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
```

**Comment by janosh** [comment]
@rmax You might try just
```cfg
[isort]
profile = "black"
```

See [`isort` docs on `black` compatibility](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html).

**Comment by mcarans** [comment]
I am running blackd from PyCharm via the BlackConnect plugin. It would be great if black handled the imports as well. There is no working equivalent for isort on PyCharm. In any case, running separate daemons for each seems like overkill.

**Comment by zsol** [comment]
I'm going to close this issue as we don't have plans for introducing import sorting into Black. There are several existing tools that provide import sorting really well, like [isort](https://github.com/PyCQA/isort) and [usort](https://github.com/facebookexperimental/usort). If you're interested in a single tool that combines both, there's [ufmt](https://github.com/omnilib/ufmt).

**Comment by stefaneidelloth** [comment]
I tried ufmt but it does not resolve my issues with the import order found by pylint:

third party import ... should be placed before ...
