### ISSUE TITLE
No matching distribution found for hatchling>=1.8.0

### ISSUE THREAD

**Issue by tnhgiang** [psf/black#3335]
**Describe the bug**

**To Reproduce**

`pre-commit` configuration:

```
  repos:
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        - id: black
```

And run `pre-commit`:

```sh
pre-commit run --all-files
```

The resulting error is:

> An unexpected error has occurred: CalledProcessError: command: ('/home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/tnhgiang/.cache/pre-commit/repomavgntpv
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/bin/python /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wkrhsflu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'hatchling>=1.8.0' hatch-vcs hatch-fancy-pypi-readme
           cwd: None
      Complete output (2 lines):
      ERROR: Could not find a version that satisfies the requirement hatchling>=1.8.0
      ERROR: No matching distribution found for hatchling>=1.8.0
      ----------------------------------------
    WARNING: Discarding file:///home/tnhgiang/.cache/pre-commit/repomavgntpv. Command errored out with exit status 1: /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/bin/python /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wkrhsflu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'hatchling>=1.8.0' hatch-vcs hatch-fancy-pypi-readme Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/bin/python /home/tnhgiang/.cache/pre-commit/repomavgntpv/py_env-python3.6/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wkrhsflu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'hatchling>=1.8.0' hatch-vcs hatch-fancy-pypi-readme Check the logs for full command output.

**Expected behavior**

**Environment**

- Black's version: `22.10.0`
- Pre-commit's version: `2.17.0`

**Additional context**
When I downgrade the black version to `22.8.0`, the problem is solved.

**Comment by ichard26** [comment]
Black hasn't supported Python 3.6 since 22.10.0. Our build backend, Hatching, never supported 3.6 and that's why `No matching distribution found for hatchling>=1.8.0` is occurring.

I do wonder if we have pre-commit fail in a more user-friendly way though.

**Comment by tnhgiang** [comment]
Thanks a lot @ichard26
