### ISSUE TITLE
up for adoption: blacken-docs

### ISSUE THREAD

**Issue by asottile** [psf/black#3343]
https://github.com/asottile/blacken-docs

I don't really know how to do this so I'll try and be succinct -- sorry this is off topic as well and that I deleted the issue template

for me, **maintaining `blacken-docs` no longer sparks joy** -- and it's not due to the integration with black (which has been fine since stable) -- but because docs are complicated  (and, well, I don't actually use it).

I'd love to figure out a way forward where either this is adopted or integrated in some way -- but I just don't know.

the implementation also isn't the _best_, it's kind of a pile of pretty-good regexes in place of actual parsers for the various formats.

I feel bad about this, but also I'm just very tired right now

**Comment by jugmac00** [comment]
Hey Anthony,

FWIW there is also https://github.com/keewis/blackdoc which we adopted at work. The mission seems to be the same, possibly also the features. Additionally, back then my colleague mentioned that `blackdoc` handled our legacy doctests very well. The maintainer @keewis is very active and friendly. Maybe there is a chance that these two projects can be "merged" in some way?

And thanks for your awesome work. Great decision to keep doing what motivates you :heart:

**Comment by adamchainz** [comment]
I’d be happy to maintain blacken-docs, it sparks joy for me. I love using it on my blog and I promoted it [on my blog](https://adamj.eu/tech/2021/09/13/three-cheers-for-blacken-docs/) and in my book.

**Comment by asottile** [comment]
alright -- I'll organize a transfer of things next week after I'm back from vacation -- appreciate it a lot @adamchainz

**Comment by ichard26** [comment]
Thank you so much @adamchainz for stepping up! While I don't have the time to commit to being a maintainer, I'm happy to help from time to time. Consider this as permission to ping me when needed!

**Comment by adamchainz** [comment]
Thanks @ichard26 !
