### ISSUE TITLE
No, tabs for indentation are the devil. Making this configurable would go against Black's philosophy.

### ISSUE THREAD

**Issue by busterbeam** [psf/black#3349]
No, tabs for indentation are the devil. Making this configurable would go against Black's philosophy.

_Originally posted by @ambv in https://github.com/psf/black/issues/47#issuecomment-374964663_

I'm brining up again.  I found one **fork** that uses tab's but its getting old.  I'm not going to try to reason why tabs are better (and believe me I have good reasons).  I'm trying to make working **fork** right now but hitting hard with tests, I've modified the tests to include tabs instead of spaces, but I'm still getting fail error messages.

In particular 
```
Oh no! 💥 💔 💥
1 file would be reformatted.
```

with the data/simple_cases/composition.py file.  any thoughts or help?

**Comment by felix-hilden** [comment]
Sorry, not really. After #2798 we're done with discussing tabs and at least I personally have no interest in debugging forks that actively go against our decisions.

**Comment by busterbeam** [comment]
Alright, fair enough, I didn't expect any support on, this just hoping. If my fork gets "fixed" thoughts on linking to it in your README? For anyone else looking for `black` with tab indentation.

I really like black on so many levels.  Just to clarify I'm not making `black` "configurable" I'm straight making a version that works with tab indentation instead

**Comment by felix-hilden** [comment]
I feel you, and was almost convinced by tabs because of the accessibility argument. But that's also a "no" I'm afraid, at least if we're holding our line from [previous comments](https://github.com/psf/black/issues/2798#issuecomment-1026065042). Using a fork essentially *is* the configuration, right? We've seen a bunch of forks and other wrappers suggested already, none of which we endorse or want to point users to. We do have a [FAQ entry](https://black.readthedocs.io/en/stable/faq.html#why-spaces-i-prefer-tabs) for the accessibility issue though.

**Comment by JelleZijlstra** [comment]
We are not switching to tabs, and we are not publicizing any Black forks.

**Comment by busterbeam** [comment]
> We are not switching to tabs

I know that, what's with repeating that?
> not publicizing any Black forks.

Yes [felix-hilden](https://github.com/felix-hilden) said something similar.

my last words on the matter in this issue will be.  I'm far from making this fork "sustainable" but I imagine that this will be helpful to black in the long term as how I plan to make the fork in the end will encourage "tab" enthusiasts to help develop `black`.  I think you should at least be comfortable with at least promoting a fork in a deprecating way such as "you can use the wrong one" or "you can do it the wrong way".

**Comment by Bunker-D** [comment]
@busterbeam, did you and up building or finding a more recent alternative to `black-with-tabs`?

**Comment by busterbeam** [comment]
> @busterbeam, did you and up building or finding a more recent alternative to `black-with-tabs`?
> 

Nope. I kind of find black overkill at what it does. I just stick to pep8 based solutions. Pyflakes, and pylint is enough for me and provide tab options.
