### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by Freed-Wu** [psf/black#3352]
```python
VERSION: Final = """{version} Copyright (C) 2022 """.format(version=__version__)
```

Expected: Nothing changed.

Actual:

```python
VERSION: Final = """{version} Copyright (C) 2022 """.format(
    version=__version__
)
```

**Comment by felix-hilden** [comment]
This is not the case on the [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC7AH5dAD2IimZxl1N_Wkh8xolBXZUb9-KngBV6iGg1nnMfChB33WPNfzw9lPdUuXGkUCykVKpS_Vd-VXKQNYyDn9m0OoXlIj3dd9QFnerrmtTIZBD19q5PsvQF4v-9PSPHih6b-QksaDI-MxmAcpAl0NTH9G_jxQNrKLAlz4ugLjQxAAAAAC6Cv0yj2yDkAAGaAbwBAABdU64UscRn-wIAAAAABFla). Have you set line length to be less than the default?

**Comment by Freed-Wu** [comment]
Yes, I have
```
[tool.black]
line-length = 79
# ex: filetype=toml
```

**Comment by Freed-Wu** [comment]
Oh, after delete the file, it looks like normal. Thanks!
