### ISSUE TITLE
Lint `src/blib2to3`

### ISSUE THREAD

**Issue by clavedeluna** [psf/black#3355]
**Is your feature request related to a problem? Please describe.**

As I've been working on some black issues and overall getting a hang of the repo, I got really frustrated when debugging methods which name an arg or a variable as the built-in `type`, for example:

`def printtoken(type, token, xxx_todo_changeme, xxx_todo_changeme1, line):  # for testing`
`def addtoken(self, type: int, value: Text, context: Context) -> bool:`

You can find many of these with `pylint src --disable=all --enable=redefined-builtin`

**Describe the solution you'd like**

There are quite a bit of linting issues in the repo in addition to this one:
- unused imports still at top of module
- unused variables
- etc

**Describe alternatives you've considered**

Can we add a pylint step to github actions so developers start using it locally, too? I think an iterative approach would be reasonable, so start with something like `pylint src --disable=all --enable=redefined-builtin` and slowly start enabling more checks as they're fixed in a new PR.

**Additional context**

This would help maintain code as well as debug. If you're using `pdb`. and you want to check the `type` of an object, if there's already a variable called `type` it doesn't work ....

**Comment by JelleZijlstra** [comment]
We already have flake8 set up for linting. I haven't had positive experiences with pylint: it has too many checks that aren't useful and it's slow. I'd be open to adding more flake8 plugins or enable additional rules though.

**Comment by clavedeluna** [comment]
@JelleZijlstra I'll focus on flake8 then. Im I mistaken or is the current pre-commit configuration for flake8 not running in some sub directories inside `src`? For example, running locally:

```
 $ flake8 src/
src/blib2to3/pygram.py:12:1: F401 '.pgen2.token' imported but unused
src/blib2to3/pytree.py:760:13: E731 do not assign a lambda expression, use a def
src/blib2to3/pgen2/token.py:81:21: E721 do not compare types, use 'isinstance()'
src/blib2to3/pgen2/pgen.py:20:1: F811 redefinition of unused 'grammar' from line 5
src/blib2to3/pgen2/pgen.py:85:13: E265 block comment should start with '# '
src/blib2to3/pgen2/pgen.py:195:13: F841 local variable 'oldlen' is assigned to but never used
src/blib2to3/pgen2/pgen.py:197:13: F841 local variable 'newlen' is assigned to but never used
src/blib2to3/pgen2/pgen.py:373:13: E722 do not use bare 'except'
src/blib2to3/pgen2/parse.py:12:1: F401 'copy' imported but unused
...
...
```

So lots of cleanup can happen inside `blib2to3`. 
And regarding the original issue of assigning vars to builtin-names, we could use [flake8-builtins](https://pypi.org/project/flake8-builtins/) for that. What do you think?

**Comment by JelleZijlstra** [comment]
I think we didn't run flake8 on blib2to3 initially because it was mostly vendored third-party code. However, we've been modifying it more and more, so it makes sense to point the linter to it too now.

As for builtins, personally I'm not too bothered by reusing names like "type". However, if another maintainer thinks it's valuable to add this plugin, I'd be OK with it.

**Comment by clavedeluna** [comment]
> I'm not too bothered by reusing names like "type".

`type` is probably the least egregious one, but if someone things that's an acceptable practice, then how about the bad behavior that comes out of shadowing `list`, `max`, etc. It's a huge slippery slope.

**Comment by felix-hilden** [comment]
Not a big deal, but also can't hurt to rename them e.g. `type_`. Sounds reasonable to me 👍

**Comment by clavedeluna** [comment]
I can make a PR to update `exclude: ^(src/blib2to3/|profiling/|tests/data/)` from pre-commit-config to remove blib2to3 so flake8, isort, etc can run on it. Sounds like you all agree this is fine and won't cause issues if merging with a new version of blib2to3 were to happen.

**Comment by ichard26** [comment]
Looks like we are in favour, go for it @clavedeluna! Lib2to3 (from Python core) isn't being developed anymore so we won't be merging in a new upstream revision anytime 🙂
