### ISSUE TITLE
Move module-level dunder names before the import statements

### ISSUE THREAD

**Issue by Deejuha** [psf/black#3358]
**Is your feature request related to a problem? Please describe.**

[PEP8](https://pep8.org/#module-level-dunder-names) says that module level dunder names like `__all__` shall be before import statements, but after the `__future__` statement.

**Describe the solution you'd like**

How about to move the dunder names to their place according to PEP8 using the black?

**Comment by denballakh** [comment]
Black is formatter, not linter with autofixing. Also black doesnt change AST.
If you move dunders before imports, you can get broken code:
```py
from a import b
__some_dunder__= b
```
After formatting:
```py
__some_dunder__ = b # NameError
from a import b
```

**Comment by ichard26** [comment]
Yeah I agree this is out of scope for Black. This is a AST unsafe change and would break valid code. Using GitHub Code Search, here are some examples:

- https://github.com/odoo/odoo/blob/177b83ea48197d079ef8568f725008d2f85f1c0b/odoo/cli/server.py#L31
- https://github.com/getsentry/sentry/blob/b5e473b1913fd43738021eba80f7316bf181b8ca/src/sentry/__init__.py#L55
- https://github.com/jumpserver/jumpserver/blob/104dd9721b221178fc0af3a6e5ea829b90b1f291/jms#L27

I'm sorry, but currently we do not have any plans to introduce additional AST unsafe codemods (and especially ones that can break code).
