### ISSUE TITLE
Ambiguity in the documentation 

### ISSUE THREAD

**Issue by Lincoln-Chamberlin** [psf/black#3375]
**Is this related to a problem? Please describe.**

This is a suggestion to improve some ambiguity in the Pragmatism section of the documentation.
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting

Current text (first paragraph of section 'AST before and after formatting')
> When run with --safe, Black checks that the code before and after is semantically equivalent. This check is done by comparing the AST of the source with the AST of the target.

**Describe the solution you'd like**

I would like to see it specified that --safe is the default. The currently wording makes it sound like --safe is an available option that can be specified but is not enabled by default. 

**Additional context**

I decided to submit this improvement suggestion after reading this, misunderstanding it, and looking through the customization documentation, only to find that what I want is already the default.

**Comment by JelleZijlstra** [comment]
Good point, PR welcome!

**Comment by Lincoln-Chamberlin** [comment]
I would recommend a wording like
>  When run with --safe (the default), Black checks that the code before and after is semantically equivalent. This check is done by comparing the AST of the source with the AST of the target.

I am not currently interested in learning about the pull request prosses for black

**Comment by ichard26** [comment]
No worries! This makes for an easy PR that's great for beginners. I won't say no to that :)

**Comment by aaossa** [comment]
This seems to have been completed by #3378

**Comment by ichard26** [comment]
Yup! Thanks for noticing! I really did merge that PR mindlessly didn't I... whoops :)
