### ISSUE TITLE
Not sure what the bug was. Might be me importing a custom function, but it still crashed when I defined it at the top

### ISSUE THREAD

**Issue by Shadow2008** [psf/black#3387]
**Black v22.10.0**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ARIAd1dAD2IimZxl1N_WlkPinBFoZRaGKlkXO7YMZhsw67RXaXtuJjalQlEjZ2xRlS7zJwwsbVAP4y8MNUapf5X-gLM_REfl5D1HMkw3DhDV96-f0L3qab9mfVZU1qB5lxBoLoMvstQBhDcnD4UMoobHN7VDT7xfSqXwv5gDSDdv4IkM8mSA8y9ETiW4iI02A3Gv3UwcQ2TwKoPZRFZdS-fOeDr6u_EUOA4mQaYmYkswaUMu0KbfifC7l36cAD7ky1piz41kFSNk7MoCeK880Vea5JA2g52VMoHDeZ1NlMyli_jrZknlbwDwBb5Bmg6P2qJp0QpYsYRrvZvhHMHZREib_6M_ZyMV9AKp3odvGpGudb-vEf9GauiM0htb9WgyOgFkYSwGsmlNGJbDoZJMpXBklQg2HOfMbPMpzCou_ykJyvVv9hgwUGSbnUF058V1c20yYN9gbVO02EqXVqU2_Adore7QdnSoCyYucsyssThCvRqhMZzESXTQgasQ17adqJ-U0lePuIzG38I07gdn_dpmDeieVdVLzCc9drs9gAjH98gwmyAaJug2-DSZlXoWWzoQijq8Vd5Kk0qtbsh-qxmgtpotGL6iEZLmuemyrL3wFW9SriTu_LILQ7vSi6ObgubTgAAAADHPywxpajvagAB-QPJCAAA6BY-s7HEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
from turtle import *
from betterInput import getInt

speed(0)
betweenBounds == False
numPoints = getInt("Enter an odd number: ", odd=True)
numPointsSkip = 1
int(numPoints/4) = smallNum
while numPoints % numPointsSkip == 0 and not betweenBounds:
    numPointsSkip = getInt(
        f"Enter a number. It may not divide the number\
of points in the star, and must be between \
{smallNum} and {smallNum*3}: "
    )
    if numPointsSkip >= smallNum and numPointsSkip <= smallNum * 3:
        betweenBounds = True
    
xCors = []
yCors = []

pu()
goto(0, -50)
pd()

for i in range(numPoints):
    circle(100, 360 / numPoints)
    xCors.append(xcor())
    yCors.append(ycor())
pointToGo = 0
pos = pointToGo % numPoints
pu()
goto(xCors[pos], yCors[pos])
pd()
for i in range(numPoints + 1):
    pos = pointToGo % numPoints
    goto(xCors[pos], yCors[pos])
    pointToGo += numPointsSkip

```

## Output

```python
cannot use --safe with this file; failed to parse source file AST: cannot assign to function call (<unknown>, line 8)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```

## Expected

**Comment by JelleZijlstra** [comment]
You have a syntax error on the line `int(numPoints/4) = smallNum`.
