### ISSUE TITLE
Don't replace global config with `pyproject.toml` one, overlay `pyproject.toml` one over the global one

### ISSUE THREAD

**Issue by KOLANICH** [psf/black#3391]
**Is your feature request related to a problem? Please describe.**

If a user wants to require a certain aspect in `pyproject.toml`, he can do it. If he doesn't do it, then it means he doesn't care. It should be up to the global config of the one running the tool. If a user wants to enforce the black-default value, he can define a field, but leave it as `None` and `black` should set the default value for that field.

**Describe the solution you'd like**

```python
config = dict(globalConfig)
config.update(pyprojectConfig)
```

**Comment by felix-hilden** [comment]
Hi, thanks for the submission! But this sounds a bit problematic for cases where people want the default style, and they want to enforce it. Someone overriding e.g. line length globally would get different results if the repo they were working on didn't explicitly set it to equal the default line length. Which seems quite awkward.

What would you use this feature for?

**Comment by felix-hilden** [comment]
Right, I hear you. But at least to me personally, especially Black being an opinionated formatter, if I don't configure something I definitely want the default. And CI checks and such won't have any user configuration either, so that could lead to a lot of confusion.

**Comment by KOLANICH** [comment]
OK. My `antiflash` has solved my problems (the defaults of `black` I don't like: spaces instead of tabs (incompletely, docstrings are still disrupted, it may be there are some more places I need to monkey-patch) and word-wrapping by default), so I guess this issue can be closed.
