### ISSUE TITLE
`Chat` link is an invalid discord invite

### ISSUE THREAD

**Issue by Avasam** [psf/black#3398]
**Is this related to a problem? Please describe.**

https://discord.com/invite/RtVdv86PrH is not a valid invite
![image](https://user-images.githubusercontent.com/1350584/204857517-6257602f-3e9b-452f-9795-8344131d54f5.png)
![image](https://user-images.githubusercontent.com/1350584/204857550-94218c46-c0da-43e8-b629-46330cde9149.png)

**Describe the solution you'd like**

Fixing the broken link :)

**Comment by Avasam** [comment]
Is the channel accessible by default? In other words, do new members need to be given a role before they can see the channel?

> Private or Public Channel: The invite link you were given might go to a private channel in the server. Remember: generated invites aren't to a server in general, but to a specific channel in the server. So it is crucial for the invite to go to a channel that is not a private channel and can be accessed by the @everyone role.

**Comment by JelleZijlstra** [comment]
The channel is public.

**Comment by Avasam** [comment]
Ok, I'll contact discord and re-open this issue if it seems to be on the server's side.
