### ISSUE TITLE
Crash in preview style with assert + parenthesized string

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3414]
```python
assert xxxxxxxxx.xxxxxxxxx.xxxxxxxxx(
    xxxxxxxxx
).xxxxxxxxxxxxxxxxxx(), (
    "xxx {xxxxxxxxx} xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
)
```
Running `black --preview` on this file results in `error: cannot format xxxxxx.py: Unable to match a closing bracket to the following opening bracket: `.

This is a regression in 22.12.0. It bisects to #3370, cc @yilei.

**Comment by yilei** [comment]
Thanks for the cc, I'll take a look!
