### ISSUE TITLE
Change the '=' in function

### ISSUE THREAD

**Issue by POEG1726** [psf/black#3421]
**Describe the style change**
Em,actually i dont know how to configure black in file.
I use python3.7.9 before,but after i updated to python3.8.10,the style i used is gone........
I have adapted to the style used before.

I want to change the "="  style in a function,I want to add space(other place is normal)，i think it is better.

**Examples in the current _Black_ style**
![image](https://user-images.githubusercontent.com/73727028/206867703-d2a76c22-5afb-4930-be46-76e75c6ff4aa.png)

```python
def a(n1, n2):
    arr = []
    ints = 123456789
    string = ''
    dicts = {}
    print(n1, n2)


a(n1=1, n2=2)
```

```python
def f():
    "Make sure this code is blackened"""
    pass
```

**Desired style**

![image](https://user-images.githubusercontent.com/73727028/206867180-f027e101-edae-48b4-9202-3f0acb3d0120.png)

```python
def a(n1, n2):
    arr = []
    ints = 123456789
    string = ''
    dicts = {}
    print(n1, n2)


a(n1 = 1, n2 = 2)
```

**Additional context**

**Comment by JelleZijlstra** [comment]
This is a core aspect of Black's style and we will not be changing it.
