### ISSUE TITLE
Crash in preview style with multiline quoted return-position type hint

### ISSUE THREAD

**Issue by intgr** [psf/black#3435]
**Describe the bug**

When using `--preview`, this input causes error message "Unable to match a closing bracket to the following opening bracket: )". No issues when running without --preview

Looks similar to #3414, but I can still reproduce this issue in main branch.

**To Reproduce**

```python
from typing import Generic, TypeVar

T = TypeVar("T")


class VeryLongClassNameWithAwkwardGenericSubtype(Generic[T]):
    pass


def something(
    argument: (
        "VeryLongClassNameWithAwkwardGenericSubtype[int] |"
        "VeryLongClassNameWithAwkwardGenericSubtype[str]"
    ),
) -> (
    "VeryLongClassNameWithAwkwardGenericSubtype[int] |"
    "VeryLongClassNameWithAwkwardGenericSubtype[str]"
):
    ...
```

**Environment**

- Black's version: 22.12.1.dev7+gabd2b25
- OS and Python version: 3.10.8, macOS

**Comment by intgr** [comment]
Playground link: https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIlAPRdAD2IimZxl1N_WlkPinBFoZStZNLAcBn-vRxIYUS6LBjgODYn4i0dWfCv56OwMhvJUPFATa0SlUYBBa_4t5rOihhZPVWyHho1PE8scTNEjoOcE-sX2dQlkNuwgjqCvIdDNifWsw8OmdnupQn3pWscSiIfZKreodKHEu8jKLJI-JZieCcodZ6lHNmorrcYLXp8uRIs7g0Ns_RZ5Yb1iETNRzoiCUlASX_HDa_Mz8P1e-s7sCVR5KwXkACPey_VgQpEQp7IWT0QpX2i00glycdxjK5uzwdOXCS6QaskeJ_WOUg3-ihsqpvy3bblZ0huHiPcy6NfYOYAE8kgbdjW7QoAAZACpgQAAPt_-suxxGf7AgAAAAAEWVo=

**Comment by JelleZijlstra** [comment]
thanks, cc @yilei as for the previous similar crash

**Comment by yilei** [comment]
Quick note: this bug exists in v22.1.0 so it's pretty old.
