### ISSUE TITLE
No Match Case Support for Python 3.10+

### ISSUE THREAD

**Issue by hg0428** [psf/black#3441]
**Describe the bug**

Black does not format files that include match case.
It won't format any of it.

**To Reproduce**

Just put

For example, take this code:

```python
match {'type':'Example','value':'null'}:
 case {'type':'Function','value':value}:
  pass#...
 case {'type':'Example','value':'null'):
  pass#...
```

And run it with these arguments:

```sh
$ black file.py --t py311
```

The resulting error is:

> error: cannot format Exec.py: cannot use --safe with this file; failed to parse source file AST: invalid syntax (<unknown>, Line 182)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.

**Expected behavior**

I expected it to format the code.

**Environment**

- Black's version: I tried it with all the latest releases.
- OS and Python version: Linux/Python 3.11a07

**Additional context**

**Comment by JelleZijlstra** [comment]
We definitely support match/case. You may be running a different version of Black or Python than you think. What does `black --version` output?

**Comment by hg0428** [comment]
> We definitely support match/case. You may be running a different version of Black or Python than you think. What does `black --version` output?
## `black --version` output:
```
22.12.1dev8+g7d062ec (compiled: no)
Python (CPython) 3.9.13
```
## `python --version` output:
```
Python 3.11.0a7
```

**Comment by hg0428** [comment]
It seems maybe black is using an older version of Python?
I only have 3.11 installed.

**Comment by JelleZijlstra** [comment]
Black is running under Python 3.9, as the above output indicates. Install it using 3.10 or 3.11 instead.

It also seems like you are installing from main, not from a release. That's fine if you're developing Black, but it means that bugs you encounter may not be valid.

**Comment by hg0428** [comment]
> Black is running under Python 3.9, as the above output indicates. Install it using 3.10 or 3.11 instead.
> 
> It also seems like you are installing from main, not from a release. That's fine if you're developing Black, but it means that bugs you encounter may not be valid.

How can I install it using 3.10 or 3.11?
No matter how many times I reinstall, it comes out the same.

**Comment by hg0428** [comment]
> python -m black

That worked! All working now!
