### ISSUE TITLE
Docker latest_release is pointing to an alpha version

### ISSUE THREAD

**Issue by babyhuey** [psf/black#3453]
The latest docker release on docker hub is pointing to an alpha version. I would have expected `latest_release` to be the latest release, and not the very latest on git. 

Is there a way to fix this to go back to 22.12.0?

**Comment by matthewarmand** [comment]
Yep seems busted, according to the [docs for the official Docker image](https://black.readthedocs.io/en/stable/usage_and_configuration/black_docker_image.html#black-docker-image) the `latest_release` tag should be:

>tag created when a new version of Black is released. Recommended for users who want to use released versions of Black. It maps to [the latest release](https://github.com/psf/black/releases/latest) of Black.

The latest release of black linked above is `22.12.0` at time of writing, and the `latest_release` Docker image gives:

```
$ docker pull pyfound/black:latest_release && docker run -it pyfound/black:latest_release black --version
black, 23.1a1 (compiled: no)
Python (CPython) 3.11.1   
```

**Comment by matthewarmand** [comment]
I'm not an expert on Github Workflows, so I could very easily be wrong here, but it seems to me like [the trigger line for this docker publish](https://github.com/psf/black/blob/cd9fef8bab3a39dfba494f1917e4158faba439f9/.github/workflows/docker.yml#L47) might be the problem.
```
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
```

This will run on every published release, regardless of `latest` vs `pre_release` status, no? Does it also need to include something indicating `pre_release == 'false'` or something like that? Just going off the [release API documentation](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release)

**Comment by matthewarmand** [comment]
According to [this support article](https://github.com/orgs/community/discussions/26281#discussioncomment-3251177), that line may need to change to something like:

```
        if: ${{ github.event_name == 'release' && github.event.action == 'published' && !github.event.release.prerelease }}
```

But then later on in the thread someone mentions a workflow they have that does not run on preleases, and gives the exact line that currently exists in Black's workflow. So maybe this was an accidental manual push? Or the behavior has changed potentially

**Comment by matthewarmand** [comment]
Scratch the "manual push", this was clearly triggered by CI: https://github.com/psf/black/actions/runs/3725518068/jobs/6318369959#step:8:176. So seems to me the `latest_release` trigger in the docker workflow needs to change.

**Comment by JelleZijlstra** [comment]
@cooperlees do you know how to yank the docker release for 23.1a1? Or at least mark it as not the latest release.

**Comment by matthewarmand** [comment]
(I'm not who you asked so sorry for the noise but since I'm here anyway) The easiest way is probably for someone on the project with Dockerhub access to re-push the `22.12.0` image to the `latest_release` tag.

**Comment by cooperlees** [comment]
Reran the Actions CI: https://github.com/psf/black/actions/runs/3658832710/jobs/6334595544

Unfortunately people will have to manually use 23.1a1 to test alpha, but not the worst case. I will try find time to cleanup the action for this new alpha workflow.

**Comment by matthewarmand** [comment]
FYI @cooperlees if you wanted to add something to support the Alpha image workflow, given the behavior we've seen in this issue it might be as easy as adding another job to the docker workflow:

```yml
     - name: Build and push latest_alpha tag
        if:
          ${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pyfound/black:latest_alpha
```

Could call it `latest_alpha`, `latest_prerelease`, whatever. Then a docs update too, etc

**Comment by cooperlees** [comment]
> FYI @cooperlees if you wanted to add something to support the Alpha image workflow, given the behavior we've seen in this issue it might be as easy as adding another job to the docker workflow:
> 
> ```yaml
>      - name: Build and push latest_alpha tag
>         if:
>           ${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease }}
>         uses: docker/build-push-action@v3
>         with:
>           context: .
>           platforms: linux/amd64,linux/arm64
>           push: true
>           tags: pyfound/black:latest_alpha
> ```
> 
> Could call it `latest_alpha`, `latest_prerelease`, whatever. Then a docs update too, etc

Thanks for the good ideas. Will take into consideration and probably implement! PR welcome. More tags won't hurt.

**Comment by matthewarmand** [comment]
> PR welcome. More tags won't hurt.

Have a gander: #3465
