### ISSUE TITLE
Extra newlines added before function with fmt skip on decorator

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3454]
I've just tested this out with a medium-sized codebase. All as expected apart from this one issue with a comment at the end of a function getting 2 newlines added above it. Removing `@decorator1` stops the comment getting moved, as does removing `# fmt:skip`.

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/3770312/208406615-62a360b0-d41e-4e00-b95c-fc3baa3eb89e.png">

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADZAIZdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyoIEqib4HPPAOaGeijv-QM5F2CIWMxNomuS8WtfuVtc-CBav7wmp196mwOSJGXUmaRTdIwYr1wf881xD3biQ1s52KZSzb20ApVmRJ9HPRaEOhoVMkb9jDbRHrld5-g2LTBdcrPwjnT90_-ZGPvMAAAAAsri7GeyV3k8AAaIB2gEAAEJ-yuKxxGf7AgAAAAAEWVo=

_Originally posted by @jgillard in https://github.com/psf/black/issues/3407#issuecomment-1357440439_

**Comment by JelleZijlstra** [comment]
I tested this out and it happens only if both of the decorators on `bar` are present and the second one has `# fmt: skip`.

Copy-pastable sample:
```python
def foo():
    pass
    # Comment on next below

@decorator1
@decorator2  # fmt: skip
def bar():
    pass
```

**Comment by yilei** [comment]
This has the same underlying issue as https://github.com/psf/black/issues/3438, I'll take a look this week.
