### ISSUE TITLE
Marker to bypass expected parsing problems

### ISSUE THREAD

**Issue by theelderbeever** [psf/black#3456]
**Is your feature request related to a problem? Please describe.**

I am working in a Databricks environment and developing workflows there. Unfortunately, it awkwardly requires external dependencies to be installed in the running file in order to make them available. Sample shown below. The issue here is that in development when trying to use `black` to format the file `black` will fail with `Cannot parse: 4:0: %pip install my_lib`. This means the whole file can't be formatted.

```python
# Databricks notebook source

%pip install my_lib

# COMMAND ----------

import my_lib
```

**Describe the solution you'd like**

Some way of marking a line that you know to be invalid so that `black` won't fail to parse it. Something like `# fmt: skip` but maybe `# fmt: as_string` so that it just treats the line as a string.

**Describe alternatives you've considered**

An annoying workaround is commenting out the line, formatting the document, then uncommenting the line. Obviously this doesn't work in CI though.

**Comment by JelleZijlstra** [comment]
Are you looking for the `--skip-source-first-line` option?

**Comment by theelderbeever** [comment]
To some extent. However, in this case it won't be the first line and could be multiple lines. The first line in the example above is required to be `# Databricks notebook source` comment.

**Comment by MeGaGiGaGon** [comment]
I'm not familiar with Databricks, but `%pip` looks like a custom magic to me. If the files are being formatted as jupyter files, there is the [`--python-cell-magics`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#python-cell-magics) command line flag that you could add `%pip` to.

**Comment by JelleZijlstra** [comment]
I feel there probably isn't room for a change to Black here. This could be handled with a small wrapper tool that preprocesses the file, passes it to Black, and reprocesses it.
