### ISSUE TITLE
Black doesn't fit short lists on a single line.

### ISSUE THREAD

**Issue by MSK61** [psf/black#3464]
**Black v23.1a1**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACFAE9dAD2IimZxl1N_WmyLkeRBtS4hSHdDpqTsX2ywCbdFkTEnjLvJFpU-l8W6EqJIu_r05WGcfpuU3lxlEUrZ5CUtMwVhN8UfPc_DGl1b8bCkO2AAAFftdFdYdywlAAFrhgEAAAATCXwnscRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
x = [
    1,
    2,
    3,
]
```

## Output

```python
x = [
    1,
    2,
    3,
]

```

## Expected
x = [1, 2, 3]

## Description
In the above input code, black didn't pack the list into a single line although it would fit. Just removing the comma after the last element(3) will allow black to pack the list into a single line. Since in other circumstances(with very long lists) black feels free to wrap the list across multiple lines and inserts a comma after the last element, it should feel just as free to remove a comma after the last element if this would make the list fit on a single line. I think the only case where removing the comma isn't allowed is with single-element tuples.

**Comment by ichard26** [comment]
Hi. This is not a bug, that trailing comma is considered a "magic trailing comma" which prevents Black from collapsing that list literal. [There's more in the documentation about this feature](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma).

**Comment by MSK61** [comment]
Thanks for pointing me to the option in the documentation for restoring the classic behavior; I think I'll stick to using this option.
The rational for my request here was a use case where it was black which initially inserted the comma after the last element during formatting a long list(say with 20 items). Then at a later time I removed many elements so that the list might end up with just a few elements. Since the last element still had the trailing comma, black would refrain from fitting it once again into a single line.
Alas... That option suffices for the moment. Thanks again.
