### ISSUE TITLE
Cannot find full list of options in the documentation

### ISSUE THREAD

**Issue by nicoddemus** [psf/black#3491]
I am porting a new project to black and wanted to consult on the options available, however I cannot find the full list of options in the documentation.

In [Usage and Configuration](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#next-steps), it states:

> You’ve probably noted that not all of the options you can pass to Black have been covered. Don’t worry, the rest will be covered in a later section.

However I cannot find a section describing all options in later sections or the rest of the documentation. 

I remember a page describing all options in a previous version of the documentation, so it might have been removed by accident, but I might be remembering wrong.

**Comment by felix-hilden** [comment]
You can find it here: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options

But you're right, the wording is confusing and should be improved 👍 thanks!

**Comment by nicoddemus** [comment]
Ahh thank you! It was "hidden" by default and I did not notice.

I will open a PR improving the wording of that section then.
