### ISSUE TITLE
Please make emojis optional

### ISSUE THREAD

**Issue by fredrgrs** [psf/black#3501]
It seems that black indiscriminently prints emojis.  Could you PLEASE give us an option to disable unicode output, just like we can disable color output?  Not everyone is able to or chooses to use unicode-capable terminals, and these multi-byte characters will screw up many terminals, as they can be interpreted as terminal control codes or expected to render as single characters per byte.

**Comment by fredrgrs** [comment]
Thanks so much for jumping on this!

**Comment by Jackenmen** [comment]
This has been repeatedly rejected, do you have any reason for wanting this which hasn't already been mentioned in these issues?

See:
#223
#1031
#1255
#1270
#3359

**Comment by fredrgrs** [comment]
Wow, it's obvious from these other issues that this is a common complaint and that you're really willing to die on this hill.  I expect this to be closed as the others have.  It's a brave new world, I guess, and we dinosaurs can get stuffed.

**Comment by JelleZijlstra** [comment]
I am rejecting this feature request since there's nothing different from the last few times it has come up.

**Comment by cladmi** [comment]
A reason for asking this, the normal black output when pasted to `Atlassian/Stash` breaks on the database https://jira.atlassian.com/browse/BSERV-8490

Yeah really annoying for anybody pasting "proof" of output. Fixing Atlassian tools is a lifelong goal to reach anything.

**Comment by swills1** [comment]
Some of us chain checks together. I have a Bash script that runs on Git's `pre-commit` hook. It runs black, isort, mypy, and flake8. The emojis make more info to trudge through and makes my output longer / inconsistent. It also hurts logging. I am getting around this currently by redirecting the output;

```
black --check $directory_to_check #> /dev/null 2>&1
exit_code=$?

if [ $exit_code -eq 0 ]; then
    echo "Pass: black passed"
else
    echo "Fail: black failed"
fi
```
If I see it failed, I can run black without the redirect and get the error info.
