### ISSUE TITLE
Black fails to format file containing fmt: on/off specifiers

### ISSUE THREAD

**Issue by sciyoshi** [psf/black#3524]
**Describe the bug**

Black fails to parse valid code within a # fmt: off block.

**To Reproduce**

[Minimal test case link here:](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC1AHBdAD2IimZxl1N_WlbvK5V_5PM4Nceap1_O8bwBvpkcNAqQ_z0HNLADdstn6zqgLmt8AtcmT1ciXc4vW7-gYhESumiSF3NmlsptV4LLupnAqDLncmQFhikoJr3j79rYDUn_LaL49J7SgNnssIUcnmBa6_8AK-STN_RqcNEAAYwBtgEAAL9SnK6xxGf7AgAAAAAEWVo=):

```python
def testing():
	print("world")
	# fmt: off
	print("hello")
	# fmt: on
```

The resulting error is:

> [cannot format file.py: INTERNAL ERROR: ...](error: cannot format test.py: Cannot parse: 4:0:        print("hello"))

**Expected behavior**

This should be formatted correctly.

**Environment**

- Black's version: happens on latest main
- OS and Python version: Linux/Python 3.11

**Comment by sciyoshi** [comment]
This may be a duplicate of https://github.com/psf/black/issues/3505

**Comment by JelleZijlstra** [comment]
Yes, looks like the same issue.
