### ISSUE TITLE
Threading/Subprocess Permission denied pickle

### ISSUE THREAD

**Issue by gentlegiantJGC** [psf/black#3535]
**Describe the bug**

I have an odd use case for Black converting Qt Designer UI files to python code and improving the output.

I have found that doing each file in a new thread and calling black in a subprocess speeds up the process a lot.

Occasionally however Black fails to reformat one or more of the files.

`error: cannot format D:\Data\GitHub\Amulet-Editor\src\amulet_editor\plugins\amulet_team_home_page\home\home\_home.py: [Errno 13] Permission denied: 'C:\\Users\\james_000\\AppData\\Local\\black\\black\\Cache\\23.1a1\\cache.-.88.1.0.0.0.1.0.0.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.pickle'`

**To Reproduce**

```py
import sys
import glob
from concurrent.futures import ThreadPoolExecutor

def _black(path: str):
    subprocess.run([sys.executable, "-m", "black", path])

def main():
    with ThreadPoolExecutor() as executor:
        for path in glob.glob("**/*.py", recursive=True):
            executor.submit(_black, path)


if __name__ == "__main__":
    main()
```

**Environment**

- Black's version: 23.1a1 and 22.12.0
- OS and Python version: Windows Python 3.11.1

**Comment by cooperlees** [comment]
How much slower is passing all the files at once to one instance of black? black has its own internal parallelism that tries to use all CPU cores via fork new instances of itself, so performance should be similar. If you try run that way, does the described  problem also occur?

That aside, I would still expect we save this state to be per process safe, so we should workout what is going on here and fix any bug we find …

**Comment by gentlegiantJGC** [comment]
It seems about as fast. I have switched to that solution.

**Comment by hauntsaninja** [comment]
Great, closing since Black's multiprocessing is the way to go here.
