### ISSUE TITLE
Does not install on alpine

### ISSUE THREAD

**Issue by builder555** [psf/black#3544]
**Describe the bug**

Trying to install black in a Docker container (alpine base image) causes an error.

**To Reproduce**

Create Dockerfile:

```Dockerfile
FROM alpine:latest
WORKDIR /build
RUN apk update && apk add --no-cache python3 py3-pip
RUN python3 -m pip install black
```
Try to build it:
`docker build .`

The resulting error is:

```console
#7 1.868 Installing collected packages: mypy-extensions, tomli, platformdirs, pathspec, packaging, click, black
#7 1.931   Attempting uninstall: packaging
#7 1.934     Found existing installation: packaging 21.3
#7 1.936 ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Expected behavior**

Container is built

**Environment**

- Black's version: main
- OS and Python version: Alpine / Python 3.10

**Comment by ichard26** [comment]
Unfortunately since release 23.1.0, Black unconditionally depends on `packaging>=22.0`. Your best options are to either downgrade Black or set up a virtual environment to install it in.
