### ISSUE TITLE
Add unexpected space before colons in slice when compute start parameter, but omitting other parameters

### ISSUE THREAD

**Issue by garf365** [psf/black#3554]
**Describe the bug**

Add unexpected space before colons in slice when compute start parameter, but omitting other parameters : see https://peps.python.org/pep-0008/#pet-peeves and specially this sentence:

> However, in a slice the colon acts like a binary operator, and should have equal amounts on either side (treating it as the operator with the lowest priority). In an extended slice, both colons must have the same amount of spacing applied. Exception: when a slice parameter is omitted, the space is omitted:

Also, `flake8` reports this error :

```
file.py:5: [E203] whitespace before ':'
file.py:9: [E203] whitespace before ':'
file.py:14: [E203] whitespace before ':'
```

**To Reproduce**

For example, take this code:

```python
test = tokens[i+1:]
def _test(tokens):
    test = tokens[i+1:]
class MyClass:
    def _define_fcfs_constraint(self, tokens):
        test = tokens[i+1:]
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

Wrong output:

```python
test = tokens[i + 1 :] # Space before colons


def _test(tokens):
    test = tokens[i + 1 :] # Space before colons


class MyClass:
    def _define_fcfs_constraint(self, tokens):
        test = tokens[i + 1 :] # Space before colons
```

**Expected behavior**

Accord PEP8 and flake8, output should be:

```python
test = tokens[i + 1:] # Space before colons omitted


def _test(tokens):
    test = tokens[i + 1:] # Space before colons omitted


class MyClass:
    def _define_fcfs_constraint(self, tokens):
        test = tokens[i + 1 :] # Space before colons omitted
```

**Environment**

- Black's version: 23.1.0 [main]
- OS and Python version: [Linux/Python 3.9.16]

**Comment by JelleZijlstra** [comment]
https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
