### ISSUE TITLE
Support Quarto-style comment blocks

### ISSUE THREAD

**Issue by tomshafer** [psf/black#3557]
**Describe the style change**

Presently black inserts a space between the "#" and "|" in [Quarto][] metadata comments like `#| label: cell1`.

**Examples in the current _Black_ style**

Space is inserted between the hash and the pipe:
```python
# | label: cell-no1
# | echo: false
```
**Desired style**

No space between the hash and the pipe, which breaks document metadata parsing:
```python
#| label: cell-no1
#| echo: false
```

**Additional context**

Quarto is the new(ish) replacement for RMarkdown and uses these kinds of comments for metadata in, e.g., Jupyter cells and so black breaks document rendering. It would be nice to keep `#|` together in the same way as a couple of other comment pairs are preserved.

[Quarto]: https://github.com/quarto-dev/quarto-cli

**Comment by ichard26** [comment]
Seems reasonable. If you'd like to submit a PR adding `|` to this string that would be appreciated!
https://github.com/psf/black/blob/9c8464ca7ddd48d1c19112d895ae12d783f01563/src/black/comments.py#L32

**Comment by JelleZijlstra** [comment]
I'm actually hesitant to add more exceptions to that list. There's a never-ending list of tools that treat some particular comment specially. Perhaps we should bite the bullet and make this configurable, or tell the tools that they need to change.

**Comment by tomshafer** [comment]
Thanks for the consideration. I've opened a PR in case it's OK to merge; would be a nice quality of life improvement! Cheers.

**Comment by JelleZijlstra** [comment]
Closing in favor of #3668.
