### ISSUE TITLE
black github workflow showing errors when nothing to black

### ISSUE THREAD

**Issue by shahzebsiddiqui** [psf/black#3562]
@ambv 

black has decided to go rogue and started failing the black checks on github workflow see https://github.com/buildtesters/buildtest/actions/runs/4138692064/jobs/7155399872 it was working all of sudden now its failing but there is nothing to black from the code-base. I have the workflow file https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/black.yml and it is using the `@stable` version

Just to prove it i am going to run `black` on my code-base and it got nothing to report. I think the CI check is reporting false positive. 

```
(buildtest)  ~/Documents/github/buildtest/ [buildtest_inspect_theme] black --version        
black, 22.12.0 (compiled: no)
Python (CPython) 3.7.3
(buildtest)  ~/Documents/github/buildtest/ [buildtest_inspect_theme] black --check buildtest tests
All done! ✨ 🍰 ✨
108 files would be left unchanged.

```

**Comment by ambv** [comment]
1. Please don't tag people personally.
2. Please check which Black version is stable (hint: it's not 22.12.0 anymore) before reporting issues.
3. Please read this about style changes between years: https://black.readthedocs.io/en/stable/faq.html#how-stable-is-black-s-style

**Comment by JelleZijlstra** [comment]
It's because we made a new release. You should update to 23.1.0 locally or pin the version to 22.12.0 in your action: https://black.readthedocs.io/en/stable/integrations/github_actions.html

**Comment by shahzebsiddiqui** [comment]
ok so right now i am still using the stable release so it should pick up the right black version? the only thing that i haven't updated locally is my local black dependency https://github.com/buildtesters/buildtest/blob/devel/requirements.txt#L11 and version in pre-commit https://github.com/buildtesters/buildtest/blob/devel/.pre-commit-config.yaml

**Comment by shahzebsiddiqui** [comment]
okay ill try that out. Thanks @ambv
