### ISSUE TITLE
Outdated documentation for isort compatibility

### ISSUE THREAD

**Issue by mitchnegus** [psf/black#3565]
**Is this related to a problem? Please describe.**

I believe that the documentation for compatibility with isort may be outdated. The [Why those options above?](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#why-those-options-above) section states:

>_Black_ wraps imports that surpass `line-length` by moving identifiers into their own indented line. If that still doesn’t fit the bill, it will put all of them in separate lines and put a trailing comma.

In my experience (and supported by this [old conversation](https://github.com/PyCQA/isort/issues/694#issuecomment-473063700)), its seems that _Black_ no longer makes a first attempt to move identifiers to their own indented line, and it just defaults to newlines for each (with trailing commas). 

**Describe the solution you'd like**

Assuming I'm not misunderstanding something, the documentation should probably be updated to reflect this chanage. I think the following wording might suffice:

> _Black_ wraps imports that surpass `line-length` by moving identifiers onto separate lines and by adding a trailing comma after each.

I'm happy to submit the MR with that change if this checks out. (PS: thanks for an awesome tool!)

**Comment by ichard26** [comment]
Huh, I didn't know this until now. A MR would be welcomed! Thanks for reporting!
