### ISSUE TITLE
Black exists

### ISSUE THREAD

**Issue by ricardo-reis-1970** [psf/black#3570]
Dear Łukasz Langa,

This is for you, since you were the one with the brilliant idea to start this abnormal cell growth that is `black`. For casual readers and passers-by, please consider that I am 50% black, as my mother is African, so this is no racist talk.

Ford once said about a car he was selling "And you can have it in any colour you like, as long as you like black." I can see why the name, here.

Big organisations all have their own code style. We all heard that MIcrsoft's new dev onboarding strategy includes something like 2 months of getting used to naming conventions. It's their problem that they feel compelled to prefix variable names with the type (fugly stuff like `int_coord_x`) and I'm only bringing that in to highlight how incredibly stupid things can get when one decides to go around and impose one's own style on everybody else. And I really mean _against_ everybody else.

I just started in a new company and I'm having a great time! Except for your little piece of work here, that someone decided (without asking) to adopt and is now ruining everything for pretty much everybody.

I find it almost poetic that you answer to issues here in a pretense of "nothing to do with me", like "The documentation has lots of arguments...". I know it's an ugly ugly kid, but its' _your_ kid, so own it. And don't hide behind tens of collaborators either, because you started this nightmare. Issue [118](https://github.com/psf/black/issues/118), for instance:
> Please discuss the approved code style at work, Black's documentation is using several arguments as to why double quotes are preferred.
> 
> If you have strong reasons to prefer single quotes, list them here. "Approved code style" is not a reason alone.

Amazing! An organisation's own approved code style is not a reason, but _your_ piece of bad taste is!

A style editor should, or rather, _must_ be configurable, otherwise it's just Naziware, and that's what your pet here is. Unapologeticall also means rude, so don't expect any less from me. Here it goes...

In 1989 (how old were you, _boy_?) I was unhappy with Sidekick so I decided to make my own text editor. We were still on MS-DOS (sophomore year), so no vi yet. And guess what? My piece of crap editor did this amazing high tech thing whereby a line over 80 characters (the standard text mode screen width) got broken into the following line, and bu natural space! Unbelievable, right? But at least, we could assess a piece of code length by its line count.

Now enter your generation, with your Twitterised and SMSised little brains and God forbid you could possibly... No! You just go in and break lines at 78 chars. The ultimate outrage is that even when one asks for longer lines, they are still split way shorter, because one Łukasz said so. Unapologetically! And the nerve on you to even mention an [appeal to authority](https://en.wikipedia.org/wiki/Argument_from_authority)! As if `black` is not the biggest such appeal in the room!

I went to the trouble of asking around my colleagues and they all agreed that legiblity gets severely hurt by having all function parameters on separate lines, and the same goes for lists. One of them complained that his mouse was at risk for so much scrolling. Then again, what do these bunch of puny PhDs and Data Scientists know, right?

The funny thing is that I'm almost blind from birth. I need zoomed screens and, obviously, that gets me even less lines per screen, now mostly filled with 10 characters each. If you think you're helping legibility, well...

But the best part is the double-quote fuckery. Here's a snippet for you, from the same language that now is at severe risk because you're the resident whateverthefuck:
```python
$ python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "a"
>>> s
'a'
>>> 
```

Amazing! Even the CLI prefers single quotes. I did not see your... sorry, `black` documentation's rationale for double quotes, but I'm sure you'll be thinking of further polluting our Python world by imposing the double quote at CLI level. I mean, just go ahead and adopt dollar signs for variables and allow for HTML tags inline and... call it PHP once and for all!

There is one person in my organisation that thought that `black` was a good idea. I'm going to make noise until we either get done with effing formatters or go for something less post-Weimar Republic, like `autopep8`, or `flake8` or something with more than 2 parameters that _actually_ takes said parameters into consideration.

**Comment by amyreese** [comment]
At the risk of actually being helpful, two of your three complaints about black style are in the short list of configuration options that black actually offers. `black --help` will gladly inform you of both the `--line-length` and `--skip-string-normalization` parameters.

**Comment by fried** [comment]
Sir this is a Wendy's

**Comment by ichard26** [comment]
OK, this is going to get out of hand for no use. I'm locking this.

Also, I'm not really sure how this is supposed to be actionable in any way other than deleting the repository and the project in general. Almost everything brought up has a response in the issue tracker or the documentation as mentioned above. Black is by design unconfigurable. If this is meant to be a rant, I'm sorry that you feel that way and I hope you feel better, but we aren't changing the core ethos of this project.

We don't control anyone's workplace. If a decision is being applied by a single person unilaterally without approval, that's not our problem to deal with.

**Comment by ichard26** [comment]
Also thank you @amyreese, I appreciate the helpful comment!
