### ISSUE TITLE
`black .` output does not match with `black CertainLocation` output

### ISSUE THREAD

**Issue by lsjhome** [psf/black#3573]
**Describe the bug**

`black .` output does not match with `black certain_folder/file` output

**To Reproduce**

This is file reformatted when you run `black .`

```
reformatted foldername/etl.py

All done! ✨ 🍰 ✨
1 file reformatted, 40 files left unchanged.
```

```
class ETL:
    def __init__(
        self,
        data=None,
        categorical_variables=[],
        continuous_variables=[],
        bool_variables=[],
        label="",
        train_limit=0,
        test_size=0.2,
    ):
        """ """

        self.data = data
        self.categorical_vars = categorical_variables
        self.numeric_vars = continuous_variables
        self.bool_vars = bool_variables
        self.label = label
        self.train_limit = train_limit
        self.test_size = test_size
        self.indep_vars = self.bool_vars + self.numeric_vars + self.categorical_vars

        pass

    # TODO: revise for pandas dataframe input
    def split_data(self):
        # Split into training and test datasets
        feature_cols = [column for column in self.data.columns if column in self.indep_vars]
```

look at the last line `feature_cols` part

when you specify the file, for instance `black foldername/etl.py`

it reformats again!

```
reformatted foldername/etl.py

All done! ✨ 🍰 ✨
1 file reformatted.
```

```
class ETL:
    def __init__(
        self,
        data=None,
        categorical_variables=[],
        continuous_variables=[],
        bool_variables=[],
        label="",
        train_limit=0,
        test_size=0.2,
    ):
        """ """

        self.data = data
        self.categorical_vars = categorical_variables
        self.numeric_vars = continuous_variables
        self.bool_vars = bool_variables
        self.label = label
        self.train_limit = train_limit
        self.test_size = test_size
        self.indep_vars = self.bool_vars + self.numeric_vars + self.categorical_vars

        pass

    # TODO: revise for pandas dataframe input
    def split_data(self):
        # Split into training and test datasets
        feature_cols = [
            column for column in self.data.columns if column in self.indep_vars
        ]
        
```
You can see the last line `feature_cols` is split into two. 
So `black .` does not follow the same principle when you specify the file

this is my `pyproject.toml`

```
[tool.black]
line-length = 100
preview = true
target-version = ['py38']
```

**Environment**

- Black's version: black, 22.12.0 (compiled: no)
- OS and Python version: MacOS Monterey 12.5 (Rosetta terminal)/Python (CPython) 3.8.13

**Additional context**
- I used rosetta terminal but I think I saw this pattern in native terminal

**Comment by JelleZijlstra** [comment]
What do you get with `black -v`? It may also be worth upgrading to 23.1.0 since we made `-v` output more informative.

**Comment by lsjhome** [comment]
> What do you get with `black -v`? It may also be worth upgrading to 23.1.0 since we made `-v` output more informative.

I updated the black version to `23.1.0` and still have the same issue.

**Comment by lsjhome** [comment]
> What do you get with `black -v`? It may also be worth upgrading to 23.1.0 since we made `-v` output more informative.

Sorry, I understood what `-v` means and I found out that the not the same config were applied. Turns out there was a parent folder that included `pyproject.toml` and it was acting like a project root. I'm sorry for the false report and thank you so much for the awesome job you're doing. I really appreciate it.
