### ISSUE TITLE
extend-exclude with an array is a footgun

### ISSUE THREAD

**Issue by konstin** [psf/black#3574]
I accidentally had the following configuration in a project:

```
[tool.black]
extend-exclude = [
    "backendapp/migrations"
]
```

If i then run `black . -vvv`, it tells me e.g.

```
manage.py ignored: matches the --extend-exclude regular expression
```

which is really confusing because `backendapp/migrations` is neither a regex nor should it match `manage.py`.

The solution is `extend-exclude = "backendapp/migrations"`, which i only realized when looking into other projects' pyproject.toml files.

**Describe the solution you'd like**

I would be nice if black would fail or at least warn when the configuration uses the wrong datatype. Additionally, there aren't any examples of `extend-exclude` in pyproject.toml in the docs, the only usage in the repo is black's own pyproject.toml

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by ichard26** [comment]
Let's do it! (unless we want to support globs - #3559 but that seems unlikely).

**Comment by Avasam** [comment]
Oh wow yeah, I just shot myself in the foot. Thanks.
```toml
extend-exclude = [
  "Externals/", # Don't format vendored code
]
```

**Comment by asarkar** [comment]
@Avasam According to [this comment](https://github.com/psf/black/issues/3754#issuecomment-1610797901), `extend-exclude` is a str, not a list. I'm curious how you got it working as a list.

**Comment by Avasam** [comment]
> @Avasam According to [this comment](https://github.com/psf/black/issues/3754#issuecomment-1610797901), `extend-exclude` is a str, not a list. I'm curious how you got it working as a list.

I didn't, the point of this issue is that arrays don't work. My example fails.
