### ISSUE TITLE
how to know which black version executed in Github action

### ISSUE THREAD

**Issue by piramiday** [psf/black#3575]
**Is this related to a problem? Please describe.**
I am running the latest Github action and the latest PyPi `black` version.
I realize that the Github action can specify which `black` version to use, but I don't want to maintain that, too.
I would like to add to the logs which black version is responsible to checking my Python scripts.
How can I accomplish that?

**Describe the solution you'd like**

I tried executing something similar to `black --version` in a subsequent step but if was obviously failing due to `black` not being in the PATH.

**Describe alternatives you've considered**

I might as well `pip install black` in my action as opposed to using the official Github action.

**Comment by ichard26** [comment]
Seems mostly reasonable although this is probably going to be less useful soon-ish as we plan on changing the default so the action version == black version installed. See https://github.com/psf/black/pull/3543.

**Comment by ichard26** [comment]
That PR only changes the default version of Black used in the GitHub Action to match the action version. There's still no programmable way of detecting the version of Black used, but it can be inferred in most cases now.
