### ISSUE TITLE
Allow semicolons in Jupyter Notebooks? (they have a syntactical meaning)

### ISSUE THREAD

**Issue by nickeubank** [psf/black#3577]
**Describe the style change**

Currently when run against Jupyter Notebooks, black removes semi-colons. But in Jupyter notebooks, a semi-colon has meaning—it tells the notebook to not print the output from that line (as it normally would by default for the last line in a cell).  When writing notebooks for instruction, this can be annoying.

**Additional context**

[An example of where this comes up](https://www.unifyingdatascience.org/html/fixed_effects.html)—note after running black on the notebook, I have to go back and re-add in `;` to prevent several hundred line outputs.

**Comment by JelleZijlstra** [comment]
We already have logic for this (e.g. https://github.com/psf/black/blob/16b98abca94343770aad561ea659380c97d473b4/src/black/handle_ipynb_magics.py#L107). Could you help clarify why this logic is not kicking in? How are you invoking Black?

**Comment by nickeubank** [comment]
oh interesting. VS Code's "Format notebook". Wondering why the implementation there doesn't respect it!
