### ISSUE TITLE
Sort types in Unions

### ISSUE THREAD

**Issue by jakkdl** [psf/black#3607]
**Is your feature request related to a problem? Please describe.**

Black will currently not reformat this:
```python
from typing import Union
a: int|float = ...
b: float|int = ...
c: Union[int, float] = ...
d: Union[float, int] = ...
```
which leads to some messy code when the type list gets long, but clearly the order of the types don't matter and might as well be sorted. I just had a git diff that was completely unnecessary, and it makes it harder to see if two somewhat complex type declarations are the same.

**Describe the solution you'd like**
I'm not 100% sure on whether Black is the correct tool to implement this, especially as there's a lot of neighboring issues (`set(2, 1)` is equivalent to `set(1, 2)`, `a: int|int` should be `a: int`) that feels like it's moving into a code-cleanup direction rather than a pure style/formatting thing.

**Comment by JelleZijlstra** [comment]
This is unsafe as it changes the AST and can easily change observable behavior (both at runtime and for type checkers) in edge cases. I think it's outside the scope of Black, which aims to be a completely safe formatter.
