### ISSUE TITLE
ruff check file.py output is unreadable

### ISSUE THREAD

**Issue by copperfield42** [psf/black#3611]
Hello, I just hear of this project so I installed to test it, following the usage indication on some file I got this

![image](https://user-images.githubusercontent.com/4504719/225796639-1e76bda0-9a30-49ec-bfe3-3754c7f495b9.png)

I installed it like `pip install ruff`
ruff version: 0.0.256
Python version 3.11.2
OS: Windows 10

**Comment by dawnofmidnight** [comment]
Hello. `ruff` is a project entirely unrelated to `black`, so this is the wrong repository. You can find its issue tracker [here](https://github.com/charliermarsh/ruff).

**Comment by copperfield42** [comment]
oh sorry, my mistake
