### ISSUE TITLE
extend-exclude does not work for files. 

### ISSUE THREAD

**Issue by asgerbolet** [psf/black#3617]
**Describe the bug**  

Running black with a `pyproject.toml`, where "extend-exclude" is set to ignore a specific file dose not work and the file is formatted when black is run.

**To Reproduce**  
Make the following Dockerfile: 
``` Docker 
FROM mcr.microsoft.com/vscode/devcontainers/base:0.203.5-bullseye

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install --no-cache-dir black==23.1.0 

WORKDIR /

RUN git init black-obs
WORKDIR /black-obs/
RUN git branch -m main

RUN mkdir file_exclude
RUN cat <<EOT > file_exclude/bug.py 
def hallo_world(): 
    print('Hallo World') 
if __name__=='__main__': 
    hallo_world() 
EOT

RUN mkdir folder_exclude
RUN cat <<EOT > folder_exclude/badly_fmt.py 
def hallo_world(): 
    print('Hallo World') 
if __name__=='__main__': 
    hallo_world() 
EOT

RUN mkdir folder_gitignore
RUN cat <<EOT > folder_gitignore/badly_fmt.py 
def hallo_world(): 
    print('Hallo World') 
if __name__=='__main__': 
    hallo_world() 
EOT

RUN echo folder_gitignore/ > .gitignore 

RUN cat <<EOT > pyproject.toml
[tool.black]
target-version = ["py310"]
extend-exclude = '''
/(
| folder_exclude
| .*bug.py
)/
'''
EOT

RUN black --config=pyproject.toml . 
```
and then run it in the terminal: 
``` sh
docker build - < Dockerfile --progress plain --no-cache --tag black_bug_report:23.1.0
```
this should then return:
```
#18 [15/16] RUN black --config=pyproject.toml .
#18 0.394 reformatted /black-obs/file_exclude/bug.py
#18 0.394 
#18 0.394 All done! ✨ 🍰 ✨
#18 0.394 1 file reformatted.
#18 DONE 0.4s
```
hench the file `bug.py` is not excluded  

**Expected behavior**  

The file/ or any file that fits the pattern would be exclude from black formatting
The RegEx pattern used for the example is: 
´´´
extend-exclude = '''
/(
| folder_exclude
| .*bug.py
)/
'''
´´´
So all files called `bug.py` should be excluded. 

**Environment**  

- Black's version: 23.1.0
- OS and Python version: Debian bullseye for exact version run: 
``` sh
docker build - < Dockerfile --progress plain --no-cache --tag black_bug_report:23.1.0 && \
docker run --rm -it --entrypoint bash black_bug_report:23.1.0
```
and then 
``` sh
python3 --version 
lsb_release -a
```
This should result in: 
``` sh
Python 3.9.2
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
**Additional context**
NA

**Comment by asarkar** [comment]
Can we get a word on when this might be fixed? Considering a common and public option is completely broken, shouldn’t it be considered important enough to be not left to stale for months?
Note that I’m not asking this to be fixed right away, but asking for a release target, if any, for a fix.

**Comment by hauntsaninja** [comment]
You have a trailing slash in your regular expression. `bug.py/` will not match `bug.py`
```
>>> import re
>>> extend_exclude = re.compile('(?x)/(\n| folder_exclude\n| .*bug.py\n)/\n', re.VERBOSE)
>>> extend_exclude.search("file_exclude/bug.py")
>>> extend_exclude.search("file_exclude/bug.py") is None
True
```

**Comment by asarkar** [comment]
I had tested the regex at regex101. If you’re seeing something different, it must be a copy-paste error. As for being nice to the volunteers, yes of course, but I don't believe I had been rude at any point.

**Comment by asgerbolet** [comment]
Thanks, for the clarification. And sorry for posting subpar regular expression.
