### ISSUE TITLE
Unusual variable name (Ø) causing issues when using other tools because it is not a basic ASCII character.

### ISSUE THREAD

**Issue by vishalnandagopal** [psf/black#3639]
An unusual but valid variable name (Ø) in [linegen.py](https://github.com/psf/black/blob/a552f7096a9f6e016c9bb1df1e0a77a17caeec1c/src/black/linegen.py#L471) .

When using `pipreqs`, a popular tool (5K+ ⭐) for generating `requirements.txt` files, it is causing issues because for some reason it is unable to parse the variable name.

Although the issue is not in black, and I have filed a [related bug report in the pipreqs repo](https://github.com/bndr/pipreqs/issues/363), using an unusual variable name invites unnecessary issues like these.

```sh
$ pip install pireqs
$ pipreqs .
```

The resulting error is:

```
ERROR: Failed on file: .\.venv\Lib\site-packages\black\linegen.py
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V\AppData\Local\Programs\Python\Python311\Lib\site-packages\pipreqs\pipreqs.py", line 131, in get_all_imports
    raise exc
  File "C:\Users\V\AppData\Local\Programs\Python\Python311\Lib\site-packages\pipreqs\pipreqs.py", line 117, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 412
    Ã˜: Set[str] = set()
     ^
SyntaxError: invalid character '˜' (U+02DC)
```

black, 22.10.0 (compiled: yes)
Python (CPython) 3.11.0
Windows 11

**Comment by JelleZijlstra** [comment]
This is not a bug in Black; it's a reminder to other tools to handle Unicode correctly.

**Comment by vishalnandagopal** [comment]
Yes, like I mentioned, it is not an issue in black and is a problem due to pipreqs using ASCII.

Can I add a PR that renames the Ø variable to phi? Would that be accepted even though the issue is not in black?

**Comment by vishalnandagopal** [comment]
Okay, thank you for responding so quickly!
