### ISSUE TITLE
Allow aligning assignments using multiple spaces before `=`

### ISSUE THREAD

**Issue by sven-frotscher** [psf/black#3654]
**Describe the style change**
When assigning multiple similar values with different-length variable names, aligning the `=` (assignment) operators using spaces should be allowed. In my opinion, this allows the reader to assess the differences in the literals (or function calls) more easily than when the `=` are scattered over different columns.

**Examples in the current _Black_ style**
```python
#!/usr/bin/env python3
"""
VT100 escape sequences for text foreground color
"""

black = "\033[30m"
red = "\033[31m"
green = "\033[32m"
yellow = "\033[33m"
blue = "\033[34m"
magenta = "\033[35m"
cyan = "\033[36m"
white = "\033[37m"
reset = "\033[0m"
```
This was produced by running Black on the small module shown below. The differences in the literals are hard(er) to spot in the example above because the assignment operators and literals start at different columns.

**Desired style**
```python
#!/usr/bin/env python3
"""
VT100 escape sequences for text foreground color
"""

black   = "\033[30m"
red     = "\033[31m"
green   = "\033[32m"
yellow  = "\033[33m"
blue    = "\033[34m"
magenta = "\033[35m"
cyan    = "\033[36m"
white   = "\033[37m"
reset   = "\033[0m"                     
```
Here, you can see the differences between the literals (different numbers between `[` and `m`) at a glance.

**Additional context**
The proposed style conflicts with [a PEP 8 pet peeve](https://pep8.org/#pet-peeves:~:text=More%20than%20one%20space%20around%20an%20assignment%20(or%20other)%20operator%20to%20align%20it%20with%20another.) and makes Flake8 throw [an error](https://www.flake8rules.com/rules/E221.html).
I found some more reasoning for, examples of and discussion around aligning operators [in this StackOverflow answer](https://stackoverflow.com/a/15302350).

Popular reasoning against aligning related operations: What do you do if you add an assignment to a variable with a longer name? In the above example, I might add
```python
underscore = "\033[4m"
```
and either leave the other assignments as they are or re-align them. The former approach leaves them misaligned, the latter touches unrelated source lines and adds noise to the diff.

I'll admit that aligning assignments is better done by hand and left untouched by Black than automatically done. To paraphrase PEP 20: *"In the face of ambiguity [concerning similar lines], refuse the temptation to guess."*

**Comment by st-pasha** [comment]
A related situation is to have vertically aligned values in a dictionary:
```python
colors = {
  "black":  "#000000",
  "red":    "#FF0000",
  "yellow": "#FFFF00",
  "white":  "#FFFFFF",
}
```

The actual formatting rule that can be implemented may be something like this:
- If there are 2+ consecutive assignment statements; and
- In at least 2/3 of those lines the column position of the `=` operator is the same; and
- In at least one of the lines where the `=` operators are aligned there is more than one space before the `=` operator --
- Then the entire group of the assignment operators is eligible for the "aligned =" formatting, where the `=` operator is placed as if the length of all identifier names was equal to longest identifier.

**Comment by yilei** [comment]
In addition to PEP 8 violation, this also violates one of _Black_'s goal to [_reduce git diffs_](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#code-style).

If the `=`s need to be kept aligned, and if you change one of the statements, it might cause _all_ statements to be realigned.

**Comment by st-pasha** [comment]
> If the =s need to be kept aligned, and if you change one of the statements, it might cause all statements to be realigned.

Indeed. However, in this situation the user explicitly opts-in into this behavior. An increased git diff is a cost that is born by the code author, and if the author deems that the benefit of having the assignment statements aligned outweighs the costs, then they probably know better.

**Comment by RitikShah** [comment]
Can't you do this?
```py
#!/usr/bin/env python3
"""
VT100 escape sequences for text foreground color
"""

# fmt: off
black   = "\033[30m"
red     = "\033[31m"
green   = "\033[32m"
yellow  = "\033[33m"
blue    = "\033[34m"
magenta = "\033[35m"
cyan    = "\033[36m"
white   = "\033[37m"
reset   = "\033[0m"               
# fmt: on
```

**Comment by JelleZijlstra** [comment]
We try to minimize changes in the stable style now (https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy). Given the concerns @yilei brought up, I am closing this requested style change. Black will continue to consistently format every assignment with a single space around the `=` sign.
