### ISSUE TITLE
Blank lines before class docstring are not removed

### ISSUE THREAD

**Issue by jonathanberthias** [psf/black#3659]
**Describe the style change**

The blank lines between a function's definition and its docstring currently get removed by Black. However, it does not do the same thing for classes.

**Current Black changes**

```python
def f():

    """The line above gets removed."""
    return 0
```
becomes
```python
def f():
    """The line above gets removed."""
    return 0
```
but
```python
class C:

    """The line above stays."""
```
is not modified by Black.

**Desired style**

I would have expected that code to get reformatted as:
```python
class C:
    """The line above stays."""
```

**Comment by huzaifakhan771** [comment]
This seems like the intended behavior. I tested it by adding more than one blank line after class declaration, and it changed it to one line.

For example:
```
class C:



    """The line above stays."""

```
becomes
```
class C:

    """The line above stays."""
```
However, it I don't have any blank line at all, it doesn't change it.

For example:
```
class C:
    """The line above stays."""
```
stays
```
class C:
    """The line above stays."""
```

**Comment by st-pasha** [comment]
I agree with the OP that Black should enforce a consistent style in this case. There is no reason for a blank line to exist between a class/function declaration and the subsequent docstring.

**Comment by JelleZijlstra** [comment]
Agree, let's remove these blank lines.
