### ISSUE TITLE
Whitespace around = in multi-line function call

### ISSUE THREAD

**Issue by st-pasha** [psf/black#3660]
**Describe the style change**

In a multi-line function-call expression, where each parameter is on its own line, it would be great to add spaces around the `=` signs.

**Examples in the current _Black_ style**

```python
some_function(
  param1="string value",
  param2=1 + 7 + 11,
  param3=[
    "one",
    "seven",
    "twelve",
  ],
  param4="another long value", 
  param5=some_other_function_call(*args),
)
```

**Desired style**

```python
some_function(
  param1 = "string value",
  param2 = 1 + 7 + 11,
  param3 = [
    "one",
    "seven",
    "twelve",
  ],
  param4 = "another long value", 
  param5 = some_other_function_call(*args),
)
```

**Additional context**

In the original python's style guide, all function calls were supposed to be in a single line. And if a function had too many parameters, they were all squeezed into as few lines as possible. In that situation, removing spaces surrounding the `=` sign was natural, as it allowed easier visual separation between parameters:
```python
some_function(param1="string value", param2=another_value, param3=["one", "two, "three"],
              param4="another long value", param5=some_other_function_call(*args))
```

Luckily, Black has abandoned this style: if a function has too many parameters to fit in a single line, then each parameter will be on its own line. But in this situation having no spaces around `=` signs no longer makes sense: the parameters are already visually well-separated.

In fact, having no spaces can often create an unpleasant situation where the RHS of a parameter is an expression with spaces, and thus the spaces are not distributed according to their precedence. For example, nobody would tolerate this kind of assignment statement: `x=1 + 7 + 11`, so why would we allow it in a function call expression?

**Comment by JelleZijlstra** [comment]
For better or worse, the standard Python convention is to not put spaces around keyword arguments. Changing that rule in Black would be enormously disruptive.

**Comment by st-pasha** [comment]
If being disruptive is the only objection, then perhaps this rule could be provided as a configuration option? It would be sad to let some decisions that were made over 20 years ago to stand in the way of progress...

**Comment by JelleZijlstra** [comment]
Black generally does not provide configuration options; we aim for a single style.
