### ISSUE TITLE
bug formatting await (a**b)

### ISSUE THREAD

**Issue by 15r10nk** [psf/black#3676]
**Describe the bug**

black converts `await (a**b)` into `await a ** b` (if run with --fast) 

**To Reproduce**

```python
async def name_5():
    await (name_1 ** name_4)
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

> cannot format file.py: INTERNAL ERROR: ...

**Expected behavior**

black should preserve the braces and be able to format the file

**Environment**

python -m black, 23.3.1.dev10+geb32729 (compiled: no)
Python (CPython) 3.11.3

**Additional context**

error log:
``` diff
--- src
+++ dst
@@ -14,34 +14,34 @@
             None,  # NoneType
         )  # /arguments
       body=
         Expr(
           value=
-            Await(
-              value=
-                BinOp(
-                  left=
+            BinOp(
+              left=
+                Await(
+                  value=
                     Name(
                       ctx=
                         Load(
                         )  # /Load
                       id=
                         'name_1',  # str
                     )  # /Name
-                  op=
-                    Pow(
-                    )  # /Pow
-                  right=
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'name_4',  # str
-                    )  # /Name
-                )  # /BinOp
-            )  # /Await
+                )  # /Await
+              op=
+                Pow(
+                )  # /Pow
+              right=
+                Name(
+                  ctx=
+                    Load(
+                    )  # /Load
+                  id=
+                    'name_4',  # str
+                )  # /Name
+            )  # /BinOp
         )  # /Expr
       decorator_list=
       name=
         'name_5',  # str
       returns=


```

For context:
I currently write a generator wich generates random python code. This is still work in progress, but finding bugs in black shows me that I am on the right track.
I will provide a script similar to `scripts/fuzz.py` as soon as it is ready.

**Comment by JelleZijlstra** [comment]
Thanks! I suppose we get the precedence wrong and incorrectly remove the parentheses. Let us know if you find additional crashes while fuzzing.

**Comment by 15r10nk** [comment]
I found two other issues while fuzzing, #3678 and #3677. I will stop searching for now because it seems that I find always the same issues.
