### ISSUE TITLE
problem parsing with statements 

### ISSUE THREAD

**Issue by 15r10nk** [psf/black#3678]
Some with statements can not be parsed by black.
They are unlikely to appear in real code, but they are valid python and can be parsed by cpython.

**Examples**

```python
with (name_2 for name_0 in name_4):
    pass
```

```python
with (a,*b):
    pass
```

None of these examples have a valid `__enter__` or `__exit__` and should fail at runtime.

black gives the following error:
```
error: cannot format example4.py: Cannot parse: 1:8: with a, *b:

Oh no! 💥 💔 💥
1 file failed to reformat.

```

**Expected behavior**

black should be able to parse and format this statements.

**Environment**

python -m black, 23.3.1.dev10+geb32729 (compiled: no)
Python (CPython) 3.11.3

**Comment by JelleZijlstra** [comment]
Presumably related to #2926, and fixable by changing `remove_with_parens()` in `linegen.py`.
