### ISSUE TITLE
What is the C error code?

### ISSUE THREAD

**Issue by otakutyrant** [psf/black#3687]
This documentation section [Line length](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length) shows a config example:

```
[flake8]
max-line-length = 88
...
select = C,E,F,W,B,B950
extend-ignore = E203, E501
```

I have checked flake8, pycodestyle and ruff documents, but I still cannot make sure what the selected `C` is.

**Comment by cooperlees** [comment]
https://pypi.org/project/flake8-comprehensions/

**Comment by otakutyrant** [comment]
@cooperlees Thank you.

**Comment by otakutyrant** [comment]
Why does the black document use `C` this code error? The README of `flake8-comrephensions` said:

> Second, if you define Flake8’s select setting, add the C4 prefix to it. Otherwise, the plugin should be active by default.

The correspond rule code of ruff is `C4` too.

**Comment by cooperlees** [comment]
It's probable doesn't need to be in our example config. I bet it was copy paste by ambv or I. Looks similar to the config at the first place black was ever used magically ;) ...
