### ISSUE TITLE
Black Formatter Adds Whitespace Before Colon in String Access, Triggering Flake8 Error (E203)

### ISSUE THREAD

**Issue by joe-r-healy** [psf/black#3693]
**Describe the bug**

When calling a function to get an index for string access. The black formatter adds whitespace after the function call. Which causes a lint error in Flake8.

**To Reproduce**

```python
str1 = "hello"
str2 = f"{str1} World!"
#Black inserts a space befor the ':' here. Then Flake8 see's that as an issue. E203 whitespace before ':'
print(str2[len(str1):])

#No whitespace is inserted here
print(str2[5:])
```

And run tox with this config:

```ini
commands = 
    format: black .
    lint:  flake8 .
```

The resulting error is:

> E203 whitespace before ':'

**Environment**

- Black's version: black-23.3.0
- OS and Python version: Osx/Python 3.9.16

**Comment by joe-r-healy** [comment]
cc. @TinMarkovic

**Comment by JelleZijlstra** [comment]
https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
