### ISSUE TITLE
Black produced different code on the second pass, moving a comment

### ISSUE THREAD

**Issue by DRMacIver** [psf/black#3706]
Running black 23.3.0 on the following code:

```
class S:
 if():last_shard.accumulated_answer_json_size_bytes=(#pylint: disable=invalid-name
[0])
```

Produces the following output:

```
class S:
    if ():
        last_shard.accumulated_answer_json_size_bytes = (
            [0]  # pylint: disable=invalid-name
        )
```

But if we run black on it again we get the following:

```
class S:
    if ():
        last_shard.accumulated_answer_json_size_bytes = [
            0
        ]  # pylint: disable=invalid-name
```

(Running black a third time makes no changes)

This should probably produce the final answer immediately when run on the initial code, but either way black presumably shouldn't reformat its own output.

Edit to add: Sorry, this is probably a dupe of #3701. When I was initially looking at it, I thought this seemed more distinct than it now looks like it does. There are some slight differences so it *might* not be, but more likely than not it's the same underlying issue.

**Comment by JelleZijlstra** [comment]
Agree this looks the same as #3701.
