### ISSUE TITLE
Shouldn't max-line-length be 80 when using bugbear?

### ISSUE THREAD

**Issue by Alveel** [psf/black#3716]
**Is this related to a problem? Please describe.**

The [documentation](https://black.readthedocs.io/en/latest/the_black_code_style/current_style.html#line-length) suggests using `flake8-bugbear` instead of just bumping `max-line-length` to 88, as bugbear already handles a line max 10% longer than `max-line-length`. However, the example _with_ bugbear below it still uses 88.

What this effectively means is that flake8 (with bugbear) won't complain about lines up to 96 characters long.

I think the example value should be 80:

```ini
[flake8]
max-line-length = 80
...
select = C,E,F,W,B,B950
extend-ignore = E203, E501
```

**Comment by cooperlees** [comment]
I think here our intention was just to "be safe" for people not running bugbear as well who copy paste. Reading is hard. At the end of the day we just want flake8 to not bother warning black enabled repositories about the line length, as, after all, you're using an autoformatter and you shouldn't ever hit the line lint warning ...

Happy to discuss further, but I think for people not reading and parsing that flake8-bugbear does this we might get some people who copy paste and wonder what is going on. I would be down to add this context to the docs tho, leaving the default if you think that helps.

**Comment by Alveel** [comment]
Perhaps the phrasing can be improved to be more explicit about this? It's currently very open and suggestive. Black is supposed to be opinionated and uncompromising, is it not? ;)

Suggested, more concise text:

> If you use Flake8, you have a few options:
>
> 1. Recommended is using [Bugbear][] and enabling its B950 check instead of using Flake8's E501, because it aligns with Black's 10% rule. Install Bugbear and use the following config:
>
>    ```toml
>    [flake8]
>    max-line-length = 80
>    ...
>    select = C,E,F,W,B,B950
>    extend-ignore = E203, E501
>    ```
>
> 2. For a minimally compatible config:
>
>    ```toml
>    max-line-length = 88
>    extend-ignore = E203
>    ```

[Bugbear]: https://github.com/PyCQA/flake8-bugbear

**Comment by cooperlees** [comment]
Sure feel free to make a PR of making it more concise. Easier for people to comment there.
