### ISSUE TITLE
Comma at end of assignment changes output with 23.3.0

### ISSUE THREAD

**Issue by daveisfera** [psf/black#3720]
This code is a little odd, but before it left it as is and now with 23.3.0, the output is changed

```
def changes(a, b, c="C", **kwargs):
    z, y = kwargs["a"], kwargs["b"]
    x, w, v, = (
        "X",
        "W",
        "V",
    )

def stays(a, b, c="C", **kwargs):
    z, y = kwargs["a"], kwargs["b"]
    x, w, v = (
        "X",
        "W",
        "V",
    )
```

With 22.x, these would both be left as is, but with 23.3.0, the `changes` function is changed to a tuple that spans multiple lines for the assigned to values

**Comment by JelleZijlstra** [comment]
The new behavior is correct. This comma is treated as a magic trailing comma (https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma).

**Comment by daveisfera** [comment]
Doesn't that go against the concept of `cede control over minutiae of hand-formatting`? Basically, if a comma is accidentally left at the end of a tuple, then completely different output is received. Should the output be the same regardless of minor modifications by a human?

**Comment by JelleZijlstra** [comment]
It kind of does! The magic trailing comma isn't a feature I'm particularly happy with and I may want to turn it off by default (#2135), but now that we have it, we should apply it consistently.

**Comment by daveisfera** [comment]
Sounds good! Thanks for the info and all your work on `black`
