### ISSUE TITLE
Structural Pattern Matching (match case statement) with Or patterns ( | )  fail to break long code into multiple lines

### ISSUE THREAD

**Issue by jackjyq** [psf/black#3726]
**Describe the style change**

**Examples in the current _Black_ style**

```python
match status:
    case ThisIsAnExampleStringEnum.this_is_example_status_one | ThisIsAnExampleStringEnum.this_is_example_status_two | ThisIsAnExampleStringEnum.this_is_example_status_three:
        print("ok")
    case _:
        print("not ok")
```

**Desired style**

```python
match status:
    case (
        ThisIsAnExampleStringEnum.this_is_example_status_one
        | ThisIsAnExampleStringEnum.this_is_example_status_two
        | ThisIsAnExampleStringEnum.this_is_example_status_three
    ):
        print("ok")
    case _:
        print("not ok")
```

**Additional context**

The complete code example:

```python
from enum import Enum


class ThisIsAnExampleStringEnum(Enum):
    this_is_example_status_one = "one"
    this_is_example_status_two = "two"
    this_is_example_status_three = "three"


status = ThisIsAnExampleStringEnum.this_is_example_status_two

match status:
    case ThisIsAnExampleStringEnum.this_is_example_status_one | ThisIsAnExampleStringEnum.this_is_example_status_two | ThisIsAnExampleStringEnum.this_is_example_status_three:
        print("ok")
    case _:
        print("not ok")

```

**Comment by mjpieters** [comment]
On the plus side: once manually formatted with parentheses and linebreaks at least Black doesn't then undo this again.

That does mean that case patterns that could fit within the line length limit are not touched either:

````
match status:
    case (
        ShortEnumName.foo |
        ShortEnumName.bar
    ):
        print("ok")
    case _:
        print("not ok")
```

should really be reformatted to put the enum values on a single line without parentheses.

**Comment by MeGaGiGaGon** [comment]
This was fixed at some point, the example code now formats properly. [Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGGAKpdAD2IimZxl1N_WmBasjhgIpHOPmDx7blBV4bgG0jyyu_W4ZiG8tnE9scHqur8QinuWP4Xyf4QWtOkB_gVfae38ThYXL_Qq6M-0NVzTfTJ6bgnd6tdH0F9UwnYsyqE1osyx810RUU3oSzsKqh4Dzmmeu8Rzt4OEjd3OKK3OclEFwEwLuy10b8SPVS3gmN1K8tjaAFfddC12ZYK_7SwT8PP5zbcX-m_A4qg_dMAAAAAnqwRYj6EZDwAAcYBhwMAAB8wTEuxxGf7AgAAAAAEWVo=). This also already has equivalent tests in [`pattern_matching_long.py`](https://github.com/psf/black/blob/84ac1a947d811f4de08f75715256ef0366ec9bc1/tests/data/cases/pattern_matching_long.py) so should be good to close.
