### ISSUE TITLE
Line too long: Long attribute chain in import

### ISSUE THREAD

**Issue by mrVragec** [psf/black#3734]
I have an import (which is already formatted in a way that doesn't violate max-line-length)
```
from base.tests.blabla.v1.something.even_more_deep \
    .this_is_one_file.this_is_also_something.one_file import Ship
```
after running black with the command
```
 black -l 99 --preview ./
```
the import would be formatted as
```
from base.tests.blabla.v1.something.even_more_deep.this_is_one_file.this_is_also_something.one_file import (
    Ship,
)
```
which would violate the --max-line-length. 
I tested is also [here](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFRANhdAD2IimZxl1N_WlkPinBFn3DxhUzbnVt2QcbuW-sWzWY4FZ7F72Vinu57D3moOCtSNkKB9NWYRITLrXXN6BYkZ5g1Cq68Sr1qPndB5siHyyBZGnbKTe4Mg8AEO9c0WSX2tgjx4MRgKNUKxqTZk5QcgZAQifkuEINjkVLonnPFor3xZNNFjBJhdgafXQumJDt2dnyUA7uuv05QmcdZ-gZoCTN-ft8Wy85V3pz6tEu8Y74fLMq2BFoIB7Mv22G3zm8iQBYavd53FFxI0PrVjAq0No5ILu64PerfXwDnC8vnlM1A8gAB9AHSAgAAHgPv_7HEZ_sCAAAAAARZWg==) 

As the `black` is not the only tool we use, that makes also other tools scream :) 

Is there any way to:
- add # noq E501 when black format that kind of the line
- or don't format the line in case the formatted line would exceed --max-line-length?

**Comment by JelleZijlstra** [comment]
I don't think there is any nice way for Black to format this. (We avoid using backslashes.)

I would recommend simply turning off line length checks from linters. If you cannot, you can manually add backslashes and use `# fmt: off` so Black will leave this line alone.

**Comment by mrVragec** [comment]
Hmmm, that's sad :( As it's quite some manual work to fix all the issues in the already existing codebase :(

**Comment by hauntsaninja** [comment]
To your first question: you can use `ruff --select E501 --add-noqa .` to add `# noqa: E501` comments everywhere necessary, in case you can't turn E501 off.

Black's not going to change to introduce backslashes, so unfortunately, I don't see an improvement we can make here.
