### ISSUE TITLE
Black is changing previously formatted code

### ISSUE THREAD

**Issue by jontwo** [psf/black#3744]
**Describe the bug**

We started to use black and used it to reformat the whole repository. One week later, on the same `black` version, many lines have been changed back to what they were previously. 

Merge request 1, introducing `black`:
![image](https://github.com/psf/black/assets/5537223/89680ed9-0052-4f41-b1cc-9186e3a5ea10)

Merge request 2, one week later:
![image](https://github.com/psf/black/assets/5537223/6ad370f3-a1bd-4fb2-806a-dbe15bff75ce)

I don't mind which version we have, but I would like `black` to pick one and stick with it.

**To Reproduce**

This is one of many examples throughout our codebase. 

```python


class TestDifferenceBetweenCoastAndCatchments(
    PytestMixin, VectorMixin, TestVectorsEqual
):
    coast_wkt = "POLYGON ((0 0, 0 6, 6 6, 6 0, 0 0))"


```

We're using the VSCode Black Formatter extension with format on save = true and line length = 100.

The issue is hard to repro because it doesn't change on every merge request, but it's often enough to cause a problem.

**Expected behavior**

`black` does not change code that it has previously formatted.

**Environment**

- Black's version: 23.3.0
- OS and Python version: Ubuntu 22.04/3.10.6

**Comment by JelleZijlstra** [comment]
You are almost certainly running Black with different options, or different versions of Black.

**Comment by jontwo** [comment]
You'd think, but we've checked and it's the same version, same options. Is there any debug logging we can enable?

**Comment by JelleZijlstra** [comment]
You can use these options to `black`:

```
  -v, --verbose                   Also emit messages to stderr about files
                                  that were not changed or were ignored due to
                                  exclusion patterns.
  --version                       Show the version and exit.
```

`-v` also prints the config used.

**Comment by hauntsaninja** [comment]
Setting the `required-version` flag / configuration can also help catch cases where people are using different versions.

**Comment by jontwo** [comment]
I think on the initial commit, `black` didn't pick up the `line-length=100` setting. We've switched to using pyproject.toml and it looks like all the settings are being picked up now. Hopefully there won't be any more changes.
