### ISSUE TITLE
Doesn't honor extend-exclude for nested file

### ISSUE THREAD

**Issue by asarkar** [psf/black#3754]
**Describe the bug**

Given the following configuration in `pyproject.toml`
```
[tool.black]
line-length = 120
extend-exclude = [
    '^(?:([^\/]+\/)+(?:test_.*\.py|.*_test\.py))$',
    '.github',
    '.mypy_cache',
    '.pytest_cache',
    'venv'
]
```

Black fails with the error:

```
Error: Invalid value for '--extend-exclude': Not a valid regular expression: unbalanced parenthesis at position 17
```

But this is a valid regex that's supposed to match any files starting or ending in `test` or files in a directory named `test`. For example, the following path matches the `test` directory:
myapp/folder/test/test_something.py

**To Reproduce**

I guess use the regex in a unit test that parses it?

**Expected behavior**

It should work. It would be even better if Black could use the `extend-exclude` list from flake8 or mypy, so that I don't have repeat it. The [documentation](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html) only shows the `max-line-length` property. 

**Environment**

- Black's version: 23.3.0
- OS: macOS Ventura 13.4.1, M1 chip
- Python version: (CPython) 3.11.3

**Comment by hauntsaninja** [comment]
The extend-exclude config is meant to be a str, not a list. The error message here could obviously be much better.

**Comment by asarkar** [comment]
@hauntsaninja Thanks, let me try that. Do you've any comment on the other thing I mentioned above?

> It would be even better if Black could use the extend-exclude list from flake8 or mypy

**Comment by asarkar** [comment]
> The extend-exclude config is meant to be a str
```
extend-exclude = """
/
^(?:(?:[^/]+/)+(?:test_.*\\.py|.*_test\\.py))$
| .github
/
"""
```
Nah, this doesn't work too. No error, but the file `test_something.py` gets formatted.

**Comment by asarkar** [comment]
@hauntsaninja How does improving the error message fix the issue where the exclude doesn’t work at all?

**Comment by hauntsaninja** [comment]
You might want to be a little nicer to volunteers.

The PR fixed your original issue and you haven't provided enough information for whatever other issue you're facing. Works fine for me:
```
λ cat pyproject.toml
[tool.black]
extend-exclude=".*_test.py"

λ cat something.py 
x = (
        'asdf'
        )

λ cat something_test.py 
x = (
        'asdf'
        )

λ black --check .
would reformat /Users/shantanu/dev/black/proj/something.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```

Maybe you're looking for `--force-exclude`? https://github.com/psf/black/blob/main/docs/usage_and_configuration/the_basics.md#--force-exclude

**Comment by JelleZijlstra** [comment]
And on this one:

> It would be even better if Black could use the extend-exclude list from flake8 or mypy

I don't think that's a good idea. People might exclude files from different tools for different reasons, and it is likely to be confusing if configuration for one tool magically affects another.
