### ISSUE TITLE
Hatchling version is incorrect in toml file

### ISSUE THREAD

**Issue by KiraUnderwood** [psf/black#3760]
**Describe the bug**

ERROR: Could not find a version that satisfies the requirement hatchling>=1.8.0 (from versions: none)

**To Reproduce**

on black installation

For example, take this code:

```python
this = "code"
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

The resulting error is:

> cannot format file.py: INTERNAL ERROR: ...

**Expected behavior**

**Environment**

- Black's version: 
- OS and Python version: 

**Additional context**

**Comment by JelleZijlstra** [comment]
Hatching 1.8.0 has `Requires-Python: >=3.7`. Are you perhaps running on Python 3.6? If so, please upgrade, as Python 3.6 has been unmaintained for over a year now.

**Comment by KiraUnderwood** [comment]
Thank you. I apologize, It turned out I have issues with pip. I fixed those and everything is fine.
I apologize for inconvenience.
