### ISSUE TITLE
--extend-exclude not working when in pre-commit

### ISSUE THREAD

**Issue by jsh9** [psf/black#3767]
**Describe the bug**

When `Black` is used as a pre-commit hook, the `--extend-exclude` option has no effect.

**To Reproduce**

- Take a piece of Python code that you know will be formatted by `Black`
- Add the path of this file to `--extend-exclude`
- Run `Black` directly in the command line (like `black /folder/that/contains/this/file`)
- Run `Black` in pre-commit

**Expected behavior**

When `Black` is run directly in the command line, that file is not formatted.

When `Black` is run via pre-commit, that file should also not be formatted.

**Actual behavior**

When `Black` is run directly in the command line, that file is not formatted.

When `Black` is run via pre-commit, that file is formatted.

**Environment**

- Black's version: the `main` branch
- OS and Python version: Python 3.9, macOS

**Root cause**

I did some debugging found the root cause: when `Black` is run directly in the command line, this branch is entered:

https://github.com/psf/black/blob/cf4cc2981900565ab931aada176abf08a1f5782d/src/black/__init__.py#L676

But when `Black` is run via pre-commit, this branch is entered because `p.is_file()` is `True`:

https://github.com/psf/black/blob/cf4cc2981900565ab931aada176abf08a1f5782d/src/black/__init__.py#L646

In the `if is_stdin or p.is_file()` branch, there's no checking of `extend_exclude` or `exclude` patterns, only `force_exclude`.  That's why `--extend-exclude` has no effect.

**Proposed solution**

Given the root cause above, the solution should be straightforward.

**Comment by hauntsaninja** [comment]
I think you're looking for `--force-exclude` https://github.com/psf/black/blob/main/docs/usage_and_configuration/the_basics.md#--force-exclude
You can also use the pre-commit exclude options. 

See https://github.com/psf/black/issues/395 and https://github.com/psf/black/issues/438

**Comment by jsh9** [comment]
I would argue that the documentation around `exclude`, `extend-exclude`, and `force-exclude` is very confusing.

Does `force-exclude` replace `exclude`?  Or does it add on top of `exclude`?

And if users have to use `force-exclude` in pre-commit, **_and_** `force-exclude` replaces `exclude`, does it mean that we now have to look into `Black`'s code base to find out what the default `exclude` pattern is?

The code logic may be fine, but I would appreciate additional clarity in the documentation.
