### ISSUE TITLE
minor: unnecessary newline inserted after `else` before function

### ISSUE THREAD

**Issue by asottile** [psf/black#377]
### current behaviour

(run against master)

```diff
$ black --diff test.py 2> /dev/null
--- test.py	2018-06-23 15:02:32.200993 +0000
+++ test.py	2018-06-23 15:03:00.152248 +0000
@@ -1,6 +1,7 @@
 if False:
     from x import y
 else:
+
     def y():
         pass
 
```

### desired behaviour

(noop)

**Comment by ambv** [comment]
This is deliberate. A def directly inside a def will do the same, too. This is to make inner defs more prominent.

We did relax this for first defs in a class so maybe we should generalize this for all indented blocks.

**Comment by ambv** [comment]
We will be solving this as part of #450.
