### ISSUE TITLE
Release 23.7.0

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3774]
It's been a while since the last release and we have some good bugfixes and enhancements. Let's do a release in the next week or so.

**Comment by hauntsaninja** [comment]
Sounds good! Reading the changlog had two nits: a) "ccode" is a typo for "code", b) I think #3757 is not a change to an integration or user facing so can be removed

**Comment by JelleZijlstra** [comment]
I noticed the typo too, will fix that along with copy-editing the rest when I prepare the release.

#3757 fixes a user-visible warning so I do think it should be mentioned.

**Comment by hauntsaninja** [comment]
#3757 is just a change in diff_shades_gha_helper.py, what am I missing? (I agree #3763 fixes a user visible warning)

**Comment by JelleZijlstra** [comment]
You're right, didn't realize that was for the internal GH action only. I'll remove it.

**Comment by JelleZijlstra** [comment]
Release cut and all wheels are on pypi
