### ISSUE TITLE
Formatter runs, no output, never ends.

### ISSUE THREAD

**Issue by eddtrettel** [psf/black#3785]
**Black https://github.com/psf/black/commit/193ee7**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABlADtdAD2IimZxl1N_W1ktIvcnCRyz_JxMldeGP3FkYC4l_yCiOWfL-S4QrUMyitkDP-9TiRumVRC_cm_kkqQAAADz8W8IWfenugABV2bVuq1xH7bzfQEAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

[code.py.txt](https://github.com/psf/black/files/12016417/code.py.txt)

## Output

```python

```

## Expected

Hi,

I've used the formatter on this code sucessfully several hundred times.  It's great!  However, my most recent version of my code, once pasted into the input window, just causes the output window to show the "blinking" icon and never ends.

Note that my code is Adafruit CircuitPython 8.1.0 on 2023-05-22.  The code runs with no issue on my device (Adafruit Matrix Portal M4 with samd51j19).  In addition, I've put this code through Black several dozens of times per day in the past days and it gets formatted.  I uncommented some sections, which made the code larger, so I'll experiment on my end with commenting out blocks of code to see if it works with Black.

Again, thank you for making this great online formatter!

Best regards,
E.T.
![Screenshot 2023-07-11 082422](https://github.com/psf/black/assets/57777492/cf85bc7f-9c68-4590-90b5-90958068330d)

**Comment by eddtrettel** [comment]
Hi,

I've found a workaround.  If it slice the code into the first third, the second, and the third (based upon rough line counts where the thirds don't split statments and/or funcitons across those boundaries, I can process the 1st, 2nd, and 3rd sections in Black, and then paste those back into my code.

The end product is that all of my code has been through Black, and that it's works as designed on my processor.

If an issue is found with the Black code please let me know via Github.  In the meantime the workaround does the job.

Thank you,
Edd Trettel

**Comment by eddtrettel** [comment]
Hi Shantanu,

Thanks for looking into this.

I don't have Black on my machines (Windows11; Linux).  Therefore we can
close this incident at this time.  I'll install it on one of my boxes and
report back to you, but that could be weeks or months.

Thanks again,
Edd

**Comment by hauntsaninja** [comment]
Sounds good, thank you for reporting and please feel free to reopen the issue if you can reproduce standalone!
