### ISSUE TITLE
Documentation of current code-style formatting of comment omits mention of hashbangs

### ISSUE THREAD

**Issue by kotnen** [psf/black#3786]
## **Describe the problem**
The documentation of the current code-style fails to list hashbang comments (`#!`) among the types of comments that are excepted from the spacing rules, even though they are indeed excepted from the spacing rules (see [src/black/comments.py](https://github.com/psf/black/blob/main/src/black/comments.py#L26)).

From the [comments subsection of docs/the_black_code_style/current_style.md](https://github.com/psf/black/blob/main/docs/the_black_code_style/current_style.md#comments):
> Some types of comments that require specific spacing rules are respected: doc comments (#: comment), section comments with long runs of hashes, and Spyder cells.

## **Describe the solution you'd like**
I would like this behaviour to be documented.  I will create a Pull Request to rectify this if/when given the go-ahead from whomever has authority over maintenance of the documentation.

## **Describe alternatives you've considered**
I did (briefly) consider allowing this to go undocumented.  I then immediately stopped considering that, as allowing this omission to continue existing would be completely and utterly silly.  Regardless of how minor the omission is, it's my opinion there's no good reason to leave this (or indeed, any) behaviour undocumented.  This applies doubly in this case specifically, because of how little effort it would require to fix the documentation (only one sentence needs to be modified).

**Comment by JelleZijlstra** [comment]
Feel free to send a PR! In general for small documentation changes it's fine to send a PR without going through an issue.
