### ISSUE TITLE
Line breaking long sequence of assignments

### ISSUE THREAD

**Issue by piotro888** [psf/black#3789]
**Describe the style change**

Hello,
We noticed that Black breaks long chains of assignments into multiple lines in a very unexpected way.

**Example source code**
```python
AA = BB = CC = DD = EE = FF = GG = HH = JJ = KK = LL = MM = NN = OO = PP = QQ = RR = SS = TT = UU = WW = XX = YY = ZZ = 1
```

**Examples in the current _Black_ style**

Black formats it in this way (last line is matched to max line length, but previous elements get 2 lines per one element):
```python
AA = (
    BB
) = (
    CC
) = (
    DD
) = (
    EE
) = (
    FF
) = (
    GG
) = (
    HH
) = JJ = KK = LL = MM = NN = OO = PP = QQ = RR = SS = TT = UU = WW = XX = YY = ZZ = 1
```

**Desired style**

We would expect that all lines would break at max line length, and that the last line would be shorter. 
We are not sure what would the desired splitting format, here are some propositions to be discussed:

```python
#1
AA = BB = CC = DD = EE =  FF =  GG =  HH = JJ = KK = LL = MM = NN = OO = PP = QQ = (
RR ) = SS = TT = UU = WW = XX = YY = ZZ = 1
#2
AA = BB = CC = DD = EE =  FF =  GG =  HH = JJ = KK = LL = MM = NN = OO = PP =  ( QQ 
) = RR = SS = TT = UU = WW = XX = YY = ZZ = 1
#3 - looks the best for me
AA = BB = CC = DD = EE =  FF =  GG =  HH = JJ = KK = LL = MM = NN = OO = PP = QQ = ( 
    RR ) = SS = TT = UU = WW = XX = YY = ZZ = 1
#4
AA = BB = CC = DD = EE =  FF =  GG =  HH = JJ = KK = LL = MM = NN = OO = PP = QQ = (
    RR
) = SS = TT = UU = WW = XX = YY = ZZ = 1
#5
AA = BB = CC = DD = EE =  FF =  GG =  HH = JJ = KK = LL = MM = NN = OO = PP = QQ = \
    RR = SS = TT = UU = WW = XX = YY = ZZ = 1
```

All of above cases look  more usable than currently formatted version. 

**Additional context**

This a legitimate minified case from code, where we needed to assign a lot of alias names to an Enum field.

**Comment by MeGaGiGaGon** [comment]
This now formats to
```py
AA = BB = CC = DD = EE = FF = GG = HH = JJ = KK = LL = MM = NN = OO = PP = QQ = RR = (
    SS
) = TT = UU = WW = XX = YY = ZZ = 1
```
[playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AD7AIldAD2IimZxl1N_WjPJNmglXZYxYNw4LDvDIL-OuyLp4bh78oArvbJ51Y_Yk07Yk9WMYYslETwTfY_bGOuOnqpe6bSEaI0zTJ64e2-8PJcWa5LkpfRVjGO7p0folt_7erRkYeDne5UNVYaTvkRtxrO0Y-EogSsXH-0p8S8whxamvujvYLjhD3XP58S8AAAAAPURukYHqbqFAAGlAfwBAAAYvpZ6scRn-wIAAAAABFla) which is almost the same as case number 4, so this should be good to close. The change looks to have been put into preview by #4010 and later stabilized in version 2024 as part of #3368. #4010 also added a roughly equivalent test case [here](https://github.com/psf/black/blob/84ac1a947d811f4de08f75715256ef0366ec9bc1/tests/data/cases/prefer_rhs_split.py#L91-L97).
