### ISSUE TITLE
`if` clauses in `match`-`case` blocks aren't reformatted to fit the line width limit

### ISSUE THREAD

**Issue by alexander-c-b** [psf/black#3793]
**Describe the bug**

`if` clauses in `match`-`case` blocks in are not reformatted when the line length is above the maximum length set.

**To Reproduce**

Take this code, where the second line is 99 characters (11 characters above the horizontal limit):

```python
match "test":
    case "test" if "any long condition" != "another long condition" and "this is a long condition":
        print("Test")

```

And try formatting it:

```sh
$ black file.py
```

Black leaves the file unchanged:

```
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Expected behavior**

Black should reformat the file as:

```python
match "test":
    case "test" if (
        "any long condition" != "another long condition" and "this is a long condition"
    ):
        print("Test")
```

**Environment**

- Black's version: 23.7.0
- OS and Python version: Ubuntu Linux 22.04 (running on the Windows Subsystem for Linux) / Python 3.10.4 

**Additional context**

This appears to happen regardless of the line length.  Also, interestingly, if parentheses are added around the boolean expression manually, Black _does_ format the file correctly.

**Comment by JelleZijlstra** [comment]
We now format this as ```
match "test":
    case (
        "test"
    ) if "any long condition" != "another long condition" and "this is a long condition":
        print("Test")
```

Which still isn't great.
