### ISSUE TITLE
Top level return statement -- expected to fail

### ISSUE THREAD

**Issue by tmontes** [psf/black#3807]
**Black v23.7.0**

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACLAFtdAD2IimZxl1N_WlbvK5V9Hvo0zZlhiNjk5fj3NP27suzgGaRw8rj04EHgl7MNtyaAYv54YsK9Rj-LrR8hWx2FwaLipjhCD_ofqJMicObS0d85yUXhPifMhs824gAAAPrMGADDTCLcAAF3jAEAAABS09gZscRn-wIAAAAABFla)

## Context

* EuroPython 2023 [Mu Editor](https://codewith.mu/) sprints.
* Mu uses black to *Tidy* up beginner's code.
* Several volunteers helping out translating Mu to other languages are poking around Mu to get the original English messages and translate them.
* @prochazka-jan found this and it surprised us.

## Options

`--line-length=88`
`--safe`

## Input

```python
def f():
    n = 42
return n
    

```

## Output

```python
def f():
    n = 42


return n

```

## Expected

Given that top-level `return` statements are invalid syntax, shouldn't black error out?

PS: Thanks! :-)

**Comment by JelleZijlstra** [comment]
Black is a formatter, not a syntax checker. We don't guarantee that we fail on all invalid code.

https://black.readthedocs.io/en/stable/faq.html#why-does-black-not-detect-syntax-errors-in-my-code
