### ISSUE TITLE
Black adds line unnecessary line breaks on tuple expansion

### ISSUE THREAD

**Issue by leonardopsantos** [psf/black#3813]
**Describe the bug**

Black adds line breaks on tuple expansion even when the line length is under the allotted limit.

**To Reproduce**

Given the following snippet:

```py
def do_something(values):
    ( a2, t0, t1, ) = values

    j = [1,
         2,
         3
    ]

    # Dummy code follows:
    if a2 < 0:
        return 0
    elif t1 == t0:
        return 1
    else:
        return 2
```

Using

```
black test_black.py --target-version py39
```

Black formats it to:

```py
def do_something(values):
    (
        a2,
        t0,
        t1,
    ) = values

    j = [1, 2, 3]

    # Dummy code follows:
    if a2 < 0:
        return 0
    elif t1 == t0:
        return 1
    else:
        return 2
```

I understand that this is probably a consequence of #656 , but I don't see this choice being described in [Black the code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html). It's the opposite of the [How Black wraps lines](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines) example.

How is 

```py
    (
        a2,
        t0,
        t1,
    ) = values
```

More readable than

```py
    ( a2, t0, t1, ) = values
```

Also:

> If a data structure literal (tuple, list, set, dict) or a line of “from” imports cannot fit in the allotted length, it’s always split into one element per line.

The `    ( a2, t0, t1, ) = values` line is clearly under the allotted length, so I don't understand why the line breaks were added.

**Expected Output**

Given that the line length is under the limit, I expect Black to just add parentheses and a trailing comma:

```py
    (a2, t0, t1,) = values
```

**Environment**

- Black's version:

```
$ black --version
black, 23.7.0 (compiled: yes)
Python (CPython) 3.8.10
```
- OS and Python version:

```
$ python3 --version
Python 3.8.10

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

Same behaviour with Python 3.11.2 and Ubuntu 23.04

**Comment by JelleZijlstra** [comment]
This is the magic trailing comma: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma

**Comment by leonardopsantos** [comment]
> This is the magic trailing comma: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma

That's true, my bad. If I omit the comma like so:

```py
( a2, t0, t1 ) = values
```

Then the line is preserved. Thanks and sorry for crying wolf.
