### ISSUE TITLE
How can I set skip-string-normalization via config files?

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [psf/black#3814]
How can I use "--skip-string-normalization" or "-S" in my `pyproject.toml` or `.black` config files? Or I can only use it via CLI?

**Comment by hauntsaninja** [comment]
`skip-string-normalization = true` in your pyproject.toml

**Comment by ladyrick** [comment]
> `skip-string-normalization = true` in your pyproject.toml

How can I set `skip-string-normalization = false` in my command line args so I can overwrite the config file?
