### ISSUE TITLE
Comment is removed inside two pairs of parentheses

### ISSUE THREAD

**Issue by sagark4** [psf/black#3815]
**Black https://github.com/psf/black/commit/c3235e**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACZAGVdAD2IimZxl1N_Wlws4SSfhvbGwuP6jsfmgnb8ARMAR2V_UJHHOyeiwNcjQiu0GhYjdcO4liGW2J0TeBgncyKtJ_H87d1jKJ2pyaCwrgBj1Mlq6vnOvm0jbchemI3s6xyDPUy5PJcAAAAAADxDb0Shhvi6AAGBAZoBAADnUeb4scRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
if ((
    True
    # sdf
)):
    print("hw")

```

## Output

```python
if True:
    print("hw")

```

## Expected
Something like:
```python
if (
    True
    # sdf
):
    print("hw")
```

**Comment by sagark4** [comment]
Apologies if I missed some rules/etiquettes when posting this issue.  I actually faced this issue in real-life when I took the suggestion of [this SO answer](https://stackoverflow.com/a/68911882) to combat `E129 visually indented line with same indent as next logical line` (before using black).  I had added a big comment inside describing the logic of the `if` condition, which got removed by black.  Please let me know if I should add more information.

**Comment by tusharhero** [comment]
Wouldn't it be better to do something like this?

```py
if True: # sdf
    print("hw")
```

**Comment by JelleZijlstra** [comment]
We should definitely not remove the comment. I would welcome a proposed fix.

**Comment by sagark4** [comment]
Well, if you blacken the following code, it stays unchanged.  [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACVAGFdAD2IimZxl1N_Wlws4SR2T8ZZR20deiE0nAGdx6Seyg-QeXSak9N53dGa4exKNRz_FhYC01c5J_XWwgJRXNgKs3tDJ1t-KRlCUaV7wS4Fni6Urt87IUL0gGma_qK4tgtMp2QAAAAAHfAfaVLPikcAAX2WAQAAABd_E5KxxGf7AgAAAAAEWVo=)

```python
if (
    True
    # sdf
):
    print("hw")
```

**Comment by rafaelclp** [comment]
@sagark4 yes, that one is fine, it's just when there are two sets of parentheses. I hit this bug today as well, but my parentheses were positioned differently:
```python
if (
    # comment
    (True)
):
    pass
```

You might be wondering why anyone would write the code above. In my case, I had something like this:
```python
if (
    a_long_condition
    # a long comment about the condition below
    and (a or b)
):
    pass
```
Then I removed `a_long_condition` and the next `and`, and ran black expecting the comment to move above the `if`. Instead, the comment was removed.

**Comment by hauntsaninja** [comment]
Changed the title, since I think this is the same issue reported in #4199
```
def return_true():
    return (
        (
            True  # this comment gets removed accidentally
        )
    )
```

**Comment by RedGuy12** [comment]
Interesting, it looks like there's some special logic here for `type: ignore` comments

```diff
-if ((
+if (
     # type: ignore
     True
-)):
+):
     print("hw")
```


This code results in a crash when running with `--safe`
```py
if ((
    True
    # type: ignore
)):
    print("hw")
```
