### ISSUE TITLE
Black trims whitespace around walrus operators in slices

### ISSUE THREAD

**Issue by charliermarsh** [psf/black#3820]
**Describe the bug**

Black trims whitespace around `:=` operators within slices. I'm not sure if this is a feature or a bug (if it's intended, feel free to close of course).

The behavior is similar to Black's treatment of `:` operators in slices as described [here](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices), but I can't tell if the same treatment is intentional for `:=` operators.

**To Reproduce**

For example, given this code:

```python
x[y := 1]
```

The formatted code is:

```python
x[y:=1]
```

Similar to treatment of the `:` operator, Black does _not_ reformat these:

```python
x[(y := 1)]
x[y := f()]
```

Here's a [playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACPAFhdAD2IimZxl1N_WmyxXI25ydt_l-wQhA0VY58ypdO-f0EIorSuhckQkLRD1Y6D1pZQmLM0fnhDVbMMexZjk98IbWC5ckOcJ6Vc8k6der8aXC3kIo2BGf_R6H4AViGa7H6QU0kAAXSQAQAAAH_bXDqxxGf7AgAAAAAEWVo=) to demonstrate the above cases.

**Comment by JelleZijlstra** [comment]
That feels like a bug, we should add spaces here. PR welcome!

**Comment by thomasjo** [comment]
> Hey @JelleZijlstra I would like to work on this issue.

@Utkarshn10 it's already being worked on: https://github.com/psf/black/pull/3823

**Comment by Utkarshn10** [comment]
Thanks for letting me know :)

> > Hey @JelleZijlstra I would like to work on this issue.
> 
> @Utkarshn10 it's already being worked on: #3823
