### ISSUE TITLE
Reformat None to (None,) on Optional List

### ISSUE THREAD

**Issue by xbeta** [psf/black#3827]
**Describe the bug**

`black` seems to reformat and change the default values from `None` to `(None,)`. Was this necessary? First time I have seen it being changed to `(None,)`

From:

```python
@dataclass
class Foobar:
    include_feedback: Optional[List[str]] = None,
    exclude_feedback: Optional[List[str]] = None,
```

To:

```python
@dataclass
class Foobar:
    include_feedback: Optional[List[str]] = (None,)
    exclude_feedback: Optional[List[str]] = (None,)

```

**To Reproduce**

And run it with these arguments:

```sh
$ black common.py --target-version py38

```

The resulting error is:

N/A

**Expected behavior**

See above.

**Environment**

- Black's version: `black, 23.7.0 (compiled: yes)`
- Python version: `Python (CPython) 3.8.17`

- OS: `macOS 13.5 (22G74)`

**Additional context**

**Comment by JelleZijlstra** [comment]
This is intentional; it makes it clear that you are creating a single-element tuple.

**Comment by drunkwcodes** [comment]
This is weird. This will change the behavior of
```
if foobar.include_feedback:
    ...
```

which is a big no.

**Comment by JelleZijlstra** [comment]
It does not. It's a tuple before and after.

**Comment by drunkwcodes** [comment]
Ah. My mistake.
