### ISSUE TITLE
 Error: Config key target-version must be a list

### ISSUE THREAD

**Issue by shawnyang2019** [psf/black#3829]
i config the black in pycharm like this :-l 120 $FilePath$ -S -t py39

format the code normally in on project but occur the following issue in another project.   can somebody helpt to resolve it,thanks

Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Config key target-version must be a list

![Snipaste_2023-08-04_12-07-51](https://github.com/psf/black/assets/47634598/ca219ecb-1e08-4990-bfc8-65b985dbc814)

python version 3.8
black version 23.7.0

**Comment by hauntsaninja** [comment]
You have an incorrect target-version in your pyproject.toml
