### ISSUE TITLE
[minor] [question] some symbols fail to be printed

### ISSUE THREAD

**Issue by mb6ockatf** [psf/black#3831]
**Describe the bug**

some output characters fail to render (or look like that)
![image](https://github.com/psf/black/assets/104227451/6df6723e-5e59-471d-a7f4-40ff13658cc7)

(i mean, those three squares after 'all done' message)

same things in both alacritty and vscode terminals. i think this is probably due to lack of dome unicode fonts, or something

**To Reproduce**

checkout screenshot above

**Expected behavior**

symbols are visible, i suppose

**Environment**

- Black's version: 23.7.0
- OS and Python version: GNU/Linux 6.4.7-arch1-3 3.11.3

it is not a serious problem, i just was curious about what are these characters supposed to mean

**Comment by JelleZijlstra** [comment]
They're just festive emoji, 🍰 and ⭐ I think. Their absence indicates your terminal has poor Unicode support, but otherwise it's harmless.

**Comment by mb6ockatf** [comment]
yes, alacritty does not support unicode. thank you for your answer
