### ISSUE TITLE
"Black produced code that is not equivalent to the source"

### ISSUE THREAD

**Issue by mcowpert** [psf/black#3842]
black, 22.8.0 (compiled: yes)
Python (CPython) 3.6.9  (I know, I know, sorry)

Ran `black` on a pytest file with some `pytest.fixture` definitions; a Test class, decorated with `pytest.usefixtures()`, with three staticmethod tests; and several test functions decorated with `pytest.parametrize()`. Got this:

> error: cannot format test/test_apps.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.

Am attaching the diff file.
[blk_l006a5yp.log](https://github.com/psf/black/files/12384167/blk_l006a5yp.log)

**Comment by mcowpert** [comment]
I just checked under Python 3.10, black 23.7, and the same file formats fine.

**Comment by hauntsaninja** [comment]
Great! The solution is then to use black 23.7
