### ISSUE TITLE
Line too long: Many cases in case block

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3850]
**Describe the bug**

Match patterns with lots of `|`-delimited alternatives are not split into multiple lines.

**To Reproduce**

```python
% cat longmatch.py 
match x:
    case "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd" | "abcd":
        pass
% black -t py311 longmatch.py --diff
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

(Note the line is 142 characters long)

**Expected behavior**

I want it to reformat to:

```python
match x:
    case (
        "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
        | "abcd"
    ):
        pass
```

Black does this already if you manually add parentheses around the whole sequence of alternatives.

**Environment**

- Black's version: 23.7.0
- OS and Python version: macOS

**Comment by rdrll** [comment]
While I was trying to fix this issue, I noticed that the rules for `match` is a bit different than the others: the [trailing comma rules ](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas) will not be activated on `match`

E.g. Black will currently leave this piece of code unchanged despite it contains trailing comma and each of its item is not in seperate lines (see [here](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACPAGBdAD2IimZxl1N_WmBasjhgIpJRm9D2G66SDLhhnFrSNeMykF1T7_XvdV1ILVbFVrh2v9AAXw2gdeUx-8Jo-bDKXZ1ooMdzNtm7kIEA1AsAChaiMeoJ3hg3MQVQGY_oHvffAABtJu4QBJOyRAABfJABAAAAElkP1rHEZ_sCAAAAAARZWg==))
```
match x:
    case 1, 2,:
        pass
```

Yet, an unintentional side effect of my current attempt would enable the trailing comma on `match` as well, hence the above code will be converted into:
```
match x:
    case (
        1, 
        2,
    ):
        pass
```
I think it is beneficial to have our trailing comma rules consistent across different syntax, but I do want to double check if this is indeed the preferable result here and there is no particular reason to do trailing comma for `match` differently.

**Comment by JelleZijlstra** [comment]
I agree we should reformat this case as you suggest.

**Comment by McDic** [comment]
I support this issue!
