### ISSUE TITLE
Error compiling contract, Error message:

### ISSUE THREAD

**Issue by Last-Winner** [psf/black#3856]
Error compiling contract, Error message:
tokenize.TokenError: ('EOF in multi-line statement', (230, 0))

The above exception was the direct cause of the following exception:

vyper.exceptions.SyntaxException: EOF in multi-line statement
  line 230:0 
       229 227      ],
  ---> 230
  ---------^

_Originally posted by @Last-Winner in https://github.com/psf/black/issues/2317#issuecomment-169572856

![Screenshot_2023-08-28-23-17-13-06](https://user-images.githubusercontent.com/96341825/263746988-39d092fc-236d-4fbf-8cab-6079fabe1f90.png)
8_

**Comment by JelleZijlstra** [comment]
This doesn't look like it has anything to do with Black.
