### ISSUE TITLE
No mypyc wheels for release 23.9.0

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3865]
The mypyc wheels for the latest release (23.9.0) failed to build (https://github.com/psf/black/actions/runs/6128665138/job/16635954268) because we were running a version of mypyc that doesn't yet support Python 3.12. Therefore, 23.9.0 now only provides a pure-Python wheel on pypi, which will be much slower.

My current plan is to upgrade to the latest mypyc (#3864), confirm that the 3.12 wheel gets built correctly with it, then release version 23.9.1 tomorrow.

**Comment by JelleZijlstra** [comment]
Experiments in #3867 show that current main doesn't build with mypyc even on versions before 3.12, and the solution isn't obvious. We'll figure it out eventually and release a new version with mypyc wheels as soon as we can.

**Comment by JelleZijlstra** [comment]
23.9.1 was just released with all the mypyc wheels for 3.8 through 3.11. Thanks @cdce8p, @hauntsaninja, @AlexWaygood, and @ichard26 for your help!

**Comment by twmr** [comment]
I've just realized that there are no mypyc wheels for python 3.12.

@JelleZijlstra you mentioned in the description of the ticket that

> My current plan is to upgrade to the latest mypyc (https://github.com/psf/black/pull/3864), confirm that the 3.12 wheel gets built correctly with it, then release version 23.9.1 tomorrow.

but in the end you 

> 23.9.1 was just released with all the mypyc wheels for 3.8 through 3.11

What is the problem with python 3.12?

**Comment by hauntsaninja** [comment]
We have Python 3.12 mypyc wheels in more recent releases, so if you upgrade to something more recent, you'll be fine.

**Comment by twmr** [comment]
Indeed. Now it works. I tried it before I wrote my above comment and the output of `black --version` contained "(compiled: no)". Anyway, now it works. Thx
