### ISSUE TITLE
Proposal: strip empty lines between module docstring and first import

### ISSUE THREAD

**Issue by euan-reid** [psf/black#3900]
**Describe the style change**

Currently Black has no opinion on the number of empty lines that may exist between the module's docstring and the first import line other than collapsing down to at-most-2. I'm proposing that Black should have an opinion, specifically that there should be none (in line with the general philosophy on empty lines).

**Examples in the current _Black_ style**

All three examples are left unchanged by Black 23.9.1:

```python
"""My super cool module"""


from __future__ import annotations


def foo():
    pass
```

```python
"""My super cool module"""

from __future__ import annotations


def foo():
    pass
```

```python
"""My super cool module"""
from __future__ import annotations


def foo():
    pass
```

**Desired style**

```python
"""My super cool module"
from __future__ import annotations

def foo():
    pass
```

**Additional context**

If there are no imports then Black currently enforces exactly two empty lines between the module docstring and the first line of code. If there's no docstring then Black strips all leading whitespace. I could see an argument that it should be two empty lines between the module docstring and the first import to match the former behaviour, but I think no lines fits better with the general philosophy of the Black style.

**Comment by JelleZijlstra** [comment]
In #3932 we instead decided to add a single newline after the docstring.
