### ISSUE TITLE
Dont format dictionaries in Code (json)

### ISSUE THREAD

**Issue by Pymann** [psf/black#3905]
**Is your feature request related to a problem? Please describe.**

Its often problematic, that you format dictionaries with new comma at the end of each iterator, exg.:

{
"any_list": [ 
"hans", 
"franz",           <--- comma to much for json format
]
}

The Problem is, that you finally cant copy your dicionary into a json-file, because the syntax doesnt fit anymore.

**Describe the solution you'd like**

format dictionaries in a style, that obyes json syntax.

**Comment by hauntsaninja** [comment]
Sorry, Black is a Python formatter, not a JSON formatter. Use of trailing commas is a well-established part of Black's style and helps reduce diff size.
