### ISSUE TITLE
Support inline flags in test cases

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#3922]
Currently, our test cases are executed with different flags based on some combination of their filename and what directory they are in. I would prefer a system where we define the flags in a directive inline, e.g. like this:

```
# flags: --target-version=py38 --preview
1+1

# output
1 + 1
```

**Comment by Nandika-A** [comment]
Hello! Can I work on this issue?

**Comment by hauntsaninja** [comment]
Yes, no need to ask, just open a PR!
