### ISSUE TITLE
Long list formatted into each element occupies one row

### ISSUE THREAD

**Issue by paoxiaode** [psf/black#3935]
**Describe the style change**

For a long list, black will format it into each element occupies one row.

**Examples in the current _Black_ style**

Before black format

```python
idx = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19,
    20, 21, 22, 23, 24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39
]
```

After black format

```python
idx = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    27,
    28,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
]
```

**Desired style**

```python
idx = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19,
    20, 21, 22, 23, 24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39
]
```

**Additional context**

**Comment by hauntsaninja** [comment]
This is not an uncommon request, see e.g. https://github.com/psf/black/issues/1281. However, Black will not be changing its style here. Black tends to prefer consistently styling structures and reducing diffs where possible.

A good solution here is using `# fmt: off` and `# fmt: on` to surround these. That said I am sympathetic, wanting compact formatting is by far the most common reason I use format directives, particularly in numerical code. I wonder if a `# fmt: compact` directive could be a good solution here.

**Comment by paoxiaode** [comment]
thanks for your reply
