### ISSUE TITLE
Preview: Improved line breaks with trailing end of line comments

### ISSUE THREAD

**Issue by MichaReiser** [psf/black#4006]
I believe this is related to the improved line breaks preview-style. 

**Examples in the current _Black_ style**

The following is *blacked* code using preview styles (copied from the playground).

```python
aaaaaa = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
a["a"] = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
a = (
    aa
) = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
```

The example shows that whether the value gets parenthesized depends on the target:
* A name target: The value doesn't get parenthesized it is an unsplittable expression and it exceeds the line-length even when parenthesized.
* A subscript target: Parenthesizes the right to make the first line fit, regardless of whether the value fits. 
* A target list: It breaks the targets before breaking the value. 

**Desired style**

I would expect that the value always gets split first before the target with the "improved line breaks" preview style (multiple targets):

```python
a = aa = (
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
```

I would also expect that whether the right gets parenthesized or not doesn't depend on the target. Meaning Black should either format:

```python
aaaaaa = (
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
a["a"] = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
a = aa = (
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
```

The alternative is to only add the parentheses if it makes the expression fit, but it is then unclear to me how the multi-target assignments should be formatted in a consistent way:

```python
aaaaaa = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
a["a"] = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111

# Parenthesize because it makes the targets fit. Inconsistent with the other two assignments
a = aa = (
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)

# or break the targets first. Inconsistent with breaking the right side first
a = (
	aa
) = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111

```

**Context**

Black almost uses the proposed layout when the expressions (ignoring comments) exceed the line width:

```python
aaaaaa = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
)
a["a"] = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
)
a = (
    aa
) = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Open questions**

How to ensure consistency with`return`, `await`, and `yield` formatting. An expression that exceeds the line length doesn't get parenthesized; changing `a = aaa...` to `a = (\n    aaa...` would make the formatting of the two inconsistent. Should the formatting of `return`, `await`, and `yield` be changed to include the comment width and always parenthesize?

```python
return aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 111111

# vs 
aaaaaa = (
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
```

**Comment by henriholopainen** [comment]
[4010](https://github.com/psf/black/pull/4010) should handle also this at least partly, as now

```
a = (
    aa
) = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
```

becomes

```
a = aa = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # 11111111111111111111
)
```

**Comment by MichaReiser** [comment]
> I would also expect that whether the right gets parenthesized or not doesn't depend on the target. Meaning Black should either format:

Now that I'm about to implement this, I realize that this is kind of hard to achieve. The issue is that the decision on whether the left or right should break now depends on each other. We can't just say, okay, let's not break the left because the right will break because the right may then realise that there isn't enough space remaining to make it fit, so it formats itself without parentheses. However, it would have been possible to fit the value if one of the right sides split earlier.
