### ISSUE TITLE
Preview: handle more huggable immediately nested parens/brackets

### ISSUE THREAD

**Issue by yilei** [psf/black#4011]
**Describe the style change**

#3964 handled the most common case from #1811, and I'd like the following cases to be handled too:

```python
foo(
    (
        1,
        2,
        3,
    )
)

foo([
    [
        1,
        2,
        3,
    ]
])
```

See [playgroud](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADeAGddAD2IimZxl1N_WlkOE2WKNpiCxsiZ6ZIRL1cm3cr3OmQofsf9OUyzIBO_A83ZWkx59NLlC9fXK-w-pVBSBaFpfY2W8u9h4XGb9FVyhxmqoQVyfT5MsLdoUaBIqIvVCpha-di3Y3IZYwAAAJljAbaAgB-SAAGDAd8BAADjWOQZscRn-wIAAAAABFla).

**Desired style**

```python
foo((
    1,
    2,
    3,
))

foo([[
    1,
    2,
    3,
]])
```

**Additional context**

I'll send a PR if this proposal looks good.

**Comment by JelleZijlstra** [comment]
Sounds good, thanks!

**Comment by yilei** [comment]
Add two more cases that aren't function calls:

Before:

```python
nested_mapping = {
    "key": [
        {
            "a very long key 1": "with a very long value",
            "a very long key 2": "with a very long value",
        }
    ]
}

nested_array = [
    [
        1,
        2,
        3,
    ]
]
```

After:

```python
nested_mapping = {
    "key": [{
        "a very long key 1": "with a very long value",
        "a very long key 2": "with a very long value",
    }]
}

nested_array = [[
    1,
    2,
    3,
]]
```
