### ISSUE TITLE
Black explodes list unnecessarily with long variable name

### ISSUE THREAD

**Issue by hauntsaninja** [psf/black#4029]
Black explodes the list in the following:
```
def foo():
    assert long_long_long_long_var == [
        0, 1, 2, 3, 4, 10, 11, 12, 13, 14, 15, 16, 17, 18
    ]
```
If you rename the variable to something short, Black no longer explodes the list.

**Comment by dankrzeminski32** [comment]
Hi @hauntsaninja, I've likely misinterpreted the docs but isn't this the expected behavior? 

> If a data structure literal (tuple, list, set, dict) or a line of “from” imports cannot fit in the allotted length, it’s always split into one element per line.

Is it supposed to explode the list only after it exceeds the limit on the new line? Like so, 

```def foo():
    assert long_long_long_long_var == [
        0, 1, 2, 3, 4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 13, 14, 15, 0, 1, 2, 3, 4, 10, 11, 12, 13, 14, 15, 16, 17, 18
     ]

**Comment by hauntsaninja** [comment]
Hmm, you're right. I think I just expected it to mirror the logic for e.g. function calling
