### ISSUE TITLE
pyproject.toml target-version support is undocumented

### ISSUE THREAD

**Issue by adamchainz** [psf/black#4031]
**Is this related to a problem? Please describe.**

Issue #3124 / PR #3219 added support for parsing `--target-version` from `[project.requires-python]` in `pyproject.toml`. But I can’t find any mention of this in the [docs for `--target-version`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#t-target-version) or elsewhere.

**Describe the solution you'd like**

A paragraph describing the support and limitations, with an example.

**Describe alternatives you've considered**

Keeping this a secret feature 👎

**Additional context**

n/a

**Comment by hugovk** [comment]
Good idea, see also:

* https://ichard26.github.io/blog/2023/01/black-23.1.0/#better-default-for---target-version-if-pep-621-python-requires-is-available
* https://github.com/psf/black/blob/main/CHANGES.md#configuration-4
