### ISSUE TITLE
pre-commit: "Expected one of commit, commit-msg, manual, ..." since 23.11.0

### ISSUE THREAD

**Issue by martin-thoma** [psf/black#4065]
**Describe the bug**

When the pre-commit hook is installed and I commit, I get:

```
An error has occurred: InvalidManifestError: 
==> File /home/martin/.cache/pre-commit/repolc31_gpb/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

**To Reproduce**

```
$ python --version
3.11.1

$ python -m venv venv
$ source venv/bin/activate

$ vim .pre-commit-config.yaml
# Add this:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black  

$ echo "a = 'b'" > c.py

$ git init
$ git add .pre-commit-config.yaml c.py
$ pip install pre-commit
$ pre-commit install

$ pre-commit --version
pre-commit 3.5.0

$ git commit -m "Example"
```

The resulting error is:

```
An error has occurred: InvalidManifestError: 
==> File /home/martin/.cache/pre-commit/repolc31_gpb/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

**Expected behavior**

A pre-commit fixes `c.py`

**Environment**

- Black's version: 23.11.0
- OS and Python version: Linux / Python 3.11.1

**Additional context**

https://github.com/psf/black/pull/3940

**Comment by MT-Cash** [comment]
The [`minimum_pre_commit_version`](https://pre-commit.com/#top_level-minimum_pre_commit_version) should get updated to 3.2.0 at least.

**Comment by davidculley** [comment]
Does executing [`pre-commit clean`](https://pre-commit.com/#pre-commit-clean) fix the issue?

**Comment by davidculley** [comment]
@Wolfcast: Your error message says `Expected […] commit` which hints at a version of `pre-commit` older than version 3.2.0 — since version 3.2.0, it's `pre-commit` instead of just `commit` — and your error message continues with `but got: 'pre-commit'` because black 23.11.0 now requires a version of `pre-commit` that is newer than 3.2.0.

**Comment by Wolfcast** [comment]
Yeah I deleted my comment before your reply :) The global pre-commit was up to date but not the one in my venv. `pip install --upgrade pre-commit` in the venv fixed it for me. My bad! Thanks!

**Comment by andrewmwilson** [comment]
IMO this solution is preferable https://github.com/psf/black/pull/4041

The current version of Debian uses pre-commit 3.0.4, so it would be nice for it to work on that.

https://packages.debian.org/bookworm/pre-commit

**Comment by marcindulak** [comment]
Ubuntu 22.04 LTS (jammy) has pre-commit 2.17.0 https://packages.ubuntu.com/jammy/pre-commit

**Comment by davidculley** [comment]
What am I missing @andrewmwilson @marcindulak, why can't Debian/Ubuntu users not execute `pip install --user pre-commit` to get a current version of `pre-commit`?

**Comment by marcindulak** [comment]
> What am I missing @andrewmwilson @marcindulak, why can't Debian/Ubuntu users not execute `pip install --user pre-commit` to get a current version of `pre-commit`?

In hobby projects it's possible to pull packages from the internet, but in enterprises someone with required permissions would need to modify CI systems and developer machine images to include that change.

Additionally, a custom installation of pre-commit brings additional packages (see example below), and those would create a liability by extending the need of scanning them for vulnerabilities and patching, while those tasks are normally delegated to the operating system vendor
```
python3 -m venv venv
. venv/bin/activate
python3 -m pip install pre-commit
...
Successfully installed cfgv-3.4.0 distlib-0.3.8 filelock-3.13.1 identify-2.5.33 nodeenv-1.8.0
platformdirs-4.1.0 pre-commit-3.5.0 pyyaml-6.0.1 virtualenv-20.25.0
```

**Comment by Seluj78** [comment]
Still getting the error after a `pre-commit clean` and a `pip install --upgrade pre-commit`.

**Comment by wiseaidev** [comment]
For `poetry` bros, remove it first:

```bash
$ poetry remove pre-commit
Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 0 installs, 0 updates, 6 removals

  • Removing cfgv (3.4.0)
  • Removing identify (2.5.33)
  • Removing nodeenv (1.8.0)
  • Removing pre-commit (2.21.0)
  • Removing pyyaml (6.0.1)
  • Removing setuptools (69.0.2)

Writing lock file
```

Then add it:

```sh
$ poetry add pre-commit --group dev
Using version ^3.6.0 for pre-commit

Updating dependencies
Resolving dependencies... (0.8s)

Package operations: 6 installs, 0 updates, 0 removals

  • Installing setuptools (69.0.2)
  • Installing cfgv (3.4.0)
  • Installing identify (2.5.33)
  • Installing nodeenv (1.8.0)
  • Installing pyyaml (6.0.1)
  • Installing pre-commit (3.6.0)

Writing lock file
```

**Comment by hauntsaninja** [comment]
Note for anyone currently broken by this, you can try using [psf/black-pre-commit-mirror](https://github.com/psf/black-pre-commit-mirror) instead. This never received the change in https://github.com/psf/black/pull/3940, so should still work with older versions of pre-commit. It'll also make black like 2x faster :-)

**Comment by davidculley** [comment]
> In hobby projects it's possible to pull packages from the internet, but in enterprises someone with required permissions would need to modify CI systems and developer machine images to include that change.
> 
> Additionally, a custom installation of pre-commit brings additional packages (see example below), and those would create a liability by extending the need of scanning them for vulnerabilities and patching, while those tasks are normally delegated to the operating system vendor

Thanks for the explanation @marcindulak and sorry for the late answer.

I haven't thus far found myself in such a situation, therefore I wasn't aware of the issues you describe. Now I can better put myself in your shoes, thank you.

**Comment by marcindulak** [comment]
The exact way is up to your particular devcontainer setup, willigness to rely on the Internet access during the installation, and to introduce more dependencies on various tools. The particular solution is more of a topic to figure out with help of LLM guesses, than a longer discussion in this issue.

pre-commit is a Python package, so it's installable for local use with various Python virtual environment management tools, like venv https://github.com/psf/black/issues/4065#issuecomment-1857399133 using in devcontainer's Dockerfile command `RUN cd /home/${USER} && python -m venv venv && . venv/bin/activate && python -m pip install pre-commit`

Activation of venv can be automatically performed by the shell init script appended in devcontainer's Dockerfile command `RUN echo "if [ -f /home/${USER}/venv/bin/activate  ]; then . /home/${USER}/venv/bin/activate; fi" >> /home/${USER}/.bashrc`. 
It's also possible to setup direnv to automatically load the venv's activate script upon entering a directory.

There are also other ways of install pre-commit into devcontainer, if you are open to rely on https://containers.dev/features.
