### ISSUE TITLE
Avoid removing whitespace for parenthesized walrus in subscripts

### ISSUE THREAD

**Issue by MichaReiser** [psf/black#4078]
**Describe the bug**

Related to the new [`walrus_subscript`](https://github.com/psf/black/pull/3823) preview style and has previously been mentioned in [this comment](https://github.com/psf/black/pull/3823#issuecomment-1656883294)

Black removes whitespace around parenthesized walrus operators but preserves them for other binary operations:

```python
x[(a + 4) :]
x[(a := 4):]
```

I would expect that the walrus operator gets formatted the same as any other binary operator:

```python
x[(a := 4) :]
```

**To Reproduce**

See [Playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AChAGhdAD2IimZxl1N_WmyxQ1GdQjZJ-UrtnkUC9HhNd4a2tNtFILOWrdvGricHZE-n29mbSRpvTO-8jSUqWnUW6pkgfj_XJzMl2ywm3QXwbYWMn5Ez-EO1iE4wEv-NmSwVw_NqslDlLQF4NJ0AAAboJbMfO3D7AAGEAaIBAAAaELSdscRn-wIAAAAABFla)

**Comment by JelleZijlstra** [comment]
Agree we should change this.
