### ISSUE TITLE
Single-argument function includes trailing comma inconsistently

### ISSUE THREAD

**Issue by charliermarsh** [psf/black#4080]
**Describe the bug**

When a single-argument function definition breaks across multiple lines, Black will add a trailing comma (after the argument) in some cases but not others.

**To Reproduce**

For example, given the following Black adds a trailing comma after the annotation on `x` in the first case, but not the second, third, or fourth:

```python
# Black inserts a trailing comma after the first argument's annotation here.
def long_function_name_goes_here(
    x: Callable[List[int]]
) -> Union[List[int], float, str, bytes, Tuple[int]]:
    pass

# But not here, or in any of the below.
def long_function_name_goes_here(
    x: Callable[[str, Any], int]
) -> Union[List[int], float, str, bytes, Tuple[int]]:
    pass

def long_function_name_goes_here(
    x: Callable[List[int, str]]
) -> Union[List[int], float, str, bytes, Tuple[int]]:
    pass

def long_function_name_goes_here(
    x: Callable[List[int], str]
) -> Union[List[int], float, str, bytes, Tuple[int]]:
    pass
```

So the inclusion of the trailing comma seems to depend on the _content_ of the annotation (but not its length). One observation: Black omits the trailing comma when the _annotation_ itself contains a comma.

(Here's the same example in the [playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ALeARBdAD2IimZxl1N_Wg0-BMXRAiYxkRLgmwJgPbucmCxkyRhldo2eOEP-o3QLvZCqxRaHz-pxcr5e3vmEsE5PexxyCAYlXUhuHdiFWHwBfgyaZvRwMoj2wQ47aKPkoaoLpBx_292oceqgoACgNq4DptlCROTZX4Eln6rV3lGi5g7Um9MqWVVSz_1GDauhC_vI-6bkxdvRzj5cV36sYL4CPmW3fLYyM7uoexyWDuQeReA2kZtfSGON0Q5YljRYNYMui5uN8TEzCh10LXJKOx-7YxN5UkfH0vF0DLyZnL_Aezfs1NQuNXMHjtms5vCJ4VLZ14R7hxT5f2xZXmin_qRA4qElJuYA1ZQ5Zj-gIT1of6fgPaf_AHHe-wyOt36MAAGsAt8FAAAMPbevscRn-wIAAAAABFla).)

**Comment by drhagen** [comment]
I would argue that Black **preserving the trailing comma** would be more consistent with the overall behavior of Black. For example, both of these function _calls_ are acceptable to Black:

```
# Preserves lack of trailing comma
really_really_really_really_really_long_name(
    really_really_really_really_really_long_name
)

# Preserves trailing comma
really_really_really_really_really_long_name(
    really_really_really_really_really_long_name,
)
```

The reason for this is that lists of things is one of the places that Black gives users a choice of formatting: (1) I want as few of lines as possible, (2) one line per item. This creates an ambiguity when there is only one element: Did the user intend to choose the everything-on-one-line option (no comma) or did the user intend to choose the split-elements-across-lines option (trailing comma)? Everywhere else, Black resolves this ambiguity by preserving trailing commas, and I think it should do that in function definitions too, even single parameter functions.

**Comment by JelleZijlstra** [comment]
@drhagen possibly, but we already add the trailing comma for non-annotated parameters, and if nothing else we should be consistent. 

```
% black  -l 20 -c 'def some_call(aaaaaarg): pass'
def some_call(
    aaaaaarg,
):
    pass
```
