### ISSUE TITLE
Black fails to format long string literals not containing any whitespace characters

### ISSUE THREAD

**Issue by jhelgert** [psf/black#4081]
**Describe the bug**

A Python file containing a string literal assignment longer than the line length limit is not reformatted if the string literal doesn't contain any whitespace characters.

**To Reproduce**

For example, take this code `example.py`:

```python
long1 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
long2 = "This is a long line that is longer than 88 characters. I expect Black and Ruff to shorten this line length."
```

Run Black:

```bash
$ black --preview example.py
reformatted example.py

All done! ✨ 🍰 ✨
1 file reformatted
```

**Expected behavior**

I expect black to shorten both line lengths to less than the length limit. However, only the second string literal is formatted:

```python
long1 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
long2 = (
    "This is a long line that is longer than 88 characters. I expect Black and Ruff to"
    " shorten this line length."
)
```

**Environment**

- Black's version: black, 23.11.0 (compiled: yes)
- OS and Python version: macOS Ventura 13.5, Python 3.11.6

**Additional context**

Related issue: #1802

**Comment by JelleZijlstra** [comment]
I don't think we should attempt to split strings without whitespace. If there is no obvious place to split, then the result is often going to be unintuitive.
