### ISSUE TITLE
Dependencies for `black[d]` are being installed by default

### ISSUE THREAD

**Issue by BryceStevenWilley** [psf/black#4107]
**Describe the bug**

Minor bug, but it seems that the extra dependencies for the `d` extra are being installed by default on 23.12.0. This can cause some issues on docker containers and such where `gcc` isn't installed, as the extra dependencies (`aiohttp`, and `frozenlist`) don't seem to have wheels.

**To Reproduce**

On a non-windows machine (I've done it on Ubuntu, and it also seems to happen on Linux github action runners) Make a new venv, source it, and install black:

```bash
python3 -m venv .venv
source .venv/bin/activate
pip install black
```

It will install requirements from the `d` extra as well; 

```
Installing collected packages: platformdirs, packaging, tomli, multidict, idna, yarl, attrs, frozenlist, async-timeout, aiosignal, aiohttp, typing-extensions, click, pathspec, mypy-extensions, black
Successfully installed aiohttp-3.9.1 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 black-23.12.0 click-8.1.7 frozenlist-1.4.0 idna-3.6 multidict-6.0.4 mypy-extensions-1.0.0 packaging-23.2 pathspec-0.12.1 platformdirs-4.1.0 tomli-2.0.1 typing-extensions-4.9.0 yarl-1.9.4
```

**Expected behavior**

It shouldn't install with the `aiohttp`, `frozenlist`, and `multidict` dependencies.

**Environment**

- Black's version: 23.12.0, pip version 20.0.2
- OS and Python version: Python 3.8.10, Ubuntu 20.04, though it also happens with github runners and the latest python-3 docker container on 22.04, see https://github.com/SuffolkLITLab/docassemble-AssemblyLine/actions/runs/7182833153/job/19560217190 

**Additional context**

First seen in https://github.com/rickstaa/action-black/issues/18

I think it has to do with: https://github.com/psf/black/commit/85b1c71a3445f32860d7b139ae4de4824f6ae102; in my pip logs, the new restrictions seem to show up as:

```
Collecting aiohttp>=3.7.4; sys_platform != "win32" or implementation_name != "pypy" and extra == "d"
```

i.e., the `extra == "d"` is ignored in favor of the sys platform not being windows, so the extras are always installed. I think a quick fix would be to wrap the extras in parenthesis. Happy to make a quick PR for that.

**Comment by JelleZijlstra** [comment]
Good catch, thanks! Seems like a bug in hatch?

We should still presumably work around it by adding parentheses, though.

**Comment by sigma67** [comment]
`isort` had a similar issue with their last minor release (dev dependencies distributed as default)

Although probably unrelated cause (they use poetry)

**Comment by mwgamble** [comment]
@JelleZijlstra Will there be a `23.12.1` release to deal with this?

**Comment by hauntsaninja** [comment]
Jelle's unavailable. I'll try to make a release in the next few days (but I haven't cut a Black release before / am currently travelling, so it'll happen when it happens)

**Comment by cooperlees** [comment]
I can cut one now if people want and am around to try help if things fail.

**Comment by sigma67** [comment]
imho it should be fixed asap because it makes latest black impossible to install on Python 3.12.

This is because multidict<7 is incompatible with 3.12. It will yield this error:

```
multidict/_multidict.c:1:10: fatal error: Python.h: No such file or directory
          1 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
```

**Comment by hauntsaninja** [comment]
Thanks to cooperlees, 23.12.1 is now a thing!

**Comment by cooperlees** [comment]
Happy Holidays!
