### ISSUE TITLE
What is "Incorrectly formatted" ?

### ISSUE THREAD

**Issue by tfrokt** [psf/black#4111]
_Python syntax has changed? Or it hasn't? This line was not flagged in the past._ 

It would be nice to add a bit more info to that error message (e.g. a link or at least a code what exactly is violated). This way the message is more annoying than helpful.

![Screenshot 2023-12-15 at 10 07 24 am](https://github.com/psf/black/assets/82917641/42833680-de26-4ded-9598-b981a8121a66)

![Screenshot 2023-12-15 at 10 07 41 am](https://github.com/psf/black/assets/82917641/29c53938-95de-49b1-8131-3d592f57f130)

**Comment by hauntsaninja** [comment]
We don't control your IDE integration. I recommend setting up your IDE so that it automatically runs black on save, rather than making you guess what black would reformat your code to

**Comment by tfrokt** [comment]
@hauntsaninja not sure if you understood my request.

It shouldn't make any difference if black runs "on save" or "in background" the message would be the same.

I am saying the message is not helpful as it is.

Also, I ran black to reformat my file (maybe that's what you are suggesting):

```
All done! ✨ 🍰 ✨
1 file reformatted.
```

The line hasn't changed and the error is still there.

**Comment by hauntsaninja** [comment]
Black does not issue errors, it's an autoformatter, not a format checker. 

The issue / message is in whatever IDE integration you're using. We don't recommend integrations that report errors.

**Comment by tfrokt** [comment]
Got it. Then my IDE (VSCode) should not show "Incorrect formatting" coming from black - as shown in the second screenshot. I'll try to trace down where that comes from.
