### ISSUE TITLE
Black 23.12.0 requires aiohttp when the d extra isn't installed

### ISSUE THREAD

**Issue by relud** [psf/black#4120]
**Describe the bug**

pip thinks that Black 23.12.0 requires aiohttp when the d extra isn't installed, and that wasn't the case for Black 23.11.0

**To Reproduce**

```sh
$ python3.11 -m venv venv
$ venv/bin/pip install black==23.12.0
```

The resulting installed packages:

```sh
$ venv/bin/pip list
Package         Version
--------------- -------
aiohttp         3.9.1
aiosignal       1.3.1
attrs           23.1.0
black           23.12.0
click           8.1.7
frozenlist      1.4.1
idna            3.6
multidict       6.0.4
mypy-extensions 1.0.0
packaging       23.2
pathspec        0.12.1
pip             23.3.1
pipdeptree      2.13.1
platformdirs    4.1.0
setuptools      68.2.2
yarl            1.9.4
```

**Expected behavior**

when installing `black==23.11.0` this is the resulting installed packages:

```
$ rm -rf venv
$ python3.11 -m venv venv
$ venv/bin/pip install black==23.11.0
$ venv/bin/pip list
Package         Version
--------------- -------
black           23.11.0
click           8.1.7
mypy-extensions 1.0.0
packaging       23.2
pathspec        0.12.1
pip             23.3.1
platformdirs    4.1.0
setuptools      68.2.2
```

**Environment**

- Black's version: 23.12.0
- OS and Python version: macos 14.2, python 3.11.6 installed via homebrew

```sh
$ python --version --version
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
```

**Additional context**

The only changes to dependencies between 23.11.0 and 23.12.0 appear to be here:
https://github.com/psf/black/compare/23.11.0...23.12.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R79-R80
> ```diff
> d = [
> -  "aiohttp>=3.7.4",
> +  "aiohttp>=3.7.4; sys_platform != 'win32' or implementation_name != 'pypy'",
> +  "aiohttp>=3.7.4, !=3.9.0; sys_platform == 'win32' and implementation_name == 'pypy'",
> ]
> ```

It's not a problem if this is intended behavior, it just seemed suspicious when I saw a network library being installed for a tool that I didn't think needed it.

**Comment by ChrisLovering** [comment]
This is solved by https://github.com/psf/black/commit/8fec1c30855890cc9cfce5ae6d633a1c1a21d724. The conversation around this, including releasing it, is in https://github.com/psf/black/issues/4107

**Comment by relud** [comment]
ah, my bad. thank you!

**Comment by hauntsaninja** [comment]
This was due to an issue in hatch (the build backend Black uses). Thanks to BryceStevenWilley and cooperlees, 23.12.1 should have this fix
