### ISSUE TITLE
Line too long: Dictionary key-value pair

### ISSUE THREAD

**Issue by ghost** [psf/black#413]
Hey,

with `black, version 18.6b4` I am getting two lines within dict merged resulting in line exceeding provided limit.

`black --py36 --line-length 80 file`

gives:

```
@ settings.py:153 @ REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        'some stuff here'
    ),
-    "DEFAULT_PAGINATION_CLASS":
-        "rest_framework.pagination.LimitOffsetPagination",
+    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": some_value_here,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
```

Line in question is 82 characters long.

Is that a bug or intended behaviour for dicts?

**Comment by zsol** [comment]
Looks like black is failing to put parenthesis in there. Smells like a bug, thanks for reporting!

**Comment by ambv** [comment]
In the mean time, if you put the value in parentheses manually, Black will keep them. We need to figure out a way to do it nicely automatically without over-extending.

**Comment by felix-hilden** [comment]
Can confirm this still happens even with experimental string processing. Here's a [playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADuAJldAD2IimZxl1N_WkRsVtdQb4Tqd369cLgVs2olGh6SvD2RoeO_pRyVR1-p6GjbePfZyz1OXc9FNC69osvnPlfj0vyQ96cj79y43dGmk-poMtQ2_9ny3ICI0V4fnqmz8X0j5gT55n7Jk38NkCkBNWPidOcAji7FxJav0FusleoJowj7JecC4ZYqmYGll0cPFr8MFdZWDVJn4dkmMAAAAADzYa8Si-ESDgABtQHvAQAA8kTsO7HEZ_sCAAAAAARZWg==) for convenience.

**Comment by berzi** [comment]
Any update on a solution for this bug?

**Comment by felix-hilden** [comment]
Any updates will be posted here!

**Comment by govindrai** [comment]
@felix-hilden I am running into this as well. I haven't contributed to black before, but I am thinking to contribute. I have two questions: has this been prioritized? and is this a good candidate a good first issue? It hasn't been resolved since 2018, could be due to complexity?

**Comment by felix-hilden** [comment]
@govindrai You're welcome to give it a go! It hasn't been prioritised, and could be a hard one, but we'll try to help if you create a PR draft 👍

**Comment by JelleZijlstra** [comment]
This is fixed on main in preview mode:
```
% black -c '''REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "some stuff here"
    ),
    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": some_value_here,
}''' --preview -l 80
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": "some stuff here",
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.LimitOffsetPagination"
    ),
    "PAGE_SIZE": some_value_here,
}
```
