### ISSUE TITLE
Installation and update of black over a docker container

### ISSUE THREAD

**Issue by BollinaVenkataManoj** [psf/black#4136]
Hey ,
i am using black as a pre-commit over a container and i am trying to install and update this plugin to use it over a application.

**this is my config
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        name: Blacken python source
        additional_dependencies: ["click==8.0.2"]**
        
     
I am getting an error asking for some stage. i tried adding a stage parameter also but it is not picking it. any suggesting that you can give.

**Updating https://github.com/psf/black ... [INFO] Initializing environment for https://github.com/psf/black.

==> File /root/.cache/pre-commit/repomskuoqri/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, prepare-commit-msg, push but got: 'pre-commit'**

**Comment by hauntsaninja** [comment]
20.8b1 is an extremely old version of Black, please update to something newer.

Note there's a similar issue affecting the latest release, see https://github.com/psf/black/issues/4065 for some details
