### ISSUE TITLE
Add option for single quoted strings as default

### ISSUE THREAD

**Issue by nathanneuro** [psf/black#4144]
**Is your feature request related to a problem? Please describe.**

I'd quite like to have an option to have single-quoted strings be the default.

Problem as described by the Blue formatter ( https://blue.readthedocs.io/en/latest/ ):
"blue defaults to single-quoted strings. This is probably the most painful black choice to our eyes, and the thing that inspired blue. We strongly prefer using single quoted strings over double quoted strings for everything except docstrings and triple quoted strings (TQS). Don’t ask us why we prefer double-quotes for TQS; it just looks better to us! For all other strings, blue defaults to single quoted strings. In the case of docstrings, those always use TQS with double-quotes.
...
We’d prefer not to fork or monkeypatch. Instead, our hope is that eventually we’ll be able to work with the black maintainers to add just a little bit of configuration and merge back into the black project.
"

**Describe the solution you'd like**

Be able to specify an option to use single-quotes as the default instead of double-quotes (except for triple quoted strings). Much like the 'line length' option, something that people can optionally specify.

**Describe alternatives you've considered**

1. using blue formatter instead of black.
2. gritting my teeth and bearing it.

**Comment by JelleZijlstra** [comment]
I would suggest alternative 2.

Black's philosophy is to minimize formatting options so that formatted code looks consistent and users don't have to worry about formatting minutiae. When I first watched @ambv present about Black, I was also surprised he chose double quotes, but the choice has served us well.
