### ISSUE TITLE
Formatting of long lines only work when line-length is specified 

### ISSUE THREAD

**Issue by howardwu1** [psf/black#4148]
Using Black Formatter extension on vs code which uses v23.10.1

for some reason I get no line formatting by default (of 79 characters) however things work when I declare line-length and any value (including the default of 79)

![image](https://github.com/psf/black/assets/61717594/f985d968-b739-476c-a1dc-a08ad7f80197)

I feel like this should be an easy bug to fix (by default just declare it with 79) not. But hopefully it will help those that got stuck with this issue https://github.com/psf/black/issues/1802

**Comment by hauntsaninja** [comment]
The default Black line length is 88 (this will not be changed).

Could you provide a repro of your issue using Black on the command line? This repo does not maintain the Black VSCode extension (see https://github.com/microsoft/vscode-black-formatter)

**Comment by howardwu1** [comment]
ah I thought the default would line up with the linter's complaints -- and yeah when I created a line that was over 88 characters and saved it all looked good -- thanks!
