### ISSUE TITLE
Black doesn't respect newlines between fmt: off and fmt: on

### ISSUE THREAD

**Issue by hauntsaninja** [psf/black#4171]
Black collapses
```
# fmt: off








# fmt: on
```

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACKAE1dAD2IimZxl1N_Wg0-Ef3tYndKG4aPyrE4Sd9Gy1qi76F8xcVocLWBR1-CimRr8K_hIYDUFLpJDUzaQEuAod9MzTDBWVLUYQQfu0-AHfDAAAAAANhGOUSRPNn2AAFpiwEAAACpbCSSscRn-wIAAAAABFla

**Comment by JelleZijlstra** [comment]
Duplicate of #2877
