### ISSUE TITLE
Weird behavior after version 24.x.x, 

### ISSUE THREAD

**Issue by Niorlys** [psf/black#4201]
**Describe the bug**
After upgrading to the latest version, when I rub `python -m black .`, I got files reformatted: 
![image](https://github.com/psf/black/assets/22604028/a0acf066-28b2-4e40-9771-fed13772a395)
 
![image](https://github.com/psf/black/assets/22604028/e2c14cc3-c8a8-4e7d-b50f-008e33e3cc3c)
 
Then, when I commit, it against reformat the files restoring them:
 
![image](https://github.com/psf/black/assets/22604028/ecc7bf84-6855-48eb-a6ce-f4c465175432)

Irrational behavior since the module reformats files and, in the next reformatting restores them.
**To Reproduce**
Using version 24.1.1, run `python -m black .` and then try committing the changes.

**Expected behavior**
If the code is already reformatted, the check in both cases, by `python -m black  --check` and after the commit should pass.
**Environment**
OS: Windows
Python's version: 3.10.8
Black's version:24.1.1

**Comment by JelleZijlstra** [comment]
You are likely running a different version of Black inside your pre-commit hook.
