### ISSUE TITLE
Black does not print errors with --quiet --check

### ISSUE THREAD

**Issue by galdor** [psf/black#4227]
Running Black with both `--quiet` and `--check` on a non-valid file leads to an exit status of 1 (correct) but no error being printed (unexpected).

Easy to reproduce, e.g. with

```python
def foo(): print("bar")
foo()
```

`python -m black --quiet --check test.py` exits with status 1 but does not print anything.

Reproduced with Black 23.12.1 and 24.1.1.

For `--quiet`, help output states:

> Stop emitting all non-critical output. Error messages will still be emitted

This is obviously incorrect.

`--quiet` should be the way to get no output on success and only errors on failure.

**Comment by JelleZijlstra** [comment]
I think this behavior is actually correct. The errors that are still printed are ones where Black itself runs into an error (i.e., it fails to format some file). But if some file needs reformatting, that's a perfectly normal part of the behavior of `--check`. I can easily imagine users running something like `black --quiet --check || echo "Some custom message"`.

**Comment by galdor** [comment]
I must be missing something: I do not want to print a custom message. I'd just like the same behaviour as the vast majority of analysis tools:

- Do not print anything on success (Black is not the only tool running during static checking, irrelevant output is distracting).
- Print what went wrong on failure.

With `--check` alone, you still get output on success. With `--check --quiet` you do not see what went wrong on failure.

If you prefer current options to keep the same behaviour, maybe adding a new flag would do the job? For example Curl has a similar behaviour where `--silent` hides errors; but one can add `--show-error` to still print errors and keeping other non-error messages silent.

Would adding `--show-error` (or `--show-errors`, `--print-errors`, I don't mind) be acceptable?

**Comment by galdor** [comment]
Thank you!
