### ISSUE TITLE
Blackd does not support all config options

### ISSUE THREAD

**Issue by giampaolo** [psf/black#4243]
While attempting to write a HTTP client for blackd to integrate into Sublime Text editor, I realized that blackd currently does not support the following `black.FileMode` options:

 ```
is_ipynb
python_cell_magics
unstable
enabled_features
```

The most important (for me at least) appears to be `enabled_features`, since it implies a list of further sub-options which are not configurable at the moment.

**Comment by JelleZijlstra** [comment]
Both `unstable` and `enable_unstable_features` are supported via the headers `X-Unstable` and `X-Enable-Unstable-Feature`: see https://black.readthedocs.io/en/stable/usage_and_configuration/black_as_a_server.html#protocol.

**Comment by JelleZijlstra** [comment]
No worries! You are right that the two ipynb-related options are missing from blackd. However, no one has specifically asked for them, so let's just leave those be for now.
