### ISSUE TITLE
Cannot parse a formatted string like f"{10 * ["a"]}"

### ISSUE THREAD

**Issue by jimmyzzxhlh** [psf/black#4246]
**Describe the bug**

The following code failed with a `Cannot parse` message.

```
a = f"{10 * ["a"]}"
```

**To Reproduce**

Take the above code, save to a file and run 

```sh
$ black <file_name>
```

The resulting error is:

error: cannot format test.py: Cannot parse: 1:14: a = f"{10 * ["a"]}"

**Expected behavior**

This is valid Python code and so black should be able to format it. 

**Environment**

- Black's version: 24.2.0
- OS and Python version: MAC / Python 3.12

**Comment by JelleZijlstra** [comment]
Duplicate of #3746
