### ISSUE TITLE
assertion with multi-line string needlessly spans multiple lines

### ISSUE THREAD

**Issue by Aran-Fey** [psf/black#4247]
**Describe the bug**

When an `assert` statement has a multi-line string, the condition is split across 3 lines for no reason.

**To Reproduce**

For example, take this code:

```python
assert some_var == expected_result, f"""
expected: {expected_result}
actual: {some_var}"""
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting output is:

```py
assert (
    some_var == expected_result
), f"""
expected: {expected_result}
actual: {some_var}"""
```

**Expected behavior**

The condition should remain as a single line.

**Environment**

- Black's version: [@ed770b](https://github.com/psf/black/commit/ed770b)
- OS and Python version: Whatever https://black.vercel.app uses

**Comment by Drachenfels** [comment]
Would not be marginally cleaner to re-format it to:

```
assert (
    some_var == expected_result,
    f"""expected: {expected_result}
    actual: {some_var}"""
)
