### ISSUE TITLE
Create URL links to actual PRs rather than simply referencing the PR number

### ISSUE THREAD

**Issue by gandhis1** [psf/black#4258]
The change log is immensely useful, however it makes reference to specific Github PRs and only mentions the PR number without actually linking to the issue.

I would like for the changelog to actually include links to the issue. It would be of great help to readers to be able to see the contextual discussion for a change, particularly for style changes.

https://black.readthedocs.io/en/stable/change_log.html

**Comment by JelleZijlstra** [comment]
That would be very useful; there's probably something we can do in Sphinx to transform the references to links. Contributions welcome!

Note the links are to PRs, not issues.

**Comment by sumezulike** [comment]
I've implemented this, but it requires https://github.com/executablebooks/MyST-Parser/pull/887, so waiting on that.
