### ISSUE TITLE
Add pipx installation in documentation

### ISSUE THREAD

**Issue by lebedevdes** [psf/black#4263]
Using pipx (https://pipx.pypa.io/stable/) to install Black globally can be a convenient approach for applying it across multiple projects, without the need to install it separately in each virtual environment or directly into the system's Python. Incorporating this suggestion into the installation instructions could benefit many users by providing a more versatile setup option.

**Comment by IsmartGaurav** [comment]
1. To get started install pipx on your system. For macOS you can use Homebrew by typing in the command brew install pipx. On Linux the installation steps differ based on the distribution. For Ubuntu you can use sudo install pipx while for Fedora you can use sudo dnf install pipx.

2. After installing pipx make sure that the paths are properly configured by running ensurepath. You may also run sudo ensurepath  global to enable actions, with the  global option.

3. Once you have set up pipx you can globally install Black using pipx. Simply enter the command pipx install black. This will set up an environment, for Black install the package and allow you to access the command globally.

**Comment by Samuel12451** [comment]
I have added the installation instruction to the README file.
