### ISSUE TITLE
Black cannot parse valid code

### ISSUE THREAD

**Issue by CanePlayz** [psf/black#4282]
**Describe the bug**

Black hits me with this error when trying to format something

```
error: cannot format ...\test.ipynb: Cannot parse: 4:31: plt.savefig(f"output/_{config["year"].replace("/", "_")}.png", bbox_inches="tight")

Oh no! 💥 💔 💥
1 file failed to reformat.
```

**To Reproduce**

Take the code below and try to format it from the command line

For example, take this code:

```python
import matplotlib.pyplot as plt

config = {"year": "2024"}
plt.savefig(f"output/_{config["year"].replace("/", "_")}.png", bbox_inches="tight")
```

And run it with these arguments:

```sh
$ black file.ipynb
```

**Expected behavior**

Parse the code fine as it is valid Python code

**Environment**

- Black's version: 24.3.0
- OS and Python version: Windows 11, Python 3.12.2

**Additional context**

**Comment by AlexWaygood** [comment]
Hi! This issue is a duplicate of #3746. Note that Python will actually fail to parse your code unless you're using Python 3.12+; this syntax is a pretty new feature :-)

**Comment by CanePlayz** [comment]
@AlexWaygood Ah, I didn't see that it was related to that at first, thanks! :)
