### ISSUE TITLE
line-length is not working as intended

### ISSUE THREAD

**Issue by gjambaisivanandham** [psf/black#4300]
I am using black version `24.3.0` and have set `line-length = 88` in my config file, however running `black .` command doesn't modify the lines of code that are over 88 characters.

Ex: 
Before running black
```str = "this is the longest text in the history of mankind that I have seen in the world for all the good and bad things" ```

After running black the result is still the same.  I don't see any error it says `x file(s) left unchanged`. 

Here is my config file
```[flake8]
max-line-length = 88
extend-ignore = E203, W503, W291
exclude = .git,__pycache__,./.venv

[tool.black]
line-length = 88```

python version: `3.11.6`

**Comment by RedGuy12** [comment]
Long strings are currently unaffected by the current Black stable style. You can use the `--unstable` flag to enable it and other unstable/preview features, [as described in the documentation](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-string-processing). However, this particular feature may not stay around for much longer - see #4208
