### ISSUE TITLE
Black fails with match-case statement with multiple branches

### ISSUE THREAD

**Issue by shahwan42** [psf/black#4323]
**Black https://github.com/psf/black/commit/735733**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFwAKhdAD2IimZxl1N_WlXpD4EPou_pxAAGTQANWgFI5m30NZJLx8Ui5CAauZKN9It-K0eTlwOHkP9iS03Hm2obkF2uCJ4yl2UhC-jLMbUaSh5p6EX1qu6wudmzr5pJq_CicfNySkKbr8t5UIQhiylDjDm0k4HReCn738T-YZTJTD0upjakVAup9vr9MAoQFrFMefVw0XH95grrx4--4nTR9bXZxujQmEmK_3VKOQAnj6LNJImZdwABxAHxAgAAYwQSSbHEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
condition = "condition"

def test_multiple_match_cases():
    match condition:
        case "1st case":
            return "1st result"
        case "2nd case":
            return "2nd result"
        case _:
            return "default result"

```

## Output

```python
cannot use --safe with this file; failed to parse source file AST: invalid syntax (<unknown>, line 4)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```

## Expected

**Comment by JelleZijlstra** [comment]
Works fine for me locally running Black under Python 3.12 with `black -t py311 matchc.py`. The playground may be running an earlier version of Python; not sure.

**Comment by shahwan42** [comment]
Yes, I changed the target version, and it worked. Thank you. 🙏
