### ISSUE TITLE
Black not deleting unnecessary brackets 

### ISSUE THREAD

**Issue by tkozuch** [psf/black#4333]
Hi.

Not sure if this is a bug or more of a feedback request, but was just wondering about certain thing.
**Describe the bug**

If writing a logical statement in Python, black doesn't delete unnecessary brackets.

**To Reproduce**

For example, take this code:

```python
a = (not False) or True
```

after formatting with black, the brackets stay

Is this an expected behavior?

isn't the above code, identical to:

```python
a = not False or True
```

As far as I remember black deleted unnecessary brackets in other places, shouldn't it also delete them here?

(Forgive me if it's the rustiness of my Python knowledge and the 2 above aren't really identical)

**Environment**

Black version: 24.4.1

**Additional context**

**Comment by tkozuch** [comment]
thank you. that calls for a close. 

was wondering if in some way I'm not getting something wrong:P

**Comment by JelleZijlstra** [comment]
There's several contexts where we currently don't remove parentheses though we probably should; look at https://github.com/psf/black/labels/F%3A%20parentheses for some examples.

But @RedGuy12 is right that in this specific case we intentionally keep the parentheses.
