### ISSUE TITLE
Strings not being formatted by Black

### ISSUE THREAD

**Issue by krusion** [psf/black#4356]
**Describe the bug**

Strings longer than my set character limit (79) don't get formatted like the rest of the code.  

**To Reproduce**

For example, take this code:

```python
string = "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test"
```

**Expected behavior**

A string split over 2 lines. 

**Environment**

- Black's version: v2024.2.0
- OS and Python version: Windows 10, Python 3.12.2. Running in VS code

**Additional context**

I saw posts about this being fixed by adding "--preview" Argument. That didn't help. However, read on multiple issues that it will be the default setting starting in 2024. 

These are my settings: 
```
"editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "black-formatter.args": [
        "--line-length",
        "79",
        "--preview",
    ],

    "editor.codeActionsOnSave": {
        "source.organizeImports": "explicit"
    },
```

Should this also work with comments or just strings?

**Comment by RedGuy12** [comment]
> I saw posts about this being fixed by adding "--preview" Argument. That didn't help. However, read on multiple issues that it will be the default setting starting in 2024.

That was the case for many preview formats, however this specific one was moved under the new `--unstable` flag instead. See also #4208

**Comment by krusion** [comment]
I see! I'm a little bit confused, so what's the argument now if I want to test if it'll help me or not? Like what should I add in my settings file?

**Comment by JelleZijlstra** [comment]
You can add `unstable = true`. However, at this point we're likely to drop this feature (see the issue @RedGuy12 linked).
