### ISSUE TITLE
Error: Invalid value for 'SRC ...': Path '...' does not exist.

### ISSUE THREAD

**Issue by dan-auer** [psf/black#4369]
[x] Update Black's version if a newer release exists: `pip install -U black`

**Describe the bug**

Black fails if it is executed on a file whose path contains a space.

**To Reproduce**

![grafik](https://github.com/psf/black/assets/70216662/87fbfeaf-ee0a-4cc2-992c-905633c091f5)

![grafik](https://github.com/psf/black/assets/70216662/87fa065c-dad9-462c-b275-d21f49a63e3a)

The resulting error is:

> Error : Invalid value for 'SRC ...': Path 'with' does not exist.

**Expected behavior**

It works on files whose path has spaces.

**Environment**

- Black's version: black-24.4.2
- OS and Python version: Win10 / Python 3.11.1

**Comment by leonardosantosdev** [comment]
Hi dan

I tried the same and it worked here.

Check how i ran:
![image](https://github.com/psf/black/assets/44507099/d7b3a962-8e82-40a9-a53f-957185f7a8c9)

Hope this helps

**Comment by hauntsaninja** [comment]
Yeah, this is related to your shell, not Black. Quoting your path should work.
