### ISSUE TITLE
import asyncio

### ISSUE THREAD

**Issue by savinay95n** [psf/black#4371]
[command-failed] Error when formatting: ASTSafetyError: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.

It is a vscode lint issue. The code still runs with this import.

**Comment by JelleZijlstra** [comment]
Could you be more specific about the issue you are seeing?

**Comment by savinay95n** [comment]
import asyncio is creating an error on phabricator when testing. It is a formatting error, and this is the message I get: 
Error when formatting: ASTSafetyError: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /data/sandcastle/temp/skycastle/blk_h_mz0g4b.log

You can check this Diff: [D57805913](https://www.internalfb.com/diff/D57805913)

**Comment by JelleZijlstra** [comment]
Your link appears to go to an internal Meta page. Black can definitely format the line `import asyncio`.

**Comment by hauntsaninja** [comment]
Feel free to re-open if you can provide a repro and the Black version you're using
