### ISSUE TITLE
Black fails to format triple quoted string with a new line in f-string.

### ISSUE THREAD

**Issue by apes0** [psf/black#4375]
**Describe the bug**

Black fails to format an f-string, containing a triple quoted string, that has a new line in it.

**To Reproduce**

For example, take this code:

```python
a = f'''{"""
"""}'''
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

>error: cannot format a.py: Cannot parse: 1:9: a = f'''{"""

**Expected behavior**

The file should be formatted. I am not sure how this should get formatted though. The code is valid for both versions of python that i tested.

**Environment**

- Black's version: 24.4.2
- OS and Python version: Ubuntu 24.04 and Python 3.12/3.10 (fails on both)

P.S.: This seems somewhat similar to #4350?

**Comment by vetedde** [comment]
Is problem actual?
![image](https://github.com/psf/black/assets/26706854/76dcbd67-45a3-40cf-985e-a100ff489ccc)

**Comment by apes0** [comment]
Hmm...
Still throws an error for me.

python 3.10:
![image](https://github.com/psf/black/assets/54032987/04bc6421-5743-4c85-b107-ffd52a77295b)

python 3.12:
![image](https://github.com/psf/black/assets/54032987/27acc2cb-f04a-4c62-805a-bf70a1fc5737)

Which version of black are you using?

**Comment by tusharsadhwani** [comment]
This has been fixed in the current release.

**Comment by tusharsadhwani** [comment]
This is fixed on `main`, but hasn't been released yet.

**Comment by hauntsaninja** [comment]
Fixed by #4339
