### ISSUE TITLE
Black produces invalid code for assignment with over-long starred expression

### ISSUE THREAD

**Issue by MichaReiser** [psf/black#4376]
**Describe the bug**
Black produces invalid code for assignments with an overlong starred expression value because it parenthesizes the starred expression.

**To Reproduce**

[Playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE7AGVdAD2IimZxl1N_WjQmO9f-zmHx38Ng-jyvLViFwS2IOr2rDcRCBP45669yUhXcayoUgYhXE8JiNdBuYRWMHNyU2Tuyk_TmHHK8VBuyTWVal23IFy73tHeX0AZQlbWUbGTvTBJg4acAAAAAAP82nZKvXzaqAAGBAbwCAABcH_l_scRn-wIAAAAABFla)

For example, take this code:

```python
B=*R*VVVVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVRBVVVVRBVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVVVVRBdddddddddddddddddddddddddddddddddd
```

and format it with the default setting produces

```python
B = (
    *R
    * VVVVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVRBVVVVRBVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVVVVRBdddddddddddddddddddddddddddddddddd
)
```

The resulting error is:

>INTERNAL ERROR: Black produced invalid code: can't use starred expression here (<unknown>, line 2). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /tmp/blk_gik62liz.log

**Expected behavior**

That black doesn't wrap the starred expression in parentheses (or only the part after the `*`?)

**Additional  Context**
First reported here https://github.com/astral-sh/ruff/issues/11759

**Comment by MichaReiser** [comment]
Maybe this is not worth fixing because the input is already a syntax error, just not a parse time syntax error

```
B=*R*VVVVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVRBVVVVRBVVVVVVRBVVVVVVVVVVVVVVVVVVVVVVVVVVVRB
  File "<stdin>", line 1
SyntaxError: can't use starred expression here

```

**Comment by JelleZijlstra** [comment]
Yes, we don't guarantee what happens if you pass Black invalid code.
