### ISSUE TITLE
add option for formatting with Single quotes `'`

### ISSUE THREAD

**Issue by ArtemIsmagilov** [psf/black#4382]
Usecase.
```python
print("Hello!")
```
run formatting with `--single-quotes`. WIll reset quotes on `'`
```bash
black . --single-quotes
```
result
```python
print('Hello!')
```

**Comment by JelleZijlstra** [comment]
We've rejected this before; e.g. #373.

**Comment by ArtemIsmagilov** [comment]
Ruff implement.
https://docs.astral.sh/ruff/settings/#format_quote-style
