### ISSUE TITLE
Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by peterdsharpe** [psf/black#4384]
**Describe the bug**

Black reports an error upon formatting a file, and asks me to make a bug report.

**To Reproduce**

For example, take [this entire file](https://github.com/peterdsharpe/AeroSandbox/blob/22a5b2d5208499e0f389d0b85eb600f008f3052f/aerosandbox/library/field_lengths.py),

And run it with these arguments:

```sh
$ black field_lengths.py
```

The resulting error is:

```
AeroSandbox\aerosandbox\library\field_lengths.py: INTERNAL ERROR: Black produced different 
code on the second pass of the formatter.  Please report a bug on 
https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\peter\AppData\Local\Temp\blk_2loifc8n.log
```

**Environment**

- Black's version: 24.4.2
- OS and Python version: Windows 11, Python 3.11.7

**Additional context**

The resulting log file (`blk_2loifc8n.log`) [can be viewed here](https://pastebin.com/1aXVjxxf).

**Comment by JelleZijlstra** [comment]
Thanks, reduced reproduction case:

```python
if 1:
    takeoff_effective_friction_coefficient = (  # From Torenbeek, Eq. 5-76; an approximation
            friction_coefficient +
            0.72 * (CD_zero_lift / CL_max)
    )
```

**Comment by JelleZijlstra** [comment]
This looks basically the same as #3701.
