### ISSUE TITLE
Black breaks variable assignments with comments inconsistently

### ISSUE THREAD

**Issue by starshinePerigee** [psf/black#4388]
I typically include a comment after an assignment to document the meaning of a variable, like so:
`my_var = 0.1  # my_var is my variable`

If my comment is too long, black will sometimes - but not always - split the assignment on to its own line:
```
my_var = (
    0.1  # this is an example. Black won't actually split this one. I have real examples shortly.
)
```

However, this split occurs inconsistently for obscure reasons? In my testing, it appears to possibly related to the number of short words in your comment. 

Given the following input:

```
my_var_1 = 0.1  # this is a short comment
my_var_2 = 0.1  # Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed aaaaaa aa aaaa
my_var_3 = 0.1  # Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
my_var_4 = 0.1  # aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa
my_var_5 = 0.1  # This is a long comment with many short words a a a a a a a a a a a a a a
```

This splits lines 2 and 5, but not 3 or 4 despite being far longer:

```
my_var_1 = 0.1  # this is a short comment
my_var_2 = (
    0.1  # Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed aaaaaa aa aaaa
)
my_var_3 = 0.1  # Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
my_var_4 = 0.1  # aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa
my_var_5 = (
    0.1  # This is a long comment with many short words a a a a a a a a a a a a a a
)
```

This is not a major issue, but it is a bit boggling.

I did a brief search and didn't find any other references in the docs or existing bugs, so sorry if this has been reported before or is a known feature. This was reproduced in the Black online playground here: [link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIMARNdAD2IimZxl1N_WmBpTZ-5BQT9yWFaCUK8ZWDUSz2fe7ttWM--QnFjDfYtJ-uZY3TzEaq-GITxerfVldWLCt9oEkmhQDMf5Em3AO6dQwaMIExExabe7YnlmEWua8HK796A5xATs2dydZY0IDuOvHoplIFCt6Y8I2CJZk85TXfl2DSgJxxF4vvmyoxYbkCBNL8AP8xHQvX-C2wGTy-CH_5T7QESWV8anlzlYrvo1WoNb3o2TYDtKh-zMUoO6TIW204MvubWiskB0H1vy2AHewEaVA69MaTWntlqDAFMj_QX-n-p7bHjJa5a4eHgzrE6NTRjxEYAFwbYg4ByiIYzXSRTMH7eUnDu_4j-0pUsAj8SnhtwXxP-AABHumUulb6kwQABrwKNBAAAvOLlSbHEZ_sCAAAAAARZWg==)

**Comment by JelleZijlstra** [comment]
I think this is because we don't split if the line is still too long after splitting.

**Comment by starshinePerigee** [comment]
Ah - that appears to be the case. In my code where this first occurred, the variable names were perfectly long such that only a very specific string length caused a break and I was going mad trying to figure out why.

Thank you for your time.
