### ISSUE TITLE
Cannot parse nested f-strings if the same quote char is used inside and outside.

### ISSUE THREAD

**Issue by maflAT** [psf/black#4408]
**Black https://github.com/psf/black/commit/9c1fd4**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACMAF5dAD2IimZxl1N_WlkB94M-fIXjTqeVxKhorS-NcPomlJhymnRzTOyZGaPOuTE-6SaihjFVbcxokbFNOC2pppRZ-kjchpSYZ4t6eufxPQLgrxNI4B-QfBbpivuH7FoSxsAAAAAxdCy8nlhxSgABeo0BAAAAPOkmmLHEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
f"#{f"Version {__version__}":^48}#"
```

## Output

```python
cannot use --safe with this file; failed to parse source file AST: f-string: expecting '}' (<unknown>, line 1)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```

## Expected

**Comment by hauntsaninja** [comment]
Your example works fine on the latest Black release, but you do need to run Black using 3.12 or newer (as the error message mentions)

**Comment by hauntsaninja** [comment]
See also https://github.com/jpadilla/black-playground/pull/77
