### ISSUE TITLE
Error in the setup docs for black.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [psf/black#4412]
**Is this related to a problem? Please describe.**

Error in the [Setup docs](https://black.readthedocs.io/en/latest/contributing/the_basics.html) command `pip install -e .[d]`, here `[d]` has no significance which causes an error while installing.

```shell
(.venv) kanishkpachauri in ~/Desktop/oss/Python/black on main λ pip install -e .[d]
zsh: no matches found: .[d]
```

<img width="789" alt="Screenshot 2024-07-25 at 8 16 59 AM" src="https://github.com/user-attachments/assets/27179127-652a-4e30-92f0-153b0c2d12f4">

**Describe the solution you'd like**

Remove `[d]` from the docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by JelleZijlstra** [comment]
`.[d]` here installs the extra for blackd. Depending on your shell you may need to do `pip install -e '.[d]'` instead.

**Comment by Mr-Sunglasses** [comment]
> `.[d]` here installs the extra for blackd. Depending on your shell you may need to do `pip install -e '.[d]'` instead.

Thanks, @JelleZijlstra, it worked, I'm currently using the `zsh` shell, does `'.[d]'` a safe option and work on every shell, yes then we can add it into the docs so that I can't cause the error for other users.

**Comment by JelleZijlstra** [comment]
I think it should work on any Unix shell but not sure about the required quoting on Windows.

**Comment by Mr-Sunglasses** [comment]
> I think it should work on any Unix shell but not sure about the required quoting on Windows.

@JelleZijlstra , I've tested both Windows and UNIX systems, and `".[d]" works for both systems.

Test on windows: [Action ref](https://github.com/Mr-Sunglasses/black/actions/runs/10087626717/job/27892073937)

<img width="1049" alt="Screenshot 2024-07-25 at 8 55 47 AM" src="https://github.com/user-attachments/assets/e90015af-3877-4add-9eeb-c2c1800e3cc8">

For Unix: ( tested on macOS 14.5 )

<img width="1440" alt="Screenshot 2024-07-25 at 8 58 28 AM" src="https://github.com/user-attachments/assets/690abfd4-e293-439a-82b1-936cf40b15ea">
