### ISSUE TITLE
Make Readability your main focus. 

### ISSUE THREAD

**Issue by maximilian22x** [psf/black#4416]
Hello,

Why did you place the imports in different positions? The goal of the code is readability, which is lacking in your current format. Imports should be at the same position for better readability. This way, I can quickly recognize the imported modules. Compare my code style on the left with the Black code style on the right. 

Which do you think offers better **readability**? I see no structure on the right Black site. 

![image](https://github.com/user-attachments/assets/297fd4b6-115c-4c29-bddc-42285d9c86aa)

**Comment by MeGaGiGaGon** [comment]
There has been discussion on similar things in the past, see #3341, #2385, and #682, but in general alignment is not something that Black seems to want to handle. This makes sense to me, as so much of Black is based around maximum line length limits, and the exact semantics of how to align code while respecting length limits is not trivial to decide or implement. 

For existing code, you can always use `# fmt: off` and `# fmt: on`, [playground example](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGHAIpdAD2IimZxl1N_WlwxRhR7MSgEEXxQpTnEuFLjxm3rlb2XqfkPiF4JpOyjAmokYxWUuO8-_ApwMPthJSNoEQzf17H2DKqPPwf4fGUDgmCMO0qQj12QC4z_zc_bHKvI9_JwZrVC_GHiJsrCrdDIt2CWklljQSAh4gY76Mw52fekszKa0g36hAZAh8AgAAAAALXhYM9l3fZVAAGmAYgDAAATL9sbscRn-wIAAAAABFla)

**Comment by JelleZijlstra** [comment]
Alignment the way you propose it interacts poorly with diffs. What happens for example, if you add an `as` import that is longer than `import matplotlib.pyplot as plt`? If we realign all the other ones to fit the new length, then your diff becomes very noisy. But if we don't do that, then the alignment becomes inconsistent.
