### ISSUE TITLE
Cannot parse multiline f-string starting with backslash `\`

### ISSUE THREAD

**Issue by turtleyacht** [psf/black#4417]
**Describe the bug**

Black fails to parse a file containing a multiline f-string that starts with a backslash `\`

**To Reproduce**

For example, take this code:

```python
print """\
This is a multiline string\
"""
```

And paste into https://black.vercel.app/?version=main

The resulting error is:

> Cannot parse: 1:6: print """\

Example:

https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACZAGFdAD2IimZxl1N_WmOQqEcOUhKyNfjwrEvHNPJJ-L3FEiTxKn-kRLm-QFP0oU2RsSfpKieifrParaKSlYAU88u1B6F0bWn_krYppL9-px2jvbbsLVg9_qRBqH77AUD8IILs3zEAAAAAeWQH5u87eYsAAX2aAQAAABaS41exxGf7AgAAAAAEWVo=

**Expected behavior**

Successfully parse.

**Environment**

- Black's version: 24.4.2
- OS and Python version: psf/black@stable

Locally, I am using Python 2.7.18 but the issue occurs [in the GitHub Action](https://github.com/turtleyacht/slimdown/actions/runs/10134776923/job/28021418891).

**Additional context**

Reused material from #4337.

**Comment by JelleZijlstra** [comment]
> Locally, I am using Python 2.7.18

We no longer support formatting Python 2 (https://black.readthedocs.io/en/stable/faq.html#which-python-versions-does-black-support). If you use Python 3 syntax, Black will format this fine.
