### ISSUE TITLE
Black refuses to reformat multi-line import statements into one line

### ISSUE THREAD

**Issue by zhouwein** [psf/black#4456]
black refuses to reformat multi-line import statements into one line, even if it fits within the character limit.

**To Reproduce**
For instance, black doesn't do anything to this code:
```
from foo.bar import (
    foobar,
    foobaz,
)
```
https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC-AGldAD2IimZxl1N_WlkPinBFn-y_xikiZUN2v-D2ZzWnB15v3GqRoY1jEU56Ved0bu6jLsciq_SpF0QhChhA7CBPUGk0utx5eH3Tup2fJP_YTw92Lor9OPMqkh04DMzRN8pNW-Eq2ajQNkt5AAAAAAC09JvCXyCXigABhQG_AQAA_Uyb9LHEZ_sCAAAAAARZWg==

even though it can be reformatted to the following (35 characters):
```
from foo.bar import foobar, foobaz
```

If the same import statement was written as one line, it doesn't try to reformat it either. This happens with or without the parentheses after the word `import`.
```
from foo.bar import foobar, foobaz
```
https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACoAGBdAD2IimZxl1N_WlkPinBFn-y_xikiZUN2v-D2ZzX3KPfPhhbUzq3GmAip-tASQAk2pgd-wFliiSK3fqS5qdus7LXf5QKoqmbbVfXA15tPeg44LhgEwdAWY3DA8UQXt5wzZgDNBqViQ2fMdAABfKkBAAAA5YM-erHEZ_sCAAAAAARZWg==
https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACqAGRdAD2IimZxl1N_WlkPinBFn-y_xikiZUN2v-D2ZzWnB4ZoRoD08p9S91EqO0cFoNUb9G0sQ2DffLyRPmWk3PpGnmrMm7aLdUatsDqCiMmcNhY9lIVHgd6mWNR3eyvbnTAgepnwzeQA3VFtGB5eOKEAAYABqwEAAIYdLXuxxGf7AgAAAAAEWVo=

However, this behavior only seems to happen if the module being imported from has a dot in it. The following code, which only differs from the first example by replacing the dot in the module with an underscore, does get reformatted into one line:

```
from foo_bar import (
    foobar,
    foobaz
)
```
https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC9AGldAD2IimZxl1N_WlkPinBFn-y_8Ioz9cNOqkOAjkgbahmg_81gG2rLW2txaIxMCVDyTmNBkPxYylMpX3ASFyM41FS1xu6rocEup_JT-8G7AQR-S3sLMKaYEORGPX1lzmLSsjQ3XYpv8_5thwAAAABZNx9C4ZSTvQABhQG-AQAAmCsnTLHEZ_sCAAAAAARZWg==

**Expected behavior**
black should always reformat multi-line import statements into one line, if it fits within the character limit. At the very least, it should consistently decide on a canonical form rather than accepting both the multi-line and the single line variants.

**Environment**

- Black's version: Stable: 24.8.0 | Main: @98a580
- OS and Python version: black.vercel.app

**Additional context**

**Comment by JelleZijlstra** [comment]
This is [the magic trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma).

**Comment by hauntsaninja** [comment]
See also `--skip-magic-trailing-comma` / `-C`
