### ISSUE TITLE
Update documentation, error messages, etc. to reflect dropping Python 3.8 runtime support

### ISSUE THREAD

**Issue by jtmedley** [psf/black#4472]
The latest version (24.10.0) drops Python 3.8 runtime support via #4452. Error messages and documentation were not updated outside of the changelog. 

This creates significant conflicting information between actual requirements and installation instructions, error messages, etc. 

Here are a few places (not an exhaustive list) that need updating: 

[README.md](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/README.md?plain=1#L39)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/README.md?plain=1#L39-L42

[getting_started.md](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/getting_started.md?plain=1#L17)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/getting_started.md?plain=1#L17-L20

[docs/faq.md](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/faq.md?plain=1#L85)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/faq.md?plain=1#L85-L96

[docs/integrations/editors.md](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/integrations/editors.md?plain=1#L237)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/docs/integrations/editors.md?plain=1#L237-L241

[autoload/black.vim](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/autoload/black.vim#L77)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/autoload/black.vim#L77-L80

[plugin/black.vim](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/plugin/black.vim#L22)

https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/plugin/black.vim#L22-L30

[tox.ini](https://github.com/psf/black/blob/1b2427a2b785cc4aac97c19bb4b9a0de063f9547/tox.ini#L3) might need updating but I'm not certain: 

https://github.com/psf/black/blob/3dcacdda0d7f69a1705f3e2a151c24a6cf004171/tox.ini#L3 

I was halfway through writing this when I saw that #3896 did a very similar thing after 3.7 support was dropped in #3765. 

It is not a coincidence that every file changed in that PR also needs changing again for dropping 3.8 support, along with at least a couple others. It would be pretty cool if updates to documentation, error messages, etc. could be more of a standard part of changes like this in the future. Tests also may need updating. Thanks!

**Comment by hauntsaninja** [comment]
PR welcome!

**Comment by JelleZijlstra** [comment]
Working on it

**Comment by jtmedley** [comment]
Good lord that was fast. Thanks!!
