### ISSUE TITLE
Support .editorconfig

### ISSUE THREAD

**Issue by mbarneyjr** [psf/black#4487]
Per [the comment on this issue](https://github.com/psf/black/issues/2401#issuecomment-991964417):

> Given there's already a note about this in the docs I'mma close this. If someone wants to suggest Black should support .editorconfig, please open a separate issue, thank you!

I don't see any issues specifically about supporting `.editorconfig`, so this is my request to the black team to support it

**Comment by JelleZijlstra** [comment]
I don't know anything about this file. Could you share more about what you'd want Black to do here?

In general I'd be hesitant to support configuration from more file types, because it makes it harder for users to understand where their configuration is coming from.

**Comment by mbarneyjr** [comment]
Sure, `.editorconfig` is a file who's main goal is to standardize and consolidate configuration across various formatters and other tools/editors. Instead of defining a formatting config in my `pyproject.toml` for black, `.prettierrc.json` for Prettier, `<whateverfile>` for <whatevertool>, you're able to specify one common set of configuration in one file, the `.editorconfig` file. You can read more about it [here](https://editorconfig.org/)

I totally get the hesitation to support more config sources, but IMO `.editorconfig` is different precisely because it's meant to consolidate config in one location and make it easier to reason about

**Comment by JelleZijlstra** [comment]
Thanks. It seems https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties has a list of supported properties. Most of those are things that are not configurable in Black (e.g., tab size); the only exception is max-line-length, which is marked as "Supported By A Limited Number of Editors". So the benefit of supporting this in Black seems limited.

**Comment by hauntsaninja** [comment]
As it stands, this is probably going to be a won't implement. If this issue becomes very popular or there's clear precedent of other (Python) auto-format/fix tools reading this config, we can reconsider

**Comment by JelleZijlstra** [comment]
Ruff rejected this feature for similar reasons astral-sh/ruff#1530

**Comment by Johnlon** [comment]
what is the meaning of the Black other tools documentbthst refers to editorconfig and says one can use 

[*.py]
profile = black


?

"profile" isn't valid editorconfig syntax at least not recognised by intellij.

any clues what that page is trying to communicate?

**Comment by codingjoe** [comment]
> Ruff rejected this feature for similar reasons [astral-sh/ruff#1530](https://github.com/astral-sh/ruff/issues/1530)

… which has been fairly negatively received. Maybe we could reconsider?

Since editorconfig is built upon Python's `configparser`, so added complexity for the PSF might be manageable. And supporting a standard that supersedes Python seems like an OK exception.

// Disclaimer: I come from a Django world, where ECMAScript, CSS, and HTML coexist in single projects. The Node community isn't too aware of PEP 621 🤷
