### ISSUE TITLE
Automatically ignore files in .gitignore

### ISSUE THREAD

**Issue by jdufresne** [psf/black#475]
I think a feature to automatically ignore files and directories listed in `.gitignore` would be useful. This file normally contains a long list of auto-generated files or files that are otherwise unnecessary to format. By pruning these big directories, black will run much faster. By adding such a feature, black will require even less configuration as most projects will no longer require passing `--exclude` on the command line. 

Other opinionated code format tools already do this or are discussing this. For example:

JavaScript Standard: https://standardjs.com/#how-do-i-ignore-files

> Paths in a project's root .gitignore file are also automatically ignored.

PHP-CS-Fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3947#issuecomment-408342692

> I think it can be fixed in a broader, generalised way, by parsing (and excluding the results of) ignore files like .gitignore.

**Comment by zsol** [comment]
I think this is reasonable for black to do :)

**Comment by behnam** [comment]
See also https://github.com/ambv/black/issues/541.

**Comment by jgirardet** [comment]
I'll go for it.

**Comment by jgirardet** [comment]
I need your opinion to go on  @zsol

**Comment by Natim** [comment]
This is the kind of errors I'd like to get rid of:

```
error: cannot format kinto/plugins/admin/node_modules/react-breadcrumbs/demo/node_modules/node-forge/tests/server.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: invalid syntax (<unknown>, line 74)
error: cannot format kinto/plugins/admin/node_modules/react-breadcrumbs/demo/node_modules/node-forge/tests/forge_ssl/forge/ssl.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: invalid syntax (<unknown>, line 125)
```

I have not intention of formatting a `node_modules` file, also one could argue that this folder has nothing to do in my code tree, but apparently for some reason it does...

**Comment by zsol** [comment]
Because we have `--include`, I think the most sensible option is to merge gitignore with the value of `--exclude`; if there's no `--exclude`, merge it with the default. Values in `pyproject.toml` basically replace the default value for command line options.

**Comment by xmo-odoo** [comment]
FWIW, on top of automatically parsing .gitignore & .hgignore (and possibly some others) [several code-searching tool have standardised on a .ignore file with similar semantics](https://news.ycombinator.com/item?id=12568245), so support for that would also be nice.

**Comment by ambv** [comment]
This was solved with https://github.com/psf/black/pull/878/.
