### ISSUE TITLE
Unexpected line break in combination with assert

### ISSUE THREAD

**Issue by aberres** [psf/black#507]
Operating system: MacOS
Python version: 3.6
*Black* version: master

The following snippet is formatted by black:

    assert (
        dbreader.CategoryDataHandler.select(
            connection, scenario_set_id=scen_set_id1, changeset_id=changeset_id0
        )
        == []
    )

I would expect the `== []` to not appear on a separate line.

**Comment by JelleZijlstra** [comment]
This issue has received little feedback after several years. We're unlikely to change this formatting decision at this point.
