### ISSUE TITLE
Allow no space between operator **

### ISSUE THREAD

**Issue by paugier** [psf/black#538]
This is a follow up of issue https://github.com/ambv/black/issues/148 (see in particular https://github.com/ambv/black/issues/148#issuecomment-384184113 by @njsmith)

Black still adds spaces around the operator `**`.

It is really bad for readability of math formula and it is not consistent with PEP 8 (https://www.python.org/dev/peps/pep-0008/#other-recommendations).

This operator has a so high precedence (https://docs.python.org/3/reference/expressions.html#operator-precedence) so I think it should be allowed not to put spaces around it.

I know that we can use 
```
# fmt: off
t = a**2 + b**3
# fmt: on
```
for math, but many times, the spaces around `**` are the worst problems, so allowing `a**2` would save us from adding too many `# fmt: off ... # fmt: on`.

**Comment by ambv** [comment]
Black does not take existing formatting into account, instead it applies uniform formatting everywhere. Hugging math operators is hard to do uniformly. See this and the next comment:
https://github.com/ambv/black/issues/148#issuecomment-383332150

I am not philosophically opposed to making Black smarter about this but I'm afraid this is less obvious if you include non-trivial operands.

**Comment by ambv** [comment]
Oh, and in case this is not clear: it's out of the question for Black to "preserve user's choice". The entire program is built around the tenet of consistent formatting without looking at preexisting style. The only place where we break this rule is vertical whitespace (people are really attached to their blank lines!) and this was a source of a lot of pain for awhile (still not *fully* solved but *mostly* fine).

We want to solve this but it's rather tricky: we will need to model an approach that Black can execute on its own. Currently Black decides on whitespace for all tokens just by looking at the current one and sometimes also at its immediate predecessor. We are not looking at what comes **after** the current token (we'd have to change the algorithm not to be simply visitor-based anymore) nor make decisions based on whether other tokens received whitespace or not (with the exception of [a simple hack](https://github.com/ambv/black/blob/ed9b31b1394bc4c57bad08a065477323c458e9c3/black.py#L1666) around type-annotated function arguments).

**Comment by paugier** [comment]
OK. I now understand that it is out of the question for Black to "preserve user's choice".

Then a simple solution would be to just remove white spaces around `**`.

I realize that it wouldn't always be consistent with PEP 8 (actually only when `**` is the only operator in the expression) but most of the time it would give a nicer result than with spaces around `**`.

**Comment by ambv** [comment]
Thinking about it some more (actually, *a lot more*) it seems to me like the easiest improvement here is to do what @paugier was suggesting all along, especially clearly in his latest comment, with the following additional twist: if `**` is the only operator in the expression, then don't hug.

**Comment by basnijholt** [comment]
@ambv, that's a solution many could probably live with! 👍 

@grothesque, you might find this one interesting.

**Comment by sbeinlich** [comment]
@basnijholt Can I try to take on this issue?

**Comment by basnijholt** [comment]
Of course you can, I don’t think anybody else is working on it 🥳

**Comment by rgommers** [comment]
> with the following additional twist: if `**` is the only operator in the expression, then don't hug.

This is actually unnecessary. `**` isn't covered at all in https://www.python.org/dev/peps/pep-0008/#programming-recommendations, but it's a lot more common to never use spaces around `**` than use this conditional rule. This can be easily verified by, e.g., searching for `x**2` and `x ** 2` in the numpy/scipy code base, or a quick poll under people who primarily write numerical code.

**Comment by felix-hilden** [comment]
If I may chime in here, I think that the rules proposed here and the linked PR are solid:

```
# One operator
a ** b

# Many pows with simple operators
a**b + c**d

# Complex pows (I think even the call is complex enough)
(a + 1) ** 2 + b ** -1 + c ** sqrt(d)

# Mixed pows would be independent
a**b + (c + 1) ** d
```

But, the argument for letting people write their maths the way they like is there as well. Black is an opinionated formatted though, so I'm not sure why this is any different from other opinionated changes we make.

**Comment by oscarbenjamin** [comment]
There are some suggestions that SymPy should use black (https://github.com/sympy/sympy/issues/17287) but it looks like it destroys visual formatting of mathematical expressions. You can see the effect of applying black to the sympy/solvers submodule here: https://github.com/sympy/sympy/pull/22434.

Forcing spaces around `**` is a deal-breaker as far as I'm concerned but also I can't accept forced spaces around `*`. I absolutely want to be able to write this:
```python
equation = a*x**4 + b*x**3 + c*x**2 + d*x + e
```
Any human reader who is used to mathematical expressions and mathematical code will prefer that to this which is much harder to parse:
```
equation = a * x ** 4 + b * x ** 3 + c * x ** 2 + d * x + d
```
If there was a configuration option to disable this particular aspect of black then we could contemplate using it.

**Comment by ichard26** [comment]
Hey everyone,

I'm picking this issue up and looking to push GH-2095 forward so it's merged in time for the stable release. I was wondering how much we actually need to keep the special case of **not** hugging expressions with just a power operator. It turns out getting such an edge case to work properly and consistently is harder than expected (with our current architecture) and since Jelle and I don't see the value of the special case we want to remove it and **make it where Black always hugs power operations with a non-complex base or exponent** (right now we've decided that everything beyond a simple NAME or CONSTANT with or without an unary op is considered complex, similar to our subscript rules).

Please weigh in with your feedback, it'll be appreciated. Thank you, daylily.

**Comment by ichard26** [comment]
Merry Christmas folks! (or happy holidays if you don't observe christmas). I have packaged up my changes into a PR (GH-2726) and wanted to collect feedback on it. Upon implementation I actually expanded the definition of what is considered a simple "operand" to include attribute access (chained attribute access too!). The rule is now something like:

> For power ops, an operand is considered "simple" if it's only a NAME, numeric CONSTANT, or attribute access (chained attribute access is allowed), with or without a preceding unary operator.

For some examples, here's some code I pulled from real world code from OSS projects formatted under this PR: 

```python
a = 5**~4
b = 5 ** f()
c = -(5**2)
d = 5 ** f["hi"]
e = lazy(lambda **kwargs: 5)
f = f() ** 5
g = a.b**c.d
h = 5 ** funcs.f()
i = funcs.f() ** 5
j = super().name ** 5
k = [(2**idx, value) for idx, value in pairs]
l = mod.weights_[0] == pytest.approx(0.95**100, abs=0.001)
m = [([2**63], [1, 2**63])]
n = count <= 10**5
o = settings(max_examples=10**6)
p = {(k, k**2): v**2 for k, v in pairs}
q = [10**i for i in range(6)]
```

For even more details [you can see this diff](https://gist.github.com/ichard26/ca6c6ad4bd1de5152d95418c8645354b) comparing main and the aforementioned PR -- i.e. it shows what would happen formatting-wise if we landed it. 

To play with it locally you can install the PR with this command: `python -m pip install https://github.com/psf/black/archive/hug-power-op.zip`.

Thanks in advance! ❀

**Comment by MarcoGorelli** [comment]
> Merry Christmas folks! (or happy holidays if you don't observe christmas)

Thanks, you too!

I've had a look at the changes, and they look great to me, well done!
