### ISSUE TITLE
cache stdin

### ISSUE THREAD

**Issue by jgirardet** [psf/black#559]
Hi,
Cache actually only only caches files because it stores path, modification time and size.

Formatted string via stdin does not cache the result. blackd not either.

Maybe we could add a cache for  stdin/blackd using hash(str_to_format), lenght and black_options used.

That would permit plugin using format via stdin and blackd  to benefit of the cache system without writting a new one.

Nice day
jimmy

**Comment by ambv** [comment]
Do you have an intuition (or better yet), any data on what the hit rate of this cache would be?

**Comment by JelleZijlstra** [comment]
Intuitively it seems like it would be low since plugins mostly run when the user hits save or edits something, which by definition means they'll hit a cache miss.

**Comment by jgirardet** [comment]
in sublime text I implemented a simple cache using hash(content_of_the_buffer) and save it with the command line arguments.
The big benefit is to not rerun black on large file when we hit save twice. I'm not sure this issue is relevant for black anymore.

**Comment by ambv** [comment]
Based on the discussion above, we won't be integrating this in Black core.
