### ISSUE TITLE
--safe can't be used when code uses async/await as names and Black runs on 3.7+

### ISSUE THREAD

**Issue by nixjdm** [psf/black#583]
Operating system: Ubuntu
Python version: 3.7
*Black* version: 18.6b4
Does also happen on master: yes
---------------------------------------

On Python 3.7, the following snippet does not produce an error

```python
from zappa.async import task

x = {"a": "b"}
```

but it should. Black is regarding that snippet as already fine, but if it is modified slightly so that it has to do any reformatting, it will break because of the `zappa.async` which is not allowed in 3.7.

```python
from zappa.async import task

x = {"a": 'b'}
```

This fails with 

```
error: cannot format test.py: cannot use --safe with this file;
failed to parse source file with Python 3.7's builtin AST. 
Re-run with --fast or stop using deprecated Python 2 syntax. 
AST error message: invalid syntax (<unknown>, line 1)
```
In my testing, it succeeds in being reformatted in Python 3.6 as it should.

So I see two things wrong with this.

1. `async` is being handled inconsistently on 3.7 (it should always fail), and
2. That error could be more accurate. The issue isn't about Python 2 syntax, it's about Python 3.6 vs Python 3.7 syntax.

Side note - I'm aware Zappa / Lambda does not support 3.7 yet. I found this by happy accident.

**Comment by JelleZijlstra** [comment]
Your second issue is similar to #423 – Black tries multiple grammars and that can sometimes lead to wrong error messages.

The first issue should be fixable by using a grammar in 3.7 that disallows `async` (or `await`) as an identifier, though I don't see it as high priority. Black is for formatting, not for detecting syntax errors.

**Comment by ambv** [comment]
The problem here is that Black is using the built-in AST of Python to compare "before" and "after". If it's running on Python 3.6, it will allow "async" and "await" as names. If it's running on Python 3.7, it won't.

We should rather use typed-ast for the --safe comparison instead of whatever we're finding on the current Python.

**Comment by ambv** [comment]
This is long fixed with the introduction of `--target-version=`.
