### ISSUE TITLE
Make coverage check non-mandatory

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#634]
A lot of open PRs are currently showing up red because of harmless tiny drops in test coverage (e.g., -0.03% in #632). This makes it harder to see at a glance which PRs are ready to be merged.

Is there a way to make the coverage check still run, but make it non-mandatory, so that CI doesn't show up as broken if the step fails?

**Comment by asottile** [comment]
yep, for coveralls you can configure this.  [for example](https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694)

**Comment by zsol** [comment]
we need @ambv to configure this over at https://coveralls.io/github/ambv/black

**Comment by ambv** [comment]
I cannot do this now because it's https://coveralls.io/github/psf/black and I have no access there. @ewdurbin, could you do that for us? Make the coverage check non-mandatory?

**Comment by ewdurbin** [comment]
looks like there are two configuration options:

- COVERAGE THRESHOLD FOR FAILURE
- COVERAGE DECREASE THRESHOLD FOR FAILURE

that are specified in %. Do you have values?

**Comment by ewdurbin** [comment]
By the way @ambv I've updated your privileges on this project to "Admin" on GitHub. Not sure why you were just "Write" before.

**Comment by ambv** [comment]
Failure threshold: 90%
Failure decrease threshold: 1%

(thanks for the updated privileges!)

**Comment by ewdurbin** [comment]
Do the upgraded privileges give you access to the Coveralls settings?

**Comment by ambv** [comment]
For some reason they don't. Compare:
<img width="1153" alt="Screenshot 2020-03-03 18 03 07" src="https://user-images.githubusercontent.com/55281/75800050-45b2e780-5d79-11ea-8e2c-24834b3ebc90.png">
vs.
<img width="1156" alt="Screenshot 2020-03-03 18 02 51" src="https://user-images.githubusercontent.com/55281/75800065-4a779b80-5d79-11ea-82ba-a0055b5e2002.png">

**Comment by ewdurbin** [comment]
Settings updated.

**Comment by ambv** [comment]
Thank you!
