### ISSUE TITLE
Formatting of if condition can be improved.

### ISSUE THREAD

**Issue by sainadh-d** [psf/black#649]
Operating system: `Mac OS X Mojave`
Python version: `Python 3.6.7`
*Black* version: `18.9b0`
Does also happen on master: Yes

I have a piece of code which looks like

```python
class MyClass:
    def my_func(self, check=False):
        flag = False
        try:
            configuration = self.get_config_from_db()
            if check:
                if 'expected_flavour' in configuration.get('flavours', []) and app_settings[0].upper() in configuration.get('settings', []):
                    flag = True
        except:
            pass
        return flag
```

Upon running black on this
```sh
black -S -l 120 temp.py
```
I get

```python
class MyClass:
    def my_func(self, check=False):
        flag = False
        try:
            configuration = self.get_config_from_db()
            if check:
                if 'expected_flavour' in configuration.get('flavours', []) and app_settings[
                    0
                ].upper() in configuration.get('settings', []):
                    flag = True
        except:
            pass
        return flag
```

Formatting of the `if` condition above is not readable.
```python
if 'expected_flavour' in configuration.get('flavours', []) and app_settings[
      0
].upper() in configuration.get('settings', []):
```

IMO the following would be more readable, which is done when there are 3 or more checks in `if`
```python
class MyClass:
    def my_func(self, check=False):
        flag = False
        try:
            configuration = self.get_config_from_db()
            if check:
                if (
                    'expected_flavour' in configuration.get('flavours', [])
                    and app_settings[0].upper() in configuration.get('settings', [])
                ):
                    flag = True
        except:
            pass
        return flag
```

**Comment by JelleZijlstra** [comment]
I agree that the formatting with index expressions on their own line isn't great and that your proposed formatting looks nicer in this case. I haven't looked at how realistic it is to implement in general though, and maybe this change would lead to worse formatting in some other case.

**Comment by ambv** [comment]
We should at least try to make Black not choose to split on indexes if optional parentheses can yield nicer formattings.

**Comment by MikeFalowski** [comment]
Still happen in version 19. It would be really nice improvement.

**Comment by miriaford** [comment]
Could any contributor please point us to how we can modify this behavior ourselves? I'm willing to fork Black and hack the source code.

**Comment by felix-hilden** [comment]
I believe this is essentially the same request as the newer #2156, which has some more discussion (though it was initially rejected) and associated PRs. I'll close this issue in favor of it!
