### ISSUE TITLE
Document mapping between command-line options and settings in pyproject.toml

### ISSUE THREAD

**Issue by trondhindenes** [psf/black#652]
It's not completely straight-forward how to specify black settings in the toml file. For example, its hard to figure out how to add the `--skip-string-normalization` option to `pyproject.toml`.

It would be really good if the documentation had the related pyproject setting documented for each option.

**Comment by zsol** [comment]
Happy to review a PR

**Comment by trondhindenes** [comment]
well I couldn't' figure it out so I don't have much to contribute, I'm afraid.

**Comment by gar1t** [comment]
This works:

```
[tool.black]
skip-string-normalization = true
```

The mapping is algorithmic - handled here: https://github.com/psf/black/blob/1ab87a3f67bc80a2e59be2692f2e2f25dd143af7/black.py#L246-L248

The values are consumed downstream as these params:

https://github.com/psf/black/blob/1ab87a3f67bc80a2e59be2692f2e2f25dd143af7/black.py#L389-L405

**Comment by ambv** [comment]
The documentation includes a pyproject.toml example which includes dashed options as well. It does also say that "The option keys are the same as long names of options on the command line."
