### ISSUE TITLE
Misleading reporting of internal errors

### ISSUE THREAD

**Issue by DRMacIver** [psf/black#708]
Whenever an exception is thrown within black and caught in `reformat_one`, it is passed to `report.failed(src, str(exc))`. Unfortunately `str(exc)` just gives you the exception message. This can be result in a fairly misleading picture of what was going on.

To give an example of why this matters, I've had a case where the actual error was:

```
    cache: Cache = pickle.load(fobj)
EOFError: Ran out of input
```

(I'm not yet sure why the cache thing was happening and don't have a reproduction of it for you, sorry, but this is a more general problem)

Because black only shows the error message this shows up as "cannot format (filename): Ran out of input". This sent me on a bit of a wild goose chase because it _looks_ like the problem is that black thinks the file is invalid, which actually it's an unrelated error.

Personally I'm very 👎 on showing anything other than the actual internal exception when something like this happens, complete with stack trace and everything, but I'm aware this is a controversial religious belief. I'd be happy with anything that made it clearer that this was an internal error and not a problem with the file.

**Comment by DRMacIver** [comment]
FWIW the cache errors I was seeing that prompted this bug turn seem to be caused by running many copies of black in parallel when your home directory is a network share. I suspect the problem is that renames are not atomic on NFS, but I wouldn't swear that's the issue. I'll file a separate bug if you want me to but I can't promise a reproducible test case.

**Comment by zsol** [comment]
Yes, please let's keep the discussion in this issue focused on improving (internal) error reporting.

**Comment by ambv** [comment]
I think we should have something like --traceback which shows full tracebacks for failed files. This should be rather easily achievable since exceptions in Python 3 hold onto their tracebacks.

**Comment by ichard26** [comment]
Also see #1263. This is similar to #423 but when an parsing error occurs during the `--safe` check.

**Comment by hauntsaninja** [comment]
In `--verbose`, we report the full stacktrace: https://github.com/psf/black/pull/1594 . I think this is fine, we don't need another flag for this and it's pretty uncommon for black to crash
