### ISSUE TITLE
Exclude patterns operate on absolute paths

### ISSUE THREAD

**Issue by wagdav** [psf/black#712]
Operating system: Linux
Python version: 3.6.7
*Black* version: 18.9b0
Does also happen on master: yes

First, thanks for making black! it's a great piece of software!

I noticed that the exclude patterns operate on the absolute paths.  For example:

```
mkdir -p /tmp/build/myproject && touch /tmp/build/myproject/hello.py
(cd /tmp/build/myproject && black --check .)
No paths given. Nothing to do 😴
```
If `myproject` is in a different directory for example `not-build`, black works as expected:
```
mkdir -p /tmp/not-build/myproject && touch /tmp/not-build/myproject/hello.py
(cd /tmp/not-build/myproject && black --check .)
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```
This happens because the string "build" is in the default exclude list and the exclude pattern operates on the absolute path.  I expect that the exclude list should care about directories  _within_ the specified directory, that is, in the given example, under `myproject`.

**Comment by zsol** [comment]
I also think this is very unintuitive, we want to match on paths relative to the arguments given.

**Comment by tomwassenberg** [comment]
After searching for a long time, I found out we were also running into this issue. The directory we use during our build procedure is `/build/repo`, during which we run `black --check .`. This would output "nothing to do", because `build` is part of the default exclude list.

I think the best solution would be what @wagdav is saying, but at the very least a more descriptive error message should be outputted when the `--verbose` flag is passed.

**Comment by ambv** [comment]
I'd like some more pointers on how to reproduce this. Black *does* operate on paths relative to the root of the project: https://github.com/psf/black/blob/5b552fab9d8820db22d6266a8702b0f24e4c7ed9/black.py#L3575

The root is found by looking up until `.git`, `.hg`, or `pyproject.toml` is found. See the function `find_project_root()`.

**Comment by wagdav** [comment]
@ambv  Thanks for pointing out filtering code. It helped me to understand better what's happening.

The issue can be reproduced using the examples in the description when there's no `.git` file or equivalent to indicate the root of the  project. Thus, the `/tmp/build` part of the path will be also matched against the default exclude patterns.

Would it make sense tor return `common_base` instead of `directory` in `find_project_root` when no project root indicators are found?

**Comment by wagdav** [comment]
I'm closing this because this is not an issue for me. The issue I pointed out in the description is an edge case which is rarely triggered during my everyday black-usage.
