### ISSUE TITLE
git pre-commit hook that overrides tracked files before commit

### ISSUE THREAD

**Issue by cypreess** [psf/black#726]
I wrote a handy pre-commit hook in bash that overrides any tracked file just before commit. Especially helpful if you have black integrated in your CI checks and you never want to commit code which is not black compliant. 

https://gist.github.com/cypreess/9b2a2ed8981c650178e28259229ff92e
```
#!/bin/bash
# Author: Kris Dorosz <cypreess@gmail.com>
# This git pre-commit hook will apply black formatting before any commit and make sure all tracked files are reformatted

echo "Using" `black --version`
black --check . 2>/dev/null
if [ $? -ne 0 ]; then
    echo "Reformatting:"
    export current_git_branch=`git branch | grep \* | cut -d ' ' -f2`

    # Find all files which were reformatted by black and choose only those one which are currently tracked by git
    for f in $(comm -12 <(black . 2>&1 | grep -o '/.*\.py$' | sort) <( (git ls-tree -r --name-only  $current_git_branch; git diff --name-only --cached) | sed  "s,^,`pwd`/,g" | sort)); do
        echo "  $f"
        git add $f
    done
fi
```

Maybe it would be helpful to integrate this hook somehow into README or codebase.

**Comment by peterjc** [comment]
Interesting - I wanted something similar, and so wrote a flake8 plugin which essentially runs `black --check`` and so can abort the commit, leaving the user to run black themselves:

https://github.com/peterjc/flake8-black

You script is *much* shorter. Grin.

**Comment by ambv** [comment]
@cypreess, I can endorse this in the docs if you put it up somewhere. But we won't be integrating this ourselves since sometimes the formatting done might be a little too much for what you're willing to accept in one commit. The "only re-add already tracked files" logic looks a bit scary, too ;-)

**Comment by hauntsaninja** [comment]
Closing as per ambv's statement. [pre-commit](https://github.com/pre-commit/pre-commit) is also a reasonable way to accomplish this and this repo provides a pre-commit hook.
