### ISSUE TITLE
`black.exe` on Python 3.7 hangs indefinately

### ISSUE THREAD

**Issue by cooperlees** [psf/black#728]
Running a Python 3.7.2 `black.exe` on Windows hangs with this stack trace when killed: https://pastebin.com/RNz6i3CH

Sample Cmd:
```
C:\temp\tp\Scripts\black.exe .\ci.py .\ptr.py .\ptr_tests.py .\ptr_tests_fixtures.py .\setup.py
```

Operating system:  Win32NT 10.0.17134.0 Microsoft Windows NT 10.0.17134.0
Python version: 3.7.2
*Black* version: 18.9b0
Does also happen on master:
- Master has 2 Unit tests fail on 3.7
-- test_multi_file_force_py36
-- test_multi_file_force_pyi
- Master running the `black.py` file itself seems to work tho ...

## Repro
- Obtain Windows
- Make a 3.7.2 venv and install black from pypi
- `git clone git@github.com:facebookincubator/ptr.git`
- cd ptr
- `c:\venv\Scripts\black.exe  .\ci.py .\ptr.py .\ptr_tests.py .\ptr_tests_fixtures.py .\setup.py`

It also fails on Azure too and Python 3.6 black runs: https://facebookopensource.visualstudio.com/ptr/_build/results?buildId=47 (let me know if link is not accessible)

I would potentially suggest moving to Azure as it has 3.7.2 available on Windows available and MacOS. Happy to do the PR, but I don't have access to enable Azure etc.

**Comment by JelleZijlstra** [comment]
The stack trace sounds like #524 (though the symptom isn't quite the same)—the process pool implementation doesn't quite work. We should somehow detect that it doesn't work and fall back to processing serially, but I'm not sure how we'd do the detection in this case.

> I would potentially suggest moving to Azure

Do you mean enabling CI that runs on Azure? That seems useful yes.

**Comment by cooperlees** [comment]
Yes, I mean moving to Azure for CI so you can have 3.7.2 - or enable it on AppVeyor if it’s avaliable.

I’ll try get a PR up for Azure CI, but tests fail for me in 3.7.2 - will see if I can work them out if I get time ...

**Comment by cooperlees** [comment]
Seems to work with 3.7.3 when I updated my Windows 10 VM. Azure is still 3.7.2 and fails.

**Comment by cooperlees** [comment]
Azure CI on https://github.com/facebookincubator/ptr/pull/56 shows black works again on > 3.7.2 on Windows.
