### ISSUE TITLE
Failure to put two blank lines above top level function definition below comment

### ISSUE THREAD

**Issue by sparr** [psf/black#748]
```
foo=1

#comment
def bar():
    pass
```

pep8 and pyflakes want a second blank line above the comment, but black does not insert one.

Operating system: Arch Linux
Python version: 3.7.2
Black version: 18.9b0
Does also happen on master: untested, and online formatter version=master is broken right now

**Comment by ambv** [comment]
Yeah, comments that directly *prepend* top-level functions are a bit problematic for Black to handle automatically in the current implementation. If you add a second empty line yourself, Black will keep it.

**Comment by ambv** [comment]
We'll be solving this as part of #246.
