### ISSUE TITLE
Please don't move tags

### ISSUE THREAD

**Issue by djmitche** [psf/black#760]
When updating the repo:
```
Failed to download remote objects and refs:  From https://github.com/ambv/black
   ea55ff2..d6db1c1  master     -> origin/master
 * [new tag]         19.3b0     -> 19.3b0
 ! [rejected]        stable     -> stable  (would clobber existing tag)
```

I assume that `stable` is meant to track the latest stable release?  That's a job for a branch, not a tag :)

**Comment by ambv** [comment]
OK, we will remove the "stable" tag and make it a branch with the next release.

**Comment by ambv** [comment]
OK, this is solved. `stable` is no longer a tag, it is a **branch**.

**Comment by sersorrel** [comment]
fwiw, this goes directly against a statement in the pre-commit documentation:

> `pre-commit` assumes that the value of `rev` is an immutable ref (such as a tag or SHA) and will cache based on that. Using a branch name (or `HEAD`) for the value of `rev` is not supported and will only represent the state of that mutable ref at the time of hook installation (and will NOT update automatically).
