### ISSUE TITLE
Do not insert spaces into `#region` comments

### ISSUE THREAD

**Issue by zooba** [psf/black#773]
Operating system: Windows
Python version: 3.7.2
*Black* version: 18.9b0
Does also happen on master: Yes

Both Visual Studio and [PyCharm](https://confluence.jetbrains.com/display/PYH/Code+folding) support marking regions of code as collapsible by putting a `#region <arbitrary text>` comment at the start and `#endregion` comment at the end (on their own lines).

When Black inserts a space between the comment marker and the leading "r" or "e" character, it breaks this functionality.

Please special-case the "#region" and "#endregion" comments when they are on their own line and do not insert a space at the start.

**Comment by zooba** [comment]
I notice that the comment at https://github.com/ambv/black/blob/master/black.py#L2141 ("all comments should have a single space") isn't adhered to anyway, as multiple spaces are retained without modification.

For reference, it looks like https://github.com/ambv/black/blob/master/black.py#L2153 requires an additional `startswith` check once the `[0] not in "..."` check has passed.

**Comment by ambv** [comment]
Sorry, I missed this issue before. We already special-case type-comments so adding this is not out of the question.

@zooba, is it at all likely for Python Tools for Visual Studio to support `# SPACE region` in the future? PyCharm already does.

**Comment by zooba** [comment]
Sorry, I missed your reply (was just looking to see if GitHub notifications have gotten any better... and no... they haven't...)

It's possible. But another case here that annoys me is when I comment out a block of code by inserting `#` at the start of each line. Black will insert a space only in the cases where there's currently none, and so when I uncomment the block those lines are incorrectly indented while the rest are fine.

I agree that's a workflow thing rather than a style thing, but maybe just leaving the space at the start of comments alone is a fine approach?

**Comment by Forst** [comment]
Something that perhaps could be improved is not adding extra empty lines before the `# endregion` comments:

Current behaviour is as follows:

```diff
@@ -16,20 +16,24 @@
 class MemberRanking(BaseModel):
     guild_id: int
     rank: int
     score: int
     user_id: int
+
+
 # endregion
```

Also, as of writing, PyCharm works just fine with `# region`/`# endregion` comments (with leading space), and highlights the non-spaced version as a PEP8 violation.

**Comment by JelleZijlstra** [comment]
Does VSCode also support spaced `# region` now? If so I'd prefer to avoid any changes here to keep Black simple.

**Comment by Forst** [comment]
Seems so, both `# region` and `#region` are collapsible:

<img width="121" alt="Screenshot 2022-01-07 at 19 07 16" src="https://user-images.githubusercontent.com/369699/148587528-a94d8a10-64db-4caf-b13b-a0a8bab1ae0e.png">

Note that I normally don't use VS Code, and I don't know whether it's a recent fix or not. It's a clean install with the official Python extension.

VS Code version: 1.63.2, commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3

**Comment by JelleZijlstra** [comment]
Closing as the intended use case no longer requires unspaced comments.

**Comment by MarximusMaximus** [comment]
I have some other tools (not VSCode/PyCharm) that rely on this `#region` and `endregion` (as well as `#` followed by any of set of chars `#=-_.`). Is it possible to consider to re-open this? Or should I file a new issue?

**Comment by zooba** [comment]
I wouldn't bother reopening. Editors generally accept that they have to adapt to work with other tools, so eventually Black will just win this battle.

**Comment by MarximusMaximus** [comment]
> If we keep special casing comments because some tool doesn't like a space after the #, I feel like we'll never get to the end of this.
> I wouldn't bother reopening. Editors generally accept that they have to adapt to work with other tools, so eventually Black will just win this battle.

More important tools (not just editors) already don't and won't bother to acquiesce to work with Black. I'll just stop using Black instead, as it is the least important tool in the chain (purely a 'nice-to-have').

I personally think it would be simpler to just have a way to tell black to not modify text in comments, since that's the never ending battle between tools and only Black is the one breaking others.
