### ISSUE TITLE
Crash under PyPy 7.0.0

### ISSUE THREAD

**Issue by dholth** [psf/black#780]
black v19.3v0, running on PyPy

Python 3.6.1 (dab365a46514, Feb 05 2019, 18:05:11)
[PyPy 7.0.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]

`error: cannot format x.py: 'PosixPath' does not support the buffer interface`

The file appears to have been reformatted anyway.

PyPy 7.1 has the same issue.

**Comment by glyph** [comment]
Has this been filed against PyPy as well?  This seems like divergent behavior which could be fixed there.

**Comment by dholth** [comment]
Good idea, I reported it there and they were able to reproduce the issue.

**Comment by hugovk** [comment]
For reference: https://bitbucket.org/pypy/pypy/issues/3015/black-crashes-on-pypy-7-with-posixpath

**Comment by JelleZijlstra** [comment]
So the problematic call looks like `os.replace('x.py', pathlib.PosixPath('y.py'))`. To unblock users of Black, I'd accept a PR that makes our call to `os.replace` call `str()` on its arguments first.

**Comment by glyph** [comment]
Is this still a crasher?

**Comment by lietu** [comment]
It just crashed for me, so I guess it is. On PyPy 7.1.1 (on Ubuntu 16.04, `pyenv install pypy3.6-7.1.1`)

**Comment by hugovk** [comment]
I had a go testing Black with `pypy3` on Travis CI:

* https://github.com/hugovk/black/commit/d9a1e31e45d101ab2b9dcab0db9d4b5091c43048

And there's an error installing one of Black's dependencies:

* `Building wheel for typed-ast (setup.py) ... error`

https://travis-ci.org/hugovk/black/jobs/567758215#L251

Unfortunately Typed AST doesn't support PyPy3. From Guido:

> Yeah, it was never meant to run against PyPy. Once PyPy catches up with
Python 3.8 and we stop caring about 2.7 it should be possible to run mypy
under PyPy -- when run under Python 3.8 or later it uses the stdlib ast
module (which has grown APIs to request type comments and to support
earlier grammar versions (to some extent).

* https://github.com/python/typed_ast/issues/97#issuecomment-484337454

**Comment by paugier** [comment]
These kinds of problems (`error: cannot format x.py: 'PosixPath' does not support the buffer interface`) have been fixed with PyPy3.6 7.2.0 (the first stable release of pypy3.6).

Now, the blocker for PyPy is the new `typed-ast` dependency (see https://github.com/psf/black/issues/727#issuecomment-547338207).

**Comment by JelleZijlstra** [comment]
Sounds like the original issue has been fixed in PyPy. #727 can track PyPy support in general.
