### ISSUE TITLE
Reconsider formatting that was changed by #762

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#781]
#762 fixed broken code, but in many cases the old, broken code produced subjectively better formatting, especially (in my experience) around assert statements.

Let's consider whether there's a way to improve the formatting in cases that were affected by #762.

It would be helpful to add examples to this issue of formatting changes caused by #762 that may not be improvements.

**Comment by rouge8** [comment]
I think this might also be a bug, because it's now producing some lines that are longer than 88 characters. 😞 

An examples from one of our codebases:

### Before

```python
class Foo:

    def meth(self):
        allow_partial_registration = (
            self.allow_partial_registration_completion
            and state.get("allow_partial_registration")
        )
```

### After

```python
class Foo:

    def meth(self):
        # the next line is 94 characters!
        allow_partial_registration = self.allow_partial_registration_completion and state.get(
            "allow_partial_registration"
        )
```

I also see it with several tests, where #762 changed

```python
assert (
    something_long
    == something_else_very_long.method_call(x)
)
```

into

```python
# in the actual code base, these exceed 88 characters
assert something_long == something_else_very_long.method_call(
    x
)
```

**Comment by zsol** [comment]
I suspect most of these problems stem from the fact that black doesn't consider all possible parenthesis while doing `right_hand_split` (invisible parens don't count).

I'm toying with a change that converts all invisible parenthesis to visible before doing the formatting, but haven't yet figured out how to eliminate "useless" ones afterwards yet.

**Comment by ambv** [comment]
It would be a simpler change to change `if bt.delimiter_count_with_priority(max_priority) > 1` to be effectively ">= 1". I considered it at the time and I was on the fence on whether I liked the additional parentheses (which often cause more vertical space to be used).

**Comment by zsol** [comment]
I agree that would result in simpler code in Black, but in cases where there's only one delimiter with max priority and it's towards the end of the line, it ends up being subjectively worse in my opinion. Case in point:

```
-        return (first_leaf.type == token.NAME and first_leaf.value == "def") or (
-            first_leaf.type == token.ASYNC
-            and second_leaf is not None
-            and second_leaf.type == token.NAME
-            and second_leaf.value == "def"
+        return (
+            (first_leaf.type == token.NAME and first_leaf.value == "def")
+            or (
+                first_leaf.type == token.ASYNC
+                and second_leaf is not None
+                and second_leaf.type == token.NAME
+                and second_leaf.value == "def"
+            )
         )
```

**Comment by zsol** [comment]
On the other hand, your suggestion would make the examples in #348 look better. I'll try that version internally and see the effect.

**Comment by gr4viton** [comment]
> I suspect most of these problems stem from the fact that black doesn't consider all possible parenthesis while doing right_hand_split (invisible parens don't count).
>
> I'm toying with a change that converts all invisible parenthesis to visible before doing the formatting, but haven't yet figured out how to eliminate "useless" ones afterwards yet.
> https://github.com/python/black/issues/781#issuecomment-488121599

Possible way to `eliminate "useless" ones afterwards`.

I do not know how black annotates individual characters - if it annotates them at all. 
If every char is not only "an index in the str", but is a separate object. Then you can do what you want without the need to eliminate the the "invisibal parenthesis" afterwards

Eg. str would get converted to `AnnotatedStr` where in annotated you can store any info for each string
```py
txt = "if a == b and c == d:"
astr = AnnotatedStr(txt)
assert astr.text_raw == txt
astr.show_annotated == "if (a == b) and (c == d):"
```
Then to get the `text_raw` formatted as with anotations, you would go alphanum chars through the annotated and formated text and would only print those chars which are in the original.
```py
formatted = "".join(
   ch for ch in asrt.show_annotated if ch == " " or ch in asrt.text_raw
)
```
