### ISSUE TITLE
File watcher empties newly created file when Blackifying in IDEA

### ISSUE THREAD

**Issue by dms-cat** [psf/black#793]
Operating system: Arch Linux
Python version: 3.6.7
*Black* version: 18.9b0
IDEA version: 2018.3.6
File Watchers version: v183.4139.22
Does also happen on master: Untested

# To reproduce

1. Set up the file watcher according to the [instructions](https://github.com/ambv/black/blob/master/README.md#pycharmintellij-idea).
1. Open a Python file with a class declaration (this is in a medium-size project, so timing might be relevant).
1. Click F6.
1. Specify a path to a new file.
1. Click OK.

# What should happen?

The code should be moved, and then Black should correct any formatting issues in the old and new file caused by IDEA.

# What happens instead?

The code is removed from the original file, but the new file is *empty.*

I don't know whether the problem is with Black or the file watcher plugin, so I'll be reporting to both. [File Watchers report](https://youtrack.jetbrains.com/issue/PY-35144)

**Comment by zsol** [comment]
I suspect this is not a problem with Black itself, but going to keep this open to see if we can improve our docs about setting up IDEA integration without such a race condition.

**Comment by JelleZijlstra** [comment]
Closing as there has been no progress and this is likely not an issue with Black. Our IDEA integration is documented in https://black.readthedocs.io/en/latest/integrations/editors.html#pycharm-intellij-idea.
