### ISSUE TITLE
Can't use Black 19.3b0 from terminal

### ISSUE THREAD

**Issue by danieltudosiu** [psf/black#795]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 18.04
Python version: 3.6.7
*Black* version: 19.3b0
Does also happen on master: Did not try

I have installed Black through the command:
`
pip3 install black
`
And it resulted in the following output:

`
Collecting black
  Using cached https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl
Collecting toml>=0.9.4 (from black)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting appdirs (from black)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting attrs>=18.1.0 (from black)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting click>=6.5 (from black)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Installing collected packages: toml, appdirs, attrs, click, black
Successfully installed appdirs-1.4.3 attrs-19.1.0 black-19.3b0 click-7.0 toml-0.10.0
`

But if I try to run it from the command line I get:

`
Command 'black' not found, did you mean:
  command 'slack' from snap slack (3.3.8)
  command 'slack' from deb slack
See 'snap info <snapname>' for additional versions.
`

I wish to install it in a way that will be available from the terminal and use it with Pycharm.

Thank you!

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

**Comment by wbolster** [comment]
this is likely because your `$PATH` is not set up correctly. in general i would advise you to use a `virtualenv`, or use a tool such as `pipsi`.

**Comment by David-OConnor** [comment]
This should be included in the docs: The dude's running a stock Ubuntu config.
