### ISSUE TITLE
Formatting command line arg lists

### ISSUE THREAD

**Issue by flying-sheep** [psf/black#799]
Hi!

I’d like to format a list of command line arguments to pass to a command.

Before black, I’d have done

```py
args = [
    self.config.blast_path,
    "-reward", "1",
    "-gapopen", "-5",
    "-gapextend", "-5",
    "-outfmt", "6",  # tabular
    "-db", self.config.blast_dbpath,
]
```

But now black of course puts name and value each on one line.

How can I elegantly avoid that? I think this is too much noise:

```py
args = [
    self.config.blast_path,
    *("-reward", "1"),
    *("-gapopen", "-5"),
    *("-gapextend", "-5"),
    *("-outfmt", "6"),  # tabular
    *("-db", self.config.blast_dbpath),
]
```

But creating a whole function just to have nicer code is a bit much work:

```py
args = create_arglist(
    self.config.blast_path,
    reward=1,
    ...,
    _long_arg_prefix="-",
)

**Comment by zsol** [comment]
Not sure about your sense of elegance (I'd be fine with the initial version TBH), but you could:

```
options = { "-reward": "1", "-outfmt", "6" }  # ...
args = [ self.config.blast_path, *(options.items()) ]
```

_I wish we had black formatting code snippets in github comments_

**Comment by JelleZijlstra** [comment]
@zsol that doesn't work:
```
In [1592]: options = { "-reward": "1", "-outfmt": "6" }  # ...
      ...: args = [ "self.config.blast_path", *(options.items()) ]

In [1593]: args
Out[1593]: ['self.config.blast_path', ('-reward', '1'), ('-outfmt', '6')]
```
I suppose it could work if you itertools.chain it, but that's even more noise.

---

As for the original question, I'm not sure there's much Black could do here; we could hardly automatically detect that a list is intended as a command line and change formatting based on that.

**Comment by char101** [comment]
Maybe disable formatting on the list:

```python
# fmt: off
args = [
    self.config.blast_path,
    "-reward", "1",
    "-gapopen", "-5",
    "-gapextend", "-5",
    "-outfmt", "6",  # tabular
    "-db", self.config.blast_dbpath,
]
# fmt: on
```

**Comment by drunkwcodes** [comment]
No. The canceling function should be automatic.

Maybe we can evaluate the alignment level by the position of commas and revert the formatting if the they vary more than the origninal block.

**Comment by felix-hilden** [comment]
We like consistency, generality and not taking previous formatting into account, so I agree that there's not much we can do beyond asking you to disable formatting manually.
