### ISSUE TITLE
failure to reformat multiline dict with inline comments in a reasonable manner

### ISSUE THREAD

**Issue by bhearsum** [psf/black#800]
Operating system: Linux
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: ✔️

Code before:
```
    SYSLOG_LEVEL_MAP = {
        50: 2,  # CRITICAL
        40: 3,  # ERROR
        30: 4,  # WARNING
        20: 6,  # INFO
        10: 7,  # DEBUG
}
```

After:
```
SYSLOG_LEVEL_MAP = {50: 2, 40: 3, 30: 4, 20: 6, 10: 7}  # CRITICAL  # ERROR  # WARNING  # INFO  # DEBUG
```

Formatting works correctly with both a shorter line length, and trimming the dictionary to be less than 88 characters. (In those cases, Black doesn't do anything do the code.)

**Comment by mozbhearsum** [comment]
Possibly similar or related to #379?

**Comment by JelleZijlstra** [comment]
#826 would fix this.

**Comment by JelleZijlstra** [comment]
> #826 would fix this

And so it did.
