### ISSUE TITLE
format_str() doesn't have line_length argument anymore

### ISSUE THREAD

**Issue by daureg** [psf/black#805]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Linux
Python version: 3.7
*Black* version: 19.3b0
Does also happen on master: probably

commit 36d3c516d3c09fc5f05c420900d removed the `line_length` argument of `format_str()` but didn't update its documentation. It's also breaking the [blackcellmagic](https://github.com/csurfer/blackcellmagic) jupyter notebook extension.

**Comment by peterjc** [comment]
It wasn't just ``format_str()`` which lost the ``line_length`` argument, also ``format_file_contents()`` changed which broke my flake8 plugin:

https://github.com/peterjc/flake8-black/issues/3
https://github.com/peterjc/flake8-black/commit/d75a7e8e94de011ac3327a0f503992761a76c7ce

You now have to create a ``FileMode`` object, and that holds the line length (see my workaround, link above).

**Comment by ichard26** [comment]
Yeah, sorry about breaking the "public" API. We should start thinking about a documented abstract public API since Black is getting ever closer to its first stable release. Related: #779
