### ISSUE TITLE
Line too long: Lambda in dictionary value

### ISSUE THREAD

**Issue by alexbecker** [psf/black#808]
Input (which I also think is a good format for output):
```python
{
    "some very long dictionary key string goes here":
        lambda: some_very_long_function_name(x, y, z)
}
```
Output:
```python
{
    "some very long dictionary key string goes here": lambda: some_very_long_function_name(
        x, y, z
    )
}
```
Note that the second line is >88 characters.

Possibly related to https://github.com/ambv/black/issues/781?

Operating system: Linux
Python version: 3.6.3
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by DANIELF01** [comment]
@JelleZijlstra this looks similar to to my comment: https://github.com/psf/black/issues/1161#issuecomment-876345158. At least in the sense that line length does not see to be respected for long/odd dictionary declarations.
