### ISSUE TITLE
Include in pyproject.toml work to only use top level directories

### ISSUE THREAD

**Issue by mlucool** [psf/black#810]
Operating system: Linux
Python version: 3.7
*Black* version: 19.3b0

How can I specify in `pyproject.tolm` directories relative to the top level that I'd like to include? Ideally I want something like: `['./foo/*.py$', './bar/*.py$']`. The goal is to allow others to run `black .`  and never worry about needing to exclude every new directory that is added.

**Comment by samuelhwilliams** [comment]
Specifying paths in the toml file seems way more complicated than it feels like it should... I want to include `app.py` at the base level, python files directly inside `./chalicelib`, and nothing else...

**Comment by ichard26** [comment]
It's been over two years since this issue was opened (sorry for the delay!) but here's an example for anyone who stumbles on this in search of help:
```toml
include = '''
/(
  | first-level-dir/.*\.pyi?
  | second-level/dir/.*\.pyi?
  | some-random-top-level-file.py
)
'''
```
