### ISSUE TITLE
Unexpected line break in subscript

### ISSUE THREAD

**Issue by cducrest** [psf/black#814]
Operating system: Linux
Python version: 3.6.7
*Black* version: 19.3b0
Does also happen on master: kind of

With black 19.3b0, I notice the following behaviour

```py3
# in == out:

def test_black_expected_behaviour():

    alice = pretty_long_name_but_not_too_long.action.do_something(
        action=None
    ).do_other_thing()[0]["args"]


def test_black_unexpected_behaviour():

    alice = pretty_long_name_and_actually_long_enough_to_make_it_weird.action.do_something(
        action=None
    ).do_other_thing()[
        0
    ][
        "args"
    ]
```

I would expect the second function to be formatted in a similar way as the first one. i tried it out with `master` [version online](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHJAOJdAD2IimZxl1N_WlbvK5V_5PM4OL5k5ukXP3WkeKePuRbkwE_TzG1UKp3G0ifjt_Msv7AfuVD93b_L5r2MP2ZF2ZQRb8__AasFO6k08vPduGIyQVGJMwuc_qaoRLjsl1DCRWkNPvT15hPIz0Lnl1Fc1uTZIJ6SHcmomWzvEs5WLP1p9bKBSnEn0ZrX3SZ3DC3XSG6eOUhQYjqurke74hyB5_jBvvWmq-HSQJhSNqw1jUWdDKq1oX3KwYLdA9jGqrT9cupesY1eZywIsRtZ4i612GCbIFkv1bvXtr6lse5tfk0nyXYAAAAWQCHzkDxvkQAB_gHKAwAAPzUbyrHEZ_sCAAAAAARZWg==)

This brings the following result:

```py3
# out:

def test_black_expected_behaviour():

    alice = pretty_long_name_but_not_too_long.action.do_something(
        action=None
    ).do_other_thing()[
        0
    ][
        "args"
    ]


def test_black_unexpected_behaviour():

    alice = pretty_long_name_and_actually_long_enough_to_make_it_weird.action.do_something(
        action=None
    ).do_other_thing()[
        0
    ][
        "args"
    ]

```

This second result seems better because more consistent, but I am not sure it is the expected behaviour since `for vertical whitespace, Black tries to render one full expression or simple statement per line. If this fits the allotted line length`.

Feel free to close this issue if you consider this to be the wished for behaviour of black, or consider this as a bug / to be improved otherwise.

**Comment by graingert** [comment]
there seems to be a few duplicates of this:

https://github.com/psf/black/issues/814
https://github.com/psf/black/issues/1101
https://github.com/psf/black/issues/1406

**Comment by ichard26** [comment]
Thank you @graingert for letting me know about those pesky duplicates! I typically don't check design issues for duplicates as clear duplicates are harder to identify. I've closed them now and marked them as duplicates.

**Comment by JelleZijlstra** [comment]
This is #236.
