### ISSUE TITLE
black reformats conditionals to be too long

### ISSUE THREAD

**Issue by rouge8** [psf/black#815]
Black sometimes reformats conditionals (and possibly other code) to exceed the 88 character line length.

Given code like this:

```python
def f():
    def g():
        def h():
            if (
                expected_sig != sig.strip()
                and expected_sig != six.moves.urllib.parse.unquote_plus(sig.strip())
            ):
                something()
```

Black reformats it to:

```python
def f():
    def g():
        def h():
            if expected_sig != sig.strip() and expected_sig != six.moves.urllib.parse.unquote_plus(
                sig.strip()
            ):
                something()
```

which is longer than 88 characters.

Operating system: OS X
Python version: 3.7.3
*Black* version: d6db1c12a8e14833fe22da377cddc2bd1f43dc14
Does also happen on master: yes

**Comment by Aareon** [comment]
I believe black should probably (assuming its not doing so already) perform a check whether conditional subsections (parts between `and`/`or`) can/should be split between lines depending on how long each section will make a specific line.

**Comment by ichard26** [comment]
Closing as this bug doesn't exist after commit 586d24236e6b57bc3b5da85fdbe2563835021076. Thanks for reporting the bug though!
