### ISSUE TITLE
Switching between function call styles results in redundant diff

### ISSUE THREAD

**Issue by PeterJCLaw** [psf/black#849]
Operating system: Ubuntu 16.04
Python version: 3.6.8
*Black* version: 188c31db7c831741e69b067c53dd040917ac03f7
Does also happen on master: yes

Consider starting with:
``` python
user_count = cache.get_or_set(
    lambda: User.objects.filter(
        user_property__in=(
            "first_property_of_a_user",
            "second_property_of_a_user",
            "third_property_of_a_user",
        )
    )
    .exclude(something=False)
    .count(),
    123456,
)
```
and removing the line `.exclude(something=False)`, then `black` will reformat the lambda content as:
``` python
user_count = cache.get_or_set(
    lambda: User.objects.filter(
        user_property__in=(
            "first_property_of_a_user",
            "second_property_of_a_user",
            "third_property_of_a_user",
        )
    ).count(),
    123456,
)
```
The move of the `.count()` up onto the previous line turns what would otherwise be a one-line diff into a three line diff, with two of those being unrelated.

I'm guessing this is caused by `black` switching from the formatting style for chained functions usually seen within parenthesis and the style usually seen outside of them?

**Comment by JelleZijlstra** [comment]
Yes, this is a result of the style chosen for fluent interfaces (#67). I don't think we can reasonably change this.

**Comment by PeterJCLaw** [comment]
Thanks for the response, however this feels like a fairly clear bug which goes against black's goals - in particular this can result in quite a lot of diff noise (though it also kinda undermines the idea that code "looks the same" everywhere).

Here's a perhaps clearer extreme example of the diff noise that this change causes:

``` python
user_count = (
    User.objects.filter(
        user_property__in=(
            "first_property_of_a_user",
            "second_property_of_a_user",
            "third_property_of_a_user",
        )
    )
    .exclude(something_else=False)
    .count()
)
```
drop the `.exclude(something_else=False)` and you get this output:
```python
user_count = User.objects.filter(
    user_property__in=(
        "first_property_of_a_user",
        "second_property_of_a_user",
        "third_property_of_a_user",
    )
).count()
```
I'm happy with that output on its own, however here's the diff:
```diff
-user_count = (
-    User.objects.filter(
-        user_property__in=(
-            "first_property_of_a_user",
-            "second_property_of_a_user",
-            "third_property_of_a_user",
-        )
-        .exclude(something_else=False)
+user_count = User.objects.filter(
+    user_property__in=(
+        "first_property_of_a_user",
+        "second_property_of_a_user",
+        "third_property_of_a_user",
     )
-    .count()
-)
+).count()
```
It's a little bit better if you ask the diff tool to ignore whitespace, but still has a lot of noise that distracts from the actual change:
```diff
-user_count = (
-    User.objects.filter(
+user_count = User.objects.filter(
     user_property__in=(
         "first_property_of_a_user",
         "second_property_of_a_user",
         "third_property_of_a_user",
     )
-    )
-    .exclude(something_else=False)
-    .count()
-)
+).count()
```

The issue here seems to be that black has multiple styles and chooses between them in what feel like an arbitrary manner, creating diff noise where having only one style would not.
I realise the choice is likely not actually arbitrary, though it's not obvious from the above code snippets or the change what the reasoning is. To me the fact that there is reasoning to be done in order to understand the choice is part of the problem.

I think I do now understand what's causing this though (thanks for the link to the discussion on fluent interfaces); I guess my question now is why three chained calls count but two don't?

Aside: while I have a preference over which of these styles I want to use, that's not what this issue is about. If there were an option to force black to pick exactly one of these styles that would IMO be ideal (both for developer choice and letting the tool have a single option to be consistent about), though I'm not holding much hope for that happening.
