### ISSUE TITLE
A couple of weird things I have found.

### ISSUE THREAD

**Issue by maxisme** [psf/black#856]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version: `Python 3.7.3`
*Black* version: `black, version 19.3b0`
Does also happen on master: Yes

When I run `$ black *`
 - Mishap 1:
My `requirements.txt` which contains `opencv-python` this is getting updated to `opencv - python`.

 -  Mishap 2:
A dictionary like `config.settings["foo"]["bar"]["baz"] = 1` is getting converted to:
```
config.settings["foo"]["bar"][
    "baz"
] = 1
``` 
even within the max line.

**Comment by JelleZijlstra** [comment]
For your first problem, you should probably run `black .` instead, so Black runs only on Python files, not files that aren't Python but happen to be parseable as such.

**Comment by hugovk** [comment]
For your second problem, I cannot reproduce it locally with the same Python and Black 19.3b0 or with [black.now.sh](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABuAFNdAD2IimZxl1N_WlXpD4Gl3S9TZ-_UpCcKwEbOWf4AWBWTP5e_gGcRTPfVoaWqO7z9Hvt2-e003E4aY2ecmLZJty7YcNw2pXytSEEjn0wRvvHlXKYAAAANVwpLuSsrRAABb2-Kvu4fH7bzfQEAAAAABFla) (also 19.3b0).

What config settings do you have?

**Comment by robin-bloehm-mck** [comment]
I can reproduce "Mishap 2" using line length 30:
[black.now.sh](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABuAFNdAD2IimZxl1N_WlXpD4Gl3S9TZ-_UpCcKwEbOWf4AWBWTP5e_gGcRTPfVoaWqO7z9Hvt2-e003E4ZKTZieATxDeSEtnMT8irX_n2btV6qs5fvHY8AAACWwHbxscPHNgABb2-Kvu4fH7bzfQEAAAAABFla)
But this is probably not a very typical setting.

**Comment by zsol** [comment]
@robin-bloehm-mck what do you prefer Black to do in that case?
