### ISSUE TITLE
Set up Coveralls and AppVeyor for psf/black

### ISSUE THREAD

**Issue by hugovk** [psf/black#864]
* [x] Enable Coveralls at https://coveralls.io/github/psf/black
* [ ] Enable AppVeyor at https://ci.appveyor.com/project/psf/black

---

Since the repo moved into the ~Python~ PSF organisation, Coveralls needs updating:

![image](https://user-images.githubusercontent.com/1324225/58260230-c1a9e900-7d7e-11e9-804d-03da0b191f42.png)

https://github.com/psf/black/blob/master/README.md

![image](https://user-images.githubusercontent.com/1324225/58260273-d71f1300-7d7e-11e9-96b0-4fedf96ee37e.png)

https://coveralls.io/github/psf/black?branch=master

It's also missing from PRs, for example https://github.com/psf/black/pull/935:

![image](https://user-images.githubusercontent.com/1324225/61848150-cb061d80-aeb5-11e9-919b-5a4b46105013.png)

Also AppVeyor needs enabling.

**Comment by hugovk** [comment]
Is this something @ambv or @psf can take care of?

**Comment by zsol** [comment]
Coveralls is done

**Comment by hugovk** [comment]
Closing, AppVeyor is no longer used (https://github.com/psf/black/pull/1401).
