### ISSUE TITLE
Inconsistent README formatting

### ISSUE THREAD

**Issue by yhoiseth** [psf/black#869]
Operating system: Not relevant
Python version: Not relevant
*Black* version: Not relevant
Does also happen on master: Not relevant

The README formatting appears inconsistent to me. Most lines seem to be limited to about 80 characters, but some are much longer. For example, the first line in the _Configuration format_ section is 124 characters.

This is by no means a big problem, but it did cause me to pause when I proposed a change to the documentation in #866.

I'll try to propose a fix.

**Comment by hugovk** [comment]
https://github.com/psf/black/pull/874 has been merged, this issue can be closed.

---

Tip: https://github.com/psf/black/pull/874#issuecomment-544280566 says:

> Closes #869.

That needs to be in the PR description to autoclose, not in a comment.
