### ISSUE TITLE
Misleading message when black checks only empty directories

### ISSUE THREAD

**Issue by chkoar** [psf/black#886]
If I provide to black a directory or several directories that exist but they are empty (all of them) black reports the following:
> No paths given. Nothing to do  

I used the following command
`black example1 example2`

The message should be different  because I have actually provided the paths. They are empty, though.

Operating system: Windows
Python version: 3.6.3
*Black* version: 19.3b0
Does also happen on master: Yes

**Comment by Jma353** [comment]
It looks like a fix for this was merged in.  Can this be closed?

**Comment by chkoar** [comment]
Did you test it with master? Which is the PR that fixed the indented behaviour?

**Comment by Rishi-jha** [comment]
I have created a PR, Please have a look.

**Comment by Rishi-jha** [comment]
[PR link](https://github.com/psf/black/pull/999)
This PR is approved, please merge, :)

**Comment by Rishi-jha** [comment]
#999
