### ISSUE TITLE
Black adds unnecessary parentheses around tuples of one element

### ISSUE THREAD

**Issue by layoaster** [psf/black#897]
Operating system: Ubuntu 19.04
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

Black forces the use of parentheses on tuples of one element without parentheses. Check the black diff below:

```diff
class LivenessProbe(View):
"""Liveness probe handler."""
-    methods = "GET",
+    methods = ("GET",)
def dispatch_request(self) -> Response:
```

**Comment by JelleZijlstra** [comment]
I'd say this is a feature, not a bug. A single comma is easy to miss, and the parentheses make it clearer that it's a tuple.

**Comment by andrewmwilson** [comment]
The fact that `methods = "GET",` is valid python syntax is incredibly annoying. It causes so many hard-to-find bugs and is basically useless.

**Comment by JelleZijlstra** [comment]
No action required here.

**Comment by jotradovec** [comment]
> I'd say this is a feature, not a bug. A single comma is easy to miss, and the parentheses make it clearer that it's a tuple.

Why?

**Comment by hauntsaninja** [comment]
> A single comma is easy to miss, and the parentheses make it clearer that it's a tuple.

**Comment by jotradovec** [comment]
@hauntsaninja 
But if I do 
`type(SomeEnum.SOME.value)`  than it is str for a = "some_str" and not tuple

This style even leads to this:
`from enum import Enum

class MyEnum(str, Enum):
    a = ("A","C")
    b = ("B")

print(MyEnum.a.value)`
Which throws TypeError: decoding str is not supported
