### ISSUE TITLE
NameError: name 'Black' is not defined

### ISSUE THREAD

**Issue by GianniGi** [psf/black#898]
Hello, install through plug doesn't work

this appears on startup
Traceback (most recent call last):
 File "<string>", line 1, in <module>
NameError: name 'Black' is not defined
Press ENTER or type command to continue

vim 8.1 on ubuntu

vimrc contains 
Plug 'python/black'

on windows it works (same vimrc)

**Comment by jneo8** [comment]
Same issue

**Comment by jneo8** [comment]
> Same issue

Solved after #https://github.com/psf/black/issues/1379#issuecomment-636284097

**Comment by JelleZijlstra** [comment]
Sounds like this is fixed.

**Comment by nullromo** [comment]
**Note**: for me I had to run `:messages` in vim to see that it was complaining about not having `ensurepip`. Based on that I had to `sudo apt-get install python3.8-venv`, then `rm -rf ~/.vim/black`, then `:Black` and then finally it worked.

**Comment by davehouser1** [comment]
My problem was I tried to run `:Black` in my active `pyenv-virtualenvwrapper`. Solution was to 

```
$ deactivate
$ rm -rf ~/.vim/black
$ vim
$ <esc> :Black
```
This installed black properly. Then I existed vim, started up my pyenv-virtualenvwrapper `workon myproject`, and was able to rum vim and `:Black` with no problems.

**Comment by naught101** [comment]
For me on a new *buntu and using black installed from apt, I needed to add

```{vim}
let g:black_virtualenv = ""
```

To my .vimrc to get it to play nice

(sorry for the zombie thread, figure it might be useful for someone, since this is what comes up in web searches)
