### ISSUE TITLE
# fmt: off should not add trailing newline

### ISSUE THREAD

**Issue by clbarnes** [psf/black#899]
Prettier calls this concept "require pragma".

Sometimes you're in a big project whose git history is too valuable to entirely blow away by reformatting. But you want your new files to be blackened, and if major changes are made to old files, blacken them at that point (and not before). A simple way to do this would be to look for a comment like `# @black` before any definitions, and add a CLI flag which allows non-marked files to be skipped.

**Comment by zsol** [comment]
I think this is a reasonable approach, but I'd like to point out that the opposite is already possible: you can mark all your existing files with `# fmt: off` at the beginning and Black won't touch them. Any new files you add without this will be formatted though.

**Comment by clbarnes** [comment]
Good point - so all that would need to happen would be a "strict mode" command line option which *only* formats `# fmt: on` blocks.

**Comment by paranoidi** [comment]
@zsol that `# fmt: off` is not documented anywhere afaik, would be appreciated if it was

**Comment by zsol** [comment]
It's documented [here](https://github.com/python/black#the-black-code-style). The empty line at the end of the file looks like a bug at first glance. Feel free to open a separate issue about it

**Comment by ichard26** [comment]
A workaround for now is to format everything and skipping the commit in git history. More info [in the docs](https://github.com/psf/black/tree/master/#migrating-your-code-style-without-ruining-git-blame)

**Comment by hauntsaninja** [comment]
I think `# fmt: off`, git ignore blame and tools like https://github.com/akaihola/darker fix the original ask.

The only thing remaining in this issue is whether `# fmt: off` should avoid adding trailing new lines.

**Comment by hauntsaninja** [comment]
Actually, that ask is better tracked at https://github.com/psf/black/issues/496
