### ISSUE TITLE
Black produced different code on the second pass of the formatter: Explicit line join in the first line

### ISSUE THREAD

**Issue by dizzy57** [psf/black#922]
Operating system: macOS Mojave 10.14.5 (18F132)
Python version: Python 3.7.3
*Black* version: 19.3b0 (f3bb22a828)
Does also happen on master: yes

Minified reproducer:
```python
\


pass
```

Black diff:
```diff
--- source
+++ first pass
@@ -1,5 +1,3 @@
-\
-

 pass

--- first pass
+++ second pass
@@ -1,3 +1,2 @@
-
 pass
```

Looks like some kind of boundary condition in `EmptyLineTracker`?

**Comment by Jma353** [comment]
I have a proposed fix for this in #948 - open to review (cc: @zsol).
