### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 603: illegal multibyte sequence

### ISSUE THREAD

**Issue by wangg12** [psf/black#931]
Can not install black on windows 10 with `pip install black`.  
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 603: illegal multibyte sequence
```

Operating system: Windows 10
Python version: 3.7

**Comment by wangg12** [comment]
Solved by adding `from io import open` in setup.py

**Comment by asottile** [comment]
that shouldn't make a difference:

```pycon
>>> import io
>>> io.open is open
True
```

**Comment by wangg12** [comment]
on Windows?

**Comment by asottile** [comment]
yes, that's python3.7 on windows

**Comment by wangg12** [comment]
so the problem is the pip package?

**Comment by asottile** [comment]
unclear, you didn't post the full output and original command

**Comment by zsol** [comment]
Can't reproduce. Please reopen with more details (and make sure you're using the latest pip)
