### ISSUE TITLE
Should have only one blank line between a comment block and a function definition

### ISSUE THREAD

**Issue by rhettinger** [psf/black#932]
The purpose of a double blank line is to divide separate blocks on thought.   However, paragraph-style block comments before a function are tightly related.  So there should be only one blank line:

```
# Notes on methods for computing quantiles
# ----------------------------------------
#
# There is no one perfect way to compute quantiles.  Here we offer
# two methods that serve common needs.  Most other packages
# surveyed offered at least one or both of these two, making them
# "standard" in the sense of "widely-adopted and reproducible".
# They are also easy to explain, easy to compute manually, and have
# straight-forward interpretations that aren't surprising.

def quantiles(dist, /, *, n=4, method='exclusive'):
    """Divide *dist* into *n* continuous intervals with equal probability.

    Returns a list of (n - 1) cut points separating the intervals.
    """
    ...
```

In the above example, Black currently inserts an extra blank line before the function definition, creating a weird disconnect between the comment and its associated function definition.

**Comment by fat-fighter** [comment]
```
# Notes on methods for computing quantiles
# ----------------------------------------
#
# There is no one perfect way to compute quantiles.  Here we offer
# two methods that serve common needs.  Most other packages
# surveyed offered at least one or both of these two, making them
# "standard" in the sense of "widely-adopted and reproducible".
# They are also easy to explain, easy to compute manually, and have
# straight-forward interpretations that aren't surprising.


def quantiles(dist, a, b, n=4, method="exclusive"):
    """Divide *dist* into *n* continuous intervals with equal probability.

    Returns a list of (n - 1) cut points separating the intervals.
    """
    pass
```

For this code, if I put a single line gap between the comment and the function definition, black increases the gap to 2 lines. On the other hand, if I do not leave any gap, then it stays that way. Isn't this the desired behavior?

If you are observing something different, try upgrading black (just a guess)?

**Comment by zsol** [comment]
I think @rhettinger's point is that Black shouldn't increase the gap to 2 lines in the case of a comment block (assuming that comment block is relevant to the function below and not to the one above).

I'm not sure I agree yet, but will keep this open.

In the meanwhile, you can put `fmt: off/on` comments around the relevant comment like so:
```python
# fmt: off
# Notes on methods for computing quantiles
# ...
# straight-forward interpretations that aren't surprising.

# fmt: on
def quantiles(dist, /, *, n=4, method='exclusive'):
    ...
```

**Comment by ambv** [comment]
@rhettinger, the way you solve this in Black is you *remove* one empty line, this way visibly tying the preceeding comment to the function. In this case two blank lines won't be inserted.

**Comment by excitoon** [comment]
A solution may be just to remove the comment.
