### ISSUE TITLE
Space added before `:` causes E203 error from flake8

### ISSUE THREAD

**Issue by dpursehouse** [psf/black#940]
`black` produces this diff:

```
-        content = content[len(GERRIT_MAGIC_JSON_PREFIX):]
+        content = content[len(GERRIT_MAGIC_JSON_PREFIX) :]
```

which causes an error from `flake8`:

```
E203 whitespace before ':'
```

I've worked around it by doing this:

```
-        content = content[len(GERRIT_MAGIC_JSON_PREFIX) :]
+        index = len(GERRIT_MAGIC_JSON_PREFIX)
+        content = content[index:]
```

but it would be nice if it didn't add that extra space.

Operating system: OSX
Python version: 3.7.4
*Black* version: 19.3b0
Does also happen on master: yes.

**Comment by JelleZijlstra** [comment]
This is mentioned in https://github.com/psf/black#slices.

**Comment by dpursehouse** [comment]
@JelleZijlstra Ah, I overlooked that.  Thanks.
