### ISSUE TITLE
Unstable formatting on multiline string with parens.

### ISSUE THREAD

**Issue by adamfaulkner** [psf/black#954]
Operating system: Linux, ubuntu 19.04
Python version: 3.7.3
*Black* version: 19.0b3
Does also happen on master: yes
---

This exhibits unstable formatting. I wasn't able to find a more minimal test case.
```
def foo(argument):
            foo = ("""
a""").format(argument)
```

```
error: cannot format /tmp/test.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_t1e4zs2e.log
```

[blk_t1e4zs2e.log](https://github.com/psf/black/files/3454849/blk_t1e4zs2e.log)

**Comment by msullivan** [comment]
Another test case for likely the same issue:
```
details = ("""%s
              %s
           """) % (a, b)
```

**Comment by ichard26** [comment]
Just rechecked, Black on master for these examples are no longer unstable, but the formatting is .. questionable. I'll leave this open for now. 

(I'm really just removing the "unstable formatting" label because I'm doing some analysis of the instability issues we've got)

**Comment by ichard26** [comment]
Actually, I created an issue (GH-2113) about explicitly improving the style for this case so I'm going to close this as it's still half-way about instability. 

Thanks for reporting!
