### ISSUE TITLE
Intermediary rule in line breaking goes against top design principle of black

### ISSUE THREAD

**Issue by maxwellmckinnon** [psf/black#956]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version: 3.7
*Black* version: 19.3b
Does also happen on master: Yes

![image](https://user-images.githubusercontent.com/5950299/62337194-861b5180-b488-11e9-9853-e28d61e8be03.png)

Is it just my biased eyes expecting a line break to indicate one argument per line following, or is this a readability problem for anyone else? If it's more than one line to do the function call, I would prefer one argument per line, no in-between behavior exceptions.

# No!
```
# in:

ImportantClass.important_method(exc, limit, lookup_lines, capture_locals, extra_argument)

# out:

ImportantClass.important_method(
    exc, limit, lookup_lines, capture_locals, extra_argument
)
```

# If it can't be one line, always break!
```
# in:

ImportantClass.important_method(exc, limit, lookup_lines, capture_locals, extra_argument)

# out:

ImportantClass.important_method(
    exc,
    limit,
    lookup_lines,
    capture_locals,
    extra_argument
)
```

Also it violates a top design principle of black:

> Black makes code review faster by producing the smallest diffs possible.

**Comment by andrewmwilson** [comment]
I totally agree!

**Comment by zsol** [comment]
This has been discussed in #220.
