### ISSUE TITLE
Documentation inconsistent use of  _ and - in cmd line params / pyproject.toml / Vim

### ISSUE THREAD

**Issue by skewty** [psf/black#957]
### Command line arguments
* --line-length
* --target-version
* --skip-string-normalization

### pyproject.toml
* line-length
* target_version
* skip-string-normalization

### Vim
* g:black_linelength
* g:black_skip_string_normalization

Also a `skip-string-normalization = 'true'` value should be included in the example 
`pyproject.toml`.  One might think it should be an `int` because the **Vim** config uses an `int` for this.  Anyhow..there is an opportunity to be more clear about how this should be specified.

**Comment by hauntsaninja** [comment]
It's target-version with hyphen even in pyproject.toml. It's true that pyproject keys are hyphen and vim keys are underscore, but that seems acceptable to me
