### ISSUE TITLE
Unstable formatting on long assert and binary op with parenthesized operand.

### ISSUE THREAD

**Issue by brandtbucher** [psf/black#959]
**Operating system:** Ubuntu 16.04
**Python version:** Python 3.7.4
***Black* version:** e664517
**Does also happen on master:** Yes

I've verified that this is a regression from 19.3b0. This is as much as I can minimize.

It doesn't matter why the line is too long. It could be any combination of the lengths of the three elements and the indentation level. It also doesn't matter what the operator is. 

```diff
--- source
+++ first pass
@@ -1,2 +1,4 @@
-assert X, X % (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
+assert (
+    X
+), X % XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 
--- first pass
+++ second pass
@@ -1,4 +1,4 @@
-assert (
-    X
-), X % XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+assert X, (
+    X % XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+)
```

**Comment by ichard26** [comment]
Just rechecked, Black on stable and master no longer crash so I'll be closing this. @brandtbucher if you find the current output not ideal:

```python3
assert X, X % (
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
)
```

... please open a new design issue.

Thanks for reporting and sorry for taking so long to get back to you!
