### ISSUE TITLE
"Black produced different code on the second pass of the formatter." Removing parens recursively in tuple.

### ISSUE THREAD

**Issue by Jma353** [psf/black#963]
Operating system: macOS Mojave 10.14.6
Python version: Python 3.7.3
*Black* version: e66451761fab864cce9077a3ee72999543b8ef65
Does also happen on master: Yes

Unstable formatting:
````python
def example():
    return ((1, ((2))))
````

````diff
--- source
+++ first pass
@@ -1,2 +1,3 @@
 def example():
-    return ((1, ((2))))
+    return (1, (2))
+
--- first pass
+++ second pass
@@ -1,3 +1,3 @@
 def example():
-    return (1, (2))
+    return (1, 2)

````

**Comment by sadovnychyi** [comment]
```python
>>> ((1, ((2)))) == (1, 2)
True
```

You need to add commas for python to treat it as a tuple.

**Comment by JelleZijlstra** [comment]
@sadovnychyi the point of this issue is that Black doesn't remove all the parentheses at once, which leads to a runtime error when running Black. We know that adding an extra set of parentheses doesn't create a tuple.

**Comment by ichard26** [comment]
Closing since Black doesn't crash on this on master and stable. While the output still retains a bunch of unnecessary parentheses, whether and how they should be removed can be discussed in https://github.com/psf/black/issues/1123. 

Thanks for reporting!
