### ISSUE TITLE
Allow specifying number of parallel jobs

### ISSUE THREAD

**Issue by ulope** [psf/black#971]
Operating system: any
Python version: any
*Black* version: 19.3b0
Does also happen on master: yes

Black currently uses `os.cpu_count()` to derive the number of pool workers it should spawn:
https://github.com/psf/black/blob/bd0ab3cba2fb2be65985741f0a4c382b675c2876/black.py#L513

Unfortunately this number is highly unreliable in virtualized and / or containerized systems including common environments like Travis CI and Circle CI (e.g. Circle always reports 36 CPUs), leading to CPU oversubscription and thereby unnecessary slowdown.

Please add a cli option to allow explicitly passing in the number of desired workers.

**Comment by zsol** [comment]
Do you have any datapoints about the slowdown caused?

**Comment by ulope** [comment]
Well... 
Good point. Apparently I very much overestimated the amount of time black contributes to the runtime of our lint suite.

It seems for a project with ~300 files and 55k lines the difference is almost negligible.

Feel free to close if you prefer.
