### ISSUE TITLE
Kwarg Operator Spacing with type hints

### ISSUE THREAD

**Issue by gtalarico** [psf/black#973]
Not sure if this is a bug or by design - did find duplicate, apologies if I missed.

I looked for examples on the [typing docs](https://docs.python.org/3/library/typing.html) and [pep 484](https://www.python.org/dev/peps/pep-0484/)  but could find clear examples.

With regards to kwargs, usually I see this (also in pep8):
```
# Yes:
def complex(real, imag=0.0):
    return magic(r=real, i=imag)

#No:
def complex(real, imag = 0.0):
    return magic(r = real, i = imag)
```

When Type annotations are used however...:

```
# Expected
def complex(real, imag: float=0.0):
    return magic(r=real, i=imag)

# Got
def complex(real, imag: float = 0.0):
    return magic(r=real, i=imag)

# inconsistent spacing if you combine annotated and non-annotated
# note spacing around `=`
def complex(real, number=0.0, imag: float = 0.0):
    return magic(r=real, i=imag)
```

Python version: 3.7.3
*Black* version: 19.3b0

**Comment by JelleZijlstra** [comment]
This is intentional; PEP 8 explicitly allows spaces around `=` for typed arguments.
