### ISSUE TITLE
Leave new line at end of file

### ISSUE THREAD

**Issue by dsaxton** [psf/black#974]
It seems that `black` removes new lines at the ends of files, but should they be left by default (trimming when there's more than one)?  That'd be consistent with the convention preferred by `git`, for instance.

**Comment by florczakraf** [comment]
Could you please share a short reproduction example because I don't seem to understand the issue you're describing?

**Comment by dsaxton** [comment]
> Could you please share a short reproduction example because I don't seem to understand the issue you're describing?

Actually, I was mistaken; looks like `black` handles this the way I was thinking it should.
