### ISSUE TITLE
Exclude does not exclude

### ISSUE THREAD

**Issue by michael-angelozzi** [psf/black#975]
Operating system: Windows 10
Python version: 3.7
*Black* version: 19.3b0

How does black perform on "recursive searches". The phrase only appears twice, under --include and --exclude, but does not define what a "recursive searches" are. Reading the documentation and other open issues I cannot get the include and exclude issues to work, maybe I am missing the obvious here:
```
pipenv run black -S C:\code\project\src\config 
--exclude=C:/code/project/src/config/generate/master_template.py 
--exclude=C:/code/project/src/*/custom*.py
reformatted C:\code\project\src\config\generate\master_template.py
reformatted C:\code\project\src\config\generate\custom.example.py
All done! ? ? ?
```
Note the `\`'s were replaced with `/` for the regex as per the wiki. 

I tried surrounding the exclude parameter in single and in double-quotes, did not make a difference, these do not work:
```--exclude='C:/code/project/src/*/custom*.py'```
```--exclude="C:/code/project/src/*/custom*.py"```
```'--exclude=C:/code/project/src/*/custom*.py'```
```"--exclude=C:/code/project/src/*/custom*.py"```
The following also does not work (not specifying a dir, but specifiying an include dir):
```
pipenv run black -S 
--include=C:/code/project/src/config 
--exclude=C:/code/project/src/config/generate/master_template.py 
--exclude=C:/code/project/src/*/custom*.py
No paths given. Nothing to do ??
```

So how does one convert all files within a certain path, but exclude certain files? An example in the documentation would really aid understanding.

Maybe because I am unfortunately having to use windows? Is it recommended that one should one just use the pathlib glob to walk the dir and call black with just one file at a time (which is very slow to open a new subprocess, runs at about one file a second).

**Comment by zsol** [comment]
exclude and include require regular expressions, not globs. They definitely work on Windows. Feel free to reopen if you can't get it working with regexes

**Comment by michael-angelozzi** [comment]
Oh thanks, I didn't realise it was regex and not globs. However I still could not get regex to work. I checked my patterns worked with https://pythex.org/. When testing I did ensure the patterns dir separator is a forward slash. 

I took step back from regex, and could not get a literal path to be excluded:

```
pipenv run black -S C:/code/src/config --exclude=C:/code/src/config/generate/master_template.py
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config --exclude=C:\code\src\config\generate\master_template.py
Invalid regular expression for exclude

pipenv run black -S C:/code/src/config --exclude='C:/code/src/config/generate/master_template.py'
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config --exclude="C:/code/src/config/generate/master_template.py"
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config '--exclude=C:/code/src/config/generate/master_template.py'
Error: Invalid value for "[SRC]
```

Side question: In the wiki it says "Exclusions are calculated first, inclusions later."
I presume this means an inclusion trumps an exclusion? Or an inclusion takes priority over an exclusion?
