### ISSUE TITLE
Trouble parsing 2.7 code in 3.7

### ISSUE THREAD

**Issue by chebee7i** [psf/black#977]
[Turns out the problem wasn't quite what I initially thought.]

The current release (19.3b0) cannot be used using 3.7 on any 2.x code that is trying to be 3.x compatible by using the print function.

In Python 3.7.3 from black commit bd0ab3cba2fb2be65985741f0a4c382b675c2876
```console
$ cat lala.py
from __future__ import print_function

print('hello', file=sys.stdout)

$ black --target-version=py27 lala.py
error: cannot format lala.py: Cannot parse: 3:19: print('hello', file=sys.stdout)
All done! 💥 💔 💥
1 file failed to reformat.
```

But if I use the same commit and run from Python 3.6.7, then it works great:
```console
$ # different environment
$ black --target-version=py27 lala.py
reformatted lala.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

**Comment by JelleZijlstra** [comment]
I believe this is fixed in master, could you try?

**Comment by chebee7i** [comment]
Note that in my description, I mention that I am running on black commit bd0ab3c, which is the tip of master.  Doesn't seem to be fixed.

**Comment by JelleZijlstra** [comment]
Sorry for missing that!

**Comment by chebee7i** [comment]
Related: https://github.com/psf/black/issues/768

However, I am no longer able to reproduce this. Not sure what was going on....maybe some shell woes.  Closing until/if I can reproduce it again.  Guessing this will come down to user error.
