### ISSUE TITLE
Consider a different emoji sequence than :sparkle: :cake: :sparkle:

### ISSUE THREAD

**Issue by asottile** [psf/black#983]
mostly just like, I don't really want to associate black with other projects that use that same sequence

**Comment by lsh-0** [comment]
is that what this is??

![Screenshot at 2019-08-14 12-23-51](https://user-images.githubusercontent.com/2142748/62991351-78a19680-be8e-11e9-8759-82017eb20800.png)

**Comment by asottile** [comment]
yeah:

```python
>>> '\u2728'
'✨'
>>> '\U0001f370'
'🍰'
```

**Comment by kaste** [comment]
That's completely unnecessary rude, and sub-tweeting alike. You should just close this issue.

**Comment by JelleZijlstra** [comment]
I'm not really sure what this is referring to. The emoji sequence is now essentially part of Black's brand and I'm not inclined to change it.

**Comment by asottile** [comment]
it's referring to kenneth

**Comment by kaste** [comment]
The issue here is violation of CoC.  This is inappropriate and the time to reaction is also inappropriate.
