### ISSUE TITLE
Exclude does not exclude

### ISSUE THREAD

**Issue by michael-angelozzi** [psf/black#986]
Hi, I opened an issue about this but was closed, and I can't reopen it, so my only option is to create a new issue.

Operating system: Windows 10
Python version: 3.7
Black version: 19.3b0

None of the following work when trying to exclude a file, and there is no example in the wiki:
```
pipenv run black -S C:/code/src/config --exclude=C:/code/src/config/generate/master_template\.py
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config --exclude=C:\code\src\config\generate\master_template\.py
Invalid regular expression for exclude

pipenv run black -S C:/code/src/config --exclude='C:/code/src/config/generate/master_template\.py'
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config --exclude="C:/code/src/config/generate/master_template\.py"
reformatted C:\code\src\config\generate\master_template.py

pipenv run black -S C:/code/src/config '--exclude=C:/code/src/config/generate/master_template\.py'
Error: Invalid value for "[SRC]

pipenv run black -S C:/code/src/config --exclude=C:\\code\\src\\config\\generate\\master_template\.py
reformatted C:\code\src\config\generate\master_template.py
```

Side question: In the wiki it says "Exclusions are calculated first, inclusions later."
I presume this means an inclusion trumps an exclusion? Or an inclusion takes priority over an exclusion?

**Comment by zsol** [comment]
I don't have access to a Windows machine for the next week or so, but you should be able to run Black with `-v` to see exclude regexes being applied. That should help debug this. I'm not sure about how including the drive works.

> In the wiki it says "Exclusions are calculated first, inclusions later."
> I presume this means an inclusion trumps an exclusion? Or an inclusion takes priority over an exclusion?

No, it means exclusion trumps an inclusion. Files and directories are only considered if they don't match the exclude regexes, and only then are inclusion regexes consulted

**Comment by michael-angelozzi** [comment]
Thanks for the reply. When I tried running with -v, the only difference I saw in stdout was unchanged files got debug stating:
```
<file path> wasn't modified on disk since last run.
```

> No, it means exclusion trumps an inclusion. Files and directories are only considered if they don't match the exclude regexes, and only then are inclusion regexes consulted

An Included dir sounds the same as the specified source dir, is **--include** just a way of specifying additional source dirs?

**Comment by fiatjaf** [comment]
I've been trying to exclude _anything_ using all possible regex, pyproject.toml, different CLI calls and never got black to exclude anything.

Here's a reproducible example of black not excluding when (I suppose) it should, on Linux:

```
mkdir test
cd test
echo 'print( 23)' > main.py
black --exclude='main.py' *
# reformatted main.py
# All done! ✨ 🍰 ✨
# 1 file reformatted.
```

**Comment by zsol** [comment]
@fiatjaf that's because you're passing in `main.py` on the command line as a file. Black will always format files passed explicitly on the command line. If you want to see `--exclude` have effect, try passing in a directory like `.`: `black --exclude='main\.py' .`

**Comment by fiatjaf** [comment]
Oh, ok, that works. Thank you.

But what I was actually trying to do before was to prevent my Black Vim thing (using Ale) to format some files automatically on-save. I've configured pyproject.toml, but nothing worked. I imagine Ale is calling Black with the file explicitly, so I'm hopeless now.

**Comment by zsol** [comment]
That issue is tracked in #949.
