### ISSUE TITLE
New Release To Fix 2.7

### ISSUE THREAD

**Issue by chebee7i** [psf/black#988]
This is a redux #977 because I had some craziness going on in my paths.

The current release of `black` is 19.3b0 and it has a number of issues that affect 2.x code.  These include:

- https://github.com/psf/black/issues/768: `Cannot parse: 3:19: print('hello', file=sys.stdout)`
- https://github.com/psf/black/issues/752: ugly whitespace `print (something)`

Both issues are pretty terrible for code trying to be 2.x/3.x compatible, and both issues have been fixed in `master`. However, neither are part of a current release.  

Can we get a new release out? If not, could we at least get a bugfix release out (19.3b1) that includes those two fixes?

**Comment by chebee7i** [comment]
Is there anything holding this up?  Or is it just that this project seems to have flatlined?

**Comment by chingc** [comment]
There are plenty of commits each month so the project is still active.  It would be nice to see a new beta release though.

Two workarounds until that happens:
1. Use [pre-commit](https://pre-commit.com/) which will let you specify a branch/tag/commit
1. pip install git+https://github.com/psf/black.git@master

**Comment by chebee7i** [comment]
Yeah, I've seen the commits...I question the priority though, as it seems like getting out a bug fix for a critical regression should be higher priority. 

The minimal response on this and similar issues is, in part, a reason why one might question the overall status of the project.

Bottom line for me is that this release is broken, and the fix is really quite simple given that the commits are already integrated in master. Workarounds are fine but no replacement for fixing the release.

**Comment by JelleZijlstra** [comment]
I agree that it makes sense to get another (pre)release out ASAP, without waiting for other in-flight changes. @ambv @zsol what do you think?

**Comment by hugovk** [comment]
+1 to a new beta (or better).

This (and isort, but there'll be an isort release in a week or two) is also blocking using Black on pip: https://github.com/pypa/pip/pull/7084#issuecomment-535839539.

**Comment by zsol** [comment]
I'm all in favor for more frequent releases in general so: yes 😎

**Comment by ambv** [comment]
OK, let's do a new beta on Thursday. Let's flag what we can finish and merge until then.

**Comment by JelleZijlstra** [comment]
I just tested out current master on our codebase and unfortunately I found two new issues: #1041 and (more serious) #1042. I may have some time later to try to fix them.

**Comment by hugovk** [comment]
Also https://github.com/psf/black/issues/1044 from running master on pip. Possibly duplicates of those two.

**Comment by quasiben** [comment]
It does not seem like black was released on 2 weeks ago.  Is a new release of black dependent on resolving:

- #1041
- #1042
- #1044

**Comment by zsol** [comment]
yes

**Comment by hugovk** [comment]
Black 19.10b0 has just been released, can this be closed?

**Comment by ambv** [comment]
I hope so. @chebee7i, can you confirm the new release fixed things for you?

**Comment by jd** [comment]
Latest version `19.10b0` fixes #752.

**Comment by tommyjcarpenter** [comment]
I am using 19.10b0 and I am still seeing this regression

**Comment by tommyjcarpenter** [comment]
Has this change hit the stable branch? IE, should this behavior be fixed on the latest stable black?
