### ISSUE TITLE
pycharm IDE intergration: breakpoints

### ISSUE THREAD

**Issue by Madoshakalaka** [psf/black#992]
Black is really amazing! I enjoyed using [black as file watcher in Pycharm](https://github.com/psf/black#pycharmintellij-idea) a lot.

Yet a small disappointment is that black does not respect breakpoints in the IDE properly 
## Before formatting

![before-formatting](https://user-images.githubusercontent.com/44753941/63405162-115e7780-c3a3-11e9-8377-1e9e42ebcb7d.png)

## After Formatting

![after-formatting](https://user-images.githubusercontent.com/44753941/63405170-19b6b280-c3a3-11e9-992e-85e2c69fae00.png)

By comparison, IDE built-in code formatting respects the breakpoint and moves the breakpoint around with code.

**Comment by Madoshakalaka** [comment]
I know it maybe not worth implementing. I submitted this feature request because black values IDE integration and provides very helpful docs. I genuinly wish there exits some simple Pycharm api that allows this.

**Comment by Madoshakalaka** [comment]
Oh, There does exist a Pycharm plugin called `black-pycharm` which claims to use `black` as default reformatting. But it's unmaintained for over one year and a half so far. I tried to use it, however it doesn't even seem to use black.

**Comment by JelleZijlstra** [comment]
I'm not sure this is something Black can fix; seems like an issue with the IDE.

**Comment by hauntsaninja** [comment]
As above, this isn't something this project can fix.
