### ISSUE TITLE
Coloured `--diff` output

### ISSUE THREAD

**Issue by selurvedu** [psf/black#994]
There is an option in [diffutils](https://www.gnu.org/software/diffutils/manual/html_node/diff-Options.html):

> **--color [=_when_]**
> 
> Specify whether to use color for distinguishing different contexts, like header, added or removed lines. _when_ may be omitted, or one of:
>  - `none` Do not use color at all. This is the default when no `--color` option is specified.
>  - `auto` Use color only if standard output is a terminal.
>  - `always` Always use color. 
> 
> Specifying `--color` and no _when_ is equivalent to `--color=auto`.

It would be nice if Black had a similar option, probably with a different name.

**Comment by Peque** [comment]
Ugly hack (ideally Black should be able to output with colors out-of-the-box):

```bash
black --diff . | colordiff
```

**Comment by selurvedu** [comment]
@Peque yeah, I used that workaround before.
